### ISSUE TITLE
=RO not working as expected.

### ISSUE THREAD

**Issue by fluxisx55** [trapexit/mergerfs#1000]
**Describe the bug**

I expect I am doing something wrong myself here but this was working then stopped when I updated (I was on 2.21.something prior)

I have 2 nfs shares mounted locally one is readonly (metadata2) one is readwrite (metawrite2)

I am able to write to the (metawrite2) directory fine and that works permission wise

I use the follow fstab entry

/opt/metadata2=RO:/opt/metawrite2 /opt/metamerge2 fuse.mergerfs allow_other,use_ino 0 0

In the root of /opt/metamerge2 if I do mkdir test this works fine but if I go a few directories down and try the same command I get the typical "mkdir: cannot create directory ‘test’: Read-only file system"

root@Ubuntu-1804-bionic-64-minimal /opt/metamerge2/Movies/2/8931a12e069635ad528da3fbf98898f3c570f07.bundle # mkdir test
mkdir: cannot create directory ‘test’: Read-only file system

At this moment /opt/metadata2 holds all the directories/files and /opt/metawrite2 is empty

**Expected behavior**

The expected behavior is if I tried to create a new entry in the bundle directory it would recreate that path in the /opt/metawrite2 directory then create the new file

**System information:**

 - OS, kernel version: Linux Ubuntu-1804-bionic-64-minimal 4.15.0-163-generic
 - mergerfs version: mergerfs version: 2.33.3

**Comment by trapexit** [comment]
You are using create policy epmfs. Have you confirmed that path exists on the other filesystem? If not then it is working as intended. 

Without you providing the information requested in the template and docs I can't comment further.

**Comment by fluxisx55** [comment]
> You are using create policy epmfs. Have you confirmed that path exists on the other filesystem? If not then it is working as intended.
> 
> Without you providing the information requested in the template and docs I can't comment further.

Not sure which other information is needed from the template .. but no the path does not exist on the other filesystem 

Prior when this was working it work create the file path on the writable share

**Comment by trapexit** [comment]
With those same settings? That's not likely. As the docs describe epmfs will not select branches that don't have the base path. That's the whole point of that policy. 

I need All information relevant to the particular behavior. Everything. You chose a policy that behaves based on the existence of paths. No one can tell you what should happen if the input to the behavior isn't provided.

**Comment by trapexit** [comment]
If you want mergerfs to select a branch regardless of where it exists you have to configure it to do so as described in the docs in the policy section.

**Comment by fluxisx55** [comment]
> If you want mergerfs to select a branch regardless of where it exists you have to configure it to do so as described in the docs in the policy section.

Alright I changed the fstab to the following and it does work as expected now.

/opt/metadata2=RO:/opt/metawrite2 /opt/metamerge2 fuse.mergerfs allow_other,use_ino,category.create=mfs 0 0

It did work like this with the old settings I have some of those file paths in my old metawrite directory but might have just been a weird thing with that version.

Thanks for the help.
