### ISSUE TITLE
Mergerfs pool as an External storage in Nextcloud not working

### ISSUE THREAD

**Issue by mikulik86** [trapexit/mergerfs#1001]
**Describe the bug**

When mounting Mergerfs pool as an local external storage in Nextcloud (as described here: https://docs.nextcloud.com/server/22/admin_manual/configuration_files/external_storage/local.html), Nextcloud shows no files.

However, when mounting hard drives them selves ( /mnt/NAS_1 or /mnt/NAS_2 instead of /mnt/NAS ) files are shown.

**Expected behavior**

Nextcloud listing files present in the Mergerfs pool

**System information:**

 - OS, kernel version: 

> Linux Server 5.11.0-43-generic #47~20.04.2-Ubuntu SMP

 - mergerfs version: 

> mergerfs version: 2.33.3

 - mergerfs settings:
 
> /mnt/NAS_1:/mnt/NAS_2 /mnt/NAS fuse.mergerfs allow_other,use_ino,cache.files=partial,dropcacheonclose=true,fsname=mergerfs 0 0

 - List of drives, filesystems, & sizes:

> df: /run/user/1000/doc: Operation not permitted
> Filesystem      Size  Used Avail Use% Mounted on
> udev            7,8G     0  7,8G   0% /dev
> tmpfs           1,6G  3,7M  1,6G   1% /run
> /dev/nvme0n1p5  457G   68G  366G  16% /
> tmpfs           7,8G  1,9M  7,8G   1% /dev/shm
> tmpfs           5,0M  8,0K  5,0M   1% /run/lock
> tmpfs           7,8G     0  7,8G   0% /sys/fs/cgroup
> 1:2             7,2T  3,8T  3,1T  56% /mnt/NAS
> /dev/loop1      9,2M  9,2M     0 100% /snap/canonical-livepatch/119
> /dev/nvme0n1p1  511M  4,0K  511M   1% /boot/efi
> /dev/loop2      100M  100M     0 100% /snap/core/11798
> /dev/sdd1       1,4T  345G  961G  27% /mnt/BACKUP
> /dev/loop3       56M   56M     0 100% /snap/core18/2253
> /dev/sdd2       458G   16K  434G   1% /mnt/Sova
> /dev/sde1       3,6T  3,3T  139G  97% /mnt/parity
> /dev/loop4       56M   56M     0 100% /snap/core18/2246
> /dev/loop5      9,2M  9,2M     0 100% /snap/canonical-livepatch/126
> /dev/loop6       62M   62M     0 100% /snap/core20/1242
> /dev/sda1       3,6T  527G  2,9T  16% /mnt/NAS_2
> /dev/loop0      128K  128K     0 100% /snap/bare/5
> /dev/loop7      100M  100M     0 100% /snap/core/11993
> /dev/loop8       66M   66M     0 100% /snap/gtk-common-themes/1515
> /dev/sdb1       3,6T  3,3T  140G  96% /mnt/NAS_1
> /dev/loop9      219M  219M     0 100% /snap/gnome-3-34-1804/72
> /dev/loop10      44M   44M     0 100% /snap/snapd/14295
> /dev/loop11     9,5M  9,5M     0 100% /snap/htop/3335
> /dev/loop12      66M   66M     0 100% /snap/gtk-common-themes/1519
> /dev/loop13     219M  219M     0 100% /snap/gnome-3-34-1804/77
> /dev/loop14     248M  248M     0 100% /snap/gnome-3-38-2004/87
> /dev/loop15      43M   43M     0 100% /snap/snapd/14066
> /dev/loop16      62M   62M     0 100% /snap/core20/1270
> /dev/loop17      55M   55M     0 100% /snap/snap-store/558
> /dev/loop18      51M   51M     0 100% /snap/snap-store/547
> tmpfs           1,6G   40K  1,6G   1% /run/user/1000
> tmpfs           1,6G  4,0K  1,6G   1% /run/user/998

> loop0         7:0    0     4K  1 loop /snap/bare/5
> loop1         7:1    0     9M  1 loop /snap/canonical-livepatch/119
> loop2         7:2    0  99,5M  1 loop /snap/core/11798
> loop3         7:3    0  55,5M  1 loop /snap/core18/2253
> loop4         7:4    0  55,5M  1 loop /snap/core18/2246
> loop5         7:5    0     9M  1 loop /snap/canonical-livepatch/126
> loop6         7:6    0  61,9M  1 loop /snap/core20/1242
> loop7         7:7    0  99,4M  1 loop /snap/core/11993
> loop8         7:8    0  65,1M  1 loop /snap/gtk-common-themes/1515
> loop9         7:9    0   219M  1 loop /snap/gnome-3-34-1804/72
> loop10        7:10   0  43,3M  1 loop /snap/snapd/14295
> loop11        7:11   0   9,5M  1 loop /snap/htop/3335
> loop12        7:12   0  65,2M  1 loop /snap/gtk-common-themes/1519
> loop13        7:13   0   219M  1 loop /snap/gnome-3-34-1804/77
> loop14        7:14   0 247,9M  1 loop /snap/gnome-3-38-2004/87
> loop15        7:15   0  42,2M  1 loop /snap/snapd/14066
> loop16        7:16   0  61,9M  1 loop /snap/core20/1270
> loop17        7:17   0  54,2M  1 loop /snap/snap-store/558
> loop18        7:18   0    51M  1 loop /snap/snap-store/547
> sda           8:0    0   3,7T  0 disk 
> └─sda1        8:1    0   3,7T  0 part /mnt/NAS_2
> sdb           8:16   0   3,7T  0 disk 
> └─sdb1        8:17   0   3,7T  0 part /mnt/NAS_1
> sdc           8:32   0   1,8T  0 disk 
> └─sdc1        8:33   0   1,8T  0 part 
> sdd           8:48   0   1,8T  0 disk 
> ├─sdd1        8:49   0   1,4T  0 part /run/timeshift/backup
> └─sdd2        8:50   0 465,7G  0 part /mnt/Sova
> sde           8:64   0   3,7T  0 disk 
> └─sde1        8:65   0   3,7T  0 part /mnt/parity
> nvme0n1     259:0    0 465,8G  0 disk 
> ├─nvme0n1p1 259:1    0   512M  0 part /boot/efi
> ├─nvme0n1p2 259:2    0     1K  0 part 
> └─nvme0n1p5 259:3    0 465,3G  0 part /

**Comment by trapexit** [comment]
My guess is it is an issue with Nextcloud. I see no evidence of it receiving errors when querying a mergerfs mount path nor it even attempting to query it for a file listing.

Have you tried asking Nextcloud folks? Or tried using another FUSE based filesystem? I'll try sshfs in a bit.

**Comment by mikulik86** [comment]
No, I haven't yet asked Nextcloud folks nor tried using another FUSE based filesystem.

**Comment by trapexit** [comment]
Try setting `inodecalc=hybrid-hash32`

**Comment by mikulik86** [comment]
> Try setting `inodecalc=hybrid-hash32`

No difference.

**Comment by trapexit** [comment]
This is almost certainly a Nextcloud problem. If I point to anything within the mount point it works fine. It's just the root of the mount that fails.

**Comment by mikulik86** [comment]
You are right, anything but root works.

Would you like to investigate it more, or should I open an issue by Nextcloud?

**Comment by trapexit** [comment]
I don't know enough about Nextcloud to be useful without additional context. You should open a ticket with nextcloud.

**Comment by mikulik86** [comment]
All right. Thanks for your help and above all for your great work on mergerfs.
