### ISSUE TITLE
Handling Disk Disconnects?

### ISSUE THREAD

**Issue by obsidience** [trapexit/mergerfs#1011]
Hi everyone, I have mergerfs running on a Raspberry PI talking to a USB enclosure.  There are times where I have to turn the enclosure off but keep the server active (and there's also time where it's unexpected).  Outside of confirming that the disks remount correctly, are there any considerations on the mergerfs side to ensure that the merged mount point works correctly?  I seem to be running into an issue sometimes where things don't come back all the way and the only solution appears to be a reboot.  I'd prefer to write a bash script to restart any necessary services such as plex and samba.  

Thanks for your help!

**Comment by trapexit** [comment]
mergerfs itself should handle the appearance and disappearance branches just fine. I can't speak for software using the filesystem and how it may respond.

**Comment by obsidience** [comment]
Awesome, thank you and closed!
