### ISSUE TITLE
Is it safe to mount at same path as one of my drives?

### ISSUE THREAD

**Issue by 07416** [trapexit/mergerfs#1012]
For instance as follows:

    /mnt/media:/mnt/media2 /mnt/media

One of my drives is already mounted under `/mnt/media` — I'd like also the mergerfs mount be located there.

**Comment by trapexit** [comment]
No, it's not. It's a deadlock situation because you've created an infinite loop.

Why not just use a different location?

**Comment by 07416** [comment]
> No, it's not. It's a deadlock situation because you've created an infinite loop.
> 
> Why not just use a different location?

Absolutely will now, thank you for confirming!
