### ISSUE TITLE
fuse: unknown option `cache.files=partial'

### ISSUE THREAD

**Issue by lettore** [trapexit/mergerfs#1014]
**Describe the bug**
On Raspbian armhf trying to mount with cache.files=partial return error fuse: unknown option `cache.files=partial'.
Mergerfs installed with apt install mergerfs, it's possible that raspberry repository have an old version of mergerfs? There are other repository where download the most recent version?

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/releases

**Comment by trapexit** [comment]
Debian based distros are *always* out of date. It isn't a rolling release distro.

**Comment by lettore** [comment]
Thank you resolved
