### ISSUE TITLE
hd-idle and mergerfs

### ISSUE THREAD

**Issue by rajil** [trapexit/mergerfs#1017]
I am running [hd-idle ](https://github.com/adelolmo/hd-idle) on disks combined using mergerfs. I have made sure that no service should be accessing the disks. However, still hd-idle is unable to make the disk go to sleep.

My mergerfs config looks like so,

```
/mnt/media*:/home/user/stuff/othervideos  /mnt/Media  mergerfs defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,category.create=epmfs,dropcacheonclose=true,minfreespace=100G,fsname=MergerFS 0 0
```

hd-idle config looks like so,

```
HD_IDLE_OPTS="  -i 60 -d -l /var/log/hd-idle.log"
```

hd-idle shows,
```
Feb 28 11:00:59 nas hd-idle[825773]: disk=sdl command=scsi spunDown=false reads=465718501 writes=22827224 idleTime=60 idleDuration=0 spindown=0001-01-01T00:00:00 spinup=2022-02-28T10:53:59 lastIO=2022-02-28T11:00:59
```
Any idea why the disk does not got to sleep when using mergerfs?

**Comment by trapexit** [comment]
Are you positive nothing is accessing the mount? mergerfs doesn't actively access anything. It only responds when requested.

**Comment by trapexit** [comment]
You can strace mergerfs to see what is going on.
