### ISSUE TITLE
Keep related files together on the same physical drive?

### ISSUE THREAD

**Issue by hugepants** [trapexit/mergerfs#102]
Thanks for making this useful tool.

I use Kodi (in OpenELEC) so I intend to use mergerfs with the options `category.search=newest` for fasthash scanning and `defaults` for best performance.

Example structure of my files on [physical drives]:

[drive1]
`/movies/movie1`
`/movies/movie1/movie.mkv`
`/movies/movie1/movie.jpg`
`/movies/movie1/movie.sub`

`/movies/movie2`
`/movies/movie2/movie.mkv`
`/movies/movie2/movie.jpg`
`/movies/movie2/movie.sub`

[drive2]
`/movies/movie200`
`/movies/movie200/movie.mkv`
`/movies/movie200/movie.jpg`

If I later add a subtitle file to the pool for movie200 named movie.sub, is there a way to ensure that this file is stored on the same physical drive for movie200 alongside its movie.mkv and movie.jpg (i.e. [drive2]), if there is available space for it?

In mhddfs, if there is space available in [drive1], it will store the movie.sub file in [drive1] `/movies/movie200/movie.sub`, but I would prefer for it to be stored in [drive2] alongside the other files for movie200.

Thanks

**Comment by trapexit** [comment]
That should be the default behavior. `epmfs` (existing path, most free space) policy for the `create` category is that.

**Comment by rubylaser** [comment]
This is not working as designed.  I was super excited about mergerfs when I was told about it, but the create mode, even with epmfs set as the default option, seems to always write to the disk with the most free space.  Here's what it looks like here.

```bash
# Find all disks that contain a movie
root@fileserver:/mnt/data# find . -name "Movie Name" -type d

# Only exists on one disk
./HIT-MJ0351YNG7XK9A/videos/Movie Name

# Let's create a subtitle file to my mergerfs pool
root@fileserver:/mnt/data# touch /storage/videos/Movie\ Name/subtitles.sub

# The file should be on disk HIT-MJ0351YNG7XK9A, but it's not
# mergerfs has created a directory on the disk with the most free space and added the file there...
root@fileserver:/mnt/data# find . -name "Movie Name" -type d
./HGST-PL2331LAG9056J/videos/Movie Name
./HIT-MJ0351YNG7XK9A/videos/Movie Name

# Verify that the file is in the new directory on the other disk
root@fileserver:/mnt/data# ls HGST-PL2331LAG9056J/videos/Movie\ Name/
subtitles.sub
```

It is not adding new files to the existing directories, but instead is creating a new folder on the disk with the most free space and adding it there.  Please let me know if there is something I can do to correct this behavior. Thanks!
