### ISSUE TITLE
Mergerfs is still able to edit files on a read-only filesystem

### ISSUE THREAD

**Issue by DUOLabs333** [trapexit/mergerfs#1027]
**Describe the bug**
I specify that a file system should be RO. However, mergerfs can still make changes to files on that system (though any new files and folders are created on the RW folder)

The master branch is **not** to be considered production ready. Feel free to file bug reports but do so indicating clearly that you are testing unreleased code.

**To Reproduce**
1. Make a folder `diff/home/<user>`
2. Make a folder `merged`
3. `sudo mergerfs -o suid,allow_other,dev /=RO:diff=RW merged`
4. `vim <some file in home directory>`
5. See that you can save, and it'll show up in you actual home directory

**Expected behavior**
File will fail to be changed.

**System information:**

 - OS, kernel version: `uname -a` `Linux system 5.16.9-1-aarch64-ARCH #1 SMP Sun Feb 13 17:50:53 UTC 2022 aarch64 GNU/Linux`
 - mergerfs version: `mergerfs -V` `mergerfs version: 2.33.4`
 - mergerfs settings
 - List of drives, filesystems, & sizes:
   - `df -h`
   - `lsblk -f`
 - A strace of the application having a problem: 
   - `strace -fvTtt -s 256 -o /tmp/app.strace.txt <cmd>`
   - `strace -fvTtt -s 256 -o /tmp/app.strace.txt -p <appPID>`
 - strace of mergerfs while app tried to do it's thing:
   - `strace -fvTtt -s 256 -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Additional context**
`unionfs` has the opposite problem -- I can't make any new folders or files (though I can't edit any existing files)

**Comment by trapexit** [comment]
You are misunderstanding the purpose and function of branch modes.

https://github.com/trapexit/mergerfs#filtering

mergerfs and unionfs have fundamentally different behaviors. In most situations they are not alternatives to one another. As the docs point out mergerfs is *not* an overlay filesystem. unionfs is.

It would help if you explained what you're trying to do.
