### ISSUE TITLE
Slow read speeds over mergerfs+smb

### ISSUE THREAD

**Issue by GrayXu** [trapexit/mergerfs#1029]
Slow read speeds over mergerfs+smb (only about 30% speeds)

It works great when local read/write or remote writes on them.

OS: Ubunut 21.04

my mergerfs config: `defaults,allow_other,use_ino,minfreespace=5G,fuse_msg_size=256,func.getattr=newest,nonempty,ignorepponrename=true`

smb config:  
```
min receivefile size = 16384
write cache size = 524288
getwd cache = yes
socket options = TCP_NODELAY IPTOS_LOWDELAY
read raw = yes
write raw = yes
```

I found [a similar question on OMV forum](https://forum.openmediavault.org/index.php?thread/28454-mergerfs-smb-ftp-slow-read-speeds-good-write-speeds/#post307383). I tried to use `iostat` to track when reads over smb. and the rareq-sz is around 128 like him. But
```
$ uname -r
5.11.0-49-generic
```
my kernel version is way newer than 4.20...

Thanks!

**Comment by trapexit** [comment]
Have you traced the client app, or mergerfs, to see what the read sizes are?

**Comment by trapexit** [comment]
Can you please run tests as described in the docs and traces? iostat is not an appropriate tool here. That measures block devices. mergerfs is a filesystem. Using `dd` will give you full control over the type of reads done.

There is no point in setting fuse_msg_size as it defaults to the max supported.

**Comment by GrayXu** [comment]
> Can you please run tests as described in the docs and traces? iostat is not an appropriate tool here. That measures block devices. mergerfs is a filesystem. Using `dd` will give you full control over the type of reads done.
> 
> There is no point in setting fuse_msg_size as it defaults to the max supported.

Thanks for your reply!

I tried `dd if=/path_to_big_file of=/dev/null bs=1M count=1024 iflag=nocache conv=fdatasync status=progress`.  
When the read target is on local mergerfs, it returns about ~170MB/s.
When the read target is on CIFS mounted pointed by `mount -t cifs //localhost/share /mnt/tmp -o guest`, the speed is only ~60MB/S. Just like on windows remote samba client.  
(note: I changed the content of the read target to prevent read cache interference.)

Since localhost ensures no network bottleneck, I thought maybe there was some mismatch between mergerfs and samba?

**Comment by GrayXu** [comment]
After I added `cache.files=off,dropcacheonclose=true` to mergerfs mount options, the `dd` read throughput over mergerfs+samba went up to ~100MB/s, which is quite faster, but still slower than directly read from disk.

**Comment by GrayXu** [comment]
But still confused about why page cache in mergerfs will decrease read performance over samba.🥲

**Comment by trapexit** [comment]
It's not the page cache *in* mergerfs. It is the FUSE page cache. All mergerfs can do is enable or disable on a file level. And as mentioned in the docs there are some behavioral changes by the kernel when enabled. If you provided me with traces as requested I could perhaps answer your question.
