### ISSUE TITLE
Feature request: SSD cache

### ISSUE THREAD

**Issue by cowai** [trapexit/mergerfs#103]
Hi,
First I would like to say thanks for this awesome software. I am getting better speeds with Mergerfs than with mhddfs and it seems more stable too. Really awesome work.

I am not sure what the max throughput for fuse is, but it would be awesome to have ssd cache as a feature. Lets say I put in a 128GB ssd into my nas. Having new files be written to a ssd first, and then after some time when the computre is idle, move the file to the physical pool.

A version 2 could be to have the most used files under a certain size to the ssd permanantly for great access/read speeds as well.

What do you think? Is this much work?

**Comment by trapexit** [comment]
That's a very different behavior from what it currently offers in regard to the moving of data. OSX and Windows AFAIK support this transparently. I've never used it but I believe [bcache](http://bcache.evilpiepirate.org) works similar to what you want but at the block level.

**Comment by cowai** [comment]
I have looked into bcache but as far as I know I would need to have a separate bcache partition for each drive in my pool. Which means I need to have a large SSD. I realize that this is a little out of scope, but you can't deny it would be quite nice ;)

One other great benefit of this would be to offload random writes. So that the physical drives could sleep more and not be stressed with small writes all the time.

**Comment by trapexit** [comment]
Hard to say what kind of performance increase you'd get unless you're running in a sync mode. At least in short bursts. It gets a lot more complicated when you account for the fact that the ssd could fill up before being flushed and you'd need to hard block or accept the risk. Neither is very nice. I'll think about how it could be done but I'm feeling like that kind of thing should be it's own project.

**Comment by cowai** [comment]
Check out this https://github.com/cconstantine/CacheFS. It is very alpha and really slow. But it tried to do this idea.

I have also recently learned that bcache can share one cache device with multiple backing devices. Which means I could convert all my drives to bcache backing devices and install an ssd.

Having it inside mergerfs could have some benefits though. Using bcache while keeping data is risky, you need to use third party scripts to accomplish it.

About your network cache idea, I think it sounds great. It could maybe be tie into fuse apis? So that it works with all fuse filesystems?

**Comment by trapexit** [comment]
It likely be better to be it's own FS and use it in combination with mergerfs or anything else.

Mount tmpfs or ssd. Set the cache to that and the destination to a slower drive (spinning disk or network fs).

**Comment by cowai** [comment]
Coulnt I try to set mergerfs to fwfs and have big ssd at the first disk in the pool, and have some kind of script to move idle files to one of the other disks in the background?

**Comment by trapexit** [comment]
Yeah. That would work similarly though obviously manual. I do this pretty regularly with rsync to re-balance.

**Comment by cowai** [comment]
#!/bin/bash
set -e
function getCacheDrive() {
	#$1 is the pool. Like /mergerfsVol_with_fwfs
	echo $(xattr -l "$1"/.mergerfs|grep srcmounts|cut -d" " -f2|cut -d":" -f1)
}

function getDriveWithMostFreeSpace() {
	#$1 is the pool. Like /mergerfsVol_with_fwfs
	pool="$1"
	free=0
	
	drives=$(xattr -l "$pool"/.mergerfs|grep srcmounts|cut -d" " -f2| sed 's/:/\n/g')
	while read drive;do
		if [[ $(xattr -l "$pool"/.mergerfs|grep srcmounts|cut -d" " -f2|cut -d":" -f1) == $drive ]];then
			continue;
		fi
		currentFree=$(df -k "$drive"|awk '/[0-9]%/{print $(NF-2)}')
		
		if [[ $currentFree -gt $free ]];then
			mostFreeDrive="$drive"
			free=$currentFree
		fi	
	done <<<"$drives"
	echo $mostFreeDrive
}

function moveIdleFilesInPath() {
	oldpwd=$PWD
	pool="$1"
	sourceFolder="$2"
	if [[ -z $3 ]]; then
		targetFolderSet=0
	else
		targetFolderSet=1
		$targetFolder="$3"
	fi
	
	cd "$sourceFolder" && find . -type f -mmin +60 -print0 | while read -d "" path;do
		lsof $path &> /dev/null && continue # move along if the file is in use
		filesize=$(du -k "$path"|awk '{print $1}')

		if [[ $targetFolderSet -eq 0 ]]; then
			targetFolder=$(getDriveWithMostFreeSpace "$pool")
		fi

		freeSpaceOnTarget=$(df -k "$targetFolder"|awk '/[0-9]%/{print $(NF-2)}')

		if [[ $filesize -lt $freeSpaceOnTarget ]];then
			rsync -n --remove-source-files -vRa "$path" "$targetFolder"/
		else
			echo "Not enough space."
			cd $oldpwd && exit 1
		fi
	done
	cd $oldpwd
};
pool="/md"
cacheDrive="$(getCacheDrive "$pool")"
moveIdleFilesInPath "$pool" "$cacheDrive"

# A quick and dirty script to move files from one folder to another. As default it moves it to the disk with the most space. But it can be overrided as a third parameter for moveIdleFilesInpath.

**Comment by lonix** [comment]
unRAID does this in a decent fasion, basicly how it works is, one force all write to cache, then moves from cache to user0 at preset interval.

This meaning the following mounts exists:
+ */mnt/cache*
+ */mnt/user0* (A pool of all array drives)
+ */mnt/user*  a pool consisting of /mnt/cache and /mnt/user0 This is the mount that is presented to shares.

So what i want from this is the ability to set something like "Prefer disk x" Then we would be able to replicate behavior.

**Comment by WildPenquin** [comment]
> I have looked into bcache but as far as I know I would need to have a separate bcache partition for each drive in my pool. 
This is incorrect - bcache can cache any number of backing devices with a single caching device.

I still think this feature would be (kind of) nice - athough I prefer the block device approach for my current setup, I can see uses for this...

**Comment by trapexit** [comment]
The amount of changes necessary to properly do such a thing for such an unlikely use case for most users isn't worth it. I don't believe speed of the underlying device is really the problem when using mergerfs in it's generally intended use case.

This behavior can be simulated out of band and could probably be thrown together without too much effort. However, I have other, more generally useful mergerfs-tools to work on in the near term but I can add an issue for it.
