### ISSUE TITLE
Broken Thumbnails on Fedora KDE

### ISSUE THREAD

**Issue by Lukas-Habring** [trapexit/mergerfs#1030]
**Description**

Dolphin (KDEs default file manager) doesn't show thumbnails for folders within a mergerfs mount.
When I access the branches individually, everything works fine.

**To Reproduce**

1) Install a fresh Fedora 35 KDE. You can of cause also use an existing installation. Installing it freshly is just the fail-safe way.
2) Use "dd if=/dev/zero of=test bs=1M count=1k" to create a new empty file.
3) Format it with a filesystem e.g. with "mkfs.ext4 test". (I tried it with ext4 and btrfs.)
3) Create a new directory inside the volume and move a photo into it.
4) use "mergerfs -o allow_other test <mount-dir>"
5) Open dolphin and look at the folder. It shows a thumbnail when you access the branch directly, but it doesn't show a thumbnail when you look at it through mergerfs.

**Expected behavior**

Dolphin should show thumbnails for every folder that has at least one file in it (assuming that this file has a thumbnail).

**System information:**

 - OS, kernel version: Fedora 35 KDE x64, Kernel 5.16
 - mergerfs version: 2.33.4
 - mergerfs settings: -o allow_other
 - List of drives, filesystems, & sizes: <not-relevant> (tried multiple)
 - strace:
I tried that, but it uses at least some megabytes of space, even if a just use it for 1 second.
I would need to check these files manually for sensitive information (passwords etc.) which is too much effort.

**Comment by trapexit** [comment]
Some file managers won't do thumbnails on "remote" filesystems or FUSE filesystems. Are you positive this isn't a Dolphin issue?

**Comment by Lukas-Habring** [comment]
Thanks for answering.
I'm pretty sure, yes, because thumbnails for files are working correctly most of the time.
Just to be sure, I turned my settings for previews of remote filesystems to the maximum of 9999999MiB.
Sometimes, thumbnails of files are disappearing immediately after they have been created and reappear again when you mouse-over them.
I'm expecting that fixing the issue above will also fix these glitches with file-thumbnails.
I didn't include that behavior in my bug report above, because it's hard to reproduce it.
But directory thumbnails are always broken.

**Comment by trapexit** [comment]
Nemo on my Linux Mint system works just fine. But if I use a remote mount (via gvfs) it doesn't work. But sshfs works fine. I just installed dolphin and it shows me thumbnails just fine on both the original filesystem, mergerfs mount, and sshfs.

Can you try sshfs to see if that gives you the same issue. I can't think of anything mergerfs is doing that would independently impact thumbnails and nothing else.

```
mergerfs -f -o use_ino,allow_other /tmp/fs /tmp/mergerfs
```

That's all I did.

**Comment by Lukas-Habring** [comment]
I tried to reproduce your testing experience.
You wrote that you are using a Linux Mint with Nemo file manager, therefore I assumed that you have the Cinnamon variant of Linux Mint.
So I downloaded Linux Mint 20.3 Cinnamon x64, copied it to a memorystick via dd and booted into the live system.
Then I installed the Ubuntu Focal deb-package of mergerfs 2.33.4.
I installed dolphin via apt (version 4:19.12.3-0ubuntu1).
Result: You are right, thumbnails work correctly.
Then I added the following repository to apt (Ubuntu 21.04): deb http://archive.ubuntu.com/ubuntu hirsute main restricted universe multiverse
This allowed me to install a newer dolphin version, namely 4:20.12.3-0ubuntu1.
At first start, dolphin shows an error with dbus and kio.file. I had this error before (in other contexts). I just executed "dbus-launch dolphin" once on the commandline and the error is gone.
Turns out: Dolphin 4:20.12.3-0ubuntu1 also shows thumbnails correctly.
Same game again with Impish (Ubuntu 21.10) repo and dolphin version 4:21.08.1-1ubuntu1, same result.
And again with Jammy (Ubuntu 22.04) Repo and dolphin version 4:21.12.3-0ubuntu1.
Turns out: You were right the whole time, it is indeed a dolphin issue. (I have dolphin version 21.12.2.1 on my fedora btw..)

Thanks for your input, that was quite helpful for me.

**Comment by trapexit** [comment]
No problem. Glad we resolved it. This has been a problem for people for years across numerous file managers and filesystems / remote access. I think zero times has the file manager provided any meaningful feedback as to why it behaved differently. Sometimes 'remote' just means a mount source with : in it.
