### ISSUE TITLE
Question about the most free disk feature

### ISSUE THREAD

**Issue by cowai** [trapexit/mergerfs#104]
When I run "touch /mergerfs/tmp/testfile", the file "/mergerfs/tmp/testfile" is created in a the first drive listed in fstab and not the one with the most space. But when I run "mkdir /mergerfs/tmp" the folder tmp is created in the drive with the most space.
Is this the intended behaviour or did I notice a bug?

**Comment by rubylaser** [comment]
I'm seeing the same behavior.  My create mode is epmfs, but if I make a directory on an underlying disk that doesn't have the most free space, and then try to write to the pool, mergerfs creates the directory on the disk with the most free space and then writes to it.

**Comment by cowai** [comment]
I should have stated that I also have epmfs. I have not changed it from the default.
@rubylaser Can you confirm that the disk that it uses is before the disk you created the folder in? I mean before as in alphabetically in the fstab mount point. In my case the first disk that has enough free space is used. It doesnt care if I create a folder on the disk with most space available. It will create files on the first disk regardless.

@trapexit Do you have any idea why this is happening?

**Comment by rubylaser** [comment]
Hello Ari,

It does not seem to be related to alphabetical order on my system.  It always writes to the disk with the most free space.  In my case /mnt/data/HGST-PL2331LAG9056J.  It is a basically empty 4TB disk.  All of the rest of my disks are fairly full right now, or have less than 2.3TB available on them.

Thanks!


--
Zack Reed
reed.zack@gmail.com [mailto:reed.zack@gmail.com]
http://zackreed.me [http://zackreed.me/]
// Rubylaser - Design & Coding
On 8/24/2015 2:36:19 PM, Ari <notifications@github.com> wrote:
I should have stated that I also have epmfs. I have not changed it from the default.
@rubylaser [https://github.com/rubylaser] Can you confirm that the disk that it uses is before the disk you created the folder in? I mean before as in alphabetically in the fstab mount point. In my case the first disk that has enough free space is used. It doesnt care if I create a folder on the disk with most space available. It will create files on the first disk regardless.
@trapexit [https://github.com/trapexit] Do you have any idea why this is happening?

**Comment by rubylaser** [comment]
It does not seem to be related to alphabetical order on my system.  It always writes to the disk with the most free space.  In my case /mnt/data/HGST-PL2331LAG9056J.  It is a basically empty 4TB disk.  All of the rest of my disks are fairly full right now, or have less than 2.3TB available on them.

This illustrates the issue.

```bash
# Find all disks that contain a movie
root@fileserver:/mnt/data# find . -name "Movie Name" -type d

# Only exists on one disk
./HIT-MJ0351YNG7XK9A/videos/Movie Name

# Let's create a subtitle file to my mergerfs pool
root@fileserver:/mnt/data# touch /storage/videos/Movie\ Name/subtitles.sub

# The file should be on disk HIT-MJ0351YNG7XK9A, but it's not
# mergerfs has created a directory on the disk with the most free space and added the file there...
root@fileserver:/mnt/data# find . -name "Movie Name" -type d
./HGST-PL2331LAG9056J/videos/Movie Name
./HIT-MJ0351YNG7XK9A/videos/Movie Name

# Verify that the file is in the new directory on the other disk
root@fileserver:/mnt/data# ls HGST-PL2331LAG9056J/videos/Movie\ Name/
subtitles.sub
```

**Comment by cowai** [comment]
```shell
root@nas:/mnt/snap/disks# df -h|egrep '/mnt|merge'
/dev/sda1                                                                                   1.8T  1.7T   98G  95% /mnt/snap/disks/wd-WD-WMAZA1856674
/dev/sdb1                                                                                   2.7T  2.3T  292G  89% /mnt/snap/disks/toshiba-X3L856LGS
/dev/sdc1                                                                                   2.7T  2.6T  3.4G 100% /mnt/snap/disks/toshiba-X3L854YGS
/dev/sdd1                                                                                   2.7T  2.4T  359G  87% /mnt/snap/disks/toshiba-9312RXXKS
/dev/sde1                                                                                   2.7T  2.0T  627G  76% /mnt/snap/disks/toshiba-6430VL7GS
/dev/sdf1                                                                                   2.7T  2.7T     0 100% /mnt/snap/disks/p1-toshiba-X3L853LGS
wd-WD-WMAZA1856674:toshiba-9312RXXKS:toshiba-X3L856LGS:toshiba-X3L854YGS:toshiba-6430VL7GS   13T   11T  1.4T  89% /md_mergerfs

root@nas:~# rm -r /md_mergerfs/tmp

root@nas:~# mkdir /md_mergerfs/tmp

root@nas:~# find /mnt/snap/disks -maxdepth 2 -type d -name "tmp"
/mnt/snap/disks/toshiba-6430VL7GS/tmp
# This is actually the disk with most free space. Now lets check if it creates a file here as well..

root@nas:~# touch /md_mergerfs/tmp/testfile

root@nas:~# find /mnt/snap/disks -maxdepth 3 -type f -name "testfile"
/mnt/snap/disks/wd-WD-WMAZA1856674/tmp/testfile
# As we see here it actually ignored the created tmp folder inside toshiba-6430VL7GS and created the file to wd-WD-WMAZA1856674 which didn't have the folder tmp. It seems for me that wd-WD-WMAZA1856674 is chosen because it fullfills minfreespace (4GB).

**Comment by rubylaser** [comment]
That is very odd.  Hopefully @trapexit can figure this out.  I like the speed and the fact that this is updated, but the accuracy of the write policies are paramount for me to avoid having files sprinkled over all of my disks.

In reality, for my media server, I like the way mhddfs works the best, in that it writes to one disk until it's completely full then moves onto the next.  I like the option of create modes like AUFS, but I've always wished the default mode of mhddfs was another option.

**Comment by trapexit** [comment]
Found a bug with that from after a recent refactor. I'll push a new release with the fix shortly.

**Comment by rubylaser** [comment]
@trapexit . Awesome!  Thanks for the super speedy response.  I hope this fixes the behavior.

**Comment by cowai** [comment]
@trapexit Wow that was fast. Thank you for this awesome software :)
