### ISSUE TITLE
The system hang when  configure the merged directory  as a member of origin set directory

### ISSUE THREAD

**Issue by ditanexp** [trapexit/mergerfs#1040]
**Describe the bug**

when i do merge  like below，the system hangs， I can 't  use “cd ”  without reboot：
`mergerfs  -o allow_other,use_ino /old:/new /old`

I'm not sure if it's bug or  freature，but this is very dangrous when do merger in production environment

**Comment by trapexit** [comment]
There is no need to reboot. Simply kill the process or abort the filesystem.

And yes, it's a known behavior. You've created an infinite loop and therefore deadlock. 

What would you have it do? Abort? There isn't a great way to manage this as anyone could create levels of indirection which would lead to it reaching back around to itself. Via bind mounts or other union filesystems.

**Comment by ditanexp** [comment]
I‘ve tried to kill the process，use：
`ps -ef|grep merger|grep -v grep|awk '{print $2}'|xargs kill -9`
but it still not work  ，i notice that the mergerfs process become <defunct> ，so i have to reboot
-------------------------------------------------------------------------------------------
anyway，when i config megerfs correctly，it works very fine ，that help me alot.
I  do a  datacenter/database maintenance job , It’s very often to extend a filesystem when demand.
Usually，we have three ways：
1.Do  a extention with the origin SAN storage lun ,then redo format and mkfs to the lun, that’s very high risk operation
2.Deploy a new lun to replace origin lun，but we have to backup and migration，it takes a lot time and  cause service interruption 
3.Depoly a new lun to the Host（VM）If the filesystem with lvm managed ，then use lvextend extend the  logicalvolume 
，the  online lvextend may still cause data loss when do wrong operate （e.g：do lvextend without esize2fs/xfs_growfs）

In my case, I want find a solusion to extend filesystem safely 、smoothly and less/ none-interrupt ，mergerfs is really a googd choice.I plan to do more tests before  production implement.  Thanks.
