### ISSUE TITLE
Seeking clarification on syntax to use for branch-specific options

### ISSUE THREAD

**Issue by codeclem** [trapexit/mergerfs#1043]
I'm trying to set minfreespace on individual branches, but fuse is unable to parse them. For example, in fstab I have:

```
/disk1=RW,1490G:/disk2=RW,1490G:/main_12a=RW,2235G:/main_14a=RW,2607G /mergerfs fuse.mergerfs use_ino,dropcacheonclose=true,allow_other,category.create=mfs 0 0
```

and I get ``fuse: unknown option `1490G:disk2=RW'`` I've tried using quotes in different ways but can't get it working. Could you provide a more complete and explicit example on how to do this? Thanks so much.

**Comment by trapexit** [comment]
Are you sure you're using a current version of the software? The example at https://github.com/trapexit/mergerfs#branches is complete. It's literally just that.

**Comment by codeclem** [comment]
Ah! Didn't realise how old Ubuntu's package was. All good after updating, thanks!

**Comment by trapexit** [comment]
Yeah. Debian is not a rolling release distro. Unless there are major bugs in software they don't update. This is why I mention in the issue template and docs to ensure you're using updated versions.

https://github.com/trapexit/mergerfs#support
https://github.com/trapexit/mergerfs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
