### ISSUE TITLE
How to set disk quota?

### ISSUE THREAD

**Issue by oreak** [trapexit/mergerfs#1049]
I know that the underlying file system can be set, but after using mergefs, how to set it?

**Comment by oreak** [comment]
> I'm not sure I understand what you're asking. The quota is enforced by the underlying filesystem. There is nothing else to do. mergerfs doesn't interact with quotas nor really could it in a material way AFAIK.

However, after the two hard disks are merged, they are in the same directory. How to limit the quota of this merged directory? Is it a separate quota on the underlying file system?

**Comment by trapexit** [comment]
mergerfs as I mentioned above and suggested by lack of discussion in the docs does not in any way interact with quotas. It's not all that practical to do so. It would have to constantly query the underlying filesystems and add them all up every call. mergerfs doesn't keep track of filesystem contents like that.
