### ISSUE TITLE
tooling to rebalance files

### ISSUE THREAD

**Issue by rubylaser** [trapexit/mergerfs#105]
This may be out of the scope of this fine piece of software, but one common thing I could see the benefit of is the ability re-balance files/folders as disks have been added over time.  For example, let's say I originally have a couple disks with TV Shows on them, but they are full.  Later, I add a 6TB disk, it would be nice to consolidate (move those files) all onto the 6TB disk.  This would be nice, because only one disk would need to be spun up to watch all of my TV Shows as opposed to potentially many if files have been sprinkled across many disks over time.

Just an idea (maybe even a stupid idea), but I thought I'd suggest it.  Thanks!

**Comment by trapexit** [comment]
I've wanted to work on something like that but I think it should probably be out of band. A tool which could re-balance between directories/drives rather than done through mergerfs. There is little reason AFAICT to do it in the main project.

**Comment by trapexit** [comment]
Before I work on nice to have tooling like that I really need to build a test framework.

**Comment by rubylaser** [comment]
Good idea.  I would agree that this does seem to be outside of the core of mergerfs.  I do like the Linux concept of doing one thing, but doing it really well.

**Comment by jkaberg** [comment]
I'll just leave a +1 for this, quite useful when merging several (older) disks

**Comment by trapexit** [comment]
moved: https://github.com/trapexit/mergerfs-tools/issues/3
