### ISSUE TITLE
Transport Endpoint Not Connected

### ISSUE THREAD

**Issue by polyboi** [trapexit/mergerfs#1050]
### Discussed in https://github.com/trapexit/mergerfs/discussions/1048

<div type='discussions-op-text'>

<sup>Originally posted by **polyboi** July  5, 2022</sup>
I'm getting the exact same behaviour described in the readme where libfuse or mergerfs are crashing when interacting with the mount and I get an error message stating "transport endpoint not connected". The only problem is that I'm already on a higher versions of both mergerfs and libfuse. I was originally trying this on Ubuntu 18.04 but did a clean install of 22.04 hoping it would fix it but I'm still getting the same issues. I built mergerfs from source and I'm trying to mount the pool with these options...

allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.create=eepfrd

Any help would be greatly appreciated.</div>

**Comment by polyboi** [comment]
I have tried multiple different versions of ubuntu server, both compiling the deb from source myself and using the pre-compiled dev but any way I set this up, I always seem to run in to the same issue.

**Comment by trapexit** [comment]
Please provide the details requested in the template / support section of the docs.

The version of libfuse is not relevant. mergerfs doesn't use the system libfuse.

**Comment by polyboi** [comment]
Looks like I had a typo in my create policy. I'm just checking now but I think that it's likely my issue.

**Comment by trapexit** [comment]
It shouldn't even start with invalid arguments. Let me look.

**Comment by trapexit** [comment]
I seem to have broken detection of invalid policies a while back but it shouldn't cause a crash. It should just be the default.

**Comment by trapexit** [comment]
Looks like there is some bug somewhere with the conversion between strings and internal objects. If queried it crashed. Never saw this before. Will look into it.

**Comment by polyboi** [comment]
Yeah, it seems to work now. I had eepfrd as my create policy instead of eppfrd and since I was copying and pasting the exact same options every time I tried to use mergerfs I was getting the exact same problem no matter how I installed it or which version of Ubuntu I was using.

**Comment by trapexit** [comment]
I found the issue. When parsing arguments policies aren't properly returning an error if not recognized. Was silently accepting invalid data. I'll release an update with a fix.
