### ISSUE TITLE
Random disk not readable after restart

### ISSUE THREAD

**Issue by wiryonolau** [trapexit/mergerfs#1052]
Hi I have this kind of setup for my server , we have 6 disk combine together by mergerfs

This is /etc/fstab entry
```
# Same for all 6 disk
UUID=<uuid> /mnt/disk-<id> ext4 defaults,nofail,noatime,x-systemd.device-timeout=10s,errors=continue 0 0

/mnt/disk-* /mnt/mergerfs fuse.mergerfs defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=50G,fsname=mergerfs 0 0
```

Sometime we need to shutdown the server and when there is write operation happen ( rsync in this case ) . After turning on some of the disk sometime not detected. Is there a way to improve mergerfs option to better prevent this. Maybe on pre shutdown disable all write and make sure everything is flush

**Comment by trapexit** [comment]
What do you mean the disk is not detected? Not detected by what? Why do you think this is related to mergerfs or data writing?

**Comment by wiryonolau** [comment]
I haven't find any strange data in the log, since it is quite random. 
Does my mergerfs mount options can be improve ?

**Comment by trapexit** [comment]
I don't understand what is wrong and you've not provided enough information for me to guess. Mergerfs has no material impact on the devices. It is a user land app like any other. It is not the direct cause of drives not being recognized.

**Comment by wiryonolau** [comment]
Ok thanks for the info. I guess it's the sata controller problem.
