### ISSUE TITLE
When doing mount -a, it creates 2 MergerFS mounts when viewed on duf

### ISSUE THREAD

**Issue by ChristianMalazarte** [trapexit/mergerfs#1060]
Not sure if this is really a bug or just a cosmetic thing. When doing mount -a, it creates 2 MergerFS mounts when viewed on duf. Would this affect performance? What is an alternative way of remounting all drives without having this duplicate problem?

**System information:**

 - OS, kernel version: Linux plexserver 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
 - mergerfs version: mergerfs version: 2.33.3
 - mergerfs settings
defaults,nonempty,allow_other,use_ino,cache.files=off,ignorepponrename=true,moveonenospc=true,dropcacheonclose=true,minfreespace=200G,fsname=mergerfs,category.create=mspmfs

**Comment by trapexit** [comment]
There is no way to remount a FUSE filesystem currently. It just mounts it again unfortunately. You could lazy umount it before mount -a. I could look into doing the same automatically when it runs any time. There just isn't much I can do otherwise.

No, there is no perf impact. Just waste of some memory.

**Comment by ChristianMalazarte** [comment]
Okay thank you so much. All that matters is there's no impact or double writes, or corruption, etc. I have plenty of memory so I should be fine. Thanks again.

**Comment by trapexit** [comment]
It's just like any other situation you mount one filesystem over an existing... all those which were using it prior will continue to do so and new requests will be routed to the new one. They are completely separate processes and filesystems.
