### ISSUE TITLE
MergerFS EL7 x86-64 RPM is 32-bit

### ISSUE THREAD

**Issue by bodgit** [trapexit/mergerfs#1061]
**Describe the bug**

I've just installed the 2.33.5 EL7 x86-64 RPM and noticed that it's pulled in the i686 glibc and related packages. Sure enough the binaries in the RPM are all 32-bit:
```
[root@server ~]# rpm -q mergerfs
mergerfs-2.33.5-1.el7.x86_64
[root@server ~]# file /usr/bin/mergerfs
/usr/bin/mergerfs: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0xf6e99a5fabc13aa3f832a1eabe3738030b286624, not stripped
```

**To Reproduce**

Install package :wink:

**Expected behavior**

I would expect an x86-64 RPM to contain 64-bit binaries. Is there any practical reason why it's compiled for 32-bit?

**Comment by trapexit** [comment]
I've been building these packages the same way (via platform specific docker images) for years now. Nothing has changed. Either it's always been like this or you're the first to notice or they changed the setup of their image.

I'm rebuilding it now and everything installed is x86_64. I'll report back when it finishes.

**Comment by trapexit** [comment]
[mergerfs-2.33.5-1.el7.x86_64.rpm.gz](https://github.com/trapexit/mergerfs/files/9447834/mergerfs-2.33.5-1.el7.x86_64.rpm.gz)

Looks fine to me. I can replace what's there with this.

**Comment by trapexit** [comment]
For some reason the 386 version is being named x86_64 and hence overwrote the actual x86_64 build. Need to see why the i386 image thinks it is 64bit.
