### ISSUE TITLE
feature request: create policy msp smallest total space

### ISSUE THREAD

**Issue by sluggathor** [trapexit/mergerfs#1070]
**Is your feature request related to a problem? Please describe.**
Using SSD as tiered storage for a bunch of drives. ff or epff will not switch to next branch if first found is full. so first tier fills up and errors out

**Describe the solution you'd like**
msp with smallest total space would allow for SSD (most often the smallest drive) to fill with some sort of path preservation and move to next branch if first branch is filled up to the limit set. or is there a way to use mspff with moving down the list if the first branch is filled to the limit.

maybe i am not understanding the limits of mergerfs completely - so i would appreciate being educated :)

**Comment by trapexit** [comment]
I'm not sure what you mean by "smallest total space". Can you explain *exactly* what information you want to be used to decide which branch to select and how this "msp smallest total space" is different from msplfs?

**Comment by sluggathor** [comment]
least free space will jump branches, when the sdd fills up or if a disk fills up. i meant to say least total capacity - if that makes more sense - but with the added benefit of using msp

**Comment by trapexit** [comment]
msplfs, not lfs.

"jump branches"... everything that isn't ep* has a possibility to change branches. That's the whole point of msp. To be sticky but not strict.

You want to ignore actual available storage entirely? What if the smallest device fills up? That would result in the branch being select, writes will happen, it will fill up and error or moveonenospc will trigger over and over. And if another request comes in during that time it will fall back with msp behavior and pick a different branch.

**Comment by sluggathor** [comment]
i am looking for a way to use some kind of tiered storage. mostly for writes and recent files. right now the ssd catches nearly all the writes via epff (a few directories are not replicated on the 1st tier). if the cache fills up before being emptied it will error out without jumping to the next tier. using msplfs will work until one of the backing drives is full and will get priority.
is there some way to use msp with some kind of priority listing? if i understand correctly using only ff will result in error and no moveonenospc when the first drive (cache) fills up, right?

**Comment by trapexit** [comment]
"i thought that's what min free space is for."

No. Min *free* space. Not min total space. 

"using msplfs will work until one of the backing drives is full and will get priority."

I'm really not understanding. What do you want to happen when a branch fills up? You appear to say you don't want it to look elsewhere but that's what ep* in regard to paths.

"if i understand correctly using only ff will result in error and no moveonenospc when the first drive (cache) fills up, right?"

Read the section on filtering. minfreespace filters out branches without the minimum free space. If you set minfreespace to 0 then yes but that's in your control.

I'm sorry but I still don't understand the algo you want or what you're trying to accomplish. Just describe it out. You have branches, their metrics (free and used space), paths, etc. Just describe how you would choose a branch based on that information.

SSD0, SSD1, HDD0, HDD1, HDD2,...

SSD0 has 10gb free out of 128gb.
...

just walk through the algo. How would you choose a branch based on the info.

**Comment by sluggathor** [comment]
so:
ssd0 is the first tier for a backing pool of a few drives. (2 mergerfs pools as described in your readme)
there is a daily script that checks free space on the ssd and calls rsync if needed to move certain folders to the backing pool.

ssd runs out of space before rsync is called - min free space is set to 150G
what happens if there is a new write on the mergerfs pool containing the ssd (epff, ssd is on top of that list)? I created all the folders that need to exist outside of the ssd on the backing drives (at least all the root folder and standard sub folder like movies/movies-4k/A, B, C etc.).
If there is data copied from say qbittorrent to the movies folder - will the ssd get skipped and the next branch gets the write? still with epff

**Comment by trapexit** [comment]
"If there is data copied from say qbittorrent to the movies folder - will the ssd get skipped and the next branch gets the write? still with epff"

It's not when data is copied. It's when a file is created. And when a file is created the policy is run, a branch selected, and the create happens on the branch selected. All according to what is described in the docs.

epff.... existing path, first found. 

> Given the order of the branches, as defined at mount time or configured at runtime, act on the first one found where the relative path exists.

And that is, as mentioned https://github.com/trapexit/mergerfs#filtering, filters out paths which fail the "minfreespace" check, are tagged RO or NC, or mounted read-only.

**Comment by trapexit** [comment]
Please just describe your wanted behavior.

**Comment by sluggathor** [comment]
sorry for being so difficult. it's not my intention.
wanted behavior:
ssd0 fills up with data. min free space on the pool containing the ssd (cachepool) is set to say 150G. ssd0 reaches 150G free space.
next disk in line has enough free space but folder structure is not completely mirrored (ssd0 /movies/4k/themovie -> next disk /movies/4k/). i would like for mergerfs to create the missing directories to continue writing. will it work as long as part of the directory-tree is already on the drive?

**Comment by trapexit** [comment]
"i would like for mergerfs to create the missing directories to continue writing"

That's exactly what moveonenospc is.

> moveonenospc=BOOL|POLICY: When enabled if a write fails with ENOSPC (no space left on device) or EDQUOT (disk quota exceeded) the policy selected will run to find a new location for the file. An attempt to move the file to that branch will occur (keeping all metadata possible) and if successful the original is unlinked and the write retried. (default: false, true = mfs)

**Comment by trapexit** [comment]
Paths are created ANYTIME they are needed. It has nothing to do with policies or anything else. Policy picks a branch. If the path is not there it is created. Completely separate things. If your policy filters out branches without the path then naturally no branch is taken and so no path is created.

Again... this would be far easier if you said what you want not ask what stuff does.

**Comment by trapexit** [comment]
I really am not confident I understand what you're looking for. I'm guessing since you don't want to use `ff` you want to try to colocate files as much as possible and then use them in the order provided?

In which case a mspff? Most shared path, first found. Which is only slightly different from msplfs or msplus given your SSDs are likely have the least free and least used space. But if you want mspff then I can do it.

**Comment by sluggathor** [comment]
see i was unclear about whether epff (as a create policy) would consider branches with less than the full path. now i think i get it a bit more. i am using epff and it works mostly like i want it to. but since my ssd AND backinpool was filling up rapidly i got a few errors about no space left on device. i think i made some errors with creating root folders (missing a few drives where i wanted the data to sit) - thank you for your patience. i dont think there is need for mspff since epff does what i need if i take a bit more care with folder creation.

thank you for your work!

**Comment by trapexit** [comment]
May I ask why you care about where files are located like that? As I mention in the docs ep* is restrictive and intended for people who have very particular setups. Like someone who wants to have a few drives strictly for TV shows and be able to pop the drive out for use on the road or something. Having to manually manage every path is excessive otherwise. msp was specifically designed for people who would like colocation but it's not the end of the world if files end up on another branch. 

Given almost all major software supports downloading individual episodes/movies/music and all backup software will restore what's missing it's generally not needed or recommended to care where files are stored.

**Comment by trapexit** [comment]
"see i was unclear about whether epff (as a create policy) would consider branches with less than the full path. "

https://github.com/trapexit/mergerfs#path-preservation

> A path preserving policy will only consider drives where the relative path being accessed already exists.

> Given the order of the branches, as defined at mount time or configured at runtime, act on the first one found where the relative path exists.

There is no hidden meaning here. It means literally "where the relative path exists." The relative base path to file /mnt/ssd/a/b/c/d is a/b/c. You can't have a/b/c/d without a/b/c.

**Comment by sluggathor** [comment]
right now my setup looks like this:

cachepool: epff, min free 150G 
2x SSD 2TB (lvm RAID1) (incoming for nearly everything except backups; torrent seed drives)
5x single XFS drive (for media) - with all folders created (movies/4k/A, B, C etc., folders for individual movies are not duplicated though)
2x drives in ZFS mirror (backups, user folders, pictures - all the important stuff) - folders are mostly pre-created

backingpool: msplfs, min free 500G
all the spinning drives

nightly cronjob that rsyncs cache drives to backingpool, takes a snapshot of the zfs mirror and starts snapraid against another drive (all that IF cache drives are more than 50% filled)
all created folders (except certain backups, or those that are deleted in general) are left on the cache drives because i 'believe' it helps with reducing spin up. might be wrong there - maybe you can shed some light on that

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/wiki/Limit-Drive-Spinup

**Comment by sluggathor** [comment]
i read that before setting this up. i just hoped it would be less of an issue - but the last weeks have shown me otherwise. might have to rethink my data structure

**Comment by sluggathor** [comment]
plex for example does not like files moving from one path to another. so it gets to see the whole cachepool

**Comment by trapexit** [comment]
What do you mean? Naturally if a file moves locations on the filesystem Plex or anything will believe the file, correctly, is gone. In Plex to minimize issues you can tell it not to empty trash on scan.

**Comment by sluggathor** [comment]
yes, but i am lazy :D will try it now. hopefully it wont have to redo intro scans

**Comment by sluggathor** [comment]
and thank you again for the great tool mergerfs is!

**Comment by MasterCATZ** [comment]
> Paths are created ANYTIME they are needed. It has nothing to do with policies or anything else. Policy picks a branch. If the path is not there it is created. Completely separate things. If your policy filters out branches without the path then naturally no branch is taken and so no path is created.

well rsync is currently biting me in the ass its creating all folder paths on an empty drive and not spanning over to empty drives when its full
mfs has worked great in the past but wanting to lower power consumption and not having a heap of disks spinning while watching a season that could all have been on just 1 drive 

I have mergerfs set with 50gb reserve but its not detecting that a drive is full and recreating a new folder branch on a fresh drive using eplfs 

rsync just keeps going to the next file trying to copy and going no free space 

anyway to have some form of path preservation while filling up 1 drive at a time ?

**Comment by trapexit** [comment]
Please don't comment on old threads. If you aren't reporting issues please use the Discussions board.
