### ISSUE TITLE
Broken symbolic links to small files on XFS with symlinkify=true

### ISSUE THREAD

**Issue by altwazar** [trapexit/mergerfs#1084]
Got broken symbolic links to files smaller than 4096b. Like "test2 -> /HDD2/TEST/a" instead of "test2 -> /HDD2/TEST/abcde/qwerty/zxcvb/test2".

**To Reproduce**

On mounted xfs file systems (/HDD1, /HDD2) create folder TEST:
```
mkdir /HDD1/TEST
mkdir /HDD2/TEST
```
merge them in folder /TEST:
```
mergerfs -o allow_other,use_ino,cache.files=partial,symlinkify=true,cache.symlinks=true,cache.statfs=true,cache.readdir=true,cache.open=true,dropcacheonclose=true,category.create=mfs,minfreespace=50G /HDD1/TEST:/HDD2/TEST /TEST
```
Create test directory and files:
```
mkdir -p /TEST/abcde/qwerty/zxcvb
echo "sdadfadf" > /TEST/abcde/qwerty/zxcvb/test1
echo "sdfgsdfgsdf" > /TEST/abcde/qwerty/zxcvb/test2
echo "yeasdf" > /TEST/abcde/qwerty/zxcvb/test3
echo "zbxzcsd" > /TEST/abcde/qwerty/zxcvb/test4
chmod a-w /TEST/abcde/qwerty/zxcvb/*
```
Results after symlinkify:
```
ls -lt /TEST/abcde/qwerty/zxcvb/    
total 16
lr--r--r-- 1 root root  8 окт 26 09:26 test4 -> /HDD2/TE
lr--r--r-- 1 root root  7 окт 26 09:26 test3 -> /HDD2/T
lr--r--r-- 1 root root 12 окт 26 09:26 test2 -> /HDD2/TEST/a
lr--r--r-- 1 root root  9 окт 26 09:25 test1 -> /HDD2/TES
```

**System information:**

 - OS, kernel version: 5.19.13-gentoo-dist #1 SMP PREEMPT_DYNAMIC Wed Oct 5 16:16:56 +07 2022 x86_64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz GenuineIntel GNU/Linux
 - mergerfs version: mergerfs version: 2.33.4
 - mergerfs settings: allow_other,use_ino,cache.files=partial,symlinkify=true,cache.symlinks=true,cache.statfs=true,cache.readdir=true,cache.open=true,dropcacheonclose=true,category.create=mfs,minfreespace=50G
 - List of drives, filesystems, & sizes:
/dev/sdc1 xfs 7,3T(2,4T used) /HDD2 (defaults,noatime)
/dev/sdg1 xfs 7,3T(2,4T used) /HDD1 (defaults,noatime)

**Comment by trapexit** [comment]
XFS is a red herring. Happens no matter the underlying filesystem. Appears to be related to symlink caching. Try disabling that.

**Comment by trapexit** [comment]
mergerfs is returning the proper values to the kernel. I'll have to look into it further. Possibly contact FUSE folks.

**Comment by altwazar** [comment]
> XFS is a red herring. Happens no matter the underlying filesystem. Appears to be related to symlink caching. Try disabling that.

Thank you for your work, without symlink caching it works normal.

**Comment by trapexit** [comment]
Figured out the issue. Will fix it soon.
