### ISSUE TITLE
Mergerfs segfault

### ISSUE THREAD

**Issue by ghr12** [trapexit/mergerfs#1094]
Hello,

Attempting to use mergerfs with 2 external USB driver. Can create merged fs successfully but seg faults as soon as any data is attempted to be copied to it. Any further access results in:
  Transport Endpoint Not Connected 

Mount point needs to be unmounted. then can be remounted. Symptoms then reoccur.

mounted with:
mergerfs -o defaults,allow_other,use_ino,category.create=mfs,moveonenospc=true,minfreespace=8G /mnt/pool/disk1:/mnt/pool/disk2 /mnt/pool/bond

System is RHEL 8.6     -    Kernel 4.18.0-372.19.1.el8_6.x86_64

mergerfs version:   mergerfs-2.33.5

rpm package built with:
su -
cd mergerfs
tools/install-build-pkgs
make rpm
rpm -i rpmbuild/RPMS/<arch>/mergerfs-<version>.<arch>.rpm

Nov 12 22:26:35 stor01 systemd[1]: mnt-pool-disk1.mount: Succeeded.
Nov 12 22:26:35 stor01 kernel: XFS (sdh1): Unmounting Filesystem
Nov 12 22:26:35 stor01 systemd[1]: mnt-pool-disk2.mount: Succeeded.
Nov 12 22:26:35 stor01 kernel: XFS (sdi1): Unmounting Filesystem
Nov 12 22:26:41 stor01 systemd[1]: mnt-pool-bond.mount: Succeeded.
Nov 12 22:27:48 stor01 kernel: XFS (sdh1): Mounting V5 Filesystem
Nov 12 22:27:48 stor01 kernel: XFS (sdh1): Ending clean mount
Nov 12 22:27:49 stor01 kernel: XFS (sdi1): Mounting V5 Filesystem
Nov 12 22:27:49 stor01 kernel: XFS (sdi1): Ending clean mount
Nov 12 22:30:40 stor01 kernel: mergerfs[4042138]: segfault at 0 ip 0000000000000000 sp 00007ff5af7f55e8 error 14 in mergerfs[400000+6f000]
Nov 12 22:30:40 stor01 kernel: Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
Nov 12 22:30:40 stor01 systemd[1]: Started Process Core Dump (PID 4042222/UID 0).
Nov 12 22:30:40 stor01 systemd-coredump[4042223]: Process 4042130 (mergerfs) of user 0 dumped core.#012#012Stack trace of thread 4042138:#012#0  0x0000000000000000 n/a (n/a)#012#1  0x0000000000001890 n/a (n/a)
Nov 12 22:30:40 stor01 systemd[1]: systemd-coredump@1-4042222-0.service: Succeeded.
Nov 12 22:33:43 stor01 systemd[1]: mnt-pool-bond.mount: Succeeded.

**Comment by trapexit** [comment]
I don't have immediate access to a RHEL8 system. Is centos 8 stream similar enough?

**Comment by trapexit** [comment]
Does the static binary crash?

**Comment by ghr12** [comment]
Static binary works.

Thanks 👍

**Comment by trapexit** [comment]
Nothing to be sorry about. I'm just trying to debug the situation and understand what could be going on. It shouldn't be crashing but without having RHEL8 it's a little hard to reproduce.
