### ISSUE TITLE
Writing issue with Docker

### ISSUE THREAD

**Issue by ynnckvdv** [trapexit/mergerfs#1095]
**Describe the bug**

I created `/mnt/storage2`  using MergerFS, it's meant to be used as storage and is mounted to a few Docker containers using docker-compose. Reading the storage works fine but I cannot write anything *from inside* the Docker container on `/mnt/storage2`. I use a Deluge container, and it's not writing when the download is set to `/mnt/storage2/media-server/Downloads`.

**Please be sure to use latest release of mergerfs to ensure the issue still exists. Not your distro's latest but the latest official release.**

I am using version 2.33.5 for Debian Bullseye.

**To Reproduce**

Steps to reproduce the behavior. List **all** steps to reproduce. **All** settings.

1. Install Debian, MergerFS, Docker & Docker-Compose.
2. Create `/mnt/storage2/media-server/Downloads`
3. Use this docker-compose.yml 
[docker-compose.txt](https://github.com/trapexit/mergerfs/files/9998485/docker-compose.txt), change the extension to .yml (GitHub wouldn't let me upload otherwise) and `docker-compose up -d`
Here's a simpler docker-compose, because the other one is too much of a hassle: 
[docker-compose.txt](https://github.com/trapexit/mergerfs/files/9998504/docker-compose.txt)
4. Try to write a file to `/mnt/storage2/media-server/Downloads`

**Expected behavior**

My Docker containers need to be able to write to `/mnt/storage2/media-server/Downloads`. 

**System information:**

 - OS, kernel version: `uname -a`: 
 ```
Linux (hostname) 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```
 - mergerfs version: `mergerfs -V`:  
 ```
 3.33.5 for Debian Bullseye
```
 - mergerfs settings:
```
# MergerFS
UUID=...       /mnt/disk-sda   ext4    defaults 0 0
UUID=...       /mnt/disk-sdb   ext4    defaults 0 0
UUID=...       /mnt/disk-sdc   ext4    defaults 0 0
UUID=...       /mnt/disk-sdd   ext4    defaults 0 0
UUID=...       /mnt/disk-sde   ext4    defaults 0 0
/mnt/disk*      /mnt/storage2   fuse.mergerfs   direct_io,defaults,allow_other,minfreespace=10G,nonempty,fsname=mergerfs 0 0
```
 - List of drives, filesystems, & sizes:
   - `df -h`:
 ```
 Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  2.1M  1.6G   1% /run
/dev/sda1        73G  9.4G   60G  14% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
mergerfs        6.2T  861G  5.1T  15% /mnt/storage2
/dev/sdd1       916G   28K  870G   1% /mnt/disk-sdd
/dev/sdb1       1.8T   28K  1.7T   1% /mnt/disk-sdb
/dev/sda3       1.8T   28K  1.7T   1% /mnt/disk-sda
/dev/sde1       916G   28K  870G   1% /mnt/disk-sde
/dev/sdc1       916G  861G  8.4G 100% /mnt/disk-sdc
tmpfs           1.6G  108K  1.6G   1% /run/user/1000
 ```
   - `lsblk -f`:
```
NAME   FSTYPE FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda
├─sda1 ext4   1.0         915c578e-d567-4375-9349-8a09e224ba58   59.7G    13% /
├─sda2 swap   1           ca9d81fe-d334-42d4-86f7-9baaaac5d162                [SWAP]
└─sda3 ext4   1.0         44fc4ae1-dfec-4ed6-85ff-e2405e77cac2    1.6T     0% /mnt/disk-sda
sdb
└─sdb1 ext4   1.0         f8bb656a-9365-4883-80e2-c37835a0c2d3    1.7T     0% /mnt/disk-sdb
sdc
└─sdc1 ext4   1.0         cdc1ff82-3fd8-4375-88a1-69352a594b0a    8.4G    94% /mnt/disk-sdc
sdd
└─sdd1 ext4   1.0         8a4391fb-9353-4a28-af8e-3ad0a17aba12  869.2G     0% /mnt/disk-sdd
sde
└─sde1 ext4   1.0         fe21aa8b-7e8b-4ec9-992f-7cfe4ec73a95  869.2G     0% /mnt/disk-sde
sdf
sr0
```
 - A strace of the application having a problem:
[strace.txt](https://github.com/trapexit/mergerfs/files/9998452/strace.txt)

**Additional context**

`/mnt/storage2` and everything within is owned by my user, with `rwxr-xr-x` permissions so it **shouldn't** be a permissions issue.
I found [ this issue](https://github.com/trapexit/mergerfs/issues/463) and I believe I have the same bug, I have included the advised flags from[ the documentation](https://github.com/trapexit/mergerfs#can-mergerfs-run-via-docker-podman-kubernetes-etc) to the containers that need them, but no luck.

Thanks in advance.

**Comment by trapexit** [comment]
Many people, including myself, have no problem writing to a mergerfs mount inside a Docker container.

Why are you binding in /dev/fuse and setting SYS_ADMIN? 

All you need to do is bind in the path like any other and ensure the permissions are correct.

docker run --rm -it -v /mnt/storage2:/mnt/storage2 --user 1000 alpine:latest sh

touch'ed a file and worked fine.

**Comment by trapexit** [comment]
Boil things down as simply as possible. Try the alpine or debian or ubuntu base image and use basic tooling like cp, mv, touch, rm to test.

**Comment by ynnckvdv** [comment]
Seems I wasn't very clear, sorry
I added the advised flags from the documentation: https://github.com/trapexit/mergerfs#can-mergerfs-run-via-docker-podman-kubernetes-etc
That's why I binded in /dev/fuse and set SYS_ADMIN.

I tested again, using the docker run cmd you sent
And I can touch a file in /mnt/storage2, but I can't do the same in any child directories. This is a new error I haven't encountered before:
```
/mnt/storage2 $ touch test
/mnt/storage2 $ ls -la
total 28
drwxr-xr-x    3 1000     root          4096 Nov  7 15:41 .
drwxr-xr-x    1 root     root          4096 Nov 14 15:33 ..
drwx------    2 1000     root         16384 Nov  7 15:41 lost+found
drwxr-xr-x    4 1000     root          4096 Nov  7 16:36 media-server
-rw-r--r--    1 1000     root             0 Nov 14 15:42 test
/mnt/storage2 $ cd media-server
/mnt/storage2/media-server $ touch test
touch: test: No space left on device
```

So all of them are owned by my user, with ID 1000, /mnt/storage2/media-server has 755 perms.
Hope this makes it more clear.

**Comment by trapexit** [comment]
Those instructions are for running mergerfs INSIDE a container.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#policies

> If all branches are filtered an error will be returned. Typically EROFS (read-only filesystem) or ENOSPC (no space left on device) depending on the most recent reason for filtering a branch. ENOENT will be returned if no eligible branch is found.

Have you confirmed such things? Again, simply things. Use one branch. Make sure the branch isn't filtered out during create due to the policy and config you set. Things like minfreespace.

**Comment by trapexit** [comment]
1) Yeah. Tutorials that aren't my own aren't necessarily correct.
2) filesystems are complex. mergerfs has lots of features. Should always read the docs and confirm your settings are what you want. What it was doing is *totally legit* it just is that you weren't expecting it.
