### ISSUE TITLE
support building deb packages

### ISSUE THREAD

**Issue by trapexit** [trapexit/mergerfs#11]

**Comment by bfqrst** [comment]
Hey @trapexit ,

thanks for your work. This is awesome. I was trying to install the deb package in latest OSMC distro which is based on Debian 8.2 at the time of this writing. I'm getting an error from the libstdc++6 because ist still version 4.9.2. Compiled everything manually and it seems as if everything went well. Got a couple of warnings though:

    src/getxattr.cpp: In function ‘void _getxattr_controlfile_minfreespace(const mergerfs::Config&, std::string&)’:
    src/getxattr.cpp:121:53: warning: format ‘%li’ expects argument of type ‘long int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
       snprintf(buf,sizeof(buf),"%li",config.minfreespace);
                                                     ^
    src/getxattr.cpp:121:53: warning: format ‘%li’ expects argument of type ‘long int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]

I was wondering if it would be a hassle to compile the .deb for a lower Debian target such as Jessy?

Cheers
bfqrst

**Comment by trapexit** [comment]
Sure. I'll look into it for my next release.

**Comment by trapexit** [comment]
BTW... what platform? i386, x64, ARM? If the latter then I'm going to need some donated hardware or a qemu image. The only ARM base general purpose machine is a ODroid-C1.

**Comment by bfqrst** [comment]
Thanks man. Yeah the intended use was for a Raspberry PI 2, therefore ARM Cortex-A7 CPU from Broadcom. The ODroid-C1 has a ARM Cortex-A5 CPU from Amlogic. Don't quite know if it the build would be compatible...

**Comment by trapexit** [comment]
I found some qemu rasppi stuff. Trying it out. Instruction set wise it should be fine with the RaspPI2 I think. The issue is probably more the library versions.

**Comment by bfqrst** [comment]
Thank you so much!

**Comment by trapexit** [comment]
It's not working with recent raspbian images. I'll play with it more later. I can look into debian on the C1 as well but honestly I'm not going to spend too much effort on it given the limited audience.

**Comment by bfqrst** [comment]
I understand and I appreciate that! All I know is that Raspbian is based on Debian Wheezy whereas OSMC (former Raspbmc) is based on Debian Jessy.

**Comment by trapexit** [comment]
2.7.0 will build on Wheezy.

**Comment by trapexit** [comment]
I've tried to build armhf packages. See if they work for you.

**Comment by bfqrst** [comment]
... deb armhf package (jessy) installed flawlessly on OSMC. libstdc++6 error ist gone. Thanks man. U rock. I'm a little bit short on time so I can't actually tell if it works, but as I said, the installation is a GO!

Cheers 
bfqrst
