### ISSUE TITLE
Transport endpoint is not connected on v2.34.0

### ISSUE THREAD

**Issue by jonpas** [trapexit/mergerfs#1108]
**Describe the bug**

Consistent "Transport endpoint is not connected" errors on a file operation on v2.34.0, verified previous version worked correctly by reverting to it. `dmesg | grep mergerfs` shows a segmentation fault.

**To Reproduce**

```
$ mergerfs /mnt/disk1:/mnt/disk2 /srv/data
$ cd /srv/data
$ touch test.txt
$ mv test.txt  tv/
mv: cannot stat 'tv/test.txt': Transport endpoint is not connected

$ sudo dmesg | grep mergerfs
[sudo] password for jonpas: 
[   38.237297] mergerfs[351]: segfault at 0 ip 0000000000000000 sp 00007f984801b638 error 14 in mergerfs[55fd2ff7e000+b000]
[   38.237394] audit: type=1701 audit(1670782579.342:264): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=346 comm="mergerfs" exe="/usr/bin/mergerfs" sig=11 res=1
```

_See `df -h` output below for the same error as well._

**Expected behavior**

`test.txt` being moved to the `tv` folder without errors, as in v2.33.5.

**System information:**

 - OS, kernel version: `Linux tyr 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux`
 - mergerfs version: `2.34.0`
 - mergerfs settings: /
 - List of drives, filesystems, & sizes:
```
$ df -h
df: /srv/data: Transport endpoint is not connected
Filesystem      Size  Used Avail Use% Mounted on
dev             3.8G     0  3.8G   0% /dev
run             3.8G  1.5M  3.8G   1% /run
/dev/sda2       457G   25G  409G   6% /
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           3.8G     0  3.8G   0% /tmp
/dev/sdb1       1.8T  1.3T  452G  75% /mnt/disk1
/dev/sdc1       293G   92K  278G   1% /mnt/disk2
/dev/sda1       511M   93M  419M  19% /boot
tmpfs           765M     0  765M   0% /run/user/1000
```
_Not sure which `strace` to provide as it happens after everything was created._

**Additional context**

Also tried with a single branch `/mnt/disk1`, same error.

mergerfs is built from source using [AUR](https://aur.archlinux.org/packages/mergerfs).

**Comment by trapexit** [comment]
Found it. Will have a fix shortly.

**Comment by jonpas** [comment]
Awesome! :)

**Comment by trapexit** [comment]
Fixed, pushed, tagged. I don't control the AUR but once updated should be good.
