### ISSUE TITLE
I broke my mergerfs

### ISSUE THREAD

**Issue by Chris230291** [trapexit/mergerfs#1115]
Today I decided to add `use_ino` because I read that it is not a default and is recommended.

```
# mergerfs
/dev/disk/by-uuid/35d167b5-b6d5-471e-aaed-33c516b9b87c /mnt/mergerfs/disk1 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/disk/by-uuid/53f86816-a9be-44c2-bbf4-bba9ce2a9be1 /mnt/mergerfs/disk2 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/disk/by-uuid/bbaab006-7745-4d6d-92bc-23d00795efdf /mnt/mergerfs/disk3 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/disk/by-uuid/3a5dcbdf-59d9-49d1-b45e-7516203a4d47 /mnt/mergerfs/disk4 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/disk/by-uuid/1d45dda3-b61c-4459-be8c-e878734f10cf /mnt/mergerfs/disk5 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/disk/by-uuid/ae516984-2e2f-4adb-ab3d-b822b9a67d99 /mnt/mergerfs/disk6 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/disk/by-uuid/d48a0a43-0307-42b3-bf11-5c16e5f89bed /mnt/mergerfs/disk7 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/dev/disk/by-uuid/1ff9a553-578f-40d5-b666-cc4cf590cf4f /mnt/mergerfs/disk8 auto nosuid,nodev,nofail,x-gvfs-show 0 0
/mnt/mergerfs/disk*     /mnt/Storage    fuse.mergerfs allow_other,use_ino,fsname=mergerfs,category.create=mfs 0 0
```

Now in windows using a samba share, the capacity is a fraction of what it should be (3x 10tb + 5x 2tb) and files are missing.

![image](https://user-images.githubusercontent.com/5328818/209453260-ef5cfd4c-7c53-4cff-a174-51de0bd8ec98.png)

If I browse the mergerfs pool on my server, I can see all of the files and folders I expect using the `ls` command.

But that is not to say its a samba only issue. My Plex Docker container that runs on the server and mounts the mergerfs pool is unable to see the files too.

![image](https://user-images.githubusercontent.com/5328818/209453278-347a840a-8881-4812-b439-09b67f72d169.png)

I have already tried removing the `use_ino` from my fstab but it seems the damage has been done.

Is there any way I can get mergerfs working correctly again?

Thanks,
Chris

**Comment by trapexit** [comment]
use_ino simply makes mergerfs set inode values in a certain way as defined in the docs.

If you can see the files in the mount then it's not a mergerfs issue. It would perhaps be a cache issue with the relevant software.

**Comment by Chris230291** [comment]
I had been playing with this for some hours before I made this issue.

I cant explain why it acted this way but I have found the cause.

My Docker containers mounted `/mnt/storage/...` (this always worked before I added `use_ino`), but my fstab mounts the pool at `mnt/Storage`. I changed fstab to lowercase `storage` and all is well again.

Sorry for wasting your time.
