### ISSUE TITLE
Ability to configure niceness

### ISSUE THREAD

**Issue by ChrisOboe** [trapexit/mergerfs#1122]
**Is your feature request related to a problem? Please describe.**
I run mergerfs on a rather weak cpu with lot's of other stuff running in parallel. 
Sometimes IO completely breaks in, when cpu usage is high and the scheduler needs to decide between mergerfs and whatever other software wants to use the cpu. 

When i give mergerfs a lower niceness, io performance keeps stable since the scheduler will prefer mergerfs. But it need to manually set the nice value. 

**Describe the solution you'd like**
It would be nice (pun intended) if it would be possible that mergerfs sets it's niceness on it's own by an mount option. 

**Describe alternatives you've considered**
Writing a systemd unit that depends on the mergerfs mount to renice merger fs. But i think cpu heavy fuse filesystems should offer this option since it's propably a general problem and not *that* specific to my own system. 

no matter if you will or won't implement this feature, thank you for your work on mergerfs!

**Comment by trapexit** [comment]
This is something I've been meaning to add for a while. mergerfs currently sets its priority to -10.

https://github.com/trapexit/mergerfs/blob/master/src/mergerfs.cpp#L139

I did this early on so to keep it from being starved by average CPU hungry apps but never really tested anything.

Can you be specific with the values you use and see a difference?

**Comment by ChrisOboe** [comment]
I didn't know it was hardcoded already to -10. For my system configuration i also use -10 for some services so i assume i can just configure them to -5 and my problems will be solved.

> Can you be specific with the values you use and see a difference?

currently not, i just noticed that when i play media via jellyfin the playing got stuck for a few seconds and it didn't happen anymore when i gave mergerfs a higher priority. 

if you want i can do some proper testing with specific values in a few days.

**Comment by trapexit** [comment]
Feature added. Will be in the next release.
