### ISSUE TITLE
allow_other is still required even though the docs says it's deprecated and always enabled

### ISSUE THREAD

**Issue by rogerdahl** [trapexit/mergerfs#1144]
Mounting a mergerfs drive from /etc/fstab still requires the `allow_other` option in order to make the drive available to regular users, even though the README.md file says, `allow_other: deprecated - Always enabled`.

Verified on latest release, 2.34.1.

**Comment by trapexit** [comment]
You're looking at new docs for a yet released version. You should always be using the docs for the version of the software you are using.

`man mergerfs` locally or for 2.34.1 online: https://github.com/trapexit/mergerfs/blob/2.34.1/README.md

**Comment by rogerdahl** [comment]
Thanks!

**Comment by KyleSanderson** [comment]
Just hit this myself.
