### ISSUE TITLE
After applying mergefs with success, cannot access mountpoint: `ls: cannot access 'mountpoint': No such file or directory

### ISSUE THREAD

**Issue by j-lorenzo** [trapexit/mergerfs#1148]
Hello!,

Currently I have this fstab:

```
UUID=fda2b4f8-3e58-4ad3-b12c-925d0a8d6769    /mnt/hdd12tb0   auto nosuid,nodev,nofail   0    0
UUID=7e034fb7-4122-4345-9a97-be91d3214f18    /mnt/hdd12tb1   auto nosuid,nodev,nofail   0    0

/mnt/hdd12tb* /mnt/merged fuse.mergerfs minfreespace=50G,category.create=mfs,func.getattr=newest,fsname=mergerfs 0 0
```

But... when I merge the filesystems, the result in /mnt is this, my user "jlorenzo" can't access the merged filesystem.

```
jlorenzo@machine:/mnt$ ls -lh
ls: cannot access 'merged': Permission denied
total 57K
drwxrwxr-x 6 jlorenzo jlorenzo 4,0K mar  8 16:55 hdd12tb0
drwxrwxr-x 2 jlorenzo jlorenzo 4,0K mar  8 16:44 hdd12tb1
drwxrwxr-x 3 jlorenzo jlorenzo    3 mar  8 16:30 hdd4tb0
drwxrwxr-x 5 jlorenzo jlorenzo    5 mar  8 10:25 hdd4tb1
d????????? ? ?        ?           ?            ? merged
```
```
jlorenzo@machine:/mnt$ ls hdd12tb0/
path1 path2
```
```
jlorenzo@machine:/mnt$ ls hdd12tb1/
path3 path4
```

I don't know what could happen, because when I check it with sudo it tells me all is working:

```
jlorenzo@machine:/mnt$ sudo ls -lL
total 61
drwxrwxr-x 6 jlorenzo jlorenzo 4096 mar  8 16:55 hdd12tb0
drwxrwxr-x 2 jlorenzo jlorenzo 4096 mar  8 16:44 hdd12tb1
drwxrwxr-x 3 jlorenzo jlorenzo    3 mar  8 16:30 hdd4tb0
drwxrwxr-x 5 jlorenzo jlorenzo    5 mar  8 10:25 hdd4tb1
drwxrwxr-x 6 jlorenzo jlorenzo 4096 mar  8 16:55 merged
```
```
jlorenzo@machine:/mnt$ sudo ls merged
path1 path2 path3 path4
```

---
Ubuntu 22.04.2 LTS
mergerfs version: 2.33.3 // tried too with the 2.34x

**Comment by j-lorenzo** [comment]
Another thing, when I use df -h with the jlorenzo user, it doesn't show me mergerfs but it does when I use sudo.

Thank you ;)

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/tree/2.34.1#basic-setup

You need `allow_other` (and `use_ino`).

**Comment by j-lorenzo** [comment]
Thank you! works like a charm ✨

**Comment by trapexit** [comment]
You may have seen the new documentation for an upcoming release that doesn't require them any longer. I've changed the default presentation on github to be the latest stable release rather than what I'm working on. In the future I'll have better docs.
