### ISSUE TITLE
No release for Ubuntu Kenetic

### ISSUE THREAD

**Issue by arnonm** [trapexit/mergerfs#1157]
**Describe the bug**
No release for Ubuntu 22.10 - Kenetic

Automatic scripts try to download https://github.com/trapexit/mergerfs/releases/download/2.34.1/mergerfs_2.34.1.ubuntu-kinetic_amd64.deb,

**Comment by trapexit** [comment]
:bump:

Would you like me to generate for short term support releases? What script are you referring?
