### ISSUE TITLE
Can a mergerfs be mounted as an nfs?

### ISSUE THREAD

**Issue by PRochefort** [trapexit/mergerfs#1164]
Good afternoon,

I'm trying to mount a mergerfs as an nfs but I'm having no success. Would someone have a few tips to share with me to get this working?

When I try to mount the mergerfs, I get a message that the directory does not exists. For the sake of transparency, I will disclose that I am trying this on an OpenMediaVault box as the source so some of the configuration is done via the web front-end.

As a test, I also tried on two freshly configured Ubuntu 22.10 VMs by manually setting up the mergerfs and then trying to export it as an nfs but didn't have success with this either.

If there are any configuration files you would like to see, ask and I will post.

I will review the documentation but if you have any suggestions, please let me know.
Thank you

**Comment by trapexit** [comment]
I can't speak to OMV but lots of people export mergerfs over NFS. There are details in the docs.

**Comment by PRochefort** [comment]
Ok, I must have missed something. I will review the documentation in greater details.
Thank you.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#can-mergerfs-mounts-be-exported-over-nfs

**Comment by PRochefort** [comment]
We can close this. The error was mine and it's working now. The problem existed between the chair and the keyboard. ;-)

Thank you for setting me straight here.
Pierre

**Comment by trapexit** [comment]
Glad you figured it out.
