### ISSUE TITLE
Trying to balance throws the error "is not a mergerfs mount"

### ISSUE THREAD

**Issue by gouthamravee** [trapexit/mergerfs#1173]
**SOLUTION**
I had xattr=nosys in the mergerfs config, this prevents the tools scripts from working as expected. I was able to run balance once I removed the xattr option from the config to return it to the default state. 

**Describe the bug**

A clear and concise description of the unexpected behavior.
I have mergerfs installed and setup through Open Media Vault. 
I can access the merged location, but when I try to run balance I get the error ` is not a mergerfs mount`

**To Reproduce**
I'm running the command below 
`sudo mergerfs.balance /srv/mergerfs/merged/ -e aquota.* -e snapraid.con*`

**Expected behavior**
I'm expecting the command to balance the array

**System information:**

 - OS, kernel version: `Linux omv6 6.1.0-0.deb11.5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1~bpo11+1 (2023-03-05) x86_64 GNU/Linux`
 - mergerfs version: `2.35.1`
 - mergerfs settings
 - List of drives, filesystems, & sizes:
```
Filesystem                                   Size  Used Avail Use% Mounted on
udev                                         7.8G     0  7.8G   0% /dev
tmpfs                                        1.6G  7.2M  1.6G   1% /run
/dev/sda2                                     62G   37G   22G  64% /
tmpfs                                        7.8G  388K  7.8G   1% /dev/shm
tmpfs                                        5.0M     0  5.0M   0% /run/lock
/dev/sdd1                                    3.6T  3.2T  423G  89% /srv/dev-disk-by-uuid-67fd7113-273a-4219-bd3b-43e69df1dbb2
/dev/sdc1                                    3.6T  3.2T  417G  89% /srv/dev-disk-by-uuid-913a945f-428d-43ab-987d-eebeb24f7161
/dev/sdo1                                    3.6T  3.2T  412G  89% /srv/dev-disk-by-uuid-5a8ed703-605e-48ec-a507-43e17f0c3504
/dev/sdl1                                    7.3T  3.0T  4.3T  42% /srv/dev-disk-by-uuid-03db52c8-c739-494b-b96f-37f53354b185
/dev/sdk                                     7.3T  6.8T  125G  99% /srv/dev-disk-by-uuid-13e11000-2295-486c-9292-11e95c37bbe2
tmpfs                                        7.8G     0  7.8G   0% /tmp
/dev/sda1                                    511M  5.8M  506M   2% /boot/efi
/dev/sdj1                                    3.6T  3.3T  362G  91% /srv/dev-disk-by-uuid-c1051291-a5bf-42e6-93a9-8d541f08aebb
/dev/sde1                                    7.3T  6.9T  415G  95% /srv/dev-disk-by-uuid-e0985793-e695-4008-8cc5-255be3783ebb
/dev/sdn1                                    7.3T   18G  7.3T   1% /srv/dev-disk-by-uuid-d2a25710-050e-4584-9eb8-eb1c9661433a
/dev/sdg1                                    3.6T  3.0T  418G  89% /srv/dev-disk-by-uuid-d5a72cf7-8b04-4475-9860-9c48735b3f23
/dev/sdf1                                    7.3T  6.9T  415G  95% /srv/dev-disk-by-uuid-98049d61-1c9b-4ec1-a698-0c2c1308a573
/dev/sdh1                                    3.6T  3.0T  416G  89% /srv/dev-disk-by-uuid-b90366a7-6fea-4a00-b18c-0b67ce756d97
/dev/sdi1                                    3.6T  3.1T  356G  90% /srv/dev-disk-by-uuid-5712d8c8-09ba-41d8-b9b7-798642b87770
/dev/sdp                                     7.3T  6.8T  125G  99% /srv/dev-disk-by-uuid-109042a2-c231-43ea-852a-a9bba0bd498f
/dev/sdq1                                    3.6T  3.2T  424G  89% /srv/dev-disk-by-uuid-c67fd0d7-2ed4-4e00-98dd-c1a7c168e5bd
/dev/sdm1                                    3.6T  3.0T  417G  89% /srv/dev-disk-by-uuid-0cdf8cd4-5c49-460a-a65a-6e340b53a2a4
/dev/sdb1                                    3.6T  3.2T  413G  89% /srv/dev-disk-by-uuid-907a124e-7a2b-4b94-8dbf-a79179e25a0c
merged:e635f518-3fba-469c-8719-d0b3862f09f2   65T   48T   17T  75% /srv/mergerfs/merged
folder2ram                                   7.8G  2.0G  5.9G  26% /var/log
folder2ram                                   7.8G     0  7.8G   0% /var/tmp
folder2ram                                   7.8G   11M  7.8G   1% /var/lib/openmediavault/rrd
folder2ram                                   7.8G  1.4M  7.8G   1% /var/spool
folder2ram                                   7.8G   75M  7.8G   1% /var/lib/rrdcached
folder2ram                                   7.8G  4.0K  7.8G   1% /var/lib/monit
folder2ram                                   7.8G   32K  7.8G   1% /var/cache/samba
tmpfs                                        1.6G     0  1.6G   0% /run/user/1000 
```
```
NAME   FSTYPE FSVER LABEL      UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda
├─sda1 vfat   FAT32            DF7C-6170                             505.2M     1% /boot/efi
├─sda2 ext4   1.0              a5ae8af9-04c5-456d-9e5a-ba0f6024fa5f   21.4G    60% /
└─sda3 swap   1                652402ec-93f5-4bbf-a924-728401ee249d                [SWAP]
sdb
└─sdb1 ext4   1.0   202107d010 907a124e-7a2b-4b94-8dbf-a79179e25a0c  412.6G    89% /srv/dev-disk-by-uuid-907a124e-7a2b-4b94-8dbf-a79179e25a0c
sdc
└─sdc1 ext4   1.0   202201d003 913a945f-428d-43ab-987d-eebeb24f7161  416.9G    89% /srv/dev-disk-by-uuid-913a945f-428d-43ab-987d-eebeb24f7161
sdd
└─sdd1 ext4   1.0   202205d012 67fd7113-273a-4219-bd3b-43e69df1dbb2  422.8G    88% /srv/dev-disk-by-uuid-67fd7113-273a-4219-bd3b-43e69df1dbb2
sde
└─sde1 ext4   1.0   202302d014 e0985793-e695-4008-8cc5-255be3783ebb  414.5G    94% /srv/dev-disk-by-uuid-e0985793-e695-4008-8cc5-255be3783ebb
sdf
└─sdf1 ext4   1.0   202301d013 98049d61-1c9b-4ec1-a698-0c2c1308a573  414.1G    94% /srv/dev-disk-by-uuid-98049d61-1c9b-4ec1-a698-0c2c1308a573
sdg
└─sdg1 ext4   1.0   202006d007 d5a72cf7-8b04-4475-9860-9c48735b3f23    417G    84% /srv/dev-disk-by-uuid-d5a72cf7-8b04-4475-9860-9c48735b3f23
sdh
└─sdh1 ext4   1.0   202011d008 b90366a7-6fea-4a00-b18c-0b67ce756d97  415.8G    84% /srv/dev-disk-by-uuid-b90366a7-6fea-4a00-b18c-0b67ce756d97
sdi
└─sdi1 ext4   1.0   202012d009 5712d8c8-09ba-41d8-b9b7-798642b87770  355.5G    85% /srv/dev-disk-by-uuid-5712d8c8-09ba-41d8-b9b7-798642b87770
sdj
└─sdj1 ext4   1.0   202204d011 c1051291-a5bf-42e6-93a9-8d541f08aebb  361.1G    90% /srv/dev-disk-by-uuid-c1051291-a5bf-42e6-93a9-8d541f08aebb
sdk    ext4   1.0   202302p001 13e11000-2295-486c-9292-11e95c37bbe2  124.2G    93% /srv/dev-disk-by-uuid-13e11000-2295-486c-9292-11e95c37bbe2
sdl
└─sdl1 ext4   1.0   202304d004 03db52c8-c739-494b-b96f-37f53354b185    4.2T    41% /srv/dev-disk-by-uuid-03db52c8-c739-494b-b96f-37f53354b185
sdm
└─sdm1 ext4   1.0   202003d006 0cdf8cd4-5c49-460a-a65a-6e340b53a2a4    417G    84% /srv/dev-disk-by-uuid-0cdf8cd4-5c49-460a-a65a-6e340b53a2a4
sdn
└─sdn1 ext4   1.0   202303d001 d2a25710-050e-4584-9eb8-eb1c9661433a    7.2T     0% /srv/dev-disk-by-uuid-d2a25710-050e-4584-9eb8-eb1c9661433a
sdo
└─sdo1 ext4   1.0   201907d002 5a8ed703-605e-48ec-a507-43e17f0c3504  411.8G    89% /srv/dev-disk-by-uuid-5a8ed703-605e-48ec-a507-43e17f0c3504
sdp    ext4   1.0   202211p002 109042a2-c231-43ea-852a-a9bba0bd498f  124.2G    93% /srv/dev-disk-by-uuid-109042a2-c231-43ea-852a-a9bba0bd498f
sr0
sdq
└─sdq1 ext4   1.0   201912d005 c67fd0d7-2ed4-4e00-98dd-c1a7c168e5bd  423.5G    88% /srv/dev-disk-by-uuid-c67fd0d7-2ed4-4e00-98dd-c1a7c168e5bd
```
 - A strace of the application having a problem:
   - `strace -fvTtt -s 256 -o /tmp/app.strace.txt <cmd>`
   - https://pastebin.com/JTmkhmjm

**Comment by gouthamravee** [comment]
Understood, if I need to move this post I don't mind. 

My bad, I completely missed the config. 
This is what I see in the file 

` /etc/systemd/system/srv-mergerfs-merged.mount`

```
[Unit]
Description = MergerFS mount for merged
After=network-fs.target zfs-mount.target
RequiresMountsFor=/srv/dev-disk-by-uuid-0cdf8cd4-5c49-460a-a65a-6e340b53a2a4 /srv/dev-disk-by-uuid-5712d8c8-09ba-41d8-b9b7-798642b87770 /srv/dev-disk-by-uuid-5a8ed703-605e-48ec-a507-43e17f0c3504 /srv/dev-disk-by-uuid-907a124e-7a2b-4b94-8dbf-a79179e25a0c /srv/dev-disk-by-uuid-913a945f-428d-43ab-987d-eebeb24f7161 /srv/dev-disk-by-uuid-b90366a7-6fea-4a00-b18c-0b67ce756d97 /srv/dev-disk-by-uuid-c67fd0d7-2ed4-4e00-98dd-c1a7c168e5bd /srv/dev-disk-by-uuid-d5a72cf7-8b04-4475-9860-9c48735b3f23 /srv/dev-disk-by-uuid-c1051291-a5bf-42e6-93a9-8d541f08aebb /srv/dev-disk-by-uuid-67fd7113-273a-4219-bd3b-43e69df1dbb2 /srv/dev-disk-by-uuid-98049d61-1c9b-4ec1-a698-0c2c1308a573 /srv/dev-disk-by-uuid-e0985793-e695-4008-8cc5-255be3783ebb /srv/dev-disk-by-uuid-d2a25710-050e-4584-9eb8-eb1c9661433a /srv/dev-disk-by-uuid-03db52c8-c739-494b-b96f-37f53354b185

[Mount]
What = merged:e635f518-3fba-469c-8719-d0b3862f09f2
Where = /srv/mergerfs/merged
Type = fuse.mergerfs
Options = branches=/srv/dev-disk-by-uuid-0cdf8cd4-5c49-460a-a65a-6e340b53a2a4:/srv/dev-disk-by-uuid-5712d8c8-09ba-41d8-b9b7-798642b87770:/srv/dev-disk-by-uuid-5a8ed703-605e-48ec-a507-43e17f0c3504:/srv/dev-disk-by-uuid-907a124e-7a2b-4b94-8dbf-a79179e25a0c:/srv/dev-disk-by-uuid-913a945f-428d-43ab-987d-eebeb24f7161:/srv/dev-disk-by-uuid-b90366a7-6fea-4a00-b18c-0b67ce756d97:/srv/dev-disk-by-uuid-c67fd0d7-2ed4-4e00-98dd-c1a7c168e5bd:/srv/dev-disk-by-uuid-d5a72cf7-8b04-4475-9860-9c48735b3f23:/srv/dev-disk-by-uuid-c1051291-a5bf-42e6-93a9-8d541f08aebb:/srv/dev-disk-by-uuid-67fd7113-273a-4219-bd3b-43e69df1dbb2:/srv/dev-disk-by-uuid-98049d61-1c9b-4ec1-a698-0c2c1308a573:/srv/dev-disk-by-uuid-e0985793-e695-4008-8cc5-255be3783ebb:/srv/dev-disk-by-uuid-d2a25710-050e-4584-9eb8-eb1c9661433a:/srv/dev-disk-by-uuid-03db52c8-c739-494b-b96f-37f53354b185,category.create=mfs,minfreespace=4G,fsname=merged:e635f518-3fba-469c-8719-d0b3862f09f2,defaults,allow_other,cache.files=auto-full,use_ino,dropcacheonclose=true,xattr=nosys,nonempty
```

**Comment by trapexit** [comment]
xattr=nosys

You have specificly disabled xattr so the runtime api is disabled.

**Comment by gouthamravee** [comment]
I have to wait a bit before I can apply the change. I'll close this once I've verified it works. Thank you!

**Comment by gouthamravee** [comment]
@trapexit Verified that works, thank you again. I turned xattr off because based on the readme it seems like off is the more performant option. Did I misread that?

**Comment by trapexit** [comment]
Yes, but unfortunately it isn't that simple at runtime. If you tell the kernel that xattr isn't supported (by telling mergerfs to use nosys errors) then the kernel caches that for the lifetime of the mount. There is no way for mergerfs to tell the kernel "hey... I randomly support xattr now". It is all or nothing and once it is told it isn't supported it never will send another xattr request till restarted. Nothing I can do about that.

The tool could be rewritten not to use the runtime api but that would require people to manually manage the list of required fields. I think for balance it is just the list of branches... but really I always question people needing the balance tool as it is really big hammer solution for something that many people tend to want more nuance for. Or they screwed up their settings to begin with.

**Comment by gouthamravee** [comment]
I've had xattr off for at least a year, balance seems to be working though. I don't have any qualms with turning it off and on manually since I've only used balance twice in the ~4 years I've been using mergerfs. In both cases it was because I added a brand new drive to the array and I wanted to make sure mergerfs continued to place files across all drives. I have mergerfs configed to use the drive with the most free space. 

In this case I had to restart OMV for the xattr change to be recognized and doing that is not an issue for me either. 

Would that be considered a misuse of the tool, or am I doing something wrong there? I'm worried about data loss more than anything else.

**Comment by trapexit** [comment]
I don't know exactly what you're looking to do so it is difficult to comment. You're looking to move data to the new drive assuming that newer means less likely to fail and want to move some data to the new filesystem to spread out risk? And you don't want to wait for balancing to happen naturally?

If so, for the purpose of data loss, I'm not sure this makes much sense. Prediction of failure is hard/impossible and you should just have backups of the data you need to be able to restore anyway which should negate any setup concerns except if you do something like a mergerfs pool that includes RAID setups and use epmfs or similar to clearly target specific branches. 

The only real reason I see for spreading out files is performance and that can also be accomplished by using `rand` policy so the new branch doesn't receive all new files. `pfrd` would be second best for that I think.

**Comment by gouthamravee** [comment]
Thank you for talking me through this, I appreciate it a lot. 

Most of my drives are 4TB and mostly full. I've been upgrading them to 8TB, and when I do that I end up with a mostly empty drive. It bothers me to see one drive that's mostly empty , and with my current config mergerfs will use that new drive heavily until its used up as much as the others. 

The worry about data loss was related to turning attr off then on again before doing balance. 

But seems like I should change my mergerfs config to use a different create policy, right now I'm using `most free space`. 

I'm going to let the balance finish what its doing, and then take some time to really understand the create policies better and move away from `most free space`. I agree `rand` sounds like the best option for me with `percent free rand` as the second best choice.

**Comment by trapexit** [comment]
unless you are using software that gets confused by xattr existing or not and does something weird when it happens then no... there is no risk of data loss

At the end of the day the perf of the system in this context is related to access patterns. There isn't much mergerfs or anything else can do as it can't predict the future. Unless you specifically know the pattern of access there is nothing you can practically do. If you want to keep your branches filled at similar levels and don't have much churn in your system then yes, you will need out of band replacement of files but that replacement won't do anything for perf necessarily. It will spread files around but without knowing the access patterns it could be worse. All this stuff is very contextual. If the concern is literally just "It bothers me to see one drive that's mostly empty" you may want to ask why. Is there (practical) functional or risk differences or is it just some OCD thing. I'm not saying it is for you but *a lot* of people over the years have had reasons that boiled down to "just because that's how I want it." There absolutely are some negative consequences if a new drive is given all new files but are you hitting them and what can be done about them? Don't forget you could simply create a new pool with xattr enabled and just schedule mergerfs.balance or a custom app to move stuff around as you wish out of band on a regular basis.

**Comment by gouthamravee** [comment]
I don't think any software I use on that array cares about xattr except for in this case the mergerfs tools. 

The array is read heavy compared to writes, and if I'm understanding the role of the xattr setting in mergerfs the main performance issue is related to lots of writes. So in my use case the performance difference would probably be minimal if noticeable at all. 

You're correct that the issue here is "It bothers me to see one drive that's mostly empty" 

"Don't forget you could simply create a new pool with xattr enabled " do you mean I can have two mergerfs pools with the exact same volumes under them? 

I feel like changing the create policy to random will solve my issue, and I don't think balancing is something I'll do in the future. It puts unnecessary stress on all the drives and at the end of the day I can just ignore the one out of balance drive until the whole array naturally balances out.

**Comment by trapexit** [comment]
> do you mean I can have two mergerfs pools with the exact same volumes under them?

Yes.

**Comment by gouthamravee** [comment]
That's amazing, I'll keep that in mind for any future trouble I want to get myself into. 

For now though, thank you again for helping me with this.

**Comment by trapexit** [comment]
mergerfs is just a proxy. People use the underlying filesystems out of band all the time.

https://github.com/trapexit/mergerfs#can-filesystems-be-written-to-directly-outside-of-mergerfs-while-pooled

*The* suggested way I have in all docs for "evacuating" a branch is to mount a replica of the pool minus the branch in question and rsync from the filesystem to the temporary pool.
