### ISSUE TITLE
fuse_write.cpp: write() method：The value of ffi_->direct_io、ffi_->keep_cache and ffi_->auto_cache  is always 0.

### ISSUE THREAD

**Issue by Brickman-MrSun** [trapexit/mergerfs#1179]
**Describe the bug**

Whatever cache.file's strategy is set to "full" or "default" or something else，
fuse_write.cpp: write() method：The value of ffi_->direct_io、ffi_->keep_cache and ffi_->auto_cache  is always 0.

**Please be sure to use latest release of mergerfs to ensure the issue still exists. Not your distro's latest but the latest official release.**

The version I used was “mergerfs-latest-release”

**To Reproduce**

Steps to reproduce the behavior. List **all** steps to reproduce. **All** settings.

Please simplify the reproduction as much as possible.
1、Add print debugging to the method of  fuse_write.cpp :write() method and fuse_write.cpp: write() method 
to prints three values：ffi_->direct_io、ffi_->keep_cache and ffi_->auto_cache（by syslog_error() method）

2、compile

3、/usr/local/bin/mergerfs -o threads=128,minfreespace=1024 ,lazy-umount-mountpoint=true ,cache.files=off /tmp/dir1:/tmp/dir2:/tmp/dir3 /tmp/mergerfs_Dir/

4、Upload a file to the mergerfs directory--/tmp/mergerfs_Dir/

5、cat /var/log/messages
May 10 16:20:42 localhost mergerfs[779]: scz_print---fuse_creat.cpp: creat()------ffi_->direct_io = 1,ffi_->keep_cache = 0,ffi_->auto_cache = 0
May 10 16:20:42 localhost mergerfs[779]: scz_print---fuse_write.cpp: write()------ffi_->direct_io = 0,ffi_->keep_cache = 0,ffi_->auto_cache = 0

**Expected behavior**

fuse_write.cpp: write()------ffi_->direct_io = 0,ffi_->keep_cache = 0,ffi_->auto_cache = 0  Should be
   ffi_->direct_io = 1,ffi_->keep_cache = 0,ffi_->auto_cache = 0

**System information:**

 - OS, kernel version: Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Wed Nov 12 01:22:24 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
 - mergerfs version: mergerfs version: unknown
 - mergerfs settings
 - List of drives, filesystems, & sizes:
   - `df -h`
/dev/sdb        2.9G  310M  2.5G   12% /tmp/dir1
/dev/sdc        2.9G   50M  2.7G    2% /tmp/dir2
/dev/sdd        2.9G  110M  2.7G    4% /tmp/dir3
1:2:3           8.7G  468M  7.8G    6% /tmp/mergerfs_Dir

   - `lsblk -f`
sdb    ext4                                      c5e1a536-1f7d-4411-be90-9a6909440827 /tmp/dir1
sdc    ext4                                      34b8513d-81fa-4706-820d-0a5490ac2284 /tmp/dir2
sdd    ext4                                      3829895c-16cc-434f-abe2-f37cd7afec3c /tmp/dir3

**Additional context**

**Comment by trapexit** [comment]
Could you explain the reason you think this is a bug?

Those values matter for `create` and `open`. They are used to pass data *to* the kernel. Write is taking data *from* the kernel. The data isn't kept around because it isn't important.

**Comment by trapexit** [comment]
This is not a bug in the sense that value is given *to* the kernel. It does not come *from* the kernel. This is common in libfuse to not set certain values in data structures. This is one such case.

The bug is in fuse_write expecting information to be there.

**Comment by Brickman-MrSun** [comment]
Hello，Mr. trapexit：

     Thanks for your prompt reply！
    I don't know much about this mechanism, but I see that there are judgments of ffi_->direct_io value in fuse_write.cpp: write(), when the value of  ffi_->direct_io is 1, execute the  function of  write_direct_io (), when the value of  ffi_->direct_io is 0, execute the  function of  write_regular(),So my personal understanding is that this value will pass the cache.file setting.
    However, when cache.file set the default value,the values of ffi_->direct_io、ffi_->keep_cache and ffi_->auto_cache are 0，when cache.file is set to full,the values  are both still going to be 0。So aren't these values something we can control from cache.file?
    



     










At 2023-05-11 00:19:08, "trapexit" ***@***.***> wrote:

This is not a bug in the sense that value is given to the kernel. It does not come from the kernel. This is common in libfuse to not set certain values in data structures. This is one such case.

The bug is in fuse_write expecting information to be there.

**Comment by trapexit** [comment]
As I mentioned before the values are set *for* the kernel. Not *from* the kernel. It is a bug in fuse_write to check for the value like that.

**Comment by Brickman-MrSun** [comment]
In fact, I wanted to test the read/write performance of "cache.files" with different values (full, autofull, partial or off).However, in the actual test, the performance of bulk reads and writes did not vary much regardless of the value of "cache.files" set, so I wanted to see how the code logic worked.Currently, the value of "cache.files" determines the values of ffi_->direct_io, ffi_->keep_cache, and ffi_->auto_cache, but these values are only used in the fuse_creat.cpp: creat () method.Therefore, I would like to ask you how to enable or disable page caching by setting different "cache.files" values.

**Comment by trapexit** [comment]
Those values are set on demand as needed in fuse_open.cpp and fuse_create.cpp. That is all that is needed. The value is given TO the kernel to tell it what to do. It is not relevant for the write request except how the kernel will interpret the return value.

https://github.com/trapexit/mergerfs/blob/latest-release/src/fuse_open.cpp#L119
https://github.com/trapexit/mergerfs/blob/latest-release/src/fuse_create.cpp#L56

There is nothing you need to do but what is described in the docs... set cache.files=X. That's it.

**Comment by Brickman-MrSun** [comment]
Mr. trapexit，Are there any recent plans to quota mergerfs subdirectories？

**Comment by trapexit** [comment]
Please create a new discussion or issue to discuss new topics.

But to answer the question, no. There is no practical way to do that.
