### ISSUE TITLE
Weird behavior, missing mount in mergerfs

### ISSUE THREAD

**Issue by Moletrix** [trapexit/mergerfs#1182]
Hey all,

I have a question regarding Mergerfs. A little bit of context, I have 2 servers, 1 old server where everything is working fine and a new server that will become the permanent server. (Migration ongoing)
My mergerfs contains 1 rclone mount and 1 local folder. I copied the files from rclone and mergerfs to the new server a couple of days ago. Now, This afternoon, My rclone mount wasn't visible anymore. When I run the mergerfs command with the rclone mount and the local folder, For 5 a 10 seconds, All files are visible but they dissapear again from mergerfs. You can see in this screenshot within 5 seconds after mounting a folder from rclone mount. 
![image](https://github.com/trapexit/mergerfs/assets/38918712/b712722a-458c-44bc-8bdc-255e829a053d)

I'm sure that this is mergerfs that is doing weird because the rclone mount is working fine. (R/W is working fine.)
Is there an option to see some debug logs from what's going on here?

**Comment by trapexit** [comment]
Please provide details as requested in the ticket template.
