### ISSUE TITLE
Why new files inside a folder cannot be created in the other disk after merging

### ISSUE THREAD

**Issue by fishfree** [trapexit/mergerfs#1192]
On Debian 11, `sudo apt install mergerfs`

My disks info:
```
$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0  800G  0 disk 
├─sda1   8:1    0  792G  0 part /
├─sda2   8:2    0    1K  0 part 
└─sda5   8:5    0    8G  0 part [SWAP]
sdb      8:16   0  500G  0 disk /data1
sdc      8:32   0  400G  0 disk /data2
sr0     11:0    1 1024M  0 rom  
```

My /etc/fstab info:
```
UUID=9ba2ecd3-9e4f-4d87-92c3-4c31fc8a4dd9 /data1 ext4  errors=remount-ro 0       1
UUID=cece59cc-d31d-4b21-88ef-142c004a9016 /data2 ext4  errors=remount-ro 0       1
/data1:/data2 /datamerged fuse.mergerfs   defaults,noauto,allow_other,use_ino,minfreespace=20G,ignorepponrename=true 0 0

```
There is a datafiles folder /data1/datafiles, and sdb of which the mount point is /data1 is full. However, when I try to write files inside /data1/datafiles, it said the disk is full. What I expected is that the free space on sdc would be used automatically. Of course, I used mergerfs until sdb reported 100% used.

**Comment by trapexit** [comment]
Please read the documentation. You have default create policy set which is epmfs. If that isn't the behavior you want then you need to configure a different policy.

**Comment by fishfree** [comment]
@trapexit Thank you very much for your tip. I thought default config would solve the most common problem as mine.
What do you think about this config against my problem? 
`/data1:/data2 /datamerged fuse.mergerfs   cache.files=off,dropcacheonclose=true,category.create=mfs,noauto,allow_other,use_ino,minfreespace=20G,ignorepponrename=true 0 0`

Many thanks!

**Comment by trapexit** [comment]
It's not a "problem." You had it configured differently than you wanted it to behave. If `mfs` offers you the behavior you want then yes... that is fine.

**Comment by trapexit** [comment]
What is unclear so I can improve the docs?
