### ISSUE TITLE
Hardlink problem when balancing the pool

### ISSUE THREAD

**Issue by racerlucas** [trapexit/mergerfs#1200]
### Discussed in https://github.com/trapexit/mergerfs/discussions/1199

<div type='discussions-op-text'>

<sup>Originally posted by **racerlucas** June 19, 2023</sup>
When I tried to balance the pool by mergerfs.balance, something like this happended:
before:
disk 1: 90% full
/srv/disk1/.BT/Video/Movie
--movie1.mkv
--movie2.mkv
/srv/disk1/Video/Movie
--movie1.mkv(hardlinked, no actual space occupied)
--movie2.mkv(hardlinked, no actual space occupied)
disk 2: 80% full

after:
disk 1: 90% full
/srv/disk1/.BT/Video/Movie
--movie1.mkv
--movie2.mkv
disk 2: 90% full
/srv/disk2/Video/Movie
--movie1.mkv(actual space occupied)
--movie2.mkv(actual space occupied)

is that a bug? or I can fix that by changing some settings?</div>

**Comment by trapexit** [comment]
mergerfs.balance is a very simple tool only intended for using in bespoke situations.  It doesn't consider links. 

You can use a standard dedup tool to "fix" it.

**Comment by trapexit** [comment]
"after each balancing"

Why are you balancing? As I said... this isn't intended to be casually used. mergerfs isn't Drive Pool. It isn't intended to need to be "rebalanced" regularly.

**Comment by trapexit** [comment]
There is never going to be a perfect rebalancing tool. Everyone has their own requirements. Some people want old data transferred to the new drive. Some want specific sets of data. The recommended way is to add the new filesystem to mergerfs, create a totally new pool minus the new filesystem, and mv/rsync the data you want over. All this tool does is pick a file at random from the most full filesystem and move it to the least filled filesystem. Managing links, prioritizing, etc would be a much bigger endeavor.

**Comment by racerlucas** [comment]
So I should just delete the old pool, create a new pool and balance it manually?

**Comment by trapexit** [comment]
Without you explaining what you want the outcome to be I can't exactly recommend something specific. What I explained above is the same strategy for adding or removing branches. Create *another* pool setup however you like and transfer the data to or from as needed. Same as you would do with any other set of two storage devices. I add and remove filesystems all the time to my personal setup and I've never used mergerfs.balance because it doesn't do what I want. What I want typically is to move all the content of an old drive to a new one which is best done by just using rsync.

**Comment by racerlucas** [comment]
All I want is to scale up the capability of the current pool. I think it might be OK to not moving the file at all.

**Comment by trapexit** [comment]
If that's all you want then you don't need to move anything. Add the branch and be done with it. However, as I mentioned most people have some idea about what they want from an expansion. Concerned about resiliency, performance, something. And if you're wanting to move data then you must be considering something else than just the size growing. Unless someone is running a server and performance is key (in which case mergerfs isn't the right solution for you anyway) the best strategy in my experience is just to copy oldest drive data to newest drive on the bet that: 1) older drive is more likely to fail 2) newer data sent to older drive going forward is easier to find again if it dies. That said if you have backups it doesn't matter.

**Comment by KyleSanderson** [comment]
https://github.com/pkolaczk/fclones recently removed their data destroyer option (which was default enabled, peculiar enough), so it actually works quite well now. Until there's a native way to manage files with mergerfs doing manual balances at the root is still the way to go.

Random flags below:
fclones group --hidden --no-ignore -s1M --cache /mnt/*T* > link.txt
fclones link < link.txt

**Comment by trapexit** [comment]
Not familiar with fclones but generally you use can use any random dedup tool against the mergerfs mount too. The only thing that won't deal with is if you have multiple files at the same relative path on different branches... but then you probably don't want to dedup them anyway.
