### ISSUE TITLE
Can you manually choose filesystem for a file?

### ISSUE THREAD

**Issue by danielkrajnik** [trapexit/mergerfs#1201]
It may be a really stupid question, but I can't figure out how in mergerfs do you move a specific file to another filesystem? Do you manually run `mv`?

mv **dir1**/very/very/very/very/very/long/path/to/a/file **dir2**/very/very/very/very/very/long/path/to/a/file

each time? It sounds a bit tedious with larger amounts of files in many directories. I hoped that mergerfs has some mechanism to handle it.

**Comment by trapexit** [comment]
I don't understand the question. Why would moving a file in mergerfs be any different from any other filesystem? Can you explain what exactly the problem is?

**Comment by danielkrajnik** [comment]
Sorry, I'm trying to "offload" some larger files to a slower filesystem (AWS Glacier) from a fast filesystem (Google Drive)  using [rclone](https://rclone.org/) (which inspired by your project developed its own equivalent [unionfs](https://rclone.org/union/)). 

I thought that you will be able to create a union of two filesystems, so that one filesystem (google drive) is used by default and only certain files are moved to the second filesystem (AWS).

**Comment by trapexit** [comment]
I'm sorry but I still don't understand your question. If you want to move files between the two filesystems you can use any random tool that supports it. mv, rsync, rclone, etc. If you are expecting mergerfs to move things around itself, it won't.

**Comment by danielkrajnik** [comment]
Sorry again, can I ask another question then? Is it possible for mergefs to create a union of two filesystems, so that filesystem1 is always used by default?

I can open it as another issue.

**Comment by trapexit** [comment]
If you just have questions use "Discussions" https://github.com/trapexit/mergerfs/discussions

Issues is for bugs and feature requests.

But I'm not really sure what you mean. How would you explicitly instruct to write to a particular branch? mergerfs has to work with the filesystem API provided. There is no concept in the filesystem as different backends. That is a mergerfs thing. If you want to write to a different branch just write to it directly.

**Comment by danielkrajnik** [comment]
Oh I haven't seen the discussion section. Sure, I will close this one then and reopen it there. I think that there is something obvious that I'm missing, but it probably shouldn't be in the issues.
