### ISSUE TITLE
Unable to access/list mount if created via CLI

### ISSUE THREAD

**Issue by maleadt** [trapexit/mergerfs#123]
I'm trying out mergerfs v2.3.0 on a Debian Jessie system (`make unsigned-deb && dpkg -i`) and I'm running into the issue that mounts created from `fstab` are working fine, yet manually-created mounts are not.

Illustrating the issue:

```
$ ls -la
total 28K
drwxr-xr-x 7 tim users 4,0K sep  6 09:34 ./
drwxr-xr-x 8 tim users 4,0K sep  6 09:32 ../
drwxr-xr-x 2 tim users 4,0K sep  6 09:33 .data1/
drwxr-xr-x 2 tim users 4,0K sep  6 09:33 .data2/
drwxr-xr-x 3 tim users 4,0K sep  6 09:33 .data3/
drwxr-xr-x 3 tim users 4,0K sep  6 09:33 .data4/
drwxr-xr-x 2 tim users 4,0K sep  6 09:34 mount/

$ [sudo] mergerfs '.data*' -o defaults -o allow_other mount

$ [sudo] ls -la
ls: cannot access mount: No such file or directory
total 24K
...
d????????? ? ?   ?        ?            ? mount/

$ [sudo] ls mount
ls: cannot access mount: No such file or directory
```

The bracketed `sudo` invocations mean that using `sudo` did not matter (both creating the mount as regular user, trying to list the mount point as `root`, or all combinations thereof).

Using an `fstab` entry instead yields a functional mount point. Curiously, invoking `mergerfs` with `-f` also seems to work fine:

```
$ sudo mergerfs -f '.data*' -o allow_other mount
...

$ ls
mount/

$ ls mount
my_files/
```

Happens on my Arch Linux system as well, running `mergerfs` from git master.

**Comment by evgkrsk** [comment]
Dup #117?

**Comment by maleadt** [comment]
Oh, yeah, that seems to be the issue indeed. I guess when in foreground mode no `chdir(/)` is performed, making this situation work.
