### ISSUE TITLE
cannot build  2.37.1 for musl libc, undefined reference to `malloc_trim'

### ISSUE THREAD

**Issue by pfpulux** [trapexit/mergerfs#1260]
Try to build release 2.37.1 for musl and it failed, see the [build.log](https://pf4sh.eu/build-mergerfs-2.37.1-x86_64-musl.log).

Build with the voidlinux build system `./xbps-src -a x86_64-musl pkg mergerfs`. A build for glibc is ok.

Use this `template`:

```
pkgname=mergerfs
version=2.37.1
revision=1
build_style=gnu-makefile
make_use_env=yes
hostmakedepends="automake libtool pkg-config which"
makedepends="fuse-devel"
short_desc="FUSE union filesystem"
maintainer="Pulux <pulux@pf4sh.eu>"
license="ISC"
homepage="https://github.com/trapexit/mergerfs"
distfiles="https://github.com/trapexit/mergerfs/releases/download/${version}/mergerfs-${version}.tar.gz"
checksum=5cb93b628c28105f42dc7a06f24007a961e19d5e877e91a6ec87c1b7cc611443

pre_build() {
	# we build from source, spoof release tarball
	vsed -i "s|^VERSION=.*|VERSION=$pkgver|" tools/update-version
}

post_install() {
	vlicense LICENSE
}
```

**Comment by trapexit** [comment]
It has nothing to do with malloc_trim. You are reading logs from the build config stage.

The problem is muslc you are using doesn't have thread set name function. Newer versions do. My static builds are using it on alpine. What version is void using?

**Comment by pfpulux** [comment]
The version used by voidlinux is: `musl-1.1.24`

**Comment by trapexit** [comment]
Apparently that version is marked EOL. Oddly musl added pthread_getname_np only in 2021 but setname_np back in 2016. I guess I can write my own implementation for old versions of musl for the next release.
