### ISSUE TITLE
Error installing Mergerfs on Unraid

### ISSUE THREAD

**Issue by dasmith8815** [trapexit/mergerfs#1265]
Has anyone run across this issue while installing mergerfs on Unraid?

pthread_setname_np
make[2]: *** [Makefile:125: build/fuse_loop.o] Error 1
make[2]: Leaving directory '/tmp/mergerfs/libfuse'
make[1]: *** [Makefile:104: objects] Error 2
make[1]: Leaving directory '/tmp/mergerfs/libfuse'
make: *** [Makefile:257: libfuse] Error 2
strip: 'build/mergerfs': No such file
/tmp/build-mergerfs: line 18: build/mergerfs: not found
cp: can't stat 'build/mergerfs': No such file or directory
mv: cannot stat '/mnt/user/appdata/other/rclone/mergerfs/mergerfs': No such file or directory
15.10.2023 08:47:20 INFO: *sleeping for 5 seconds
15.10.2023 08:47:25 ERROR: Mergerfs not installed successfully. Please check for errors. Exiting.

**Comment by trapexit** [comment]
It would help if you explained exactly what you were doing. If you are using the build image then you must make sure you use the latest one. However, why not just use the static build I have in every release?

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#other

**Comment by dasmith8815** [comment]
Hey Trapexit appreciate the help I am using  https://github.com/BinsonBuzz/unraid_rclone_mount    for Unraid have been using for some years now, system went down for reboot and now I am getting error when running my mount script. Looks like its failing every time with installing mergerfs -

**Comment by trapexit** [comment]
I would submit a request to them then.
