### ISSUE TITLE
Invalid argument on a glob'd drive

### ISSUE THREAD

**Issue by LotusGuy** [trapexit/mergerfs#127]
Looking at this for a possible replacement for mhddfs, but trying to mount my pooled drives I get the following:

`zentyal@zentyal:~$ sudo mergerfs -o defaults,allow_other /poolmount/Data* /MyPool/`
`fuse: invalid argument '/poolmount/Data3'`
`zentyal@zentyal:~$`

Here's a df of my mounts:

`zentyal@zentyal:~$ df -h`
`Filesystem                       Size  Used Avail Use% Mounted on`
`/dev/mapper/Zentyal--vg-root      29G   21G  7.7G  73% /`
`none                             4.0K     0  4.0K   0% /sys/fs/cgroup`
`udev                             7.9G  4.0K  7.9G   1% /dev`
`tmpfs                            1.6G  5.1M  1.6G   1% /run`
`none                              50M     0   50M   0% /run/lock`
`none                             7.9G  4.0K  7.9G   1% /run/shm`
`none                             100M     0  100M   0% /run/user`
`/dev/sdg1                        236M   67M  157M  30% /boot`
`/dev/sdc1                        1.9T  1.4T  512G  73% /poolmount/Data1`
`/dev/sdd1                        1.9T  1.2T  717G  62% /poolmount/Data2`
`/dev/sde1                        1.9T  1.3T  561G  70% /poolmount/Data3`
`/dev/sdf1                        1.9T  1.4T  523G  72% /poolmount/Data4`
`/dev/sdb1                        1.9T  967G  896G  52% /poolmount/Data5`
`/dev/sda1                        1.9T  1.1T  809G  57% /poolmount/Data6`
`/dev/sdh1                        1.9T  1.4T  479G  75% /poolmount/Parity1`
`/dev/mapper/Zentyal--vg-PlexLib   20G  2.9G   18G  15% /var/lib/plexmediaserver`
`zentyal@zentyal:~$`

Cheers.

**Comment by trapexit** [comment]
You have to escape the sources. The shell is expanding the asterisks. Use `/poolmount/Data*`

**Comment by LotusGuy** [comment]
Duhhhhh.  :-(

Now I have to get my Samba share working correctly as it isn't working quite the same as my mhddfs mount.

Cheers.
