### ISSUE TITLE
ls of pool missing files from 2 disks

### ISSUE THREAD

**Issue by LotusGuy** [trapexit/mergerfs#128]
I created a pool of 6 disks.  Doing an ls of one of the directories I only see files and directories from the 1st 4 drives.  All files and any directories not on the first 4 disks do not show up:

`zentyal@zentyal:~$ sudo mergerfs -o defaults,allow_other /poolmount/Data\* /MyPool/`
`zentyal@zentyal:~$ df -h`
`Filesystem                       Size  Used Avail Use% Mounted on`
`/dev/mapper/Zentyal--vg-root      29G   21G  7.6G  73% /`
`none                             4.0K     0  4.0K   0% /sys/fs/cgroup`
`udev                             7.9G  4.0K  7.9G   1% /dev`
`tmpfs                            1.6G  7.4M  1.6G   1% /run`
`none                              50M     0   50M   0% /run/lock`
`none                             7.9G  8.0K  7.9G   1% /run/shm`
`none                             100M     0  100M   0% /run/user`
`/dev/sdg1                        236M   67M  157M  30% /boot`
`/dev/sdc1                        1.9T  1.4T  512G  73% /poolmount/Data1`
`/dev/sdd1                        1.9T  1.2T  717G  62% /poolmount/Data2`
`/dev/sde1                        1.9T  1.3T  561G  70% /poolmount/Data3`
`/dev/sdf1                        1.9T  1.4T  523G  72% /poolmount/Data4`
`/dev/sdb1                        1.9T  968G  895G  52% /poolmount/Data5`
`/dev/sda1                        1.9T  1.1T  809G  57% /poolmount/Data6`
`/dev/sdh1                        1.9T  1.4T  479G  75% /poolmount/Parity1`
`/dev/mapper/Zentyal--vg-PlexLib   20G  2.9G   18G  15% /var/lib/plexmediaserver`
`1:2:3:4:5:6                       11T  7.0T  4.0T  65% /MyPool`
`zentyal@zentyal:~$`

`zentyal@zentyal:~$ ls -l /MyPool/Backup/`
`total 5031988`
`drwxr-xr-x  5 administrator adm                  57 Oct 23  2014 Acronis`
`-rwxrwx---+ 1 administrator adm            10813448 Feb 18  2015 arkeia.9.0.15_master_linux.fedora13_x86-64.rpm`
`-rwxrwx---+ 1 administrator adm            20188811 Feb 18  2015 arkeia.9.0.15_master_linux.generic.glibc2.11_x86-64.tar.gz`
`-rwxr-xr-x  1 zentyal       zentyal            1196 Oct 23  2014 caCertificate`
`-rwxr-xr-x  1 zentyal       zentyal            3160 Oct 23  2014 certificate`
`-rwxr-xr-x  1 zentyal       zentyal             916 Oct 23  2014 certificateKey`
`-rwxrwx---+ 1 administrator adm              260166 Sep  1 11:47 corsair.jpg`
`-rw-r--r--  1 eddie         domain users       2566 Dec 24  2014 DeepThought.pfx`
`drwxrwx---+ 3 administrator adm                  26 Sep  3 10:45 EddieHome`
`-rwxrwx---+ 1 administrator adm          4321222656 Nov 22  2012 FRANKENSTEIN_MUST_BE_DESTROYED.ISO`
`drwxrwx---+ 2 administrator adm                 103 Aug 31 11:51 md5deep`
`drwxrwx---+ 2 administrator adm                4096 Sep  1 08:33 md5 - Zero`
`drwxrwx---+ 2 administrator adm                   6 Apr  9 16:28 OpenClient`
`-rwxrwx---+ 1 administrator adm           800157184 Apr 29  2013 XC10-2.5.0.0-beta.ova`
`drwxrwx---+ 2 administrator adm                4096 Sep  2 03:15 Zentyal`
`zentyal@zentyal:~$`

These show up in the pool:

`zentyal@zentyal:~$ ls -l /poolmount/Data1/Backup/`
`total 12`
`drwxrwx---+ 4 administrator adm 41 Feb 27  2015 Acronis`
`drwxrwx---+ 2 administrator adm  6 Apr  9 16:28 OpenClient`
`drwxrwx---+ 2 administrator adm  6 Mar 25 03:00 Zentyal`

`zentyal@zentyal:~$ ls -l /poolmount/Data2/Backup/`
`total 4250256`
`drwxr-xr-x  5 administrator adm         57 Oct 23  2014 Acronis`
`-rwxrwx---+ 1 administrator adm   10813448 Feb 18  2015 arkeia.9.0.15_master_linux.fedora13_x86-64.rpm`
`-rwxrwx---+ 1 administrator adm   20188811 Feb 18  2015 arkeia.9.0.15_master_linux.generic.glibc2.11_x86-64.tar.gz`
`-rwxrwx---+ 1 administrator adm 4321222656 Nov 22  2012 FRANKENSTEIN_MUST_BE_DESTROYED.ISO`
`drwxrwx---+ 2 administrator adm          6 Apr  9 16:28 OpenClient`
`drwxrwx---+ 2 administrator adm       4096 Sep  2 03:15 Zentyal`

`zentyal@zentyal:~$ ls -l /poolmount/Data3/Backup/`
`total 68`
`drwxr-xr-x  5 administrator adm       73 Jan 27  2015 Acronis`
`-rwxr-xr-x  1 zentyal       zentyal 1196 Oct 23  2014 caCertificate`
`-rwxr-xr-x  1 zentyal       zentyal 3160 Oct 23  2014 certificate`
`-rwxr-xr-x  1 zentyal       zentyal  916 Oct 23  2014 certificateKey`
`drwxrwx---+ 2 administrator adm        6 Mar 24 09:00 OpenClient`
`drwxrwx---+ 2 administrator adm        6 Mar 25 03:00 Zentyal`

`zentyal@zentyal:~$ ls -l /poolmount/Data4/Backup/`
`total 781700`
`drwxr-xr-x  4 administrator adm                 41 Oct 23  2014 Acronis`
`-rwxrwx---+ 1 administrator adm             260166 Sep  1 11:47 corsair.jpg`
`-rw-r--r--  1 eddie         domain users      2566 Dec 24  2014 DeepThought.pfx`
`drwxrwx---+ 3 administrator adm                 26 Sep  3 10:45 EddieHome`
`drwxrwx---+ 2 administrator adm                103 Aug 31 11:51 md5deep`
`drwxrwx---+ 2 administrator adm               4096 Sep  1 08:33 md5 - Zero`
`drwxr-xr-x  2 administrator adm               4096 Sep  1 08:44 OpenClient`
`-rwxrwx---+ 1 administrator adm          800157184 Apr 29  2013 XC10-2.5.0.0-beta.ova`
`drwxrwx---+ 2 administrator adm               4096 Sep  2 03:00 Zentyal`

But these don't: 

`zentyal@zentyal:~$ ls -l /poolmount/Data5/Backup/`
`total 612228`
`drwxrwx---+ 5 administrator adm                 57 Jul 31 20:03 Acronis`
`-rwxrwx---+ 1 administrator adm             176325 Oct 19  2014 Config.pm`
`drwxrwx---+ 3 administrator adm                 20 Aug 26 12:03 EddieHome`
`-rwxrwx---+ 1 administrator adm          255852544 Aug 29 16:51 gparted-live-0.23.0-1-i586.iso`
`-rwxrwx---+ 1 administrator adm              90058 Jul 13 12:19 LeftRear.jpg`
`-rwxrwx---+ 1 administrator adm          204863488 Aug 25 15:15 lifeboat-installer-3.0.6-2.6.32_431.3.1.el6_2.x86_64.iso`
`-rwxrwx---+ 1 administrator adm                127 Jul 13 12:21 Link.txt`
`-rwxrwx---+ 1 administrator adm            2289655 Jul  2 17:03 messages`
`drwxrwx---+ 4 eddie         domain users      4096 May  8 14:23 MFTams-RHEL55-64`
`drwxrwx---+ 2 administrator adm             176128 Sep  1 00:25 OpenClient`
`-rwxrwx---+ 1 administrator adm          108103680 Aug 28 14:42 PlexMediaServer-0.9.12.11.1406-8403350-arm7.spk`
`-rwxrwx---+ 1 administrator adm              88875 Jul 13 12:18 RightRear.jpg`
`-rwxrwx---+ 1 administrator adm               5371 Jul  1 10:58 shorewall.conf`
`-rwxrwx---+ 1 administrator adm             628051 Jul  1 09:41 shorewall-init.log`
`-rwxrwx---+ 1 administrator adm             294186 Jul 20 09:52 skeleton.tgz`
`-rwxrwx---+ 1 administrator adm           54111305 Jun  4 10:15 SPE_Overview_BWilson_RChan_20150526.mov`
`-rwxrwx---+ 1 administrator adm                452 Jul  1 09:42 tunup.sh`
`-rwxrwx---+ 1 administrator adm               6048 Jun 29 09:05 UK-VPN.conf`
`-rwxrwx---+ 1 administrator adm             167569 Jul  1 09:29 UK-VPN.log`
`drwxrwx---+ 3 eddie         domain users        37 Jan 22  2013 WMQv75-POT`
`drwxrwx---+ 2 administrator adm               4096 Sep  8 03:02 Zentyal`

`zentyal@zentyal:~$ ls -l /poolmount/Data6/Backup/`
`total 1366276`
`drwxrwx---+ 4 administrator adm                 41 Mar 31 02:01 Acronis`
`-rwxrwx---+ 1 administrator adm              64644 Jul 17 10:35 BadHTTP.png`
`-rwxrwx---+ 1 administrator adm              11731 Aug 12 23:14 BogoLinux.ovpn`
`drwxrwx---+ 3 eddie         domain users        25 May 22 17:46 Danger Man V1D1`
`drwxrwx---+ 3 eddie         domain users        34 May 22 18:10 Danger Man V1D10`
`drwxrwx---+ 3 eddie         domain users        26 May 22 18:13 Danger Man V1D11`
`drwxrwx---+ 3 eddie         domain users        26 May 22 17:42 Danger Man V1D12`
`drwxrwx---+ 3 eddie         domain users        27 May 26 15:40 Danger Man V1D13`
`drwxrwx---+ 3 eddie         domain users        25 May 22 17:49 Danger Man V1D2`
`drwxrwx---+ 3 eddie         domain users        25 May 22 17:52 Danger Man V1D3`
`drwxrwx---+ 3 eddie         domain users        25 May 22 17:54 Danger Man V1D4`
`drwxrwx---+ 3 eddie         domain users        33 May 22 17:57 Danger Man V1D5`
`drwxrwx---+ 3 eddie         domain users        33 May 22 18:00 Danger Man V1D6`
`drwxrwx---+ 3 eddie         domain users        33 May 22 18:03 Danger Man V1D7`
`drwxrwx---+ 3 eddie         domain users        33 May 22 18:06 Danger Man V1D8`
`drwxrwx---+ 3 eddie         domain users        33 May 22 18:08 Danger Man V1D9`
`-rwxrwx---+ 1 administrator adm              56696 Jun 28 14:25 direct.cap`
`-rwxrwx---+ 1 administrator adm          896194242 Jul 22 19:41 exagear-desktop-armv7.tar.gz`
`-rwxrwx---+ 1 administrator adm              73070 Jul 17 10:35 GoodHTTP.png`
`-rwxr-xr-x+ 1 zentyal       zentyal        1285986 Jun 18 21:07 IMG_0135.JPG`
`-rwxr-xr-x+ 1 zentyal       zentyal        1262467 Jun 18 21:07 IMG_0136.JPG`
`drwxrwxrwx+ 3 eddie         domain users      4096 May  4 18:46 MFTsrv-Win2008-Teacher`
`-rwxrwx---+ 1 administrator adm          477102080 Jun 23 11:13 nethserver-6.6-x86_64.iso`
`drwxrwx---+ 2 administrator adm             176128 Sep  1 00:25 OpenClient`
`-rwxrwx---+ 1 administrator adm                353 Jul 22 09:24 pk-000000000697.key`
`-rwxrwx---+ 1 administrator adm              34239 Aug 16 14:08 plex.cap`
`-rwxrwx---+ 1 administrator adm           17715471 Jun 28 15:04 transcode.cap`
`-rwxrwx---+ 1 administrator adm            4977597 Jul 21 14:07 tun0.cap`
`drwxrwx---+ 2 administrator adm               4096 Sep  2 03:25 Zentyal`
`zentyal@zentyal:~$`

Cheers.

**Comment by trapexit** [comment]
What are the permissions of the Backup directories?

```
$ ls -lhd /poolmount/Data*/Backup
```

Are you using group level permissions? If so see the readme in known issues and #88.

**Comment by LotusGuy** [comment]
Didn't realise that I had them set differently:

`zentyal@zentyal:~$ ls -lhd /poolmount/Data*/Backup`
`drwxrwx---+  5 administrator adm 8.0K Mar 14 16:02 /poolmount/Data1/Backup`
`drwxr-xr-x   7 administrator adm 4.0K Apr 15 09:38 /poolmount/Data2/Backup`
`drwxr-xr-x  11 administrator adm 4.0K Apr 15 09:38 /poolmount/Data3/Backup`
`drwxr-xr-x   8 administrator adm 4.0K Sep  1 13:09 /poolmount/Data4/Backup`
`drwxrwx---+  8 administrator adm 4.0K Sep  7 15:28 /poolmount/Data5/Backup`
`drwxrwx---+ 19 administrator adm 4.0K Aug 20 13:03 /poolmount/Data6/Backup`
`zentyal@zentyal:~$`

I guess that's a side effect of mhddfs's "allow_other" that it really doesn't care about permissions because it's all running as root.

Cheers.

**Comment by trapexit** [comment]
mhddfs does some very hacky things. I can't say for sure that's the reason but with mergerfs I've yet to implement full group support. Secondary groups are not yet set when changing contexts due to their clunky and relatively expensive nature of querying. 

That said... I'm looking into ways to provide support and not impact performance. There are a few different ways which I'm currently prototyping. I hope to have something soon.

Since the user in question doesn't have "other" access and apparently isn't administrator or it's primary group is adm its unable to list the contents and silently ignored. 

What to do here isn't easy to say. Mostly if something works I ignore errors. I only return an error if everything fails. So here since I can see some directories you get a truncated view. When trying to figure out what mergerfs is doing its very useful to use the extended attributes to see what it's seeing.

I'm going to be working on some tooling to help diagnose issues such as this. Something that would compare directories or files which exist across drives and point out permission differences.

**Comment by LotusGuy** [comment]
Forcing the ls to run as "administrator" gives me the full listing and I'm guessing that adding "world read" will also make those files/directories visible.

You mention the extended attributes.  I'm guessing that this is a similar situation in that "secondary group" support isn't there, because all the directories and files belong to a "fileshare" group which (Zentyal) Samba has forced the files/directories to be members of for sharing and trying with a user of that group also doesn't work.

Lastly, do you support xattrs, which Samba 4 uses for storing Windows ACLs.

Cheers.

**Comment by trapexit** [comment]
If it's relying on secondary groups it won't currently work. If world readable (executable also for directories) things will work fine.

Yes, xattrs are supported. Please read over the readme. I've a lot of info there. I'll try to create a summary feature section so it's more obvious though.

**Comment by LotusGuy** [comment]
Yeah, it's the heavy use of secondary group that's screwing things up.

I'll keep an eye on this for future updates.

Cheers.
