### ISSUE TITLE
splice_move triggers fuse "trying to steal weird page" errors

### ISSUE THREAD

**Issue by kitkitnet** [trapexit/mergerfs#132]
I'm using the latest release with Ubuntu 14.04, but I found mergerfs try to flood the syslog with following message when trying to read some files in the mount point.

Sep 10 23:06:54 largenas kernel: [127134.904188] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.904192]   page=ffffea00016e1f80 index=8915 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.913344] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.913349]   page=ffffea0000ea4fc0 index=8916 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.913353] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.913355]   page=ffffea00003993c0 index=8917 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.913358] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.913360]   page=ffffea00023d5ac0 index=8918 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.913364] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.913366]   page=ffffea0001b0df40 index=8919 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.919126] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.919131]   page=ffffea0001625940 index=8920 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.919134] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.919136]   page=ffffea00019a4180 index=8921 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.919140] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.919142]   page=ffffea00001b7d80 index=8922 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.919145] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.919147]   page=ffffea0001422900 index=8923 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.924580] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.924585]   page=ffffea00009d1f80 index=8924 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.924589] fuse: trying to steal weird page
Sep 10 23:06:54 largenas kernel: [127134.924594]   page=ffffea0000311340 index=8925 flags=1ffff0002000029, count=1, mapcount=0, mapping=          (null)
Sep 10 23:06:54 largenas kernel: [127134.924599] fuse: trying to steal weird page

It is like hundreds of them per minutes, I just mount it without any parameter. Is it something specify to my box? 

My environment:

Kernel: Linux largenas 3.13.0-63-generic #104~precise1-Ubuntu SMP Tue Aug 18 17:03:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Fuse: /usr/local/bin/mergerfs -V
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19

**Comment by trapexit** [comment]
I've noticed the same thing on my Ubuntu 14.04.3 box as well. I've yet to figure out why it happens. The FUSE mailinglist has been unhelpful. I'm going to change the default values which seem to trigger it but I found that if you use `-ono_splice_move` it seems to stop it.

**Comment by kitkitnet** [comment]
Thanks. I can confirm the no_splice_move can suppress the kernel log in syslog. Hope you can find the root cause for that..

**Comment by rubylaser** [comment]
As a sidenote, I'm using Ubuntu 14.04.3 64 bit server, but with a 4.2 kernel instead of the default 3.13 or 3.19 kernels and I haven't seen these errors. I don't know if it's related to the kernel, but I thought I'd mention it.

**Comment by cowai** [comment]
@trapexit 
Is this fixed?

**Comment by trapexit** [comment]
Are people still experiencing it? I need the precise versions of the kernel and libfuse to report back to the developers. They were pretty sure it was addressed in newer versions but need the versions to confirm if you could be affected.

**Comment by cowai** [comment]
I just tried it on stock kernel on ubuntu trusty and no errors are seen in syslog now.

**Comment by kitkitnet** [comment]
I removed the "no_splice_move" in my mount options and  I can't reproduce it with stock kernel either (3.13.0-74-generic). 

Closing this issue now.
