### ISSUE TITLE
Mergerfs volume with a single disk pool

### ISSUE THREAD

**Issue by lcharles123** [trapexit/mergerfs#1326]
**Is your feature request related to a problem? Please describe.**
No, I want to create a mergerfs volume with only one disk in the pool, to easily edit fstab for add new disks further

**Describe the solution you'd like**
Like `/mnt/hdd0:/mnt/hdd1` is a valid combination, make `/mnt/hdd0:` be a valid combination too.

**Comment by trapexit** [comment]
The : is not required. just do '/mnt/hhd0'

**Comment by lcharles123** [comment]
Yes, it is correct. 
For some reason I was trying to mount a single disk and the mounted volume have a different size than the physical disk, but now its working as expected. Sorry for that.
