### ISSUE TITLE
Tiered caching clarification

### ISSUE THREAD

**Issue by oregonpillow** [trapexit/mergerfs#1329]
I want to setup tired caching.
Here is an excerpt from readme. I don't understand what the 2nd point means:
```
1. Create 2 mergerfs pools. One which includes just the slow devices
   and one which has both the fast devices (SSD,NVME,etc.) and slow
   devices.
2. The 'cache' pool should have the cache filesystems listed first.
...
```

what is the 'cache' pool? I assume by cache pool you mean the pool with fast + slow devices? 

So for example, would this be correct within fstab:
```
# slow + fast devices
/mnt/slow1:/mnt/slow2:/mnt/fast1    /mnt/media    fuse.mergerfs

# slow only
/mnt/slow1:/mnt/slow2               /mnt/media    fuse.mergerfs

```

thanks!

**Comment by trapexit** [comment]
The cache pool is the pool with the cache filesystems, yes.

**Comment by trapexit** [comment]
What kind of setup do you have where this setup would be beneficial?

**Comment by oregonpillow** [comment]
Thanks. Ok something like this then?
```
# slow + fast devices
/mnt/fast1:/mnt/slow1:/mnt/slow2   /mnt/media1    fuse.mergerfs <options>

# slow only
/mnt/slow1:/mnt/slow2              /mnt/media2    fuse.mergerfs <options>
```
The usecase is for a media server. I download files over usenet which can max out a 10Gb connection and write to nvme. Then, the slowest part is it takes forever to transfer the downloaded files to slow media storage. By allowing the new media to reside temporarily on nvme (tiered cache), media files would be accessible almost instantly and can be migrated to slow storage during the night for example.

**Comment by trapexit** [comment]
Yup. That ordering is most important if you are using create=ff policy and want to spill over. Some people have different ideas/strategies though so.... at the end of the day it's just about having the pool you use generally which includes the cache focused branches and the other pool just to make migration easier. Could just as well be a bespoke tool but then the policies would all need to be added to that.

**Comment by trapexit** [comment]
I'll see about adding some additional details / examples to make it more clear.

**Comment by oregonpillow** [comment]
I'll try implementing later today/tomorrow and bug you if i have more questions. Thanks again really appreciate it.

**Comment by trapexit** [comment]
np, and thanks for the support. appreciated.
