### ISSUE TITLE
Benchmarking tool

### ISSUE THREAD

**Issue by oregonpillow** [trapexit/mergerfs#1331]
**Is your feature request related to a problem? Please describe.**
With the various options available, it seems the only way to find out which settings are optimal for performance are to simply try different configurations/combinations.

**Describe the solution you'd like**
Would a benchmarking tool make sense for the project? Something that would automate some of the `dd` benchmark tests for different mergerfs options (also clear kernel caches between tests) and return a summary of results for different configurations.

Happy to try and contribute something if you think it has value.

**Comment by trapexit** [comment]
I would say "no". There are many options but they aren't *performance* options. They are functional options. They enable or disable specific, sometimes completely incompatible options. Doing a benchmark would not be meaningful unless you absolutely didn't care at all about the function of the product... which likely no one would.

**Comment by oregonpillow** [comment]
I understand, despite the options being functional I had the impression that for some options, it was less than obvious for a given system, which options should be enabled for better performance. Without reading up on all of the options so far, I wrongly assumed that some had minimal effect on functionality.

`Unfortunately, given the number of variables it has been difficult to find a single set of settings which provide optimal performance...` - from the readme Performance section.

But no worries just thought i'd ask. Thanks for quick reply

**Comment by trapexit** [comment]
The options are not performance related per se. They may *affect* performance but if it was merely a "make faster" switch it would just be enabled by default. Hence the explicit "NOTE: be sure to read about these features before changing them to understand what behaviors it may impact"
