### ISSUE TITLE
"&" sign in dirs path 

### ISSUE THREAD

**Issue by SirYaro** [trapexit/mergerfs#1333]
**Describe the bug**
Not sure if this is a bug or wrong special character escaping on my part (probably the latest), but I could swear this works some time ago (a few months probably) and now it doesn't.

Here is my mount point in fstab:
```
/home/yaro/Megas/boardgame_arch01-at_zrobione1/MEGA/Planszowe/_planszowe_P\&P_zrobione_/:/home/yaro/Megas/boardgame_arch02-at_zrobione2/MEGA/Planszowe/_planszowe_P\&P_zrobione_2/:/home/yaro/Megas/boardgame_arch03-at_archiwum3/MEGA/Archiwum3/       /home/yaro/PnP/zrobione_all/            fuse.mergerfs           x-systemd.requires=/home,defaults,allow_other,use_ino,category.create=epmfs,moveonenospc=true,minfreespace=1G   0       0
```
as a result, I'm getting displayed only "Archiwum3" directories in "zrobione_all". Two other dirs are ignored/skipped.
When I changed "P\\&P" part to "PnP" everything works fine again.

**Please be sure to use latest release of mergerfs to ensure the issue still exists. Not your distro's latest but the latest official release.**

```
$ sudo dpkg -s mergerfs
Package: mergerfs
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 1048
Maintainer: Antonio SJ Musumeci <trapexit@spawn.link>
Architecture: amd64
Version: 2.40.2~ubuntu-focal
$ 
```

**To Reproduce**

merge dirs with "&" sign in the path.

**Expected behavior**

paths with "&" sign visible at the merged mount point.

**System information:**

 - OS, kernel version: `uname -a`
` Linux yaro-desktop2 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - mergerfs version: `mergerfs -V`
` mergerfs v2.40.2`
 - mergerfs settings
`x-systemd.requires=/home,defaults,allow_other,use_ino,category.create=epmfs,moveonenospc=true,minfreespace=1G`

**Comment by trapexit** [comment]
You don't need to escape & in /etc/fstab. It isn't a delimiter or special char.

**Comment by SirYaro** [comment]
I just check it on some temporary dirs, and it seems you're right. It works perfectly now.

But I can swear it did not work without escaping some time ago. I wouldn't make my life harder without reason... I think... I hope :)
Regardless, my report makes no sense now. Sorry 4 bothering you. :)

**Comment by trapexit** [comment]
No worries. Nothing has changed here in ages. ATM I'm pretty sure : is not properly escapable but since no one ever complained just haven't gotten to it. I want to move to config file anyway.
