### ISSUE TITLE
The Debian12 mergerfs ls&df command displays an exception.

### ISSUE THREAD

**Issue by Gloryandel** [trapexit/mergerfs#1334]
Linux debian 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux
mergerfs version: 2.33.5
ArchLinux all functions are normal!
# no sudo

```
ls -la
ls: 无法访问 'pool': 权限不够
总计 72
drwxr-xr-x  7 root root 4096  5月 6日 17:59 .
drwxr-xr-x 18 root root 4096  4月19日 10:00 ..
drwxr-xr-x  1 root root    0  5月 6日 17:26 data01
drwxr-xr-x  1 root root    0  5月 6日 17:25 data02
drwxr-xr-x  1 root root    0  5月 6日 17:25 data03
drwxr-xr-x  1 root root    0  5月 6日 17:18 data04
d?????????  ? ?    ?       ?              ? pool

angel@debian /srv % df -Th
文件系统                    类型      大小  已用  可用 已用% 挂载点
/dev/sdb1                   btrfs     2.0G  3.8M  1.8G    1% /srv/data01
/dev/sde1                   btrfs     2.0G  3.8M  1.8G    1% /srv/data02
/dev/sdc1                   btrfs     2.0G  3.8M  1.8G    1% /srv/data03
/dev/sdd1                   btrfs     2.0G  3.8M  1.8G    1% /srv/data04
Mergerfs mount point not displayed！
```
# use sudo
Everything is normal
```
angel@debian /srv % sudo ls -la
总计 88
drwxr-xr-x  7 root root 4096  5月 6日 17:59 .
drwxr-xr-x 18 root root 4096  4月19日 10:00 ..
drwxr-xr-x  1 root root    0  5月 6日 17:26 data01
drwxr-xr-x  1 root root    0  5月 6日 17:25 data02
drwxr-xr-x  1 root root    0  5月 6日 17:25 data03
drwxr-xr-x  1 root root    0  5月 6日 17:18 data04
drwxr-xr-x  1 root root    0  5月 6日 17:26 pool
angel@debian /srv % sudo df -Th
文件系统                    类型           大小  已用  可用 已用% 挂载点
/dev/sdb1                   btrfs          2.0G  3.8M  1.8G    1% /srv/data01
1:2:3:4                     fuse.mergerfs  8.0G   16M  7.2G    1% /srv/pool
/dev/sde1                   btrfs          2.0G  3.8M  1.8G    1% /srv/data02
/dev/sdc1                   btrfs          2.0G  3.8M  1.8G    1% /srv/data03
/dev/sdd1                   btrfs          2.0G  3.8M  1.8G    1% /srv/data04
```
# mount default info
```
$sudo mount
/dev/sdb1 on /srv/data01 type btrfs (rw,noatime,compress=zstd:3,space_cache=v2,subvolid=5,subvol=/)
1:2:3:4 on /srv/pool type fuse.mergerfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions)
/dev/sde1 on /srv/data02 type btrfs (rw,noatime,compress=zstd:3,space_cache=v2,subvolid=5,subvol=/)
1:2:3:4 on /srv/pool type fuse.mergerfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions)
/dev/sdc1 on /srv/data03 type btrfs (rw,noatime,compress=zstd:3,space_cache=v2,subvolid=5,subvol=/)
1:2:3:4 on /srv/pool type fuse.mergerfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions)
/dev/sdd1 on /srv/data04 type btrfs (rw,noatime,compress=zstd:3,space_cache=v2,subvolid=5,subvol=/)
1:2:3:4 on /srv/pool type fuse.mergerfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions)
```

**Comment by trapexit** [comment]
As requested by the ticket template and the docs... please provide all the details about the setup. Additionally, please use the latest version as requested in the docs. I can't support old versions.

**Comment by trapexit** [comment]
I can't do anything if the old version has issues. I can't control what Debian includes. It is simply not a good use of time to check an old version of the software on a distro I can't change.

You still aren't providing enough info. Is it ran as root? You don't have allow_other set.I need all the information about the setup to comment. That's why I ask for it.

No, there is no way to stop the writes. Why would it be unsafe to snapshot while in use? If it was unsafe they wouldn't allow it.

**Comment by Gloryandel** [comment]
1. Use mergerfs run by sudo to mount, this is the mount command: `sudo mergerfs -o ignorepponrename=false,dropcacheonclose=true,moveonenospc=true /srv/data01:/srv/data02 :/srv/data03:/srv/data04 /srv/pool`
2. “Why would it be unsafe to snapshot while in use? If it was unsafe they wouldn't allow it.”：I have shared directories for samba created under pool, but these are all btrfs filesystems aggregated from different partitions, which leads to the fact that if a snapshot is taken, if files are modified (albeit for an extremely short period of time) during the time interval between separate snapshots of the subvolumes, there's a chance that files in the shared directories won't be taken at the same time during the snapshot, and it seems like it would be very confusing to do a rollback on snapshots taken from the shared directories.

**Comment by Gloryandel** [comment]
Blocking for a very small amount of time ensures that no writes are performed for a period of time, so that even though the snapshots are not simultaneous, the lack of writes ensures that the contents of the snapshots for a set of subvolumes are just a moment in time. Implementing same moment snapshots of multiple subvolumes.

**Comment by trapexit** [comment]
Please stick to 1 topic per ticket. It is too difficult to discuss multiple things in one thread.

Re 1) Right, so you don't have allow_other set so it doesn't allow other users to see it. That's by design. If you want anyone to see the share you must add allow_other. You are using old software. You need to read the docs from that version.

**Comment by Gloryandel** [comment]
So it is, thank you very much!
