### ISSUE TITLE
Can't the systemd service mount mergefs?

### ISSUE THREAD

**Issue by Gloryandel** [trapexit/mergerfs#1353]
**Describe the bug**

For the same script, running it manually is normal, and other file systems can be mounted by starting the service, except for the merger error:

service Unit

```
[Unit]
Description=Arc Init Service

[Service]
ExecStart=/etc/arc/arc-init.sh

[Install]
WantedBy=default.target
```
Call process：
arc-init.sh->  fork arc-fs.sh -> mergerfs

service log
```
Aug 07 20:36:41 Arc mergerfs[965]: /srv/pool/data was not a mount point needing to be unmounted
Aug 07 20:36:41 Arc mergerfs[967]: running basic garbage collection
Aug 07 20:36:41 Arc mergerfs[967]: threadpool (fuse.read): spawning 4 threads w/ max queue depth 4
Aug 07 20:36:41 Arc mergerfs[967]: read-thread-count=4; process-thread-count=-1; process-thread-queue-depth=-1; pin-threads=fal>
Aug 07 20:36:41 Arc mergerfs[978]: /srv/pool/appdata was not a mount point needing to be unmounted
Aug 07 20:36:41 Arc mergerfs[979]: threadpool (fuse.read): spawning 4 threads w/ max queue depth 4
Aug 07 20:36:41 Arc mergerfs[979]: read-thread-count=4; process-thread-count=-1; process-thread-queue-depth=-1; pin-threads=fal>
Aug 07 20:36:41 Arc mergerfs[979]: running basic garbage collection
```
Tips：`/srv/pool/data was not a mount point needing to be unmounted`

Running arc-fs.sh directly without using systemd can mount merges properly.

**Expected behavior**

**System information:**

 - OS：Linux Arc 6.10.3-arch1-1  x86_64 GNU/Linux
 - mergerfs version: mergerfs v2.40.2
 - mergerfs settings：mergerfs -o lazy-umount-mountpoint=true,ignorepponrename=true,dropcacheonclose=true,moveonenospc=true,minfreespace=1G /srv/mfbranch/data/data01:/srv/mfbranch/data/data02:/srv/mfbranch/data/data03:/srv/mfbranch/data/data04 /srv/pool/data

**Comment by Gloryandel** [comment]
> What about this suggests a mergerfs issue?

I'm very sorry, actually wanted to ask for help from the big guys. For some reason, mergerfs mounts don't mount whenever they appear anywhere in systemd, while those regular filesystems are unaffected. Read your how-to, there are examples of systemd mounts, so I don't know what's going on 😅

**Comment by trapexit** [comment]
I show an example in the docs that works fine. The log you show shows it mounting. When mergerfs exits normally it also logs it is exiting which isn't shown in your logs. You are saying there is a mergerfs error but I see none. You will have to provide more details about the situation if you want help.

**Comment by Gloryandel** [comment]
> I show an example in the docs that works fine. The log you show shows it mounting. When mergerfs exits normally it also logs it is exiting which isn't shown in your logs. You are saying there is a mergerfs error but I see none. You will have to provide more details about the situation if you want help.

Found `mergerfs[12237]: threadpool (fuse.read): destroying 4 threads` in the logs suggesting that the mergerfs process should have been destroyed along with the systemd exit. Sleeping the script for 60 revealed that the mergerfs instance exists while the service is running.
I solved the problem by modifying the service type to ensure that the process is not destroyed after running mergerfs.
```
[Unit]
Description=Arc Init Service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/etc/arc/arc-init.sh

[Install]
WantedBy=default.target
```
If possible, I'd like you to change the case about this part, or give a hint to other mates who don't know about systemd. systemd's default [Service] Type=simple destroys mergerfs after exit.

**Comment by trapexit** [comment]
Change what? You were allowing mergerfs to daemonize and in my example I don't. These are different usecases with different expectations and therefore need different config. There is nothing special about mergerfs with regards to how it should be run from systemd vs other software. In my example I even present how to do a setup where it has dependencies. RemainAfterExit is for indicating a service is to be considered active after it exits. mergerfs in my example is in the foreground and doesn't exit. type=oneshot is for oneshot jobs where something has a one off run. the example is not for that. It's a long lived service that is actively monitored by systemd.

**Comment by Gloryandel** [comment]
> Change what? You were allowing mergerfs to daemonize and in my example I don't. These are different usecases with different expectations and therefore need different config. There is nothing special about mergerfs with regards to how it should be run from systemd vs other software. In my example I even present how to do a setup where it has dependencies. RemainAfterExit is for indicating a service is to be considered active after it exits. mergerfs in my example is in the foreground and doesn't exit. type=oneshot is for oneshot jobs where something has a one off run. the example is not for that. It's a long lived service that is actively monitored by systemd.

It turns out that this is the case, I incorrectly understood mergerfs to mean mount btrfs, etc., and the mount script was written the same way. It executed without blocking to exit, and the mergerfs process that was started exited when the script finished.😬
