### ISSUE TITLE
mergerfs mount point disappear

### ISSUE THREAD

**Issue by rasithapr** [trapexit/mergerfs#1354]
For general questions and support please use [GitHub Discussions](https://github.com/trapexit/mergerfs/discussions) or [Discord](https://discord.gg/MpAr69V).

mergerfs v2.40.2 on debian linux 12

i used this /mnt/Disk* /mnt/Storage fuse.mergerfs cache.files=partial,dropcacheonclose=true,ignorepponrename=true,allow_other,use_ino,minfreespace=1G,fsname=mergerfs,defaults 0 0 options when i started

but now i want to change the opntions to this /mnt/Disk* /mnt/Storage fuse.mergerfs cache.files=partial,dropcacheonclose=true,ignorepponrename=true,allow_other,use_ino,category.create=mfs,minfreespace=1G,fsname=mergerfs,defaults 0 0

only change is category.create=mfs when i restarted with this options the mount folder disapper & cant mount the filder its saying folder is missing & i cant create the folder its saying folder folder exists....

how to solve this 

hope you understand the question

**Comment by trapexit** [comment]
Please follow the instructions in the support docs regarding issues like this. At the very least you need to say what version of the software you're using.

**Comment by rasithapr** [comment]
mergerfs v2.40.2

**Comment by trapexit** [comment]
Please provide the details asked for in the docs and in the ticket creation page. The docs present fully functional examples. Your comments are too vague to help with.

**Comment by rasithapr** [comment]
Im sorry im very new to github.. ill look in to the docs u mentioned. Tx
