### ISSUE TITLE
Some files from qbittorrent get corrupted

### ISSUE THREAD

**Issue by ViRb3** [trapexit/mergerfs#1361]
**Describe the bug**

System details
- Raspberry Pi 5 8GB
- Raspberry Pi OS 6.6.31+rpt-rpi-v8 / Debian 12
- mergerfs v2.40.2
- qbittorrent 4.6.7 inside Docker container
- Docker 20.10.24+dfsg1
- 4x WD 8TB external HDDs, LUKS with btrfs on top, RAID1 between each pair of disks, merged with mergerfs
- `cache.files=partial,dropcacheonclose=true,category.create=mfs`

When downloading very large torrents with many files directly onto my mergerfs mount, everything seems fine and the download completes. However, when I restart my device, some torrents will report as "Missing files". Upon doing a full recheck, some files will be flagged as invalid and begin to redownload. I had this happen twice in a row on the same torrent, and once on another torrent. I tried with `cache.files=partial` and also `cache.files=off`.

I have been downloading directly onto my disks without mergerfs using the same setup for years and never saw this issue before. Therefore, I am fairly confident it is related to my usage of mergerfs.

**Comment by trapexit** [comment]
mergerfs is used by likely thousands for that same purpose without issue. I'm not able to build out that exact setup. You're going to have to narrow down the situation yourself.

**Comment by ViRb3** [comment]
Great news, just figured this out and it has nothing to do with mergerfs!

Turns out my problematic torrents share the same root directory, and some files overlap. Therefore, based on which torrent you download last, it will overwrite the overlapping files, and on restart, the rest of the torrents will report an error. If you recheck the failing torrents, the cycle continues.

**Comment by ViRb3** [comment]
Sorry for the off-topic, but since qbittorrent seems to work with both `cache.files=off` and `partial` (presumably falls back from mmap to regular IO), do you have any recommendation on which mode is more performant/better? I did some tests and didn't spot any noticeable difference.
