### ISSUE TITLE
.mergerfs file is read-only

### ISSUE THREAD

**Issue by dannytrigo** [trapexit/mergerfs#1365]
**Describe the bug**

I cannot remove a source mount because I cannot write to the `.mergerfs` pseudo file with `xattr`.

```
# xattr -w user.mergerfs.srcmounts '-/mnt/ntfs/data-03' /mnt/data/.mergerfs
[Errno 30] Read-only file system: b'/mnt/data/.mergerfs'
```

The filesystem is not read-only, and I can write to the pool:

```
grep mergerfs /proc/mounts
mergerfs /mnt/data fuse.mergerfs rw,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
```

**System information:**

```
uname -a
Linux lister 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
mergerfs -V
mergerfs v2.40.2
```

**Comment by trapexit** [comment]
srcmounts is a read only value. `user.mergerfs.branches` is the proper value to use to change things.

**Comment by dannytrigo** [comment]
Ah, sorry for that :(
