### ISSUE TITLE
swap deb and unsigned-deb make targets

### ISSUE THREAD

**Issue by woodensoul2k** [trapexit/mergerfs#140]
I get the following message when after running the make deb on Debian 8.  I do get a deb file created.  Should I just do a generic install or just use the .deb that you provide instead?

Build message:

dpkg-deb: building package `mergerfs' in `../mergerfs_2.5.0_amd64.deb'.
make[1]: Leaving directory '/root/mergerfs'
 dpkg-genchanges  >../mergerfs_2.5.0_amd64.changes
dpkg-genchanges: including full source code in upload
 dpkg-source --after-build mergerfs
dpkg-buildpackage: full upload; Debian-native package (full source is included)
 signfile mergerfs_2.5.0.dsc
gpg: skipped "Antonio SJ Musumeci <trapexit@spawn.link>": No secret key
gpg: dpkg-sign.KW0ODF4h/mergerfs_2.5.0.dsc: clearsign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc and .changes file
Makefile:192: recipe for target 'deb' failed
make: *** [deb] Error 25

**Comment by trapexit** [comment]
It's trying to sign the file with my private keys. If you're creating a
random deb you can use `make unsigned-deb`

**Comment by trapexit** [comment]
Or use the deb provided. 

https://github.com/trapexit/mergerfs/releases

**Comment by woodensoul2k** [comment]
Thank you for the quick response. The unsigned-deb worked like a charm.
