### ISSUE TITLE
support mhddfs-like behavior regarding writing error enospc

### ISSUE THREAD

**Issue by trapexit** [trapexit/mergerfs#141]
mhddfs will move a file to another drive if it has sufficient space when a write fails due with enospc. This is particularly useful if you're using `epmfs` or similar but want a failsafe in case the primary drive fills and there exists another drive with more free space.

If enospc is received on a write find the drive with the most free space. Clone the path, Copy the file over (data and metadata) to the target, unlink the old file, swap the file handle fuse is storing, and attempt the write again. Return that write's response no matter what.

**Comment by rubylaser** [comment]
This would be an awesome feature.  I hope you can get this working.

**Comment by trapexit** [comment]
I need to do a bit more testing before I cut a release but should be ready to go.

**Comment by rubylaser** [comment]
Thanks, I just made the deb file and I'm checking it out.
