### ISSUE TITLE
Can't install in Fedora 22

### ISSUE THREAD

**Issue by imbeta** [trapexit/mergerfs#142]
make rpm fails:

[root@home]# dnf install fuse-devel libattr-devel pandoc gcc-c++ git
Last metadata expiration check performed 2:32:04 ago on Thu Sep 24 17:50:24 2015.
Package fuse-devel-2.9.4-1.fc22.x86_64 is already installed, skipping.
Package libattr-devel-2.4.47-9.fc22.x86_64 is already installed, skipping.
Package pandoc-1.13.2-2.fc22.x86_64 is already installed, skipping.
Package gcc-c++-5.1.1-4.fc22.x86_64 is already installed, skipping.
Package git-2.4.3-6.fc22.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

[root@home]# git clone https://github.com/trapexit/mergerfs.git
Cloning into 'mergerfs'...
remote: Counting objects: 1402, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1402 (delta 2), reused 0 (delta 0), pack-reused 1396
Receiving objects: 100% (1402/1402), 406.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1190/1190), done.
Checking connectivity... done.

[root@home]# cd mergerfs/
[root@home]# make rpm
/bin/rm -rf rpmbuild
/bin/rm -rf obj
/bin/rm -f src/version.hpp
/bin/rm -f "mergerfs" "mergerfs.1" clonepath
/bin/find . -name "*~" -delete
/bin/pandoc -s -t man -o mergerfs.1 README.md
./tools/git2debcl --name mergerfs > ChangeLog
/bin/git log --format='%aN <%aE>' | sort -f | uniq > AUTHORS
/bin/mkdir /tmp/.mergerfs-2.5.0_2_gde583b7.CTKxpTFX/mergerfs-2.5.0_2_gde583b7
/bin/cp -ar . /tmp/.mergerfs-2.5.0_2_gde583b7.CTKxpTFX/mergerfs-2.5.0_2_gde583b7
/bin/tar --exclude=.git -cz -C /tmp/.mergerfs-2.5.0_2_gde583b7.CTKxpTFX -f mergerfs-2.5.0_2_gde583b7.tar.gz mergerfs-2.5.0_2_gde583b7
/bin/rm -rf /tmp/.mergerfs-2.5.0_2_gde583b7.CTKxpTFX
which: no rpmbuild in (/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin)
/bin/mkdir -p rpmbuild/{BUILD,RPMS,SOURCES}
/bin/sed 's/__VERSION__/2.5.0_2_gde583b7/g' mergerfs.spec > \
        rpmbuild/SOURCES/mergerfs.spec
cp -ar mergerfs-2.5.0_2_gde583b7.tar.gz rpmbuild/SOURCES
ba rpmbuild/SOURCES/mergerfs.spec \
        --define "_topdir /tmp/mergerfs/rpmbuild"
/bin/sh: ba: command not found
Makefile:201: recipe for target 'rpm' failed
make: [rpm] Error 127 (ignored)

**Comment by trapexit** [comment]
do you have rpmbuild installed?

**Comment by trapexit** [comment]
Also... you can just use the prepared package: https://github.com/trapexit/mergerfs/releases

**Comment by imbeta** [comment]
upsss.... noob mistake.... dnf install rpm-build did the trick
Thanks for the prompt reply!

**Comment by trapexit** [comment]
I added it to the list of dependencies in the doc.
