### ISSUE TITLE
Trouble mounting several folders

### ISSUE THREAD

**Issue by imbeta** [trapexit/mergerfs#143]
I can get to work mergerfs with wildcards, for example:

This works:
[root@home]# mergerfs /mnt/disks/tvshows01:/mnt/disks/tvshows02:/mnt/disks/tvshows03:/mnt/disks/tvshows04 /mnt/mergerfs/

This doesn't:
[root@home]# mergerfs /mnt/disks/tvshows* /mnt/mergerfs/
fuse: invalid argument `/mnt/disks/tvshows03'

When mounting from fstab, it doesn't work either way:
/mnt/disks/tvshows*     /mnt/mergerfs     fuse.mergerfs     defaults,allow_other    0 0

[root@home]# mount -a
mount: wrong fs type, bad option, bad superblock on /mnt/disks/tvshows*,
       missing codepage or helper program, or other error

/mnt/disks/tvshows01:/mnt/disks/tvshows02:/mnt/disks/tvshows03:/mnt/disks/tvshows04     /mnt/mergerfs     fuse.mergerfs  defaults,allow_other     0 0

[root@home]# mount -a
mount: wrong fs type, bad option, bad superblock on /mnt/disks/tvshows01:/mnt/disks/tvshows02:/mnt/disks/tvshows03:/mnt/disks/tvshows04,
       missing codepage or helper program, or other error

**Comment by trapexit** [comment]
As the docs mention you must escape the glob tokens on the command line. The shell is expanding the * and screwing up the call to mergerfs.

As for fstab... if it's not working either way then it must be your system. There isn't enough info for me to figure out what's wrong.

**Comment by imbeta** [comment]
Should've read twice the doc, escaping the wildcard made it work.

Regarding the fstab, after further testing, closing the path with the slash made the trick:
/mnt/disks/tvshows*/    /mnt/mergerfs/     fuse.mergerfs  defaults,allow_other    0 0

**Comment by trapexit** [comment]
Strange. I'll look into that more. May be something funny with fstab and mount. Not really sure. I've not experienced that and I use a similar setup.

**Comment by mjmeehan** [comment]
Maybe the package could register an alias that disables globs? See http://stackoverflow.com/a/22945024

**Comment by trapexit** [comment]
I think it'd be best to just have better error handling. I need to do a proper usage anyway. If I see too many arguments (which is what the glob results in) then I can print a note regarding globbing.

**Comment by imbeta** [comment]
Why disable globs if they work? Closing the path with the slash makes it work.
