### ISSUE TITLE
proper usage output

### ISSUE THREAD

**Issue by imbeta** [trapexit/mergerfs#146]
How can I see the current version of mergerfs installed?

[root@home ]# mergerfs -V
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

Is this output ok? it only show FUSE

**Comment by trapexit** [comment]
There isn't a usage printout yet. If it's already mounted you can look at the extended attribute `user.mergerfs.version`. Otherwise use the package manager to see.
