### ISSUE TITLE
dedup tool

### ISSUE THREAD

**Issue by trapexit** [trapexit/mergerfs#153]
A tool which would audit a mount looking for duplicate files and offering ways to remove them.

**Comment by methanoid** [comment]
Would be nice. Not to force dedup but to flag for later dedup operations.

**Comment by trapexit** [comment]
I've got something I'm working on. I've got my own needs so I'm trying to make it useful for all my use cases for v1 and then go from there. I'm going to put these tool in a separate project since I'm writing them in Python.

**Comment by trapexit** [comment]
moved to https://github.com/trapexit/mergerfs-tools/issues/2
