### ISSUE TITLE
create package for Debian Wheezy

### ISSUE THREAD

**Issue by cfineman** [trapexit/mergerfs#154]
Tried to install your pre-built 2.6.0 DEB file and got dependency issues. Was installing on an OMV server (running Wheezy). 

I will rebuild from source if need be (was trying to avoid installing developer packages on the server) but wanted to double check that you were not aware of any issues around 2.6.0 on Wheezy. The libc/stdc++ libraries are only a minor version off fwiw.

**Comment by trapexit** [comment]
The debs provided currently are built on Ubuntu 14.04 LTS.

**Comment by trapexit** [comment]
Unless mergerfs gets picked up by Debian I'm simply not going to be able to build on all platforms. Even so mergerfs is currently using features which require more modern compiler and don't build on default Wheezy currently.

**Comment by cfineman** [comment]
Understood. Your package is compelling enough that I may jump off the OMV bandwagon and move to  Tahr. 

Thanks for your work on this!

**Comment by trapexit** [comment]
If you can install g++ 4.8 or .9 you should be able to build it fine.
That's what others have done on CentOS.

**Comment by cfineman** [comment]
Looks like the default install would be 4.7. Honestly I don't want to mess
around with trying to customize OMV because I don't know what it will do to
the various plugins. To me the plugins getting validated against a known
platform is the only real value OMV has for me.

Thanks for your advice nonetheless... i'm downloading a 1404 iso to shove
into a VM as I type :-) Can't wait to try mergerfs!

**Comment by trapexit** [comment]
Installing a newer compiler (and possible stdlibs) should not impact the system unless they are are being extremely strict on the software installed which would seem odd. It would be an addition, not replacement, of software.

**Comment by cfineman** [comment]
Came across a posting where OMV folks strongly recommended against installing the new libs ( is there  some backporting required?? I've seen general warnings about installing 4.8 on Wheezy). 

I'm no linux expert (e.g. don't want to be bothered to learn about proper ways to manage backporting or other non-standard configs) but I'm comfortable enough administering linux that moving to a more supported platform is gonna keep my life much simpler (aka less stressful :-) )

**Comment by trapexit** [comment]
I'm not sure why they'd oppose doing so as it's pretty common practice
generally.

Regardless I'm working on an alternative solution to the feature which
necessitates the newer compiler. If that pans out then I'll be able to
support Wheezy.

**Comment by trapexit** [comment]
Check the 2.7.0 release. I've built on on Wheezy.

**Comment by cfineman** [comment]
Thanks Antonio! I was so jazzed to try your package I junked omv and went
with a raw Ubuntu installation for my server.

Was it some funky c++ idiom you had to work around to use the older
compiler? I know I ran into some issues around closures and templates in g++

**Comment by trapexit** [comment]
I'm using thread local storage for the credential cache but wasn't using plain old data so it required C++11 which isn't always accessible on older platforms.
