### ISSUE TITLE
Issue with files dated Jan 1, 1970

### ISSUE THREAD

**Issue by meersjo** [trapexit/mergerfs#176]
Hey,

I've found that files dated Jan 1, 1970 01:00:00 or before don't seem to display in the merged mount, even though they're perfectly accessible in the original mount. As soon as they're touched to Jan 1, 1970 01:00:01 they become available again.

See attached screenshot for example; ls -alh command in both window run concurrently.

This is on Linux Mint Qiana (≃ Ubuntu trusty) 32-bit. Not latest from git, but commit ac03e08d314afe802be17e56c140b2972bf72ce5 (july 16 2015). Haven't had time to test with more recent, but I can't find an obvious issue report for it so submitting :-)

**Comment by meersjo** [comment]
![mergerfs-jan_1_1970-issue](https://cloud.githubusercontent.com/assets/1178044/11629319/d1f854d8-9cf7-11e5-803d-737c4b61eaaf.png)

**Comment by meersjo** [comment]
Also, mount line in fstab is this:
> /mnt/md3:/mnt/md4:/mnt/md5:/mnt/md6    /data/raid5store        fuse.mergerfs    _netdev,defaults,allow_other,func.getattr=newest                        0       0

**Comment by trapexit** [comment]
Please try with the latest. v2.8.0. Quite a bit has changed since then and a quick test seems to work fine for me.

**Comment by meersjo** [comment]
Confirmed working in 2.8.0-2. Apologies for the superfluous issue report, and thank you for the swift response.
