### ISSUE TITLE
Samba Recycling Bin not working?

### ISSUE THREAD

**Issue by knorx** [trapexit/mergerfs#182]
G'day,
I just started using mergerfs and experience issues when using a samba recyling bin on a mergerfs pool. The essence of the problem is that on my samba shares based on folders of the mergerfs pool, deleted files are directly removed without being moved to the recycle bin. Samba is at least recognizing that sth. is getting deleted (if recycle bin is not existing, it is created properly), but the files don't arrive there. I have set up another share directly on one disk participating in the pool. In this scenario the recycling bin works as expected.

Is there any known incompatibility of smb recycling bin and mergerfs?

PS: Working on 2.8.0 amd64 Debian Wheezy (OMV)

**Comment by trapexit** [comment]
How are you interacting with it? That is... what is issuing the delete? Is the recycle bin a feature of Samba or of the software interacting with it?

**Comment by knorx** [comment]
The delete is issued by a windows explorer connected to the smb share. The Recycle Bin feature is [part of Samba](https://www.samba.org/samba/docs/man/manpages/smb.conf.5.html#VFSOBJECTS). The recycle bin is called an VFS-Object in Samba. There seems to be [some abstraction layer](https://www.samba.org/samba/docs/man/Samba-Developers-Guide/vfs.html) for the file system inside Samba which then allows for these objects.
Maybe the hook they install is interfering with a similar hook installed by mergerfs? I don't really get by now what they actually do to hook into the filesystem to get the delete request.

**Comment by trapexit** [comment]
Likely when you delete through Samba the Recycle Bin feature is just moving the file to that directory. Do you have some sample config? I'll try to find documentation on the feature to see what they are doing.

**Comment by lhurt** [comment]
It works exactly this way. My system is configured this way.

My smb.conf looks this way

[global|
.... lots of lines omitted

 vfs objects = recycle
 recycle:directory_mode = 0777
 recycle:versions = Yes
 recycle:exclude_dir = tmp
 recycle:keeptree = Yes
 recycle:maxsize = 0
 recycle:exclude = *.tmp,*.temp,*.log,*.ldb
 recycle:repository = _Papierkorb_

Regards
17. Dezember 2015 17:23 Uhr, "Antonio SJ Musumeci"  schrieb:
	Likely when you delete through Samba the Recycle Bin feature is just moving the file to that directory. Do you have some sample config? I'll try to find documentation on the feature to see what they are doing.

**Comment by knorx** [comment]
This is a full blown sample `/etc/samba/smb.conf` from the system I am experiencing the issue on. Samba version is: `samba/wheezy uptodate 2:3.6.6-6+deb7u5`

@lhurt: Do you see the same problem or did you just want to provide a samba example config?

```
#======================= Global Settings =======================
[global]
workgroup = WORKGROUP
server string = %h server
dns proxy = no
log level = 1
syslog = 1
log file = /var/log/samba/log.%m
max log size = 1000
syslog only = yes
panic action = /usr/share/samba/panic-action %d
encrypt passwords = true
passdb backend = tdbsam
obey pam restrictions = yes
unix password sync = no
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = yes
socket options = TCP_NODELAY IPTOS_LOWDELAY
guest account = nobody
load printers = no
disable spoolss = yes
printing = bsd
printcap name = /dev/null
unix extensions = yes
wide links = no
create mask = 0777
directory mask = 0777
map to guest = Bad User
use sendfile = yes
aio read size = 16384
aio write size = 16384
null passwords = no
local master = yes
time server = yes
wins support = no
max protocol = SMB2
max xmit = 65535
socket options = TCP_NODELAY IPTOS_LOWDELAY SO_SNDBUF=65535 SO_RCVBUF=65535
read raw = yes
write raw = yes
max connections = 65535
max open files = 65535
netbios aliases = Machine2

#======================= Share Definitions =======================
[testpoolfolder]
path = /media/<HDD-UID>/testpoolfolder/
guest ok = no
read only = no
browseable = yes
inherit acls = yes
inherit permissions = yes
ea support = no
store dos attributes = no
vfs objects = recycle
recycle:repository = .recycle/%U
recycle:keeptree = yes
recycle:versions = yes
recycle:touch = yes
recycle:directory_mode = 0777
recycle:subdir_mode = 0700
recycle:exclude =
recycle:exclude_dir =
recycle:maxsize = 0
printable = no
create mask = 0755
force create mode = 0644
directory mask = 0755
force directory mode = 0755
hide dot files = yes
valid users = @"homies"
invalid users =
read list =
write list = @"homies"
```

**Comment by lhurt** [comment]
Hi,
just wanted to provide a workin example. This is the relevant part of my live configuration providing a recycle bin on my samba installation. Whenever a file is deleted on a share a directory called "_Papierkorb_" is created in the root folder of that share containing the file with its full path.

It works for me for years. Nevertheless there are occasions where it stops working unless all files from all affected recycle bins on all disks are deleted manually. This is very rare and I'm not sure if it's related to manual actions on one branch. Therefore I didn't investigate it.
17. Dezember 2015 22:04 Uhr, "knorx"  schrieb:
	This is a full blown sample /etc/samba/smb.conf from the system I am experiencing the issue on. Samba version is: samba/wheezy uptodate 2:3.6.6-6+deb7u5

	@lhurt (https://github.com/lhurt): Do you see the same problem or did you just want to provide a samba example config?

	#======================= Global Settings ======================= [global] workgroup = WORKGROUP server string = %h server dns proxy = no log level = 1 syslog = 1 log file = /var/log/samba/log.%m max log size = 1000 syslog only = yes panic action = /usr/share/samba/panic-action %d encrypt passwords = true passdb backend = tdbsam obey pam restrictions = yes unix password sync = no passwd program = /usr/bin/passwd %u passwd chat = *Entersnews*spassword:* %nn *Retypesnews*spassword:* %nn *passwordsupdatedssuccessfully* . pam password change = yes socket options = TCP_NODELAY IPTOS_LOWDELAY guest account = nobody load printers = no disable spoolss = yes printing = bsd printcap name = /dev/null unix extensions = yes wide links = no create mask = 0777 directory mask = 0777 map to guest = Bad User use sendfile = yes aio read size = 16384 aio write size = 16384 null passwords = no local master = yes time server = yes wins support = no max protocol = SMB2 max xmit = 65535 socket options = TCP_NODELAY IPTOS_LOWDELAY SO_SNDBUF=65535 SO_RCVBUF=65535 read raw = yes write raw = yes max connections = 65535 max open files = 65535 netbios aliases = Machine2 #======================= Share Definitions ======================= [testpoolfolder] path = /media//testpoolfolder/ guest ok = no read only = no browseable = yes inherit acls = yes inherit permissions = yes ea support = no store dos attributes = no vfs objects = recycle recycle:repository = .recycle/%U recycle:keeptree = yes recycle:versions = yes recycle:touch = yes recycle:directory_mode = 0777 recycle:subdir_mode = 0700 recycle:exclude = recycle:exclude_dir = recycle:maxsize = 0 printable = no create mask = 0755 force create mode = 0644 directory mask = 0755 force directory mode = 0755 hide dot files = yes valid users = @"homies" invalid users = read list = write list = @"homies"

**Comment by knorx** [comment]
So it looks like this is a problem of Samba only trying to use `rename` when moving files to the recycle-bin. As mergerfs does return `EXDEV`, the operation fails and it does simply removes the file (what is pretty nasty in my eyes :D).
Discussion was continued in the [Open Media Vault Forum](http://forums.openmediavault.org/index.php/Thread/12048-SMB-Recycle-Bin-on-mergerfs-pool-share-not-working/?postID=99789#post99789).

However - I wonder why EXDEV is returned at all here since the file should not change the device when being moved to trash in my scenario. But I guess this is what you suggested with your upcoming change that EXDEV should be called less often.

**Comment by trapexit** [comment]
I currently return EXDEV if it's ever cross directory because it's more complicated for me to know what's the "right thing." I'm making it smarter in the next version but EXDEV will still happen in certain situations. Should cut down on the problems.
