### ISSUE TITLE
mergerfs dedup'ing drives in statfs which are based on FUSE

### ISSUE THREAD

**Issue by rhkean** [trapexit/mergerfs#183]
df doesn't shows the sums of underlying file systems.  I've only tested this on a raspberry pi 2 with ntfs mounts.  I'll try to test on my Ubuntu install that is currently using mhddfs later this week, after I get home.

my fstab:
```
proc                   /proc           proc           defaults          0  0
LABEL=boot             /boot           vfat           defaults          0  2
LABEL=root             /               ext4           defaults,noatime  0  1
LABEL=home             /home           ext4           defaults,noatime  0  0
LABEL=var              /var            ext4           defaults,noatime  0  0
UUID=xxxxxxxxxxxxxxxx  /mnt/data/HDD1  ntfs           defaults          0  0
UUID=xxxxxxxxxxxxxxxx  /mnt/data/HDD2  ntfs           defaults          0  0
/mnt/data/*            /mnt/MEDIA      fuse.mergerfs  defaults,allow_other,minfreespace=20G,fsname=MediaPool  0  0
```
df -h output:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G  993M   14G   7% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           463M     0  463M   0% /dev/shm
tmpfs           463M  6.4M  457M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
/dev/mmcblk0p4   30G  324M   28G   2% /var
/dev/mmcblk0p3   15G   38M   14G   1% /home
/dev/mmcblk0p1   60M   20M   41M  34% /boot
/dev/sda1       1.9T   70G  1.8T   4% /mnt/data/HDD2
/dev/sdb1       4.6T  1.7T  2.9T  37% /mnt/data/HDD1
MediaPool       4.6T  1.7T  2.9T  37% /mnt/MEDIA
```
When mounted using mhddfs, MediaPool reported:
```
/dev/sda1                      1.9T   70G  1.8T   4% /mnt/data/HDD2
/dev/sdb1                      4.6T  1.7T  2.9T  37% /mnt/data/HDD1
/mnt/data/HDD1;/mnt/data/HDD2  6.4T  1.8T  4.7T  28% /mnt/MEDIA
```

**Comment by trapexit** [comment]
It works as expected on other filesystems. Perhaps its something to do with ntfs. This is the kernel based, read-only ntfs?

**Comment by rhkean** [comment]
ntfs-3g package

tonight, I'll test on my x86_64 Ubuntu server and I'll also reformat the drives at ext4 and report back.

**Comment by rhkean** [comment]
confirmed that it's related to the ntfs format.
BTW, I forgot to mention that these are USb drives

I mounted them in my Ubuntu trusty x86_64 server and saw the same thing... MediaPool mount only reported the first drive's total, used and available space.

I unmounted them, formatted both as ext4, and remounted them. the MediaPool mount them reported the summed totals.

**Comment by trapexit** [comment]
I'm betting it's that I dedup based onthe statvfs f_fsid. I recall seeing FUSE (which ntfs-3g uses) returning the same value for different mounts. I need to understand why it does and figure out another way to uniquify.

**Comment by rhkean** [comment]
I reformatted as ntfs and changed the order they are mounted....  now it's reported the sizes of the smaller drive since I'm mounting it first.

(hope this helps)

**Comment by trapexit** [comment]
Yup. It's got to be the fsid. I'm not familiar enough with FUSE's control over the FSID but clearly it's not unique. If it's constant then I can make it except that from deduping.

**Comment by jayschieber** [comment]
I have the same problem, but am using only ext4 drives.

**Comment by trapexit** [comment]
Could you please provide some working example of said problem? Are you positive you've configured mergerfs with the root mounts of the drives in question and they aren't pointing to the same drive?

**Comment by jayschieber** [comment]
I am pretty sure that they are mounted correctly.  Here is fstab:
UUID=4376900f-1458-4eef-976a-90a86cf2b0ea /media/RAID1          ext4    defaults        0       2
UUID=7a6dc2f0-c97d-46e6-ab32-e9283dd063ea /media/RAID2          ext4    defaults        0       2
UUID=39c7ce73-3cce-4237-b267-3a0ba77ded82 /media/RAID3          ext4    defaults        0       2
UUID=87040fc1-567b-44e3-8fdd-fd90d72a0e2a /media/RAID4          ext4    defaults        0       2
UUID=021b0209-dc53-4954-a088-fc92de9696db /media/RAID5          ext4    defaults        0       2
UUID=92904293-0394-47aa-9c18-28b581faad86 /media/RAID_Parity    ext4    defaults        0       2
# Use mergerfs to pool snapraid drives
/media/RAID4:/media/RAID3:/media/RAID2:/media/RAID1:/media/RAID5 /media/virtual fuse.mergerfs defaults,allow_other,minfreespace=20G 0 0

df -h gives (some lines deleted here):

Filesystem          Size  Used Avail Use% Mounted on
4:3:2:1              13T  8.7T  3.3T  74% /media/virtual
/dev/sda            2.7T  2.1T  557G  79% /media/RAID1
/dev/sdc            4.6T  3.0T  1.4T  68% /media/RAID_Parity
/dev/sdb            2.7T  2.5T   85G  97% /media/RAID2
/dev/sdh            3.6T  3.0T  450G  88% /media/RAID3
/dev/sdg            3.6T  1.3T  2.2T  38% /media/RAID4
/dev/sdf1           3.6T  680G  2.8T  20% /media/RAID5

**Comment by trapexit** [comment]
/media/virtual is listed that at boot time was /media/RAID{4,3,2,1} as it's name is "4:3:2:1"

The values look right to me.

Size = 13T ~= 3.6T(4) + 3.6T(3) + 2.7T(2) + 2.7T(1) 
Used = 8.7T ~= 1.3T(4) + 3.0T(3) + 2.5T(2) + 2.1T(1)

What's the problem? Did you change the /etc/fstab file without remounting? If you want to change the runtime you can't just change fstab. You have to use the runtime config interface as defined in the docs.

**Comment by jayschieber** [comment]
I changed fstab and rebooted.  Not sure what you mean by "runtime config interface".

**Comment by trapexit** [comment]
Have you looked at the documentation?

https://github.com/trapexit/mergerfs#runtime

If you want to look at what's actually included in the pool use the runtime interface.

```
$ xattr -p user.mergerfs.srcmounts /media/virtual/.mergerfs
```

From what you posted it was clear RAID5 was not included. As mentioned in my previous comment the name of the filesystem was "4:3:2:1" which means at mount time it was only the RAID1 - RAID4.

**Comment by jayschieber** [comment]
I did look at the documentation, but it did not work for me.   At any rate, trying another reboot did the trick.  Thanks for your help.

**Comment by trapexit** [comment]
What didn't work? If you change fstab you have to remount to have it take effect (which a reboot does). fstab is just a file. The only way to change things at runtime is via the xattr interface.
