### ISSUE TITLE
FR: Extra policies for use with files that exist on multiple source drives

### ISSUE THREAD

**Issue by meersjo** [trapexit/mergerfs#186]
I would like to propose the following extra policies:
* rr (round robin): if a file exists on multiple source points, rotate through them on every access.
* loc (lowest open count): pick the file instance that has the lowest open file descriptors on it. This might benefit from a sub-policy to specify behaviour when multiple instances have the lowest count.

I realise that both of these have quite a few potential problems, and understand that they might get refused or put on the long track :-)

My intended usecase is a (read-only) mount of multiple identical source drives, in order to optimally balance read throughput of the same files.

In more detail; I use the linux davfs implementation; but that is unfortunately limited to a single operation at a time. Being able to stick multiple instances of the same mount under a MergerFS instance would greatly increase usability, as wel as throughput on networks with connection-based throttling.

**Comment by trapexit** [comment]
Interesting usecase. My concern, though not a big one, is worrying about storing state which rr would require. I try to keep as much as possible as stateless or otherwise designed to keep from creating additional contention points. Round robin could probably be handled via "rand". For that usecase you'd ideally know the max throughput of each drive and balance that way but that's far more intrusive unless the kernel provides some moving average throughput which can be queried inexpensively.

loc is also interesting but would also require keeping shared state since the only way to find that information otherwise would be to scrape /proc/<pid>/fd/* and that'd be very expensive on every open. If files were held open for a long time then it may be OK but still not ideal.

Also, and perhaps more importantly, FUSE will be a bottleneck here. There are some features and enhancements in the works (stacked io, misc kernel improvements removing some contention points) which would really help do what you're looking for and provide near native performance but they aren't ready yet.

Could you describe more what you're looking for. If davfs is limited to one operation at a time how would this load balancing help? Wouldn't it be accessing only one file at a time? Or do you mean you'll run multiple instances of davfs pointed to a single mergerfs mount?

**Comment by meersjo** [comment]
The latter, yes - that's what I'm doing now, but simply starting two jobs at once, on on each mount point. With a single mount point I could take advantage of parallelism in the applications themselves, greatly simplyfying configuration and management.

As I said, I realize this is a considerable edge case; I'm merely hoping that there'll be enough overlap with other handling of duplicate files to make it interesting :-p

**Comment by trapexit** [comment]
Handling of duplicate files is really an edge case and one that is somewhat frustrating to handle at times. Particularly with things like `rename` which I'm currently reworking. I'm fine introducing niche features so long as they don't negatively impact the average usecase. I think there is no real impact here but figuring out something that is actually useful / functional is important. Assuming a good random  distribution `rand` would probably equal `rr`. Checking the open file count or actual read/write metrics would be best but need to find a way to do so cheaply.

I think that throughput through FUSE could negate speed advantages if there are many connections / files opened. At least until stacked io is (possibly) introduced.

Is this only for throughput? Not backup? Wouldn't RAID0 be more straight forward?

**Comment by mjmeehan** [comment]
How do you know the duplicate (named) files are equivalent? If one file is
written to via mergerfs, is the write mirrored on all covered filesystems?

**Comment by trapexit** [comment]
I think you're assuming they are the same. Something externally is making that guarantee. Which is probably simple enough but if it's critical to not have that be a problem RAID0 is better.

If davfs is readonly then you could mount mergerfs readonly as well to limit the possibility of writing through mergerfs.

**Comment by meersjo** [comment]
Fair point, @mjmeehan. In my case I'm sure because I'm explicitly mounting the same remote multiple times; but apart from that I suppose that's not MergerFS' problem.

For writes in such a system, wouldn't the "all" policy do the trick? I do agree that RAID0 would be the better solution for physical volumes, but that won't work on remote mounts.

**Comment by meersjo** [comment]
That's an interesting point, though, @trapexit  - does MergerFS go through the VFS ? How do you handle files being modified on the underlying FSes ?

**Comment by meersjo** [comment]
@trapexit, regarding the throughput limitation, given that my personal case is related to network throttling on a connection level, I'm not sure FUSE is going to be the limiting factor there. Multiple copies stack almost linear up to available bandwidth. In the general case, though, I suppose it might - I know little of FUSE.

**Comment by trapexit** [comment]
"all" does not apply to writes. Theoretically it could but I have very purposefully kept from doing that. `write` is classified as without policy actually. open and create return one file descriptor and then it's used till released. open/create could return multiple file descriptors but I really really don't want to.

Writing to multiple targets while simple on the surface is extremely complicated the moment an error occurs. Writes are inherently side effects. I can't queue up all the writes, try them, and on any error back out the whole of the request.  With other operations like `chown` it's less critical. If one fails... meh. Likely you didn't have permission so it's not a huge deal. With a write you run the risk of leaving broken, half written files around. And yes... you could maybe delete the file if you error and take it out of the immediate list of open files or similar but then you end up into a complicated situation where every single user will probably need a different failure handler.

I don't think it's an unworthy idea to try to create such a project for some usecase but it's tricky and given mergerfs is mostly intended for data dumps where you don't want or need to bother with RAID or other similar technologies... I don't feel it'd be good to introduce that complexity into it.

**Comment by trapexit** [comment]
As for modifications... it's no different from normal. If multiple apps are acting on a file there can be a logical conflict. flock and whatnot should work all the same though.

**Comment by trapexit** [comment]
Did you ever try using `rand`? Do you feel there is still a usecase for a different style of  policy?

**Comment by meersjo** [comment]
I suppose for the general case, rand would be fine. For my specific case it isn't, as I have a limit of a single transfer per mountpoint; even round-robin is not as good as the proposed loc policy would be, as it would still ignore already-finished mounts when it isn't their turn.

From the earlier discussion it's clear that the current status could work fine for the general case when reading, and only needs write/all for writing - or simply an outside synchronisation mechanism.

I don't necessarily think that my specific usecase occurs often enough to warrant a lot of time invested in the implementation, though, so I won't particularly mind if you choose to close this :-)

**Comment by trapexit** [comment]
Limiting `open`s to one per drive requires extra housekeeping that's too specialized IMO. It still feels like there could be better solutions to this. I think FUSE would be too much of a bottleneck vs say even software RAID.
