### ISSUE TITLE
mergerfs/mount point crashing

### ISSUE THREAD

**Issue by jkaberg** [trapexit/mergerfs#188]
I'm seeing crashes now and then, especially on high IO so I thought I'd debug the fs to see the cause but can't seem to find any documentation on how to do that properly?

**Comment by trapexit** [comment]
What kind of crash? mergerfs? OS? It's a userland app so debugging is the same as any other C/C++ app.

What version of mergerfs, OS, FUSE, kernel?

If you can provide a reproducible example of the issue I can investigate myself.

**Comment by jkaberg** [comment]
@trapexit Not to familiar with C/C++, could you point me in any direction? An short guide or so would really help

Got a pretty solid reproduceble error (refresh an large Plex library with metadata files crashes the mergerfs mountpoint)

**Comment by trapexit** [comment]
I suspect it's the version of libfuse or the kernel you're using. 2.9.0 is rather old and had a few known bugs.

Given I don't know what the cause (userland or kernel) it may not be too easy to debug. I may just try reproducing it with a VM. I realize it may not be easy but a newer libfuse / kernel would probably be best since no one else reports this problem. 

Can you use `mergerfs -v`? Confirm it's 2.8.0? `-V` returns only the fuse information.

**Comment by jkaberg** [comment]
```
root@dunder:~# mergerfs -v
mergerfs version: 2.8.0
FUSE library version: 2.9.0
fusermount version: 2.9.0
using FUSE kernel interface version 7.18
```

I'll see if I can upgrade the libfuse/kernel, altho I'm not sure I want to / willing to risk it :-P

**Comment by trapexit** [comment]
Understood. Unfortunately there is little (more likely nothing) I can do about the version of libfuse and kernel should they have bugs. I've a lot of users, including myself, on Ubuntu 14.04 and Debian 8 without issue.

**Comment by jkaberg** [comment]
I doubt this will help you but I'll post it here anyhow,

´´´
Jan 21 22:17:52 dunder kernel: [186706.165825] mergerfs[22663]: segfault at 7fce96f0c570 ip 00007fce96b3059c sp 00007fce80ff0300 error 4 in libfuse.so.2.9.0[7fce96b27000+2a000]
´´´

**Comment by trapexit** [comment]
Actually it does. It indicates it's crashing in the libfuse library. Testing with 2.9.4 would be ideal. Not sure I can work around any of their bugs.

**Comment by rubylaser** [comment]
@trapexit, do you have directions to upgrade Ubuntu 14.04.3 to libfuse 2.9.4 without screwing around with a bunch of dependencies? Thanks!

**Comment by trapexit** [comment]
I hadn't looked into it but from a quick experiment:

https://launchpad.net/ubuntu/wily/amd64/libfuse2/2.9.4-1ubuntu1
https://launchpad.net/ubuntu/wily/amd64/fuse/2.9.4-1ubuntu1

I just installed the Wily deb packages and it **appears** to be working alright. No dependency issues.

**Comment by rubylaser** [comment]
Well, that was super easy. Thanks, I'm running 2.9.4 libfuse now :)

**Comment by jkaberg** [comment]
Ok, so I backported fuse and libfuse from debian sid (to wheezy). Will do some tests and see how it goes, if all is well I'll post the .deb

Ping me if I forget this :wink:

**Comment by trapexit** [comment]
It seems that there are no dependencies for libfuse and fuse's dependency is libfuse. It should be as simple as finding a newer deb and dpkg -i'ing it even on debian though I've not tried.

**Comment by trapexit** [comment]
Any

**Comment by jkaberg** [comment]
@trapexit Yeah no issues, been running rock solid since 6 days

**Comment by trapexit** [comment]
Good to hear. I've included the issue in the Readme and how to fix it.
