### ISSUE TITLE
Incorrect Combined Free Space (first hdd)

### ISSUE THREAD

**Issue by j-shade** [trapexit/mergerfs#209]
The disk pooling is working wonderfully, however upon doing ' df -h ' the free space resulting is wrong..

Its clear to me it is showing the free space of the first mounted disk (as is correct in my fstab):

#<file system>   <mount point>   <type>     <options>  <dump>  <pass>
/mnt/hdd*  /mnt/data     fuse.mergerfs   defaults,allow_other 0 0

where i have mounted 4 hdd's named /mnt/hdd1..hdd2..hdd3..hdd4 etc

The output of df -h is showing:

Filesystem               Size  Used Avail Use% Mounted on
1:2:3:4                     1.9T  1.6T  247G  87% /mnt/data
/dev/sdc1                1.9T  1.8T  103G  95% /mnt/hdd3
/dev/sda1                1.9T  1.6T  247G  87% /mnt/hdd1
/dev/sde1                1.9T  1.7T  169G  91% /mnt/hdd4
/dev/sdb1                1.9T  1.7T  142G  93% /mnt/hdd2

Am I supposed to be changing some of the mount options, such as search=all?

EDIT:
Currently running Fedora 23:
Linux server 4.3.3-301.fc23.x86_64 #1 SMP Fri Jan 15 14:03:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

FUSE Versions:
mergerfs version: 2.9.0
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

**Comment by trapexit** [comment]
Found the issue. Will have a patch out shortly.
