### ISSUE TITLE
Enahancement read Priority

### ISSUE THREAD

**Issue by rubylaser** [trapexit/mergerfs#221]
I thought of a potential interesting way to use mergerfs to provide redundancy between two underlying filesystems. It would require mergerfs to support read priorities. So that it would read from the local filesystem if available. Instead of re-typing everything, please take a look here an see if you think it's possible (or a stupid idea). 

Docker Users?  Thoughts on NFS mounted config volumes.

https://forums.servethehome.com/index.php?threads/Docker-Users%3F--Thoughts-on-NFS-mounted-config-volumes%2E.8552/

**Comment by trapexit** [comment]
I don't understand what is being asked for. There is already priority based on the policy and order of mounts.

**Comment by rubylaser** [comment]
He has a local NFS share and a remote share over a fast VPN connection (100 Mbps) mounted via NFS. I was considering having him use mergerfs to pool the two NFS mounts into one highly available data store for his Plex media. 

I didn't realize that the order in /etc/fstab gave read priority based on the order of the mount points. If so, I think this may work for his purposes. 

I hope this is explainatuin makes more sense. Ultimately, he would like the pool to be available if one or the other NFS shares went down (they have mirrored content).

**Comment by trapexit** [comment]
The order matters for first found or any other were it's not searching for something across them all.
