### ISSUE TITLE
ignore drives mounted as readonly when using create policies

### ISSUE THREAD

**Issue by goldelehr** [trapexit/mergerfs#224]
Hi, 

is it possible to mount a single drive read only? I do want to merge existing files on that drive with the other drives but if i create new directories and files they must not be written to that specific drive. 

Thanks for you help!

**Comment by trapexit** [comment]
It does not support that.

Is it that you want the drive via mergerfs to be read only or that it is actually read only. The latter would be preferable. It would be easy'ish to make all creates skip drives which are read only.

**Comment by goldelehr** [comment]
It doesn't matter for me if the drive is actually read-only or not (i could mount it that way). I just need that mergerfs does not create any folders or files on that drive even if it had the most space available or the folders exist on that drive.

**Comment by trapexit** [comment]
Alright. I'll look into it.

**Comment by trapexit** [comment]
Can you try 2.11.0? 

I've added filtering of readonly devices when trying to create things. It has a greater overhead but it's likely negligible.

If it turns out to be more expensive than liked I have some ideas to cache the info (which I may do eventually anyway) but this seemed like a good first round.

**Comment by dellipse** [comment]
When I try to write to a mergerfs filesystem that has one of the sources mounted as read-only, it will not allow the creation of files on the read-write mounted source.

mergerfs -o defaults,allow_other,minfreespace=50G /mnt/read-write:/mnt/read-only /mnt/testarea

**Comment by trapexit** [comment]
Can you provide a better example to make it reproducible? It works fine for me with two tmpfs mounts.

```
$ mkdir /tmp/{rw,ro,merge}
$ sudo mount -t tmpfs -o rw,size=128M tmpfs /tmp/rw
$ sudo mount -t tmpfs -o ro,size=128M tmpfs /tmp/ro
$ touch /tmp/rw/foo
$ touch /tmp/ro/foo
touch: cannot touch '/tmp/ro/foo': Read-only file system
$ sudo mergerfs -o defaults,allow_other,minfreespace=10M /tmp/rw:/tmp/ro /tmp/merge
$ touch /tmp/merge/blah
```

**Comment by 2devnull** [comment]
I am also having this problem in 2.16.1. Have an ACD as read-only and a local read-write and writing to it states it cannot write to a read-only file system.

**Comment by trapexit** [comment]
Is it mounted read only or defacto readonly? It must be mounted readonly and reported by the kernel as readonly via statvfs calls.

**Comment by 2devnull** [comment]
Mounted with:
```
acd_cli mount --read-only --allow-other --umask 000 ${base}/encrypted/ || exit 1
encfs -S -o allow_other ${base}/encrypted/Storage ${base}/decrypted
```

Then:
`mergerfs -o defaults,allow_other,fsname=mergerfsPool,moveonenospc=true,minfreespace=20G ${base}/rw:${base}/decrypted ${base}/merge`

Same thing worked with unionfs-fuse, albeit that had the option to specify RO or RW on each item to be merged.

**Comment by trapexit** [comment]
I don't know how acd works. If the kernel doesn't tell me it's readonly then ... it must not be passing that along.

**Comment by 2devnull** [comment]
what command can I used to do that check to see what the kernel is reporting?

**Comment by 2devnull** [comment]
For my purpose, I do have a workaround which is to mount mergerfs with category.create=lfs as this should always make mergerfs create the files on the rw since it will always be less free space there than acd.

**Comment by trapexit** [comment]
There isn't one. Let me try it out. /proc/mounts indicates it is mounted with 'ro' but perhaps there is something else going on.

It looks like acd reports the available size as 100TB. That strategy could fail (though unlikely). Why not just 'ff' and mount acd last?

**Comment by trapexit** [comment]
Oh... I think it's because you have encfs mounted as rw.

**Comment by 2devnull** [comment]
ya, 'ff' would be a direct way if indicating which one to have the new files created on. I may do that, but with acd showing 100TB, both options should have the same effect. But I would go with your suggestion since it is more appropriate.

I never wanted to mount acd as read-only anyway as I loose the ability to delete stuff, all I was after was to ensure I'm not writing to it via the mergerfs point.

**Comment by trapexit** [comment]
Ah. There isn't a way to have that level of granularity. Even if I had per source rw/ro overrides to supersede what the OS tells me... it wouldn't allow you to unlink just as it wouldn't allow create or changes. It may be best to simply order them the way you want and use 'ff' and maybe use ACLs to set certain paths as read only just in case.

What precisely are you trying to do / setup?

**Comment by trapexit** [comment]
If you can just mount encfs readonly then it should work. You could then mount it again if you wanted to manually be able to add / delete / change content.

**Comment by 2devnull** [comment]
yes, that is possible although since I'm passing the mergerfs share up to a docker container, it causes me to have to stop the container also. I think what I have now with 'ff' will work just the way I would like.

Also, I didn't see an option of using encfs in read-only mode so not sure if it supported it.

**Comment by trapexit** [comment]
I'd think you would just be able to add 'ro' to the options. It's a general mount option.

BTW... the following program would let you check what the kernel thinks.


```
#include <errno.h>
#include <stdio.h>
#include <sys/statvfs.h>

int
main(int    arvc,
     char **argv)
{
  int rv;
  struct statvfs st;

  rv = statvfs(argv[1],&st);
  if(rv == -1)
    {
      perror("error:");
      return 1;
    }

  if(st.f_flag & ST_RDONLY)
    printf("read-only\n");
  else
    printf("read-write\n");

  return 0;
}
```

**Comment by RaymondSchnyder** [comment]
I have the same issues as him 2 years later.
Not with ACD, but with GSuite.
Shall i create a new issue?
the "category.create=ff" fix didnt work for me.

my issue very short: i cannot rename / move any files on the mergerfs mount and i get a "read only system" exception every time.

Sadly, i cannot enable read/write on the GSuite FUSE Mount, as this would hammer the API of Google.

my dir structure:
/mnt/local == local harddrive, writeable
/mnt/media == gdrive mount, readonly
/mnt/data == mergerfs mount

I tried to debug it with the strace command you provided, and it seems like mergerfs is searching for the file to rename/move on the local drive first, which obviously isnt there, and searches then on the gdrive mount, which there is the file it searched.
But as it cannot write to the gdrive mount, it fails on any move/rename action with a "read only filesystem" error.

**Comment by trapexit** [comment]
What do you mean "same issue"? mergerfs has long ignored readonly branches for creates.

**Comment by RaymondSchnyder** [comment]
> What do you mean "same issue"? mergerfs has long ignored readonly branches for creates.

It should, but it doesnt.
Like, not "ignoring" in the way i understand it.

attached is the log of the following command tried on shell:
"mv Zodiac\ \(2007\)\ -\ \[1080p\]\ -\ \[\].nfo.2 Zodiac\ \(2007\)\ -\ \[1080p\]\ -\ \[\].nfo.3"

[mergerfs.txt](https://github.com/trapexit/mergerfs/files/2710424/mergerfs.txt)

**Comment by trapexit** [comment]
I really can't help you if you aren't providing relevant information as described in the ticket template.

As the trace shows there is no open for writing being done and /mnt/media is seen as readonly and being skipped.

```
12339 statfs("/mnt/media", {f_type=FUSE_SUPER_MAGIC, f_bsize=4096, f_blocks=274877906944, f_bfree=260737287898, f_bavail=274877906944, f_files=1000000000, f_ffree=1000000000, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RDONLY|ST_NOSUID|ST_NODEV|ST_RELATIME}) = 0       
```
