### ISSUE TITLE
add readonly and minfreespace filters to all create policy

### ISSUE THREAD

**Issue by restfuladi** [trapexit/mergerfs#236]
Could mfs policy be done by % free? Right now smaller disks in a mixed pool get underutilized.

This tool is best in class, thanks for the hard work.

**Comment by trapexit** [comment]
I won't change `mfs`. It's "most free space" not "most percentage free space". Why not just use a different policy? Percentages are harder to follow and don't work well when you are trying to calculate the best place to put things. A small drive could be pooled with a large drive with more free space than the small has total. Do you still then want to put the file on the small drive?

If you don't care about preserving directory structure (which mfs doesn't offer) why not `fwfs`, `lfs`, or `rand`?

**Comment by restfuladi** [comment]
Percentage may not be the ideal way to do it, I agree. The main benefit of even distribution of data would be faster Snapraid sync/fix/scrub times.

**Comment by trapexit** [comment]
Not necessarily nested.

2 drives. DriveA = 128GB and DriveB = 4TB. DriveA will be skipped after a smallish amount of data unless B is largely filled already. If drives are close in size they'll balance files across them more.

If you want general spread `rand` is probably simplest. It doesn't filter using minfreespace though. I could add that and then I feel like it'd give you what you want.

**Comment by restfuladi** [comment]
Could you do Least Used Space? That would be ideal for even spread and I think Snapraid users would appreciate it.

Thanks for all your help.

**Comment by trapexit** [comment]
Hmm... `lus` would work. I'm not sure that's any better than `rand` with `minfreespace` checking. `lus` would be more precise in usage but over time should be the same as `rand`.

**Comment by trapexit** [comment]
Let me make `rand` work with `minfreespace` and try that? If it doesn't turn out the way you like I'll create `lus`.

**Comment by restfuladi** [comment]
works for me, thank you!
