### ISSUE TITLE
When moving file, keep on the same disk

### ISSUE THREAD

**Issue by yuuzhan** [trapexit/mergerfs#248]
Use case

I have two disks in a pool:
```
1:2           4.0T  2.6T  2.8T  48% /drobo
/dev/sdc1       2.0T  2.0T  4.0G 100% /mnt/d/1
/dev/sdd1       2.0T  575G  1.5T  29% /mnt/d/2
```

I have a folder on disk2:
/mnt/d/2/folder

I have a file on disk 1:
/mnt/d/2/bigFiles/Movie.avi

when I move the file on the pool to the folder

mv /drobo/bigFiles/Movie.avi /drobo/folder/

It will move it from Disk1 to Disk2

If I create an empty folder on disk2
mkdir /mnt/d/2/folder

now when I move the file, it remains on disk2

It should create the folder on disk2 if it does not exist when moving

**Comment by trapexit** [comment]
Have you read the documentation on rename?

**Comment by yuuzhan** [comment]
I fully admit that I know enough about this to be dangerous to myself and my system lol.

user.mergerfs.func.rename: all

So, if I am reading it right, it is not a path perserving policy?

Sorry for my noobyness!

```
/drobo$ xattr -l .mergerfs
user.mergerfs.srcmounts: /mnt/d/1:/mnt/d/2:/mnt/d/3
user.mergerfs.minfreespace: 4294967296
user.mergerfs.moveonenospc: false
user.mergerfs.policies: all,eplfs,epmfs,erofs,ff,lfs,mfs,newest,rand
user.mergerfs.version: 2.12.1
user.mergerfs.pid: 289
user.mergerfs.category.action: all
user.mergerfs.category.create: epmfs
user.mergerfs.category.search: ff,newest
user.mergerfs.func.access: ff
user.mergerfs.func.chmod: all
user.mergerfs.func.chown: all
user.mergerfs.func.create: epmfs
user.mergerfs.func.getattr: newest
user.mergerfs.func.getxattr: ff
user.mergerfs.func.link: all
user.mergerfs.func.listxattr: ff
user.mergerfs.func.mkdir: epmfs
user.mergerfs.func.mknod: epmfs
user.mergerfs.func.open: ff
user.mergerfs.func.readlink: ff
user.mergerfs.func.removexattr: all
user.mergerfs.func.rename: all
user.mergerfs.func.rmdir: all
user.mergerfs.func.setxattr: all
user.mergerfs.func.symlink: epmfs
user.mergerfs.func.truncate: all
user.mergerfs.func.unlink: all
user.mergerfs.func.utimens: all
```

**Comment by trapexit** [comment]
`user.mergerfs.category.create: epmfs`

epmfs = existing path, most free space 

That's path preserving.

**Comment by trapexit** [comment]
If you don't care about preserving paths then use `mfs`. But `epmfs` and `eplfs` will only clone paths across drives as an absolute last choice. And with `rename` it means it will return EXDEV to the app calling it.

**Comment by trapexit** [comment]
I just tweaked the language in the readme to clearly indicate that the `create` policy affects the `rename` behavior.

**Comment by yuuzhan** [comment]
Ahh, thank you for bearing with me on this.  I do see that I missed that.

Thanks again for your great work (and patience).

**Comment by cfineman** [comment]
Sorry to resuscitate a closed issue... I ran into this trying to move a movie file and wanted to double check the approach I used:

```
 xattr -w user.mergerfs.func.rename epmfs /storage/.mergerfs
 xattr -w user.mergerfs.func.link epmfs /storage/.mergerfs
```

That look right to you trap?

**Comment by trapexit** [comment]
Ran into what? The details on how rename works are in the docs. What precisely is the issue?
