### ISSUE TITLE
Building from tarball yields wrong version

### ISSUE THREAD

**Issue by pheerai** [trapexit/mergerfs#252]
I am maintainer of the [Arch User Repository Package of mergerfs][1].

The build of mergerfs is done via a downloaded version-tarball with the usual `make`-call (except for some basic prefix-rewrites).

When downloading the current release (2.12.2) and building it, the output of `mergerfs -v` is:
```
mergerfs version:
FUSE library version: 2.9.5
fusermount version: 2.9.5
using FUSE kernel interface version 7.19
```
i.e., Makefile can't detect the version properly.

Edit: When building using our complete "toolchain", the version is faad131, which is the current commit from the tool that manages and distributes the informations necessary to build packages (uses git)

[1]: https://aur.archlinux.org/packages/mergerfs

**Comment by trapexit** [comment]
Yes, because the version is picked up from git. I don't create manually edited version files which I'd rather not do. The changelog is similarly generated from git.

I could create a release tarball the same way I create deb / rpm packages or you could build with the git repo rather than tarball.

**Comment by trapexit** [comment]
Actually... I already create a man page manually for systems without pandoc... I may as well have release step which updates everything else. I just don't like having to remember to keep them up to date each time I make a release.

**Comment by pheerai** [comment]
I would already be glad if there was something "VERSION"-Flag for the Makefile that manually overrides the routines. Although I think auch is a really bad idea...

**Comment by trapexit** [comment]
I'll start uploading a buildable tar.gz just like I do with rpms and debs.

https://github.com/trapexit/mergerfs/releases/download/2.12.2/mergerfs-2.12.2.tar.gz

You should then just need to change

`source=("https://github.com/trapexit/mergerfs/archive/${pkgver}.tar.gz")`

to 

`source=("https://github.com/trapexit/${pkgname}/releases/download/${pkgver}/${pkgname}-${pkgver}.tar.gz")`
