### ISSUE TITLE
crash on filesystems without xattr support

### ISSUE THREAD

**Issue by uber-morlock** [trapexit/mergerfs#255]
```
# mergerfs -v
mergerfs version: 2.12.2
FUSE library version: 2.9.5
fusermount version: 2.9.5
using FUSE kernel interface version 7.19
```

I have some WebDAV mounted via **davfs2** folders merged in one **/mnt/union**
```
# df -h
Filesystem                Size  Used Avail Use% Mounted on
0:1:2:3:4:5:6:7:8:9       145G   36G  107G  25% /mnt/union
https://webdav.example   10G  2.8M   10G   1% /mnt/webdav/0
https://webdav.example   11G   32K   10G   1% /mnt/webdav/1
...
```
all action in **/mnt/union** return fail.
_UPDATE: only WRITE, excuser. READ and REMOVE not crashed it (but I know, this is not very correct definitions)_

 Example:
```
# touch /mnt/union/test_file
touch: cannot touch '/mnt/union/test_file': Software caused connection abort
```

when i do some action directly in /mnt/webdav/* -- OK
when in mounting point (like /mnt/webdav/*) nothing mounted and they are only local folder -- mergerfs working fine :)

if use **mhddfs** this trouble is absent. how to live further?

**Comment by trapexit** [comment]
Can you please provide specific details? How did you mount things? What are the settings?

**Comment by uber-morlock** [comment]
write operations at _more then one_ davfs-mounted device return "Software caused connection abort"

about **davfs2**
```
# cat /etc/fstab 
https://webdav.example /mnt/webdav/0 davfs rw,_netdev 0 0
https://webdav.example /mnt/webdav/1 davfs rw,_netdev 0 0
```
version 1.5.2 from http://download.savannah.gnu.org/releases/davfs2/

about **mergerfs**
after/before mounting from _fstab_ via **mount -a** run
`mergerfs -o defaults,allow_other,direct_io $LIST $UNION_DIR
`
or
`mergerfs -o defaults,allow_other $LIST $UNION_DIR
`
no difference, the result is the same

system Linux 3.16.0-62-generic #83~14.04.1-Ubuntu SMP Fri Feb 26 22:52:39 UTC 2016

I hope that this information is the most complete. thanks for you project, I only learning :)

**Comment by trapexit** [comment]
Okay. Reproduced it. Will look into it and report back.

**Comment by trapexit** [comment]
The issue is that davfs doesn't support xattr and mergerfs isn't failing gracefully. I'll fix it and put out a new release later today.
