### ISSUE TITLE
Folder Dates

### ISSUE THREAD

**Issue by totalretribution** [trapexit/mergerfs#261]
Hi,
I'm running mergerfs on Openmediavault and it does not return the most recent modify date for folders. Instead it seems to use the folder dates from the first pool drive listed in the fstab mount.

Thanks

**Comment by trapexit** [comment]
Yes, because you've configured it to return that. If you want it to return the value from the directory with the most recent mtime you have to set getattr to newest. Please read the docs on policies and the tips section.
