### ISSUE TITLE
Systemd doesn't manage globing

### ISSUE THREAD

**Issue by lulandco** [trapexit/mergerfs#264]
Hi,
I've just discovered mergerfs and I'm impressed in compare to other fuse union fs.

I've wrote a mount unit in systemd but I noticed that globbing doesn't work : 

    [Mount]
    What = /media/Disk:/mnt
    ...
works.

    [Mount]
    What = /media/Disk\*:/mnt
    ...
doesn't . In mountpoints there is just "/mnt" . Is there a way to make globbing works in systemd ?

Thanks

**Comment by trapexit** [comment]
I've no idea how systemd interprets things. Have you tried not escaping the * ? I wouldn't imagine it needs it.
