### ISSUE TITLE
Feature Request: 'balanced' write policy

### ISSUE THREAD

**Issue by saintdev** [trapexit/mergerfs#273]
Or possibly 'least used space'. Balance disk usage across all drives in the pool until the smallest drive reaches minfreespace. Then continue with the least used space on the remaining drives.

**Comment by trapexit** [comment]
Define "balanced".

How is "least used" different from the existing "most free"?

**Comment by saintdev** [comment]
> Define "balanced".

What I'm thinking of when I say "balanced" would attempt to spread data over all the drives equally instead of using a single drive primarily. "Least used" was just an idea of a way to achieve this.

> How is "least used" different from the existing "most free"?

If you have drives that vastly differ in their capacity, say you have a 4TB drive and a 1TB drive. With "most free", the 4TB drive will always have the most free space and will be used exclusively until you have written 3TB of data to it. With a "least used" policy, both drives would be used equally until the 1TB drive reaches minfreespace left. So after 2TB, you are now writing exclusively to the 4TB drive. "Least used" results in kind of the opposite behavior of "most free" as the pool is written to.

**Comment by trapexit** [comment]
I realized what you meant after I hit submit. 

Alright. Random would, on average, provide a similar behavior but I'll look at implementing it.

**Comment by saintdev** [comment]
Wow, that was quick! Thanks!

**Comment by trapexit** [comment]
No problem.

**Comment by saintdev** [comment]
I'm not sure this works correctly. I created a pool with two empty drives and wrote a bunch of files and they all get written to the smaller drive.

```
$ fallocate -l10G d1
$ fallocate -l50G d2
$ mkfs.ext4 d1
$ mkfs.ext4 d2
$ mount -o loop d1 /mnt/d1
$ mount -o loop d2 /mnt/d2
$ mergerfs -o defaults -o category.create=lus /mnt/d1:/mnt/d2 /mnt/pool
$ attr -g mergerfs.category.create /mnt/pool/.mergerfs
Attribute "mergerfs.category.create" had a 3 byte value for /mnt/pool/.mergerfs:
lus
$ df -h
/dev/loop0                9.7G     22.5M      9.2G   0% /mnt/d1
/dev/loop1               49.1G     51.8M     46.5G   0% /mnt/d2
1:2                      58.8G     74.3M     55.7G   0% /mnt/pool
$ du -hs /path/to/files
681.1M  /path/to/files
$ cp -r /path/to/files /mnt/pool/
$ df -h
/dev/loop0                9.7G    703.5M      8.5G   7% /mnt/d1
/dev/loop1               49.1G     51.8M     46.5G   0% /mnt/d2
1:2                      58.8G    755.4M     55.0G   1% /mnt/pool
$  ls /mnt/d1 /mnt/d2
/mnt/d1:
files  lost+found

/mnt/d2:
lost+found
```

**Comment by trapexit** [comment]
Probably because you didn't format them with `-m 0`. The available disk space is not represented correctly in df because of the reserve. Try with no reserve. I suppose I could use f_bfree instead of f_bavail but that wouldn't be technically correct either. At least for regular users.

**Comment by saintdev** [comment]
Ok, that does work.

Looking into it, it looks like f_bfree would result in the more expected behavior even if it is not 'correct'. Though I guess you could run into issues where the policy thinks the drive available, but there are no blocks available.
