### ISSUE TITLE
mergerfs on other fuse mount

### ISSUE THREAD

**Issue by xinush** [trapexit/mergerfs#276]
Hi

First of all, thank your for the excellent tool! It has been working great for my case, combing multiple storage devices.

I am wondering if mergerfs on on top of other fuse mounts is supposed to work.  For example, mergerfs on a sshfs mount.  So far , no luck to make it work.  I also have tried the same with mhddfs and it seems like it is working ok though.

cheers!

**Comment by trapexit** [comment]
In what way does it not work? I just tested that setup and it appears to work fine.

**Comment by trapexit** [comment]
Remember that you have to have permissions properly aligned [0]. FUSE needs to be called with `allow_other` if you are running as different users. Otherwise you need to run them all as the same user.

**Comment by xinush** [comment]
Thanks for the prompt reply!

After retrying with a normal user, it works fine..

It appears the issue was when a root user is used. It just shows nothing without any message when the mergerfs-mounted directory is listed with ls:

root@lubuntu-14:~# sshfs ${remote_server}:/tmp /mnt/tmp1
root@lubuntu-14:~# **ls /mnt/tmp1**
hsperfdata_tomcat7  learn.log  tomcat7-tomcat7-tmp   #### ((( sshfs - mounted ok ))))

root@lubuntu-14:~# mergerfs -o defaults,allow_other **/mnt/tmp1**:/mnt/tmp2 /media/tmp
**root@lubuntu-14:~# ls /media/tmp
#############  ((nothing shows.  /mnt/tmp2 is just an empty dir)**

root@lubuntu-14:~# ls -al /media/
drwxr-xr-x   2 root root   4096 May  8 21:32 tmp

root@lubuntu-14:~# ps -aef | grep -i mergerfs
root      2949  2244  0 21:39 ?        00:00:00 mergerfs -o defaults,allow_other /mnt/tmp1:/mnt/tmp2 /media/tmp


cheers!

**Comment by trapexit** [comment]
Right. You have to use allow_other for both. It shows nothing because it doesn't have permission to see anything.
