### ISSUE TITLE
[Possible bug] hard linked files do not seem to have the same inode number

### ISSUE THREAD

**Issue by tgharib** [trapexit/mergerfs#277]
I'm not sure if this an intentional design decision or a bug so I figured I'd make an issue in case it is a bug.

First, my use-case: I'm currently backing up my hard-drives to the cloud. The only problem is that I very heavily use hardlinks for incremental backups and for saving space and since I'd prefer to upload less data, instead of uploading hard-linked files multiple times, I'd rather upload only one copy of the file. I'm using the command `find / -type f -links +1 -printf '%i %n %p\n'` to list all hard-linked files. Then, I sort the output by inode number and make a list of files to exclude for `duplicity` when uploading. The only roadblock is that while on a regular filesystem, `find / -type f -links +1 -printf '%i %n %p\n'` lists all hard-linked files, that doesn't seem to be the case under mergerfs. I did some investigating and I think it might be related to this (`/mnt/Combined` is the merger mountpoint and `/mnt/ExtraHDD1`, `/mnt/ExtraHDD2`, etc are the hard-drives):

```
owner@manjaro:/mnt/Combined$ mkdir test
owner@manjaro:/mnt/Combined$ cd test
owner@manjaro:/mnt/Combined/test$ echo "hello" > a
owner@manjaro:/mnt/Combined/test$ ln a b
owner@manjaro:/mnt/Combined/test$ ls -l
total 8
-rw-r--r-- 2 owner users 6 May  9 12:33 a
-rw-r--r-- 2 owner users 6 May  9 12:33 b
owner@manjaro:/mnt/Combined/test$ ls -i a
533085 a
owner@manjaro:/mnt/Combined/test$ ls -i b
533086 b
owner@manjaro:/mnt/Combined/test$ cd /mnt/ExtraHDD2/
owner@manjaro:/mnt/ExtraHDD2$ cd test
owner@manjaro:/mnt/ExtraHDD2/test$ ls -l
total 8
-rw-r--r-- 2 owner users 6 May  9 12:33 a
-rw-r--r-- 2 owner users 6 May  9 12:33 b
owner@manjaro:/mnt/ExtraHDD2/test$ ls -i a
5111810 a
owner@manjaro:/mnt/ExtraHDD2/test$ ls -i b
5111810 b
```

It seems that a and b have the same inode number under `/mnt/ExtraHDD2` but they have differing inode numbers under `/mnt/Combined`. I can hack around it by enumerating all hard-linked files under `/mnt/ExtraHDD1`, `/mnt/ExtraHDD2`, etc and then replacing "ExtraHDD*" with "Combined" if this is a show stopper.

**Comment by trapexit** [comment]
It's a design decision. FUSE either creates inodes itself or the user of the FUSE library must provide them. To provide them correctly on merged disks is way too costly. One would need to scan the entire drive and manage which files are the same. So mergerfs lets libfuse manage the inodes and as a result two files which on the original drive may be the same are given different values.

**Comment by trapexit** [comment]
Why not just backup the source drives instead of the pool? You can even discovery at runtime the list using the xattr interface if keeping the list up to date is a problem.

**Comment by tgharib** [comment]
Oh right, backing up the source drives works too. Completely forgot this is just a JBOD afterall.

Overall, I'm really happy mergerfs supports hard links at all. :)

**Comment by trapexit** [comment]
It's a non-trivial thing to support in a typical filesystem. It complicates things. Directory links are even more complicated which is why they generally are forbidden. From a creation perspective you can look at the docs on rename and link.
