### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by muyiwao221** [trapexit/mergerfs#284]
Can I just use mergerFS on drives that I previously used mhddFS on before without losing my data / running into any compatibility issues? Please let me know.

Thanks!!

**Comment by trapexit** [comment]
Yes. You can easily try it to see how it works by following the readme or details from https://github.com/trapexit/backup-and-recovery-howtos

**Comment by muyiwao221** [comment]
Alright just to be clear, I meant switching from mhddfs to mergerfs without backing up and restoring to the filesystem. Would I simply be able to mount the drives into mergerfs instead of mhddfs and still be able to access all the files? Or would the different permissions mess things up?

Thanks

**Comment by trapexit** [comment]
Yes. It's an overlay filesystem. It's not a filesystem in and of itself. Again, you can mount it as many times as you want wherever you want to fool with it.

**Comment by muyiwao221** [comment]
Thanks
