### ISSUE TITLE
Q: How does spindown / umount affect the overlayfs

### ISSUE THREAD

**Issue by mihai-stancu** [trapexit/mergerfs#286]
Hi,

I want to configure some of the merged disks to spindown after a while -- most of the time they won't be likely candidates for either reading or writing.

Will mergerfs spin them up again?

**Comment by trapexit** [comment]
Mergerfs does control the spinup or spin down of drives. The OS and drives do based on usage. Mergerfs actively queries drives as you do so if it needs info and the OS needs to spin up the dive it will do so.

**Comment by mihai-stancu** [comment]
Thank you!
