### ISSUE TITLE
Running MergeFS as container

### ISSUE THREAD

**Issue by AndreyNikiforov** [trapexit/mergerfs#292]
Is there a possibility and a benefit of running mergeFS inside as individual [docker] container?

**Comment by trapexit** [comment]
I don't see how doing so would be of any benefit. You'd need to manually mount all local mounts into the container as well as the destination. You'd lose the ability to modify mergerfs at runtime without going through the container api. And the FUSE device. And probably set it up as privileged.

Why do you want to do it? It can probably be done but I don't see any reason for it.
