### ISSUE TITLE
drop debian/ from .gitignore

### ISSUE THREAD

**Issue by rickysarraf** [trapexit/mergerfs#303]
Can you please drop debian/ from the .gitignore in the repo ?

This creates problems for me during packaging.

**Comment by trapexit** [comment]
You mean debian/files and debian/changelog?

**Comment by rickysarraf** [comment]
Actually, this can be closed. Because my packaging for Debian is different that what you have. And, in any ways, my packaging workflow does exclude upstream debian/ folder.
