### ISSUE TITLE
Mount contents empty when using fstab

### ISSUE THREAD

**Issue by hungsu** [trapexit/mergerfs#306]
Hi all,

When I use mergerfs from the command line, using `mergerfs -o defaults,allow_other /media/sf_\* /media/darknet`, I can see everything in the resulting mount just fine.

But when I use `/etc/fstab` with this line
`/media/sf_* /media/darknet fuse.mergerfs defaults,allow_other 0 0`

The resulting mount appears to have nothing inside it. Any idea what I'm doing wrong?

Few more details:
I'm running this from an Ubuntu 16 Virtualbox VM. The host OS is Windows 10. The drives I'm trying to mount are USB drives shared to the VM with Virtualbox's inbuilt auto mount feature.

**Comment by trapexit** [comment]
Have you confirmed with the runtime as to what paths it's sourcing? /media/sf_* has to exist before mergerfs comes up as the docs indicate. The globing only happens at startup and modification of the runtime value.

**Comment by hungsu** [comment]
My apologies for not replying. You're correct, those paths do not exist at the time mergerfs attempts to do its thing. I'll have to just start mergerfs a different way.

**Comment by trapexit** [comment]
If the paths are known just use them literally.
