### ISSUE TITLE
Directory is only partially moved in some circumstances

### ISSUE THREAD

**Issue by abattech** [trapexit/mergerfs#308]
/s is the mount point of mergerfs pool. 
fstab entry: /mnt/server2/pool/d* /s fuse.mergerfs category.create=epmfs,defaults,allow_other,minfreespace=50G,fsname=merged_storage,direct_io 0 0
/s/other is an existing directory
/s/nnn/XXX is an existing directory i want to move to other
/s/other/XXX does not exist
Everything is ext4
.....
mergerfs version: 2.14.0-18-gf0f8e52
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19

Now here is the actual case:

/s/nnn> mv XXX /s/other

This command completes with success. Examination of /s/nnn/XXX reveals that the directory is still there, as *some* of the content is still there. /s/other/XXX also exists, and constains the rest of content which used to reside in /s/nnn/XXX. I.e. contents of /s/nnn/XXX have been moved only partially.

I *suspect* that this happens when /s/other exists only on disks which are filled more than allowed by minfreespace param (i increased the value of the param *after* i created the contents of the fs). Perhaps, in such case mergerfs refuses to move the files. There are plenty of empty disks in the pool, so mergerfs should be able to move files appropriately, or even just do a rename within the same filled up disk (which should be OK, since a rename would *not increase* used space).

**Comment by abattech** [comment]
I think this is part of official behavior. Rename succeeds if any of renames succed. Is that right? If so, i will close the issue.

**Comment by trapexit** [comment]
Have you read over the section on [rename](https://github.com/trapexit/mergerfs#rename--link)?

Without know *precisely* what the layout across drives are, what their permissions are, what the user doing the request, and the resulting layout.... I can't comment. `mv` is one of the most complex operations you can perform as the docs explain.

**Comment by abattech** [comment]
Yes, i can imagine it is super complex. Let me try to give you enough details.

Disk1: /other exists (owned and rw by me), 56Gb free <---- close to being filled up to minfreespace
Disk2: /other exists (owned and rw by me), 19Gb free <-- overfilled
Disk3: /other does not exist, /nnn/XXX exists (owned and rw by me, 300Gb in size, no subdirectories)
Disks 4-7: Mostly empty, they contain neither /other nor /nnn, so are completely irrelevant
I am performing the move as me.
Roots of every drive is rw by me. All the structure is rw by me.

After the rename completed only partially and /s/other/XXX now exists, i was able to successfully move the files under /s/XXX in a different way: 

mv XXX/* /s/other/XXX/

It is not feasible to give you much more detailed info. Is there anything in particular you need to know?

**Comment by trapexit** [comment]
It's best if you can recreate the situation in the minimal way and provide me with that info. The situation is too complicated for me to analyse without personal reproduction.

**Comment by trapexit** [comment]
I'm closing this for now. If you can provide me with a simple reproduction I'll look into it again.
