### ISSUE TITLE
[Question] Moving var into pooled drives

### ISSUE THREAD

**Issue by z-vap** [trapexit/mergerfs#310]
I intend on installing a linux server release onto a USB stick. but I would like to move /var off of the stick and onto one of the drives I plan on pooling.      In my /etc/fstab I had the mergerfs  section of three pooled drives (mounted as /storage) then after that I had /storage/var mounted as /var).  Upon reboot the OS became unresponsive, and I had to boot into recovery mode to move /storage/var back to root.  

Is this even possible with Mergerfs, or would it be better to mount the /var to /mnt/disk1/var which would later end up being mounted as  /storage/var.   Reason I am asking is sometimes when there are files on the disks, I  get weird fuse errors about the drive not being empty, when I do mount -a.   

/mnt/disk1 
/mnt/disk2
/mnt/disk3
/mnt/parity

**Comment by trapexit** [comment]
If you're getting those errors it's because /var is not empty. Not familiar enough with what's going on to comment but you can use `-o nonempty` to force it to ignore that it's not empty.

**Comment by z-vap** [comment]
Thanks but I don't really understand why it even cares if its empty.    I mean we're mounting a bunch of disks which invariably will have files in them (videos, documents, songs, etc).  They will never be empty.    So I am not sure why the message...

**Comment by trapexit** [comment]
It doesn't care about the source. It is complaining that the destination is not empty. It's a standard behavior of mount.
