### ISSUE TITLE
Question on moving a dir while maintaining list of files

### ISSUE THREAD

**Issue by M1dKn1ght** [trapexit/mergerfs#311]
firstly, nice work on mergerfs. it working well on my setup, but I have a problem with on operation that im unsure if its possible to do or not?, hoping someone can help

I have set in my fstab using these options
category.create=eplfs,defaults,allow_other,minfreespace=100M

now the senerio is....

I always want to fill the HDD with the lowest space first (which its doing), but I come to this problem.

when I move a directory that contains 50 .rar files, I need to get this directory intact. where at this stage when its moved, its moved to the lowest hdd space, once that's full, the remaining rar files are then moved to the next lowest hdd space, which is not what I want.

so.. is there a way that merge checks the size of the source folder, and on move, will move to the next lowest hdd space that will be enough space for the whole dir?

thankyou

**Comment by trapexit** [comment]
Moving of a directory across drives is not atomic. There isn't a way to know that high level of a behavior is occurring. From mergerfs' perspective it's a bunch of copies of files. Even that is really the opening of a file, copying data, and removing the old file.

**Comment by M1dKn1ght** [comment]
ok thanks for the reply. my next best option as a walk-around, would be say set the freelimit to 5GB, and I notice the first hdd getting close to this limit, then manually hand fill the drive to under the 5gb limit so mergerfs starts with the next hdd

**Comment by trapexit** [comment]
If you don't use path preserving then a move will create the path on the drive it originates on.

**Comment by M1dKn1ght** [comment]
I did try changing eplfs to lfs with the same results.  or should remove "category.create=lfs" altogether?

**Comment by trapexit** [comment]
Did you change the runtime value? Remount?

**Comment by M1dKn1ght** [comment]
I just rebooted...

but creating it on the same drive isn't really what I want anyway. in the way I was hoping it would work, the walk around is as I said, once I see the first lowest drive get close to the freelimit, I can hand move the next so its under the freelimit, then on the next move through mergerfs it will target the next lowest which is what I need
