### ISSUE TITLE
not - ignoring read-only file system

### ISSUE THREAD

**Issue by M1dKn1ght** [trapexit/mergerfs#312]
i have a a few mounts set, one of those are read-only. and going from the mergerfs doc's it should ignore any read-only mounts when making/creating etc... but in my case if I try and make a directory, its trying to make it on the read-only mount. 
any suggestions?

**Comment by trapexit** [comment]
What exactly is the setup? What OS? Without details I can't comment. If the operating system doesn't tell mergerfs it's read only I cant know.

**Comment by M1dKn1ght** [comment]
its running under Ubuntu. theres a total of 10 or so mounts points. 2 of which are set to read-only

One read-only is on a Thecus n7700 NAS, the other read-only is on 1 drive that's on a windows 2012 server

all shares are NFS

fuse.mergerfs category.create=eplfs,defaults,allow_other,direct_io,moveonenospc=true,minfreespace=5G

**Comment by M1dKn1ght** [comment]
sorted... sorry, didn't realize I actually need to set the ro in the mount line itself..

**Comment by trapexit** [comment]
Was the remote read only?

I currently use `statvfs` to tell me if something is read only. If the remote is read only and the local isn't explicitly then it isn't transmitted. 

I could try to do a more empirical check. Try to create a file and check for a `read only` error. However, I'd prefer not to do that kind of thing (impact the underlying system).
