### ISSUE TITLE
using SYS_setgroups16 rather than SYS_setgroups32 on older ARM kernels

### ISSUE THREAD

**Issue by Feirlane** [trapexit/mergerfs#319]
I've recently created a mergefs drive pool with a new drive I've got. 

The thing is, most directories and files are created by applications running as their own users and I have ACLs and sticky bits set so everything belongs to the group 'mediamanager' with rw permissions.

Now, when I as a regular user, member of the mediamanager group, try to create a file inside a mediamanager group owned directory I'm getting a permission denied error.

I tried creating the same directory structure in both disks and creating files in both of them around mergerfs and it works, but not though mergerfs.

I'm mounting the pool as root through fstab with the following options:
_defaults,gid=1011,moveonenospc=true,category.action=all,category.create=mfs,category.search=newest,allow_other_

I also tried with and without the gid=1011, which is the gid of the mediamanager group.

Is there any know issues with group permissions? I tried googling but nothing relevant came up.

Thanks in advance!

**Comment by trapexit** [comment]
There should be no problems with entitlements. There are some limits as described in the readme[0] but I doubt you're experiencing it.

Can you provide me *exactly* the layout and acls? The users attempting to access?

[0] https://github.com/trapexit/mergerfs#supplemental-user-groups

**Comment by Feirlane** [comment]
I tried removing all the acl's as I only used them to force write group permissions on the files created inside the folder, but no luck. My setup is as follows:

```
drwxr-xr-x  4 root root         4096  Sep 16 19:42 /disks/
drwxr-xr-x  9 root root         4096  Dec 12  2015 /disks/storage01
drwxr-xr-x  7 root root         4096  Sep 19 08:56 /disks/storage02
drwxrwsr-x 30 root mediamanager 20480 Sep 18 16:09 /disks/storage01/downloads/
drwxrwsr-x  2 root mediamanager 4096  Sep 19 09:00 /disks/storage02/downloads/

drwxr-xr-x 7 root mediamanager 4096 Sep 19 08:56 /mnt/
drwxrwsr-x 2 root mediamanager 4096 Sep 19 09:00 /mnt/downloads/
```

_/mnt_ is the mergerfs mount with the following options:
`/disks/storage* /mnt    fuse.mergerfs   defaults,gid=1011,moveonenospc=true,category.action=all,category.create=mfs,category.search=newest,allow_other          0       0`

When I try to create a file or a directory inside downloads I get the following error:
`
feirlane@host / $ touch /mnt/downloads/test
touch: cannot touch '/mnt/downloads/test': Permission denied
`

Meanwhile, creating files in the individual drives works ok:
```
feirlane@host / $ touch /disks/storage01/downloads/test01
feirlane@host / $ touch /disks/storage02/downloads/test02
```

And I can see both new files through the mergerfs:
```
feirlane@host / $ ls -l /mnt/downloads/test*
-rw-r--r-- 1 feirlane mediamanager 0 Sep 19 09:00 /mnt/downloads/test01
-rw-r--r-- 1 feirlane mediamanager 0 Sep 19 09:00 /mnt/downloads/test02
```

I tried both mounting the mergerfs with and without gid.

As storage02 was a new empty disk, I tried mounting the disk empty and relying on mergerfs to create the directory structure when needed but, as I was getting the above error, I replicated the folder hierarchy up to _downloads_ with the same permissions as storage02 to no avail.

My user is a member of the mediamanager group, as I can create files inside the individual download folders in each disk.

If I, as root, create  folder in the merger mount, and then assing feirlane as owner, I then can create files inside that folder as a regular user, that's why I believe it has something to do with group permissions.

Thanks a lot for your help, cheers.

**Comment by trapexit** [comment]
Shouldn't be using `gid` option. It works just fine for me. Did you just add the user to the group and not open a new shell?

```
mergerfs -odefaults,moveonenospc=true,category.action=all,category.create=mfs,category.search=newest,allow_other /tmp/a:/tmp/b /tmp/c
```

```
$ pwd
/tmp/c
$ xattr -p user.mergerfs.allpaths . | tr '\0' '\n' | xargs -n1 ls -ld
drwxrwsr-x 2 root vboxusers 4096 Sep 19 09:22 /tmp/a/downloads
drwxrwsr-x 2 root vboxusers 4096 Sep 19 09:42 /tmp/b/downloads
$ id
uid=1000(bile) gid=1000(bile) groups=1000(bile),128(vboxusers)
$ touch foo
$ ls -lh
total 0
-rw-rw-r-- 1 bile vboxusers 0 Sep 19 09:45 foo
```

**Comment by Feirlane** [comment]
If I run the same mergerfs command as you with my own paths as my regular user, then I'm able to create files in the downloads folder:

```
feirlane@host / $ mergerfs -odefaults,moveonenospc=true,category.action=all,category.create=mfs,category.search=newest,allow_other /disks/storage01/:/disks/storage02/ /mnt/
feirlane@host / $ cd /mnt/downloads/
feirlane@host downloads $ xattr2 -p user.mergerfs.allpaths . | tr '\0' '\n' | xargs -n1 ls -ld
drwxrwsr-x 30 root mediamanager 20480 Sep 19 09:00 /disks/storage01/downloads
drwxrwsr-x 2 root mediamanager 4096 Sep 19 16:52 /disks/storage02/downloads
feirlane@host downloads $ touch test
feirlane@host downloads $ ls -lh test
-rw-r--r-- 1 feirlane mediamanager 0 Sep 19 17:02 test
```

However, if I run the command with sudo, which I guess is the same as mounting the merger through fstab, then the regular user is unable to create files:
```
feirlane@host / $ sudo mergerfs -odefaults,moveonenospc=true,category.action=all,category.create=mfs,category.search=newest,allow_other /disks/storage01/:/disks/storage02/ mnt/
feirlane@host / $ cd /mnt/downloads/
feirlane@host downloads $ touch c
touch: cannot touch 'c': Permission denied
feirlane@host downloads $ xattr2 -p user.mergerfs.allpaths . | tr '\0' '\n' | xargs -n1 ls -ld
drwxrwsr-x 30 root mediamanager 20480 Sep 19 09:00 /disks/storage01/downloads
drwxrwsr-x 2 root mediamanager 4096 Sep 19 16:55 /disks/storage02/downloads
```

My user is and has been a member of the mediamanager group for a very long time, and I've rebooted the machine countless times before:
```
feirlane@nekodroid downloads $ id
uid=1000(feirlane) gid=1000(feirlane) groups=1000(feirlane),...,1011(mediamanager)
```

**Comment by trapexit** [comment]
I still can't replicate the issue. I ran mergerfs as root prior. Tried using sudo just in case. Still works.

What OS is this? Is mergerfs being run with decreased capabilities or some other security features turned on?

The only thing left to do is to run `strace -f -p <mergerfs_pid>` and try to touch the file. Then I can see what's going on under the hood.

**Comment by Feirlane** [comment]
This is running under ArchLinux ARM on an Odroid U3 with kernel 3.8.13.30, no selinux, grsec, etc.

This is the output of `strace -f -p mergerfs_pid`:

```
<unfinished ...>
[pid   429] <... read resumed> "2\0\0\0\1\0\0\0BA\1\0\0\0\0\0\1\0\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 50
[pid   429] lstat64("/disks/storage01/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=20480, ...}) = 0
[pid   429] lstat64("/disks/storage02/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
[pid   429] lstat64("/disks/storage02/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
[pid   429] writev(3, [{iov_base="\220\0\0\0\0\0\0\0BA\1\0\0\0\0\0", iov_len=16}, {iov_base="\34\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0"..., iov_len=128}], 2) = 144
[pid   139] <... read resumed> "*\0\0\0\1\0\0\0CA\1\0\0\0\0\0\34\0\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 42
[pid   429] read(3,  <unfinished ...>
[pid   139] lstat64("/disks/storage01/downloads/g", 0xb6b962d8) = -1 ENOENT (No such file or directory)
[pid   139] lstat64("/disks/storage02/downloads/g", 0xb6b962d8) = -1 ENOENT (No such file or directory)
[pid   139] writev(3, [{iov_base="\20\0\0\0\376\377\377\377CA\1\0\0\0\0\0", iov_len=16}], 1) = 16
[pid   579] <... read resumed> ":\0\0\0#\0\0\0DA\1\0\0\0\0\0\34\0\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 58
[pid   139] read(3,  <unfinished ...>
[pid   579] lstat64("/disks/storage01/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=20480, ...}) = 0
[pid   579] lstat64("/disks/storage02/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
[pid   579] statfs64("/disks/storage01", 88, 0xb11f6168) = 0
[pid   579] statfs64("/disks/storage02", 88, 0xb11f6168) = 0
[pid   579] open("/disks/storage02/downloads/g", O_WRONLY|O_CREAT|O_NONBLOCK|O_LARGEFILE, 0100644) = -1 EACCES (Permission denied)
[pid   579] writev(3, [{iov_base="\20\0\0\0\363\377\377\377DA\1\0\0\0\0\0", iov_len=16}], 1) = 16
[pid   579] read(3,  <unfinished ...>
[pid   578] <... read resumed> "*\0\0\0\1\0\0\0EA\1\0\0\0\0\0\34\0\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 42
[pid   578] lstat64("/disks/storage01/downloads/g", 0xb19f62d8) = -1 ENOENT (No such file or directory)
[pid   578] lstat64("/disks/storage02/downloads/g", 0xb19f62d8) = -1 ENOENT (No such file or directory)
[pid   578] writev(3, [{iov_base="\20\0\0\0\376\377\377\377EA\1\0\0\0\0\0", iov_len=16}], 1) = 16
[pid   578] read(3,
```
That output looks inclomete to me, but it just sits there after the command and I'm not familiar enough with strace to know if this is not normal?

Cheers.

**Comment by Feirlane** [comment]
And this is strace's output when running the same touch command as sudo:
```
<unfinished ...>
[pid   572] <... read resumed> "2\0\0\0\1\0\0\0FA\1\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 50
[pid   572] setreuid(-1, 0)             = 0
[pid   572] setregid(-1, 0)             = 0
[pid   572] lstat64("/disks/storage01/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=20480, ...}) = 0
[pid   572] lstat64("/disks/storage02/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
[pid   572] lstat64("/disks/storage02/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
[pid   572] writev(3, [{iov_base="\220\0\0\0\0\0\0\0FA\1\0\0\0\0\0", iov_len=16}, {iov_base="\34\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0"..., iov_len=128}], 2) = 144
[pid   443] <... read resumed> "*\0\0\0\1\0\0\0GA\1\0\0\0\0\0\34\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 42
[pid   572] read(3,  <unfinished ...>
[pid   443] setreuid(-1, 0)             = 0
[pid   443] setregid(-1, 0)             = 0
[pid   443] lstat64("/disks/storage01/downloads/g", 0xb29f62d8) = -1 ENOENT (No such file or directory)
[pid   443] lstat64("/disks/storage02/downloads/g", 0xb29f62d8) = -1 ENOENT (No such file or directory)
[pid   443] writev(3, [{iov_base="\20\0\0\0\376\377\377\377GA\1\0\0\0\0\0", iov_len=16}], 1) = 16
[pid   443] read(3,  <unfinished ...>
[pid   442] <... read resumed> ":\0\0\0#\0\0\0HA\1\0\0\0\0\0\34\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 58
[pid   442] setreuid(-1, 0)             = 0
[pid   442] setregid(-1, 0)             = 0
[pid   442] lstat64("/disks/storage01/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=20480, ...}) = 0
[pid   442] lstat64("/disks/storage02/downloads", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
[pid   442] statfs64("/disks/storage01", 88, 0xb33f6168) = 0
[pid   442] statfs64("/disks/storage02", 88, 0xb33f6168) = 0
[pid   442] open("/disks/storage02/downloads/g", O_WRONLY|O_CREAT|O_NONBLOCK|O_LARGEFILE, 0100644) = 4
[pid   442] fstat64(4, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid   442] writev(3, [{iov_base="\240\0\0\0\0\0\0\0HA\1\0\0\0\0\0", iov_len=16}, {iov_base="\224\t\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0"..., iov_len=144}], 2) = 160
[pid   442] read(3,  <unfinished ...>
[pid   430] <... read resumed> "@\0\0\0\31\0\0\0IA\1\0\0\0\0\0\224\t\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 64
[pid   430] dup(4)                      = 5
[pid   430] close(5)                    = 0
[pid   430] writev(3, [{iov_base="\20\0\0\0\0\0\0\0IA\1\0\0\0\0\0", iov_len=16}], 1) = 16
[pid   427] <... read resumed> "\200\0\0\0\4\0\0\0JA\1\0\0\0\0\0\224\t\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 128
[pid   430] read(3,  <unfinished ...>
[pid   427] setreuid(-1, 0)             = 0
[pid   427] setregid(-1, 0)             = 0
[pid   427] lstat64("/disks/storage01/downloads/g", 0xb4fd4218) = -1 ENOENT (No such file or directory)
[pid   427] lstat64("/disks/storage02/downloads/g", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid   427] utimensat(0, "/disks/storage02/downloads/g", [{1474301631, 757153456}, {1474301631, 757153456}], AT_SYMLINK_NOFOLLOW) = 0
[pid   427] lstat64("/disks/storage01/downloads/g", 0xb4fd4278) = -1 ENOENT (No such file or directory)
[pid   427] lstat64("/disks/storage02/downloads/g", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid   427] lstat64("/disks/storage02/downloads/g", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid   427] writev(3, [{iov_base="x\0\0\0\0\0\0\0JA\1\0\0\0\0\0", iov_len=16}, {iov_base="\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\224\t\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
[pid   427] read(3,  <unfinished ...>
[pid   140] <... read resumed> "@\0\0\0\31\0\0\0KA\1\0\0\0\0\0\224\t\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 64
[pid   140] dup(4)                      = 5
[pid   140] close(5)                    = 0
[pid   140] writev(3, [{iov_base="\20\0\0\0\0\0\0\0KA\1\0\0\0\0\0", iov_len=16}], 1) = 16
[pid   429] <... read resumed> "@\0\0\0\22\0\0\0LA\1\0\0\0\0\0\224\t\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 64
[pid   140] read(3,  <unfinished ...>
[pid   429] close(4)                    = 0
[pid   429] writev(3, [{iov_base="\20\0\0\0\0\0\0\0LA\1\0\0\0\0\0", iov_len=16}], 1) = 16
[pid   429] read(3,
```

**Comment by trapexit** [comment]
Given mergerfs keeps threads' identity for efficiency it looks like other commands may have been run  which set the uid and gids.

Try `strace -f -o /tmp/mergerfs.trace mergerfs -f -o....` in one terminal (as root) and then as the user attempt the touch but without cd'ing and anything else in that directory. It will keep the trace as simple as possible.

Should be able to attach the file to the comment.

**Comment by Feirlane** [comment]
[mergerfs.trace.txt](https://github.com/trapexit/mergerfs/files/480670/mergerfs.trace.txt)

I ran the strace command and then did `touch /mnt/downloads/testfile` followed by terminating the mergerfs process with ^C

I noticed this call to setgroups:
`setgroups(6, [1000, 0, 10, 0, 50, 0]) = 0`

The group list is of equal length to the number of gorups my user belongs to, but some groups are replace with 0, like group 190(systemd-journal) or group 1011(mediamanager)

**Comment by trapexit** [comment]
Strange. 10 and 50 are legit? What's the full list?

**Comment by Feirlane** [comment]
These are my groups:

`uid=1000(feirlane) gid=1000(feirlane) groups=1000(feirlane),10(wheel),50(games),190(systemd-journal),994(craftbukkit),1011(mediamanager)`

Adding some output to _gidcache.cpp_ and rebuilding mergerfs shows the correct groups are being used in each function:
```
gidcache::initgroups:
gidcache::cache: 1000,10,50,190,1011,994,
1000,10,50,190,1011,994,

gidcache::setgroups: 1000,10,50,190,1011,994,

gidcache::initgroups:
gidcache::cache: 1000,10,50,190,1011,994,
1000,10,50,190,1011,994,

gidcache::setgroups: 1000,10,50,190,1011,994,
```
while strace still shows the 0's being used for the syscall

**Comment by Feirlane** [comment]
Hardcoding 1011 in all positions in the groups array inside gidcache.cpp works, and allows me to write the file. However, strace stills shows 0's in the even positions in the setgroups array:
```
12555 setgroups(6, [1011, 0, 1011, 0, 1011, 0]) = 0
```

**Comment by Feirlane** [comment]
Seems like the setgroups that appears in strace is putting a 0 between each group, thus when you try to set 6 groups you're only really setting 3 (1000, 10 and 50).

If I pass rec->size*2 to the syscall, the groups get set correctly. I'm trying to find why this happens, but so far no luck.

**Comment by trapexit** [comment]
Good catch. Perhaps it's a 32bit vs 64bit issue.

**Comment by Feirlane** [comment]
Apparently, at least in my arm system, the ```SYS_setgroups``` syscall refers to the 16bit version. Changing the syscall to ```SYS_setgroups32``` seems to solve the problem, but I doubt this whill fly for all other supported architectures... I'll keep looking into this and try to find a way to tell the correct syscall at compile time

**Comment by trapexit** [comment]
https://github.com/golang/go/issues/17092

**Comment by Feirlane** [comment]
By the looks of that, are they using SYS_SETGROUPS32 for all 32 bit arms, and SYS_SETGROUPS for the 64bit arms whithout any further checks?

**Comment by trapexit** [comment]
Yeah. At least on older kernels. 

I have an ODroid C1 but not setup at the moment. Can you try changing setgroups to....

```
static
inline
int
setgroups(const gid_t_rec *rec)
{
#if defined __linux__ and UGID_USE_RWLOCK == 0
# if defined SYS_setgroups32 and defined __arm__
  return ::syscall(SYS_setgroups32,rec->size,rec->gids);
# else
  return ::syscall(SYS_setgroups,rec->size,rec->gids);
# endif
#else
  return ::setgroups(rec->size,rec->gids);
#endif
}
```

You can just run `cpp gidcache.cpp` and look for `::syscall`. If you see a number rather than SYS_setgroups then we're set.

**Comment by Feirlane** [comment]
That did the trick.

I don't have a 64bit arm available but, can we be sure SYS_setgroups32 will not be available there? My first approach was looking for ```__arm__``` to be defined and ```__aarch64__``` to be undefined:
```
#if defined __arm__ and !defined __aarch64__
```

**Comment by trapexit** [comment]
Yeah. It looks like on 64bit platforms they have SYS_setgroups and the old version is redefined to SYS_setgroups16. On 32bit platforms... at  least arm and i386 it's SYS_setgroups and SYS_setgroups32. So in fact I should just check for SYS_setgroups32 and it should cover any 32bit platform.

**Comment by Feirlane** [comment]
Indeed I just had a look into the /usr/include/bits/syscall.h from the arm64 package for archlinuxarm and SYS_setgroups32 seems to not be in there. It looks like this mistery is solved then. Thank you very much for your help in all this!

**Comment by trapexit** [comment]
Thank you. I'll have a 2.16.1 out tonight probably with this change.
