### ISSUE TITLE
when mergerfs merged with sshfs

### ISSUE THREAD

**Issue by pahome** [trapexit/mergerfs#323]
I mounted like this:
```
1.sshfs user@ip:~/dir ~/sshfs  //success
2.mergerfs -o defaults ~/hdd1:~/sshfs ~/mnt  //success
```
but when I modified the file in ~/sshfs, it shows the file is read-only
If I modified the file in ~/hdd1, it successed.
how to make the file in ~/sshfs writable?
thx

**Comment by trapexit** [comment]
Are you positive the sshfs is writable? Mergerfs isn't doing anything funny and I've tested that setup before without it being a problem.

Make sure the users and permissions are aligned right.

**Comment by pahome** [comment]
thank u , it works when I delete the "default" parameter, it seems can not recognize the user from remote server
