### ISSUE TITLE
Disk I/O speed difference when mount through mergerfs

### ISSUE THREAD

**Issue by pahome** [trapexit/mergerfs#326]
I found something weird when I want to test the IO speed through fuse-based system.
Mine machine is Ubuntu 4.4.0-38 x86_64
fio_version = 2.14

I mount a **raid 0(4 x ssd)** in ~/a, a **sshfs** in ~/b.And I use **mergerfs** to mount them in ~/mnt
The job file is originally belonged to ~/a/jobfile, so I will see it in ~/mnt/jobfile.
And I test the ~/mnt/jobfile by fio config file.

...................................Condition 1......................................
When I command: **mergerfs -o allow_other -o direct_io ~/a:~/b ~/mnt** , and monitor the I/O by `iostat -xd 1`

```
Read:
Device    rkB/s     wkB/s    %util
~/a       1200     0         98.00
Write:
Device    rkB/s     wkB/s    %util
~/a       100       400      98.00
```
....................................Condition 2...........................
When I command: **mergerfs -o allow_other ~/a:~/b ~/mnt** , and monitor the I/O by `iostat -xd 1`

```
Read:
Device    rkB/s     wkB/s    %util
~/a       1200      0        98.00
Write:
Device    rkB/s     wkB/s    %util
~/a       0         1000     98.00   <----- that's my expected result before
```
I thought I can speed up writing by using option `-o direct_io` but not working, and the speed of write decrease!

But I dont found anything about the detail or influence of option `-o direct_io` ?

thx for help :)

**Comment by trapexit** [comment]
There will always be speed differences. There is additional layers of indirection. 

direct_io limits the caching done which should increase write performance but there are many factors. How the app does the writing, etc.

Try using `dd` to do tests rather than artificial benchmarks.

Try using any other FUSE passthrough filesystem. Or mount against tmpfs rather than the raid array. 

Unless you can show this is a problem with mergerfs, which I doubt it is, I'm closing this.

**Comment by trapexit** [comment]
Also you're mounting sshfs in addition to a localdisk. The overhead alone on certain actions will cause it to be slower because of it being a remote filesystem. You should not be testing speeds with it included.

**Comment by pahome** [comment]
I tested without mount sshfs, only the raid0.
So when I test ~/mnt/jobfile ,it also test the ~/a/jobfile.
and the results are the same with original results.
When I add option `-o direct_io`, the speed of seq. writing will slow down pretty much.

I know the option `-o direct_io` belonging to FUSE option when I type `mergerfs --help`
so I have no idea which part is the critical influence to the speed of writing

thx
