### ISSUE TITLE
Read Only Device

### ISSUE THREAD

**Issue by lonix** [trapexit/mergerfs#332]
I Might simply be very stupid here, but i cant see a way to add a read only device to a array, e.g. i have 
/mnt/disk1
/mnt/disk2 <- This i want mounted readonly.

I Could get around that by mounting disk2 as /mnt/disk2ro in read-only and add that i presume. but that does not sound like a good option.

**Comment by trapexit** [comment]
I don't follow. To make a mount read only you mount it as such. Why would it be different for adding it to mergerfs?

What are you trying to do? Exclude a drive from creation decisions? That's not the same as read only.

**Comment by AndCycle** [comment]
I see a possible use case as I am currently trying to fit mergerfs/snapraid/snapper here,

I wanna fill my disk in order with date base project for future long-term archiving,
it's not really working well with any policy as you won't have equal free space left with them,

as snapraid and snapper require RW access to work with,
it require extra work to remount them to work with mergerfs,

here is an example layout as I am currently working with,

```
A disk
/company1           
|                
+-- /20150124-project1        
|   |            
|   +-- datafolder
|   +-- datafolder2
|                
+-- /20150822-project2        
|   |            
|   +-- datafolder
|                
```
```
B disk     
/company1       
|                
+-- /20160322-project3        
|   |            
|   +-- datafolder
|   +-- datafolder2
|   +-- datafolder3
|                
+-- /20160411-projectwhat        
|   |            
|   +-- datafolder
|   +-- datafolder2
|   +-- datafolderNO
        
/company2
|                
+-- /20160211-projectA        
|   |            
|   +-- datafolder
|   +-- datafolder2
|                
+-- /20160811-projectB        
|   |            
|   +-- datafolder
|   +-- datafolder2
|                
```
```
C disk
/company1       
|                
+-- /20171211-projectlol       
|   |            
|   +-- datafolderX
|   +-- datafolderY
|   +-- datafolderZ
|                
+-- /20171222-projectyea        
|   |            
|   +-- datafolderB
|   +-- datafolderC
        
/company5
|                
+-- /20170222-projjjject        
|   |            
|   +-- datafolderS
|   +-- datafolderY
|                
+-- /20170511-PROPRO      
|   |            
|   +-- datafolder1
|   +-- datafolder2
|                

```

**Comment by AndCycle** [comment]
on second thought, I should use `bind` mount for `ro` to fed in `mergerfs` right?
or reverse this to fed `rw` for snapraid/snapper,

just left this usage case here if anyone wanna find a solution.

**Comment by trapexit** [comment]
I don't understand what you're asking or trying to do. If you want things in order based on drive position you should use the `ff` policy. Of course if you've already got data on the drives in those paths it won't fill them in order according to date because mergerfs has no idea what it's writing (nor should it).

Yes, if you want mergerfs to see the drive as readonly and readwrite elsewhere then yes, use bind mounting.

**Comment by AndCycle** [comment]
I think the original post just ask a syntactic sugar so he can ignore the bind mounting to ease this kind of  management,
I end up with similar idea so this post come up on my google result.

thanks for the reply.
