### ISSUE TITLE
Some FUSE filesystems trigger signal SIGFPE (Arithmetic exception)

### ISSUE THREAD

**Issue by aus** [trapexit/mergerfs#335]
I'm trying to use mergerfs with [rclone](https://github.com/ncw/rclone). rclone is another FUSE filesystem that allows mounting Cloud services like Google Drive. When trying to merge a rclone target with another path (backed by physical disks), a signal SIGFPE (Arithmetic exception) is trigger and I get a segfault.  

This seems to occur when there is a `statfs /` on the mergerfs. I believe the error occurs because the struct of the rclone filesystem is all zeros. But I'm not confident that's the issue. 

If that is the issue, could there be some better bullet-proofing for filesystems that do not build out a proper statfs? You might argue that this is an rclone bug, but I'm not experienced with FUSE  and POSIX standards to know where a statfs struct with all zeros actually valid.

_Steps to reproduce_

1. [Configure](http://rclone.org/commands/rclone_config/) rclone remote filesystem
2. Mount a rclone FUSE mount via `rclone mount acd: /mnt/cloud/acd`
3. Mount a mergerfs via:
`mergerfs /mnt/disk/d*:/mnt/cloud/acd /mnt/pool/hybrid_acd -o rw,defaults,allow_other,debug`
4. Trigger a `statfs()` with something like:  `df /mnt/pool/hybrid_acd`

**Error logs**

_df on rclone_
```
# df /mnt/cloud/acd
Filesystem     1K-blocks  Used Available Use% Mounted on
acd:                   0     0         0    - /mnt/cloud/acd
```
_df on mergerfs_
```
# df /mnt/pool/hybrid_acd
df: /mnt/pool/hybrid_acd: Software caused connection abort
```
_syslog_
```
Nov 15 19:47:02 nas kernel: [  555.010279] traps: mergerfs[2531] trap divide error ip:56164a52e9c7 sp:7f6b6cc19070 error:0 in mergerfs[56164a510000+2a000]
```
_debug FUSE_
```
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.25
flags=0x0007fffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000439
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3206
getattr /
   unique: 2, success, outsize: 120
unique: 3, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 3206
opendir flags: 0x8000 /
   opendir[0] flags: 0x8000 /
   unique: 3, success, outsize: 32
unique: 4, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[0] flags: 0x0
   unique: 4, success, outsize: 16
unique: 5, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 3206
statfs /
Floating point exception (core dumped)
```
_statfs() on rclone FUSE /mnt/cloud/acd_
```
/mnt/cloud/acd, mounted on acd::
        f_bsize: 0
        f_frsize: 0
        f_blocks: 0
        f_bfree: 0
        f_bavail: 0
        f_files: 0
        f_ffree: 0
        f_favail: 0
        f_fsid: 0
        f_flag: ST_RDONLY ST_NOSUID
        f_namemax: 0
```
_mergerfs -v_
```
# mergerfs -v
mergerfs version: 2.16.1-20-g12b9fc1
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

If you want the coredump, just let me know.

**Comment by trapexit** [comment]
Thanks. Should be a trivial fix. I'll try to get a fix out in the next day or so.

**Comment by aus** [comment]
That was fast! Thanks, it looks like that gets passed the error.

I'm still having trouble exporting the filesystem over NFS, but I'll have to do more debugging to determine if it is mergerfs related. I'll open a separate issue if I find something. 

Thanks again!

**Comment by trapexit** [comment]
It was a 3 line change :)

The NFS thing is a known issue with FUSE. I should probably document it in the README. You normally need to set the fsid option on NFS. And possibly use 'noforget' but that can be a problem at times.
