### ISSUE TITLE
on EIO, retry read on next srcmount

### ISSUE THREAD

**Issue by aus** [trapexit/mergerfs#338]
I have a use case where one of my srcmounts could be unreliable and potentially throw EIO errors on read. In this case, is it feasible to retry the read on the next srcmount?

The details of my usecase would be to merge a Google Cloud Drive FUSE filesystem and a Amazon Cloud Drive FUSE filesystem via [rclone](https://github.com/ncw). Occasionally, one of the filesystems will throw EIO errors when service rate limits are exceed. In this example, mergerfs will fail the read with EIO when it encounters the EIO on the selected srcmount. However, the file could be successfully read if retried on the next srcmount.

**Comment by trapexit** [comment]
I'm not sure this is practical or even possible. When using newer FUSE features for reading I don't have control over errors AFAICT. Falling back to the older interface I do have control but there isn't a "next srcmount." Reads and writes are performed on a file descriptor. It was already looked up at the time the 'open' or 'creat' was called. I currently don't hold which path the file was opened from as it's not needed otherwise.

Besides... if I'm understanding the situation correctly wouldn't the EIO returned occur on every further file read? Assuming the open policy would pick the same source that EIOed prior.

Sounds to me that rclone should better handle that situation... rate limits are not something POSIX filesystem API understands and returning EIO isn't correct IMO. It should probably wait the appropriate amount of time and retry.

**Comment by aus** [comment]
It sounds like this probably isn't feasible, but let me try to clarify some details. 

Let's say we have two filesystems:

```
/mnt/cloud/google
/mnt/cloud/amazon
```

These filesystems are backed by the rclone FUSE mount, which translates filesystem operations into their respective cloud service HTTP APIs.
 
Under these cloud filesystems are identical file trees. They are merged with something simple like:

`mergerfs -o defaults,allow_other /mnt/cloud/google:/mnt/cloud/amazon /tmp/mnt/`

`fileA` resides as both `/mnt/cloud/google/fileA` and `/mnt/cloud/amazon/fileA`.

In my example, an application would try to access `/tmp/mnt/fileA`. Given the mergerfs options, it would try to read the file from `/mnt/cloud/google`. However, my Google account has been rate limited. rclone would not be able to read the file from Google and the *rclone* read operation would fail with EIO.

If mergerfs had some sort of logic to catch this error and realize the file is also available at `/mnt/cloud/amazon`, maybe it could avoid the read error. If mergerfs can't catch the read error, maybe it could update the file descriptor to point to `/mnt/cloud/amazon/fileA`. If the application retried the read, it would be successful.

rclone is just used as an example, though. The same logic could also apply to two traditional local filesystems, where one source mount has a faulty drive prone to I/O errors. Something like:

`mergerfs -o defaults,allow_other /mnt/bad_drive:/mnt/good_drive /tmp/mnt/`

Regarding having rclone handle the rate-limiting, it does. It has logic to exponentially wait and retry the read operation. However, there are scenarios where the rate-limit may not reset for an extended period of time (ie 24 hours). In this case, rclone gives up and fails the read. Since rclone does not support any sort of merging, the Amazon and Google FUSE mounts are two separate rclone processes unaware of each other. 

Hopefully, that clarifies things.

**Comment by aus** [comment]
Here's a simple setup I was using to replicate the above scenario. I used the example in-memory FUSE filesystem in [fusepy](https://github.com/terencehonles/fusepy) to simulate this. I [patched](https://github.com/aus/fusepy/commit/f6ffe995398cb8885c029db18b03ca4bbe046aec) it so read operations would always raise EIO. You can replicate by...

```
# setup test directories and file
mkdir -p /tmp/mnt/good
mkdir -p /tmp/mnt/bad
mkdir -p /tmp/mnt/merger
date > /tmp/mnt/good/fileA

# setup FUSE in-memory filesystem that always returns EIO on read operations
git clone https://github.com/aus/fusepy.git && cd fusepy
git checkout eio
python examples/memory.py /tmp/mnt/bad

# in new terminal, copy fileA to in-memory FUSE and test for EIO
cp /tmp/mnt/good/fileA /tmp/mnt/bad/fileA
cat /tmp/mnt/bad/fileA # should give Input/Output error

# setup bad mergerfs
mergerfs -o defaults,allow_other /tmp/mnt/bad:/mnt/good /tmp/mnt/merger
cat /tmp/mnt/merger/fileA # should give Input/Output error
fusermount -u /tmp/mnt/merger

# setup good mergerfs
mergerfs -o defaults,allow_other /tmp/mnt/good:/mnt/bad /tmp/mnt/merger
cat /tmp/mnt/merger/fileA # should not give an error
fusermount -u /tmp/mnt/merger
```

In the `bad mergerfs` scenario, perhaps the read could somehow be retried against `/mnt/good/fileA`.

**Comment by trapexit** [comment]
I understood.

As I said I'm not sure FUSE gives me access to the errors when using the high level API and read_buf callback. I need to look into it more. If I can then I could add additional information when opening files to keep which drive it came from and should it fail I could remove it from the list of drives to check and if a new file is found it could continue. I'm not too hot on having to carry around the necessary data for the extreme off chance of such and error but it's really not too big a deal.

My concern regarding continuous errors however still remains. How does rclone handle rate limits for things other than "read"? Future activity on other files would fail on open I'd think. So ... you'd get file A to finish reading... but all future activity would fail. The only way to manage that would be to remove the drive all together from srcmounts and I'm a bit concerned with blacklisting or removing the drive automatically on random read error.

**Comment by trapexit** [comment]
I'd have to harm read performance to manage read errors . FUSE takes the file descriptor I have and manages it itself. I'd need to instead to either disable the read_buf feature or do reads explicitly and lose the buffering it does. I'd need to perform some benchmarks to see what the impact would be. The feature could be optional so its an optional performance hit but the constant source erroring still needs to be managed and making every single function handle that kind of error situation is messy. The best behavior would be to allow the read to continue and remove the drive from srcmounts. But that's not what you want. You want the drive to be used at some later point. I don't see a good way to manage this automatically. You need some sort of source mount watchdog. Building such a thing into each and every FS call isn't reasonable and doing it externally would introduce race conditions and rclone probably has no way of externally indicating there's a problem.

**Comment by aus** [comment]
Fair enough. Since there's no clean way to handle this, I'm fine with closing the issue. Thanks for your input and letting me bounce the idea off you.

Maybe this problem is better solved in rclone. If it had logic to retry a failed read against another cloud provider, we could avoid complications in the FUSE layer entirely.

**Comment by trapexit** [comment]
I'm not opposed to having some "on read error remove srcmount" or "on read error look for other file" but it needs to be done generically and without much or any compromise. But the aspects that are more specific to your usecase (the need to deal with the temporary nature of the failure condition) probably can't be done without a major change but possibly could be done out of band. A simple watcher which could reconfigure the srcmounts on the fly. But that would require some way to easily know there is an issue with the underlying device. The problem with comparing this to a normal drive error is that in my experience when a device dies it's dead for good (or till reboot).

Something that might work reasonably well could be just the "on read error remove srcmount" feature (this depends on how rclone behaves in this errored state) and an external monitor could modify srcmounts to add it back when it's ready again.

Is the main concern managing the read error or the underlying filesystem errored state?

**Comment by calisro** [comment]
Personally, removing the drive on errors would be great but it would be good to also retry it and bring it back online if it comes back.  Temporary blacklisting based on some interval.

**Comment by trapexit** [comment]
How would you know when to retry it? A timer only makes sense for this rclone situation. Much of the time in my experience when you get a real error with a harddrive... the device is down till there's manual intervention. Often rebooting of the machine. Since the OS will remove the drive on sufficient erroring there isn't much need for mergerfs to do so. I've had it happy many times and mergerfs just hums along.

For the rclone use case it'd be easier to simply build an external watcher. mergerfs is almost fully runtime configurable. The problem is having rclone mounts provide feedback to the watcher so it can properly manipulate the srcmounts. The thing that doesn't deal with is attempting to read from another drive if one fails. While it can be done there is a performance penalty (likely) due to needing to perform the read manually rather than leaving it to FUSE. I'll need to benchmark it though.

**Comment by calisro** [comment]
ah yes. I was thinking through this only from an rclone perspective.  An external watcher would be the right approach.

**Comment by trapexit** [comment]
I'll try to do some benchmarks and see if the failover of a read call can be done without general impact.

If rclone can provide a way to know the general status of the mount (pseudo file which returns the general health?) then I could throw an external controller together no problem.

**Comment by brimur** [comment]
Sorry to dig up an old thread but I was curious if anyone found a solution to this? I have a use case where I have a NAS with a folder I mount in Ubuntu and a copy of the data on a cloud service. I was hoping to use mergerfs to create a mount combining both the NAS, mounted using NFS and the cloud data, mounted using rclone. The idea was that my applications would not be interrupted if I shutdown the NAS to conserver energy.

The problem I am having is that once the NAS is offline anything that accesses the mergerfs folder hangs. Even doing an LS just hangs and never recovers.

**Comment by trapexit** [comment]
That's not something mergerfs can manage practically. The hanging isn't mergerfs. It is the kernel. If you tried to do the same thing in the NFS mount the same thing should happen. If there was an error mergerfs would return it. It's not. It blocks. As a userland process mergerfs can't do anything that any other app can do.
