### ISSUE TITLE
Lack of subdirs

### ISSUE THREAD

**Issue by CCoupel** [trapexit/mergerfs#339]
Hi Traxit, great job with your mergerfs. I was looking a way to merge several branch with R/W abillity but I need to add/remove branch dynamicaly usinf fuse. And MergerFS is the only on doing all this.

What I see is when there is multiple subdir on one br1, I can not write file on br2 ont these subdir. By looking at the documentation, the subdirs might be ceated on the go:

BR1(RO): /Dir1/Dir1.2/Dir1.3
BR2(RW): /

touch /Merge/Dir1/toto
BR1(RO): /Dir1/Dir1.2/Dir1.3
BR2(RW): /Dir1/toto => subdir Dir1 is created on BR2

touch /Merge/Dir1/Dir1.2/toto 
touch: cannot touch 'toto': No such file or directory => subdir Dir1/Dir1.2 is not created on BR2

**Comment by trapexit** [comment]
What are you trying to do? What version? What settings?

I just created the setup you list above and it works fine.

**Comment by CCoupel** [comment]
Hi Trapexit,
thanks for your feedback.
Here is my use case:
I merge 2 FS; One is full (Multimedia-3To), the other is empty (Multimedia-3To-2)

$sudo mkdir mergeFS
$/usr/bin/sudo /usr/local/bin/mergerfs -o defaults,allow_other /media/Multimedia-3To mergeFS
$/usr/bin/sudo /usr/bin/xattr -w user.mergerfs.srcmounts "+/media/Multimedia-3To-2" $/mnt/mergeFS/.mergerfs
$/usr/bin/sudo /usr/bin/xattr -w user.mergerfs.category.create "eplfs" /mnt/mergeFS/.mergerfs
$/usr.bin/sudo /usr/bin/xattr -w user.mergerfs.moveonenospc true /mnt/mergeFS/.mergerfs

$xattr -l /mnt/mergeFS/.mergerfs                                                                                                                                              
user.mergerfs.srcmounts: /media/Multimedia-3To:/media/Multimedia-3To-2                                                                                                                        
user.mergerfs.minfreespace: 4294967295                                                                                                                                                        
user.mergerfs.moveonenospc: false                                                                                                                                                             
user.mergerfs.policies: all,epall,epff,eplfs,eplus,epmfs,eprand,erofs,ff,lfs,lus,mfs,newest,rand                                                                                              
No such xattr: user.mergerfs.version                                                                                                                                                          
user.mergerfs.pid: 2352                                                                                                                                                                       
user.mergerfs.category.action: all                                                                                                                                                            
user.mergerfs.category.create: epmfs                                                                                                                                                          
user.mergerfs.category.search: ff                                                                                                                                                             
user.mergerfs.func.access: ff                                                                                                                                                                 
user.mergerfs.func.chmod: all                                                                                                                                                                 
user.mergerfs.func.chown: all                                                                                                                                                                 
user.mergerfs.func.create: epmfs                                                                                                                                                              
user.mergerfs.func.getattr: ff                                                                                                                                                                
user.mergerfs.func.getxattr: ff                                                                                                                                                               
user.mergerfs.func.link: all                                                                                                                                                                  
user.mergerfs.func.listxattr: ff                                                                                                                                                              
user.mergerfs.func.mkdir: epmfs                                                                                                                                                               
user.mergerfs.func.mknod: epmfs                                                                                                                                                               
user.mergerfs.func.open: ff                                                                                                                                                                   
user.mergerfs.func.readlink: ff                                                                                                                                                               
user.mergerfs.func.removexattr: all                                                                                                                                                           
user.mergerfs.func.rename: all                                                                                                                                                                
user.mergerfs.func.rmdir: all                                                                                                                                                                 
user.mergerfs.func.setxattr: all                                                                                                                                                              
user.mergerfs.func.symlink: epmfs                                                                                                                                                             
user.mergerfs.func.truncate: all                                                                                                                                                              
user.mergerfs.func.unlink: all                                                                                                                                                                
user.mergerfs.func.utimens: all 


$mkdir -p /media/Multimedia-3To/dir1.1/dir1.2/dir1.3
$du /media/Multimedia-3To                                                                                                                                            
0       /media/Multimedia-3To/dir1.1/dir1.2/dir1.3                                                                                                                                            
0       /media/Multimedia-3To/dir1.1/dir1.2                                                                                                                                                   
0       /media/Multimedia-3To/dir1.1 

$touch /mnt/mergeFS/toto                                                                                                                                                      
$ ls /media/Multimedia-3To-2/                                                                                                                                                  
lost+found  toto

touch /mnt/mergeFS/dir1.1/toto2                                                                                                                                              
$ ls /media/Multimedia-3To-2/                                                                                                                                                  
dir1.1  lost+found  toto 
$ ls /media/Multimedia-3To-2/dir1.1/                                                                                                                                           
 toto2


$ touch /mnt/mergeFS/dir1.1/dir1.2/dir1.3/toto3                                                                                                                                
touch: impossible de faire un touch « /mnt/mergeFS/dir1.1/dir1.2/dir1.3/toto3 »: Aucun fichier ou dossier de ce type                                                                          
cyril@osmc:/mnt$ touch /mnt/mergeFS/dir1.1/dir1.2/toto3                                                                                                                                       
touch: impossible de faire un touch « /mnt/mergeFS/dir1.1/dir1.2/toto3 »: Aucun fichier ou dossier de ce type

**Comment by trapexit** [comment]
You clearly compiled it yourself and something is wrong. What platform are you on? Clearly the xattr commands you ran aren't working.

As I pointed out prior it should work fine. Please use a proper release if you can.

**Comment by CCoupel** [comment]
I compiled from the latest sources.
I am on raspi 2 with osmc.

I will try to recompile.

**Comment by trapexit** [comment]
It's Debian. Can't you use one of the precompiled debs?

**Comment by CCoupel** [comment]
Hi,
My debian seems to be too old; Imade some tests on unbutu xenial and it seems to work fine now with the deb pkg.
thanks for your help.
