### ISSUE TITLE
use_ino option doesn't work

### ISSUE THREAD

**Issue by Hunter16g** [trapexit/mergerfs#353]
The command `mergerfs -o defaults,allow_other,category.create=mfs,use_ino /mnt/Manager/:/mnt/Films/:/mnt/Musique/ /mnt/Storage` doesn't seem to do anything, the mount point is empty. Is there any way to get a more verbose output/log ? The same command without use_ino works fine, is it not compatible with another option I used ?
Thanks in advance for the help.

**Comment by trapexit** [comment]
What version of mergerfs? `use_ino` only works with the latest release. v2.18.0+

**Comment by Hunter16g** [comment]
That's it, thanks. So invalid options just fail silently ?

**Comment by trapexit** [comment]
No. Not specifically. It's a low level FUSE option and wasn't explicitly blacklisted. There are dozens of FUSE options which can be passed in and if they aren't referred to in mergerfs docs it's not tested.
