### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by tolotos-rgu** [trapexit/mergerfs#354]
I created a mergerfs using a drive with a existing directory structure and a empty drive. 
How will mergerfs create the needed directory structure on the second drive if the first one is filled up and put the files there? 

I tried this using two loop devices 
`dd if=dev/zero bs=1024k count=512 of=data0`
`dd if=dev/zero bs=1024k count=512 of=data1`

`losetup  /dev/loop0 data0`
`losetup  /dev/loop1 data1`

`mkfs.ext4 /dev/loop0`
`mkfs.ext4 /dev/loop1`

`mkdir drive0`
`mkdir drive1`
`mkdir driveAll`

`mount /dev/loop0 drive0`
`mount /dev/loop1 drive1`

`mergerfs drive0:drive1 driveAll`

`cd driveAll`

`mkdir folder`
`cd folder`

`dd if=/dev/zero bs=1024k count=400 of=dummy0  ==> OK`
`dd if=/dev/zero bs=1024k count=400 of=dummy1  ==> dd: error writing 'dummy1': No space left on device`

**Comment by tolotos-rgu** [comment]
I retried with moveonenospc=true and now the above test worked. 
I'll remount the working drives with this additional option now.

**Comment by trapexit** [comment]
If you don't care what drive the files end up on don't use a path preserving policy. Just use 'mfs' or similar rather than 'epmfs'.
