### ISSUE TITLE
Is copy-on-write supported?

### ISSUE THREAD

**Issue by ErAzOr2k** [trapexit/mergerfs#355]
Hi,

Is copy-on-write supported like unionfs does?
This would be usefull for read only mounts.

**Comment by trapexit** [comment]
It's not supported. COW behavior as seen in unionfs or overlayfs conflicts with the way policies are used. At least it would without breaking some assumptions currently made by the policies. It's an interesting space but I don't see what mergerfs can offer that overlayfs and such don't already.

**Comment by ErAzOr2k** [comment]
Thanks for your Feedback.
So, how can I handle the following situation?

My Cloud Drive (which is mounted as read only) and local storage are mounted together by mergefs.
Now I'd like to edit e.g. textiles, which are only available on the cloud.
Situation now is, that I get the Message: cannot save file because target is read only

**Comment by trapexit** [comment]
Use overlayfs?

Why is it read-only if you want to edit it? What's the workflow you want?

**Comment by RaymondSchnyder** [comment]
> Use overlayfs?
> 
> Why is it read-only if you want to edit it? What's the workflow you want?

I can only assume, but i think his workflow is to edit a file only available in the cloud (download it, edit it and upload it again) with the local read write disk.

**Comment by trapexit** [comment]
mergerfs doesn't and won't provide overlayfs behavior. overlayfs does that already. It seems like a bad policy given it will lead to files being out of sync. Seems better to just have the files on your local disk and then rclone sync the files to cloud drive or whatnot. If you want CoW then just mount overlayfs over the readonly cloud drive and then put that path into mergerfs.
