### ISSUE TITLE
Severe system performance decrease over time with mmap usage

### ISSUE THREAD

**Issue by VanBreuk** [trapexit/mergerfs#356]
I'm running mergerfs to bundle two SSD drives, in order to handle a large database that was surpassing the single drive capacity. This database is run by a process that uses extensively memory mapped files, on a high RAM (64 GB) Ubuntu server.

After reading about the FUSE performance issues with older kernels, I upgraded to 4.5.4. The process starts fine and runs fine from the mergerfs mount point, with very reasonable resource usage, but after a few hours mergerfs is staying over ~100% CPU usage, and the whole system lags heavily.

Mergerfs is bundling / and /mnt/ssd2 as /mnt/vssd. Processes are run as root.

Is this asking to use direct_io? If so, should I try development branch?

Thank you for your feedback.

**Comment by trapexit** [comment]
mmap won't work with direct_io. FUSE limitation. 

This sounds like a fuse / kernel issue. Perhaps a caching thing. We should bring this to the fuse development mailinglist.

Off topic: wouldn't RAID or LVM be a better fit here?

**Comment by VanBreuk** [comment]
I had not considered RAID because the server cannot afford redundancy, and between RAID 0, LVM or trying Mergerfs I went with the latter because it was considerably simpler to run - and I wanted to try it. But if FUSE brings issues in my setup, maybe I will need to give LVM a try...  otherwise the only workaround I've seen would be regular reboots.

**Comment by trapexit** [comment]
For a database something like LVM or raid (at the hardware or volume or filesystem level) would likely be the best. Mergerfs doesn't give you contiguous storage. 

Itd be better if you sent the message to the fuse mailing list but if you prefer I can do so.

**Comment by VanBreuk** [comment]
Thank you for the input, it is much appreciated. I posted a message to fuse-devel.

**Comment by trapexit** [comment]
BTW: What software is this? It uses multiple files to store the data? mergerfs does not provide contiguous data storage so I want to be sure the software doesn't try creating a files that are beyond the size of a single drive.

**Comment by VanBreuk** [comment]
It is a beta-stage gateway between different cryptocurrency blockchains, that creates database distillates from the blockchain data for fast access (and since one of them is Bitcoin, the total data size is pretty big).

And it does use multiple files in a Sophia type of database, so the filesizes should not be an issue compared to the drive size.

**Comment by trapexit** [comment]
Just to make sure I'd be sure to set the minfreespace to something beyond the largest file size and use the `mfs` create policy.
