### ISSUE TITLE
UMASK not ignored when the parent directory has default ACL

### ISSUE THREAD

**Issue by aplatanado** [trapexit/mergerfs#357]
The umask(2) man page says:

> Alternatively, if the parent directory has a default ACL (see acl(5)), the umask is ignored, the default ACL is inherited, the permission bits are set based on the inherited ACL, and permission bits absent in the mode argument are turned off.

That is, if the parent directory has a default ACL, the process umask should have no effect when creating files or directories inside. But mergerfs always apply the process umask. For examples, see [src/mkdir.cpp](../blob/master/src/mkdir.cpp#L132) and [src/create.cpp](../blob/master/src/create.cpp#L122).

**Comment by trapexit** [comment]
POSIX ACLs aren't really supported by FUSE. In the kernel or userspace AFAIK. I would need to manually manage ACLs. If extended attributes are enabled in mergerfs I guess I could try checking parent directories for "system.posix_acl_default" and ignore umask so the kernel can manage the acl correctly but I don't believe that overall the POSIX ACL system will work correctly with FUSE till support is properly added.

**Comment by aplatanado** [comment]
I didn't know that ACLs aren't supported by FUSE. For me, it works.

I'm using ACL in some devices. Through the merged filesystem, I see the ACL, the new files and directories inherit the permissions correctly (except for the umask issue) and I manage ACL using setfacl().

**Comment by trapexit** [comment]
It's probably working with mergerfs because I'm passing through calls but with permissions the kernel actually manages it for you. It doesn't however handle ACLs. I think I can pretty easily fix this issue. I'll try to get something done this week.

**Comment by trapexit** [comment]
Can you try the [posix-acl](https://github.com/trapexit/mergerfs/tree/posix-acl) branch?

**Comment by aplatanado** [comment]
Yes. I tried the branch. It doesn't work and, after some debugging, I think I have found the problem.

I have followed the next steps:

1. I have created a directory inside a mergerfs pool
2. I have set the "other permissions" and "default other permissions" as 7. 
3. I have set session umask as 0007.
4. I have attached to mergerfs process.
5. I have tried to create a new directory using mkdir command. With strace I have checked that mkdir command call mkdir() system call with mode 0777.

But mergerfs::fuse::mkdir is called with mode = 0770. That is, with umask already applied. Obviously, a few functions calls later, mkdir() syscall is invoked using that mode.

Does FUSE apply umask to the mode specified in the system call before call mergerfs? I assumed not, seeing the mergerfs code.

**Comment by trapexit** [comment]
I figured it out. Quirk of feature changes in libfuse a while back. I need to tell the kernel *not* to mask for me. Try the branch now.

Unfortunately since fuse doesn't support posix acl's what I need to do is manually check for default permissions and not use the umask but the overhead should be low.

**Comment by aplatanado** [comment]
Now it works. The default permissions are used to set the permissions of new files and directories, ignoring umask.
