### ISSUE TITLE
Photon OS?

### ISSUE THREAD

**Issue by jimphreak** [trapexit/mergerfs#359]
Have you successfully gotten mergerfs working in PhotonOS?  I believe (though I'm not sure how to confirm) I got it installing using the .rpm file but when adding to /etc/fstab the mounts are working at boot.  Not sure if the install of mergerfs failed or Photon OS is missing mount.fuse.  I can't seem to find any info on how to install it.

**Comment by rubylaser** [comment]
Have you checked to see if mergerfs reports being installed (also check for the version of FUSE installed)?
`mergerfs -V`

If FUSE is working and mergerfs is properly installed, have you tried mounting via the command line without /etc/fstab (for example, say you have two data disks, you would like to mount at /storage)?
`mkdir -p /storage
mergerfs -o defaults,allow_other,moveonenospace=true,minfreespace=10G /mnt/data/disk1:/mnt/data/disk2 /storage`

**Comment by jimphreak** [comment]
Hey rubylaser.  Looks like mergerfs did not successfully install.  Having trouble finding the right command to install in Photon.

**Comment by rubylaser** [comment]
That is the correct way to install, but you will need to meet the dependencies for it to work (in this case rpmlib). I'm not a Redhat/Centos guy, and Photon OS is a cutdown/minimal distro, so it may take some work to get working correctly.   

Honestly, the small benefit of running a cutdown OS probably isn't worth the pain of needing to track down repositories or compile software to meet dependencies.  I'd just run a minimal Debian/Ubuntu Server VM and run Docker/LXC for all my container needs :)

**Comment by trapexit** [comment]
I can look into creating a specific Photon package but I don't have one today. Just for centos and fedora. 

Have you tried building it yourself?

**Comment by jimphreak** [comment]
I think you are right @rubylaser.  It's not worth the effort it appears to be.

**Comment by trapexit** [comment]
I just tried to build on Photon natively but unless I'm blind the package repo doesn't have g++ / clang++.

**Comment by rubylaser** [comment]
So, none of the typical packages show up in the repo?  I haven't tried Photon OS, but I hope it's not _that_ stripped down :)
`yum install gcc gcc-c++ make`

**Comment by trapexit** [comment]
It's a custom PhotonOS set of repos. I take it back... gcc package include g++ but the environment as a whole is really bare bones. Slowly finding appropriate dependencies.

**Comment by jimphreak** [comment]
Did you install the minimal version of the full ISO version?

**Comment by trapexit** [comment]
I'm using the official docker image.

**Comment by jimphreak** [comment]
I'm confused.  PhotonOS is deployed either OVA (minimal) or ISO (full) in VMware.  Which one did you use to get Photon installed?

**Comment by trapexit** [comment]
I'm using https://hub.docker.com/_/photon/

**Comment by jimphreak** [comment]
Oh interesting.  I suspect that is the minimal version which doesn't contain as many built in tools.

**Comment by aus** [comment]
I was able to build with this:

```
# enable devel repo
echo "[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True" > /etc/yum.repos.d/photon-devel.repo

# install build essentials via:
# https://github.com/vmware/photon/wiki/Frequently-Asked-Questions
curl -L https://git.io/v1boE | xargs -I {} tdnf install -y {}

# install other deps
tdnf install -y git fuse-devel attr rpm-build attr-devel

# build
mkdir /src ; cd /src 
git clone https://github.com/trapexit/mergerfs.git ; cd mergerfs
make
```

However, I wasn't able to locate a package for pandoc , which may pose problems when building packages.

**Comment by trapexit** [comment]
pandoc is not necessary for building. The man page is provide in the source as a backup and kept up to date.
