### ISSUE TITLE
Attempting to mount via fstab causes emergency mode

### ISSUE THREAD

**Issue by 19wolf** [trapexit/mergerfs#364]
My fstab:
```
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
#Root
UUID=a7691b4d-b971-4efc-b783-3996d1409cdd /               ext2    noatime,nodiratime,errors=remount-ro 0       1
#Datadrives
UUID=fe857e6e-27ec-45de-a10b-5fb46cf86bbf /mnt/datadrive/1 btrfs   defaults        0       2
UUID=3005b964-62d9-4bd4-947d-01607354c7f8 /mnt/datadrive/2 btrfs   defaults        0       2
#UUID=xxx /mnt/datadrive/3 btrfs defaults 0 2

#MergerFS
/mnt/datadisk/*  /data  fuse.mergerfs  defaults,allow_other,category.create=lus,use_ino,x-systemd.requires=/mnt/datadrive/1,x-systemd.requires=/mnt/datadrive/2 0 0
```
When I comment out the mergerfs line, my computer boots fine, but when I try to set it, I end up in 'emergency mode'. Mounting using the `mergerfs -o defaults,allow_other,category.create=lus,use_ino` etc works fine

**Comment by trapexit** [comment]
Do you have the [fuse package installed and therefore mount.fuse available?](https://github.com/trapexit/mergerfs#srcmounts)

**Comment by 19wolf** [comment]
Right after I submitted this, I double checked that and it was already installed, so yes.

**Comment by trapexit** [comment]
Don't know then. It's not likely to be mergerfs but the setup. Have you tried using mount to simulate it directly?

**Comment by 19wolf** [comment]
```
wolf@NAS:~$ sudo mount -a
fuse: missing mountpoint parameter
wolf@NAS:~$ sudo apt install fuse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fuse is already the newest version (2.9.4-1ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by trapexit** [comment]
"missing mountpoint parameter"

Something about your fstab line is wrong. Nothing stands out but clearly it's malformed. 

Try using `mount`. 

`mount -t fuse.mergerfs ...`

**Comment by 19wolf** [comment]
So I mounted my data drives at /mnt/datadrive/* and was trying to fuse /mnt/datadisk/* which didn't exist. 0.0
