### ISSUE TITLE
Permission issue - Docker

### ISSUE THREAD

**Issue by 2devnull** [trapexit/mergerfs#366]
For some reason, files created by uid 1000 in a Docker container on a mergerfs pool with ownership 1000:1000 creates the files with ownership 1100:1100 (which is the host user uid and gid). 

Doing an ls -l on the pool shows the file correctly at 1000:1000, but doing an ls -l on the folder that the file was actually created shows the ownership as 1100:1100. 

BTW - the ownership of the folder that the file is created in is also 1000:1000. The question is why is the host user uid/gid being used for the newly created files which the container shouldn't even know about that user.

Would appreciate any insight on resolving this.

**Comment by trapexit** [comment]
Can you provide me with an explicit example? I've not experienced that.
