### ISSUE TITLE
Permission denied while writing

### ISSUE THREAD

**Issue by tolotos-rgu** [trapexit/mergerfs#367]
I merged two cifs-mounts together. The are mounted with 

`<share1> <path1> cifs  iocharset=utf8,rw,noacl,credentials=<path_to_credentials_file>,forceuid,forcegid,uid=109,gid=115,file_mode=0666,dir_mode=0777 0       0`
`<share2> <path2> cifs iocharset=utf8,rw,noacl,credentials=<path_to_credentials_file>,forceuid,forcegid,uid=109,gid=115,file_mode=0666,dir_mode=0777 0       0`

In both mounts I can write without troubles.

Mergerfs is configured in fstab like

`<path1>:<path2> <common_path> fuse.mergerfs defaults,allow_other,moveonenospc=true,use_ino,fsname=emby_merge,uid=109,gid=115 0 0`

Now <path1> gets full and subsequent writes creating

`$dd if=/dev/zero of=data bs=1024k count=1`
`dd: failed to open 'data': Permission denied`
`$`

Any ideas whats wrong?

**Comment by trapexit** [comment]
Why are you setting the uid and gid settings for mergerfs?

**Comment by tolotos-rgu** [comment]
To enshure the service using this merge can write. It is running with this uid and gid.

**Comment by trapexit** [comment]
While running as root it handles changing users itself. There should be no need to do that and it's not been tested. I can look into it but I'd prefer the entitlements be managed at cifs and let mergerfs proxy the  user credentials.

**Comment by trapexit** [comment]
Yes... those settings don't do what you think they do. Please remove them and try again.

**Comment by tolotos-rgu** [comment]
I changed  to

`<path1>:<path2> <common_path> fuse.mergerfs defaults,allow_other,moveonenospc=true,use_ino,fsname=emby_merge 0 0`

`$mount`
says
`emby_merge on <common_path> type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,allow_other)`^

But I get the same error.

**Comment by tolotos-rgu** [comment]
`df -h`

gives 

`<share1>  9.8T  9.8T  2.9G 100% <path1>`
`<share2>  2.0T  256K  2.0T   1% <path2>`
`emby_merge                            12T  9.8T  2.0T  84% <common_path>`

There should be 2.9G free on <path1> but mkdir test in <common_path> results in an error too?!
Is there some invisible metadata from mergerfs which can be corrupted by my wrong settings?

**Comment by tolotos-rgu** [comment]
`# xattr -l .mergerfs`
`user.mergerfs.srcmounts: <path1>:<path2>`
`user.mergerfs.minfreespace: 4294967295`
`user.mergerfs.moveonenospc: true`
`user.mergerfs.policies: all,epall,epff,eplfs,eplus,epmfs,eprand,erofs,ff,lfs,lus,mfs,newest,rand`
`user.mergerfs.version: 2.19.0`
`user.mergerfs.pid: 4473`
`user.mergerfs.category.action: all`
`user.mergerfs.category.create: epmfs`
`user.mergerfs.category.search: ff`
`user.mergerfs.func.access: ff`
`user.mergerfs.func.chmod: all`
`user.mergerfs.func.chown: all`
`user.mergerfs.func.create: epmfs`
`user.mergerfs.func.getattr: ff`
`user.mergerfs.func.getxattr: ff`
`user.mergerfs.func.link: all`
`user.mergerfs.func.listxattr: ff`
`user.mergerfs.func.mkdir: epmfs`
`user.mergerfs.func.mknod: epmfs`
`user.mergerfs.func.open: ff`
`user.mergerfs.func.readlink: ff`
`user.mergerfs.func.removexattr: all`
`user.mergerfs.func.rename: all`
`user.mergerfs.func.rmdir: all`
`user.mergerfs.func.setxattr: all`
`user.mergerfs.func.symlink: epmfs`
`user.mergerfs.func.truncate: all`
`user.mergerfs.func.unlink: all`
`user.mergerfs.func.utimens: all`

**Comment by trapexit** [comment]
2.9G is less than the default minfreespace. As such it's skipped in creation calculations as described in the docs. Are you positive that share2's mount is properly permissioned?

**Comment by tolotos-rgu** [comment]
I can create files and folders in share2.

`drwxrwxr-x  4 emby emby     0 Feb  8 22:32 <common_path>/`
`drwxrwxr-x  4 emby emby     0 Feb  8 22:32 <path1>/`
`drwxrwxr-x  3 emby emby     0 Feb  8 19:14 <path2>/`

**Comment by tolotos-rgu** [comment]
Without every mount

`drwxrwxr-x  2 emby emby  4096 Nov 14 17:33 <common-path>`
`drwxrwxr-x  2 emby emby  4096 Nov  8 17:45 <path1>`
`drwxrwxr-x  2 emby emby  4096 Feb  7 00:21 <path2>`

**Comment by trapexit** [comment]
I just created a cifs mount with similar options to you and was able to read and write to it and then mounted it using mergerfs and similarly had no issues.

Unless you provide me with very specific details to reproduce I'm not sure what else I can do. mergerfs, when running as root and with allow_other, impersonates the caller. Except when doing special behaviors (cloning paths between drives) which could be root squashed there shouldn't be an issue. If it is being root squashed then that's the problem. It should be running as the user. I could try to work around that by retrying things as the user when root gets permission denied in certain things.

**Comment by tolotos-rgu** [comment]
What do you mean with 'root squashed' ? 
All commands above where run as root user.

**Comment by trapexit** [comment]
https://en.wikipedia.org/wiki/Unix_security#Root_squash

I don't know if cifs does that... I'm about to look into it... but on NFS it can be a problem.

**Comment by tolotos-rgu** [comment]
Hmm, the shares are from my provider. I rent the disc space and get the share data to mount. 
As I can write as root direct into the second share I think that's not the problem - isn't it?

**Comment by tolotos-rgu** [comment]
The mount command gives the following for the mounted shares:

`<share1> on <path1> type cifs (rw,relatime,vers=1.0,cache=strict,username=u138443,domain=PUBLICBACKUP208,uid=109,forceuid,gid=115,forcegid,addr=2a01:04f8:0b16:1000:0000:0000:0000:0056,unix,posixpaths,serverino,mapposix,rsize=1048576,wsize=65536,actimeo=1)`
`<share2> on <path2> type cifs (rw,relatime,vers=1.0,cache=strict,username=u141605,domain=PUBLICBACKUP231,uid=109,forceuid,gid=115,forcegid,addr=2a01:04f8:0b16:1000:0000:0000:0000:0088,unix,posixpaths,serverino,mapposix,rsize=1048576,wsize=65536,actimeo=1)`

**Comment by tolotos-rgu** [comment]
I changed the order in the fstab to `<path2>:<path1> <common_path>` and no I can write again?!

**Comment by tolotos-rgu** [comment]
Is there any possibility to turn on logging in mergerfs to find the reason?

**Comment by trapexit** [comment]
No. Logging is a side effect and having that as part of a filesystem can be an issue.

Without extremely specific details I can't comment further. I need any paths involved, all their acls, owners, etc. All my tests have worked fine. You can try strace'ing mergerfs (strace -f -o /tmp/trace.txt -p mergerfsPid) and performing the file creation to see what's happening. As I mentioned mergerfs is just a proxy. It impersonates the user making the call. Permission issues are almost always a result of misaligned or strange (nonstandard) underlying permissions. CIFS is non-standard.

Have you tried creating files as some other user? Have you tried running mergerfs as non-root?

**Comment by tolotos-rgu** [comment]
Here is the output of strace:
```
1658  read(3,  <unfinished ...>
5355  read(3,  <unfinished ...>
5351  read(3,  <unfinished ...>
5350  read(3,  <unfinished ...>
5343  read(3,  <unfinished ...>
5341  read(3,  <unfinished ...>
1657  read(3,  <unfinished ...>
1654  read(3,  <unfinished ...>
1656  read(3,  <unfinished ...>
1651  read(3,  <unfinished ...>
655   futex(0x7ffd9c567760, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff <unfinished ...>
1658  <... read resumed> "8\0\0\0\3\0\0\0\343\206\2\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 56
1658  lstat("/extDrives/emby_storage_001/", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
1658  lstat("/extDrives/emby_storage_001/", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
1658  writev(3, [{"x\0\0\0\0\0\0\0\343\206\2\0\0\0\0\0", 16}, {"\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\4\0\0\0)\0\0\0\0\0\0\0\0\0\0\0"..., 104}], 2) = 120
1658  read(3,  <unfinished ...>
5355  <... read resumed> "2\0\0\0\1\0\0\0\344\206\2\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 50
5355  lstat("/extDrives/emby_storage_001/test.data", 0x7ffa377f5190) = -1 ENOENT (No such file or directory)
5355  lstat("/extDrives/emby_storage_002/test.data", 0x7ffa377f5190) = -1 ENOENT (No such file or directory)
5355  writev(3, [{"\20\0\0\0\376\377\377\377\344\206\2\0\0\0\0\0", 16}], 1) = 16
5351  <... read resumed> "B\0\0\0#\0\0\0\345\206\2\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 66
5355  read(3,  <unfinished ...>
5351  lstat("/extDrives/emby_storage_001", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
5351  lstat("/extDrives/emby_storage_001", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
5351  statfs("/extDrives/emby_storage_001", {f_type=0xff534d42, f_bsize=512, f_blocks=20971520000, f_bfree=6064153, f_bavail=6064153, f_files=6097312, f_ffree=6064153, f_fsid={0, 0}, f_namelen=4096, f_frsize=512, f_flags=4128}) = 0
5351  lstat("/extDrives/emby_storage_002", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
5351  statfs("/extDrives/emby_storage_002", {f_type=0xff534d42, f_bsize=512, f_blocks=4194304000, f_bfree=4194303488, f_bavail=4194303488, f_files=4194303496, f_ffree=4194303488, f_fsid={0, 0}, f_namelen=4096, f_frsize=512, f_flags=4128}) = 0
5351  stat("/extDrives/emby_storage_001", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
5351  mkdir("/extDrives/emby_storage_002", 040775) = -1 EEXIST (File exists)
5351  chmod("/extDrives/emby_storage_002", 040775) = 0
5351  open("/extDrives/emby_storage_001", O_RDONLY|O_NONBLOCK) = 4
5351  ioctl(4, FS_IOC_GETFLAGS, 0x7ffa55ff20c0) = -1 ENOTTY (Inappropriate ioctl for device)
5351  close(4)                          = 0
5351  llistxattr("/extDrives/emby_storage_001", NULL, 0) = 0
5351  open("/extDrives/emby_storage_002", O_RDONLY|O_NONBLOCK) = 4
5351  close(4)                          = 0
5351  chown("/extDrives/emby_storage_002", 109, 115) = -1 EACCES (Permission denied)
5351  writev(3, [{"\20\0\0\0\363\377\377\377\345\206\2\0\0\0\0\0", 16}], 1) = 16
5351  read(3,  <detached ...>
```

**Comment by tolotos-rgu** [comment]
The folders on which the shares and the mergerfs are mounted are owned by `user:group = emby:emby`. 
The permissions are 
```
root@emby /extDrives # ll
total 40
drwxr-xr-x  8 root root  4096 Jan  5 23:40 ./
drwxr-xr-x 25 root root  4096 Feb  3 10:53 ../
drwxrwxr-x  4 emby emby     0 Feb  8 22:32 emby_common/
drwxrwxr-x  4 emby emby     0 Feb  8 22:32 emby_storage_001/
drwxrwxr-x  3 emby emby     0 Feb  8 23:13 emby_storage_002/
drwx------  2 root root 16384 Aug 27 20:28 lost+found/
```

All files and folders below `\extDrives\emby_common` have 775 (folders) and 664 (files).

I tried creating the files as user root and emby with the same results. 
Mounting the mergerfs as user emby and writing as user emby ends with the same result.

**Comment by trapexit** [comment]
`5351  chown("/extDrives/emby_storage_002", 109, 115) = -1 EACCES (Permission denied)`

As root can you chown that path?

**Comment by tolotos-rgu** [comment]
```
root@emby /extDrives/emby_storage_002 # ll
total 4
drwxrwxr-x 3 emby emby    0 Feb  8 23:13 ./
drwxr-xr-x 8 root root 4096 Jan  5 23:40 ../
drwxrwxr-x 2 emby emby    0 Feb  8 23:17 __transcode/
```
```
root@emby /extDrives/emby_storage_002 # chown root:root __transcode/
chown: changing ownership of '__transcode/': Permission denied
```

**Comment by tolotos-rgu** [comment]
I can create files and folders as user root and emby but can't change ownership as both users.

**Comment by trapexit** [comment]
Clearly root (and therefore mergerfs) doesn't have full permissions over the underlying drives. It's non-standard.

I'm not sure what I can do here besides ignore the error (which is not ideal). mergerfs is trying to duplicate the filepath from one drive to the other. The only valid way to do that is to try it and let the action succeed or error and responded accordingly.

Have you tried using `noperm` in your cifs mount? https://linux.die.net/man/8/mount.cifs

**Comment by tolotos-rgu** [comment]
I added the `noperm` into fstab and remounted the shares. It gives the same result. 
I think I should no contact the provider from which the shares are provided now. 
Maybe he must change something. 

Thank you for your help!

**Comment by trapexit** [comment]
I'm not familiar enough with cifs to make suggestions but looking up "chmod cifs permission denied" on Google shows some suggestions but it's not clear if it can work without returning permission denied.

I can look at handling these errors in a way where it'll only return an error if the state of the file (for example the owner or mode) is not what I wanted it to be. 

Unfortunately CIFS is just not standard with regard to permissions and such so this kind of stuff happens. Ideally it'd allow chown/chmod calls even if it ignored them.

**Comment by tolotos-rgu** [comment]
Is ignoring chown/chmod possible with settings or must this be implemented first? 
I Google around like you and tried lots of suggestions I found. But nothing is working. 
So if I can set a special "CIFS"-mode (ignore the two calls which are not supported in CIFS) it would be nice.

**Comment by trapexit** [comment]
It would need to be implemented. I think I can do it in a way that won't need explicitly being enabled. I'll take a look.

**Comment by tolotos-rgu** [comment]
Thank you.

**Comment by tolotos-rgu** [comment]
I played around with the sources and this two changes let the system work: 

```
diff --git a/src/chown.cpp b/src/chown.cpp
index 2c15ffc..e2df025 100644
--- a/src/chown.cpp
+++ b/src/chown.cpp
@@ -96,6 +96,7 @@ namespace mergerfs
           uid_t       uid,
           gid_t       gid)
     {
+/*
       const fuse_context      *fc     = fuse_get_context();
       const Config            &config = Config::get(fc);
       const ugid::Set          ugid(fc->uid,fc->gid);
@@ -107,6 +108,8 @@ namespace mergerfs
                     fusepath,
                     uid,
                     gid);
+*/
+     return 0;
     }
   }
 }
diff --git a/src/fs_clonepath.cpp b/src/fs_clonepath.cpp
index c81e643..dcfae38 100644
--- a/src/fs_clonepath.cpp
+++ b/src/fs_clonepath.cpp
@@ -97,8 +97,8 @@ namespace fs
       return -1;

     rv = fs::chown(topath,st);
-    if(rv == -1)
-      return -1;
+    //if(rv == -1)
+    //  return -1;

     rv = fs::utime(topath,st);
     if(rv == -1)
``` 

I know this is not a solution for all, but with cifs it works.

**Comment by trapexit** [comment]
Yes. I'm aware of where the issue is but doing those things break normal usage.

**Comment by tolotos-rgu** [comment]
Yes, i know that this breaks the normal operation. I changed it locally to get the system running further. 
Hopefully you find a common solution for all users.

**Comment by tolotos-rgu** [comment]
Your branch is active now. I let the system run for the next 24h and check if all is working. 
I'll report the results tomorrow.

**Comment by trapexit** [comment]
Can you not recreate the situation you did originally?

**Comment by tolotos-rgu** [comment]
I can create files and folders manually. This will created on the second mount. 
At this time all manual stuff works great but I want to check if the service is running as well.

**Comment by tolotos-rgu** [comment]
Ok, the first file was written by the service. 
You can delete my pull request. 

Thank you!!

**Comment by trapexit** [comment]
No problem. The change will be included in the next release.
