### ISSUE TITLE
Mergerfs is 'mounting', but I'm not seeing the contents of the drives...

### ISSUE THREAD

**Issue by maxiedaniels** [trapexit/mergerfs#368]
I have two drives, located at /media/StorageDisk1 and /media/StorageDisk2 that I'm trying to merge into one folder, located at /media/Storage.

I tried the fstab line: `/media/StorageDisk*  /media/Storage  fuse.mergerfs  defaults,allow_other,use_ino  0       0`

But while I'm seeing 'Storage' mounted after a restart, there's no files in it (while there are a lot of files in each of my storage disks). I also tried `mergerfs -o defaults,allow_other,use_ino /media/StorageDisk\* /media/Storage` but I have the same issue.

Any ideas??

**Comment by trapexit** [comment]
What version are you using? You should only use `use_ino` with `2.19.0` or greater.

Be sure to look at documentation for the version you're using... the docs on this site are always for the latest.

**Comment by maxiedaniels** [comment]
Oh - I'm using 2.14.0, the version that's in the apt repository for Ubuntu.. I'll update now and retry.. thanks!
