### ISSUE TITLE
Yaketty releases

### ISSUE THREAD

**Issue by mtompkins** [trapexit/mergerfs#380]
Thanks for such a great solution. I've noticed that (at least by naming convention) Yaketty specific releases haven't been issued since 2.13.1 While I presume the Xenial releases will work as expected, I figured I'd ask for a bit of clarity.

If I missed some notice somewhere of this condition and to simply use Xenial named releases, apologies.

**Comment by trapexit** [comment]
I'm only providing LTS packages unless they won't work for other releases.

**Comment by mtompkins** [comment]
Perfecto - thanks for the confirmation
