### ISSUE TITLE
Sonarr: Importing files into MergerFS volume fails with IOException 25

### ISSUE THREAD

**Issue by LanderN** [trapexit/mergerfs#381]
Log from sonarr:
```
17-4-3 17:00:26.6|Warn|ImportApprovedEpisodes|Couldn't import episode /mnt/hdd3/Downloads/Complete/xxxxxxxxxxxxxxxx.mkv

[v2.0.0.4645] System.IO.IOException: Win32 IO returned 25. Path: 
  at System.IO.File.Move (System.String sourceFileName, System.String destFileName) <0x7ff70e15a5c0 + 0x002f0> in <filename unknown>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, Boolean overwrite) <0x411c4680 + 0x0024c> in <filename unknown>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional (System.String sourcePath, System.String targetPath, Int64 originalSize, DiskTransferVerificationMode verificationMode) <0x411c3240 + 0x00189> in <filename unknown>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) <0x411c2000 + 0x00a5b> in <filename unknown>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) <0x41151f60 + 0x0005b> in <filename unknown>:0 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Tv.Series series, System.Collections.Generic.List`1 episodes, System.String destinationFilePath, TransferMode mode) <0x411c1890 + 0x00439> in <filename unknown>:0 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode) <0x411b64b0 + 0x0011f> in <filename unknown>:0 
  at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, Boolean copyOnly) <0x411b5500 + 0x005b7> in <filename unknown>:0 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import (System.Collections.Generic.List`1 decisions, Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, ImportMode importMode) <0x411afcf0 + 0x0143a> in <filename unknown>:0 
```

`xattr -l`:
```
user.mergerfs.srcmounts: /mnt/hdd1:/mnt/hdd2:/mnt/hdd3:/mnt/hdd4
user.mergerfs.minfreespace: 4294967295
user.mergerfs.moveonenospc: true
user.mergerfs.policies: all,epall,epff,eplfs,eplus,epmfs,eprand,erofs,ff,lfs,lus,mfs,newest,rand
user.mergerfs.version: 2.20.0
user.mergerfs.pid: 911
user.mergerfs.category.action: all
user.mergerfs.category.create: epmfs
user.mergerfs.category.search: ff
user.mergerfs.func.access: ff
user.mergerfs.func.chmod: all
user.mergerfs.func.chown: all
user.mergerfs.func.create: epmfs
user.mergerfs.func.getattr: ff
user.mergerfs.func.getxattr: ff
user.mergerfs.func.link: all
user.mergerfs.func.listxattr: ff
user.mergerfs.func.mkdir: epmfs
user.mergerfs.func.mknod: epmfs
user.mergerfs.func.open: ff
user.mergerfs.func.readlink: ff
user.mergerfs.func.removexattr: all
user.mergerfs.func.rename: all
user.mergerfs.func.rmdir: all
user.mergerfs.func.setxattr: all
user.mergerfs.func.symlink: epmfs
user.mergerfs.func.truncate: all
user.mergerfs.func.unlink: all
user.mergerfs.func.utimens: all
```

fstab:
```
#1TB disk
UUID="01CF0FAAA5015A60" /mnt/hdd1       ntfs auto,rw,user,noatime,async,bigwrites,uid=1000,gid=1000,umask=0000  0       0
#2TB disk
UUID="2319473D3482E061" /mnt/hdd2       ntfs auto,rw,user,noatime,async,bigwrites,uid=1000,gid=1000,umask=0000  0       0
#3TB disk
UUID="05E4009F6CB6D1A0" /mnt/hdd3       ntfs auto,rw,user,noatime,async,bigwrites,uid=1000,gid=1000,umask=0000  0       0

/mnt/hdd*      /srv/samba/media        fuse.mergerfs defaults,allow_other,use_ino,moveonenospc  0       0
```

Any ideas are welcome (I plan to use rtorrent, so that's why I didn't include `direct_io`).

**Comment by trapexit** [comment]
I don't know. According to what I've found online [0] that error indicates a SEEK issue but I'm not sure why that would happen. Some poorly written apps don't handle certain rename/move errors all that well but given this is a C# app running via a few levels of indirection (samba, ntfs fuse, etc.) I can really comment. Need to narrow down the possibilities. First I'd try changing the policy to non-path preserving. Perhaps the reported error is wrong. 

If that doesn't work you may want to contact Sonarr folks.

[0] https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382%28v=vs.85%29.aspx

**Comment by LanderN** [comment]
Thanks for the lightning fast response!

Setting the create category to ff seems to have done the trick! Is this expected behavior? Also, how can i persist this change in fstab? Add `category.create=ff` to the options?

**Comment by trapexit** [comment]
Does `mfs` or other non-path preserving policies also work? If yes... then yes... expected as defined in the docs under the caveats for rename & link[0] and the FAQ section on SAMBA[1]. The software is poorly written and doesn't handle a situation it should.

As to setting it from the command line, yes[0].

[0] https://github.com/trapexit/mergerfs#rename--link
[1] https://github.com/trapexit/mergerfs#samba-moving-files--directories-fails
[2] https://github.com/trapexit/mergerfs#options

**Comment by LanderN** [comment]
I think I was confused because of the fact that epmf was listed as path preserving instead of epmfs, so I assumed epmfs was non path preserving. It's of course obvious it was just a typo. For the samba thing, I assumed it was only applicable when actually using samba to move the files, apparently it is not. Thanks for your time!

**Comment by trapexit** [comment]
I'll fix that typo. Thanks.

It's the Samba client really. That's why it affects multiple systems. Samba itself isn't trying to hide the fact that a file can be asked to move it cross devices and returns the appropriate error. It's just that some apps, including SMB clients, fail to handle it correctly.

Unfortunately it's a very common problem. I could, in mergerfs, do more to hide the error but some apps not only handle the situation correctly but try to do things explicitly when they notice that situation has arisen. It's impossible for me to know what to do. Hide the issue or report it. 

I can try to add a more generic warning about apps which fail to handle rename.

**Comment by LanderN** [comment]
That is indeed impossible to fix for everybody, but maybe there could be an option to try to hide/mask the error for people using applications that have this problem? 

This issue does not exist in mhddfs, so is mhddfs non-path preserving by default then? If so, maybe MergerFS should also be non-path preserving by default to provide better compatibility with users switching from mhddfs? Maybe even an "acts just like mhddfs"-configuration in the Readme for people having issues?

**Comment by trapexit** [comment]
It's very very difficult and expensive to have per application behavior. Broken apps should be fixed. It's not a mergerfs issue. This is a totally valid situation.

Mhddfs does not provide policies at all and works basically like ff.  The reason it defaults to epmfs is because in general people have seemed to prefer that. But not matter what I select someone wont like it. Which is why there are opinions. 

I can add more documentation to point people to select different options but I can't just change the default. People need to read the documentation and pick the appropriate settings for their needs.

**Comment by LanderN** [comment]
Makes a lot of sense! Anyways, thanks for the great software and support! I will close this issue now, since it's not a bug in MergerFS.

**Comment by trapexit** [comment]
I'd suggest submitting a ticket with Sonarr and asking them to be sure that when moving files that `EXDEV` is properly supported.

**Comment by trapexit** [comment]
I've updated the documentation to more clearly explain `EXDEV` issues. Hopefully it helps.

https://github.com/trapexit/mergerfs/commit/215f129a2a0f00a1d6ab3ecafbcd5af29c09fc7d

**Comment by trapexit** [comment]
@LanderN Can you strace mergerfs when using `mv` to rename the file? 

`strace -f -o /tmp/mergerfs.trace -p $(pgrep mergerfs)`

should do it

**Comment by LanderN** [comment]
Can I send you the trace privately (there might be personal information in there i suppose)?

**Comment by trapexit** [comment]
trapexit@spawn.link

**Comment by LanderN** [comment]
For anyone that might be interested: @trapexit has possibly identified the issue and is working on a patch.

**Comment by trapexit** [comment]
Are you able to build and try the branch clone-errors? If not I can provide a build if you let me know your platform.

**Comment by LanderN** [comment]
Since this is a headless box, it would indeed be easier if you could provide a build. I'm on Debian x64.

**Comment by trapexit** [comment]
[mergerfs_2.20.0-5-gc043ef9~debian-jessie_amd64.zip](https://github.com/trapexit/mergerfs/files/892754/mergerfs_2.20.0-5-gc043ef9.debian-jessie_amd64.zip)

**Comment by LanderN** [comment]
No more error on move 👍

**Comment by trapexit** [comment]
Cool. I'll merge the branch and include it in the next release.

Thanks for finding a bug :)

**Comment by LanderN** [comment]
Happy to help!
