### ISSUE TITLE
fuse: trying to steal weird page

### ISSUE THREAD

**Issue by jkansanen** [trapexit/mergerfs#401]
Hi,

I'm getting these errors if direct_io mount option isn't used (no errors if direct_io is used):

kernel: fuse: trying to steal weird page
kernel:  page=ffffea0005320080 index=1120 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:  page=ffffea0005329d00 index=3932 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:  page=ffffea00081a3dc0 index=4160 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:  page=ffffea00068b8b00 index=5983 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:  page=ffffea0005df2a40 index=7264 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:  page=ffffea0004bd1b40 index=3672 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:  page=ffffea0004bd20c0 index=3673 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:  page=ffffea0004bd43c0 index=3679 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)

more info:

mergerfs version: 2.20.0-dirty
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

Linux 4.10.6 #1 SMP  x86_64 GNU/Linux

filesystems are BTRFS

**Comment by trapexit** [comment]
What are your other settings?

**Comment by jkansanen** [comment]
mergerfs -o defaults,direct_io,allow_other,use_ino,noforget,fsname=storage,minfreespace=20G,moveonenospc=true /snapraid/storage_d* /storage/

**Comment by trapexit** [comment]
Can you try replacing `defaults` with `atomic_o_trunc,auto_cache,big_writes,default_permissions` (ie... leaving out the splice_move, splice_read, and splice_write options which defaults also adds)

**Comment by trapexit** [comment]
I've fired off an email to the FUSE development list to see if anyone knows more about that error. I've seen it before but randomly and could never track down what was causing it.

**Comment by jkansanen** [comment]
I did some more testing and this issue only happens if i use mergerfs through NFS share. No problems with local access, also there's no issue with NFS if I use options: atomic_o_trunc,auto_cache,big_writes,default_permissions,allow_other,use_ino,noforget,fsname=storage,minfreespace=20G,moveonenospc=true

**Comment by trapexit** [comment]
Could you try the `split_*` options one by one and in combination to see which of those cause it?

**Comment by jkansanen** [comment]
The problem seems to be with direct_io writes (NFS uses DIO) and splice_read with >=4096 byte writes example:

**with splice_read:**

FAILS while writing:

dd if=/storage/path1/testfile of=/storage/path2/testfile iflag=direct oflag=direct **bs=4096** count=10
dd: error writing '/storage/path2/testfile': Bad address
1+0 records in
0+0 records out 

OK with <4096 blocksize:

dd if=/storage/path1/testfile of=/storage/path2/testfile iflag=direct oflag=direct **bs=4095** count=10
10+0 records in
10+0 records out 

**without splice_read:**

OK:
dd if=/storage/path1/testfile of=/storage/path2/testfile iflag=direct oflag=direct **bs=4096** count=10
10+0 records in
10+0 records out 

OK:
dd if=/storage/path1/testfile of=/storage/path2/testfile iflag=direct oflag=direct **bs=4095** count=10
10+0 records in
10+0 records out

**Comment by trapexit** [comment]
According to the FUSE kernel maintainer:

> I think this is due to the PageWaiters bit added in v4.10 by
> 
> 62906027091f ("mm: add PageWaiters indicating tasks are waiting for a page bit")
> 
> That bit is harmless and probably left behind due to a race.  Following patch
> should fix the warning.
> 
> Thanks,
> Miklos
> 
> ---
>  fs/fuse/dev.c |    1 +
>  1 file changed, 1 insertion(+)
> 
> --- a/fs/fuse/dev.c
> +++ b/fs/fuse/dev.c
> @@ -811,6 +811,7 @@ static int fuse_check_page(struct page *
>                1 << PG_uptodate |
>                1 << PG_lru |
>                1 << PG_active |
> +              1 << PG_waiters |
>                1 << PG_reclaim))) {
>                 printk(KERN_WARNING "fuse: trying to steal weird page\n");
>                 printk(KERN_WARNING "  page=%p index=%li flags=%08lx, count=%i, mapcount=%i, mapping=%p\n", page, page->index, page->flags, page_count(page), page_mapcount(page), page->mapping);

**Comment by trapexit** [comment]
He thinks the bad address issue is something else.

Could you run the test where you got that error and `strace -o /tmp/mergerfs.trace -f -p $(pgrep mergerfs)` before doing so?

**Comment by jkansanen** [comment]
mergerfs -o splice_read,atomic_o_trunc,auto_cache,big_writes,default_permissions,allow_other,use_ino,noforget,f    sname=storage,minfreespace=20G,moveonenospc=true /snapraid/storage_d* /storage/

**dd if=/storage/path1/testfile of=/storage/path2/testfile iflag=direct oflag=direct bs=4096 count=10** (failed)

https://pastebin.com/GJzAgpax

**dd if=/storage/path1/testfile of=/storage/path2/testfile iflag=direct oflag=direct bs=4095 count=10** (OK)

https://pastebin.com/W8GWjghZ

**Comment by trapexit** [comment]
Would it be possible to test a pre 4.9 kernel?

**Comment by jkansanen** [comment]
Linux debian 4.7.0-1-amd64 #1 SMP Debian 4.7.2-1 (2016-08-28) x86_64 GNU/Linux
mergerfs version: 2.20.0-42-g25ce993
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

dd if=foo of=foo2 iflag=direct oflag=direct bs=4096 count=10
dd: error writing 'foo2': Bad address

**Comment by icebal** [comment]
just noticed i am also having this issue, version info below:
arch 4.14.2-2
mergerfs version: 2.23.1-1
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
splice option are all on, dd with bs over 4095 works fine as well

**Comment by seuffert** [comment]
also seeing this issue, updated mergerfs still having it. quite a lot of entries in kernel log...

ubuntu 17.10 / Linux 4.13.0-21-generic
mergerfs version: 2.23.1-12-gb48054f (current git self compiled)
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

`mergerfs -o defaults,ro,allow_other,use_ino,dropcacheonclose=true,symlinkify=true,symlinkify_timeout=10`

> [776372.567851] fuse: trying to steal weird page
> [776372.567857]   page=ffffef05827630c0 index=584378 flags=fffffc00000ad, count=1, mapcount=0, mapping=          (null)

**Comment by animosity22** [comment]
I noticed the same thing in my logs as well:

```
[340084.270219] fuse: trying to steal weird page
[340084.270220]   page=ffffea00153cba40 index=14 flags=17fffc00000002b, count=1, mapcount=0, mapping=          (null)
[340084.270221] fuse: trying to steal weird page
[340084.270223]   page=ffffea00153cba80 index=15 flags=17fffc00000002b, count=1, mapcount=0, mapping=          (null)
felix     4978     1  0 Jan05 ?        00:04:08 /usr/bin/mergerfs -o defaults,allow_other,use_ino,category.action=all,category.create=ff /local/movies:/media/Movies /Movies
felix     4990     1  0 Jan05 ?        00:07:22 /usr/bin/mergerfs -o defaults,allow_other,use_ino,category.action=all,category.create=ff /local/tv:/media/TV /TV
```

Doesn't seem to cause any issues from what I can tell.

**Comment by seuffert** [comment]
may i ask why this was closed? the issue still persists in the current version

**Comment by trapexit** [comment]
AFAIK its a kernel issue and nothing to do with mergerfs. I can leave it open but I've reported it upstream and is generally out of my hands.

**Comment by ahippo** [comment]
Just for the record, the issue still persists on
 * Linux 4.16.9-gentoo x86_64
 * mergerfs 2.24.2
 * fuse 2.9.7
 * mount options: `defaults,hard_remove,dropcacheonclose=true,moveonenospc=true,minfreespace=64M,auto_unmount`
 (i.e., _no_ direct_io)
 * underlying FS: two ext4 over loopback devices over another ext4
```
fuse: trying to steal weird page
  page=00000000c5d1cde0 index=736 flags=80000000000000ad, count=1, mapcount=0, mapping=          (null)
fuse: trying to steal weird page
  page=00000000aad99da7 index=2144 flags=80000000000000ed, count=1, mapcount=0, mapping=          (null)
fuse: trying to steal weird page
  page=0000000046d3b38e index=368 flags=40000000000000ad, count=1, mapcount=0, mapping=          (null)
```

**Comment by fcying** [comment]
I found the same log in my journalctl log as well, but doesn't seem to cause write & read errors.
```
kernel:   page=fffff0f545d5a940 index=1335588 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f546f55340 index=632708 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f545185000 index=1342233 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f545a039c0 index=1343705 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f545ba6300 index=1344505 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f544c3b100 index=1355777 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f5475a2300 index=1355809 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f544440180 index=1383204 flags=afffe00000000ad, count=1, mapcount=0, mapping=          (null)
kernel: fuse: trying to steal weird page
kernel:   page=fffff0f5406eef40 index=3415768 flags=1fffe00000000ad, count=1, mapcount=0, mapping=          (null)
```

**Comment by EnorMOZ** [comment]
Something of note which is interesting. When ran via .mount `local:remote on /mnt/merged type fuse.mergerfs (rw,noatime,user_id=0,group_id=0,allow_other)` vs .system file or manually `local:remote on /mnt/merged type fuse.mergerfs (rw,nosuid,nodev,noatime,user_id=1000,group_id=1000,default_permissions,allow_other)` Same options provided in all commands.  However running `mount` shows different options were added.

**Comment by trapexit** [comment]
This is possibly a kernel issue and I'm unable to reproduce it. It did happen to me a couple years ago briefly but never since. Until causes are narrowed down I'm not sure what I can do. Can you create a small VM which exhibits the problem?

**Comment by EnorMOZ** [comment]
@trapexit I posted a separate issues somewhat related to this. https://github.com/trapexit/mergerfs/issues/572  Did some digging and depending on how you mount  mergerfs can cause this issue. Seems like certain flags are added when .service or cli is ran an are not added when using a .mount file.

**Comment by trapexit** [comment]
Not sure where the adding is happening. Might be fusermount. Will need to look. They seem pretty harmless... Not sure why they'd cause this but if we can reproduce it I can talk with the kernel maintainer.

My contact info is in the docs.

**Comment by trapexit** [comment]
Let me see if I can reproduce it on my system with those. I use default_permissions as I include it in 'defaults'.

**Comment by rajil** [comment]
This is happening on my ArchLinux host. Here are the details,
```

atomic_o_trunc,big_writes,default_permissions,splice_move,splice_read,splice_write,allow_other,direct_io,use_ino,category.create=mfs,minfreespace=100G

Linux box 5.4.25-2-lts

[56394.682834] fuse: trying to steal weird page
[56394.682841] fuse:   page=0000000014218101 index=666584 flags=affff0000000097, count=1, mapcount=0, mapping=00000000c18be74e

```
