### ISSUE TITLE
allow_other not allowing any other

### ISSUE THREAD

**Issue by Atario** [trapexit/mergerfs#404]
For some reason `allow_other` isn't working for me, at all.  At least, I *think* that's what's going on.

I'm on v.2.20.0 of `mergerfs`; OS is Ubuntu 16.04.2 LTS.

My `fstab` line is this:

>     /srv/storage/c*/u /srv/storage/union2 fuse.mergerfs defaults,noauto,noatime,use_ino,dropcacheonclose=true,category.create=mfs,allow_other 0 2

Here is what happens:

>     foo@bar:~$ ls -la /srv/storage
>     total 76
>     drwxr-xr-x 19 root root 4096 Apr 14 10:17 .
>     drwxr-xr-x  3 root root 4096 Dec 23  2013 ..
>     drwxr-x---  4 root root 4096 Apr 14 07:28 c1d1
>     drwxr-x---  4 root root 4096 Apr 14 07:28 c1d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d3
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d4
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d5
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d1
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d3
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d4
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d5
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d1
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d3
>     drwxr-x---  3 root root 4096 Dec 29  2013 c3d4
>     drwxr-x---  3 root root 4096 Dec 29  2013 c3d5
>     drwxr-xr-x  5 root root 4096 Feb 16  2016 union
>     drwxr-xr-x  2 root root 4096 Apr 14 10:17 union2
>     foo@bar:~$ sudo mount /srv/storage/union2
>     foo@bar:~$ ls -la /srv/storage
>     ls: cannot access '/srv/storage/union2': Permission denied
>     total 72
>     drwxr-xr-x 19 root root 4096 Apr 14 10:17 .
>     drwxr-xr-x  3 root root 4096 Dec 23  2013 ..
>     drwxr-x---  4 root root 4096 Apr 14 07:28 c1d1
>     drwxr-x---  4 root root 4096 Apr 14 07:28 c1d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d3
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d4
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d5
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d1
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d3
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d4
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d5
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d1
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d3
>     drwxr-x---  3 root root 4096 Dec 29  2013 c3d4
>     drwxr-x---  3 root root 4096 Dec 29  2013 c3d5
>     drwxr-xr-x  5 root root 4096 Feb 16  2016 union
>     d?????????  ? ?    ?       ?            ? union2
>     foo@bar:~$ sudo ls -la /srv/storage
>     total 76
>     drwxr-xr-x 19 root root 4096 Apr 14 10:17 .
>     drwxr-xr-x  3 root root 4096 Dec 23  2013 ..
>     drwxr-x---  4 root root 4096 Apr 14 07:28 c1d1
>     drwxr-x---  4 root root 4096 Apr 14 07:28 c1d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d3
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d4
>     drwxr-x---  4 root root 4096 Dec 28  2013 c1d5
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d1
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d3
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d4
>     drwxr-x---  4 root root 4096 Dec 28  2013 c2d5
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d1
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d2
>     drwxr-x---  4 root root 4096 Dec 28  2013 c3d3
>     drwxr-x---  3 root root 4096 Dec 29  2013 c3d4
>     drwxr-x---  3 root root 4096 Dec 29  2013 c3d5
>     drwxr-xr-x  5 root root 4096 Feb 16  2016 union
>     drwxr-xr-x  5 root root 4096 Feb 16  2016 union2
>     foo@bar:~$ 

`root` can see and work inside `union2` just fine, but no one else.

(That other `union` is from `mhddfs`, which I'm trying to get rid of as soon as I have `mergerfs` working.  It has the same `allow_other` setting specified and is working (such as it is).)

**Comment by trapexit** [comment]
Note your permissions. Only root has access to read.

**Comment by trapexit** [comment]
And read the docs. I mention visibility issues in the tips section.

**Comment by Atario** [comment]
You mean the `c?d?` folders?  The `u` folders inside those (which are the actual ones being sourced) have `rwxr-xr-x`.

**Comment by trapexit** [comment]
If the parent directory is not accessible by the user then neither is the children.

**Comment by trapexit** [comment]
The reason it probaby works with mhddfs is because it's not doing things correctly. It plays fast and loose with permissions.

**Comment by Atario** [comment]
It's too bad there's no provision given for my use case, then.  I'd rather restrict access as much as I can to the direct sources, and instead force users to access through the merged view only.  It sounds like I have no choice but to let everyone get in every which way.

**Comment by trapexit** [comment]
Then bind mount the sub directories elsewhere and merge those. mergerfs is literally merging paths together. If the user doesn't have access to that original path then it's not granted in exactly the same way it normally would. mhddfs is actually reading the path as root so you're actually getting a backdoor view into something you shouldn't.

**Comment by Atario** [comment]
I'm not sure how the bind mount suggestion would accomplish what I'm trying to do.  Wouldn't everyone still have to have direct access to each of them, without having to go through the merged filesystem?

**Comment by trapexit** [comment]
Sorry, bind mounts and mount namespaces. Just like containers do. 

Why is it a problem to let users see the underlying filesystem?

**Comment by Atario** [comment]
It leaves it open to being messed with — mismatching permissions, wrecking the free-space balancing, duplicating files, etc.  Same reason users can't write to the underlying storage mechanism of any filesystem, really.

**Comment by trapexit** [comment]
What are you using this for? This sounds like an atypical concern in that most usecases are single user machines or not given direct access anyway. If you have multiple users then mount namespaces are the correct way to limit visibility. The fact it worked with mhddfs as I mentioned is really a severe security violation which was one of the reasons I wrote mergerfs.

AFAIK you could setup something with /etc/security/namespace.conf but I'm not very familiar with it's use. If you figure it out I'd be happy to include something in the docs to articulate for others.

**Comment by Atario** [comment]
It's a Samba file server that has a bunch of storage HDDs under Snapraid, with a few other server functions accumulated over time.  I use a merging file system to present everything as one big storage area and automatically manage the internal space balancing and such.  Access via Samba is permission-enforced by Samba's own mechanisms.  It's the on-server processes and such that come into play in this scenario.

I suppose it's not the end of the world if I just have to suck it up and allow it.  As long as it means I no longer have to babysit the thing when creating a bunch of big files (transport endpoint disappeared!  Unmount and remount and restart services that were working on it, *again!*), it would still be a win.

I'm not too familiar with the concept of mount namespaces, but it sounds as though the child namespace would still require direct access to the source mount points for anything within the child namespace to work — am I understanding that right?  Or is it possible for the child namespace to have them removed and the parent to automatically handle the translation back to the real setup, or some such?  Sorry for the noob quiz questions.

At any rate, poking around a little, it seems as though setting `default_permissions` makes `mhddfs` behave the same way `mergerfs` does — enforcing all permissions as usual.  But leaving it off allows everyone who can see the mount to access everything inside it.  I do remember trying turning off `default_permissions` with `mergerfs`, but it didn't change any behavior, and [the FUSE docs](https://www.kernel.org/doc/Documentation/filesystems/fuse.txt) seem to indicate that what `mhddfs` does is at least condoned ("By default FUSE doesn't check file access permissions, the filesystem is free to implement its access policy or leave it to the underlying file access mechanism")…

**Comment by trapexit** [comment]
default_permissions causes the kernel to enforce permissions based on data already given to the kernel instead of asking the process. This improves performance when you're mimicking exactly standard POSIX entitlements. Which given what mergerfs and mhddfs do ... should happen.

It doesn't really change things for you because mergerfs is properly changing credentials when performing all actions where it would matter. mhddfs doesn't do that. It runs as root and occasionally tries to mimic proper entitlements. It's happenstance that what you want works because the author of mhddfs did that out of ignorance of the correct way to handle that situation.

**Comment by pfofi** [comment]
Has anyone found a solution to this problem yet? I'm migrating from aufs and there I could hide the branch mount points within a root-only directory.

**Comment by trapexit** [comment]
Solution to what? What does confusion about permissions have to do with whiteout'ing files?

**Comment by pfofi** [comment]
Example:
```
root@test:~#: mergerfs /mnt/branches/b1:/mnt/branches/b2 /mnt/pool

root@test:~# ls -l /mnt
total 0
drwx------ 1 root root 8 Aug 27 15:34 branches
drwxr-xr-x 1 root root 0 Aug 27 15:34 pool

user@test:~$ ls -l /mnt
ls: cannot access '/mnt/pool': No such file or directory
total 0
drwx------ 1 root root 8 Aug 27 15:34 branches
d????????? ? ?    ?    ?            ? pool
```

**Comment by trapexit** [comment]
You aren't indicating what version you're using. If it is older you must use `-o allow_other`

Look at the docs for examples on how to use the software and meaning of arguments. https://github.com/trapexit/mergerfs?tab=readme-ov-file#options

**Comment by trapexit** [comment]
Please don't revive old threads. Create new ones and follow the instructions on reporting issues and asking questions.
