### ISSUE TITLE
Question: replace aging harddisk - "just copy to new drive?"

### ISSUE THREAD

**Issue by Symbiot78** [trapexit/mergerfs#408]
Hi @trapexit 

I have 2 disks I want to replace.. they're getting old and SMART isn't too happy anymore..

Is it possible to just do the following:

1. disable snapraid (if running with mergerFS)
2. remove the 2 drives from MergerFS pool
3. add 1 larger drive to mergerFS that can hold data from the 2 old disks
4. copy paste content of the 2 old drives to the new larger drive
5. enable snapraid & do full sync

Or is there a better way?

**Comment by trapexit** [comment]
You don't need to remove the drives from mergerfs. mergerfs is fully runtime configurable. Just plug in the new drive, add it to mergerfs, `sudo rsync -avPHAX /drive1/ /drive2/`, then either move the drive in snapraid to the new drive or add it and do a sync then empty the old one and sync again then remove it.

https://github.com/trapexit/backup-and-recovery-howtos/blob/master/docs/recovery_(mergerfs,snapraid).md
https://github.com/trapexit/mergerfs#runtime
https://github.com/trapexit/mergerfs-tools#mergerfsctl
