### ISSUE TITLE
[Request] Add option to set "split level" similar to unRAID

### ISSUE THREAD

**Issue by chrisallen** [trapexit/mergerfs#410]
see here: https://lime-technology.com/wiki/index.php/Un-Official_UnRAID_Manual#Split_level

The idea being that the top level folders on the mergerfs mount could have their own "split level" similar to the "users shares" in unRAID

each of the top level folders are Level 1, then the subfolders of those would be level 2 and so on.

This would allow a user to have a `TV` top level folder and set `split level 2` on it, this means that we would split so that each TV show folder would live on only one disk.

Similarly, if I set `split level 3` It would split TV shows at the season level, ensuring that all episodes for a season reside on the same disk (preventing spin up of other disks when binge watching)

**Comment by trapexit** [comment]
It wouldn't prevent spin up if anything at all requires data from the other drives. Which is common. Most policies query live data any the OS doesn't cache it for long. 

A similar behavior can be gotten by using path preserving policies and happens naturally if the using that policy when a directory is created.

**Comment by chrisallen** [comment]
So if I was to use a pool of disks and the `EPMFS` policy, then in the below example, if `lost` was only on `drive1` does that mean that if I was accessing `/mergerfs_mount/tv/lost/s01e01.mkv` It would only spin up `disk1` ?

```
disk1
-tv
   - lost
disk2
-tv
   - prison break
```

**Comment by trapexit** [comment]
mergerfs doesn't make any guarantees about spinup. It queries data about the filesystems as it needs it from the OS and if the OS decides to spin them up mergerfs has no control over that. epmfs is usually only a create policy which isn't going to be run unless it's creating something. getattr and open policies may limit spinup if they are `ff` and literally nothing else is running to request information but again... no promises.

**Comment by chrisallen** [comment]
going to close this since I think `epmfs` covers 99% of this use case.
