### ISSUE TITLE
hardlinking not working (but should?)

### ISSUE THREAD

**Issue by fucheeno** [trapexit/mergerfs#411]
Hello,

First off I love your software and I have been using at home for a year now with snapraid without a single issue. Just perfect and indispensable so thanks for that!

Now I am trying to use mergerfs on a remote server with just two mounts, one normal rw mount (home/monkey/local) and one rclone ro mount (/home/monkey/rclone), in that order to mount point /home/monkey/merged. I am using the options "defaults,allow_other,use_ino" along with every single combination it seems of create and action modes.

Every attempt to hardlink a file from another directory on home (/home/monkey/incoming) results in the dreaded error "invalid cross-device link" even though the link being created can only be created on the rw mount which is technically on the same disk.

In the reading I have done this should work with mergerfs in some permutation, unlike other tools like unionfs. Can you please help me figure out what I might be missing and some beer will be gladly on the way? :)

Thank you!

**Comment by trapexit** [comment]
What's the create policy? Have you read the details on [how rename and link work?](https://github.com/trapexit/mergerfs#rename--link)

**Comment by fucheeno** [comment]
I have tried every create policy by now I think. 

The mount for the rw is just a typical rw mount for /home and the ro directory shows as the following when doing "cat /proc/mounts"

/home/monkey/rclone fuse.rclone ro,nosuid,nodev,relatime,user_id=1000,group_id=1000,allow_other 0 0

**Comment by trapexit** [comment]
That all appears fine. Hard links certainly work given the conditions in the docs. I'd need more specific details.

Worse case if you strace'd mergerfs just before attempting a link.

`strace -p $(pgrep mergerfs) -f -o /tmp/mergerfs.trace`

And then attach it here.

**Comment by fucheeno** [comment]
[mergerfs.txt](https://github.com/trapexit/mergerfs/files/1032743/mergerfs.txt)

**Comment by trapexit** [comment]
`link` isn't actually being called which only should occur (with EXDEV being the error) if the drive the file being linked does not equal the drive which create would result in picking. But that is only if it's a path preserving policy. What is your create policy when you ran this?

**Comment by fucheeno** [comment]
category.create=ff

**Comment by trapexit** [comment]
Can you show me exactly the link command being done? It's hard to understand what you wrote originally regarding what the link is. 

No matter what you can not link across devices. Even if you are trying to link from a drive being used by mergerfs into a mergerfs mount. The OS still sees them as different.

**Comment by fucheeno** [comment]
ln /home/monkey/incoming/Brief.Encounter.1945.NTSC.DVD.x264.mkv-Tree/Brief.Encounter.1945.NTSC.DVD.x264-Tree.mkv /home/monkey/merged/media/film/Brief Encounter (1945)/Brief.Encounter.1945.NTSC.DVD.x264-Tree.mkv

**Comment by trapexit** [comment]
Yeah... you can't do that. They are different devices. You should use a symlink.

**Comment by fucheeno** [comment]
yeah, that is what I though mergerfs did somehow as opposed to other union tools. :(

Unfortunately radarr and sonarr do not support symlinking. :(

I do appreciate your help and am all ears if you have any other ideas. :)

**Comment by trapexit** [comment]
Seems odd they don't follow symlinks.

There isn't much I can do. I suppose I could do something where a symlink is interpreted as a hardlink instead or something but they'd have to be created outside mergerfs because the OS itself will error if you try to link across devices.

Why not point your tools to the merged mount?

**Comment by fucheeno** [comment]
sonnarr and radarr are pointed to the merged mount. the new content gets downloaded elsewhere and then copied to the merged mount because I can't use hard links, causing 2x the space needed and unnecessary disk i/o which impacts the box. :(

**Comment by trapexit** [comment]
Why do you download elsewhere? Hardlinks work fine within mergerfs. Just download into the merged mount. You can merge together whatever paths you want if it's a layout issue. mergerfs handles it just fine.

**Comment by fucheeno** [comment]
OH, I see what you are saying. I will try that later today and let you know. :)

**Comment by trapexit** [comment]
?

**Comment by matijaerceg** [comment]
omg this makes so much more sense, thank you trapexit

**Comment by voarsh2** [comment]
I'm having issues with this.

My path:
/mnt/storage/downloads/complete/
/mnt/storage/downloads/tvshows

It seems Sonarr isn't creating hardlinks. And when I try and manually create a hardlink:
```
ln -v /mnt/storage/downloads/complete/The.Mandalorian.S03.WEB-DL.1080p.LF_\[rutor\]/* /mnt/storage/downloads/tvshows/The\ Mandalorian/Season\ 3
```
I get: Invalid cross-device link

Are you saying I should combine /downloads and /tvshows to be together? O.o

**Comment by trapexit** [comment]
Please create a new ticket or discussion with the details of your setup.

**Comment by voarsh2** [comment]
Fine, as you wish. Thought I'd spare the "spam" and be accused of not searching online first.....
