### ISSUE TITLE
Unable to run any mergerfs command "GLIBCXX_3.4.21 not defined"

### ISSUE THREAD

**Issue by penance316** [trapexit/mergerfs#414]
I have just installed and tried to get mergerfs setup on my machine, however, i am receiving the following error:

mergerfs: relocation error: mergerfs: symbol _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference.

I assume it's not a problem with mergerfs but was wondering if anyone has had this issue before and knows how to solve it.

Much appreciated

**Comment by trapexit** [comment]
How'd you install it? What OS?

**Comment by penance316** [comment]
Apologies for not including the details.
OS: Linux Mint 17.3 Rosa

I installed with wget and dpkg.
wget https://github.com/trapexit/mergerfs/releases/download/2.21.0/mergerfs_2.21.0.ubuntu-xenial_amd64.deb
dpkg -i mergerfs_2.21.0.ubuntu-xenial_amd64.deb

thanks

**Comment by trapexit** [comment]
You used the wrong package. Rosa is based on Ubuntu 14.04 Trusty.

**Comment by penance316** [comment]
Ah that makes sense. I have managed to get it built from source now and it is running.

Thanks for the quick reply :)
