### ISSUE TITLE
Can't Compile Ubuntu 17.04

### ISSUE THREAD

**Issue by TomAshley303** [trapexit/mergerfs#419]
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:81: recipe for target 'mergerfs' failed
make: *** [mergerfs] Error 1

and...
Makefile:192: recipe for target 'install-build-pkgs' failed
make: *** [install-build-pkgs] Error 100

**Comment by trapexit** [comment]
I just followed the instructions in the docs in a Docker container of 17.04 and it works fine. Can you provide more information about what you did?
