### ISSUE TITLE
Is debian stretch supported?

### ISSUE THREAD

**Issue by jacobwgillespie** [trapexit/mergerfs#425]
Since stretch is now released, do you know of any potential incompatibilities?  I know there's not yet a `.deb` for stretch, but is there anything else I should watch out for when upgrading?

**Comment by trapexit** [comment]
No issues that I'm aware of. I will add it to my build process and upload a deb for the most recent release.

**Comment by jacobwgillespie** [comment]
Yep, appears to be working without any issues - thanks!

**Comment by MrRooks** [comment]
Should we just use the Jessie builds on Stretch? I don't see the Stretch deb files listed in releases.

**Comment by trapexit** [comment]
Yeah. For now. I don't yet have a Stretch build env.
