### ISSUE TITLE
bad block bitmap checksum

### ISSUE THREAD

**Issue by deepfriedheroin** [trapexit/mergerfs#426]
I just started getting an error when writing to my pool from SABNZBD. The error only happens for single files over 3 gigs, or for smaller files, written one after another. I've also had problems writing to my snapraid.content file - only for the drive in the error message, below.

I've been able to mv a few large directories from another disk in the pool to the affected disk, with no error. 

Maybe something to do with renaming? 

Because, I think, snapraid does this: `snapraid.content.temp -> snapraid.content` and SABNZBD renames files as: `_UNPACK.folder.name -> folder.name -> actual.file.location`. 

The error pops up at times when the file gets stuck at `_UNPACK.folder.name`.

Here's what I'm seeing:

```
[ 9453.578188 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm kworker/u10:2: bg: 54414 bad block bitmap checksum
[ 9465.435816 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54424 bad block bitmap checksum
[ 9465.874724 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54431 bad block bitmap checksum
[ 9484.045777 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54438 bad block bitmap checksum
[ 9484.543959 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54439 bad block bitmap checksum
[ 9484.699544 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54440 bad block bitmap checksum
[ 9484.727156 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54441 bad block bitmap checksum
[ 9484.754140 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54442 bad block bitmap checksum
[ 9484.783454 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54443 bad block bitmap checksum
[ 9484.821063 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54444 bad block bitmap checksum
[ 9484.860592 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54445 bad block bitmap checksum
[ 9484.863995 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54446 bad block bitmap checksum[ 9453.578188 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384 comm mergerfs: bg: 54424 bad block bitmap checksum
[ 9484.867101 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54447 bad block bitmap checksum
[ 9535.952144 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54485 bad block bitmap checksum
[ 9536.152345 ] EXT4-fs (sdd1): Delayed block allocation failed for inode 61524 at logical offset 530432 with max blocks 2048 with error 74 
[ 9536.153665 ] EXT4-fs error (device sdd1): This should not happen!! Data will be lost
[ 9536.153665 ] 
[ 9541.271774 ] EXT4-fs error (device sdd1): ext4_validate_block_bitmap:384: comm mergerfs: bg: 54491 bad block bitmap checksum
[ 9542.532669 ] EXT4-fs (sdd1): Delayed block allocation failed for inode 61524 at logical offset 688128 with max blocks 2048 with error 74 
[ 9542.534145 ] EXT4-fs error (device sdd1): This should not happen!! Data will be lost
[ 9542.534145 ] 
```

I ran BBF at the OS level and found no bad blocks. Short SMART test also came back clean. 

```
root@nas:~/bbf# ./bbf scan /dev/sdd1
Imported bad blocks from /root/badblocks.VK0JBRYY
Scanning: 0 - 15628048384
Current: 15628048384 (100.00%); bps: 281821.20; eta: 00:00:00; bad: 0
Bad blocks written to /root/badblocks.VK0JBRYY
```

I’ve only recently upgraded from mergerfs 2.20.0 (no errors on this version)

Here’s what I’m running now:

mergerfs 2.23.0

`defaults,allow_other,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=20G,fsname=mergerfsPool`

Ubuntu 16.04.2 LTS in a Proxmox VM

I'm going to change to `category.create=epmfs`, to see if I get this error on an empty disk. Other than that, I'm not sure what to. 

Any assistance would be appreciated.

**Comment by trapexit** [comment]
This isn't a mergerfs issue. As the messages mention it looks to be a filesystem (or possibly drive) problem.

Have you run fsck.ext4 against it?

(btw... someone uses bbf? :D)

**Comment by deepfriedheroin** [comment]
> (btw... someone uses bbf? :D)


Ha! I thought you'd get a kick out of that. 

I haven't run fsck.ext4, yet. 

Not your problem, but what's the proper way to run it on a single mergerfs pooled disk?

**Comment by trapexit** [comment]
I wrote bbf because I never liked badblocks but haven't given it the attention it needs to gain more wide spread use. I actually was thinking of trying to improve it's performance recently.

If you don't want to shut down your system I'd first stop everything which might be using the drive in question and then umount it. mergerfs doesn't care if it disappears. Then fsck it and mount it when you're finished. Don't need to do anything with mergerfs specifically. You could remove it from mergerfs via the runtime config but I tend not to bother.

**Comment by deepfriedheroin** [comment]
you should. it's another good tool in my toolbox. 

ok to close, since it's not mergerfs related. thanks!
