### ISSUE TITLE
Write Speed slow on local/remote merged folder

### ISSUE THREAD

**Issue by mazeprince** [trapexit/mergerfs#427]
Hi there,
i really like mergerfs and use it for quite some time now. 
I have a little more complex setup:
1.:
_diskA diskB diskC_ are merged together to _local_ 
with: mergerfs -o defaults,allow_other,use_ino,func.getattr=newest,category.create=ff,minfreespace=10G _diskA:diskB:diskC local_
2.:
_remote_ and _local_ are merged to _all_
with : mergerfs -o defaults,allow_other,direct_io,use_ino,func.getattr=newest,category.create=ff _local:remote all_
_remote_ is an rclone mount (https://github.com/ncw/rclone), it is **read only**.

It is working beautiful, but i have some write speed issues which i dont understand. I can write files directly on _all_ and it respects the order (category.create=ff) and _remote_ is readonly anyway. But:
I can write files with full speed on _local_ (round about 80 MB/s) but to _all_ just with around 20-30 MB/s. Of course the _remote_ is quite slow in reading and file listing, but why is the writing affected with ff policy? mergerfs doesnt need to check _remote_ for existing files while writing, does it? Am i missing something?

As mergerfs doesnt have debug logs (and i think it wouldnt throw errors anyway) i dont know where to start. I thought about cpu limitation, but i dont get why writing to _local_ works full speed then. I thougt it is maybe because of the double merge, but i tested it with merging _local_ and a new  _local2_ to _all_ and it writing full speed. So the _remote_ mount is definitly the reason, but, as i said, using ff policy i dont understand why the slow remote mount affects the writing....

I can live with the slow writing for now (and i can write fast to _local_ if i need to) but i dont understand it. Any ideas/suggestions are appreciated!

edit: It is an debian stable/stretch with 
mergerfs version: 2.23.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
and an J1900 CPU

**Comment by trapexit** [comment]
You've got mergerfs on top of mergerfs? If so... you shouldn't. That adds another level of indirection which is going to add a lot of latency to all requests.

As for the policy affecting writes.... it shouldn't. The policy only applies to the open'ing of the file. Writes and reads don't have any extra overhead outside what is introduced by mergerfs being a proxy. That said... when policies are run some are more expensive than others and any that look across all the drives (which pretty much all but ff do) then the read only drives could affect certain behaviors because mergerfs still needs to scan them and see that they are readonly. There are ways to optimize that at the expense of flexibility but we'd need to confirm that's the actual issue.

**Comment by mazeprince** [comment]
Yes, i do. I thought it is probably not the best idea, but i like that i have a direct access to the pooled drives without remote and an access to all files.
That's why i did the test with an double merge (but without rclone remote) which gives me full speed. So i thought the double merge isn't the problem.
But i just did another test:
If i do
mergerfs -o defaults,allow_other,use_ino,func.getattr=newest,category.create=ff,minfreespace=10G _diskA:diskB:diskC:remote all_
i get full speed. 
And i got an idea for my demand for _local_ and _all_
mergerfs -o defaults,allow_other,use_ino,func.getattr=newest,category.create=ff,minfreespace=10G _diskA:diskB:diskC local_

and 
mergerfs -o defaults,allow_other,use_ino,func.getattr=newest,category.create=ff,minfreespace=10G _diskA:diskB:diskC:remote all_

Nice!
I still don't really get why the double merge just creates problems when i include the remote mount and NOT when i do a double merge without the remote. Any thoughts on that?

Thank you anyway!

**Comment by trapexit** [comment]
What do you mean "creates problems"? Are you saying that having mergerfs on top of mergerfs when there's no remote at the lowest mount has zero performance impact but with it it does have an impact? A quick test for me shows a significant decrease in performance under what's probably the best case scenario when using mergerfs -> mergerfs -> raw drive.

And again: the performance depends on the usage pattern. If you don't tell me exactly what you're usage pattern is I can't comment. Raw streams of read and writes should not be impacted but there are situations where it could because the remote system has to be queried.

**Comment by trapexit** [comment]
I just added a rclone read-only mount to my pool and I see no change in performance when using dd to write files. There's a performance hit when having an extra layer of indirection but nothing changes when having rclone mount included.

dd if=/dev/zero of=foo bs=1M count=512 conv=fdatasync

**Comment by mazeprince** [comment]
yes, thats whats happening for me:
without remote: mergerfs --> mergerfs --> raw

dd if=/dev/zero of=foo bs=1M count=512 conv=fdatasync
512+0 Datensätze ein
512+0 Datensätze aus
536870912 Bytes (537 MB, 512 MiB) kopiert, 3,655 s, 147 MB/s

with remote: mergerfs --> mergerfs --> raw

dd if=/dev/zero of=foo bs=1M count=512 conv=fdatasync
512+0 Datensätze ein
512+0 Datensätze aus
536870912 Bytes (537 MB, 512 MiB) kopiert, 24,1944 s, 22,2 MB/s

So the mergerfs on top of mergerfs just impact perfomance if you include a remote drive. It does not if you don't include a remote drive. 

Anyway, as i wrote i found the above solution good enough, it just isn't clear to me why a double mount (mergerfs on top of mergerfs) just has perfomance decrease when a remote is included.

**Comment by trapexit** [comment]
I am completely unable to replicate your experience. Can you please show me exactly what your setup is?

Regardless, having multiple levels of indirection is always going to cause increased costs. Given you aren't using any difference policies I don't see the point of even trying to do so.

**Comment by mazeprince** [comment]
Hi,
so wrote a short bash script to get a more standardized "test" and run it at my server and on my workstation. Looks like you are right, now everytime i do a double merge perfomance decreased, regardless of an underlying remote. I don't know what i did wrong in my previous tests, but at least it is consistent with your results now.

Thank you very much for your help (DONT double merge :-) ) and your responses!


I attach the code, but it is useless now, because of my "new" results.

```#!/bin/bash
#Define the variables
DISKA='/media/nas/diska'
DISKB='/media/nas/diskb'
DISKC='/media/nas/diskc'
DISKD='/media/nas/diskd'
REMOTE='/home/nas/gdrive'
LOCAL='/home/nas/local'
ALL='/home/nas/all'
#Merge all three disks
echo $DISKA $DISKB $DISKC $DISKD $REMOTE $LOCAL $ALL
echo 'Merge all local disks to a local point'
mergerfs -o defaults,allow_other,use_ino,func.getattr=newest,category.create=ff,minfreespace=10G $DISKA:$DISKB:$DISKC $LOCAL
echo 'Perfom write speed test'
dd if=/dev/zero of=$LOCAL/foo bs=1M count=512 conv=fdatasync
sleep 3
rm $LOCAL/foo
sleep 1
echo 'Umount merged folder'
fusermount -u $LOCAL
echo 'Merge all local disks and an rclone remote'
mergerfs -o defaults,allow_other,direct_io,use_ino,func.getattr=newest,category.create=ff $DISKA:$DISKB:$DISKC:$REMOTE $ALL
sleep 2
ls $ALL
echo 'Perfom write speed test'
dd if=/dev/zero of=$ALL/foo bs=1M count=512 conv=fdatasync
sleep 3
rm $ALL/foo
sleep 1
echo 'Umount merged folder'
fusermount -u $ALL
sleep 1
echo 'Merge all local disks and then merge another disk with this merged folder'
mergerfs -o defaults,allow_other,use_ino,func.getattr=newest,category.create=ff,minfreespace=10G $DISKA:$DISKB:$DISKC $LOCAL
sleep 1
mergerfs -o defaults,allow_other,direct_io,use_ino,func.getattr=newest,category.create=ff $LOCAL:$DISKD $ALL
sleep 2
ls $ALL
echo 'Perfom write speed test'
dd if=/dev/zero of=$ALL/foo bs=1M count=512 conv=fdatasync
sleep 3
rm $ALL/foo
sleep 1
echo 'Umount all merged folders'
fusermount -u $ALL
sleep 1
fusermount -u $LOCAL
echo 'Done'

echo 'Merge all local disks first and then merge the remote with this merged folder'
sleep 2
mergerfs -o defaults,allow_other,use_ino,func.getattr=newest,category.create=ff,minfreespace=10G $DISKA:$DISKB:$DISKC $LOCAL
sleep 1
mergerfs -o defaults,allow_other,direct_io,use_ino,func.getattr=newest,category.create=ff $LOCAL:$REMOTE $ALL
sleep 2
ls $ALL
echo 'Perfom write speed test'
dd if=/dev/zero of=$ALL/foo bs=1M count=512 conv=fdatasync
sleep 3
rm $ALL/foo
sleep 1
echo 'Umount all merged folders'
fusermount -u $ALL
sleep 1
fusermount -u $LOCAL
echo 'Done'
```
