### ISSUE TITLE
FTBFS and embedded library

### ISSUE THREAD

**Issue by rickysarraf** [trapexit/mergerfs#431]
The newer versions of mergerfs, after 2.21.0, fail to build. Also, why is libfuse being embedded with mergerfs ? Is it just temporary until the distributions catch up on libfuse3  ? Debian currently have libfuse2 version 2.9.7. But I also noticed that version 2.22.0 carried the older version of libfuse. Can you please clarify why libfuse is being included in the source, instead of a dependency ?

```
dh clean --parallel
   dh_auto_clean -O--parallel
	make -j4 distclean
make[1]: Entering directory '/tmp/mergerfs'
Makefile:70: "xattr not available: disabling"
/bin/rm -rf rpmbuild
/bin/rm -f src/version.hpp
/bin/rm -rf obj
/bin/rm -f "mergerfs" mount.mergerfs
/usr/bin/find . -name "*~" -delete
cd libfuse && make clean
make[2]: Entering directory '/tmp/mergerfs/libfuse'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/bile/dev/mergerfs/libfuse/missing aclocal-1.15 -I m4
/bin/bash: /home/bile/dev/mergerfs/libfuse/missing: No such file or directory
Makefile:408: recipe for target 'aclocal.m4' failed
make[2]: *** [aclocal.m4] Error 127
make[2]: Leaving directory '/tmp/mergerfs/libfuse'
Makefile:108: recipe for target 'clean' failed
make[1]: *** [clean] Error 2
make[1]: Leaving directory '/tmp/mergerfs'
dh_auto_clean: make -j4 distclean returned exit code 2
debian/rules:13: recipe for target 'clean' failed
make: *** [clean] Error 2
gbp:error: 'fakeroot debian/rules clean' failed: it exited with 2
16:07 ♒♒♒    ☹  => 1  
```

**Comment by trapexit** [comment]
Fails to build on what platform? As you can see in the releases I build on many versions of Debian and Ubuntu and Redhat just fine. I know people build it successfully on other platforms as well. Did you follow the [build instructions](https://github.com/trapexit/mergerfs#building)?

It embeds libfuse because:
1) I support many old platforms which use old and buggy versions of libfuse. Embedding it keeps many of my users who don't know and don't care to know how to update their systems from having to learn to build libfuse themselves.
2) libfuse is lacking in certain features I want. Given libfuse v2 is no longer maintained and libfuse3 either didn't or doesn't have the features either and mergerfs hasn't been ported to v3... embedding it was easier than forking it and expecting people to install my version.

**Comment by rickysarraf** [comment]
it is the clean target failing. And from the error it is because of stale paths.

Regarding embedding libfuse, so you are carrying your own version of libfuse, which you will maintain yourself. I do not see this as an optimal path for Debian, or other distributions otherwise.

https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
https://fedoraproject.org/wiki/Packaging:Guidelines#Bundling_and_Duplication_of_system_libraries
https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles

**Comment by trapexit** [comment]
The clean target works just fine on my Ubuntu 16.04 system and all the platforms I build for. Can you answer my original questions so I can debug? What platform? Were the correct build packages installed? What version?

As for distros... If that means they won't carry mergerfs then so be it. I'm not going to spend countless hours debugging and walking people through upgrading old, buggy releases of code I have no control over. Especially given the sensitivity of the software (handling people's data). I'm also not going to go through the effort of getting them all to carry a fork or to try to take ownership of the original. Ideally I'd like to get completely away from libfuse but that's more effort than its worth at the moment.

**Comment by rickysarraf** [comment]
This build failure is seen on Debian Sid on x86.

Regarding the latter, I think for Debian, we'll stick with 2.21.0 and see how things progress.

**Comment by trapexit** [comment]
How? How are you building? I don't maintain the deb in the main repo so if that's what your testing then I'm the wrong person to talk to. My builds work just fine.

Alright. Given you've not given me an alternative solution to my problem I'll do what makes my and my users lives easier.

**Comment by rickysarraf** [comment]
It is your clean target which has hard coded path. That is what I mentioned earlier.
```
cd libfuse && make clean
make[2]: Entering directory '/tmp/mergerfs/libfuse'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/bile/dev/mergerfs/libfuse/missing aclocal-1.15 -I m4
/bin/bash: /home/bile/dev/mergerfs/libfuse/missing: No such file or directory
Makefile:408: recipe for target 'aclocal.m4' failed
```

Regarding the embedded library, I understand your pain. It is just that there are many more utilities using libfuse, without any problems afaik. Hence, shipping mergerfs with embedded libraries in Debian as an excepiton, is something I'll just hold off for some time.

**Comment by rickysarraf** [comment]
You can check about mergerfs in Debian.
https://tracker.debian.org/pkg/mergerfs
https://anonscm.debian.org/gitweb/?p=collab-maint/mergerfs.git
and full build logs here
https://buildd.debian.org/status/package.php?p=mergerfs

**Comment by trapexit** [comment]
Where are the exact logs? I don't see them for 2.23.0. I build in completely clean debian sid docker images and have no issues. With the tarball or git repo as I show above. It seems I don't ship a completely clean tarball but it works none-the-less.

"without any problems afaik"

That's not true. There are well known bugs in older version which cause it to crash under load among other issues (as noted in my docs.) They aren't always noticed with other filesystems because they aren't used 24/7 and transferring massive amounts of data like mine would be. Also, as I said I've needed to modify the library because of lacking features & bad implementation.

I assure you I wouldn't have embedded it if things worked. I support Debian Wheezy, Ubuntu Precise, and other distros with old and buggy versions. OMV for example uses mergerfs and due to being based on Wheezy users regularly had issues because of libfuse.

I'm happy to help fix the build but I need you to provide me more than the above. None of the platforms I build for (in clean environments) have issues nor do the misc other platforms that have their own packages.

**Comment by rickysarraf** [comment]
Here's the log. There's no log in the build servers because 2.23.0 did not build locally for me, to upload to the archive.

```
rrs@priyasi:/tmp/mergerfs (master)$ gbp buildpackage 
dh clean --parallel
   dh_auto_clean -O--parallel
	make -j4 distclean
make[1]: Entering directory '/tmp/mergerfs'
Makefile:70: "xattr not available: disabling"
/bin/rm -rf rpmbuild
/bin/rm -f src/version.hpp
/bin/rm -rf obj
/bin/rm -f "mergerfs" mount.mergerfs
/usr/bin/find . -name "*~" -delete
cd libfuse && make clean
make[2]: Entering directory '/tmp/mergerfs/libfuse'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/bile/dev/mergerfs/libfuse/missing aclocal-1.15 -I m4
/bin/bash: /home/bile/dev/mergerfs/libfuse/missing: No such file or directory
Makefile:408: recipe for target 'aclocal.m4' failed
make[2]: *** [aclocal.m4] Error 127
make[2]: Leaving directory '/tmp/mergerfs/libfuse'
Makefile:108: recipe for target 'clean' failed
make[1]: *** [clean] Error 2
make[1]: Leaving directory '/tmp/mergerfs'
dh_auto_clean: make -j4 distclean returned exit code 2
debian/rules:13: recipe for target 'clean' failed
make: *** [clean] Error 2
gbp:error: 'fakeroot debian/rules clean' failed: it exited with 2
20:53 ♒♒♒    ☹  => 1  
```

And here's the explicit reason
```
rrs@priyasi:/tmp/mergerfs/libfuse (master)$ make clean
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/bile/dev/mergerfs/libfuse/missing aclocal-1.15 -I m4
/bin/bash: /home/bile/dev/mergerfs/libfuse/missing: No such file or directory
Makefile:408: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
20:55 ♒♒♒    ☹  => 2  
```

I will check the Debian Policy to see if I can add this exception for the embedded library. Meanwhile, it'd be nice to have this build environment cleaned up and fixed. The stale paths are from the libfuse autoconf/auotmak logs.

**Comment by rickysarraf** [comment]
Just FYI. I raised this topic on the Debian Developers mailing list. And got comments inline with what I've mentioned. https://lists.debian.org/debian-devel/2017/08/msg00163.html

There, the upstream for libfuse too chimed in. It was told that they aren't aware of any such known issues with libfuse.

**Comment by trapexit** [comment]
I've replied.

**Comment by ahippo** [comment]
@trapexit, I'm hitting the same roadblock (regarding embedded libfuse) for inclusion of mergerfs into Gentoo main tree.
What I'm hearing is, it should be _possible_ to build against (unpatched) system libfuse.
Will there be any issues if built against vanilla fuse-2.9.7?
I understand that `-o threads=` option will be gone, and parallel access performance will be degraded,
but will there by any correctness or other issues?

I'm thinking of simply adding `EMBEDDED_FUSE` variable to the Makefile, which would default to "yes".
If it's set, then build and use embedded libfuse.
If not, then use `pkg-config --libs 'fuse >= 2.9.7'` during final link.
Distros will then be able to say `make EMBEDDED_FUSE=''` and make sure to install proper dependencies.

As far as I can tell, ntfs3g does something similar: with embedded libfuse, there are more features; but system libfuse makes distros happy.

If it makes sense to you, I can quickly cook up required Makefile changes.

**Comment by trapexit** [comment]
`threads` code would need to be managed appropriately and documentation updated to indicate the possible incompatibility. I'm fine with such a change. To support OSX at some point similar changes would need to be made.

**Comment by ahippo** [comment]
> `threads` code would need to be managed appropriately

What do you mean?

> and documentation updated to indicate the possible incompatibility.

Oh yeah, good point!
I'll propose changes to the README file too.

> I'm fine with such a change. To support OSX at some point similar changes would need to be made.

Great!
Let me see if I can get something working today.

**Comment by ahippo** [comment]
>> `threads` code would need to be managed appropriately
> 
> What do you mean?

As far as I can see, `threads` changes are mostly isolated to `libfuse/`.
The only place outside of `libfuse/` to mention `threads` is `src/option_parser.cpp`, where the option is mentioned in help text.
So, that should be fairly straightforward.

**Comment by ahippo** [comment]
@rickysarraf, since #495 is merged, you no longer need to run `make clean` in `libfuse/` subdirectory, but can simply do `make INTERNAL_FUSE=0 && make INTERNAL_FUSE=0 install`.
So, you may want to reconsider inclusion of mergerfs into Debian/Ubuntu repo.
