### ISSUE TITLE
Files are corrupted when copied through mergerfs

### ISSUE THREAD

**Issue by midgetspy** [trapexit/mergerfs#432]
/mnt/snapraid/pool is my mergerfs filesystem and it contains a disk /mnt/snapraid/2tb/disk1. When copying straight to the disk my checksums always match, when copying to the mergerfs filesystem the checksums are different each time. File size is always consistent. See below for some tests:

1. Checksum my test file, do it a couple times to be sure it's consistent
```
[midgetspy@MidgetStorage ToSort]$ ls -l My.Test.File
-rwxrw-rw- 1 nobody nobody 15470712685 Jul 10 00:13 My.Test.File
[midgetspy@MidgetStorage ToSort]$ sha1sum My.Test.File
42cdd666935211340e1995f10a8d90fa9cd9c1b8  My.Test.File
[midgetspy@MidgetStorage ToSort]$ sha1sum My.Test.File
42cdd666935211340e1995f10a8d90fa9cd9c1b8  My.Test.File
[midgetspy@MidgetStorage ToSort]$ sha1sum My.Test.File
42cdd666935211340e1995f10a8d90fa9cd9c1b8  My.Test.File
```

2. Copy it through mergerfs, has a different sum
```
[midgetspy@MidgetStorage ToSort]$ cp My.Test.File /mnt/snapraid/pool/
[midgetspy@MidgetStorage ToSort]$ sha1sum /mnt/snapraid/pool/My.Test.File
daee23d6049c5267e616ae11efa9f359244b03e4  /mnt/snapraid/pool/My.Test.File
[midgetspy@MidgetStorage ToSort]$ sha1sum /mnt/snapraid/2tb/disk1/My.Test.File
daee23d6049c5267e616ae11efa9f359244b03e4  /mnt/snapraid/2tb/disk1/My.Test.File
```

3. Try a second time, the checksum is different yet again
```
[midgetspy@MidgetStorage ToSort]$ cp My.Test.File /mnt/snapraid/pool/My.Test.File.2
[midgetspy@MidgetStorage ToSort]$ sha1sum /mnt/snapraid/pool/My.Test.File.2
c5cdaa5210b1bef2250025649755094c4c274465  /mnt/snapraid/pool/My.Test.File.2
[midgetspy@MidgetStorage ToSort]$ sha1sum /mnt/snapraid/2tb/disk1/My.Test.File.2
c5cdaa5210b1bef2250025649755094c4c274465  /mnt/snapraid/2tb/disk1/My.Test.File.2
```

4. Copy it to that disk directly, checksum matches
```
[midgetspy@MidgetStorage ToSort]$ ls /mnt/snapraid/2tb/disk1
My.Test.File  My.Test.File.2
[midgetspy@MidgetStorage ToSort]$ cp My.Test.File /mnt/snapraid/2tb/disk1/My.Test.File.3
[midgetspy@MidgetStorage ToSort]$ sha1sum /mnt/snapraid/2tb/disk1/My.Test.File.3
42cdd666935211340e1995f10a8d90fa9cd9c1b8  /mnt/snapraid/2tb/disk1/My.Test.File.3
[midgetspy@MidgetStorage ToSort]$ sha1sum /mnt/snapraid/pool/My.Test.File.3
42cdd666935211340e1995f10a8d90fa9cd9c1b8  /mnt/snapraid/pool/My.Test.File.3
```

5. Check the resulting file sizes, they're all identical (but all have different hashes)
```
[midgetspy@MidgetStorage ToSort]$ ls -l /mnt/snapraid/pool/
total 66282036
-rwxrw-r--   1 midgetspy midgetspy 15470712685 Aug  4 11:29 My.Test.File
-rwxrw-r--   1 midgetspy midgetspy 15470712685 Aug  4 11:33 My.Test.File.2
-rwxrw-r--   1 midgetspy midgetspy 15470712685 Aug  4 11:41 My.Test.File.3
```

I tried reproducing with a 10GB file of all 0's but that case succeeded.

Command used to make my pool: `sudo mergerfs -o atomic_o_trunc,auto_cache,big_writes,default_permissions,allow_other,use_ino,moveonenospc=true,fsname=pool,category.create=eplfs /mnt/snapraid/4tb/disk\*:/mnt/snapraid/1tb/disk\*:/mnt/snapraid/2tb/disk1 /mnt/snapraid/pool`

This is on CentOS, the machine has ECC RAM.

```[midgetspy@MidgetStorage ToSort]$ mergerfs --version
mergerfs version:
FUSE library version: 2.8.3
using FUSE kernel interface version 7.12
```

**Comment by trapexit** [comment]
What version of mergerfs?

**Comment by midgetspy** [comment]
mergerfs version is included in the original post.

OS is CentOS on an ancient kernel:

```[midgetspy@MidgetStorage ToSort]$ uname -a
Linux MidgetStorage 2.6.32-358.11.1.el6.SiL3286.x86_64 #1 SMP Thu Jun 27 06:54:42 MDT 2013 x86_64 x86_64 x86_64 GNU/Linux
```

I was thinking about trying to reproduce on a fresh OS install but I need to pick up a spare drive before I try that. If you want to share your script I can try it here as well and see what my results are?

**Comment by trapexit** [comment]
It's not in the original post. You put "mergerfs version: " and then it's blank.

**Comment by trapexit** [comment]
There's nothing really to share. It just does what you did above in a loop. Copying the file and comparing to the original.

**Comment by midgetspy** [comment]
Hm, it shows up in the original post for me, I wonder if the rest of the post came through. A screenshot of what I see in my OP:

![image](https://user-images.githubusercontent.com/63207/28984836-0fc4c168-791d-11e7-9359-bafb5dd7487d.png)

Anyway:

```
[midgetspy@MidgetStorage ToSort]$ rpm --query centos-release
centos-release-6-4.el6.centos.10.x86_64
[midgetspy@MidgetStorage ToSort]$ mergerfs -V
mergerfs version:
FUSE library version: 2.8.3
using FUSE kernel interface version 7.12
```

**Comment by trapexit** [comment]
Your screenshot is exactly what I see.... and clearly the value is empty. How did you install mergerfs? 

Clearly it's old and using a very old version of libfuse. Please replicate with a v2.23.0 before I go debugging this.

**Comment by midgetspy** [comment]
OK I'll try reproducing on a fresh install of CentOS with the latest version of mergerfs, thanks.

**Comment by trapexit** [comment]
You don't need to try it on a new version of CentOS... just with a recent version of mergerfs. Change one thing at a time else we might not know what's broken.
