### ISSUE TITLE
minfreespace seemingly not working with epff create policy

### ISSUE THREAD

**Issue by Sunako** [trapexit/mergerfs#438]
As the title says, I have set a minfreespace of 20GB, and have moveonenospc set to on, however when writing to a disk with a bit more than 20GB of space, it will seemingly ignore the minfreespace setting and continues to write until the disk is actually out of space.

Here is a df where you can see how mergerfs has written to sdb until it is truly full, even ignoring the base 4GB minfreespace setting, let alone my 20GB one:
```
/dev/sdb2       1.8T  1.8T   44M 100% /mnt/disk/sdb
/dev/sdc1       917G  390G  528G  43% /mnt/disk/sdc
```
Here is my xatter for .mergerfs
```
user.mergerfs.srcmounts: /mnt/disk/sdb:/mnt/disk/sdc:/mnt/disk/sdd:/mnt/disk/sde:/mnt/disk/sdf
user.mergerfs.minfreespace: 21474836480
user.mergerfs.moveonenospc: true
user.mergerfs.dropcacheonclose: false
user.mergerfs.symlinkify: false
user.mergerfs.symlinkify_timeout: 3600
user.mergerfs.nullrw: false
user.mergerfs.ignorepponrename: false
user.mergerfs.policies: all,epall,epff,eplfs,eplus,epmfs,eprand,erofs,ff,lfs,lus,mfs,newest,rand
user.mergerfs.version: 2.23.0
user.mergerfs.pid: 2319
user.mergerfs.category.action: all
user.mergerfs.category.create: epff
user.mergerfs.category.search: ff
user.mergerfs.func.access: ff
user.mergerfs.func.chmod: all
user.mergerfs.func.chown: all
user.mergerfs.func.create: epff
user.mergerfs.func.getattr: ff
user.mergerfs.func.getxattr: ff
user.mergerfs.func.link: all
user.mergerfs.func.listxattr: ff
user.mergerfs.func.mkdir: epff
user.mergerfs.func.mknod: epff
user.mergerfs.func.open: ff
user.mergerfs.func.readlink: ff
user.mergerfs.func.removexattr: all
user.mergerfs.func.rename: all
user.mergerfs.func.rmdir: all
user.mergerfs.func.setxattr: all
user.mergerfs.func.symlink: epff
user.mergerfs.func.truncate: all
user.mergerfs.func.unlink: all
user.mergerfs.func.utimens: all
```

Maybe I'm doing something wrong, but I don't seem to see it if I am since the policy for epff says it should respect minfreespace.

**Comment by trapexit** [comment]
Is the directory on other drives?

**Comment by Sunako** [comment]
It wasn't originally, however I did make an identical one to test on sdc and it still ignored it and went for the one on sdb.

**Comment by trapexit** [comment]
Are you sure the permissions are correct? As the docs indicate the policy falls back to `ff` if nothing matches which means if you had a drive being skipped because it didn't have enough space it'd be picked if no other drives were available. Then if the permissions were such that the user couldn't access it it also would be skipped.

**Comment by Sunako** [comment]
The permissions are correct, all owned and grouped by the user doing operations, and correct permissions. I can further attest to the permissions being correct since once sdb did fully run out of space it did in fact move on to another disk as it should without any write failure.

**Comment by trapexit** [comment]
I just checked the code[0] and the behavior on my own system and it worked as expected. Two drives, A:B, B with more space, minfreespace set above A's free space. File ended up on B. Removed file, changed minfreespace to below A's free space and file ended up on A.



[0] https://github.com/trapexit/mergerfs/blob/master/src/policy_epff.cpp#L57

**Comment by Sunako** [comment]
It is possible I've done something wrong, but I'm not sure what it would be. Is my base assumption that setting the minfreespace to 20G with epff would make it so that on 20G or less of an existing path would cause it to try to find another disk to make the path and necessary files at?

These are my fstab options if it is helpful:
```
/mnt/disk/sd[b-f] /mnt/storage fuse.mergerfs direct_io,defaults,allow_other,use_ino,minfreespace=20G,category.create=epff,moveonenospc=true,fsname=mergerfs 0 0
```

**Comment by trapexit** [comment]
Yes, that's what will happen. In the order provided, pick the first drive which has that relative path which has >= minfreespace and that user can reach.

This is easy to check.

```
$ xattr -w user.mergerfs.func.mkdir all /mnt/storage/.mergerfs
$ mkdir /mnt/storage/foo
$ xattr -p user.mergerfs.allpaths /mnt/storage/foo | tr '\0' '\n'
$ # should show all drives
$ touch /mnt/storage/foo/bar
$ xattr -p user.mergerfs.basepath /mnt/storage/foo/bar
/mnt/disk/sd<driveplacedon>
```

**Comment by Sunako** [comment]
I think some weirdness was happening because of rsync. Do the permissions and mtime/etc need to be exactly the same for mergerfs to consider a found path "valid"? If so maybe that is why it ignored the first additional path, as it was not exactly the same. That doesn't really explain why it just gave up and continued writing to sdb when there were other disks available where it could worked on.

**Comment by trapexit** [comment]
No, mtime is not part of the policy except for `newest`.

**Comment by trapexit** [comment]
Did you try the above commands? 

If you think there is a problem I need precise directions to reproduce the issue. As mentioned above what you've described so far works fine for me.

**Comment by Sunako** [comment]
I did, the file there ended up in the correct place, sdc. However for whatever reason when I run an rsync it just goes to sdb despite it being lower than minfreespace. Maybe rsync is just being weird.

```
xattr -w user.mergerfs.func.mkdir all /mnt/storage/.mergerfs
mkdir /mnt/storage/private/foo
xattr -p user.mergerfs.allpaths /mnt/storage/private/foo/ | tr '\0' '\n'
/mnt/disk/sdc/private/foo
/mnt/disk/sdd/private/foo
/mnt/disk/sde/private/foo
/mnt/disk/sdf/private/foo
touch /mnt/storage/private/foo/bar
xattr -p user.mergerfs.basepath /mnt/storage/private/foo/bar
/mnt/disk/sdc
```

**Comment by Sunako** [comment]
So I guess I figured something out, I was rsyncing to a path like this: `/mnt/storage/private/dir1/` within said path the current items being rsync'd were in a subdir: `/mnt/storage/private/dir1/dir2/`, sdb had all the correct folders, however in sdc I only had `private/dir1/` not `dir2` within it. I guess mergerfs refuses to make directories, not sure if this is intentional or what, but it also explains why it would continue going on sdb and not do anything if the dir didn't exist on any other drives at all.

**Comment by trapexit** [comment]
Follow out mkdir and create one step at a time.

mkdir -> epff, create -> epff

mkdir dir1/dir2/
create file dir1/dir2/foo

mkdir ends up on 1 drive. then there's only 1 drive available to place things within it. epff is followed... as you asked it to be by those policies. It doesn't refuse to make it but doing what you asked. Only create files and directories where the path exists.

Look at epall for mkdir. I think that's what you want.

**Comment by Sunako** [comment]
I guess I just expected that if it was doing operations in a subdir and below the minfreespace on the drive, it would just make the proper paths on the next drive, not just keep going while below minfreespace. I think I may need to use epall for mkdir as you said.

**Comment by trapexit** [comment]
mkdir and create are different functions. Path preservation means just that. If it creates directories on other drives it's not preserving paths.
