### ISSUE TITLE
Please explain mounting twice (with and without direct_io)

### ISSUE THREAD

**Issue by dpantel** [trapexit/mergerfs#439]
Hello

In the readme, you mention "If the performance loss is too high for other apps you can mount mergerfs twice. Once with direct_io enabled and one without it."

Can you elaborate?  Do you just duplicate the mount line with and without direct_io? Or do you need separate mounting points?

Thanks

**Comment by trapexit** [comment]
`Do you just duplicate the mount line with and without direct_io? Or do you need separate mounting points?`

Yes. Both.

**Comment by dpantel** [comment]
Off the top of your head, what are the downsides of mounting an array twice?  I expect a bit of cpu/memory overhead.  Anything else?

Thanks.

**Comment by trapexit** [comment]
Nope.

**Comment by dpantel** [comment]
Great, thanks.
