### ISSUE TITLE
Migrate from mhddfs

### ISSUE THREAD

**Issue by jb-alvarado** [trapexit/mergerfs#441]
Hello,
at the moment I run mhddfs, but I would like to change to mergerfs.
You think I just can migrate my mhddfs pool to mergerfs? Or can this end in Data-loss?

Regards
Jonathan

**Comment by trapexit** [comment]
Both products are merely pooling drives. Proxies. They don't store date in any special way. There is no risk of data loss by switching.

**Comment by jb-alvarado** [comment]
Ah ok, thank you! I though maybe they get confuse when folder contents a spread over different drives.
