### ISSUE TITLE
Restoring trash is broken (in Gnome)

### ISSUE THREAD

**Issue by dpantel** [trapexit/mergerfs#442]
Not sure if this is a mergerfs issue or a Gnome trash issue, but here goes:

I used `mergerfs.mktrash <mount_pt>` to create .Trash directories on my drives and the mergerfs mountpoint.  When i "delete" something, it does show up in my Gnome trashcan, however there are two issues:

1. (minor) The deleted item shows up twice, both for the mergerfs mount point and the path to the actual storage mount point
2. (major) When using "restore" from the Gnome trash can, instead of moving the item to the original location, it's moved inside the .Trash directory.

Example follows:

mergerfs mount point: /mnt/data
my user id: 1000
mergerfs.mktrash creates: /mnt/data/.Trash

"trashing" file /mnt/data/example_path/example_file moves it to /mnt/data/.Trash/1000/files/example_file

restoring the file from Gnome trashcan moves it to /mnt/data/.Trash/example_path/example_file

Of note, when the file is in the .Trash, the info file has a relative path:
[Trash Info]
Path=example_path/example_file
DeletionDate=2017-10-07T17:18:29

$ mergerfs -v
mergerfs version: 2.23.0
FUSE library version: 2.9.7
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

**Comment by trapexit** [comment]
what are your mergerfs settings?

**Comment by dpantel** [comment]
defaults,allow_other,direct_io,use_ino,category.create=lfs,moveonenospc=true,minfreespace=10G,fsname=mergerfsPool

defaults,allow_other,dropcacheonclose=true,use_ino,category.create=lfs,moveonenospc=true,minfreespace=10G,fsname=mergerfsPoolDupe

**Comment by trapexit** [comment]
If you aren't using path preservation (you aren't) then you don't really need the trash creation tool. At least I don't believe you should. It's just to have consistency across all drives.

**Comment by trapexit** [comment]
Well... I don't have Gnome installed on my system but I am using Caja which I believe is derivative of the Gnome file manager and I'm not experiencing any issues with trashing or restoring.

I guess I'll need to try setting up Gnome to test further.

**Comment by dpantel** [comment]
After more testing, it seems like a Gnome/gvfs problem, not a MergerFS problem.  Just rebooted without mounting with MergerFS and deleting/restoring still does not work correctly.  I guess I'll go searching for help with Gnome and friends.  Sorry to bug you.

**Comment by dpantel** [comment]
In case anyone else stumbles on this, there is now a patch for gvfsd-trash:

https://bugzilla.gnome.org/show_bug.cgi?id=789328
