### ISSUE TITLE
Use of syscall(SYS_setreuid,...) on 32bit systems

### ISSUE THREAD

**Issue by wsheppard** [trapexit/mergerfs#444]
I understand calling syscall() directly matches the Samba source which does this to minimise changing privileges in multi-threaded systems. 

However, on ( my ) 32-bit ubuntu kernel ( 16.04 ), this has a side effect of ending up calling "sys_setreuid16" by the time we get to the kernel.

For 16-bit UIDs this isn't a problem, however with the use of LXC and containers and when mapping UIDs beyond 16bit UIDs this truncates the calling UID and ends up causing strange behaviour.

For example - creating a new file as UID 80000 ends up with a file with 14464. 

I understand the use of 32bit kernels is probably shrinking but I thought it worth mentioning this.

I have worked around this by simply getting glibc involved via setreuid().

Thanks,

Will.

**Comment by trapexit** [comment]
Thanks for that heads up. 

Changing the syscall's to setreuid breaks the expectations of that code. Simply changing it will likely lead to race conditions and which will will result in the wrong user and groups being set. There is a flag you can use enable at compile time (in the makefile) which enables the BSD compatible code which would address your issue properly. `UGID_USE_RWLOCK=1` should do it.

I'll look at fixing this. Seems like I need to set SYS_setreuid32.

**Comment by wsheppard** [comment]
Thanks for that - I rebuilt with that flag set and the changes I made in place ( assuming that was your advice - let me know if I've misunderstood - indeed, the LOCK flag set alone does not help )

I presume the race condition could come from having multiple-threads? If I run with num_threads=1 will that help reduce issues of that kind or not?

Thanks

**Comment by trapexit** [comment]
With that flag set you don't need your change. If you decide to run single threaded then your change is fine.

Yes, it'd eliminate any possible race conditions. You could also run in in single threaded mode with `-s`.

If you're willing to wait a bit I should have a proper fix sometime today.

**Comment by wsheppard** [comment]
Hi,
Yes, I see now. 

Out of curiosity, I just added the suffix 32 to the syscalls ( in ugid_linux.hpp) and that has done the job too ( without the LOCK flag ) - however, there are many syscalls in this kernel which end up at their 16bit variants when called without a "32" suffix. 
I've attached the syscall table file from the linux kernel source ( for my current kernel ) in case that helps.


[syscall_32.tbl.txt](https://github.com/trapexit/mergerfs/files/1391108/syscall_32.tbl.txt)

**Comment by trapexit** [comment]
Yeah, unfortunately the definitions change depending on the architecture. I've got a working fix to accommodate 32bit and 64bit platforms.

I ran into a similar issue with setgroups but I didn't realize there was this pid namespace issues.

The fix will come later today.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/releases/tag/2.23.1

Should fix the issue.
