### ISSUE TITLE
Files disappear

### ISSUE THREAD

**Issue by Mangoes** [trapexit/mergerfs#446]
**System:** ubuntu server 17.10
**mergerfs version:** 2.23.1 (compiled from git on the ubuntu 17.10 with "make clean", "make deb")
**Pool** : 7 BTRFS disks

This pool **has worked great for years** with mhddfs.

Yesterday I changed the pool from mhddfs to mergerfs.
(mount options: defaults,allow_other,direct_io,use_ino,moveonenospc=true,minfreespace=50G)

**First issue yesterday after switching the pool over to mergerfs:**
One of the folders in the pool contains 10 active deluge torrent downloads.

Immediately after switching the pool over to mergefs I noticed:

1. In the torrent dir: in samba 2 dirs and 2 files didn't appear. Deluge (which is accessing the pool directly, not via samba) marked these 2 files as errors because it didn't see them. (the other 8 downloads where fine).

**The FIX:** I deleted the 2 dirs (didn't need them) and moved the 2 files to one of the other drives in the pool.

After this, all was fine and deluge continued to download the files without any issue, and samba could see all of the files in the torrent dir.

**Second issue today 20 hours later:**
Suddenly for no reason, while it was downloading, deluge marked 8 of the 10 downloads as errors. The files disappeared.

_Checking in the samba share:_ all of the files in the torrent folder disappeared. Everything else in the other dirs was still there.

_Checking on the filesystem:_ as root everything was there. But as user, it was showing d?????????????? for the permissions. (this wasn't the case before????)

**What I did:**

1. I ran: "mergerfs.fsck -f newest" on the pool. It fixed some issues. But the problem was still there.

2. Found an issue with mmap in the docs (don't know if this applies to deluge?). So to make sure, I replaced "direct_io" with "dropcacheonclose=true", and remounted the pool. 

This issue was still there. I tried many times, unmounting, remounting, etc...

**The FIX:** I switched back to mhddfs and everything is fine ! The files are there in samba, and deluge (which accesses the pool directly, not via samba) downloads like a charm as it has been doing for years.

So, what's the problem ? Is mergerfs buggy or is mhddfs just superior ?

How can I fix this?

Thanks.

**Comment by trapexit** [comment]
You've not really given me enough information to deduce the problem. MergerFS is not buggy AFAIK and mhddfs is far from superior. mhddfs in fact is extremely lax on security which can manifest as "working" when in fact it's not properly responding to acls because it runs as root.

As the docs mention in regard to files or directories not appearing it's probably permissions. Take one file or directory in which you're experiencing the problem and check the permissions. mergerfs enforces, strictly, proper credentials which means that things can look weird if permissions are out of sync.

**Comment by Mangoes** [comment]
Thanks for your feedback.

**First:** 
1. Then why was mergerfs partially working at first (deluge seeing only 8 files out of the 10)
2. And then after moving these 2 files to another drive within the pool, it was all working fine during 20 hours, deluge constantly writing to these files while downloading them.
3. And after these 20 hours, why did these 10 files (each inside their own folder) suddenly disappear in deluge and samba without me doing anything ?

**Second:**
Permissions is the first thing I checked.

Here is the content of the torrent directory:

drw-rwSr--+ 1 myuser  deluge 1534 oct 22 21:25 .
drwxr-xr-x     1 myuser  users   124 mar 20 00:24 ..
drwxrws---+ 1 deluge  deluge  202 oct 22 21:30 File1-dir
drwxr-s---     1 deluge  deluge  158 oct 22 03:33 File2-dir
drwxr-s---     1 deluge  deluge  172 oct 22 08:08 File3-dir
drwxr-s---     1 deluge  deluge  140 oct 21 18:43 File4-dir
drwxrws---+ 1 deluge  deluge  186 oct 22 20:20 File5-dir
drwxrws---+ 1 deluge  deluge  938 oct 21 19:22 File6-dir
drwxr-s---     1 deluge  deluge  172 oct 18 17:39 File7-dir
drwxr-s---     1 deluge  deluge  174 oct 20 00:29 File8-dir
drwxr-x---     1 deluge  deluge  154 oct 21 18:48 File9-dir
drwxrws---+ 1 deluge  deluge 1678 oct 22 20:15 File10-dir

deluge is running as user deluge.

The "S" is to force group permission as rw for new files (this is not working with mhddfs, but was working fine with mergerfs as you can see with the 4 files that where created after I switched to mergerfs (during the 20 hours when it worked)). I set the S because even when running deluge with a 664 mask it creates the files as rw-r (but I don't know if this was because of mhddfs... perhaps...).

Anyway, this "S" shouldn't be the problem for mergerfs, should it ?

Many thanks for your help.

**Comment by Mangoes** [comment]
Furthermore, what about the "direct_io" with deluge? Changing it to "dropcacheonclose=true" didn't seem to change anything.

Does "direct_io" have anything to do with my problem ?

What should I do, keep the "direct_io" or not?

Thanks !

**Comment by trapexit** [comment]
I don't know if mhddfs properly handled umask. It's been years since I fooled with it.

I don't know the state of the files before your issue. I don't know how deluge works. You're asking me questions to things that without extremely clear timeline of behavior could I possibly answer. MergerFS is just stat'ing and readdir'ing directories like literally any other piece of software. If you `ls` and don't see something it means that mergerfs isn't seeing it either (mostly certainly due to permissions) or there is some serious bug that's gone uncaught the past couple years.

I don't know how deluge works. I don't use it. That said... direct_io has nothing to do with listing content. Only reading and writing. If it works at all with it enabled then it should be fine. Same with if it works while off. 

Unless you can create a concise, reproducible situation there's not much outside what is already in the docs which I can say. I put all known issues and gotcha's in the docs. I've never received feedback from anyone regarding deluge or btrfs. I can try to setup deluge but I'm pretty sure others have used it with success.

**Comment by Mangoes** [comment]
**I am now trying this:**

1. I am now remounting the pool with mergerfs (so what follows is done with mergerfs to be sure all is done right)
2. mv the dir torrents to torrents2
3. mkdir torrents with new chown and chmod (done with mergerfs)
4. mv everything from torrents2 to torrents
5. rm -r torrents2
5. chown and chmod all the files in torrents again to make sure.

I hope this will fix it. I'll report back.

Thanks !

**Comment by trapexit** [comment]
I just installed deluge 1.3.12 on ubuntu 16.04 and downloaded several ubuntu iso's without issue. I'll let it run for a while to see if anything happens. I've got ext4 drives with the following setup `defaults,hard_remove,allow_other,direct_io,ignorepponrename=true,fsname=media,use_ino,dropcacheonclose=true`

**Comment by Mangoes** [comment]
Thanks for your feedback.

I have done what I said above, this means:

1. recreated all the directories a new (to make sure all the special acl attributes are removed) and moved the files into the new directories
2. removed all the special acl attributes on the files with setfacl -x , now all of the files also have default attributes.

**Example:** sudo getfacl *

file: FILE.txt
owner: deluge
group: deluge
user::rw-
group::rw-
other::r--

As you can see, there is no other attribute left than the default ones.

But:
1. "ls -la" still shows -????????? ? ?       ?         ?            ? FILE.txt
2. "sudo ls -la" still shows drw-rw-r-- 1 deluge  deluge 1678 oct 22 22:39 FILE.txt

So, I remounted with mhddfs and I will finish downloading the files. And when done, I will copy them to windows over samba and then back to the server with mergerfs.

**Conclusion:**

There seems to be a bug. Either in mergerfs, or in BTRFS, or fuse, or a combination of all of them together.... ?

**Comment by trapexit** [comment]
Use strace with `ls`. Obviously it can see the file but is unable to `stat` it.

And if you can see it as root then clearly it's a permissions problem.

`strace -o /tmp/ls.trace ls -la`

**Comment by Mangoes** [comment]
One thing I forgot to report:

After I did all of this (as explainend above):

1. I am now remounting the pool with mergerfs (so what follows is done with mergerfs to be sure all is done right)
2. mv the dir torrents to torrents2
3. mkdir torrents with new chown and chmod (done with mergerfs)
4. mv everything from torrents2 to torrents

At this point "ls -la" correctly showed drw-rw-r-- 1 deluge deluge 1678 oct 22 22:39 FILE.txt

Then I did point 6 on each file in each directory (to make sure the properties when rewritten properly):

6. chown and chmod all the files (*) in torrents again to make sure.

After I did this point 6, "ls -la" again showed -????????? ? ? ? ? ? FILE.txt   (only sudo was showing the correct properties).

**Conclusion:** chown / chmod triggered the bug. The bug was also triggered alone while deluge was writting to the files after ~ 20 hours....

**Comment by Mangoes** [comment]
Attached the output of "strace -o /tmp/ls.trace ls -la"

[ls.zip](https://github.com/trapexit/mergerfs/files/1405402/ls.zip)

**Comment by trapexit** [comment]
`lstat("File1.txt", 0x55e3bc3a48b0)      = -1 ENOENT (No such file or directory)`

What are your exact mount settings? And the permissions before and after chmod'ing? Both through mergerfs and underlying FS?

MergerFS is changing credentials to the user making the call and then issues the same command. If `ls` can't read the file but can read the directory often it's a mismatch between directories.

There are too many variables for me to help with these kinds of issues. I need the most compact and straight forward reproduction possible. With standards app and workflows.

**Comment by Mangoes** [comment]
**To summarize** (where the problem is coming from):

1. I was running mhddfs (pool on BTRFS drives)
2. A long time ago while using mhddfs, on the torrent dir I "setfacl" to force group rw on anything written in this directoy (but this didn't do anything as it seems mhddfs doesn't support acls)
3. Today after switching to mergerfs, the problem happens. It seems (?) only with the files that had the setfacl set while the directory had this S attribute (point2 above).

**Answer to your last post:**
a) There was no mismatch between directories left after I recreated all the directories with mkdir (so the dirs were back to default acl settings). Then, I copied the files into the directories.

b) So, only the files had the acl flag. But after "chown deluge:deluge" and "chmod 664" the problem was back. (my user who is in the deluge group can see the files, but the permissions appear as ???????????? with "ls -la". And deluge application gives an error on the files, and they don't appear in samba shares).

c) I then removed everything that wasn't default with "setfacl -x" on each file. This didn't fix the problem.

**What I am doing now:**
Remounted with mhddfs. And I will finish the downloads this way.

After this is done, I will go back to mergerfs. I think (?) there won't be any problem with new files created with mergerfs (I hope).

Thanks for your help.

**Comment by Mangoes** [comment]
**Mount settings :** defaults,allow_other,direct_io,use_ino,moveonenospc=true,minfreespace=50G,fsname=mergerfs

**Permissions:**
644 changed to 664

It's the same in the underlying drives.

But since this problem happened with mergerfs, "ls -la" in the directories with the problem now also show "-????????? ? ? ? ?            ? File.txt".  (same on the underlying drives)

So, the problem seems to have been caused by mergerfs (on files that had the setfacl group rw on the directory). These files now remain broken.

**Conclusion:** as I said, back to mhddfs to finish downloading these files, and then I'll try mergerfs again for new files.

**Comment by Mangoes** [comment]
**And don't forget this strange thing:**

When I first switched to mergerfs:

1. deluge couldn't see 2 out of 10 files (8 were ok)
2. I moved the files from their underlying drive to another in the pool. Then, it was ok.
3. During ~ 20 hours deluge downloaded the files without any problem.
4. After ~ 20 hours, the deluge UI suddenly had all of the files marked as error. It could see the files any more... (user "ls -la" shows "-????????? ? ? ? ? ? File.txt")

How strange is this ?

**Comment by Mangoes** [comment]
It seems I was able to fix the problem by chmod 775 the directories inside my torrents folder.

Further testing show that chmod 664 the directories, brings the problem back.

**To summarize:**

 The folder structure is: /torrents/File1/File1.txt

If dir File1 is "chmod 664" the problem is there. With "chmod 775" the problem is fixed.

This also means, that it isn't possible to recursively chmod -R 664 all the files, because this would bring the problem back for all the File1.txt.

If I would do  "chmod -R 664", I can "ls -la" all the directories like "File1" (and they show correct permissions), but listing the files inside the directories (File1.txt) showns ?????????????? File1.txt   for the permissions (and I can't write to the files).

"chmod 775" on the directories like "File1" fixes it.

This is strange. So now, how can I recursively "chmod -R 664" all the files in one go (*) without breaking the permissions?

**Comment by trapexit** [comment]
Not having directory execute bit set explains it. mergerfs didn't have permissions to access the directory. mhddfs, which almost always runs things as root, has access. I'll have to look to see why it knew the files. Stat'ing and reading a directory are separate calls so there may be a disconnect in these kinds of situations.

As for changing specific types' permissions: use `find`

`find /base/path -type f -exec chmod ugo=664 {} \;`

`find /base/path -type f -exec chmod ugo=775 {} \;`

**Comment by trapexit** [comment]
Nope... it's legit.

```
$ mkdir /tmp/asdf
$ cd /tmp/asdf
$ seq 10 | xargs touch 
$ cd ..
$ ls -1 /tmp/asdf
ls: cannot access 'asdf/8': Permission denied
ls: cannot access 'asdf/2': Permission denied
ls: cannot access 'asdf/10': Permission denied
ls: cannot access 'asdf/5': Permission denied
ls: cannot access 'asdf/3': Permission denied
ls: cannot access 'asdf/7': Permission denied
ls: cannot access 'asdf/9': Permission denied
ls: cannot access 'asdf/6': Permission denied
ls: cannot access 'asdf/4': Permission denied
ls: cannot access 'asdf/1': Permission denied
total 0
-????????? ? ? ? ?            ? 1
-????????? ? ? ? ?            ? 10
-????????? ? ? ? ?            ? 2
-????????? ? ? ? ?            ? 3
-????????? ? ? ? ?            ? 4
-????????? ? ? ? ?            ? 5
-????????? ? ? ? ?            ? 6
-????????? ? ? ? ?            ? 7
-????????? ? ? ? ?            ? 8
-????????? ? ? ? ?            ? 9
```

**Comment by Mangoes** [comment]
So this means that as it is, the "chmod" command is broken/incomplete.

Because in a recursive folder structure, who will think about _"find /base/path -type f -exec chmod ugo=664 {} \;"_ when you have "chmod -R 664" ???

So, "chmod -R" doesn't work properly ???

Many thanks for your help !

**Comment by trapexit** [comment]
chmod -R does work right. It just doesn't distinguish between directories and files when used that way. There is 'X' which according the man page: execute/search only if the file is a directory or already has execute permission for some user (X).

Which means if you had everything as 664 you could `chmod -R ugo+X /base/path`

**Comment by Mangoes** [comment]
So:

- Everytime we do "chmod -R" without executable bit, we then need to fix the directories with "chmod -R ugo+X", otherwise all the files are broken.

Wow....yeah, to me this looks like "chmod" is definitively broken.

Thanks.

**Comment by trapexit** [comment]
It's not broken. You aren't using it correctly. Changes are relative (`+`, `-`) or absolute (`=`). 'X' gives you the ability to set or reset execute based on the common pattern you're looking for.

If you're doing `chmod -R 664 /path/` you are explicitly saying "change all files & dirs from base path down to 644". chmod is not super complex. It has `X` for the common pattern of wanting to add execute to dirs. Any other fanciness requires something like find.

**Comment by Mangoes** [comment]
So the problem isn't chmod, it's the linux/unix system that is flawed.

A folder without "x" bit doesn't allow access to the files (you can see them, but not read even if rw is set). "rw" is not enough to give access... and file permissions will show as ????????????????.

**So Read doesn't read unless the holding folder is executable. The folder giving Read access is not enough.**

I'm sorry, but I can't see the logic behind this unnecessary complication.

But here we are beyond the scope of mergerfs.

Thanks a lot for your help.

**Comment by trapexit** [comment]
Read means you can 'read the directory'. You can see whats inside it. Execute means you can gain access to those files. Between read and execute you can say: hide a file from casual view but allow others to access it if they know where it is. Or the reverse (probably less useful).

https://en.wikipedia.org/wiki/File_system_permissions#Traditional_Unix_permissions
