### ISSUE TITLE
Software that attempts to chown files inside mount breaks.

### ISSUE THREAD

**Issue by Nottt** [trapexit/mergerfs#447]
`"chown: changing ownership of '/redacted/': Permission denied"`

Is there a way to allow chown to be used or start mergerfs as the user that should own that folder so hopefully the software will skip this task (even if current folder already shows as owned by desired user in `ls -l` output of the folder).

This happens if I just run chown in the terminal as root too. 

Creating my mount with this fstab entry. 
```
/mnt/disk* /home/automation/downloads/ fuse.mergerfs defaults,allow_other,use_ino,dropcacheonclose=true,moveonenospc=true,minfreespace=10G,ignorepponrename=true,category.create=epmfs  0 0
```

**Comment by trapexit** [comment]
I don't quite understand what's wrong. Are you suggesting that chown isn't working as it should? Something you have permissions isn't working? What are the permissions of the file/directory in question? Are you using special acls? File attributes?

**Comment by Nottt** [comment]
I can't chown any files inside the mount, even as root... I don't have anything else other than that fstab entry. But I think I may know what is...One of the folders is a CIFS mount that also fails to chown files...I don't know if this can be a cause or not of this issue since in theory the mergerfs mount is a different filesystem?

**Comment by trapexit** [comment]
mergerfs is *not* an overlay or copy-on-write filesystem. It's a simple merging / union filesystem. If the underlying system forbids the chown then it will return precisely that error.

**Comment by Nottt** [comment]
Oh okay, thanks. It was my CIFS mount...I just assumed it was mergerfs...you can close this issue!
