### ISSUE TITLE
Cannot access folder symlinks over Samba

### ISSUE THREAD

**Issue by haoto** [trapexit/mergerfs#448]
I have a mergerfs mount shared over samba to allow access from Windows clients.

On Windows clients, I can access symlinks pointed at files, both within the same folder and across different folders, without problem. But when I try to access folder symlinks, it gives me an error dialog saying:

```
D:\Path\To\Symlink\Name is not accessible.

The directory name is invalid.
```

I can also access folder symlinks just fine on the Linux host. I'm not sure if it's related, but the underlying filesystems are BTRFS.

**Comment by trapexit** [comment]
There's no such thing as a "folder symlink." Do you mean a symlink which happens to refer to a directory? Symlinks to directories work just fine with mergerfs. Are you sure the symlink isn't pointed to something incorrect or with permissions SAMBA doesn't have access to?

**Comment by haoto** [comment]
Yes, I meant to say symlinks to folders. They are all on the same file system and Samba does have permission for them. I used exact same steps for links to files and to folders. Somehow the latter just doesn't work over Samba.

**Comment by trapexit** [comment]
Does it work locally?

**Comment by haoto** [comment]
Yes.

**Comment by trapexit** [comment]
What are the links? This is not likely to be a mergerfs issue but I can't help if you don't provide me with precise information about the content and permissions.

**Comment by haoto** [comment]
I tried creating an empty folder at the root of the mount, then create a symlink to that said folder, also at the root of the mount. Everything with 777 permission. The symlink shows up in the Samba share but when I try to access it, it gives the error on the top post.

**Comment by haoto** [comment]
To add, the Samba share also has 777 permission for guests. I'll try accessing the same share on a Linux host later, but IIRC Linux clients also can't access the symlinks to folders over Samba.

**Comment by trapexit** [comment]
I don't know what I can do further without evidence that this is a mergerfs issue. MergerFS and Samba are used together by many people including myself without issues. I just tested it and worked fine.

I'd need something more precise and reproducible to comment or test further.

**Comment by haoto** [comment]
It could be specific to btrfs as the underlying file system. I've had endless issues with overlayfs which is why I switched to mergerfs. What should l look for if I go through the debug logs myself?

**Comment by trapexit** [comment]
I don't see how symlinks could be screwed up on btrfs. There are no mergerfs logs and I don't know what to check on windows. If you think it's btrfs then why not just create a new mergerfs and Samba mount which points to another fs? /tmp or anything.

**Comment by haoto** [comment]
Heh, all my file systems are btrfs. Hadn't thought about /tmp though. Will try that now.

**Comment by haoto** [comment]
Welp, still no luck, exact same problem with everything on /tmp. So not a problem with btrfs either.

Mergerfs is mounted with `defaults,allow_other`.

Samba version is 4.4.4.

**Comment by trapexit** [comment]
What's the Samba settings? What's the link? Absolute or relative?

Have you tried symlinks not through mergerfs? Samba mount on /tmp and then through mergerfs to tmp.

**Comment by haoto** [comment]
Sorry for the late reply. Turns out this isn't related to mergerfs at all as I got the same result over Samba on a ext4 share too. I believe it's this Samba bug: https://bugzilla.samba.org/show_bug.cgi?id=12860, but my Centos install hasn't got the fix yet. Closing because it's unrelated to mergerfs.
