### ISSUE TITLE
[Question] Can I add non-empty drives?

### ISSUE THREAD

**Issue by Nixellion** [trapexit/mergerfs#453]
I suspect the question is "Yes" but I just want to double and triple-check it, to keep the data safe.

Is it possible to make mergerfs pool starting with non-empty drive(s)?

I'm starting my NAS with 1 HDD for main pool, and I want to later start adding more drives to it when needed. Should I setup mergerfs now, before writing data to this drive, or will it be as simple to set it up when I really need it?

I'm sorry for the silly question :)

**Comment by trapexit** [comment]
Yes.

https://github.com/trapexit/mergerfs#can-mergerfs-be-used-with-drives-which-already-have-data--are-in-use

It doesn't make any difference whether you set it up now or later outside the need to point your apps to the pool.

**Comment by Nixellion** [comment]
Thanks a lot.
