### ISSUE TITLE
LFS doesn't work

### ISSUE THREAD

**Issue by segator** [trapexit/mergerfs#455]
General description
===================
LFS doesn't work as I expected

Expected behavior
=================
fill up until minfreespace a disk before start write on other disk

Actual behavior
===============
I set the create policy to LFS, but it's seems is using a policy to write new files to empties disks

**Precise** steps to reproduce the behavior
===========================================
mount lfs with single disk with lfs create and add disks with xattr 
`xattr -w user.mergerfs.srcmounts '+>/mnt/local/peliculas/disco3' .mergerfs
`

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: 
`mergerfs version: 2.23.1
FUSE library version: 2.9.7
fusermount version: 2.9.4
using FUSE kernel interface version 7.19
`
* [ ] mergerfs settings: /mnt/local/peliculas/disco* /mnt/local/peliculas/mountpoint fuse.mergerfs minfreespace=1G,defaults,allow_other,category.create=lfs,moveonenospc=true,fsname=Peliculas 0 0
* [ ] Linux version:Linux segator 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* [ ] List of drives, filesystems, & sizes: `df -h`
`Peliculas                      44T  8.1T   36T  19% /mnt/local/peliculas/mountpoint
/dev/sdm                      7.3T  147G  7.2T   2% /mnt/local/peliculas/disco5
/dev/sde1                     472M  106M  342M  24% /boot
/dev/sdi                      7.3T  170G  7.2T   3% /mnt/local/peliculas/disco2
/dev/sdp                      7.3T  151G  7.2T   3% /mnt/local/peliculas/disco6
/dev/sdl                      7.3T  164G  7.2T   3% /mnt/local/peliculas/disco4
/dev/sdk                      7.3T  151G  7.2T   3% /mnt/local/peliculas/disco3
/dev/sdh                      7.3T  7.3T  1.4G 100% /mnt/local/peliculas/disco1
`

**Comment by trapexit** [comment]
I'm not sure I understand. What you describe as expected behavior is 'first found' policy. 'least free space' works as described in the docs. Choose the drive with the least free space.
