### ISSUE TITLE
Permission Nightmare

### ISSUE THREAD

**Issue by MYDIH** [trapexit/mergerfs#457]
General description
===================

I'm running a docker container (running emby media server) and it is unable to read my media library located behind a mergerfs mount. After digging (a lot) I found that it is permission related. The host and all the containers I use shares some known users with matching Uids and Gids. All the "shared" files between containers and host are owned by one of those users. Now the problem, when using mergerfs (without it everything is fine), the root user inside the container can access the data into the mounted dir, but the special users previously described can't. When I list the directories with `ls -la`, permissions are messed up and replaced with ? signs and files are reported as not found ...

Expected behavior
=================

Being able to access mergerfs mount from a docker container when the user in the docker container isn't root

Actual behavior
===============

Can't access mounts on users different from root into containers

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

Described Before

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`

```
mergerfs version: 2.23.1
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments

`/mnt/.IndividualDisks/Disk2:/mnt/.IndividualDisks/Disk3      /mnt/Data      fuse.mergerfs        defaults,allow_other,direct_io,use_ino,category.create=rand     0 0`

* [x] Linux version: `uname -a`

`Linux ArchMainServer 4.14.6-1-ARCH #1 SMP PREEMPT Thu Dec 14 21:26:16 UTC 2017 x86_64 GNU/Linux`

* [x] Versions of any additional software being used

`Docker version 17.11.0-ce, build 1caf76ce6b`

* [x] List of drives, filesystems, & sizes: `df -h`

```
/dev/sdb1          1,8T    820G  921G  48% /mnt/.IndividualDisks/Disk2
/dev/sdd1          1,8T    719G 1022G  42% /mnt/.IndividualDisks/Disk3
```

**Comment by rubylaser** [comment]
This is a configuration error and not the fault of mergerfs.  I have the exact setup you mention above working without issue.  That being said, @trapexit is going to need to see some examples of the permissions of the underlying disks.  

Also, what command did you use to create your Emby Server in docker?  You need to use the optional settings to set the app user to a system user, and setup a directory to store the configuration files (that is also owned by that same user, not root).  Something like this.

`docker run -it --rm -v /usr/local/bin:/target \
    -e "APP_USER=username" \
    -e "APP_CONFIG=/var/lib/embyserver" \
    emby/embyserver instl`

Also, do you have other Docker containers running that can access the mergerfs mountpoint? In my case, I have 5 other containers that access the mount without issue.

**Comment by MYDIH** [comment]
Thanks for your (quick) comment,

> This is a configuration error and not the fault of mergerfs

Glad to here it ! Was struggling at finding an alternative ...

> Also, do you have other Docker containers running that can access the mergerfs mountpoint? In my case, I have 5 other containers that access the mount without issue.

Let's take a simple example then, I have a transmission container, much more simple than the emby one. This is it's dockerfile :

```
FROM base
LABEL maintainer="MYDIH <mailmydih@gmail.com>"

RUN apk --no-cache --no-progress upgrade                                                              \
    && apk --no-cache --no-progress add curl transmission-daemon transmission-cli bash \
    && groupadd -g 2001 private-manager                                                               \
    && usermod -u 2000 -G private-manager transmission                                                \
    && groupmod -g 2000 transmission

COPY settings.json /usr/local/share/transmission/config/settings.json
RUN chown -R transmission:transmission /usr/local/share/transmission && \
    chmod 744 /usr/local/share/transmission/config/settings.json

USER transmission:transmission

VOLUME ["/mnt/Torrents"]

EXPOSE 9091 51413/tcp 51413/udp

HEALTHCHECK --interval=60s --timeout=15s \
  CMD curl -LSs http://localhost:9091/ >/dev/null

ENTRYPOINT ["transmission-daemon", "--foreground", "-g", "/usr/local/share/transmission/config/", \
            "--log-info", "--no-portmap"]
```

Base is just alpine + shadow. When using the above dockerfile, when the container is run and accessed using exec, `whoami` properly returns transmission but when navigating to /mnt/Torrents, the error I descibed above is shown ... The run command :

```
docker run --network containers --dns 192.168.2.1 --ip 192.168.2.4 -d --restart always -it \
           --mount type=bind,src=/mnt/Data/Downloads/Torrents,dst=/mnt/Torrents            \
           --name transmission transmission
```

Thanks for your help

**Comment by trapexit** [comment]
The easiest way to test is probably to create a sticky directory with the same perms as /tmp inside the pool. If you can use that directory then check the permission of files created. If it's not working then it's something else. SELinux or the like. http://nanxiao.me/en/selinux-cause-permission-denied-issue-in-using-docker/

**Comment by MYDIH** [comment]
Thanks again for your time,

So actually I isolated the problem using a minimal image, the thing that I didn't understood is that all the chain of directories (even out of the container) needs to be accessible. When that's the case, it seems to work (in my minimal example at least). I will try to arrange my permissions to take this fact into account.

I will edit this last comment to confirm that this issue should be closed.

Thanks again

**Comment by MYDIH** [comment]
Hey again,

Just to add to that I really loose a lot of time, having weird permissions driving me nuts, but in the end all my permissions issues was due to the fact that you need to remount when you change (drastically maybe ?) permissions. Anyway, after a remount, all my problems wher gone ...

The problem that make me start this issue was surely the permissions of my merged mount points (disk1, disk2, etc ...). But after that I was having weird issues about users able to see a 770 directory without being in the proper group. If you face such a problem, remount the mergerfs mount point.
