### ISSUE TITLE
use_ino option not shown as mount option

### ISSUE THREAD

**Issue by henfri** [trapexit/mergerfs#460]
General description
===================
When mounting with the option use_ino, neither the output of the command "mount" nor "cat /proc/mounts" shows that this mount option is actually used.
Example command:
`mergerfs -o defaults,allow_other,use_ino /root/mergerfstest/test1:/root/mergerfstest/test2 /mnt/test`

Expected behavior
=================
`mount`
`1:2 on /mnt/test type fuse.mergerfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,**use_ino**)
`

Actual behavior
===============
`1:2 on /mnt/test type fuse.mergerfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
`

**Precise** steps to reproduce the behavior
===========================================
run
`mergerfs -o defaults,allow_other,use_ino /root/mergerfstest/test1:/root/mergerfstest/test2 /mnt/test`
`mount`
`cat /proc/mounts |grep /mnt/test`

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
mergerfs version: 2.23.1
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
see above
* [x] Linux version: `uname -a`
Linux homeserver 4.13.0-0.bpo.1-amd64 #1 SMP Debian 4.13.13-1~bpo9+1 (2017-11-22) x86_64 GNU/Linux

Thanks for your work on mergerfs! I appreciate it.

**Comment by henfri** [comment]
Hello,

can I do anything to further nail down this problem?
Or any other suggestions?

Greetings,
Hendrik

**Comment by trapexit** [comment]
It's probably a FUSE issue. I just need to get the cycles to investigate and send a report upstream.

**Comment by henfri** [comment]
Hello,

thanks for your reply. 
Cycles?
Anything I can do to support?

How can I find out, if the mount option is just not displayed, or whether it is not used by mergerfs?
I'd like to know, if this is the reason for my problem here:
https://github.com/borgbackup/borg/issues/3492

Is there a workaround for the time being?

Greetings,
Hendrik

**Comment by trapexit** [comment]
What's the relation between the option in the mount options and your borg issues? Is something querying the options in order to decided how to act?

**Comment by henfri** [comment]
No, Not at all. I Just need to confirm that use_ino is active to make Sure that this ist Not the cause for my Borg issue.

**Comment by trapexit** [comment]
If you put it in the arguments it's used. If the value was invalid it'd error. Just look at the inode of a file. If it's some large really number then it's working.

The feature works if that's ultimately what you're asking. It just isn't showing up in the options for some reason. It's not the only one as I remember. Just a display issues.

**Comment by henfri** [comment]
Ok, thanks. 
I also found the problem with borg (see that issue).

**Comment by trapexit** [comment]
Can't be fixed. Not passed to the kernel.
