### ISSUE TITLE
Moving files via SSHFS results in Operation not permitted - Invalid cross-device link

### ISSUE THREAD

**Issue by Jotschi** [trapexit/mergerfs#462]
General description
===================
I'm trying to move a file from one folder which is mapped to pysical deviceA/fs to one folder that is mapped to deviceB/fs. The action is not directly performed on the mounted mergerfs but instead run over SSHFS.

Expected behavior
=================

No error

Actual behavior
===============
I started mergerfs in debug mode and saw that the rename operation (move) results in error -18. 

```
unique: 1159, opcode: RENAME (12), nodeid: 35, insize: 76, pid: 16838
rename /folderA/file /folderB/file
   unique: 1159, error: -18 (Invalid cross-device link), outsize: 16
```

I'm not sure how mergerfs should behave or whether this is an error of SSHFS any hint would be welcome. I don't see this issue when using NFS.

Steps to reproduce the behavior
===========================================

1. Setup filesystems

```bash
dd if=/dev/zero of=diskA bs=1024 count=1000
sudo losetup /dev/loop2  diskA
sudo mkfs.ext4 /dev/loop2
mkdir mountA
sudo mount /dev/loop2 mountA

dd if=/dev/zero of=diskB bs=1024 count=1000
sudo losetup /dev/loop3  diskB
sudo mkfs.ext4 /dev/loop3
mkdir mountB
sudo mount /dev/loop3 mountB

# Use losetup or physical disks to separate the filesystems
sudo mkdir mountA/folderA
sudo touch mountA/folderA/file
sudo mkdir mountB/folderB
```

2. Setup mergerfs on the server

```bash
sudo mkdir merged
sudo mergerfs -o allow_other -d -f mountA:mountB merged
```

3. Mount the merged folder

```bash
sudo mkdir mergedSSHFS
sudo sshfs -o allow_other,sshfs_debug,debug -f root@localhost:/tmp/test/merged mergedSSHFS
```

3. Invoke the move

```bash
sudo mv mergedSSHFS/folderA/file mergedSSHFS/folderB/file
```

~~Observe the `Operation not permitted` error.~~

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: 2.18.0
* [x] mergerfs settings: `mergerfs -o allow_other -d -f`
* [x] Linux version: `Linux proton 4.9.0-3-amd64`
* [x] SSHFS (client): 2.8

**Comment by trapexit** [comment]
EXDEV is a perfectly valid error should rename be called across devices or with mergerfs if the devices under it are different. If you're using default settings (epmfs for create) then it won't be cloning the paths (as described in the docs.)

What is the output of `mv`? If it gets EXDEV it should copy and unlink.

**Comment by Jotschi** [comment]
Sorry, totally forgot to add that. I get `Operation not permitted`  from mv.

**Comment by trapexit** [comment]
Is sshfs or mergerfs running as root? Is sshfs root squashing? 

You need to boil it down further. One drive in mergerfs. Reproduce and strace mergerfs or sshfs to see where it's happening.

**Comment by Jotschi** [comment]
All processes run as root. There is should be no root squashing involved. I don't think it is a permission problem. I think sshfs is just respond with a generic Operation not permitted error. I'll run sshfs in verbose debug to confirm that. I will also check whether category.action=epff changes the result. Thanks for your input.

**Comment by Jotschi** [comment]
@trapexit I tried to reproduce the issue locally with an losetup arrangement and was unable to do so. I'll close the issue for now and see whether I can isolate the real cause. But so far mergerfs seems to work just fine. Maybe it has something to do with the ZFS filesystem that I'm using. I'll reopen the issue if needed. Thanks your your help.

**Comment by y2kbugger** [comment]
I get the same thing when trying to move between different subvolumes of a BTRFS file system which has been sshfs mounted.

When I SSH directly into the system I get no problem. There's also no issue when moving within a subvolume.

**Comment by trapexit** [comment]
"same thing" meaning what? Permission issue or EXDEV?

**Comment by y2kbugger** [comment]
"Operation not permitted" using mv

**Comment by trapexit** [comment]
What is the setup? Are you positive there isn't some root squashing or similar going on? mergerfs expects root to be able to be able to take certain privileged behaviors.

**Comment by y2kbugger** [comment]
Sorry, I just meant without mergerfs at all, I thought that might help
diagnose the previous and future problems: I don't think they have anything
to do with mergerfs.

**Comment by trapexit** [comment]
If you think it's a problem with sshfs (which is unlikely, it sounds like a typical permission problem due to how sshfs works) then you should bring it up with them.
