### ISSUE TITLE
Issue: Moving a folder to a different directory leaves an empty folder behind

### ISSUE THREAD

**Issue by heymoe** [trapexit/mergerfs#464]
General description
===================
I've noticed that sometimes when I move a folder that contains some files and/or sub-folders with files in there, I'm left with an empty folder (and sub-folder) of the directory I moved in the source folder.

Example:
/share = the mergerfs mount point
cd /share/dir1
mv some-folder /share/dir2

some-folder and the files and sub-folders in it are successfully gets moved to dir2 but I'm left with an empty some-folder in dir1.

I've had this happen when moving some-folder to another directory under /share as well as to a stand alone drive / path that is not part of the mergerfs mount. This happens when running the mv command directly on the linux server as well as via /share being exported via samba and me dragging a some-folder to a different directory via windows explorer. 

Expected behavior
=================
Not left with an empty folder in the source directory after it's moved to a new destination. 

Actual behavior
===============
see General description

**Precise** steps to reproduce the behavior
===========================================
see General description

I also looked at the Known issues and FAQ and didn't see anything in there that might be causing what I'm seeing. I'm not getting an error. It happens over samba as well as on the local server from the command line.

Since this doesn't happen all the time I'm sure debugging this isn't going to be easy. I'll see if I can figure out a way to make this reproducible. 

System information
==================
# mergerfs -V
```
mergerfs version: 2.23.1
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

# mergerfs options:
`defaults,allow_other,dropcacheonclose=true,use_ino,fsname=mergerfs,minfreespace=10G,func.getattr=newest`

# uname -a
`Linux SVR 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux`

Running Arch Linux 64bit

Drives are 4x 8TB Western Digital Reds

**Comment by trapexit** [comment]
Have you confirmed that the permissions are identical for all underlying paths?

**Comment by heymoe** [comment]
I'm pretty sure in the cases I noticed this issue that the permission and ownership of the files and directories were correct but will double check the next time I see this happen.

Plus I was able to delete the empty directories using the same user / session right after the move was done without having to fix permissions or ownerships.

**Comment by trapexit** [comment]
Whichever the situation I'll need more information so I can reproduce it. A minimal reproduction if possible.

**Comment by heymoe** [comment]
I'll see what I can come up with. Like I said it doesn't happen all the time. The last time it happened I moved   like 100 directories from one folder to another and out of all of those I only end up with one empty directory after the move was done. Really hit and miss.

**Comment by trapexit** [comment]
Was it across devices? If so then it could be faux failure due to async remove. You could try using hard_remove option.

**Comment by heymoe** [comment]
I'm pretty sure that when this happens it is when moving a directory from across devices be it a another device that is part of the mergerfs share or not. I'll look into trying hard_remove but it sounds like it's not a recommend option from the man pages.

**Comment by trapexit** [comment]
No one else has reported this issue. As the docs indicate if there are errors they will be ignored if anything in the process succeeded. Without hard_remove it's possible that a removal of a directory will fail because FUSE is doing an async removal of the files inside the directory.

If that is the issue the solutions are to use hard_remove, a non-path preserving policy, or ignorepponrename=true.

**Comment by heymoe** [comment]
Just an update: I've been running with `hard_remove` for a while now and everything seems to be working without any noticeable problems / side-effects.

**Comment by trapexit** [comment]
Okay. Great. I'll add a note to the docs about it in case others run into it.
