### ISSUE TITLE
Error when creating a new file or directory in a existing directory that is not on the target disk

### ISSUE THREAD

**Issue by irate-badger** [trapexit/mergerfs#467]
General description
===================
This is on Ubuntu 17.10, on the bundled version of mergerfs.
```
> mergerfs -v
mergerfs version: 2.21.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

I appear to be getting the same errors as:

> https://github.com/trapexit/mergerfs/issues/358

When creating a new file:
```
> touch file
touch: setting times of 'file': No such file or directory
```
Or a directory:
```
> mkdir example
mkdir: cannot create directory ‘example’: Operation not permitted
```

I am using mfs for my create option. In fact I use this command.
```
mergerfs -o minfreespace=4G,defaults,allow_other,category.create=mfs,func.getattr=newest /mnt/example/\* /srv/example
```

To create an example folder that I'll be exporting as a shared folder.

The folders all have the correct permissions. I have run chown -R irate-badger:users /mnt/example to confirm this.

Expected behavior
=================

When creating a file or folder, the disk with the most free space is used. If I have two disks sda and sdb that are spanned with mergerfs the first file will go on sda and the second on sdb.

Actual behavior
===============
If there are directories involved that are not on both disks then mfs fails. For example, `sda` has a folder `example` in the root that `sdb` does not. When mergerfs creates the unified view the merged mount point displays a single folder `example`. If `sdb` is larger than `sda` then creating a file inside `example` mergefs will attempt to create the file on `sdb`. `sdb` does not contain the folder `example` and fails to create the file. This appears to require the combined locations to be on separate disks/partitions rather than combining two folders as the behaviour requires the disks to be actual different sizes.

**Precise** steps to reproduce the behavior
===========================================

I apologise if this is noted anywhere, but I would want my files to be spread over the disks hence the mfs option is being used. This does require two disks and having one be the preferred disk (as it has more free space), but lacking folders that the disk with less space has.
In this example both disks are the same size.

```
mkdir -p /mnt/disks/sdb1
mkdir -p /mnt/disks/sdc1
mnt /dev/sdb1 /mnt/disks/sdb1
mnt /dev/sdc1 /mnt/disks/sdc1
mergerfs -o minfreespace=4G,defaults,allow_other,category.create=mfs,func.getattr=newest /mnt/disks/\* /srv/mergerfs

mkdir /mnt/disks/sdb1/foo
dd if=/dev/zero of=/mnt/disks/sdc1/file.txt count=1024 bs=1024
dd if=/dev/zero of=/srv/mergerfs/foo/file.txt count=1024 bs=1024
dd: failed to open '/srv/mergerfs/foo/file.txt': Operation not permitted
```

If doesn't appear to be replicating the directory structure as described in the README.md to the other drives that do not have this folder, but should be taking this new file.

**Comment by irate-badger** [comment]
Updated to latest git:

```
mergerfs version: 2.23.1-14-gdb27a91
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

Mergerfs was not running as root, as both the source and destination locations are rw by the logged in user. 

It appears that the issue was that I was not running this as root, running as my user still encounters this issue. I misunderstood the point:
> Safe to run as root

As meaning that running as root was optional, as such I still consider this a bug that users which do not have root access will encounter. Both underlying disks are ext4:

```
➜   mount
...
/dev/sdb1 on /mnt/example/sdb1 type ext4 (rw,relatime,data=ordered)
/dev/sdc1 on /mnt/example/sdc1 type ext4 (rw,relatime,data=ordered)
sdb1:sdc1 on /srv/mergerfs type fuse.mergerfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions,allow_other)
```
Permissions, I chowned everything to be accessible by my user and the users group on the mount points before running mergerfs. My local user can touch files on both mounted disks, and create directories:
```
➜  / users
irate
➜  / groups
irate adm cdrom sudo dip plugdev lpadmin sambashare docker users
➜  / cd /mnt/disks
➜  disks ls -ltra
drwxr-xr-x 4 root        root   4096 Feb 24 19:56 .
drwxr-xr-x 5 irate       users  4096 Feb 25 18:33 sdb1
drwxr-xr-x 3 root        root   4096 Feb 25 20:04 ..
drwxr-xr-x 6 irate       users 12288 Feb 25 20:13 sdc1

➜  nas cd sdc1
➜  sdc1 ls -ltra
drwx------ 2 irate       users   16384 Feb 24 19:55 lost+found
drwxr-xr-x 4 root        root     4096 Feb 24 19:56 ..
drwxr-xr-x 4 irate       users    4096 Feb 25 18:32 foo
-rw-r--r-- 1 irate       users 1048576 Feb 26 05:40 file.txt
drwxr-xr-x 5 irate       users    4096 Feb 25 18:33 .

➜  sdc1 cd example 
➜  example ls -ltra
drwxr-xr-x 5 irate       users       4096 Feb 25 18:33 ..
drwxr-xr-x 5 irate       users       4096 Feb 26 05:27 .

➜  .config cd ../../sdb1
➜  sdb1 ls -ltra
drwxr-xr-x 5 irate       users       4096 Feb 25 18:33 ..
drwxr-xr-x 5 irate       users       4096 Feb 26 05:27 .
➜  sdb1
```

The file system through mergerfs looks exactly how you would expect, displaying all files in both locations with the permissions set to irate:users with 755 on folders and 644 on the file.

**Comment by trapexit** [comment]
As the docs mention it's best to run as root because certain actions are only available with elevated privileges (such as certain aspects of cloning paths between drives). People do use mergerfs as non-root but permissions must be completely squared away. 

Can you strace mergerfs while performing the mkdir & touch. I suspect the issue would be in the cloning of paths where there is a balance between consistency and casual expectations.

**Comment by trapexit** [comment]
I think I may have found an issue which would manifest when not running as root. Let me fix it and then you can try that.

**Comment by irate-badger** [comment]
FYI - I don't mind running this as root, to be honest I had initially manually mounted it when I was playing about as a way to replace some excessive RAIDing, and it seems better than using LVM for the purpose. This is a great project, and thank you for putting your time into it! I can run strace to grab some logs later if you still need them.

**Comment by trapexit** [comment]
I did find an issue. It's trying to clone one directory below where it should in certain situations which when running as root you'd not notice. I'm guessing non-root (without proper permissions for that sub directory) is a rarity. I've a quick fix but I'll probably do the better fix and put out a new release. In a couple days.
