### ISSUE TITLE
rm: fts_read failed: No such file or directory when removing a large directory structure

### ISSUE THREAD

**Issue by VinzNL** [trapexit/mergerfs#468]
General description
===================
In certain cases when trying to recursively remove a large directory structure it fails part-way through. 
Running the rm or find -delete command over and over again eventually removes everything.

Expected behavior
=================
All files should be removed in one go.

Actual behavior
===============
This error is thrown part-way through:
rm: fts_read failed: No such file or directory

**Precise** steps to reproduce the behavior
===========================================

Warning: this test tries to consumes over 400k inodes and will take a while to run!

root@ur-quan:/share# mkdir test
root@ur-quan:/share# cd test
root@ur-quan:/share# for i in `seq 1 10`; do mkdir $i; for j in `seq 1 10`; do mkdir $i/$j; for k in `seq 1 10`; do mkdir $i/$j/$k; for l in `seq 1 10`; do mkdir $i/$j/$k/$l; for m in `seq 1 10`; do mkdir $i/$j/$k/$l/$m; for n in `seq 1 3`; do touch $i/$j/$k/$l/$m/$n; done; done; done; done; done; done
root@ur-quan:/share# cd ..
root@ur-quan:/share# rm -rf test
rm: fts_read failed: No such file or directory
root@ur-quan:/share# find test | wc -l
141586
root@ur-quan:/share# rm -rf test
rm: fts_read failed: No such file or directory
root@ur-quan:/share# find test | wc -l
30475
root@ur-quan:/share# rm -rf test
root@ur-quan:/share#

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
mergerfs version: 2.23.1
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
UUID="61e6fa14-668c-4f46-80aa-b186540415b8"     /media/disk2    ext4    defaults,relatime       0 2 #data1
UUID="f3745de8-b2aa-4a66-bde2-cc4064697a8b"     /media/disk4    ext4    defaults,relatime       0 2 #data2
UUID="fff8f360-cc5f-49f3-86b2-05432b087139"     /media/disk5    ext4    defaults,relatime       0 2 #data3
/media/disk2/merge:/media/disk4/merge:/media/disk5/merge        /share  fuse.mergerfs   defaults,allow_other,direct_io,use_ino,minfreespace=10G,moveonenospc=true,ignorepponrename=true,fsname=share,func.mkdir=lus,category.search=newest  0 0

* [x] Linux version: `uname -a`
Linux ur-quan 4.14.0-3-686-pae #1 SMP Debian 4.14.17-1 (2018-02-14) i686 GNU/Linux

* [x] Versions of any additional software being used
Debian testing with mergerfs from Debian experimental

* [x] List of drives, filesystems, & sizes: `df -h`
Filesystem      Size  Used Avail Use% Mounted on
/dev/sde        372G  343G   29G  93% /media/disk5
/dev/sdb        372G  344G   29G  93% /media/disk2
/dev/sdd        372G  343G   29G  93% /media/disk4
share           1.1T  1.1T   86G  93% /share

* [x] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [x] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
See attachments.
[app.strace.txt.gz](https://github.com/trapexit/mergerfs/files/1766618/app.strace.txt.gz)
[mergerfs.strace.txt.gz](https://github.com/trapexit/mergerfs/files/1766619/mergerfs.strace.txt.gz)

**Comment by trapexit** [comment]
Try using the 'hard_remove' option.

**Comment by VinzNL** [comment]
That does seem to fix the issue. Good to know it's a fuse problem and not a mergerfs problem! I don't think hard_remove will be a problem on a mount with fairly static media files, so I'll leave it enabled permanently.

**Comment by trapexit** [comment]
I'll be adding a note in the docs about this shortly. Somehow no one has run into this (or at least mentioned it) over the past couple years yet two have reported it recently.
