### ISSUE TITLE
change permissions 

### ISSUE THREAD

**Issue by polearnik** [trapexit/mergerfs#476]
Hi 
I try to use mergerfs  to merge 9 disks  of 9 different servers in one big used for owncloud.
 8 disks are connected through sshfs  and merge with command 
```
mergerfs -o defaults,allow_other,use_ino,minfreespace=10G /home/user/server1:/home/user/server2.... /home/user/owncloud-data
```
the problem is in different users for use. Disk is mounted as user  but owncloud read/write files as www-data . So owncloud cant upload any files on this  bit disk.

What is the best solution?  I need to change permissions for  write or to change user. For now permissions is drwx------ user user

**Comment by trapexit** [comment]
Yes. Permissions need to be in alignment. mergerfs enforces standard entitlements.
