### ISSUE TITLE
many stat calls on NFS - extreme slowdown for 4 KB writes?

### ISSUE THREAD

**Issue by 7eggert** [trapexit/mergerfs#479]
General description
===================

I'm hunting down a mergerfs / mhddfs caused slowdown from 30 MB/s to 200 kb/s. Using some strace, i found a possible cause:

mergerfs is stating each possible link on each 4KB write. Even though I THINK it should be cached locally, I consider this to be a possible cause.

Expected behavior
=================
If the file is open and the descriptor is valid, use that

Actual behavior
====
<pre><code>
[pid  5734] <... lstat resumed> {st_mode=S_IFREG|0644, st_size=257363006, ...}) = 0
[pid  5734] lgetxattr("/mnt/nas5a/mhddfs_data13/incoming/mov/!Mediathek/Entdeckung der Welt - Natur und Tiere - Die Kunst der Anpassung - Die Namib-W\303\274ste.mp4", "security.capability", 0x0, 0) = -1 EOPNOTSUPP (Operation not supported)
[pid  5734] writev(3, [{"\20\0\0\0\241\377\377\377\225\311\4\0\0\0\0\0", 16}], 1) = 16
[pid  5734] read(3, "..., 135168) = 1042
[pid  5734] pwrite(4, ..., 962, 257363006) = 962 ←write to file
[pid  5734] writev(3, ..., 2) = 24
[pid  5734] read(3, ..., 135168) = 3214
[pid  5734] pwrite(4, ..., 3134, 257363968) = 3134 ←write to file
[pid  5734] writev(3, ..., 2) = 24
[pid  5734] read(3, ..., 135168) = 68
[pid  5734] lstat("/mnt/nas13a/mhddfs_data13/foo", 0x7f87e4a7f220) = -1 ENOENT (No such file or directory)
[pid  5734] lstat("/mnt/nas13b/mhddfs_data13/foo", 0x7f87e4a7f220) = -1 ENOENT (No such file or directory)
[pid  5734] lstat("/mnt/nas13c/mhddfs_data13/foo", 0x7f87e4a7f220) = -1 ENOENT (No such file or directory)
[pid  5734] lstat("/mnt/nas13d/mhddfs_data13/foo", 0x7f87e4a7f220) = -1 ENOENT (No such file or directory)
[pid  5734] lstat("/mnt/nas5a/mhddfs_data13/foo",  <unfinished ...>
===========
</code></pre>

**Precise** steps to reproduce the behavior
===========================================

1) Have two arm-powered NAS with six disks, each exported individually
2) mount as described below
3) Have a program write a file in 4 KB blocks (stupid but that's what it does)

System information
==================

<pre><code>
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.3
using FUSE kernel interface version 7.19

Linux be10 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

mount options NFS:

be13:/mnt/disk1/d1 /mnt/nas13a nfs rw,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.7.213,mountvers=3,mountport=1026,mountproto=udp,local_lock=all,addr=192.168.7.213 0 0

mount options mergerfs: 
13a/mhddfs_data13:13b/mhddfs_data13:13c/mhddfs_data13:13d/mhddfs_data13:5a/mhddfs_data13:5b/mhddfs_data13 /mnt/mergerfs_data13 fuse.mergerfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0

Filesystem                                                                                                 Size  Used Avail Use% Mounted on
be5:/mnt/HD/HD_b2/d1                                                                                       3.6T  2.9T  793G  79% /mnt/nas5a
be5:/mnt/HD/HD_a2/d2                                                                                       2.7T  1.5T  1.2T  56% /mnt/nas5b
be13:/mnt/disk1/d1                                                                                         1.9T  1.7T  152G  92% /mnt/nas13a
be13:/mnt/disk2/d2                                                                                         1.9T  1.8T   41G  98% /mnt/nas13b
be13:/mnt/disk3/d3                                                                                         1.9T  1.6T  253G  87% /mnt/nas13c
be13:/mnt/disk4/d4                                                                                         1.9T  1.4T  489G  74% /mnt/nas13d
13a/mhddfs_data13:13b/mhddfs_data13:13c/mhddfs_data13:13d/mhddfs_data13:5a/mhddfs_data13:5b/mhddfs_data13   14T   11T  2.9T  79% /mnt/mergerfs_data13

</code></pre>

**Comment by trapexit** [comment]
Mergerfs doesn't stat per write. The lstats are it searching for the file. Something else triggered that. It's the policy running. That only happens as defined in the docs. 

Can you provide a more thorough trace? What are your mergerfs options?

**Comment by 7eggert** [comment]
Sorry, the mergerfs options didn't copy:
/mnt/nas13*/mhddfs_data13:/mnt/nas5*/mhddfs_data13      /srv/mergerfs_data13    mergerfs        uid=1000,gid=100,defaults,allow_other,dropcacheonclose=true,minfreespace=300G,moveonenospc=true,use_ino,hard_remove,ignorepponrename=true,noauto 0 0

I simplified the test: Now I dd if=/dev/zero  to test.dd. As long as dd is running, I get the trace blow, as soon as I stop dd, it stops.

<pre><code>
[pid  5735] writev(3, [{"\20\0\0\0\241\377\377\377\364\34!\0\0\0\0\0", 16}], 1) = 16
[pid  5735] read(3,  <unfinished ...>
[pid  5734] <... read resumed> "P\20\0\0\20\0\0\0\365\34!\0\0\0\0\0^\27\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 4176
[pid  5734] pwrite(6, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096, 2441216) = 4096
[pid  5734] writev(3, [{"\30\0\0\0\0\0\0\0\365\34!\0\0\0\0\0", 16}, {"\0\20\0\0\0\0\0\0", 8}], 2 <unfinished ...>
[pid  5735] <... read resumed> "D\0\0\0\26\0\0\0\366\34!\0\0\0\0\0^\27\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 68
[pid  5735] lstat("/mnt/nas13a/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas13b/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas13c/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas13d/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas5a/mhddfs_data13/incoming/test.dd",  <unfinished ...>
[pid  5734] <... writev resumed> )      = 24
[pid  5734] read(3,  <unfinished ...>
[pid  5735] <... lstat resumed> {st_mode=S_IFREG|0644, st_size=2445312, ...}) = 0
[pid  5735] lgetxattr("/mnt/nas5a/mhddfs_data13/incoming/test.dd", "security.capability", 0x0, 0) = -1 EOPNOTSUPP (Operation not supported)
[pid  5735] writev(3, [{"\20\0\0\0\241\377\377\377\366\34!\0\0\0\0\0", 16}], 1) = 16
[pid  5735] read(3,  <unfinished ...>
[pid  5734] <... read resumed> "P\20\0\0\20\0\0\0\367\34!\0\0\0\0\0^\27\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 4176
[pid  5734] pwrite(6, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096, 2445312) = 4096
[pid  5734] writev(3, [{"\30\0\0\0\0\0\0\0\367\34!\0\0\0\0\0", 16}, {"\0\20\0\0\0\0\0\0", 8}], 2) = 24
[pid  5735] <... read resumed> "D\0\0\0\26\0\0\0\370\34!\0\0\0\0\0^\27\0\0\0\0\0\0\350\3\0\0\350\3\0\0"..., 135168) = 68
[pid  5734] read(3,  <unfinished ...>
[pid  5735] lstat("/mnt/nas13a/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas13b/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas13c/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas13d/mhddfs_data13/incoming/test.dd", 0x7f87e427e220) = -1 ENOENT (No such file or directory)
[pid  5735] lstat("/mnt/nas5a/mhddfs_data13/incoming/test.dd", ^CProcess 5733 detached
</code></pre>

**Comment by trapexit** [comment]
FUSE is requesting the stat. It doesn't appear to happen when using direct_io. I don't remember seeing this before. I'll need to talk with the fuse developers.

**Comment by trapexit** [comment]
I found that disabling xattrs also disables the stat per write. I was going to make it so you can turn off xattrs in general given it can harm performance but I don't understand why it getxattr's and stat's per write. I'll add the ability to disable xattrs in general which should address your problem but I'll still need to talk with the FUSE authors.

**Comment by trapexit** [comment]
Figured it out. The kernel is requesting security.capability. I just pass it through.

I could do a few things. 1) An option to disable all xattr. Side effect is that the ability to modify mergerfs at runtime would be lost. 2) Logically disable xattr by always returning some error (not ENOSYS... it will disable all future calls which would disable runtime changes. 3) Specifically short circuit "security.capabilities" getxattr's which would at least limit the call from being proxied over the wire.

Unfortunately there is no way to disable xattr per file or have the kernel cache the result over the course of the file being open.

**Comment by 7eggert** [comment]
Thanks.

More ideas:
4) You could filter xattr for not security.capability ← ugly hack
5) Compare the name to the list of open files and use that file handle
6) Cache the result for open files at least for some seconds
7) if 4 then 5 + 6

I don't know the exact options offered by the fuse library.

I think I'll just use direct_io for now - I avoided that suspecting that some of my programs will barf. (Not closing this issue for now?)

**Comment by trapexit** [comment]
4 is what I was referring to with 3. Not sure what 5 gives us besides working on the file handle rather than path. The high cost is in the ultimate request to the underlying filesystem. Not the path look up. It'd be nicer but really fuse should support file descriptor based xattr functions. Could do 6. On file open look for the security value at open and cache it. Problem is that the getxattr is not within the context of the open file. I don't have access to the file handle. Related to the problem with 5.

No matter what if xattrs are enabled there will be a cost to the constant reading. The choice is whether or not to forward the request. The easiest and probably the most practical given how few people use extended security capabilities is to have an option to turn that specific query off.

**Comment by 7eggert** [comment]
5 is: Do not call six NFS servers and possibly have another fs layer buffer the result.

Given your description and the strace, I imagine you could have a list of open fds and the associated name (or one per thread). OTOH one could rename that file, put another in place and gain access. But basically it's a FUSE ∕ kernel issue for issuing the call in the first place?

I agree that disabling security calls per mount is the best option for now and/or to mention  _really_ using direct_io on NFS shares, as this killed the network yesterday.

**Comment by trapexit** [comment]
For some FUSE calls there are versions which effectively are the stateful versions of the regulars. The fstat instead of stat. For whatever reason {get,list,set,remove}xattrs don't feature those same versions. I only have the path based ones. Meaning without a decent amount of complexity and overhead I can't guarantee the behavior as with the file descriptor versions where FUSE would provide me the state (which I previously created.)

Even if I had them the overhead would still probably harm performance to a significant degree according to other's who've run into this. They specifically respond ENOATTR when asked for security.capabilities but let anything else through. Its not ideal but its a decent enough compromise.

I'll add a note in the docs about this and make a change to allow short circuiting security.capabilities as well as disabling xattr all together.
