### ISSUE TITLE
Releases for Ubuntu 18.04?

### ISSUE THREAD

**Issue by sprat** [trapexit/mergerfs#483]
Sorry to hijack the template but this issue is more a question than a bug report.

Since mergerfs is now available in the Canonical repositories for Ubuntu 18.04, do you plan to provide up-to-date binary packages for this Ubuntu version?

Thanks for the hard work!

**Comment by trapexit** [comment]
Yes. I've just not gotten around to creating new build containers in order to make the packages. I'll try to do so soon.

**Comment by sprat** [comment]
That's cool, thank you!

**Comment by sprat** [comment]
Any progress?

**Comment by trapexit** [comment]
Not yet. You can use the xenial builds.

**Comment by guysoft** [comment]
Any way to give you a hand?

**Comment by trapexit** [comment]
You want me to build an old version of mergerfs for Bionic? What's wrong with the current version?
