### ISSUE TITLE
Value too large for defined data type error

### ISSUE THREAD

**Issue by lashgar** [trapexit/mergerfs#485]
General description
===================
I get the following error sometime when the compiler is reading files from mergerfs filesystem:
`cc1: error: /home/vmuser/work/dev/t202-3.20/ext/com/build/s2e/include: Value too large for defined data type`

This is the most close issue I could find in the web. It seems the error can be resolved if the filesystem is network mounted by passing `nounix,noserverino` mount flags: https://stackoverflow.com/questions/2438890/cc1plus-error-include-value-too-large-for-defined-data-type-when-compiling-wi

Is there equivalent flags in mergerfs?

Thanks.

System information
==================
Please provide as much of the following information as possible:

* [2.24.2-2-g4b1f9af ] mergerfs version: `mergerfs -V`
* [/media/SecondDisk/work/dev/:/home/vmuser/work/original-dev/ /home/vmuser/work/dev/  fuse.mergerfs  defaults,allow_other,use_ino,hard_remove  0       0 ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ Linux UBUNTU-14-LTS-AHMAD 3.13.0-145-generic #194-Ubuntu SMP Thu Apr 5 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux] Linux version: `uname -a`

**Comment by trapexit** [comment]
Is the compiler [not compiled for large file support](https://www.gnu.org/software/coreutils/faq/coreutils-faq.html#Value-too-large-for-defined-data-type)?

There isn't a way to turn off 64bit inodes but you could not use `use_ino`.

**Comment by lashgar** [comment]
Not so sure if the compiler is built to support large files or not. I am cross compiling for 32-bit ARM from my 64-bit x86_64. Removing `use_ino` solved the issue for now. Thanks.
