### ISSUE TITLE
not all paths in fstab get added to pool

### ISSUE THREAD

**Issue by nbonfire** [trapexit/mergerfs#486]
General description
===================
My fstab looks like this:
`/mnt/disk1:/mnt/disk2:/mnt/disk3/gh:/mnt/disk4/gh /storage fuse.mergerfs direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs 0 0`

The last two paths don't get added to pool:

``` 
nickb@home  ~ 04  sudo xattr -l /storage/.mergerfs 
                                                                                            
user.mergerfs.srcmounts: /mnt/disk1:/mnt/disk2
```

If I `xattr -w user.mergerfs.srcmounts '+>/mnt/disk3/gh:/mnt/disk4/gh' /storage/.mergerfs` 

they show in the xattrs and the files are visible in the pool.

**Precise** steps to reproduce the behavior
===========================================

I have 4 disks, disks 3 and 4 have all the files in a subdirectory (legacy data).

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: 

mergerfs version: 2.18.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments

`/mnt/disk1:/mnt/disk2:/mnt/disk3/gh:/mnt/disk4/gh /storage fuse.mergerfs direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs 0 0`

* [ ] Linux version: `uname -a`

Linux home 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

* [ ] List of drives, filesystems, & sizes: `df -h`

mergerfs         22T   18T  3.4T  84% /storage
/dev/sde1       7.3T  3.8T  3.2T  55% /mnt/disk1
/dev/sdb1       7.3T  6.9T   48G 100% /mnt/disk2
/dev/sdd1       3.6T  3.3T  115G  97% /mnt/disk4
/dev/sdc1       3.6T  3.4T   98G  98% /mnt/disk3

**Comment by trapexit** [comment]
It's likely the mount ordering. I imagine the latter two aren't mounted when mergerfs is mounted. It's being asked to mount something which doesn't exist.

**Comment by nbonfire** [comment]
thanks, that makes sense. i'll try making a systemd file for the mount then
