### ISSUE TITLE
use_ino option causes mount directory to be completely empty

### ISSUE THREAD

**Issue by jeffgt14** [trapexit/mergerfs#490]
General description
===================
Very odd behavior. If I try to use the “use_ino” mount option, my /mnt/storage will not display anything in Nautilus nor the terminal as both user and root. The odd thing is, the folders are there somewhere because I can “cd /mnt/storage/Music” and it’ll advance to the directory but ls won’t display anything ever. I can also create a file in /mnt/storage and go browse /mnt/data and find it in one of my drives. If I remove the “use_ino” option, everything works great.

Expected behavior
=================
Mounting drivepool via fstab or mount should display contents in /mnt/storage

Actual behavior
===============
/mnt/storage does not display anything in Nautilus or Terminal.

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.13.1
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
/mnt/data/* /mnt/storage fuse.mergerfs defaults,direct_io,allow_other,use_ino,minfreespace=15G,fsname=mergerfs,func.getattr=newest 0 0

* [ ] Linux version: `uname -a`
Linux xxxxxx-server 4.4.0-130201807041620-generic #0+mediatree+hauppauge-Ubuntu SMP Thu Jul 5 03:28:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* [ ] List of drives, filesystems, & sizes: `df -h`
Filesystem Size Used Avail Use% Mounted on
udev 7.7G 0 7.7G 0% /dev
tmpfs 1.6G 38M 1.6G 3% /run
/dev/sdc2 103G 87G 11G 90% /
tmpfs 7.7G 6.2M 7.7G 1% /dev/shm
tmpfs 5.0M 4.0K 5.0M 1% /run/lock
tmpfs 7.7G 0 7.7G 0% /sys/fs/cgroup
/dev/sde 2.7T 2.6T 17G 100% /mnt/data/HDDSG1
/dev/sdc1 94M 189K 94M 1% /boot/efi
/dev/sda 2.7T 2.6T 16G 100% /mnt/data/HDDWD1
/dev/sdb 2.7T 2.6T 17G 100% /mnt/data/HDDSG2
/dev/sdd 2.7T 2.6T 0 100% /mnt/parity/HDDWD2
tmpfs 1.6G 88K 1.6G 1% /run/user/1000
mergerfs 8.1T 7.7T 49G 100% /mnt/storage

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/#tips--notes
```
use_ino will only work when used with mergerfs 2.18.0 and above.
```

From above:
```
mergerfs version: 2.13.1
```
