### ISSUE TITLE
Cannot create files using windows 7 samba client

### ISSUE THREAD

**Issue by SenorSmartyPants** [trapexit/mergerfs#500]
General description
===================
Cannot create files (or copy existing files on local windows drive ro mergerfs) using windows 7 samba client

Expected behavior
=================
Files should create or be copied.

Actual behavior
===============
"File Too Large" error dialog
"The file 'New Text Document.txt" is too large for the destination file system"
this is with a 0 byte txt file.

**Precise** steps to reproduce the behavior
===========================================
Open samba mergerfs share. Right click to create new text file. Or copy existing file from C: to file share.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.18.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
LABEL=media1TB    /mnt/media1TB     ext4    defaults,noatime 0       0
LABEL=elements3TB /mnt/elements3TB  ext4    defaults,noatime 0       0

/mnt/media1TB:/mnt/elements3TB     /mnt/storage     fuse.mergerfs direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs 0 0

* [ ] Linux version: `uname -a`
Linux nanners 4.14.18-sunxi #24 SMP Fri Feb 9 16:24:32 CET 2018 armv7l GNU/Linux
* [ ] Versions of any additional software being used
Samba
https://hub.docker.com/r/dperson/samba/
* [ ] List of drives, filesystems, & sizes: `df -h`
Filesystem      Size  Used Avail Use% Mounted on
udev            433M     0  433M   0% /dev
/dev/mmcblk0p1  7.0G  6.8G  123M  99% /
mergerfs        3.6T  2.1T  1.6T  57% /mnt/storage
/dev/sda1       917G  279G  638G  31% /mnt/media1TB
/dev/sdb1       2.7T  1.8T  950G  66% /mnt/elements3TB

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
Please use the most recent version of mergerfs.

You're really not giving me enough information to comment further. Samba and mergerfs is used together widely without issue. Especially if you're using docker you're going to need to be very careful about entitlements.

**Comment by SenorSmartyPants** [comment]
I'll upgrade, didn't know I wasn't running the most recent. Debian stable is a bit behind.

I'm not sure what you mean regarding docker and entitlements.

**Comment by trapexit** [comment]
Containers typically run with different user namespaces. You have to pick what uid & gid the container runs as. Samba is likely changing roles as well. You have to ensure that directories are permissioned correctly for the user reading.

**Comment by SenorSmartyPants** [comment]
Ah, yes. Thank you, I'll do some debugging in that area.

**Comment by SenorSmartyPants** [comment]
Not sure why yet, samba would behave differently between mergerfs and ext4 volumes if it was a UID issue. But I'll keep it in mind.

**Comment by trapexit** [comment]
Just go into the container, running as the same user as samba, and see if you can interact with the mergerfs volume passed in. 

Samba has it's own set of complex'ish behaviors regarding uids. As does mergerfs. As does using containers. It's pretty easy to get something out of sync.

**Comment by SenorSmartyPants** [comment]
Finally got around to upgrading mergerfs to 2.24.2. 

That seemed to fix my samba related issues described above.

Thanks for the help and this cool piece of software.
