### ISSUE TITLE
Confusing “double caching” wording in README

### ISSUE THREAD

**Issue by Artefact2** [trapexit/mergerfs#501]
Quoting the README:

    * direct_io: […] direct_io will cause double caching of files and therefore less memory for caching generally (enable dropcacheonclose to help with this problem).
    * dropcacheonclose: […] Recommended when direct_io is not enabled to limit double caching. (default: false)

Seems to me that it's contradicting itself there? Seems to imply `direct_io` enabled and disabled cause double caching issues?

**Comment by trapexit** [comment]
You misquoted the README. `direct_io` says `not enabling direct_io will cause ...`

**Comment by Artefact2** [comment]
Heh, can't believe I failed to read that correctly multiple times. Sorry for the noise and thanks for pointing it out!
