### ISSUE TITLE
[user case] mergerfs for fast reads from read-only and slow writes to rw layer

### ISSUE THREAD

**Issue by lavdnone** [trapexit/mergerfs#502]
I have two mounts with same files (which sync on background).
One is slow network one another is local folder.

Idea is to have reads done from local folder and writes to be done on slow network one (for proper sync).

Lets say I make local read-only with bind mount and then merge it with remote:
```
    mount /localfiles /localfilesro -o bind
    mount /localfilesro -o remount,ro,bind
    mergerfs -o defaults,allow_other,minfreespace=10M /localfilesro:/remotefilesrw /tmp/merge
```

As /localfilesro is first I assume it will choose it for read operations:
`    cp -r /tmp/merge/somefolder /somewhere/somefolder`
will give me performance of 
`    cp -r /localfiles/somefolder /somewhere/somefolder`

If I will write to it 
`    cp -r /somewhere/somefolder /tmp/merge/somefolder `
it will do, in my case, slow
`    cp -r /somewhere/somefolder /remotefilesrw/somefolder `

Also if it will be an issue that /remotefilesrw is a fuse mount?

Thanks!

**Comment by lavdnone** [comment]
Already some results.
Wonder why it doubled time just on bind mount. Looks like there is almost no loss from bind mount to mergerfs on read.
Maybe there is also some way to save those 40 seconds on wright through merged by tuning fuse.mergerfs params?

mergerfs and bind ro mount read:
```
[rose@vin ~]$  date &&  cp -r /home/rose/t01merge/cur ./ && date
Fri Sep 14 00:59:36 EDT 2018
Fri Sep 14 00:59:41 EDT 2018
[rose@vin ~]$  date &&  cp -r /home/rose/t01ro/cur ./ && date
Fri Sep 14 01:00:06 EDT 2018
Fri Sep 14 01:00:11 EDT 2018
```

Direct local:
```
[rose@vin ~]$  date &&  cp -r /home/rose/main/testbr/t01/cur ./ && date
Fri Sep 14 01:01:04 EDT 2018
Fri Sep 14 01:01:06 EDT 2018
```

Remote:
```
[rose@vin ~]$  date &&  cp -r /home/rose/t01/cur ./ && date
Fri Sep 14 01:01:38 EDT 2018
Fri Sep 14 01:02:03 EDT 2018
```

Writes and read backs:
```
[rose@vin ~]$  date &&  cp -r ./cur /home/rose/t01/cur2 && date
Fri Sep 14 01:03:28 EDT 2018
Fri Sep 14 01:07:03 EDT 2018
[rose@vin ~]$  date &&  cp -r ./cur /home/rose/t01merge/cur3 && date
Fri Sep 14 01:07:34 EDT 2018
Fri Sep 14 01:11:44 EDT 2018
[rose@vin ~]$  date &&  cp -r /home/rose/t01merge/cur2 ./ && date
Fri Sep 14 01:13:08 EDT 2018
Fri Sep 14 01:13:16 EDT 2018
[rose@vin ~]$  date &&  cp -r /home/rose/t01ro/cur3 ./ && date
Fri Sep 14 01:13:29 EDT 2018
Fri Sep 14 01:13:33 EDT 2018
```

**Comment by trapexit** [comment]
Why not use "time" for checking the length of time cp takes?

I'm not entirely sure what you're asking vs stating. If you want creates to happen on the remote drive you can set the create policy to something which would select it and set the open policy to something which would select the local.

Bind mounts are logical, not physical. There should be no difference in performance. You have to make sure to clear filesystem caches between tests otherwise the OS may be holding on to the data in caches which would fool with the results.

**Comment by lavdnone** [comment]
Guess it was too soon.
When saving file changes get "Read-only file system." message.
Guess it happens because it is opened (read) from the first layer which is read-only.
When I save I need it to save to available non ro layer - which is second one in my case.
Though creating new files works fine.

**Comment by lavdnone** [comment]
Tried adding cache wr dir as a front layer, same result. When saving file says Read-only file system.

df shows it:
`ro:                    fuse.mergerfs    30T  5.6T   24T  19% /home/rose/t01merge`

**Comment by trapexit** [comment]
Creates and open/write are two different behaviors. If the file already exists local and is opened for write you'll get that error. 

mergerfs doesn't write to multiple locations. If you're going to mirror between local and remote you have to do it out of band.

I'm still not clear what you're trying to accomplish.

**Comment by lavdnone** [comment]
Same exact result with aufs "Read-only file system." 
`mount -t aufs -o br=/home/rose/t01ro=ro:/home/rose/t01=rw -o udba=reval  none /home/rose/t01merge`

**Here is what I am trying to achieve:**
I simply need all reads to be done from 1st no matter what, and all writes being done to 2nd no matter what. Never read anything from 2nd. Effectively separating read and write operations to different locations.

**What I expect to happen from the setup above:**
- 2 layers: 1st read-only 2nd writable (In my case both locations are identical clones but one is fast another is slow. Locations are being synchronized on a background on their own.)
- 1st is always shown
- when file is open - always opened from 1st
- if file is changed and exists on 1st or 2nd - it is just overwritten to 2nd
- if same file being opened 1 second later it gets opened from 1st again

As 1st is read-only mergerfs figures out to write to 2nd writable one.
**But it only works with new files.**
If file exists on 1st or 2nd Instead of throwing "Read-only file system." it just needs to do the same - wright it to first available writable layer, overwriting it if needed.

I don't see why it can't do that as default logical behavior - if it needs to write - no point in throwing error if there is a writable layer that can be used.

**Comment by trapexit** [comment]
> I don't see why it can't do that as default logical behavior

mergerfs doesn't have layers. It's not a layered filesystem. It's a union filesystem. What to act on is based on ordering and policy logic as defined in the docs.

Reads and writes aren't independent operations from open and create. (They could be with a massive overhead but I've not written mergerfs that way.) A read and write can only happen after a open or create. Doing what you want would require adding some filter to open policies based on whether or not writing was requested.

> But it only works with new files.

Yes, because open and create are done first and you have different policies which target different drives. Once the file is already existing on the RO drive it will use open policy to find it. Not create. Since the drive is read only it fails to write.

I still don't understand why you sync from slow to fast. This could all be addressed if you simply reversed the sync direction. Why not write to local and sync remote rather than write remote and sync local?

I could change the code to ignore readonly devices for opens but that will complicate the code. Policies are not specific to commands so I'd need to recreate every single policy just for open.

**Comment by lavdnone** [comment]
Thanks for reply.

It's not that I am syncing from slow to fast on purpose - the sync itself makes the node slow and the absence of such keeps it fast:
Underlying is GlusterFS cluster through number of servers and locations. Each write operation goes out to many nodes and is not closed until finished. Read does the same to check file consistency - even though it then reads local, for many-small-file load it is a disaster. Imagine fuse + network latency attr checks. (_Slow mount_)
Each node has file storage where files reside as a regular file system or at least can be made accessible that way in most cases. Access is fast and simple. (_Fast mount_)

If files need to be modified - we need to go through _Slow mount_, so files will be populated to cluster and consistency preserved.
Read only apps fly on Fast mount, but changes to _Fast mount_ will not go to cluster (well unless files explicitly queried and trigger _heal_ sync procedure).

I understand what you are saying about Open - Read - ... chain and if it is opened from one place it will take effort to break the chain and write it somewhere else.

If somehow we can make it to work I am sure many people in Gluster community will be very happy, as it is a constant struggle to get performance back from cluster.
It was very promising until it failed to write existing file skipping ro mount.

Maybe separate mount option like _skiprowrite_ for this case. I can test it on load after and push to community as a solution.

**Comment by lavdnone** [comment]
`create` policy appears to be working as needed executing it on first available rw mount.
Indeed, open /w write might need its own `create` version of the `open` policy, enabled with some mount option, as it still need to get content from (first ro) _Fast mount_ and but save it to (next rw) _Slow mount_ 
Like when you open file, edit and save it to different location. First that initially came to mind is catch it on save and direct properly.

How about overwrite existing files? Even if it exists it needs to be written to first wr - might need another mount option.

ps. tried mhddfs and unionfs just now - didn't work. mergerfs is the only hope

**Comment by lavdnone** [comment]
How about if put rw _Slow mount_ first and ro _Fast mount_ second and somehow make all file lookups fail on wr _Slow mount_ even though it is first. It will find no file on 1st rw and open file from 2nd ro, saving it to 1st rw, as it intend to do initially by design.
Mount option can be something like `skiplrwookup` disabling ability to find if file is there on all rw mounts.
Might be much easier then previous suggestion.

**Comment by trapexit** [comment]
> How about overwrite existing files?

What existing files? The ones on RO? You won't be able to do that. mergerfs is not a layering filesystem and I'm not interested in making it one. The only way it'd work is if the file were opened on remote, rewritten there, and sync'ed down by glusterfs for later use by something opening it read only.

All policies are shared across categories. Anything that would be specific to a function would lead to specific policies for that function. Any change has to be useful across the category. If the search policies simply skipped rw mounts it would lead to a strange behavior if it doesn't effectively do the same policy without that set after a failure to find a file. Having all that code for a very bespoke usage isn't ideal.

Preferably this kind of thing would be supported by glusterfs rather than layering another filesystem on top. I'm not opposed to accommodating the situation but I don't want to make a very invasive change for 1 person.

**Comment by lavdnone** [comment]
>>    How about overwrite existing files?
> What existing files? The ones on RO? 
No to RO, to the second RW. When I copy files to mergerfs, and they exist on RO - it tries to wright then to RO, instead of RW - that is what I am trying to fix here.

Lets keep it simple. mergerfs already has 99% of what is needed:
Sticking to last suggestion which currently provides this functionality:
```
[folder1] RW    [folder2] RO
 |- File1         |- File1
 |-               |- File2
 |- File3         |- File3
   |- subfol1       |- subfol1
     |- File4         |- File4
     |-               |- File5
```
(1) If File2 or File5 is accessed - it is read from the first available location `folder2`, when saved it is put to `folder1`
(2) When File1 File3 File4 is accessed - it is opened from the first available location `folder1` and saved to `folder1` after.

Now, if mount option `norwsearch` is enabled existing files on RW folder `folder1` are simply ignored:
(1) Stays the same
(2) When File1 File3 File4 is accessed - it is opened from the first available location **skipping RW** `folder2` and saved to `folder1` after as done in (1).

From the logic of it simply `making all file lookups skip RW mounts` will do the thing.

(I actually tried hiding files for read access on folder1 by using bindfs removing read permissions --perms=a-r but it affects folders as well making it non browsable)

**Could be a number of user cases:**
- Keep part of merged fs RO - for example if you always want to see files on CD as they are, and keep changes (hidden) just in case. 
- Or keep change attempts hidden on purpose to monitor what intruder was attempting to change on your file system: those changes will be kept on folder1 even though will have no effect on the merged mount.
- For the purpose of strict multi-path setup. Say you have 10G and 100M link to storage and you have read intensive application. Put RW 100M mount for writes and 10G mount for reads.
- I am 100% sure that I am not alone in Gluster community trying to return some speed by complicating setup.

ps. Glusterfs is focusing on making fs for local enterprise SAN storage - when you have 10Gb separate network to your storage in your server room, and that is all you need, works like a charm. There is geo-replication feature which is not any good so far, with 1 to 1 sync limitations, so you need to create pares off all of your 10 node cluster etc. Honestly, feels like its better for Gluster guys to focus on what their fs does. And as mention mergerfs already has 99% what is needed.

**Comment by lavdnone** [comment]
Ah going through code and tests with mergerfs I see that it just directs wrights to the proper tree.
If file opened from regardless RW or RO it will be worked with the home branch of the file, and if it is RO error out.
Sorry for confusing you. It is something like cow_down I am looking for, but in mergerfs you don't need even regular cow, mergerfs designed to do different thing all together.

**Comment by lavdnone** [comment]
If someone will get here with same request, here is production build of unionfs for such setup.
https://github.com/lavdnone/unionfs-fuse/
