### ISSUE TITLE
Mergerfs directory not accessible in LXD container. ls returning - cannot access 'data': No such file or directory

### ISSUE THREAD

**Issue by coryrwest** [trapexit/mergerfs#508]
General description
===================
mergerfs directories are not accessible inside LXD containers without global read and execute permissions.

I understand that this issue is quite complex and I have a workaround so by no means is this a huge priority. It just makes using mergerfs with LXD a little complicated.

Expected behavior
=================
`ls` to list the directory with the correct permissions and accessible.

Actual behavior
===============
I have simplified this as much as I can. I have a mergerfs volume that does not have any other issues with my system. I create a new LXD container (targeting Ubuntu Xenial, though I have tried Alpine with the same issue) and mount my mergerfs directory. I have an raw.idmap set to map my user on the host (1001) to the user in the container (1000). When I ssh into the container the directory cannot be accessed. Below is what I receive with `ls`:

Alpine:
```
ls: ./baddata: No such file or directory
```

Ubuntu:
```
ls: cannot access 'library': No such file or directory
       ? ? d?????????   ? ?      ?          ?            ? baddata
```

I have narrowed the problem down to permissions. I am not sure if I am doing something wrong or if there is actually a bug. Assuming the following file structure on the host in mergerfs (with permissions specified, using uid and gid for simplicity):
```
/main - rwxrwxr-x 1001:1001
  /files - rwxrwx--- 1001:1001
    ... lots of files - rwxrwx--- 1001:1001
```
When mapped to the container using the below command, the files directory become inaccessible:
`lxc config device add containername baddata disk source=/main/files path=/baddata`

If I change the permissions on `files` to `rwxrwxr-x` it will map correctly. Also, if I map `main` instead of `files` it will also work correctly. It is only when I directly map the directory that has the bad permissions.

**Precise** steps to reproduce the behavior
===========================================
 - Start with new Debian Stretch install
 - Install snap from apt
 - Install LXD from snap
 - Create a mergerfs volume using options below
 - Make a directory `main` owned non-root user and assign `rwxrwxr-x` permissions
 - Make a subdirectory in `main` owned non-root user and assign `rwxrwx---` permissions
 - Make a new ubuntu container
 - Use `raw.idmap` to map the host user to the container user
   - `printf "uid {hostuid} {containeruid}\ngid {hostgid} {containergid}" | lxc config set containername raw.idmap -`
 - Create a new device on that container mounting the bad directory.
  - `lxc config device add containername baddata disk source=/main/files path=/baddata`
 - ssh to the container and attempt to `ls` the directory

System information
==================
Version of mergerfs: 
```
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

mergerfs settings:  `defaults,allow_other,use_ino,dropcacheonclose=true,moveonenospc=true,category.create=epmfs,minfreespace=100G,nonempty`

Version of Linux: 
`Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`

Versions of any additional software being used: 
`The LXD snap tracking the stable channel, currently version 3.5`

List of drives, their filesystems, and sizes (before and after issue):
```
/mnt/data/sdc          920G 
/mnt/data/sdb          920G
/mnt/data/sde          532G
```
All drives are encrypted with LUKS and formatted with BTRFS.

**Comment by trapexit** [comment]
It's possible there is an issue with user translation and FUSE but I'm not familiar with how FUSE manages user namespaces.

I've not used lxd but I'll see what I can find when I have the cycles. I'd suggest stracing mergerfs when performing the `ls` to see what uid it's changing to and what the opendir or similar error is being returned.

**Comment by trapexit** [comment]
Any update? I'm happy to add something to mergerfs to help if it makes sense but if this is just a permission issue I'd prefer to close this ticket.

**Comment by coryrwest** [comment]
You can close this. I found a workaround that works reasonably well and don't have the time right now to investigate further. I just wanted to make sure that there was a record of an issue like this for if/when someone else has this issue.

**Comment by coryrwest** [comment]
@fmoledina I ended up mounting the directory above the one I wanted with more permissive permissions. The sub-directory (the one I original wanted to mount) will be accessible and mounted correctly with the correct permissions. It will just be one level deeper, which isn't ideal, but solved my problem.

**Comment by fmoledina** [comment]
Interesting. So I understand it, the 'sub-directory' is the actual mergerfs mount point? And you needed to mount the directory one level up as a 'disk' device in the LXD container?

**Comment by coryrwest** [comment]
Not quite. The mergerfs mount point in my case is at the root `/data` and the folder I wanted to mount in the LXD container was two or three levels down (something like `/data/documents/backup/lxd`). I wanted to mount `lxd` as the disk device but couldn't, so I just mounted `backup` which had more permissive permissions and it all worked.

All the folders above (`/data/documents/backup`) had `rwxrwxr-x` permissions and the `lxd` folder had `rwxrwx---` permissions.

**Comment by fmoledina** [comment]
Ah, I understand now. Well, I'll keep this info for posterity if I run into issues with mounting mergerfs points into my LXD containers. Thanks.
