### ISSUE TITLE
Mergerfs random crashes with SIGABRT

### ISSUE THREAD

**Issue by cycne** [trapexit/mergerfs#519]
Description
==================
When lot of reading/stat files , mergerfs exit
Strace attached. look at the end.

System information
==================
Kernel: 4.4.50-1.el7.elrepo.x86_64

[mergerfs.strace.txt_03.gz](https://github.com/trapexit/mergerfs/files/2499721/mergerfs.strace.txt_03.gz)
# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 

# mergerfs -V
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

# cat /etc/fstab 
/swap.img                                  swap                 swap           defaults        0 0
UUID=8983b55f-e7ec-401e-9de5-04ad985a4601  /                    ext4           defaults        1 1
UUID=8408d13e-4d8b-425e-a535-4c034d497416  /mnt/disks/1         ext4           defaults        1 2
UUID=f098d00a-6d33-4f50-b01c-f45eb9d8c811  /mnt/disks/2         ext4           defaults        1 2
/mnt/disks/*                               /mnt/storage         fuse.mergerfs  defaults,allow_other,direct_io,use_ino,hard_remove,category.create=epff,moveonenospc=true,minfreespace=100M,fsname=mergerfsPool  0       0
/mnt/mysql                                 /mnt/storage/mysql   none           defaults,bind 0 0

**Comment by trapexit** [comment]
I've never seen this before. What do you mean by " lot of reading/stat files "?

**Comment by cycne** [comment]
Thanks for response.
First of all, congratulations and thank you for developing and sharing this amazing tool.

I have a system in which multiple processes scan hundreds of files in a given directory tree, taking information from the creation date, size, among other things and keeping them updated in a database.
I realized that when I start the process, the mergerfs stopped after some time(Transport endpoint is not connected)  ...  so I was able to reproduce and generate the attached log.

Today I removed the "direct_io" option and I still had no problems. I'm watching..

**Comment by trapexit** [comment]
Could you create some simple script to reproduce the problem? Hundreds of people, including myself, use mergerfs quite extensively for years and I've never seen this. I need more info to track this down.

**Comment by cycne** [comment]
Until next weekend I'll try to create something generic that can reproduce the error.
I'll let you know. 
Thank you!!!

**Comment by cycne** [comment]
I tried to reproduce the error in another machine, but it didn't give error.
When I disabled the 'direct_io' option the error apparently stopped, but now , days later it came back.
Very strange because I have another server for months running the same kernel version and mergerfs without problems.
I let you know as soon as I get any information.
Thank you.

**Comment by cycne** [comment]
Generally these problems are pointed out in dmesg, messages, syslog and i don't saw errors in these logs. But I will investigate according to your suggestions.
Looking to the strace log, I checked that the error comes from libfuse: write (2, "fuse internal error: node 820748" ..., 43) , that refers to function get_node()  in fuse.c.
Unfortunately i don't have knowledge about internal working of libfuse to trace this , otherwise I could help more.

**Comment by trapexit** [comment]
Yeah, it means the node being requested is no found which should never happen. It's certainly possible that it's a bug within libfuse but it seems bizarre that over the years no one else has hit it. Are these other machines the exact same OS & kernel? Maybe try reproducing it in a VM?

**Comment by cycne** [comment]
Same OS, kernel and all versions of all   but different machines. I tryed to reprodice here in another machine, but no problems happened.
This is the closest I've seen about the issue:  https://github.com/libfuse/libfuse/issues/299
This week i will do more tests and i let you know.

**Comment by trapexit** [comment]
Ah... hmm... hadn't noticed that. Might be a bug with the kernel. I'll try to reproduce that setup and see if I can replicate.

**Comment by trapexit** [comment]
Is this still an issue?

**Comment by cycne** [comment]
I have only one server with this issue,  but thas greatly reduced after I removed mount bind.

**Comment by trapexit** [comment]
"greatly reduced"? Meaning it still happens?

Since I can't reproduce it there isn't much I can do ATM. If you can provide a way to reproduce it or have more info feel free to reopen the ticket.

**Comment by cycne** [comment]
After replacing the machine, the problem no longer occurred.
Thank You
