### ISSUE TITLE
hardlinking not working between drives in merged pool

### ISSUE THREAD

**Issue by phetrommer** [trapexit/mergerfs#522]
General description
===================
hardlinking doesn't work between drives in a merged pool.

Expected behavior
=================
from what I've read I assume mergerfs supports hardlinking between all the drives in a merged pool

Actual behavior
===============
my layout is as such
`/mnt/disk*/` (1 for each of my 4 disks)
`/mnt/storage/` (the merged pool)

`/mnt/storage/data/tv/downloads`
`/mnt/storage/data/tv/series/season/file`

ln: failed to create hard link `/mnt/storage/tv/Bodyguard/Season 01/file1.mkv` => `/mnt/storage/tv/downloads/file1.mkv`: Invalid cross-device link

it only manages to work if the folders end up in the same drive folder, for example
`/mnt/disk1/tv/downloads/file.mkv`  => `/mnt/disk1/tv/Bodyguard/Season 01/file.mkv`
it wont work if 
`/mnt/disk1/tv/downloads/file.mkv` => `/mnt/**disk2**/tv/Bodyguard/Season 01/file.mkv`

(i'm using hardlink because this is sonarr/radarr/lidarrs only options)

**Precise** steps to reproduce the behavior
===========================================

1. mount 2 separate disks as `/mnt/disk*`
2. merge as `/mnt/storage/`
3. put `/tv/` on disk1 and `/downloads/` on disk2 (which they may end up as if you have fullish drives like me)
4. try to hardlink `/mnt/storage/tv/downloads/file1.mkv` => `/mnt/storage/tv/file1.mkv`

System information
==================
Please provide as much of the following information as possible:

* mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

* 
```
UUID="c46989d4-bda4-414f-9929-1c47c952e7b8" /mnt/disk4 ext4 defaults,nofail 0 0
UUID="3c2ab642-0c22-491a-85a3-53c56a5a8cce" /mnt/disk3 ext4 defaults,nofail 0 0
UUID="ecab40ce-feb3-460f-b517-c3eec1c13639" /mnt/disk2 ext4 defaults,nofail 0 0
UUID="7cc9e8ab-3fe1-4ee5-b29d-2f83b5452fb0" /mnt/disk1 ext4 defaults,nofail 0 0

/mnt/disk*      /mnt/storage    fuse.mergerfs dropcacheonclose=true,defaults,allow_other,minfreespace=30G,fsname=mergerfs 0 0

```
* `Linux SERVER 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* all EXT4 (this was happening before my drives got so full)
``` 
mergerfs                      16T   15T   90G 100% /mnt/storage
/dev/sdd1                    1.8T  1.7T  767M 100% /mnt/disk2
/dev/sdc1                    2.7T  2.6T   29G  99% /mnt/disk1
/dev/sde1                    3.6T  3.4T   30G 100% /mnt/disk3
/dev/sda1                    7.3T  6.9T   31G 100% /mnt/disk4

```

[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/2522424/mergerfs.strace.txt)

let me know if you need anymore information

**Comment by trapexit** [comment]
> from what I've read I assume mergerfs supports hardlinking between all the drives in a merged pool

No, it doesn't simulate hard links across drives. Besides the symlinkify behavior it doesn't do anything more than union drives. I don't even know how you'd go about faking a hard link across devices.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#rename--link
