### ISSUE TITLE
mergerfs displays wrong group

### ISSUE THREAD

**Issue by Bl00dsoul** [trapexit/mergerfs#523]
General description
===================
Creating a directory as root inside of a mergerfs mount, mounted with gid= option results in the wrong permissions being displayed inside mergerfs

Expected behavior
=================
filesystem permissions to be consistent with the underlying filesystem.

Actual behavior
===============
filesystem permissions (group) between mergerfs and the underlying filesystem are different.

**Precise** steps to reproduce the behavior
===========================================

fstab:
/mnt/disk*         /mnt/mergerfs          fuse.mergerfs nofail,defaults,allow_other,use_ino,hard_remove,noatime,noexec,nodev,nosuid,gid=<some valid group id that isn't root>  0       0

as root (uid 0):
/mnt/disk* /mnt/mergerfs
cd /mnt/mergerfs/
mkdir test
ls -al: 
drwxrws---  2 root ftp  4.0K Oct 28 13:15 test
cd /mnt/disk1
ls -al: 
drwxrws---  2 root root  4.0K Oct 28 13:15 test

System information
==================
mergerfs version: 2.24.2-2-g4b1f9af
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

Linux nas 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

**Comment by Bl00dsoul** [comment]
I had hoped it would force all (new) files to have the same group (the one set by GID)
And at the very least set the mount point to the right group so services that depend on it can start & operate properly

**Comment by trapexit** [comment]
You want to overwrite the actual group as defined by the underlying filesystem?

**Comment by trapexit** [comment]
I just tested using gid=1234 and it worked as described in the docs. It overwrites the gid of all files regardless of what it really is.

I don't quite understand what you're trying to accomplish. mergerfs properly supports changing credentials and outside out of sync duplicate files/dirs you will always get exactly as it exists on the drive. `uid` and `gid` (and any other fuse option not defined in mergerfs' docs) aren't really tested.
