### ISSUE TITLE
Docker images trapexit/mergerfs-build-env due to missing git installation

### ISSUE THREAD

**Issue by peteward44** [trapexit/mergerfs#524]
General description
===================
Builds using the trapexit/mergerfs-build-env docker images are failing on (at least) tags ubuntu-bionic-amd64 and ubuntu-xenial-amd64 due to missing git binaries. Copying the docker image and executing ```apt-get install git``` on the container resolves the issue. This should be patched into the versions that are currently hosted on docker hub.

System information
==================
Ubuntu linux "bionic" amd64 18.04

**Comment by trapexit** [comment]
Odd... the install-build-pkgs target in the makefile should be installing it. I'll take a look.

**Comment by peteward44** [comment]
Just in case someone else comes across this problem in the meantime; for a workaround it's a lot easier to just clone the git repo yourself and map the dir to the one in the docker image; thus skipping the git clone inside the build script. Ie.

```
git clone https://github.com/trapexit/mergerfs.git /tmp/mergerfs
docker start -v /tmp/mergerfs:/tmp/mergerfs trapexit/mergerfs-build-env:ubuntu-bionic-amd64 [.....]
```

**Comment by trapexit** [comment]
That's how it's supposed to work. git is installed for build inside the container. It's explicitly designed to have the source bind mounted in.

These images are my own and not intended for public consumption. I have scripts which run through all my build images and builds packages.

**Comment by peteward44** [comment]
OK fair enough. Thanks for looking anyway

**Comment by trapexit** [comment]
There is a reason it doesn't download itself. Old versions of git regularly got blocked while doing a pull and would hold up the whole build process. Hence putting it in a script outside the build image. I can upload the build script but it just runs git pull and runs each build container with the path mounted in just as you showed above.
