### ISSUE TITLE
"No free space left on device

### ISSUE THREAD

**Issue by alex-phillips** [trapexit/mergerfs#536]
General description
===================
so i ran into this issue today:
* a directory only existed on one disk (disk1)
* i went to copy a file over to that folder (via mergerfs) it's now returning a 'no space left on device'
* if i manually create that path on disk2 then do the copy, it works just fine

Expected behavior
=================
I do have a minimum size set, which disk1 is under, but I would think that it would see the path on disk1, skip it, and create the path when necessary on disk 2

Actual behavior
===============
Returns 'no space left on device'

**Precise** steps to reproduce the behavior
===========================================
Here is my `/etc/fstab` line:

```
/mnt/disk*     /mnt/storage     fuse.mergerfs defaults,func.getattr=newest,allow_other,use_ino,minfreespace=50G,fsname=mergerfs 0 0
```

And the output from `df -h`:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       3.7T  3.7T   17G 100% /mnt/disk1
/dev/sdf1       3.7T  3.6T  135G  97% /mnt/disk2
/dev/sdc1       3.7T  3.6T  100G  98% /mnt/disk3
/dev/sdd1       1.9T  1.8T   78G  96% /mnt/disk4
/dev/sde1       1.9T  1.8T   69G  97% /mnt/disk5
/dev/sdb1       3.7T  3.7T  4.4G 100% /mnt/parity1
/dev/sdh1       3.7T  3.7T  4.4G 100% /mnt/parity2
```
> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ :heavy_check_mark: ] mergerfs version: `mergerfs -V`
```
mergerfs version: e3bac84
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.8
using FUSE kernel interface version 7.19
```
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments (see above)
* [ ] Linux version: `uname -a`: `Linux 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h` (see above)
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
You are using the default policy which is path preserving. It looks to me to be doing what it's configured to do. Be sure to read the docs regarding policies fully.

**Comment by alex-phillips** [comment]
What would you recommend for what I'm attempting to achieve? Basically I'd guess I want the defaults but if 'no space left' on existing path, go to the next available disk?

**Comment by trapexit** [comment]
It's not really clear what you're trying to accomplish. If you don't care about which drive a file ends up on use mfs. If you do care but handle running out of space use the option for moving a file when running out of space.

**Comment by trapexit** [comment]
Path preservation requires some human intervention. If you don't want that there are a few options available to deal with edge cases but mfs is generally the easiest policy to use.

**Comment by alex-phillips** [comment]
Got it. Will experiment with some of them. Thanks!
