### ISSUE TITLE
mergerfs slow writes to /home on same 

### ISSUE THREAD

**Issue by reichbc** [trapexit/mergerfs#541]
General description
===================
I have two disk pools installed on two separate host cards.
Pool 1 consists of four Dell SAS Cheetah 15K.7 300GB drives in RAID 10 mounted to a PERC H710. Debian is installed here.

Pool 2 consists of two Western Digital 8tb WD80EMAZ drives in HBA mode on a PERC H310 in IT mode, mounted to /mnt/es1 and /mnt/es2 respectively.

MergerFS is setup to take any drive in /mnt/es* and mount it to /storage.

When attempting to copy data from the MergerFS mountpoint to the /home/user directory (on the same array as the /storage mountpoint) the write speed is no more than 30MB/s.

Expected behavior
=================
Saturated disk writes according to tests using `dd`.

Actual behavior
===============
Disk writes under the copy or move data situation do not exceed 30MB/s.

**Precise** steps to reproduce the behavior
===========================================
####Creating 10GB files using /dev/zero first on `/home/brandon` then on the storage drive using both its direct mountpoint `/mnt/es1` and its mergerfs mountpoint `/storage`

`brandon@grandcentral:~$ dd if=/dev/zero of=/home/brandon/test.file bs=1M count=10000`  
`10000+0 records in`  
`10000+0 records out`  
`10485760000 bytes (10 GB, 9.8 GiB) copied, 36.9333 s, 284 MB/s`  
`brandon@grandcentral:~$ dd if=/dev/zero of=/storage/test.file bs=1M count=10000`  
`10000+0 records in`  
`10000+0 records out`  
`10485760000 bytes (10 GB, 9.8 GiB) copied, 27.9124 s, 376 MB/s`  
`brandon@grandcentral:~$ dd if=/dev/zero of=/mnt/es1/test.file bs=1M count=10000`  
`10000+0 records in`  
`10000+0 records out`  
`10485760000 bytes (10 GB, 9.8 GiB) copied, 27.8982 s, 376 MB/s`

####Copying the created test file from the storage drive to `/home/brandon` using the drive's mountpoint `/mnt/es1/`

`brandon@grandcentral:~$ dd if=/mnt/es1/test.file of=/home/brandon/test.file`  
`20480000+0 records in`  
`20480000+0 records out`  
`10485760000 bytes (10 GB, 9.8 GiB) copied, 72.3243 s, 145 MB/s`  

####Copying the created test file from the storage drive to `/home/brandon` using the MergerFS mountpoint `/storage`

`brandon@grandcentral:~$ dd if=/storage/test.file of=/home/brandon/test.file`  
`^C2810325+0 records in`  
`2810324+0 records out`  
`1438885888 bytes (1.4 GB, 1.3 GiB) copied, 48.0017 s, 30.0 MB/s`  

System information
==================
Please provide as much of the following information as possible:

* [X] mergerfs version: `2.18.0`
* [X] mergerfs settings: `/mnt/es*	/storage	fuse.mergerfs	direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs	0	0`
* [X] Linux version: `Linux grandcentral 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`
* [X] List of drives, filesystems, & sizes:  
`Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G   11M  3.2G   1% /run
/dev/sda2        28G  6.9G   20G  27% /
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
mergerfs         15T  3.2T   12T  22% /storage
/dev/sdc1       7.3T  3.2T  4.2T  44% /mnt/es1
/dev/sdb1       7.3T   18G  7.3T   1% /mnt/es2
/dev/sda4       489G   36G  429G   8% /home
/dev/sda1       511M  144K  511M   1% /boot/efi
tmpfs           3.2G     0  3.2G   0% /run/user/1000`

**Comment by trapexit** [comment]
1. Please use a current version. 2.18.0 is rather old.
2. Have you tried modifying settings as described in the performance section of the docs? https://github.com/trapexit/mergerfs#performance-tweaking
3. Have you run tests as shown in the docs to get a theoretical speeds with different blocksizes?  https://github.com/trapexit/mergerfs#nullrw
