### ISSUE TITLE
Files are lost when moved from pool to branch 

### ISSUE THREAD

**Issue by doak** [trapexit/mergerfs#545]
General description
===================

Moved files from the pool (i.e. *mergerfs'* mountpoint) to one of the branches are lost, even without an error.
For the test case, all branches and the pool directory are located on the very same filesystem.

Moving files between branches is working like expected.

Since the FAQ states [Can drives be written to directly? Outside of mergerfs while pooled?](https://github.com/trapexit/mergerfs#can-drives-be-written-to-directly-outside-of-mergerfs-while-pooled), I expect that accessing and modifying files in branches while mounted by *mergerfs* is allowed.

Expected behavior
=================

File should be moved to dedicated branch. At least it should fail with an error if this is not possible **and** files must not be lost.

Is there anything I miss or misinterpret?

Actual behaviour
===============

There is no error **and** files are lost.

**Precise** steps to reproduce the behavior
===========================================

Tiny script to reproduce:

```
#!/usr/bin/env bash


prepare() {
    mkdir -p branch1 branch2 branch3 &&
    mkdir -p MERGED &&
    trap "fusermount -u MERGED" EXIT &&
    mergerfs branch1:branch2:branch3 MERGED &&
    touch MERGED/test-file &&
    true
}

validate() {
    ls MERGED/test-file >/dev/null 2>&1 ||
    warn "File 'MERGED/test-file' vanished."
}

do_test() {
    mv MERGED/test-file branch2/
}

error() {
    echo "ERR: $*" >&2
    exit 1
}

warn() {
    local errcode=$?
    echo "WRN: $*" >&2
    return $errcode
}


prepare &&
validate ||
error "Preparation failed."

do_test ||
error "Test run failed."

validate ||
error "Unexpected behaviour."
```

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version:
```
mergerfs version: 2.25.1-8-g90e422c
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.8
using FUSE kernel interface version 7.19
```
* [x] mergerfs settings: only default options, see script above.
* [x] Linux version: Linux flatbox 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux
* [ ] Versions of any additional software being used: nothing else used beside GNU coreutils, namely `mv`.
* [x] List of drives, filesystems, & sizes: only `/tmp` is used:
```
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/debian-crypt  201G  117G   74G  62% /
```
* [ ] strace of application having problem: provided if needed
* [ ] strace of mergerfs while app tried to do it's thing: provided if needed

**Comment by trapexit** [comment]
It's not a mergerfs issue. It's an issue with what you're doing.

Run `mv` in verbose mode and you'll see it copies and then removes. It does this because the syscall `rename` which is does first fails with `EXDEV` so it copies the file then removes the source. 

```
copied 'test-file' -> 'branch2/test-file'
removed 'test-file'
```

Outside a warning in the docs I don't see what could be done to keep this from happening. It's just doing what it's told by `mv`.

**Comment by doak** [comment]
Thank you for your fast response. I was afraid that it something like this.
I warning and/or a section in FAQ would be valuable for sure.

> Outside a warning in the docs I don't see what could be done to keep this from happening. It's just doing what it's told by mv.

Since this is IMHO really a dangerous outcome, it would be very good to catch it. I just came across *mergerfs* today, hence I don't have only a very abstract idea how it (perhaps) works. Thus, please don't feel offended from the following rough and immature ideas. 

Starring at the posted output of `mv`...
Perhaps it is possible to "fool" `mv`/`cp` that source and destination is the same file. In that case they both fail gracefully afaik. (That means the copy part of the EXDEV rename would fail.)
I guess that is not possible, since *mergerfs* just "provide" the file descriptors, but does neither know what will happen with them nor if they are used within the same context.

For the same reason it is probably not possible to tweak the file removing part by *mergerfs*.

**Comment by doak** [comment]
From the strace it looks like some context is available for *mergerfs*:

    renameat2(AT_FDCWD, "MERGED/te", AT_FDCWD, "branch1", RENAME_NOREPLACE) = -1 EXDEV (Invalid cross-device link)

and

    renameat2(AT_FDCWD, "MERGED/te", AT_FDCWD, "branch1/te", RENAME_NOREPLACE) = -1 EXDEV (Invalid cross-device link)

I guess the second one could be "intercepted" to at least fail gracefully, couldn't it?

**Comment by doak** [comment]
I see. No hope ... :/
Thanks for your input, anyway.

Not sure if you maintain some "won't fix" or "invalid" label. Feel free to close this issue as such.

**Comment by trapexit** [comment]
I believe similar would happen if you were to bind mount a path then run mv. It would see them as separate files on separate files systems. In that case at least it can see it will overwrite.

**Comment by doak** [comment]
For completeness, there is the update of documentation: #550

**Comment by doak** [comment]
For the record, my best workaround is to enable `ff` policy for `unlink` which ensures that files aren't deleted (silently). In fact the move operation will either luckily succeed or is a graceful nop. Other similar implementation (e.g. *mhddfs*) seems to handle this the same.

**Comment by trapexit** [comment]
That's not a work around. You're just changing the unlink policy to delete one file instead of all. It's not a no op.

**Comment by doak** [comment]
Sure.
I considered it a workaround regarding loosing files, not regarding correct move semantic.
