### ISSUE TITLE
Hardlink Question / Issue

### ISSUE THREAD

**Issue by galli-leo** [trapexit/mergerfs#548]
General description
===================
I have setup my merged drives all under /mnt/storage. When I try to hardlink something, it fails if the destination path does not exist on the same drive. Is this expected or can I configure something for this work correctly? If I read the README correctly, setting func.getattr=all, should work right? I tried that but I still couldn't get hardlinking to work.

Expected behavior
=================

Actual behavior
===============

**Precise** steps to reproduce the behavior
===========================================

1. Have two drives in a mergerFS pool, mounted with func.getattr=all.
2. Folder exists on one drive, but not the other: `/mnt/disk1/test`
3. Try hardlinking on the merged pool: `ln /mnt/pool/file.txt /mnt/pool/test/file.txt`

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: ```mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19```
* [x] mergerfs settings: `/mnt/data*:/mnt/plexdrive=RO /mnt/storage fuse.mergerfs dropcacheonclose=true,defaults,allow_other,minfreespace=50G,fsname=mergerFS,func.mkdir=all,func.getattr=all 0 0` or the command line arguments
* [x] Linux version: `Linux blackpearl 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
getattr=all, as the docs mention, is the same as epff for any search but more expensive: https://github.com/trapexit/mergerfs#policy-descriptions

**Comment by galli-leo** [comment]
@trapexit > mergerfs can't practically fake links. It's just a union of drives.

Yeah I am perfectly fine with that, but what I would like to have, is that mergerfs tries to use the drive the original is on when hardlinking, at all costs, i.e. creates the directories if needed. 

> You're getting that error because you're using path preservation. If two paths are on different drives then it can't be linked because you've said to preserve paths.

So, if I understand that correctly, setting func.link = all would achieve that? Since that is not path preserving anymore.

> Where did you get that setting func.getattr=all would change the behavior of linking? EXDEV for rename and link are pretty thoroughly explained in the docs.

I misread that, but to me it was unclear how the target drive was determined. The docs say that if target_drive != source_drive, the target path is copied to the source drive. Does that mean it will actually use the source drive as the destination?

Thanks for your quick response!

**Comment by trapexit** [comment]
> but what I would like to have, is that mergerfs tries to use the drive the original is on when hardlinking, at all costs

There is no such thing as linking across drives. links are only possible on the same mount / device. Hence the situation you're in. You are asking to preserve paths AND then ask it to link across drives. It can't so it returns EXDEV.

> setting func.link = all would achieve that

No. That sets what is the source. Not destination.

>  to me it was unclear how the target drive was determined.

It's described in the section of the docs I linked. I'm not sure what to clarify. It says that the create policy determines whether rename/ link are path preserving, that the rename/link policy picks the source, and for each of those sources it tries to rename/link to the create branch. If that fails run the create policy and if that doesn't return the same device it will fail.

And then there's `ignorepponrename` to have a compromise.

**Comment by galli-leo** [comment]
> There is no such thing as linking across drives. links are only possible on the same mount / device. Hence the situation you're in. You are asking to preserve paths AND then ask it to link across drives.

That's perfectly fine, I don't want to link across drives, I want link to always use the same drive, even if the paths do not exist. Maybe my explanation was unclear, let me give you an example:

Directory tree is as follows:

```
/mnt/
    ├── disk1/ (Physical Drive mounted)
    |   ├── downloads/
    |   |   ├── My.Movie.mkv
    ├── disk2/ (Physical Drive mounted)
    |   ├── movies/
    ├── storage/ (mergerFS mounted using: /mnt/disk1:/mnt/disk2 /mnt/storage fuse.mergerfs dropcacheonclose=true,defaults,allow_other,minfreespace=50G,fsname=mergerFS,func.mkdir=all 0 0)
    |   ├── downloads/
    |   |   ├── My.Movie.mkv
    |   ├── movies/
```

The command I call: `ln /mnt/storage/downloads/My.Movie.mkv /mnt/storage/movies/My.Movie.mkv`.

What I would like to have happen:

1. mergerFS detects that the path `movies/` does not exist on the source drive (disk1).
2. mergerFS creates the path `movies/` on the source drive (disk1).
3. mergerFS hardlinks the file on disk1.

Therefore, it would look like this afterwards:

```
/mnt/
    ├── disk1/ (Physical Drive mounted)
    |   ├── downloads/
    |   |   ├── My.Movie.mkv
    ├── movies/
    |   |   ├── My.Movie.mkv
    ├── disk2/ (Physical Drive mounted)
    |   ├── movies/
    ├── storage/ (mergerFS mounted using: /mnt/disk1:/mnt/disk2 /mnt/storage fuse.mergerfs dropcacheonclose=true,defaults,allow_other,minfreespace=50G,fsname=mergerFS,func.mkdir=all 0 0)
    |   ├── downloads/
    |   |   ├── My.Movie.mkv
    |   ├── movies/
    |   |   ├── My.Movie.mkv
```

Currently, mergerFS just fails with EXDEV.

Is this possible with any options for mergerFS? Or could this be added as an option?

**Comment by trapexit** [comment]
> That's perfectly fine, I don't want to link across drives

I'm simply pointing out that you said you wanted to keep links on a drive and that there is no alternative.  A link by definition is on the same drive.

Did you read the docs? It's literally the first thing mentioned in the section I linked you to (everything about rename is the same with link).

> NOTE: If you're receiving errors from software when files are moved / renamed then you should consider changing the create policy to one which is not path preserving, enabling ignorepponrename, or contacting the author of the offending software and requesting that EXDEV be properly handled.
