### ISSUE TITLE
[Question] How does mergerfs handle duplicate files?

### ISSUE THREAD

**Issue by ShapeShifter499** [trapexit/mergerfs#553]
How does mergerfs handle duplicate files?  If I ran mergerfs to combine a bunch of locations and there happened to be two files named the same and in the same location in the root what would happen? And what if the files were different but named the same?

i.e.  "dir1/test.txt"   and   "dir2/test.txt"   mergerfs to  "merge/"

**Comment by trapexit** [comment]
It depends on the policy. Everything is in the docs.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#functions--policies--categories
