### ISSUE TITLE
Add folder on Bootdisk to pool - possible?

### ISSUE THREAD

**Issue by zilexa** [trapexit/mergerfs#554]
This is a question, not an issue. Please direct me to the right place to ask this if I should not ask it here.

With a pool of 2 5TB harddrives and an 500GB SSD with Debian, hardly 6GB in use on the SSD, I would like to do the following:
1 new files are created on the SSD (with restrictions, like max 80% full). Only once a day (at night) will they be written to the harddrives. Even if a file is updated during the day, only the SSD is used.
2 if a file has not been accessed/modified for X days it will be deleted from the SSD.

This means my HDDs only spin up once a day. 

Basical form of caching, would this be something I can do with MergerFS? I do not want to add another SSD for this, the current SSD is an M.2 SATA Samsung Evo 860 but as said it also contains the OS.

Could I therefore create a folder on the SSD and add it to the pool? Or partition the drive 10% for OS (which is plenty) and 90% for this purpose? I learned to stay away from partitioning SSDs.

**Comment by trapexit** [comment]
Yes, you can add any path to the pool. You can add the same path twice. mergerfs doesn't care. You just need to set the policies accordingly to the behavior you want. This kind of behavior is discussed in the docs.

https://github.com/trapexit/mergerfs#caching

**Comment by zilexa** [comment]
Thanks a lot for your quick reply!
