### ISSUE TITLE
fuse: unknown option `func.readdir:ff'

### ISSUE THREAD

**Issue by alexyao2015** [trapexit/mergerfs#557]
General description
===================
Using func.<func>=<policy> does not work with any function that is categorized as N/A.

Expected behavior
=================
Expected the mergerfs to mount when using -o func.readdir=ff.

Actual behavior
===============
I get this error:
fuse: unknown option `func.readdir:ff'

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

I used this command:
mergerfs -o func.readdir:ff /mnt/test:/mnt/test2 /mnt/final

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.4
using FUSE kernel interface version 7.19
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
mergerfs -o func.readdir:ff /mnt/test:/mnt/test2 /mnt/final
* [ ] Linux version: `uname -a`
Linux rclone 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
Why would functions explicitly marked "not applicable" for policies have policies?

**Comment by trapexit** [comment]
Also, the syntax is wrong. It's `func.<function>=<policy>`

**Comment by alexyao2015** [comment]
Oh, the docs make it seem that the functions just had no categories so they were classified as N/A. I did not realize it meant that they did not have policies. 

I was trying to have mergerfs readdir for only the first directory only, so I wanted to use that function.

**Comment by alexyao2015** [comment]
Essentially, I have rclone mounted with a cache layer and it mounted with the same remote without any caching. So these two mounts have the same files just different ways of accessing them. I need a way to read only the cached directory and delete in the directory without cache. I want to prevent reading the directly mounted directory to increase speed.

Is there currently any way to achieve this?

**Comment by alexyao2015** [comment]
I do realize that open is what is used for reading the files, but I need something to do a ff for directory listing and attributes. With the current setup, opening the directory causes an ls on both the cached and uncached mounts. Since the directories are exactly the same, there is no need to ls both directories. 

Yes, I am using rclone's caching backend. The issue with the caching backend is it seems to be unstable when making changes to existing files. Deleting and renaming files tend to take a long time and stall, while doing these same operating on a noncached mount does not have these issues. I also want to eventually use vfs caching which does not support file modifications. 

Merging these directories would allow for reading off the cached backend and edits (renaming/moving) to occur on the noncached mount.

**Comment by trapexit** [comment]
Ideally you'd talk with ncw of rclone and getting things fixed. The point of mergerfs is to be a union of drives. It has to readdir all drives. I'd rather not add policies to readdir just to work around rclone bugs. It doesn't have any other uses AFAICT. 

Why not just tag or mount the cached backend as readonly, have it set to the first drive, and open set to `ff`? Would that not give you what you want?

**Comment by trapexit** [comment]
> I need something to do a ff for directory listing and attributes

readdir goes through drives in order as listed and it only acquires the name of files. getattr is what gets the attributes. If you want attributes from the first drive then have `getattr` set to `ff`.

**Comment by alexyao2015** [comment]
I definitely understand that, but the current situation with rclone is it has two different methods for caching: the caching backend and vfs caching. VFS caching does not support file modifications at all and is a read only type of mount. So if using VFS caching, there is no way to edit already existing files without mergerfs. 

> Why not just tag or mount the cached backend as readonly, have it set to the first drive, and open set to ff? Would that not give you what you want?
That is actually exactly what I am currently doing. I am currently running it in docker with this command `-o defaults,nonempty,allow_other,direct_io,use_ino,category.create=ff,category.search=ff,minfreespace=0,func.getattr=newest`. It does provide almost what I want, but directory listings are slow because it is querying two cloud directories.

**Comment by trapexit** [comment]
Have you tried adding entry and attribute caching?

**Comment by trapexit** [comment]
If you've got things working but it's just that readdir is slow why the questions about read and unlink?

**Comment by trapexit** [comment]
why are you using `getattr.newest` if the branches are all the same? The values would not be different.

**Comment by alexyao2015** [comment]
I guess I could take a look at entry and attribute caching. Though rclone docs mention that 

> The kernel can cache the info about a file for the time given by “--attr-timeout”. You may see corruption if the remote file changes length during this window

So I'm not too sure about it as of now though I haven't really looked into it that much. And I thought I read that mergerfs does not have caching?

**Comment by trapexit** [comment]
If you change files out of band there is always a risk of corruption. I don't see how attribute caching makes it any different.

mergerfs doesn't do explicit file caching. Tiered caching based on device speed. That has nothing to do with kernel page caching, attribute caching, or entry caching.

**Comment by alexyao2015** [comment]
I didn't have problems with read and unlink because they were already working. 

I wasn't really sure about the `getattr.newest`, but I did have another directory that was merged. Its merged like this /local-copy:/cache:/direct. So new files are moves to /local-copy and eventually rclone copy to /cache. So there could be duplicate file in /local-copy and /cache until the file is removed from /local-copy. The file should be the same though, so does that mean `getattr.newest` is not required?

Here is my project that I am working on with the relevant files. [mountscript](https://github.com/alexyao2015/cloud-media-scripts/blob/rclonecache/scripts/mount.script) [variables](https://github.com/alexyao2015/cloud-media-scripts/blob/rclonecache/scripts/variables)

**Comment by trapexit** [comment]
> I didn't have problems with read and unlink because they were already working.

OK, it's just confusing to be discussing multiple aspects when some of them actually aren't in question. It's best to give all relevant information up front.

> I did have another directory that was merged 

You didn't mention that prior.

If you expect the file to be the same and the attributes are being copied as well then no it shouldn't be required.

**Comment by alexyao2015** [comment]
Also, I'm not sure why I am only getting ~8 MB/s when writing with mergerfs, but with unionfs, I get ~50 MB/s maxing out my gigabit connection. CPU usage shows only 1% when writing files on mergerfs. I did read about disabling direct_io, but it didn't seem to do anything.

Any ideas on that as well?

**Comment by trapexit** [comment]
I said mergerfs *does not* support tiered caching. https://github.com/trapexit/mergerfs#caching

> Is this the caching you mentioned earlier?

Yes, entry caching and attribute caching. Exactly the same as rclone's `--attr-timeout`.

**Comment by trapexit** [comment]
> Its unionfs-fuse.

There should be no serious difference then. You're settings are probably not the same. Even if just implicitly.

**Comment by alexyao2015** [comment]
Here's options I'm using with unionfs-fuse:
`-o cow,allow_other,direct_io,nonempty,auto_cache,sync_read`

And mergerfs:
`-o defaults,nonempty,allow_other,sync_read,category.create=ff,category.search=ff,minfreespace=0`

**Comment by alexyao2015** [comment]
The only real difference I see is the category policies and cow. I already tried adding and removing direct_io, so that is not the cause. 

And CoW should not be a factor since I am writing new files. So that only leaves the category policies?

**Comment by trapexit** [comment]
No, defaults expands to things you aren't including.  https://github.com/trapexit/mergerfs#mount-options

Does unionfs-fuse have xattrs enabled?

**Comment by alexyao2015** [comment]
For this particular image, I pulled unionfs-fuse from Alpine linux repositories and mergerfs from edge/testing repository. 

Looking at the unionfs-fuse build log, it does look to have xattrs enabled? I see lines like this `gcc -Os -Wall -Os -I/usr/include/fuse -D_FILE_OFFSET_BITS=64  -DFUSE_USE_VERSION=26 -DLIBC_XATTR   -c -o unionfs.o unionfs.c` though I am not too familiar with how this works.

**Comment by alexyao2015** [comment]
Thank you!!
Its looks like it was one of the defaults that expanded. Using this `-o auto_cache,direct_io,nonempty,allow_other,sync_read,category.create=ff,category.search=ff,minfreespace=0` gave me the same performance I got from unionfs-fuse. 

I'll try to do some more testing tomorrow to narrow it down and figure out which option caused the slowdown. I'll also take a look at the attribute caching as well.

**Comment by trapexit** [comment]
My guess its the `splice_*` args.

**Comment by alexyao2015** [comment]
So you were right. It was `splice_read`, but `splice_move` did not cause an issue. Even with `splice_read` and `splice_move` on, reads were still fine though which was strange. It seems that `splice_read` caused issues with writes?

**Comment by trapexit** [comment]
It's only supposed to change the way in which data is written to and from the fuse device. Would need to investigate more to understand why it'd cause an issue.
