### ISSUE TITLE
Ubuntu repos, especially bionic, needs newest release.

### ISSUE THREAD

**Issue by robertbaker** [trapexit/mergerfs#570]
template NA.

currently an outdated 2.21 is in the ubuntu bionic repo. I tried doing a basic mount per the docs and got an error about missing mount param.
I manually installed the newest bionic deb and it worked fine. So please update the ubuntu repos with your latest release (maybe release what's in master now??)

**Comment by trapexit** [comment]
1) I don't control what gets into Debian / Ubuntu. I'm not the package maintainer. That's why I produce my own packages.

2) That's not how Debian / Ubuntu work. They don't randomly update packages for a release. They primarily update for bugs. Not features.
