### ISSUE TITLE
Need help with renaming inside the unionfs

### ISSUE THREAD

**Issue by robertbaker** [trapexit/mergerfs#571]
Using the latest release.

```mergerfs -o defaults,allow_other,use_ino,nonempty,statfs_ignore=ro,security_capability=false,xattr=nosys,category.create=ff,minfreespace=2G,umask=002,noatime,fsname=pgPool /mnt/move=RW:/mnt/gdrive=NC:/mnt/tdrive=NC:/mnt/tcrypt=NC:/mnt/gcrypt=NC:/mnt/downloads=RO /mnt/unionfs```

I need to mv / rename files that are in /mnt/downloads/client/movies to /mnt/unionfs/movies (which should end up really being /mnt/move/movies)

I have /mnt/move mounted as RW. so files written to /mnt/unionfs should really go to /mnt/move, but they are all going to /mnt/downloads if the files exist in a sub directory underneath downloads.

Is there a way for me to force writing to /mnt/move?

I'm trying to do radarr/sonarr hardlinking. sonarr library is /mnt/unionfs/tv. I added a remote mapping from /mnt/downloads to /mnt/unionfs.

It moves and renames the files, but it puts them under /mnt/downloads/tv, not /mnt/move/tv. I even mounted /mnt/downloads as RO and it still moves the files there.

The only way I see getting around this is by putting /mnt/downloads under another subdir so it's /mnt/unionfs/downloads.

Is there a way to accomplish this? Is there a param I'm missing?

I'm guessing this is expected behavior because mergerfs is going Oh that's a path on this drive, let's keep it on the same mount?

**Comment by trapexit** [comment]
It follows the rules as described in the docs. The directories e exist in the same drive so it succeeds. link and rename only work on the same drive. It's impossible for link across drives.

**Comment by robertbaker** [comment]
Everything is on the same drive.

So ff will find the first one and stop.

So if I do: /mnt/d1=RW:/mnt/d2=NC:/mnt/d3=NC:/mnt/d4=NC:/mnt/d5=RW
which one will it write to first everytime? d1 or d5?

I'm essentially looking for a way to tell it to write stuff to the first RW drive and ignore the other RW drive. Does NC allow hardlinks, or does that need to be RW?

**Comment by trapexit** [comment]
Your original post said:

> I'm trying to do radarr/sonarr hardlinking. sonarr library is /mnt/unionfs/tv. I added a remote mapping from /mnt/downloads to /mnt/unionfs.

Now you say:

> I'm essentially looking for a way to tell it to write stuff to the first RW and ignore the other RW drive. Does NC allow hardlinks, or does that need to be RW?

Writes != links. They are very different things. A link can **only** exist on the same mount. The behavior is explained here: https://github.com/trapexit/mergerfs#rename--link

The tagging only effects the link / rename behavior to the extent that they use the create policy as described in the docs.

>  sonarr can't do a hardlink and copies to /mnt/move.

It can't do hardlinks across mounts. It's impossible. If you make /mnt/downloads RO then of course it can't copy to it.

> So if I do: /mnt/d1=RW:/mnt/d2=NC:/mnt/d3=NC:/mnt/d4=NC:/mnt/d5=RW which one will it write to first everytime? d1 or d5?

`ff` is based on the order you've given plus the filters. It's not about writing. It's about creating. Writes aren't determined by policy. Only create / open. Create with that setup would always hit d1 (ignoring other filters). 


You can't do what you're asking in mergerfs or any union filesystem. You are asking it to distinguish between the same relative path which is counter to what its intended. /mnt/move/tv and /mnt/download/tv are basically the same. The /tv is all that matters and intended to be the same location. If you want files to be moved or copied between them you'll have to do it out of band but I really don't understand what the point of keeping your download directory for tv in the same relative directory as the final destination and keeping them on separate drives dedicated to those purposes.

**Comment by trapexit** [comment]
I don't know how sonarr works or it's settings. Ultimately if you're performing a link operation it works as described in the docs. You can't link across drives. If you want files copied between directories on different drives them then you need to tell sonarr to do so and have path preservation or tags appropriately set.

**Comment by robertbaker** [comment]
Thanks for the help. I have 1 HDD, all folders are under 1 HDD.

I'll keep trying different things.

The idea is you point plex and arr at /mnt/unionfs/tv or /mnt/unionfs/movies

sonarr will attempt to move from /mnt/downloads to /mnt/unionfs/tv (it's lib location). We keep it as NC because sonarr writes a bunch of little stuff that would eat up gdrive api. I'm using rclone with it.

**Comment by trapexit** [comment]
I really don't understand what you're trying to do. If you have one hdd then what is /mnt/move and /mnt/download? They are the same drive?

**Comment by robertbaker** [comment]
The same drive yes.

/mnt/move is watched by a script then calls rclone move.

I may have a workaround, where I detect the 'moved' folders under /mnt/downloads and mv them with a script.

It seems complicated and it probably is.

**Comment by trapexit** [comment]
I don't understand why you're adding the same drive but different directories into mergerfs? Why not just have a single base path on the drive and have it move files between the directories for download and library?

**Comment by robertbaker** [comment]
I could but then I have to wait for files to upload for everything to see them

**Comment by trapexit** [comment]
I don't see how the merging of two directories in mergerfs vs one has any impact on when you see them in your library. Either way this isn't a mergerfs issue so I'm closing this ticket.
