### ISSUE TITLE
'defaults' consumed by mount, different from mergerfs cmd line 

### ISSUE THREAD

**Issue by EnorMOZ** [trapexit/mergerfs#572]
General description
===================
When using a .mount systemd file the proper flags are added and you don't see `fuse: trying to steal weird page` messages in sys/kern.log file.  Similar error as https://github.com/trapexit/mergerfs/issues/401

Expected behavior
=================
Do not see `fuse: trying to steal weird page` message in sys/kern.log file and proper fuse options are added.
`local:remote on /mnt/merged type fuse.mergerfs (rw,noatime,user_id=0,group_id=0,allow_other)`

Actual behavior
===============
 You see `fuse: trying to steal weird page` message in sys/kern.log file. And flags are added.
`local:remote on /mnt/merged type fuse.mergerfs (rw,nosuid,nodev,noatime,user_id=0,group_id=0,default_permissions,allow_other)`

**Precise** steps to reproduce the behavior
===========================================
run `mergerfs /mnt/local=RW:/mnt/remote=NC /mnt/merged -o rw,noatime,category.create=ff,minfreespace=0,allow_other,dropcacheonclose=true,security_capability=false,xattr=nosys,statfs_ignore=ro,use_ino,hard_remove,auto_cache,umask=0002,dev,suid` as root and you will see via mount command `local:remote on /mnt/merged type fuse.mergerfs (rw,nosuid,nodev,noatime,user_id=0,group_id=0,default_permissions,allow_other)`

Create a .mount file
`# /etc/systemd/system/mnt-unionfs.mount

[Unit]
Description=mergerfs mount

[Mount]
What=/mnt/local=RW:/mnt/remote=NC
Where=/mnt/merged
Type=fuse.mergerfs
Options=defaults,category.create=ff,minfreespace=0,allow_other,dropcacheonclose=true,security_capability=false,xattr=nosys,statfs_ignore=ro,use_ino,hard_remove,auto_cache,umask=0002,noatime
[Install]
WantedBy=default.target`

Then run the mount command . It will output `local:remote on /mnt/merged type fuse.mergerfs (rw,noatime,user_id=0,group_id=0,allow_other)`

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19`
* [ ] mergerfs settings: `mergerfs /mnt/local=RW:/mnt/remote=NC /mnt/merged -o rw,noatime,category.create=ff,minfreespace=0,allow_other,dropcacheonclose=true,security_capability=false,xattr=nosys,statfs_ignore=ro,use_ino,hard_remove,auto_cache,umask=0002,dev,suid`
* [ ] Linux version: `Linux myserver 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by EnorMOZ** [comment]
Basically seems like `nosuid,nodev,default_permissions` are always added when ran via cli or .service systemd file no matter what user is running it or User is defined in the file. However when a .mount systemd file is used those options are not included when ran as root.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/blob/master/libfuse/doc/kernel.txt#L248

This is why `nodev` and `nosuid` are being set. 

As for `default_permissions`: seems there is a disconnect between `defaults` being used via mergerfs cmd line app and using mount with -t fuse.mergerfs. Looks like my technique for trying to add variables for mount to pick up isn't working with mount. It only works with fusermount.

Which means that if you're using defaults on the command line with the mergerfs command vs mount you're getting the atomic_o_trunc, auto_cache, big_writes, default_permissions, splice_move, splice_read, and splice_write on the former and not the latter.

I'll need to find a way to fix this but as the docs mentioned about this issue the splice args can impact it. You should test those.
