### ISSUE TITLE
mergerfs is copying files when i rename / move them.

### ISSUE THREAD

**Issue by kiwijunglist** [trapexit/mergerfs#573]
General description
===================
I use mergerfs. I rename movie files in radarr which runs in docker. When radarr renames some files, or renames the folder that a file is located in it copies the file instead of a simple rename function.  All the files are located on /mnt/storage/movies/.... the existing location and new location are both within /mnt/storage/movies

Expected behavior
=================

rename files or folders is quick and doesn't requiring copying

Actual behavior
===============

files are copied and then deleted instead of a simple rename

System information
==================
Please provide as much of the following information as possible:

mergerfs version: 2.21.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

Linux server 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

fstab
=====

UUID=82042aab-1a2c-11e9-bf40-902b34dd724a none swap sw 0 0
UUID=82042aac-1a2c-11e9-bf40-902b34dd724a / ext4 defaults 0 0
UUID=83ede676-1a2c-11e9-bf40-902b34dd724a /home ext4 defaults 0 0
UUID=3AF5-CBC3 /boot/efi vfat defaults 0 0

UUID="accf4128-ef55-44bc-b105-5b82ce3f342f" /mnt/disk-8tb1 ext4 defaults 0 0
UUID="057aee3a-63ac-4014-9ec2-25470d81cdf1" /mnt/disk-8tb2 ext4 defaults 0 0
UUID="c2c8f098-2158-495b-bb2c-a150fd049496" /mnt/disk-8tb3 ext4 defaults 0 0
UUID="b8e93a30-3f17-4737-9a45-3047c43f80a8"  /mnt/parity ext4 defaults 0 0
UUID="3eb93b46-7fe0-452a-8335-72aabe8dc0b5" /mnt/disk-6tb1 ext4 defaults 0 0
UUID="f413c50f-d0c8-4db9-9093-1749f51c3c60" /mnt/disk-4tb1 ext4 defaults 0 0
UUID="81ca18e1-7807-485c-ad8a-1ad826de70fe" /mnt/disk-3tb1 ext4 defaults 0 0
UUID="fb17a341-9176-4490-8df1-0c7fcea02c30" /mnt/disk-3tb2 ext4 defaults 0 0
UUID="fc6d8b67-3170-4cad-b158-7478284c07bc" /mnt/disk-3tb3 ext4 defaults 0 0
UUID="c8b7c67a-c02c-4f40-89dc-5c54c69315f3" /mnt/disk-3tb4 ext4 defaults 0 0

/mnt/disk* /mnt/storage fuse.mergerfs direct_io,defaults,allow_other,category.create=eplfs,use_ino,minfreespace=30G,fsname=mergerfs 0 0

**Comment by kiwijunglist** [comment]
Apologies, some of the information requested maybe missing as I am just a noob with linux still.

**Comment by kiwijunglist** [comment]
Package: gvfs-fuse
==========
Versions:
1.36.1-0ubuntu1.2 (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_main_binary-amd64_Packages
                  MD5: e8ae435dfe556826602d3a021208211e
 Description Language: en
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_main_i18n_Translation-en
                  MD5: e8ae435dfe556826602d3a021208211e
 Description Language:
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages
                  MD5: e8ae435dfe556826602d3a021208211e

1.36.1-0ubuntu1 (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_main_binary-amd64_Packages
                  MD5: e8ae435dfe556826602d3a021208211e
 Description Language: en
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_main_i18n_Translation-en
                  MD5: e8ae435dfe556826602d3a021208211e
 Description Language:
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages
                  MD5: e8ae435dfe556826602d3a021208211e


Reverse Depends:
  gnome-core,gvfs-fuse 1.30
  lubuntu-qt-desktop,gvfs-fuse
  lubuntu-gtk-desktop,gvfs-fuse
  lubuntu-desktop,gvfs-fuse
  xubuntu-desktop,gvfs-fuse
  vanilla-gnome-desktop,gvfs-fuse
  ubuntustudio-desktop,gvfs-fuse
  ubuntukylin-desktop,gvfs-fuse
  ubuntu-unity-desktop,gvfs-fuse
  ubuntu-mate-desktop,gvfs-fuse
  ubuntu-mate-core,gvfs-fuse
  ubuntu-budgie-desktop,gvfs-fuse
  pcmanfm-qt,gvfs-fuse
  pcmanfm,gvfs-fuse
  nemo,gvfs-fuse
  lubuntu-qt-desktop,gvfs-fuse
  lubuntu-gtk-desktop,gvfs-fuse
  lubuntu-desktop,gvfs-fuse
  ubuntu-desktop,gvfs-fuse
  cinnamon-core,gvfs-fuse
Dependencies:
1.36.1-0ubuntu1.2 - libc6 (2 2.4) libfuse2 (2 2.8) libglib2.0-0 (2 2.49.3) gvfs (5 1.36.1-0ubuntu1.2) fuse (2 2.8.4)
1.36.1-0ubuntu1 - libc6 (2 2.4) libfuse2 (2 2.8) libglib2.0-0 (2 2.49.3) gvfs (5 1.36.1-0ubuntu1) fuse (2 2.8.4)
Provides:
1.36.1-0ubuntu1.2 -
1.36.1-0ubuntu1 -
Reverse Provides:

**Comment by trapexit** [comment]
It's not mergerfs. It doesn't copy/unlink on rename.

You are using a path preserving policy so I suspect your simply hitting a EXDEV error because the path doesn't exist on the destination branch nor would it be created on it (read the docs for more detail). As a result radarr is moving the file.

You can use a different, non path preserving policy or enable ignorepponrename. Or create the relevant path on the target drive.


In the future please consider updating to the most recent version of mergerfs before submitting tickets. Makes it easier to debug.

**Comment by trapexit** [comment]
Upgrade. You're using an old release.

**Comment by kiwijunglist** [comment]
sorry. thank you.
