### ISSUE TITLE
NFS Stale file handle

### ISSUE THREAD

**Issue by m-fonseca** [trapexit/mergerfs#576]
General description
===================
Hello.  I'm getting stale file handles over my NFS export (backed by mergerfs).  

Additionally, kodi will stop steaming 5-30 seconds into a movie.

I can't seem to find anyone else talking about this, so maybe I'm just incorrectly configuring it.  I did read somewhere to make sure `use_ino` was set to avoid kodi steaming issues, but that made no difference for me.

I've been using NFS for quite some time without any problem until I switched to mergerfs, so I don't necessarily suspect my nfs configuration as being a problem.

Steps to reproduce the behavior
===========================================

On my nfs mounted drive, if I do something silly like:
```
while ls -1 |head -n 1 ; do sleep 1 ; echo $((i++)); done
```
After about 1000 seconds I get stale handles.  Also If I play from kodi it will cause these as well.

System information
==================
```
: mergerfs -V
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.9
using FUSE kernel interface version 7.19
```
```
: grep mergerfs /etc/fstab 
/media/sr_d* /srv fuse.mergerfs defaults,allow_other,use_ino,hard_remove,category.create=lfs,moveonenospc=true,minfreespace=20G,fsname=mergerfs_pool 0 0
```
```
: uname -a
Linux test 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux
```
```
/dev/sde        1.9T  1.9T     0 100% /media/sr_p3
/dev/sdg        1.9T  1.9T     0 100% /media/sr_p4
/dev/sdb        1.9T  1.8T   25G  99% /media/sr_p1
/dev/sdc        7.3T  7.3T   20G 100% /media/sr_d2
/dev/sdd        1.9T  1.9T     0 100% /media/sr_p2
/dev/sdf        1.8T  967G  866G  53% /media/sr_d1
/dev/sdi        7.3T  658M  7.3T   1% /media/sr_d3
mergerfs_pool    17T  8.3T  8.2T  51% /srv
```

```
: grep srv /etc/exports 
/var/nfs-export/srv     	192.168.1.0/24(rw,async,insecure,no_root_squash,no_subtree_check,fsid=1)
```

```
: lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux buster/sid
Release:	testing
Codename:	buster
```

**Comment by trapexit** [comment]
Have you tried what's mentioned in the docs?

https://github.com/trapexit/mergerfs#nfs-clients-returning-estale--stale-file-handle
https://github.com/trapexit/mergerfs#can-mergerfs-mounts-be-exported-over-nfs

**Comment by m-fonseca** [comment]
ugh!  How did I miss this.  Sorry for wasting your time.

One thing.  I noticed 'noforget' option is not in the man page.

Thanks again!

**Comment by trapexit** [comment]
The online docs are usually newer than the man page but they are based on the same document when I do releases. The whole `noforget` thing is common across libfuse filesystems. I only more recently added the details to the mergerfs docs.
