### ISSUE TITLE
Freebsd Question

### ISSUE THREAD

**Issue by animosity22** [trapexit/mergerfs#578]
I was getting closer to testing again on FreeBSD as I worked a little more on getting it compiled.

I found this old bug that I hit on the latest version:

https://github.com/sahib/rmlint/issues/139

```
gmake INTERNAL_FUSE=0
tools/update-version
c++ -O2 -g   -Wall -Wno-unused-result -I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64  -DFUSE_USE_VERSION=29 -MMD -DUSE_XATTR=1 -DUGID_USE_RWLOCK=0  -c src/fs_cow.cpp -o obj/fs_cow.o
src/fs_cow.cpp:107:59: error: use of undeclared identifier 'O_LARGEFILE'
      src_fd = fs::open(src_fullpath_,O_RDONLY|O_NOFOLLOW|O_LARGEFILE);
                                                          ^
src/fs_cow.cpp:113:49: error: use of undeclared identifier 'O_LARGEFILE'
      dst_fd = fs::mktemp(dst_fullpath,O_WRONLY|O_LARGEFILE);
                                                ^
2 errors generated.
```

I am getting the same error. I tried the user's repo above from an older version and that compiled no problem:

```
./mergerfs --version
mergerfs version: 2.16.1-20-g12b9fc1
```

uname -a
FreeBSD freeplex 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64

Seems to be so close as the older version in my testing does some to do what I was hoping.

Any chance this can be addressed again?

**Comment by trapexit** [comment]
Try building the master branch.

**Comment by trapexit** [comment]
You can run `gmake install-build-pkgs` too which should install all build dependencies.

**Comment by animosity22** [comment]
Awesome.

So I just grabbed it on my test VM and built without issue:

```
git https://github.com/trapexit/mergerfs.git
cd mergerfs

# Install the dependencies for the building of the package
gmake install-build-pkgs 

# complile mergerfs
gmake install
```

and

```
root@freeplex:~ # mergerfs --version
mergerfs version: 2.25.1-42-ga80f9a0
FUSE library version: 2.9.7-mergerfs_2.26.0
mount_fusefs [fuse4bsd] version: 0.3.9-pre1
using FUSE kernel interface version 7.27
```

Thanks for your help!

**Comment by trapexit** [comment]
No problem. It's not tested so please fool with it before using it in prod.
