### ISSUE TITLE
High availability possible?

### ISSUE THREAD

**Issue by Iguana9999phil** [trapexit/mergerfs#588]
I’m curious if mergerfs is able to be used in a high availability environment. Let say I’ve got 2 nfs mounts to 2 storage servers with both the same data. I merge these mounts on the target server into one mount which is served out from there. 

If the first mount would give issues with reading a file would it be possible for mergerfs to stop reading the file from the first mount and start reading from the second mount? This would be in case there are errors / timeouts with reading files, not when the mount disappears as a server goes down.

**Comment by trapexit** [comment]
Not currently and not practically. Which errors? Many errors aren't clean and leave the mount in a weird state. Files stuck open, full blocking of IO calls, etc. It would depend on the specific error and how it manifests. Also it's not that simple. What happens with the bad mount / branch? How long do you take it out of rotation?

**Comment by trapexit** [comment]
Also... this is the same as #342
