### ISSUE TITLE
Cannot see or interact with files from RO/NC branch

### ISSUE THREAD

**Issue by lyarenei** [trapexit/mergerfs#594]
General description
===================
I just discovered mergerfs and while I was playing with it, I found some kind of odd behavior, which don't understand. It's basically what the title says. If I set a branch in a mountpoint as RO or NC, I am not able to see or access any files from that branch in the mountpoint.

(Now, if explicitly specify the branch as RW, the fuse throws an error for missing mountpoint, but since the RW is default option anyway, I want to focus on the RO/NC issue here.)

I am not sure if this is correct behavior or not, but I haven't found anything about this in the manual or readme, unless I have ultimately missed something.

Mount command is executed as root, the directories and files are owned by root and have full permissions set (0777).

**Precise** steps to reproduce the behavior
===========================================
(as root)
- Create some directories: `mkdir /tmp/dira /tmp/dirb /tmp/dirc`
- Create some files: `touch /tmp/dira/filea /tmp/dirb/fileb`
- Give full permissions to directories and files (just in case): `chmod -R 0777 /tmp/dira /tmp/dirb`
- Mount/merge the non-empty dirs: `mergerfs /tmp/dira=RO:/tmp/dirb /tmp/dirc`
- List the merge: `ls /tmp/dirc`

Running `df -h` shows only `/tmp/dirb` being mounted, which seems like the `/tmp/dira` was somehow ignored.

Expected behavior
=================
Both existing files are listed and available

Actual behavior
===============
Only the file from `/tmp/dirb` is listed and available

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
```
mergerfs version: 2.21.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
``` 
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
branches: /tmp/dira=RO:/tmp/dirb
mountpoint: /tmp/dirc
no additional options used
```
* [ ] Linux version: `uname -a`
```
Linux ubuntu 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* [ ] Versions of any additional software being used
```
none
```
* [ ] List of drives, filesystems, & sizes: `df -h`
```
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  1.6M  1.6G   1% /run
/dev/md2       1007G   71G  886G   8% /
tmpfs           7.8G  8.0K  7.8G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/md1        488M  125M  338M  27% /boot
tmpfs           1.6G     0  1.6G   0% /run/user/0
overlay        1007G   71G  886G   8% /var/lib/docker/overlay2/8ec5b90abeed03b35aae0af97eee6d4381f44f2166f311b3ede15475758dd9bf/merged
overlay        1007G   71G  886G   8% /var/lib/docker/overlay2/8807a1f1a8cbffb6116804b9dfd0863e6c8d980a4272225298a7594a75ef8cdb/merged
shm              64M     0   64M   0% /var/lib/docker/containers/d4096256aa44fbe777a3f69f8148b55deb46e92270dfc06fcefd62f2b0a080c9/mounts/shm
overlay        1007G   71G  886G   8% /var/lib/docker/overlay2/586ec927c3a8589f83414ce2cde5ee6beb32bb26f50feadd0d3648cbb80a590d/merged
overlay        1007G   71G  886G   8% /var/lib/docker/overlay2/5c531f2df218bcf45e9a6bc03cb8e8433a9cc2c1d48e35fc7c15689d352251e4/merged
shm              64M     0   64M   0% /var/lib/docker/containers/c4dd5c038477226de4ad7ef98e636885080587ffdb411b42fdb15144554e652f/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/d608bb1f260be79684df84c4f79215e1d54bd892385d1fd09d5c2badeab361f7/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/1206fe5216e887789682494ee154463c872bd48ea486e232a4d2be05cfd43513/mounts/shm
overlay        1007G   71G  886G   8% /var/lib/docker/overlay2/6543d27928709b6ebd7ef6f64425999184ee991ac90b408c312b6093251cd512/merged
shm              64M     0   64M   0% /var/lib/docker/containers/7100ceb96c5b8520df5de1652bfd9fb210703051384638a49a3b2b09b8648e43/mounts/shm
/dev/loop0       92M   92M     0 100% /snap/core/6531
/tmp/dirb      1007G   71G  886G   8% /tmp/dirc
```
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
- https://pastebin.com/nC8Ku7SV
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
- https://pastebin.com/b9x6F4JJ

**Comment by trapexit** [comment]
You're using an old version. 2.21.0 is from almost 2 years ago. Setting branch type wasn't added till 2.25.0.

**Comment by trapexit** [comment]
What is happening is that you are adding `=RO` or `=NC` and it doesn't exist as a path. Look at the settings via the runtime xattr interface and you'll see.

**Comment by lyarenei** [comment]
Oh my... of course. I installed it from the official repo, it never crossed my mind there would be such an old version, but I should have definitely checked out, my bad.

Of course, now it works perfectly, thanks for pointing out!

**Comment by trapexit** [comment]
np

Yeah, I build my own packages for that reason.
