### ISSUE TITLE
[rTorrent] Incomplete data for files ≥ 4 GiB when download path includes a mergerfs mountpoint

### ISSUE THREAD

**Issue by Igetin** [trapexit/mergerfs#596]
General description
===================
I have set my rTorrent download directory like this: `directory.default.set = /media/drives/Torrent`. Here `drives` is a mergerfs mount point. I have also set the option `pieces.hash.on_completion = yes`.

Whenever I add a torrent that includes a file of size 4 GiB or larger, rTorrent will download the data normally until the percentage shows ”100 %”. After that, it will perform the hash check, and then shows the error message:
```
Hash check on download completion found bad chunks, consider using "safe_sync"
```

After this, the torrent becomes inactive. At this point the completion percent of the file is not 100 anymore, but something lower (this depends on torrent, but the file is not complete on the disk, since it cannot be opened normally in related programs). The “safe_sync” in the error message is actually a deprecated option name, but nowadays refers to the option [pieces.sync.always_safe](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-pieces-sync-always-safe), which I have enabled.

Expected behavior
=================
rTorrent should download the file data completely, then perform a hash check and continue seeding the torrent.

Actual behavior
===============
rTorrent inactivates the torrent after a hash check, and displays this error message:
```
Hash check on download completion found bad chunks, consider using "safe_sync"
```

Additional details
===========================================

I have hundreds of files with a size _lower_ than 4 GiB, of which **none** have this problem. **Every** torrent with a 4 GiB or larger file has failed with the error so far. If I tell rTorrent to force recheck the hash of a torrent with the error, it will perform the check and show the same error again.

The problem does **not** occur with these settings:
```
directory.default.set = /media/drives/Torrent
pieces.hash.on_completion.set = no
```
**Nor** with these (Lunatea points to an actual drive):
```
directory.default.set = /media/Lunatea/Torrent
pieces.hash.on_completion.set = yes
```
The error does **not** appear with either of these settings when performing a manual hash check after the data has downloaded.

It seems like the automatic hash check does not play well with mergerfs.

Steps to reproduce the behavior
===========================================

1. Have mergerfs mounted via `/etc/fstab` with the options: `minfreespace=20G,defaults,allow_other,use_ino,dropcacheonclose=true`
2. Have these lines in `rtorrent.rc`:
```
directory.default.set = /path/with/mergerfs/mountpoint
pieces.hash.on_completion.set = yes
```
3. Start rTorrent (run `rtorrent`)
4. Add and start a torrent containing a file that has a size of 4 GiB or larger; for example, by pressing backspace inside the client and entering `/path/to/torrent_file`
5. Wait until the file’s data is downloaded completely and rTorrent initiates the hash check

See the section below for configuration details.

System information
==================

Hardware: Raspberry Pi 3B (revision 1.2)

`mergerfs -V`:
```
mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.3
using FUSE kernel interface version 7.19
```

`/etc/fstab`:
```fstab
UUID=032e16d0-ec79-4ead-a895-7e2401f45f6f /media/Phantomile ext4          defaults                                                            0 0
UUID=b8aa0f4a-3e4a-47b5-bdfc-fd695b017cbd /media/Lunatea    ext4          defaults                                                            0 0
/media/Phantomile:/media/Lunatea          /media/drives     fuse.mergerfs minfreespace=20G,defaults,allow_other,use_ino,dropcacheonclose=true 0 0
```

`uname -a`:
```
Linux osmc 4.4.50v7-aufs #1 SMP Wed Mar 8 12:18:30 CET 2017 armv7l GNU/Linux
```
rTorrent version: 0.9.7
libtorrent version: 0.13.7

`.rtorrent.rc`:
```
method.insert = cfg.basedir, private|const|string, (cat,"/home/osmc/.rtorrent/")
method.insert = cfg.watch,   private|const|string, (cat,"/media/drives/Torrent/.watch/")
method.insert = cfg.logs,    private|const|string, (cat,(cfg.basedir),"log/")
method.insert = cfg.logfile, private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
method.insert = cfg.session,  private|const|string, (cat,(cfg.basedir),"session/")
method.insert = cfg.download, private|const|string, (cat,"/media/drives/Torrent/")

dht.mode.set = disable
protocol.pex.set = no
trackers.numwant.set = 40
trackers.use_udp.set = yes
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

throttle.max_downloads.global.set = 80
throttle.max_uploads.global.set = 80
throttle.max_downloads.set = 20
throttle.max_uploads.set = 20
throttle.min_peers.normal.set = 39
throttle.max_peers.normal.set = 40
throttle.min_peers.seed.set = 39
throttle.max_peers.seed.set = 40
throttle.global_down.max_rate.set_kb = 10000
throttle.global_up.max_rate.set_kb = 3000

pieces.preload.type.set = 2
pieces.sync.always_safe.set = 1

network.port_range.set = 51999-51999
network.port_random.set = no
network.http.max_open.set = 50
network.max_open_files.set = 600
network.max_open_sockets.set = 300
network.receive_buffer.size.set =  4M
network.send_buffer.size.set = 12M
pieces.memory.max.set = 1800M
network.xmlrpc.size_limit.set = 2M

session.path.set = (cat, (cfg.session))
directory.default.set = (cat, (cfg.download))
execute.nothrow = sh, -c, (cat, "echo >",\
    (session.path), "rtorrent.pid", " ",(system.pid))

encoding.add = utf8
system.umask.set = 0027
system.cwd.set = (directory.default)
network.http.dns_cache_timeout.set = 25
pieces.hash.on_completion.set = yes

method.insert = system.startup_time, value|const, (system.time)
method.insert = d.data_path, simple,\
    "if=(d.is_multi_file),\
        (cat, (d.directory), /),\
        (cat, (d.directory), /, (d.name))"
method.insert = d.session_file, simple, "cat=(session.path), (d.hash), .torrent"
method.set_key = event.download.finished, organize_and_notify, "execute = /usr/bin/env, python, /home/osmc/rt_o$

schedule2 = watch_start, 5, 5, ((load.start_verbose, (cat, (cfg.watch), "*.torrent")))

network.scgi.open_local = (cat,(session.path),rpc.socket)
execute.nothrow = chmod,770,(cat,(session.path),rpc.socket)

log.execute = (cat, (cfg.logs), "execute.log")
log.xmlrpc = (cat, (cfg.logs), "xmlrpc.log")
print = (cat, "Logging to ", (cfg.logfile))
log.open_file = "log", (cfg.logfile)
log.add_output = "debug", "log"
```
___

Running the setup described above, I took an strace of both rTorrent and mergerfs, from when the automatic hash check begins, to when the check has completed with the error. I emailed the traces to @trapexit.

**Comment by trapexit** [comment]
This appears to be a kernel bug. I've reached out to the linux-fsdevel mailinglist.

**Comment by trapexit** [comment]
https://marc.info/?l=linux-fsdevel&m=155550785230874&w=2

I'll try to test the patch tonight and provide feedback. If this fixes it it should show up in all current stable releases.

**Comment by trapexit** [comment]
The patch works. You'll need to either wait for the patch to show up in a future release of the kernel or build a new kernel module with the patch yourself.

**Comment by trapexit** [comment]
@Igetin Just got word that the patch will be in the next patches for 4.4, 4.9, 4.14, 4.19, 5.0, and 5.1. Looks like that should cover you.
