### ISSUE TITLE
Issue in mounting mergerfs folder

### ISSUE THREAD

**Issue by kevindd992002** [trapexit/mergerfs#600]
General description
===================
So I'm following this guide: https://blog.linuxserver.io/2017/06/24/the-perfect-media-server-2017/ in trying to create my home media server using mergerfs plus snapraid. I'm stuck at the point where I need to mount the drives and the mergerfs pool by editing fstab. Here's what I have in fstab:

/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7HJVDDRF-part1 /mnt/parity1 ext4 defaults 0 0
/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7HJWSH1F-part1 /mnt/disk1 ext4 defaults 0 0

/mnt/disk* /mnt/storage fuse.mergerfs direct_io,defaults,allow_other,use_ino,minfreespace=50G,fsname=mergerfs 0 0

Issuing a df -h, I see that the disk1 and parity1 mount points are successfully created. But for the mergerfs mount, I have this error:

mount: wrong fs type, bad option, bad superblock on /mnt/disk*,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

What do I need to do? Thanks.

Expected behavior
=================
mergerfs pool gets mounted properly.

Actual behavior
===============
After issuing mount -a, I get this error:

mount: wrong fs type, bad option, bad superblock on /mnt/disk*,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Precise** steps to reproduce the behavior
===========================================
Edit fstab to include this /mnt/disk* /mnt/storage fuse.mergerfs direct_io,defaults,allow_other,use_ino,minfreespace=50G,fsname=mergerfs 0 0 and it should error out when issuing mount -a

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
    mergerfs version: 2.18.0
    FUSE library version: 2.9.7
    using FUSE kernel interface version 7.19

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
`# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda2 during installation
UUID=19f7b5b3-ce66-4795-9232-fa970eb88010 /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda1 during installation
UUID=1881-1A0B  /boot/efi       vfat    umask=0077      0       1
# /home was on /dev/sda6 during installation
UUID=a09f15e7-ad9f-4eec-be31-18d48debcbe2 /home           ext4    defaults        0       2
# /tmp was on /dev/sda5 during installation
UUID=55944ad3-65ba-4060-9bae-b634c91fa822 /tmp            ext4    defaults        0       2
# /var was on /dev/sda3 during installation
UUID=ea841688-fa3d-4688-800c-c98e3e8c9cfe /var            ext4    defaults        0       2
# swap was on /dev/sda4 during installation
UUID=1afad8b0-4c72-45f4-b32f-c305257ba5f6 none            swap    sw              0       0

# data/parity drive mount points
/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7HJVDDRF-part1 /mnt/parity1 ext4 defaults 0 0
/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7HJWSH1F-part1 /mnt/disk1 ext4 defaults 0 0

# mergerfs mount point
/mnt/disk* /mnt/storage fuse.mergerfs direct_io,defaults,allow_other,use_ino,minfreespace=50G,fsname=mergerfs 0 0
`
* [ ] Linux version: `uname -a`
    Linux epsilon 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux
* [ ] Versions of any additional software being used
    N/A
* [ ] List of drives, filesystems, & sizes: `df -h`
    `Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           782M  8.6M  773M   2% /run
/dev/sda2        23G  1.3G   21G   6% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda1       511M  132K  511M   1% /boot/efi
/dev/sda5       1.9G  5.7M  1.7G   1% /tmp
/dev/sda3       9.2G  246M  8.4G   3% /var
/dev/sda6       192G   61M  182G   1% /home
tmpfs           782M     0  782M   0% /run/user/1000
/dev/sdc1       7.3T   93M  6.9T   1% /mnt/parity1
/dev/sdb1       7.3T   93M  6.9T   1% /mnt/disk1
`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
    Not sure how to do this or if even required. Please advise.
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
    Not sure how to do this or if even required. Please advise.

**Comment by trapexit** [comment]
Do you have mount.fuse installed?

**Comment by kevindd992002** [comment]
I'm sorry as I'm a Linux noob and am simply following the linuxerver.io guide. How do I check if mount.fuse is installed? In your NOTE, it does say that the it is included in any Ubuntu/Debian Linux OS. I use the latest version of Debian (Stretch 9.8) and just upgraded its kernel to 4.19 so I'm assuming I have mount.fuse but I still want to confirm. Nowhere in the linuxserver.io guide did the author say to explicitly install mount.fuse.

**Comment by kevindd992002** [comment]
For what it's worth, I have only one data disk and one data parity for now. After I set all this up, I will migrate the data from another HDD over to this new media server and will include the drive where the data came from to the pool.

Question: Can mergerfs work with just one data disk?

**Comment by trapexit** [comment]
```
$ which mount.fuse
/sbin/mount.fuse

$ sudo apt install fuse
```

> Can mergerfs work with just one data disk?

Yes. It works with N where N >= 1.

**Comment by kevindd992002** [comment]
> 
> 
> ```
> $ which mount.fuse
> /sbin/mount.fuse
> 
> $ sudo apt install fuse
> ```
> 
> > Can mergerfs work with just one data disk?
> 
> Yes. It works with N where N >= 1.
> 
> > Nowhere in the linuxserver.io guide did the author say to explicitly install mount.fuse
> 
> That's just a 3rd party's guide. You should always check the actual project docs.

There you go! I didn't have mount.fuse after all. After running "apt install fuse", I have mount.fuse now.

Since I already have "fuse/stable 2.9.7-1+deb9u2 amd64" before I run "apt install fuse", did I effectively reinstall that package? Why didn't it have mount.fuse in the first place? I thought doing an apt upgrade will upgrade all components of a package already?

Also, are these mergerFS options enough?

direct_io,defaults,allow_other,use_ino,minfreespace=50G,fsname=mergerfs

What do these practically do? category.create=lfs and moveonenospc=true . I read the description in your website about these but I'm still confused if I need them or not.

**Comment by trapexit** [comment]
I can't speak for your setup. I'd have thought that the mergerfs package would have required fuse package. Regardless, I recommend updating to the most recent release found on the [release page](https://github.com/trapexit/mergerfs/releases).

> Also, are these mergerFS options enough?

Enough for what? 

> I read the description in your website about these but I'm still confused if I need them or not.

What's confusing? I try to make the docs as simple and straight forward as possible. You don't **need** anything. They are options. You choose what you want. If you want the `lfs` policy then yes... you "need" to set it. Otherwise it defaults to `epmfs` as it says in the docs. Though I'd suggest `mfs` for most users. As for `moveonenospace`... again... if you want that feature. It tries to move files to a new drive if the drive runs out of space while writing. That's very unlikely though using `mfs`.

**Comment by kevindd992002** [comment]
Ok, I'm the one at fault here. I read that 3rd party guide again and it does say to install fuse which I did not notice because in their video guide they did not mention installing fuse. Again, my bad. I installed mergerFS 2.25.1 just now.

I guess enough for a basic media server setup. Here are my clarifications:

1. What's a use case for lfs? Why would one want for the system to write a file in a drive with lfs?
2. The description of mfs is this:

Search category: same as epmfs. Action category: same as epmfs. Create category: Pick the drive with the most available free space.

So for the create category, what's the difference from epmfs? They both use the most free space drive, right? Why separate the description for Create category?

3. What's the use of minfreespace for the default epmfs policy?

**Comment by trapexit** [comment]
> What's a use case for lfs?

Someone wants to fill one drive at a time. I don't recall what the specific usecase was.

> what's the difference from epmfs? 

The "ep" part. Hence the name. The whole path preservation feature.

> What's the use of minfreespace for the default epmfs policy?

To limit the perceived size of the drives. Some filesystems don't respond well to filling up.

**Comment by kevindd992002** [comment]
> 
> 
> > What's a use case for lfs?
> 
> Someone wants to fill one drive at a time. I don't recall what the specific usecase was.
> 
> > what's the difference from epmfs?
> 
> The "ep" part. Hence the name. The whole path preservation feature.
> 
> > What's the use of minfreespace for the default epmfs policy?
> 
> To limit the perceived size of the drives. Some filesystems don't respond well to filling up.

I see. Can you give me some examples on how path preserving and non-path preserving policies differ?

And is the 4G default enough (non-problematic) for ext4 filesystems?

**Comment by trapexit** [comment]
> examples

https://github.com/trapexit/mergerfs#path-preservation

> is the 4G default enough (non-problematic) for ext4 filesystems?

Depends on how large your average files are and your total disk space. Generally it's fine hence the default.

**Comment by kevindd992002** [comment]
> https://github.com/trapexit/mergerfs#path-preservation
Right. That's what I've been reading in your documents but I'm still trying to get my head around it. Say, relative to my mergerfs pol directory (in my case, /mnt/storage), I have the folders "Movies" and "Shows", does this mean I have to create those folders manually on each of my data drives so that epmfs will consider them? What if all drives don't have those folders and a user creates both folders under the /mnt/storage pool directory, what will happen?

**Comment by trapexit** [comment]
It means simply that when a file is created the only branches considered are those with relative paths that already exist. Preserve the existing path layout.

Yes, if you want a path to be considered then you'd need to create them.

> What if all drives don't have those folders and a user creates both folders under the /mnt/storage pool directory, what will happen?

It depends on your settings. It happens exactly as described in the docs. Walk through it logically.

1. mkdir /mnt/storage/movies (movies gets created on a drive based on the mkdir policy)
2. mkdir /mnt/storage/shows (shows gets created on a drive based on mkdir policy)

I'm not sure how else to explain these behaviors. They happen exactly as described in the docs. Every function has a policy associated with it. At the time that function happens the policy is run and a branch chosen for the behavior. If you make a directory then `mkdir` is called on whatever branch the policy *you* set it to chooses.
