### ISSUE TITLE
Is there an option to ignore some kind of files

### ISSUE THREAD

**Issue by zzj0311** [trapexit/mergerfs#602]
General description
===================
I'm new to mergerfs and I'm asking this because I'm using aria2c to deal with private trackers. aria2c use a small .aria2 file to record info of a download and when it comes to pt, it would be modified quiet frequent like once a few mins. And here comes the problem, the .aria file is deleted and then created when there's a modify and on default setting, it would then be placed in the disk which has the most space.....while it won't take much time to let them all be placed in one disk when the remained disk space differs, it may be a problem when disk space goes similar.

here's my option: defaults,allow_other,use_ino

As its not a bug, seems it's not necessary for me to provide my environment at this time

Expected behavior
=================
.aria2 files always placed where it firstly created

Actual behavior
===============
it goes to the disk with the most space

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.
download bittorrent with aria2c with option "seed-ratio=0.0"

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ ] Linux version: `uname -a`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
No. There is no per file customization. I don't understand... why you care which drive it ends up on?

**Comment by zzj0311** [comment]
All right, thanks. And it actually matters when there's a disk failure, I may only lose .aria2 file and have to resume maually...

**Comment by trapexit** [comment]
mergerfs doesn't keep you from needing backups. You could just as well have corruption too which isn't dependent on cross device issues. If you want to colocate files you can use path preservation but seems like more effort than it's worth in this case.
