### ISSUE TITLE
Best data migration procedure

### ISSUE THREAD

**Issue by kevindd992002** [trapexit/mergerfs#604]
General description
===================
As the title says, what is the best data migration procedure for my new media server that is described below:

1.) 2 x 8TB drives -> one is already configured in a mergerfs pool, and one is configured as a parity drive with snapRAID 
2.) 1 x 3TB drives -> this drive is still in an old Windows computer that has all my movies/shows media files

The 3TB drive will be joined to the mergerfs pool after data migration. How do I migrate the data so that it will respect my mergerfs options? Some choices I have in mind:

1.) Transfer over the network from the Windows computer to the media server via SMB -> data will all reside in the 8TB data drive and when I join the empty 3TB drive to the pool, it will remain empty, so the 2-disk array will not be balanced. Also, this will be slow.

2.) Connect the 3TB drive to the media server, mount it (can Debian mount NTFS partitions?), transfer the data to the 8TB drive, format the 3TB drive to ext4 and join it to the pool -> data will also be imbalanced but this is way faster than option 1

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`

```
mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda2 during installation
UUID=19f7b5b3-ce66-4795-9232-fa970eb88010 /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda1 during installation
UUID=1881-1A0B  /boot/efi       vfat    umask=0077      0       1
# /home was on /dev/sda6 during installation
UUID=a09f15e7-ad9f-4eec-be31-18d48debcbe2 /home           ext4    defaults        0       2
# /tmp was on /dev/sda5 during installation
UUID=55944ad3-65ba-4060-9bae-b634c91fa822 /tmp            ext4    defaults        0       2
# /var was on /dev/sda3 during installation
UUID=ea841688-fa3d-4688-800c-c98e3e8c9cfe /var            ext4    defaults        0       2
# swap was on /dev/sda4 during installation
UUID=1afad8b0-4c72-45f4-b32f-c305257ba5f6 none            swap    sw              0       0

# data/parity drive mount points
/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7HJVDDRF-part1 /mnt/parity1 ext4 defaults 0 0
/dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7HJWSH1F-part1 /mnt/disk1 ext4 defaults 0 0

# mergerfs mount point
/mnt/disk* /mnt/storage fuse.mergerfs direct_io,defaults,allow_other,use_ino,minfreespace=50G,fsname=mergerfs 0 0
```

* [ ] Linux version: `uname -a`

`Linux epsilon 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux`

* [ ] Versions of any additional software being used

N/A

* [ ] List of drives, filesystems, & sizes: `df -h`

```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           782M  8.9M  773M   2% /run
/dev/sda2        23G  1.6G   21G   8% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
mergerfs        7.3T   93M  6.9T   1% /mnt/storage
/dev/sda1       511M  132K  511M   1% /boot/efi
/dev/sda3       9.2G  415M  8.3G   5% /var
/dev/sda6       192G   61M  182G   1% /home
/dev/sda5       1.9G  5.7M  1.7G   1% /tmp
/dev/sdc1       7.3T   93M  6.9T   1% /mnt/parity1
/dev/sdb1       7.3T   93M  6.9T   1% /mnt/disk1
tmpfs           782M     0  782M   0% /run/user/1000
```

**Comment by trapexit** [comment]
I'd do 2. You can use something like mergerfs.balance (https://github.com/trapexit/mergerfs-tools) to split files across the two drives afterwards.

**Comment by kevindd992002** [comment]
That's what I thought. Thanks, I'll try that. As to any instructions to adding a new drive in an existing pool, do you have any documentations regarding that?

**Comment by trapexit** [comment]
The main docs cover all the config and runtime options. Just add the path to the fstab and you can use the runtime interface to change at runtime if you wish.

**Comment by kevindd992002** [comment]
Ok, I'm done with migrating the data from the 3TB standalone drive to the 8TB pool. I'm having issues using xattr to include the new drive to the pool during runtime. It says xattr command is not found even though I already installed python-xattr and python3-xattr which I read from another guide is the correct package to install for that command. Which between the two is the correct one and should I only keep one in my system?

**Comment by trapexit** [comment]
I don't know. What distro are you using? You can just use mergerfs.ctl as well.

**Comment by kevindd992002** [comment]
I'm using Debian. python, python2, and python3 are all installed but I still cannot get that xattr command. Yeah, I guess I can try mergerfs.ctl and see if that works. It's just weird why the xattr command isn't present even though I already installed it, and I even tried rebooting with no success.

**Comment by trapexit** [comment]
python-xattr and python3-xattr are NOT the packages for the *tool* xattr. The package `xattr` is.

```
$ apt-file search /usr/bin/xattr
xattr: /usr/bin/xattr
```

**Comment by kevindd992002** [comment]
Then I guess this guide: https://zackreed.me/mergerfs-neat-tricks/ is wrong again. Like I said, I came from Windows and I'm still learning my way around Linux so I'm not sure if a reboot would do anything at all.

**Comment by trapexit** [comment]
I knew you were using Windows but didn't realize you were new to Linux. Obviously dealing with something as low level as a filesystem requires a bit of familiarity. I'll see if I can add a bit to the docs regarding the xattr tool but each distro is different.

**Comment by kevindd992002** [comment]
Right, I may have left that bit of info out on my earlier thread. It's never too late to start getting familiar with Linux.
