### ISSUE TITLE
File creation fails with "no space left"

### ISSUE THREAD

**Issue by doak** [trapexit/mergerfs#607]
General description
===================

Several branches (located on the very same filesystem) are merged into one pool. File creation within pool fails due of "no space left", although 4 GB are free. Furthermore, version 2.24.2 **works** like expected.
It fails nevertheless for current master (2.25.1-70-g85e2a3e) as well as for 2.25.1.

I am wondering why this behaviour suddenly popped up (on my machine), since I had no such issues in the past and it seem to be very fundamental.

I have plenty of inodes left by the way. That is the reason for opening a new issue, #598 seems to be different.

Expected behavior
=================

File is created without error.

Actual behavior
===============

`touch` fails with "no space left".

**Precise** steps to reproduce the behavior
===========================================

    #!/usr/bin/env bash
    
    prepare() {
        rm -rf branch1 branch2 branch3 &&
        mkdir -p branch1 branch2 branch3 &&
        mkdir -p MERGED &&
        trap "fusermount -u MERGED" EXIT &&
        mergerfs branch1:branch2:branch3 MERGED &&
        true
    }
    
    validate() {
        touch MERGED/test-file ||
        warn "File 'MERGED/test-file' can't be created."
    }
    
    error() {
        echo "ERR: $*" >&2
        exit 1
    }
    
    warn() {
        local errcode=$?
        echo "WRN: $*" >&2
        return $errcode
    }
    
    
    prepare ||
    error "Preparation failed."
    
    validate ||
    error "Unexpected behaviour."

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`

        mergerfs version: 2.25.1-70-g85e2a3e
        FUSE library version: 2.9.7-mergerfs_2.26.0
        fusermount version: 2.9.9
        using FUSE kernel interface version 7.27
   
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [x] Linux version: `uname -a`

         Linux flatbox 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux

* [ ] Versions of any additional software being used
* [x] List of drives, filesystems, & sizes: `df -h`

        doak@flatbox:~/tmp/mergerfs$ df -h
        Filesystem                Size  Used Avail Use% Mounted on
        udev                      5,8G     0  5,8G   0% /dev
        tmpfs                     1,2G  1,2M  1,2G   1% /run
        /dev/mapper/debian-crypt  201G  187G  4,0G  98% /
        tmpfs                     5,9G  178M  5,7G   3% /dev/shm
        tmpfs                     5,0M  4,0K  5,0M   1% /run/lock
        tmpfs                     5,9G     0  5,9G   0% /sys/fs/cgroup
        /dev/sda2                 181M  125M   43M  75% /boot
        /dev/sda1                 476M  5,1M  470M   2% /boot/efi
        tmpfs                     1,2G  8,0K  1,2G   1% /run/user/1000
        doak@flatbox:~/tmp/mergerfs$ df -i
        Filesystem                 Inodes  IUsed    IFree IUse% Mounted on
        udev                      1519474    479  1518995    1% /dev
        tmpfs                     1524619    730  1523889    1% /run
        /dev/mapper/debian-crypt 13434880 990906 12443974    8% /
        tmpfs                     1524619    139  1524480    1% /dev/shm
        tmpfs                     1524619      3  1524616    1% /run/lock
        tmpfs                     1524619     17  1524602    1% /sys/fs/cgroup
        /dev/sda2                   48960    340    48620    1% /boot
        /dev/sda1                       0      0        0     - /boot/efi
        tmpfs                     1524619     22  1524597    1% /run/user/1000

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
How many bytes? Precisely.

The default for minfreespace is 4GiB. 2*30 * 4 = 4294967296. All branches are on the same drives with the same free space which is likely less than 4GiB. As the docs [say](https://github.com/trapexit/mergerfs#filters): _If all branches are filtered an error will be returned. Typically EROFS or ENOSPC depending on the reasons._

It "works" in prior versions because it was a bug. It didn't model the documentation.

**Comment by doak** [comment]
You are very right. I am sorry, I was blended by "working previously" and didn't check the default value for `minfreespace` (though documentation is very clear about it).
Sorry for interruption.
