### ISSUE TITLE
Cannot create a file if existing target is RO, but another target is available

### ISSUE THREAD

**Issue by ybznek** [trapexit/mergerfs#608]
General description
===================
I merge two directories using mergerfs, 1st one is RO, 2nd one is RW.

When I want to create a file in a path which is available only in RO directory, it is not created, because the same path not exists in RW directory. I tried various *create* policy but without effect

Expected behavior
=================
mergerfs will create a directory tree in RW folder, so file can be saved, sth like (mkdir -p /tmp/rw/b/c)

Actual behavior
===============
Permission denied

**Precise** steps to reproduce the behavior
===========================================
mkdir -p /tmp/ro/b/c # create RO directory
chmod -R -w /tmp/ro/b
mkdir /tmp/rw # create RW directory
mkdir /tmp/target # create target directory
mergerfs /tmp/ro:/tmp/rw /tmp/target # mount
touch /tmp/target/b/c/new_file # create a new file => Permission denied

System information
==================
mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.9
using FUSE kernel interface version 7.19

Linux frank 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by trapexit** [comment]
You're not understanding how it works.

https://github.com/trapexit/mergerfs#filters

```
All create policies will filter out branches which are mounted read-only, tagged RO (read-only) or NC (no create), or has available space less than minfreespace.
```

A *mount* has to be read-only or tagged as such. It has nothing to do with "read-only" directories which is a different thing all together. It's not about general permissions.

Try the following.

```
$ mergerfs /tmp/ro=RO:/tmp/rw /tmp/target
```
