### ISSUE TITLE
2.26 breaks -fsname= option?

### ISSUE THREAD

**Issue by Wintersdark** [trapexit/mergerfs#613]
General description
===================
Since upgrading to the 2.26 bionic amd64 release, my fsname'd pools have reverted to color-separated device lists.  Not a big deal, just messy when you've got lots of drives.

Expected behavior
=================
df -h should show the fsname entry under "Filesystem"

Actual behavior
===============
df -h shows the colon separated default list of devices used in a mount.

`derrick@tuna:~$ cat /etc/fstab | grep fsname
/mnt/chip*:/mnt/brick*                                  /mnt/pool       fuse.mergerfs   defaults,allow_other,use_ino,dropcacheonclose=true,noforget,minfreespace=16G,moveonenospc=true,category.create=ff,func.getattr=newest,fsname=pool       2       3

/mnt/chip*                                              /mnt/cache      fuse.mergerfs   defaults,allow_other,use_ino,dropcacheonclose=true,noforget,minfreespace=4G,moveonenospc=true,category.create=mfs,func.getattr=newest,fsname=cache      2       3

/mnt/brick*                                             /mnt/archive    fuse.mergerfs   defaults,allow_other,use_ino,dropcacheonclose=true,noforget,minfreespace=16G,moveonenospc=true,category.create=lus,func.getattr=newest,fsname=archive   2       3
`

`derrick@tuna:~$ df -h
Filesystem                                                                                                                                                                    
Size  Used Avail Use% Mounted on

udev                                                                                                                                                                           12G     0   12G   0% /dev

tmpfs                                                                                                                                                                         2.4G  2.6M  2.4G   1% /run

/dev/sdo1                                                                                                                                                                      51G   33G   16G  68% /

tmpfs                                                                                                                                                                          12G  8.0K   12G   1% /dev/shm

tmpfs                                                                                                                                                                         5.0M     0  5.0M   0% /run/lock

tmpfs                                                                                                                                                                          12G     0   12G   0% /sys/fs/cgroup

1:2:3                                                                                                                                                                         1.2T  403G  704G  37% /mnt/cache

chip01:chip02:chip03:brick01:brick02:brick03:brick04:brick05:brick06:brick07:brick08:brick09:brick10:brick11:brick12:brick13:brick14:brick15:brick16:brick17:brick18:brick19   53T   47T  3.7T  93% /mnt/pool

01:02:03:04:05:06:07:08:09:10:11:12:13:14:15:16:17:18:19                                                                                                                       52T   47T  3.1T  94% /mnt/archive

/dev/sdaa                                                                                                                                                                     1.8T  1.7T   49G  98% /mnt/brick09

/dev/sdab                                                                                                                                                                     1.8T  1.7T   50G  98% /mnt/brick08

/dev/sdy                                                                                                                                                                      1.9T  1.8T   76G  96% /mnt/brick05

/dev/sdc                                                                                                                                                                      535G   26G  482G   5% /mnt/scratch

/dev/sdw                                                                                                                                                                      932G  916G   16G  99% /mnt/brick03

/dev/sdv                                                                                                                                                                      550G  507G   16G  98% /mnt/brick15

/dev/sdq                                                                                                                                                                      2.8T  2.7T   35G  99% /mnt/brick02

/dev/sdb                                                                                                                                                                      823G  108G  673G  14% /mnt/chip03

/dev/sda                                                                                                                                                                      549G   19G  503G   4% /mnt/plex

/dev/sdu                                                                                                                                                                      916G  855G   16G  99% /mnt/brick14

/dev/sde                                                                                                                                                                      7.3T  6.6T  315G  96% /mnt/brick18

/dev/sdp                                                                                                                                                                      2.8T  2.7T  131G  96% /mnt/brick01

/dev/sdx                                                                                                                                                                      1.9T  1.8T   78G  96% /mnt/brick04

/dev/sdm                                                                                                                                                                      234G  207G   15G  94% /mnt/chip02

/dev/sdf                                                                                                                                                                      7.3T  6.6T  315G  96% /mnt/brick19

/dev/sdz                                                                                                                                                                      1.9T  1.8T   79G  96% /mnt/brick06

/dev/sds                                                                                                                                                                      3.6T  3.1T  318G  91% /mnt/brick10

/dev/sdi                                                                                                                                                                      3.6T  3.1T  317G  91% /mnt/brick13

/dev/sdn                                                                                                                                                                      110G   88G   16G  85% /mnt/chip01

/dev/sdt                                                                                                                                                                      3.6T  3.1T  317G  91% /mnt/brick11

/dev/sdg                                                                                                                                                                      3.6T  3.1T  313G  92% /mnt/brick12

/dev/sdj                                                                                                                                                                      2.7T  2.3T  314G  88% /mnt/brick17

/dev/sdh                                                                                                                                                                      2.7T  2.3T  317G  88% /mnt/brick16

tmpfs                                                                                                                                                                         2.4G     0  2.4G   0% /run/user/1000
`

**Precise** steps to reproduce the behavior
===========================================

Just run df -h with -fsname= mergerfs mounts

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V` 
`derrick@tuna:~$ mergerfs -V
mergerfs version: 2.26.0
FUSE library version: 2.9.7-mergerfs_2.26.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.27
`

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
See above in actual behavior.

* [ ] Linux version: `uname -a`
`derrick@tuna:~$ uname -a
Linux tuna 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

* [ ] List of drives, filesystems, & sizes: `df -h` 
See above in actual behavior.

**Comment by trapexit** [comment]
Oops. I'll take a look.
