### ISSUE TITLE
Couple of usage questions

### ISSUE THREAD

**Issue by IronicBadger** [trapexit/mergerfs#618]
General description
===================
Hi trapexit, hope you're doing ok these days. 

I've recently started putting a lot more of my irreplaceable data onto a zfs mirror. I'd like to mount this under mergerfs but enforce that the paths created are only ever on existing path. 

So, is presenting a zfs filesystem via mergerfs fine? I tend to write primarily to the direct path not the fuse one but some apps like samba go via fuse. What gotchas might there be.

**Comment by trapexit** [comment]
> So, is presenting a zfs filesystem via mergerfs fine?

Sure. It'll work like any other filesystem. What's the concern?

**Comment by IronicBadger** [comment]
Yes, sorry I didn't explain fantastically well.

* `/mnt/storage` is the main fuse mount point mergerfs looks at.
* `/mnt/tank/fuse` is the zfs filesystem
* `/mnt/disk1-9` are my traditional data disks as covered the blog post on LSIO a couple of years back

```
# The main fstab entry
/mnt/disk*:/mnt/tank/fuse /mnt/storage fuse.mergerfs defaults,allow_other,direct_io,use_ino,hard_remove,minfreespace=250G,fsname=mergerfs 0 0
```

Any files on `/mnt/tank/fuse` have been placed there deliberately, at least the high level directories anyway. Typically ZFS contains things like photos, docs, music and other irreplaceable stuff where as `/mnt/disk*` formatted to ext4 is media which I'm less bothered about.

Mergerfs must not be allowed to create any directories on `/mnt/storage` which exist on `/mnt/tank/fuse`. By using defaults with `epmfs` I believe this to be the case until the ZFS filesystem is full (not a likely scenario here but worth considering). I'm sanity checking before writing up a 2019 blog post. Thanks in advance.

**Comment by trapexit** [comment]
Even if you run out of space it wouldn't create paths on other drives (with current versions of mergerfs). It'll return ENOSPC for any create once there aren't any eligible drives due to minfreespace and path filtering. If you haven't looked over the docs recently I'd suggest doing so. There's a decent number of features since your original article.

**Comment by IronicBadger** [comment]
Wow, yes. Lots of new features. Thanks for all the hard work since then! How do I throw you a bone?

**Comment by trapexit** [comment]
No problem. Have more coming.

https://github.com/trapexit/mergerfs#support-development
