### ISSUE TITLE
MergerFS deleting files in use

### ISSUE THREAD

**Issue by antigravity83** [trapexit/mergerfs#637]
General description
===================
When files are deleted on the original mount, they are also deleted in the MergerFS mount, even if they are open and in use. 

Expected behavior
=================
Wait for file to no long be in use before deleting it. 

Actual behavior
===============
As in General Descriptiom

Is there a way to tell MergerFS to not delete a file until it's no longer in use?

**Comment by trapexit** [comment]
I don't really follow. Files will be unlinked should unlink be called. What do you mean by "no longer in use"?

**Comment by antigravity83** [comment]
My setup is currently this:

/mnt/folder1 (real folder)
/mnt/folder2 (real folder)
/mnt/folder3 (MergerFS folder)

When a file is deleted in folder1, it then deletes (unlinks) from folder3 - which is fine. 

The issue comes when the file being unlinked in folder3 is currently in use (say it's a video file being played). 

When the above happens, the video being played cuts out and errors.

Is there anyway to get around this?

**Comment by trapexit** [comment]
What version are you using?

**Comment by antigravity83** [comment]
2.26.0-dirty

**Comment by trapexit** [comment]
Please, as the support instructions request, use the latest version.

atomic_o_trun,big_writes, and default_permissions are unnecessary.

**Comment by antigravity83** [comment]
Ok thanks I can remove those and update the version. Would that fix the issue I am experiencing though?

**Comment by trapexit** [comment]
I'm not sure but I don't want to spend time debugging an an old, custom built release that has known issues.

**Comment by trapexit** [comment]
You haven't provided me enough information to test the issue so I'm not sure what I can do at this point. There is a template to fill out when you create a ticket so I have enough information to comment.

**Comment by antigravity83** [comment]
Oh sorry, didn't realise it had issues. Will update and get back to you. 

I can see there's some cache options in newer versions.

**Comment by antigravity83** [comment]
Basically just want to know if there's any way to stop MergerFS unlinking files if they are currently being used by another service.

Ie. a cache functionality for open files

**Comment by trapexit** [comment]
> Basically just want to know if there's any way to stop MergerFS unlinking files if they are currently being used by another service.

It's not going to ever do that. Unlinked files should be fully usable. In fact I spent a lot of work recently to make that situation to be more standard. Opening an unlinking is a very normal and standard behavior of *nix filesystems. If you didn't unlink when requested it would break some software. 

I don't understand what you mean by "cache functionality for open files".

**Comment by antigravity83** [comment]
Sorry, maybe I haven't explained my workflow correctly. 

Basically I have Plex running from a MergerFS directory. 

If I'm playing a file from MergerFS, and that file is then renamed/deleted in the native folder, that change is replicated in the MergerFS folder even whilst I'm still playing back that file. 

As a result, playback stops and errors out. 

So I'm trying to stop this from happening. 

In my mind, I was thinking any file that is being played in Plex, from the MergerFS folder, is put into a cache, so that if it is renamed/deleted during playback, playback isn't affected. 

Then once playback has completed, it's removed from the cache, and the rename/deletion is  completed in the MergerFS folder.

**Comment by trapexit** [comment]
You mentioned on reddit it was an rclone mount. Here you're implying it's a local filesystem. It's possible that rclone doesn't properly support continued use of unlinked files. If so that'd be a rclone problem.

**Comment by trapexit** [comment]
Hmm... it seems to me that rclone supports reading unlinked files. Perhaps it's a Plex thing.

**Comment by antigravity83** [comment]
I think the issue

**Comment by antigravity83** [comment]
Thanks. I think the issue is that the file is being renamed/deleted from the Rclone mount, and then MergerFS can no longer reference the original file - as it no longer exists. 

So I might need to run Plex directly from the Rclone mount- I believe Rclone won't update a file on an Rclone mount if it's currently open.

**Comment by trapexit** [comment]
What are your rclone mount settings?

**Comment by trapexit** [comment]
I just mounted mergerfs on rclone, opened a file, read it, unlinked it out of band, reset the index, reread the data, closed it. Worked fine.

**Comment by antigravity83** [comment]
rclone mount plex: ~/files/plex --config ~/.config/rclone/rclone.conf --allow-non-empty --dir-cache-time 72h --drive-chunk-size 32M --log-level INFO --log-file ~/logs/plex.log

**Comment by antigravity83** [comment]
On a computer now - hopefully I can explain it in more detail:

MACHINE 1
- Downloads files
- Renames files and places them into an organised structure
- Copies these folders/files onto 2x rclone mounts
- When a better version of an existing file is found, it deletes the old file off the rclone mount, and replaces it with the improved version (<--- this is where I am getting stuck)

MACHINE 2
- The two above rclone mounts are mounted on this machine
- MergerFS merges these two mounts into a single location
- Plex reads and streams from the MergerFS folder

The problem i'm experiencing occurs when:

- MACHINE 2 is streaming a file from the MergerFS folder in Plex
- MACHINE 1 finds an upgraded version of the file being played on the secondary machine. Machine 1 deletes this file on the rclone mount and copies the upgraded version to the Rclone mount
- The file is deleted from the Rclone Mount and subsequent MergerFS folder on Machine 2. If the file is being streamed by Plex at the time, the stream errors out because the file no longer exists on Machine 2, either in MergerFS or the Rclone mount. 

What I thought would happen - is that the upgraded file wouldn't be deleted from Machine 2 if it was currently being streamed by Plex. RClone would wait for the file to no longer be open, and then delete it

**Comment by trapexit** [comment]
Unlinking is no the problem. An open, unlinked file still should work exactly as any other so long as you're using the file descriptor and not trying to look for the file again. The file itself is different from the name. The file name is just a link. A way to find the file. A file is not truly removed until all links are removed and open file descriptors closed. If Plex is looking at the file again later rather than working on the file descriptor then that's a bug on their side.

**Comment by trapexit** [comment]
If Plex isn't working exclusively on the file descriptor then that may explain the situation and would have nothing to do with rclone. I'll have to check.

**Comment by trapexit** [comment]
Yup. A Plex thing. They seem to reopen the file. I had two file. Played one. Exchanged them atomically. Waited a bit and the other video started playing from that offset into the video. Since they are both encoded the same it doesn't freak out but if that weren't true I'm sure Plex would error out.

**Comment by antigravity83** [comment]
Thanks for your help.

So you were streaming a file via Rclone Mount merged into a MergerFS folder?

I'm curious to see if your playback stops if you delete the file on the Rclone mount mid stream

**Comment by trapexit** [comment]
No. From the local filesystem. 

If you delete the file it errors out once it tries to reopen the file. It must be transcoding / buffering some amount and then reopens for some reason later. That's bad practice and IMO a bug in Plex.
