### ISSUE TITLE
Seeing high CPU after a day or two even on 2.28.0

### ISSUE THREAD

**Issue by keithah** [trapexit/mergerfs#638]
General description
===================
Just updated to latest (2.28.0) and still seeing these issues. It's fine at first but creeps up to 50-80% within a day or two and eventually have to umount/kill processes/remount to get it to be low again. 

I'm sure its a misconfiguration somewhere.. but would love some suggestions, thanks!

I use this as a media store for Plex and have NFS mounted on a few different servers, so theres constant reads and 10-20gb/day in writes.

Machine is a Intel(R) Xeon(R) CPU E5-2630L w/ 8 cores, load is:
 21:50:42 up 8 days,  9:32, 10 users,  load average: 20.10, 20.29, 19.33                                                       

It's Ubuntu 18.04.2, fully updated.

Expected behavior
=================
CPU stays low

Actual behavior
===============
htop:
> 1748 root       10 -10 1380M  238M  2688 S 48.9  0.7  6h18:55 mergerfs /mnt/data* /storage -o rw,category.create=lfs,noforget,

(it'll go as much as 80-90%)

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [X] mergerfs version: `mergerfs -V`
mergerfs version: 2.28.0                                                                                                       
FUSE library version: 2.9.7-mergerfs_2.28.0                                                                                    
fusermount version: 2.9.7                                                                                                      
using FUSE kernel interface version 7.29 
* [X] mergerfs settings: `cat /etc/fstab` or the command line arguments
> /mnt/data*  /storage  fuse.mergerfs  category.create=lfs,defaults,noforget,use_ino,allow_other,direct_io,minfreespace=30G,fsnam
> e=mergerfs,func.getattr=newest,moveonenospc=true  0  0  
* [X] Linux version: `uname -a`
Linux sea 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux                          
* [X] Versions of any additional software being used
snapraid v11.2 by Andrea Mazzoleni, http://www.snapraid.it                                                                     
Plex Media Server 1.15.8
* [X] List of drives, filesystems, & sizes: `df -h`
/dev/sda        3.6T  1.3T  2.2T  36% /mnt/data6                                                                               
/dev/sdc        3.6T  1.1T  2.4T  31% /mnt/data8                                                                               
/dev/sdp        3.6T  2.7T  807G  77% /mnt/data11                                                                              
/dev/sdo        3.6T  893G  2.6T  26% /mnt/data10                                                                              
/dev/sdb        3.6T  2.3T  1.2T  68% /mnt/data7                                                                               
/dev/sdn        3.6T  1.3T  2.2T  37% /mnt/data9                                                                               
/dev/sdi        7.3T  5.7T  1.7T  78% /mnt/data3                                                                               
/dev/sdk        7.3T  7.3T   30G 100% /mnt/data5                                                                               
/dev/sdf        7.3T  6.1T  1.3T  83% /mnt/data0                                                                               
/dev/sdd        7.3T  7.3T   21G 100% /mnt/parity0                                                                             
/dev/sde        7.3T  7.3T   21G 100% /mnt/parity1                                                                             
/dev/sdh        7.3T  7.3T   29G 100% /mnt/data2                                                                               
/dev/sdj        7.3T  7.3T   30G 100% /mnt/data4                                                                               
/dev/sdg        7.3T  7.3T   30G 100% /mnt/data1                                                                               
/dev/sdq        3.6T  2.0T  1.5T  59% /mnt/data12     
/mergerfs         69T   52T   16T  77% /storage

**Comment by trapexit** [comment]
What do you mean by cpu goes up? What's the workload when it is high? Is it high idle? Is it high doing the same exact test? I need more info to comment. The only thing that is atypical is noforget.

**Comment by trapexit** [comment]
Also... Did you look at the "performance" section in the docs and see if any of the options mentioned impact it at all?
