### ISSUE TITLE
Artificial size setting per branch

### ISSUE THREAD

**Issue by irneb** [trapexit/mergerfs#641]
General description
===================
This is definitely just a question / feature request. Unsure if it's already possible, can't seem to find such in mergerfs docs or fuse docs. If there is already a simpler solution, please comment, else I would love to see some way of doing this per my suggestion below.

I'm looking for a way to set a custom maximum size for any one branch. Not a minimum free space overall, but an artificial total size.
ATM I have a work-around using a sparse file, mounted as a "virtual" disk, which I set as a maximum size. These then get mounted as if they're normal partitions, which then get unioned through mergerfs. Meaning I'm "faking" a size for mergerfs to see as the base FS size of the branch.

It does seem like a complete overkill for this. Quite an involved setup just to set a maximum size per branch.

As a side note, the reason I'm doing this is to get a rclone setup using cloud shares as the final destination for the content. In effect I'm setting each of these sparse files as the cache folder to each cloud storage instead of the more normal "just a folder" idea. The trouble with using the normal folder as cache means whatever partition this is saved to tells mergerfs "this is the total size". Likely to be much larger than the cloud's total allowed size and also likely to be on the same partition - meaning same drive is added multiple times over.

I just feel going this workaround route is orders of magnitude too much when all I really wanted is to limit the size of any one branch.

Expected behavior
=================
Set each branch to have a maximum size (similar to the R/RW options). Then mergerfs uses that instead of relying on the underlying FS's info when testing for available size.

I.e. I'm looking for something like an option to the branch such as:
```bash
/path_to_brach1=RW,size=5G:/path_to_branch2=RW,size=2G ...
```

Actual behavior
===============
At the moment mergerfs relies solely on the underlying FS per branch to determine the total size available per branch. No means I can find to adjust this - except the above mentioned work-around using sparse files. Could probably also do it by making "real" partitions of specified size, but that uses space where not really needed.

**Precise** steps to reproduce the behavior
===========================================
The way I have it now:
```bash
sudo mkdir /mnt/cloud
sudo mkdir /mnt/cloud/files
sudo truncate -s 2G /mnt/cloud/files/gdrive1.img
sudo truncate -s 5G /mnt/cloud/files/dropbox1.img
sudo mkfs.ext4 /mnt/cloud/files/gdrive1.img
sudo mkfs.ext4 /mnt/cloud/files/dropbox1.img
sudo mkdir /mnt/cloud/cache_mounts
sudo mkdir /mnt/cloud/cache_mounts/gdrive1
sudo mkdir /mnt/cloud/cache_mounts/dropbox1
```
Then using the fstab as per below. At which point I get the following:
```bash
irne@base1:~$ ls -l /mnt/cloud/union/
total 0
-rw-rw-rw- 1 root root 0 Jun 15 12:54 test1.txt
-rw-rw-rw- 1 root root 0 Jun 15 13:05 test2.txt
-rw-rw-rw- 1 root root 0 Jun 15 13:05 test3.txt
-rw-rw-r-- 1 irne irne 0 Jun 15 13:27 test4.txt
-rw-rw-r-- 1 irne irne 0 Jun 15 13:27 test5.txt
irne@base1:~$ ls -l /mnt/cloud/cache_mounts/gdrive1/
total 0
-rw-rw-rw- 1 root root 0 Jun 15 12:54 test1.txt
-rw-rw-rw- 1 root root 0 Jun 15 12:54 test3.txt
-rw-rw-r-- 1 irne irne 0 Jun 15 13:27 test4.txt
irne@base1:~$ ls -l /mnt/cloud/cache_mounts/dropbox1/
total 0
-rw-rw-rw- 1 root root 0 Jun 15 13:05 test2.txt
-rw-rw-rw- 1 root root 0 Jun 15 13:05 test3.txt
-rw-rw-r-- 1 irne irne 0 Jun 15 13:27 test5.txt
```

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version:
```bash
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.9; using FUSE kernel interface version 7.19
```
* [ ] mergerfs settings:
```bash
# Cloud mounts
/mnt/cloud/files/gdrive1.img /mnt/cloud/cache_mounts/gdrive1 auto loop,defaults,allow_other 0 0
/mnt/cloud/files/dropbox1.img /mnt/cloud/cache_mounts/dropbox1 auto loop,defaults,allow_other 0 0
/mnt/cloud/cache_mounts/* /mnt/cloud/union fuse.mergerfs defaults,nonempty,_netdev,allow_other,direct_io,use_ino,category.action=all,category.create=rand,category.search=newest,moveonenospc=true,minfreespace=20M,fsname=cloud 0 0
```
* [ ] Linux version: `Linux base1 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* [ ] Versions of any additional software being used: `N/A`
* [ ] List of drives, filesystems, & sizes: `df -h`
```bash
/dev/loop4      2.0G  6.0M  1.8G   1% /mnt/cloud/cache_mounts/gdrive1
/dev/loop5      4.9G   20M  4.6G   1% /mnt/cloud/cache_mounts/dropbox1
cloud           6.8G   26M  6.4G   1% /mnt/cloud/union
```

**Comment by trapexit** [comment]
You could also use LVM (or possibly filesystem quotas) too.

The problem with doing it in mergerfs is that I'd have to audit all the functions to enforce the faux size. It'd be a lot of work for a very niche feature. This isn't just overriding the values from `statfs`. It's keeping track of all files in the branch path, aggregating their sizes for use in the new faked `statfs`, enforcing the size limit at `write`, etc.

Once you setup your loopback devices isn't that it? It's a one time cost. It doesn't seem like something you'd be changing regularly.

**Comment by irneb** [comment]
Agreed. It would really only be a nice to have - probably outweighed by possible problems on the mergerfs / fuse side of things. You're right about the loop devices. It's only a once off thing, so even if it does seem excessive - it doesn't happen every day.

**Comment by trapexit** [comment]
If it weren't a PITA to implement I'd be happy to do so but like I said there isn't a way to manage the size without rewriting mergerfs to actually track files. Most things in mergerfs are stateless... leaving state management to the filesystem. Most filesystems don't have quotas or way to determine the aggregate size of a directory.
