### ISSUE TITLE
Writing to read-only branch

### ISSUE THREAD

**Issue by jmbraben** [trapexit/mergerfs#642]
General description
===================
I have two branches merged. One is RO, one is RW...I am able to modify files on the RO branch

Expected behavior
=================
I would expect no possibility of modifying RO branch files

Actual behavior
===============
I am modifying RO branch files

**Precise** steps to reproduce the behavior
===========================================
First, let me apologize if I am missing something obvious, but based on:

- All action policies will filter out branches which are mounted read-only or tagged as RO (read-only).
- All create policies will filter out branches which are mounted read-only, tagged RO (read-only) or NC (no create), or has available space less than minfreespace.

I am confused.
Here is what I am doing:

# create files on source drives
```
?@ubuntu-virtual:jmbraben:/media
$ echo located on disk3 > disk3/file.txt
?@ubuntu-virtual:jmbraben:/media
$ echo located on disk2 > disk2/file.txt
```
# mount merged 
```
?@ubuntu-virtual:jmbraben:/media
$ mergerfs -o allow_other,use_ino /media/disk2:/media/disk3=RO /media/merged
```
# display contents of files
```
?=1@ubuntu-virtual:jmbraben:/media
$ cat merged/file.txt 
located on disk2
?@ubuntu-virtual:jmbraben:/media
$ echo modify from merged > merged/file.txt
?@ubuntu-virtual:jmbraben:/media
$ cat merged/file.txt 
modify from merged
?@ubuntu-virtual:jmbraben:/media
$ cat disk2/file.txt 
modify from merged
?@ubuntu-virtual:jmbraben:/media
$ cat disk3/file.txt 
located on disk3
```
# remove the rewritable file (and try to remove read-only file)
```
?@ubuntu-virtual:jmbraben:/media
$ rm merged/file.txt 
?@ubuntu-virtual:jmbraben:/media
$ cat merged/file.txt 
located on disk3
?@ubuntu-virtual:jmbraben:/media
$ rm merged/file.txt 
rm: cannot remove 'merged/file.txt': Read-only file system
```
# everything is as expected until here
# modify the merged file...I would expect either "create new file" at disk 2, or to fail as "read-only"
```
?@ubuntu-virtual:jmbraben:/media
$ echo modify from merged > merged/file.txt
?@ubuntu-virtual:jmbraben:/media
$ cat merged/file.txt 
modify from merged
?@ubuntu-virtual:jmbraben:/media
$ cat disk3/file.txt 
modify from merged
?@ubuntu-virtual:jmbraben:/media
$ ls -la disk3/file.txt 
-rw-r--r-- 1 jmbraben jmbraben 19 Jun 17 11:30 disk3/file.txt
?@ubuntu-virtual:jmbraben:/media
$ ls -la disk2/file.txt 
ls: cannot access 'disk2/file.txt': No such file or directory
?=1@ubuntu-virtual:jmbraben:/media
```
# Modifying the read-only disk3 branch does not seem like proper behavior
#...please help me understand

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
$ mergerfs -v
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.29

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
mergerfs -o allow_other,use_ino /media/disk2:/media/disk3=RO /media/merged

* [ ] Linux version: `uname -a`
Linux ubuntu-virtual 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
$ df -h | grep sd
/dev/sda1        32G  8.8G   21G  30% /
/dev/sdb1       3.6T  3.5G  3.4T   1% /media/disk2
/dev/sdc1       458G   21G  414G   5% /media/disk3

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt
[app.strace.txt](https://github.com/trapexit/mergerfs/files/3298040/app.strace.txt)
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/3298041/mergerfs.strace.txt)

`

**Comment by trapexit** [comment]
You've created files out of band. The file is 'open'ed. Not 'create'd. `open` is a search, not a create. The point of RO tagging was not to make the filesystem actually read only. That's what mounting `ro` does. It was to add filtering to certain policies.

**Comment by jmbraben** [comment]
So the reason I wanted the behavior was to share information with a container...I'd like to be able to mount the merge directory and allow the container to "contribute" to the merge via the r/w branch, but in no case would I want the container to modify the ro branch...periodically, the container r/w contents would be moved to the ro branch (by external agent). These same input branches are used by other containers also (via mergerfs but both branches ro). By using mergefs, the "contributing" container has no idea that its contributed content has moved to the ro branch. I can make the ro branch truly a ro mount (through bindfs for example), but I was under the misunderstanding that mergefs accomplished that already and this was not necessary (based upon "_RO will exclude those paths from create and action policies (just as a filesystem being mounted ro would)_". But I do see that "open" is under "search" policies...

To be clear than, by tagging an input as "ro", the intent is not to make the branch "immutable" but to limit policy...which currently does not include "fopen (w, w+, a, a+)" ...all of which can modify the "ro" branch. 
If you did filter the "fopen(w,w+,a,a+)"...would the policy than create the file on the r/w branch? (as the policy limitation would remove the "ro" branch from consideration...this would be my expected behavior btw)
If you did make this change, would you consider the branches to be truly "read-only"? Or would you be concerned there is still possibility for modification? I was ransomwared last fall (everything encrypted)...so I'm a bit "cautious" now to say the least.

In my (probably naive) thinking, I was imagining mergerfs to be a superset of bindfs (at least in this regards)...my general concern with layering bindfs and mergerfs is performance.

**Comment by trapexit** [comment]
> If you did filter the "fopen(w,w+,a,a+)"...would the policy than create the file on the r/w branch? 

As I mentioned above, no. If the file already exists it's an open. Not create. The point of the policy is to pick the branch or file. Just because one branch is RO doesn't mean it doesn't exist. The file still exists and can't be created. Only opened. If I change anything it'd be to have files opened RDWR or WRONLY fail on RO branches the same way they would on mounted `ro` devices.

If you want a truly read only setup you should mount it read only. To replicate all of that in mergerfs doesn't make much sense when the kernel will do it perfectly.

Why would you use bindfs? Why not just do a mount --bind?

Are you trying to aggregate storage or just adding readonly and readwrite? If the latter why wouldn't you just mount the path :rw for the writing container and :ro for all others? Even if you do need to aggregate storage why wouldn't you do that anyway. I feel like I'm misunderstanding what you're trying to accomplish.

**Comment by jmbraben** [comment]
ok...--bind vs bindfs...agreed.
The aggregation (of not necessarily storage) is the point. Think about a torrent client in a container on the mergerfs...the torrent will download into the r/w, but periodically I want to move the files to the ro (to prevent any possibility of corruption by that container to the main library...but I don't want to have to go into the client and say "i moved your files...start sharing them from the "ro" location"...same is true with clients like Plex that will see the mergerfs and not be aware that files have moved from "torrent r/w to main "ro""
Obviously I can make this work by binding the mounts read-only, and was just confused by some statements in the documentation as to the current behavior....hopefully I'm the exception in the confusion with regards to this issue (and no need for any changes)...'cause now I'm all "educated"...thanks

**Comment by trapexit** [comment]
Ok. Yeah, sounds to me you should just be doing a `-v /mnt/mergerfs:/storage:ro` for the consumer containers.
