### ISSUE TITLE
allow_other not honored in 2.28.1, works on 2.21.0

### ISSUE THREAD

**Issue by muncrief** [trapexit/mergerfs#645]
General description
===================
I have a system that works perfectly with 2.21.0, but gives permission denied errors with 2.28.1. I mount an ext4 user directory via fstab at boot, and later allow users to attach branches. It is critical that the add be done as the user owner of the filesystem, not root.

Expected behavior
=================
After mounting a user filesystem with mergerfs with the "allow_other" option I expect the user to be able to add branches to the mergerfs filesystem.

Actual behavior
===============
With 2.21.0, and the "allow_other" option, mergerfs works perfectly. With 2.28.1 it fails with a "permission denied" error unless run as root.

**Precise** steps to reproduce the behavior
===========================================
Note: I've been working on this problem off and on for about two months now and have tried myriads of different strategies and options. I didn't want to bother you and assumed it was pilot error on my part, but at this point I have to give in and acknowledge I'm stumped. So the example below is simply the most straightforward and simple one of many I could illustrate.

1. Install mergerfs V2.21.0

2. Make test directories:
mkdir /home/<user>/merger_test_main
mkdir /home/<user>/merger_test_branch_boot
mkdir /home/<user>/merger_test_branch_user

3. Add Initial mergerfs branch to fstab:
nano /etc/fstab
ADD:
/home/<user>/merger_test_branch_boot		/home/<user>/merger_test_main		fuse.mergerfs defaults,allow_other,direct_io,use_ino,hard_remove,fsname=mergerfs,minfreespace=2G,func.getattr=newest 0 0

4. Reboot

5. Add branch as user:
xattr -w user.mergerfs.srcmounts "+>/home/<user>/merger_test_branch_user" "/home/<user>/merger_test_main.mergerfs"

6. Verify user branch as been added:
xattr -l "/home/<user>/merger_test_main.mergerfs"

7.  Install mergerfs V2.28.1 and reboot.

8. Repeat step 5 and a "permission denied" error will occur.

9. Repeat step 6, but this time it will verify "/home/<user>/merger_test_branch_user" has not been added.

System information
==================
Version and settings have been detailed above.
------------------------------------------------

Filesystem
-----------
Note: I've created my own custom Wine Manager system that allows wine bottle XDGs to be multiplexed with the main system XDG. That's why ~/.config, ~/.local/share, and ~/Desktop are shown as mergerfs. However as the example above will illustrate the directories used do not affect the problem.

udev                                           7.8G     0  7.8G   0% /dev
tmpfs                                          1.6G  3.2M  1.6G   1% /run
/dev/sda5                                       46G   23G   22G  51% /
tmpfs                                          7.9G   17M  7.8G   1% /dev/shm
tmpfs                                          5.0M  4.0K  5.0M   1% /run/lock
tmpfs                                          7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda6                                       37G  8.5G   27G  25% /home
/dev/sda7                                      276G  257G  5.8G  98% /mnt/data1
/dev/sda2                                       99M   32M   67M  33% /boot/efi
mergerfs                                        37G  8.5G   27G  25% /home/phalynx/.local/share
mergerfs                                        37G  8.5G   27G  25% /home/phalynx/.config
/dev/sdc1                                      1.8T  1.5T  258G  86% /mnt/data3
/dev/sdd1                                      902G  281G  576G  33% /mnt/data4
/dev/sdb1                                      916G  677G  194G  78% /mnt/data2
mergerfs                                       916G  677G  194G  78% /home/phalynx/Desktop
tmpfs                                          1.6G  8.0K  1.6G   1% /run/user/1001

Linux Version
--------------
Linux Entropod 5.1.11-050111-lowlatency #201906171435 SMP PREEMPT Mon Jun 17 18:42:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Final Notes
-----------
I don't have an strace now because I'm in the middle of a job and don't have time to restructure my filesystem, and I expect an strace will not be necessary as I'm still assuming I'm doing something wrong. However if you need one I will produce it ASAP.

**Comment by muncrief** [comment]
Oops, I tried to insert "user" between less than/greater than signs in my initial post, but for some reason they were deleted when I submitted the text. So the "/home//" strings should be "/home/user/'. And as you can see in my case it's /home/phalynx/. I was just trying to make the example simpler and, of course, bungled it :)

**Comment by trapexit** [comment]
allow_other has nothing to do with runtime configuration.

Individuals who can modify the runtime are based on the runtime pseudo file. The reason for the change is that mergerfs is now hardcoding default_permissions which is appropriate. It was a security issue without it.

I could allow the pseudo file to have it's permissions changed or the owner changed rather than hardcoded now but there no way I can revert that behavior as it as a massive security hole.

**Comment by trapexit** [comment]
Nothing has changed wrt to the permissions of the pseudo file since 2.21.0 but due `defaults` being different in fstab vs commandline (for reasons I won't go into here) you weren't picking up `default_permissions` which it expanded to. If you add default_permissions to your 2.21.0 options I would expect it to deny non root as well.
