### ISSUE TITLE
Error 4 using SFTP with the merged point as root entry

### ISSUE THREAD

**Issue by kevincaradant** [trapexit/mergerfs#646]
General description
===================
Hi
I discovered you library today. It's almost perfect but I got an issue about "error 4"
![image](https://user-images.githubusercontent.com/6093175/59974678-5c305e80-95af-11e9-87f5-024f76f59e21.png)
![image](https://user-images.githubusercontent.com/6093175/59976225-b0443e80-95c1-11e9-875c-020b741fcf7a.png)

I have two storages (1 and 2)  merged in a point of mount "storages" (storage1 containing the "Y" or "Z" folder and storage2 containing the "X" folder.
I can move files from the root of the point of mount to "X" folder but I got an issue if try to move it in "Y" or "Z" ...

I don't understand why I got an error 4 using sftp ?
If I do on server in ssh,  `mv /media/pc/storages/toto.txt /media/pc/storages/Y` it works so why I can't do the same thing using sftp ?
Using SFTP, are we agree that I should use the point: `/media/pc/storages` as root entry?

NB: I didn't see 'permissions denied' so it's seems to be not a problem of permissions, isn't it ? I already read all the readme but my apologizes if I missed something :/

Expected behavior
=================
The move files should works

Actual behavior
===============
![image](https://user-images.githubusercontent.com/6093175/59974678-5c305e80-95af-11e9-87f5-024f76f59e21.png)

System information
==================
Please provide as much of the following information as possible:
```
* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.28.1-2-g10e5829
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.4
using FUSE kernel interface version 7.29
```

My groups:
![image](https://user-images.githubusercontent.com/6093175/59974854-268c7500-95b1-11e9-9938-027fd395f523.png)

MyPermissions:
![image](https://user-images.githubusercontent.com/6093175/59974861-3f952600-95b1-11e9-9962-7400856486f2.png)

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
UUID=7A0E1B100E1AC4D3 /media/pc/storage1 ntfs-3g uid=1000,gid=1001,nofail,auto,dmask=022,fmask=033 0 0
UUID=9CE3-538F  /boot/efi       vfat    defaults        0       1
UUID=6FDC8C9B0BFA1028 /media/pc/storage2 ntfs-3g uid=1000,gid=1001,nofail,auto,dmask=022,fmask=033 0 0
/media/pc/storage1:/media/pc/storage2 /media/pc/storages fuse.mergerfs allow_other,use_ino,func.getattr=newest,hard_remove 0 0
```
* [ ] Linux version: `uname -a`
```
Linux pc-NUC7i5BNH 4.15.18-041518-generic #201804190330 SMP Thu Apr 19 07:34:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
* [ ] List of drives, filesystems, & sizes: `df -h`
![image](https://user-images.githubusercontent.com/6093175/59974749-0f00bc80-95b0-11e9-9ac1-b8faaadd036c.png)

**Comment by trapexit** [comment]
You're using a path preserving policy. If the file is being moved across drives it will error as such as the docs mention. Without knowing precisely what's going on I can't really say what's wrong but I suspect it's that. You should try enabling `ignorepponrename` or change the create policy to `mfs`.

**Comment by kevincaradant** [comment]
OK thank you :)
I'm not sure it's really an issue with mergerfs. 
I took note of what you give me as answer and close the issue
