### ISSUE TITLE
File corruption

### ISSUE THREAD

**Issue by moonman** [trapexit/mergerfs#647]
General description
===================
Fine: source -> directly to pool member(bypassing mergerfs).
Corrupt: source -> mergerfs pool
Fine: source -> mhddfs pool (same hdd pool, mergerfs disabled, mhddfs enabled)
Tested with a 60GB video file and diff several times and different mount options.

Mount options i tried it with:
allow_other,nofail,moveonenospc=true,use_ino,direct_io,func.getattr=newest,category.create=ff 
allow_other,nofail,moveonenospc=true,func.getattr=newest,category.create=ff

Expected behavior
=================
No file corruption

Actual behavior
===============
Files get corrupter when written via mergerfs

**Precise** steps to reproduce the behavior
===========================================
Just copy files to mergerfs pool

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
```
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29
```
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
#/media/4TB:/media/4TB-Second:/media/4TB-Third:/media/2TB-Ext:/media/3TB:/media/8TB /media/storage-pool fuse.mergerfs  allow_other,nofail,moveonenospc=true,use_ino,direct_io,func.getattr=newest,category.create=ff 0 0
#/media/4TB:/media/4TB-Second:/media/4TB-Third:/media/2TB-Ext:/media/3TB:/media/8TB /media/storage-pool  fuse.mergerfs  allow_other,nofail,moveonenospc=true,func.getattr=newest,category.create=ff 0 0
```
* [ ] Linux version: `uname -a`
```
Linux srv01 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux
```
* [ ] Versions of any additional software being used
```
cp --version
cp (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
```
* [ ] List of drives, filesystems, & sizes: `df -h`
```
Filesystem                                                                          Size  Used Avail Use% Mounted on
dev                                                                                 5.9G     0  5.9G   0% /dev
run                                                                                 5.9G  1.1M  5.9G   1% /run
/dev/sda1                                                                            63G   38G   23G  63% /
tmpfs                                                                               5.9G   16K  5.9G   1% /dev/shm
tmpfs                                                                               5.9G     0  5.9G   0% /sys/fs/cgroup
/dev/sdb3                                                                           2.7T  2.1T  624G  78% /media/Files
/media/4TB;/media/4TB-Second;/media/4TB-Third;/media/2TB-Ext;/media/3TB;/media/8TB   23T   14T  8.5T  62% /media/storage-pool
/dev/sdc1                                                                           1.8T  1.8T   72G  97% /media/2TB
/dev/sdg1                                                                           1.8T  1.8T  2.8G 100% /media/2TB-Ext
/dev/sde1                                                                           7.3T   93M  6.9T   1% /media/8TB
/dev/sdd1                                                                           2.7T 1014G  1.6T  39% /media/3TB
/dev/sdh1                                                                           932G  100G  833G  11% /media/1TB
/dev/sdi1                                                                           3.6T  3.6T  3.4G 100% /media/4TB-Second
/dev/sdj1                                                                           3.6T  3.6T  974M 100% /media/4TB-Third
/dev/sdf1                                                                           3.6T  3.6T  2.2G 100% /media/4TB
tmpfs                                                                               1.2G     0  1.2G   0% /run/user/0
```
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
No failure
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
No failure

**Comment by trapexit** [comment]
You need to provide more information. Thousands use mergerfs without any such issue. I need an explicit example. How is it corrupted?

**Comment by moonman** [comment]
I'm guessing with all the given info you don't see anything obvious?
It is a video file and it just won't play after a certain point. diff reports that the files are different. Would a compiler make any difference. Archlinux is on gcc 9.1.0. It is also running in ESXi as a VM which shouldn't make any difference.

I will test with smaller files and see if it makes any difference.

**Comment by trapexit** [comment]
I use my own software and have the same kernel version and have no problems nor has anyone else reported any issues. I can spin up a fresh Arch install in a VM and try it out.

**Comment by trapexit** [comment]
Can you simplify the situation? Seems like it'd be skipping the first few drives and writing to /media/3TB? Doesn't look like it's moving the file on ENOSPC given the listed sizes.

Try with 1 drive with enough storage. Provide me with *exact* details. File size before and after. What drive is the source & dest. Etc. If there was actual corruption happening just due to a data write no one could use this. Clearly there is something atypical here.

**Comment by moonman** [comment]
Actually, it surpired me, but the file ended up on the 8TB Drive, while I expected it to be on the 3TB drive as well. And it seems it always ends up in the 8TB drive if I use mergerfs (mhddfs puts it on the 3TB drive as expected).

**Comment by trapexit** [comment]
Something above isn't representative of when the action was taken then. The name of the mount in the `df` clearly isn't what was from that fstab setting.

**Comment by moonman** [comment]
It is though. category.create=ff is supposed to take the first drive in the pool, but it doesn't. I didn't pay too much attention to this to be honest since I was more concerned with corruption. Anyway, I will run the tests right now and I will take md5sum of the source and destination files.

**Comment by trapexit** [comment]
It takes the first that isn't filtered out. https://github.com/trapexit/mergerfs#filters

Also needs to be accessible. mhddfs doesn't manage security properly, mergerfs does, so you must ensure permissions are proper.

md5sum isn't really that useful. Something like `cmp` would be better to indicate where it differs.

**Comment by moonman** [comment]
Ok, I did a full system update, reboot and I haven't been able to reproduce this issue anymore. Thanks for the help, hopefully I didn't waste too much of your time.

**Comment by trapexit** [comment]
No problem. Glad to hear things are working.
