### ISSUE TITLE
Can i only change one fs file? 

### ISSUE THREAD

**Issue by swimfish09** [trapexit/mergerfs#648]
copy, create, delete file only impact the first fs.

**Comment by trapexit** [comment]
As the docs mention each function has a certain policy to determine what to act on. https://github.com/trapexit/mergerfs#functions--policies--categories

'copy' isn't a filesystem function. Yes, 'create' results in 1 file. 'delete'... you mean 'unlink' or 'rmdir'? Both have policies you can set.
