### ISSUE TITLE
file will be deleted when i modify the file when two fs contains the same file (include file attr)

### ISSUE THREAD

**Issue by swimfish09** [trapexit/mergerfs#649]
General description
===================

firstly i will create a new file test2.txt in /mnt/remote, then i will use `copy -p /mnt/remote/test2.txt /home/store/cache/vfs/local/mnt/remote/test2.txt`
lastly i will change the file use command `vim /mnt/merged/test2.txt`
after save the file lost in fs /home/store/cache/vfs/local/mnt/remote

Expected behavior
=================

only file /home/store/cache/vfs/local/mnt/remote/test2.txt changed

Actual behavior
===============
 file /home/store/cache/vfs/local/mnt/remote/test2.txt losted

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
```
mergerfs version: 2.28.1-2-g10e5829
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.2
using FUSE kernel interface version 7.29
```
* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
mergerfs -o allow_other,use_ino,noforget,category.action=ff,category.create=ff,category.search=newest  /home/store/cache/vfs/local/mnt/remote:/mnt/remote=RO /mnt/merged/
```
* [x] Linux version: `uname -a`
```
Linux server2 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* [x] List of drives, filesystems, & sizes: `df -h`
```
192.168.56.101:/home/store/programs                47G   27G   21G  58% /mnt/remote
home/store/cache/vfs/local/mnt/remote:mnt/remote   94G   52G   43G  56% /mnt/merged
```

**Comment by trapexit** [comment]
If you strace vim you'd see that it's issuing renames and unlinks. They rename the file to "filename~", write to "filename", then unlinks "filename~". mergerfs doesn't and is not designed to write to multiple files at once. It tolerates certain situations where file paths overlap but I don't see how this situation could be managed. vim is telling it to unlink the files.

**Comment by swimfish09** [comment]
if the two fs contains the same file , which file will exist in merged

**Comment by trapexit** [comment]
I don't understand the question. Every function has a policy. The files acted on are decided by the policy. https://github.com/trapexit/mergerfs#functions--policies--categories

**Comment by swimfish09** [comment]
> If you strace vim you'd see that it's issuing renames and unlinks. They rename the file to "filename~", write to "filename", then unlinks "filename~". mergerfs doesn't and is not designed to write to multiple files at once. It tolerates certain situations where file paths overlap but I don't see how this situation could be managed. vim is telling it to unlink the files.

fine, so at moment, there is no way to overwrite file at the same fs.

**Comment by trapexit** [comment]
No. As I said in the other ticket it does not write to multiple files. It's not raid1. It's a union. 

Even if mergerfs did open/write to all files found it still wouldn't be able to manage what vim is doing. Vim is renaming the original file, copying it's content, then writing a new file, then removing the old one. There is no way to know that the files are related.

**Comment by trapexit** [comment]
vim isn't technically changing a file. It's writing a new one and replacing the old.
