### ISSUE TITLE
nfs file stale if file exist

### ISSUE THREAD

**Issue by swimfish09** [trapexit/mergerfs#650]
General description
===================

i can not overwrite file to merged fs at the nfs client

Expected behavior
=================

if file exist overwrite file , if not create one.

Actual behavior
===============

```
-bash: /mnt/proj/rch_tianlulixian_cg/syncData/render/s0000/s0000_0010/images/dx/dx7_10_2/env/v001/env.1125.exr: Stale file handle
```

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
```
mergerfs version: 2.28.1-2-g10e5829
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.2
using FUSE kernel interface version 7.29
```

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
mergerfs -o allow_other,use_ino,noforget,category.action=ff,category.create=ff,category.search=newest /proj-small/rch_tianlulixian_cg:/proj/yuanli-rch_tianlulixian_cg  /proj/merged-rch_tianlulixian_cg
```
* [x] Linux version: `uname -a`
```
Linux bms-1e29-0002 5.1.5-1.el7.elrepo.x86_64 #1 SMP Sat May 25 16:10:51 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by swimfish09** [comment]
after execute the command,  Stale file handle error disappear
```
sync
echo 2 > /proc/sys/vm/drop_caches
```

**Comment by trapexit** [comment]
Provide actual, reproducible examples or I can't help you.
