### ISSUE TITLE
Is this behavior ok?

### ISSUE THREAD

**Issue by genimac** [trapexit/mergerfs#651]
General description
===================
Created 9 disk mergerFS with xfs 
Filling data from another server with rsync, around 25Tb

Expected behavior
=================
Fill the disks proportionally. Same % use on each one.

Actual behavior
===============
Seems it adds files until a disk is full and the go to another

**Precise** steps to reproduce the behavior
===========================================
Just run the rsync and watched how the disks fills.

Also, is it ok to hard link on the mergerFS? origin and destina will be both on /home/storage

System information
==================
Please provide as much of the following information as possible:

mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.9
using FUSE kernel interface version 7.19

fstab
```
proc /proc proc defaults 0 0
# /dev/sda1 during Installation (RescueSystem)
UUID=23df778d-7069-4f04-a874-1556956433d3 /boot ext3 defaults 0 0
# /dev/sda2 belongs to LVM volume group 'vg0'
/dev/vg0/swap  swap  swap  defaults 0 0
/dev/vg0/tmp  /tmp  reiserfs  defaults 0 0
/dev/vg0/root  /  xfs  defaults 0 0
UUID=f6f9f333-b8bc-48e8-9200-a659f32b4ab5       /mnt/disk1      xfs     defaults        0       0
UUID=213c78ea-87ed-4f02-9304-30da2ae2c684       /mnt/disk2      xfs     defaults        0       0
UUID=59666350-b11b-4a9b-9f81-5b50f68a28ec       /mnt/disk3      xfs     defaults        0       0
UUID=8eba354c-8db9-4c65-9093-c5c9e90dceb4       /mnt/disk4      xfs     defaults        0       0
UUID=fdff0d65-ab4e-456e-a45b-e19c6637d5d6       /mnt/disk5      xfs     defaults        0       0
UUID=ea5f3ea6-9671-4b17-99c8-54f658e6618b       /mnt/disk6      xfs     defaults        0       0
UUID=087f2ea5-829c-42af-89f2-d41aa6c3d11f       /mnt/disk7      xfs     defaults        0       0
UUID=bdfc0169-1f86-4732-9f11-9d3bf59f726e       /mnt/disk8      xfs     defaults        0       0
UUID=66186ce1-3b7c-4db3-9efc-9021a29f99a7       /mnt/disk9      xfs     defaults        0       0

#mergerfs
/mnt/disk*     /home/storage     fuse.mergerfs direct_io,defaults,allow_other,use_ino,minfreespace=50G,fsname=mergerfs 0 0`
```

Linux "server name" 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux
```

Filesystem            Size  Used Avail Use% Mounted on
udev                   32G     0   32G   0% /dev
tmpfs                 6.3G  920K  6.3G   1% /run
/dev/mapper/vg0-root  5.4T  8.9G  5.4T   1% /
tmpfs                  32G  8.0K   32G   1% /dev/shm
tmpfs                 5.0M     0  5.0M   0% /run/lock
tmpfs                  32G     0   32G   0% /sys/fs/cgroup
mergerfs               50T  5.9T   44T  12% /home/storage
/dev/sdf1             5.5T  194G  5.3T   4% /mnt/disk5
/dev/sdh1             5.5T   68G  5.4T   2% /mnt/disk7
/dev/sdg1             5.5T  721G  4.8T  13% /mnt/disk6
/dev/sdc1             5.5T   55G  5.5T   1% /mnt/disk3
/dev/sdb1             5.5T  107G  5.4T   2% /mnt/disk2
/dev/sdi1             5.5T  7.2G  5.5T   1% /mnt/disk8
/dev/sdj1             5.5T   67G  5.4T   2% /mnt/disk9
/dev/sdd1             5.5T  4.6T  889G  85% /mnt/disk4
/dev/sda1             5.5T   31G  5.5T   1% /mnt/disk1
/dev/sde1             976M   52M  873M   6% /boot
/dev/mapper/vg0-tmp    10G   33M   10G   1% /tmp
tmpfs                 6.3G     0  6.3G   0% /run/user/1000
```

**Comment by trapexit** [comment]
> Seems it adds files until a disk is full and the go to another

Because that's the behavior you've configured for. Default policy is `epmfs`.

Read about policies in the docs.

https://github.com/trapexit/mergerfs#functions--policies--categories

> Fill the disks proportionally. Same % use on each one.

There is no "min % full" policy at the moment. It's generally not preferred. That said I may add it since there is a rare'ish situation where it makes the most sense.

**Comment by genimac** [comment]
I must change the defaults on fstab to lus will do it?

**Comment by trapexit** [comment]
Do what?

Choose whatever policy you prefer.

**Comment by genimac** [comment]
Sorry new to the mergerFS.
I mean to get a policy that fills the disk proportionally, is only change the line in fstab to:

`/mnt/disk*     /home/storage     fuse.mergerfs direct_io,lus,allow_other,use_ino,minfreespace=50G,fsname=mergerfs 0 0`

**Comment by trapexit** [comment]
As I mentioned prior there is no percentage based policies. Proportional breaks when drives are significantly different in size. mfs and lus make more sense and don't have bad edge cases like proportional.

Yes. You have to set the option. `category.create=<policy>`

https://github.com/trapexit/mergerfs#options
https://github.com/trapexit/mergerfs#policy-descriptions

You can set it at runtime with the runtime interface.

https://github.com/trapexit/mergerfs#runtime-config

**Comment by genimac** [comment]
Thanks a lot for the clarifications.
