### ISSUE TITLE
Cannot access mount through PHP in Docker

### ISSUE THREAD

**Issue by ViRb3** [trapexit/mergerfs#658]
General description
===================
This is a weird one, but I cannot use the mergerfs mount through php at all. It works with virtually everything else. Browsing via the shell and even calling `stat` from there works perfectly.

Expected behavior
=================
Works

Actual behavior
===============
`Warning: stat(): stat failed for /mnt/unified in Command line code on line 1`

**Precise** steps to reproduce the behavior
===========================================
```
mergerfs -o allow_other,use_ino,minfreespace=100G /mnt-all/\* /mnt/unified
docker run -v /mnt:/mnt -it --entrypoint /bin/bash php
php -r 'stat("/mnt/unified");' 
```
Any other way to access that mount in php would also fail

System information
==================
```
mergerfs version: 2.28.1-6-g52e4d60
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29

Linux raspberrypi 4.19.66-v7l+ #1253 SMP Thu Aug 15 12:02:08 BST 2019 armv7l GNU/Linux

4256  read(3,  <unfinished ...>
4255  read(3,  <unfinished ...>
4254  read(3,  <unfinished ...>
4253  read(3,  <unfinished ...>
4252  futex(0xbe9a4734, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
4256  <... read resumed> "8\0\0\0\3\0\0\0\36{\5\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 56
4256  lstat64("/mnt-all/drive-a/", {st_mode=S_IFDIR|S_ISGID|0777, st_size=4096, ...}) = 0
4256  lstat64("/mnt-all/drive-a/", {st_mode=S_IFDIR|S_ISGID|0777, st_size=4096, ...}) = 0
4256  writev(3, [{iov_base="x\0\0\0\0\0\0\0\36{\5\0\0\0\0\0", iov_len=16}, {iov_base="\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\376\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
4256  read(3,  <detached ...>
```

**Comment by ViRb3** [comment]
From all the troubleshooting I forgot the most vital one: I remounted and now everything works.

**Comment by ViRb3** [comment]
The problem is back, and now re-mounting does not help. I also tried removing `use_ino` but no change.

**Comment by trapexit** [comment]
I'm not having any issue. What's the error precisely?

**Comment by ViRb3** [comment]
It simply says:
`stat failed for /mnt/unified`

If I try `readdir("/mnt/unified")` it will return empty. I originally encountered this issue with NextCloud in Docker (a self-hosted cloud in PHP).

**Comment by ViRb3** [comment]
The mount just worked again, after a combination of remounts and container restarts. Could this be some form of a race condition?

**Comment by trapexit** [comment]
I don't know with what. Without an actual error it's tough to say. I've never had issues and many others use mergerfs mounts in docker. When php fails the stat cli tool works fine?

Can you run strace against php when it fails? 

`docker run --rm --cap-add=SYS_PTRACE --security-opt=seccomp:unconfined -it -v /media:/media --entrypoint /bin/bash php`

`# apt update; apt install strace`

`# strace -o /tmp/trace php -r 'stat("/mnt/unified");'`

**Comment by ViRb3** [comment]
I just reinstalled and I cannot reproduce this anymore. I will keep an eye out and re-open the issue with your suggested logging if it happens again. Thanks for the help!
