### ISSUE TITLE
NFS client mounting mergerfs pool does not respect "category.create=mfs" option

### ISSUE THREAD

**Issue by rodhull** [trapexit/mergerfs#664]
General description
===================
My config is generally the same as reported in https://github.com/trapexit/mergerfs/issues/626 except for the versions of mergerfs/kernel etc

I have for some time been using the "**category.create=eplfs**" mount option (as set by OpenMediaVault's web UI)

However, this resulted in one of my disks (_/srv/dev-disk-by-label-WD6TBBAY1_) recently filling up.

I re-read the docs and decided I didn't need any path preservation, so deleted the folder (and its contents) which had most recently had too much data added to it causing the drive to become full and changed the mount option for the pool to "**category.create=mfs**" instead.

So, now, the previously full drive (_/srv/dev-disk-by-label-WD6TBBAY1_) has **12GB** free.

I have 2 other drives in the pool with **248GB** and **2.7TB** free respectively.

I have shutdown the NFS server, unmounted mergerfs, re-mounted mergerfs, restarted the NFS server and re-mounted on the client. I've also tried fully rebooting both the server and the client

When creating the folder again from the client which has mounted the NFS-exported pool, it created the folder on the same drive (currently the one with **least** free space - **12GB**). If I remove it again, and create the folder directly on the OMV server inside the mounted mergerfs pool (so from _/srv/ecaf2ef9-aa68-47d9-99ad-ac21d64d8764_) it succeeds and creates the folder on the "**mfs**" drive - the one with **2.7TB** free.

However, when my NFS client now tries to write to this folder (now on the "**mfs**" drive), the folder is created AGAIN on the drive with only **12GB** free (so the "**lfs**" drive) and data is only being written there filling it up again.

Expected behavior
=================
Folder created by client which has mounted the NFS-exported pool should be created on drive with **most** free space.
Also, if a folder already exists on the "**mfs**" drive, this folder should be chosen to write to.

Actual behavior
===============
Folder created by client which has mounted the NFS-exported pool still is created on drive with "**least free space**" despite option change.
Also, even if the folder exists on the "**mfs**" drive, another folder of the same name is created and written to the "**lfs**" drive.

**Precise** steps to reproduce the behavior
===========================================

In my case, create a pool with "**category.create=eplfs**" option, use for some time, change option to "**category.create=mfs**", remove a folder on the current "**lfs**" drive, and when writing from an NFS client, observe mergerfs still create the folder on the "**lfs**" drive. 

If you create the folder from the server itself on the mounted mergerfs pool (not via NFS), still observe an NFS client create/write to the current "**lfs**" drive.

System information
==================
Please provide as much of the following information as possible:

mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.29

Pertinent bits of /etc/fstab: 
```
 >>> [openmediavault]
/dev/disk/by-label/WD6TBBAY1 /srv/dev-disk-by-label-WD6TBBAY1 ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
/dev/disk/by-id/usb-WD_Elements_25A1_575833314434383746543045-0:0-part1 /srv/dev-disk-by-id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1 ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
/dev/disk/by-label/WD3TBBAY2 /srv/dev-disk-by-label-WD3TBBAY2 ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2
/srv/dev-disk-by-label-WD6TBBAY1:/srv/dev-disk-by-id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1:/srv/dev-disk-by-label-WD3TBBAY2 /srv/ecaf2ef9-aa68-47d9-99ad-ac21d64d8764 fuse.mergerfs defaults,allow_other,direct_io,use_ino,noforget,category.create=mfs,minfreespace=10M 0 0
/srv/ecaf2ef9-aa68-47d9-99ad-ac21d64d8764/media /export/media none bind,nofail 0 0
# <<< [openmediavault]
```
Pertinent output of df -h:
```
label-WD6TBBAY1:id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1:label-WD3TBBAY2   12T  8.8T  3.0T  75% /export/media
/dev/sdd1                                                                                   3.6T  3.4T  248G  94% /srv/dev-disk-by-id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1
/dev/sda1                                                                                   5.5T  5.5T   12G 100% /srv/dev-disk-by-label-WD6TBBAY1
/dev/sdb1                                                                                   2.7T   89M  2.7T   1% /srv/dev-disk-by-label-WD3TBBAY2
label-WD6TBBAY1:id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1:label-WD3TBBAY2   12T  8.8T  3.0T  75% /srv/ecaf2ef9-aa68-47d9-99ad-ac21d64d8764
```

Not done an strace yet, but can do so if required.

**Comment by trapexit** [comment]
What does the runtime options say? There simply isn't a way for mfs to behave like lfs. 

It's a little difficult to follow all the drives and such given their names + NFS, etc. Can you please simplify the situation? Set up a minimal replicatable example.

**Comment by rodhull** [comment]
Thanks for replying so fast!

OK - runtime options on the server - very interesting results. There appear to be 2 processes running (which doesn't look right to me):

```
root@omv:~# ps -ef|grep mergerfs
root       402     1  7 10:02 ?        00:18:43 mergerfs /srv/dev-disk-by-label-WD6TBBAY1:/srv/dev-disk-by-id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1:/srv/dev-disk-by-label-WD3TBBAY2 /srv/ecaf2ef9-aa68-47d9-99ad-ac21d64d8764 -o rw,allow_other,direct_io,use_ino,noforget,category.create=lfs,minfreespace=10M,dev,suid
root      2734     1  0 10:07 ?        00:01:56 mergerfs /srv/dev-disk-by-label-WD6TBBAY1:/srv/dev-disk-by-id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1:/srv/dev-disk-by-label-WD3TBBAY2 /srv/ecaf2ef9-aa68-47d9-99ad-ac21d64d8764 -o rw,allow_other,direct_io,use_ino,noforget,category.create=mfs,minfreespace=10M,dev,suid
```

This might explain why this behaviour is happening...each process has a different mount option (one "mfs", the other "lfs")

Why is this? It must be some config from OMV doing it?

As for being able to follow things - apologies, but I think you have the hang of it - I know - "mfs" cannot in any way behave like "lfs". I am not sure NFS even comes into it to be honest...

Anyway, to clarify (abstracting NFS for a second), let's say I have 2 drives :

```
/dev/sda1 - mounted to /srv/dev-disk-by-label-WD6TBBAY1
/dev/sdb1- mounted to /srv/dev-disk-by-label-WD3TBBAY2
```

In this scenario (which mirrors real life in my case - there's another but it doesn't seem to have a bearing since it is neither the one with "mfs" nor "lfs" ). The first drive in the above list has 12GB free, the second, 2.7TB free.

They are both in a mergerfs pool and the fstab entry has the mount option of "category.create=mfs"

I am seeing the OPPOSITE behaviour - rather than a new folder/data being created on the "mfs" drive (the second in the example above) it is being created on the "lfs" drive (the first drive).

The fact that in my case mergerfs is running under 2 different PIDs (each with a different policy option) is what is causing it I presume?

Now, why is this happening all of a sudden? I merely changed the mount option from the OMV web UI from **category.create=eplfs** to **category.create=mfs** - I know most changes made in the OMV web UI cause edits to /etc/openmediavault/config.xml (which I can see reflected correctly in mine):

```
<unionfilesystems>
      <filesystem>
        <uuid>ecaf2ef9-aa68-47d9-99ad-ac21d64d8764</uuid>
        <name>mergerfs</name>
        <self-mntentref>053f0ee8-61e6-41b4-8c29-bf35a5c76602</self-mntentref>
        <mntentref>d4c1fdc9-078d-4dda-9942-deeb2f4438bc</mntentref>
        <mntentref>cf0be8f5-f066-46b0-bbf9-6694afd2f4ad</mntentref>
        <mntentref>a428557a-eeff-46da-8cd2-558dd6907686</mntentref>
        <create-policy>mfs</create-policy>
        <min-free-space>10M</min-free-space>
        <options>defaults,allow_other,direct_io,use_ino,noforget</options>
      </filesystem>
    </unionfilesystems>
```

In turn, I also have the expected entry in /etc/fstab (see original post above) - so why are there 2x mergerfs processes?

**Comment by trapexit** [comment]
I don't use OMV or manage their plugin that orchestrates mergerfs so I can't really speak to any of that. Should hit up their forum. But yes... that's likely the problem. Just check the runtime settings on the mount to see what it says.

https://github.com/trapexit/mergerfs#runtime-config

**Comment by rodhull** [comment]
So, I killed both mergerfs processes, manually re-mounted the pool and it now works fine (also via an NFS client). "mfs" works as expected and data is being written to the drive with the most free space again (consistently now it seems).

As a quick test, I completely rebooted the OMV server again to see if the second PID had been started with the spurious "lfs" mount option, and now there is just the one as expected.

I suspect some weirdness around the OMV web UI potentially caused some transient config to be live that has now vanished (strange that it persisted across one reboot but is now gone, but hey ho). Very strange. I'll report it to the OMV guys if it happens again.

Thanks for your help...not many projects get such fast (and sane) responses from their devs!

FWIW, my runtime options are now:

```
root@omv:/srv/ecaf2ef9-aa68-47d9-99ad-ac21d64d8764# xattr -l .mergerfs
user.mergerfs.async_read: true
user.mergerfs.branches: /srv/dev-disk-by-label-WD6TBBAY1=RW:/srv/dev-disk-by-id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1=RW:/srv/dev-disk-by-label-WD3TBBAY2=RW
user.mergerfs.cache.attr: 1
user.mergerfs.cache.entry: 1
user.mergerfs.cache.files: libfuse
user.mergerfs.cache.negative_entry: 0
user.mergerfs.cache.open: 0
user.mergerfs.cache.readdir: false
user.mergerfs.cache.statfs: 0
user.mergerfs.cache.symlinks: false
user.mergerfs.direct_io: true
user.mergerfs.dropcacheonclose: false
user.mergerfs.fuse_msg_size: 32
user.mergerfs.ignorepponrename: false
user.mergerfs.link_cow: false
user.mergerfs.minfreespace: 10485760
user.mergerfs.moveonenospc: false
user.mergerfs.nullrw: false
user.mergerfs.pid: 413
user.mergerfs.policies: all,epall,epff,eplfs,eplus,epmfs,eprand,erofs,ff,lfs,lus,mfs,newest,rand
user.mergerfs.posix_acl: false
user.mergerfs.security_capability: true
user.mergerfs.srcmounts: /srv/dev-disk-by-label-WD6TBBAY1:/srv/dev-disk-by-id-usb-WD_Elements_25A1_575833314434383746543045-0-0-part1:/srv/dev-disk-by-label-WD3TBBAY2
user.mergerfs.statfs: base
user.mergerfs.statfs_ignore: none
user.mergerfs.symlinkify: false
user.mergerfs.symlinkify_timeout: 3600
user.mergerfs.version: 2.28.1
user.mergerfs.xattr: passthrough
user.mergerfs.category.action: epall
user.mergerfs.category.create: mfs
user.mergerfs.category.search: ff
user.mergerfs.func.access: ff
user.mergerfs.func.chmod: epall
user.mergerfs.func.chown: epall
user.mergerfs.func.create: mfs
user.mergerfs.func.getattr: ff
user.mergerfs.func.getxattr: ff
user.mergerfs.func.link: epall
user.mergerfs.func.listxattr: ff
user.mergerfs.func.mkdir: mfs
user.mergerfs.func.mknod: mfs
user.mergerfs.func.open: ff
user.mergerfs.func.readlink: ff
user.mergerfs.func.removexattr: epall
user.mergerfs.func.rename: epall
user.mergerfs.func.rmdir: epall
user.mergerfs.func.setxattr: epall
user.mergerfs.func.symlink: mfs
user.mergerfs.func.truncate: epall
user.mergerfs.func.unlink: epall
user.mergerfs.func.utimens: epall
```

**Comment by trapexit** [comment]
Glad it's working now. I'd report it regardless as this could affect others.
