### ISSUE TITLE
mergerfs eating files

### ISSUE THREAD

**Issue by azilber** [trapexit/mergerfs#665]
General description
===================
Using mergerfs 2.82.2-1 on Centos7 (OpenVZ 7)

Things were working well till minfreespace value was reached.  Then files being sent to the mergerfs directory just vanish.

I tried unmounting the mergerfs directory, and I removed minfreespace.  Nothing helps, files vanish without any errors.

As it is, the mergerfs is no longer functional at all.

Expected behavior
=================
files should appear somewhere.

Actual behavior
===============
Files silently vanish.

**Precise** steps to reproduce the behavior
===========================================

My fstab:
Testing:
/mnt/wd*:/mnt/samsung1	/mnt/pool  fuse.mergerfs	defaults,allow_other,fsname=mergerfs,moveonenospc=true,dropcacheonclose=true,security_capability=false,xattr=nosys,cache.files=auto-full,cache.readdir=true	0 9

Original:
/mnt/wd*:/mnt/samsung1	/mnt/pool		  fuse.mergerfs	defaults,allow_other,intr,large_read,minfreespace=50G,fsname=mergerfs,moveonenospc=true,use_ino,dropcacheonclose=true,security_capability=false,xattr=nosys,cache.files=auto-full,cache.readdir=true	0 0

drives are all formatted xfs. xattr .mergerfs are all defaults.

rsyncing to the pool directory works until it either reaches minfreespace (or without minfreespace it just reaches end of drive) and files just seem to go to /dev/null

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: 
mergerfs version: 2.28.2
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.2
using FUSE kernel interface version 7.29
* [ ] mergerfs settings:  defaults,allow_other,fsname=mergerfs,moveonenospc=true,dropcacheonclose=true,security_capability=false,xattr=nosys,cache.files=auto-full,cache.readdir=true
* [ ] Linux version: Linux dreck 3.10.0-957.12.2.vz7.96.21 #1 SMP Thu Jun 27 15:10:55 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux
* [ ] List of drives, filesystems, & sizes: `df -h`
Filesystem      Size  Used Avail Use% Mounted on
/dev/md126       92G  2.3G   85G   3% /
devtmpfs        7.8G     0  7.8G   0% /dev
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           7.8G  9.2M  7.8G   1% /run
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/md124      477M  9.8M  467M   3% /boot/efi
/dev/md125      125G  206M  118G   1% /vz
/dev/sda1       1.9T  1.9T  3.9G 100% /mnt/wdblack1
/dev/sdc1       1.9T  991G  872G  54% /mnt/wdgreen2
/dev/sdb1       1.9T  813G  1.1T  44% /mnt/wdgreen1
/dev/sdd1       1.9T   33M  1.9T   1% /mnt/samsung1
tmpfs           1.6G     0  1.6G   0% /run/user/0
/dev/sdh1       1.9T  1.2T  663G  65% /mnt/usb/2
/dev/sdj1       1.9T  1.8T   96G  95% /mnt/usb/4
mergerfs        7.3T  3.6T  3.7T  50% /mnt/pool
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
Lots of:
15067 select(5, NULL, [4], [4], {60, 0}) = 1 (out [4], left {59, 999999})
15067 write(4, "\202\7\27%\5\231t\302\234\223\0267\340\360\226\266\374\212\212\240R\237\211\243\325\221\316\201\336(0\366"..., 4092) = 4092
15067 select(5, NULL, [4], [4], {60, 0}) = 1 (out [4], left {59, 999999})
15067 write(4, "\374\17\0\7", 4)        = 4
15067 select(5, NULL, [4], [4], {60, 0}) = 1 (out [4], left {59, 999999})
15067 write(4, "\317Ha\21\354\ft\3530,\346\246\3441\245a\217G\27\216r\333\317e$'\353H&\7\34\204"..., 4092) = 4092
15067 select(5, NULL, [4], [4], {60, 0}) = 1 (out [4], left {59, 999999})
15067 write(4, "\374\17\0\7", 4)        = 4
15067 select(5, NULL, [4], [4], {60, 0}) = 1 (out [4], left {59, 999998})
15067 write(4, "\215u\vy\352v6\320\310=\330L\36W{\222,\320X\251\251\27$\16c5\7\30\24V\272T"..., 4092) = 4092
15067 select(5, NULL, [4], [4], {60, 0}) = 1 (out [4], left {59, 999999})
15067 write(4, "\374\17\0\7", 4)        = 4
15067 select(5, NULL, [4], [4], {60, 0}) = 1 (out [4], left {59, 999999})
15067 write(4, "\242f\243`ET\324\3\256\251i\24\352\215\33\336\31.C\205\340)mL<\241\314A\31\200\217K"..., 4092) = 4092

* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
http://dpaste.com/1BVYKGD

**Comment by trapexit** [comment]
You have path preserving enabled. It should return ENOSPC when it runs out of space (minfreespace reached for all drives with that path). rsync for whatever reason doesn't stop when hitting that error. This has nothing to do with mergerfs. Try using `cp` or `mv`... it should fail appropriately.
