### ISSUE TITLE
Source tarball release missing for 2.28.2

### ISSUE THREAD

**Issue by zofrex** [trapexit/mergerfs#666]
General description
===================
The mergerfs-2.28.2 release doesn't contain the usual source tarball release (would be named "mergerfs-2.28.2.tar.gz") like previous releases have.

It does contain a "source code" download which I think is autogenerated by Github, I'm not sure if that's the same thing or not. If there's no functional difference between the two then I'm happy using that one instead, but I don't want to switch without assurance that's the right thing to do.

Expected behavior
=================
Release includes a "mergerfs-2.28.2.tar.gz" file.

Actual behavior
===============
The release does not contain this file.

**Precise** steps to reproduce the behavior
===========================================

[Go here](https://github.com/trapexit/mergerfs/releases/tag/2.28.2) and look, or alternatively run:

```
mergerfs_version=2.28.2
mergerfs_filename="mergerfs-${mergerfs_version}.tar.gz"
curl --fail -OJL "https://github.com/trapexit/mergerfs/releases/download/${mergerfs_version}/${mergerfs_filename}"
```

You can see this works with previous versions, e.g. 2.28.1.

System information
==================
N/A

**Comment by trapexit** [comment]
Fixed. Sorry. Just forgot to upload it.
