### ISSUE TITLE
xattr -l .mergerfs shows 'No such xattr:' after a while

### ISSUE THREAD

**Issue by azilber** [trapexit/mergerfs#667]
General description
===================

When first mounting the pool, xattr -l .mergerfs works just fine.  After some time, sometimes minutes to an hour, variables are no longer visible using xattr.

Expected behavior
=================
Variables should be visible.

Actual behavior
===============
No such xattr: user.mergerfs.branches
No such xattr: user.mergerfs.cache.attr
No such xattr: user.mergerfs.cache.entry
No such xattr: user.mergerfs.cache.files
No such xattr: user.mergerfs.cache.negative_entry
No such xattr: user.mergerfs.cache.open
No such xattr: user.mergerfs.cache.readdir
No such xattr: user.mergerfs.cache.statfs
No such xattr: user.mergerfs.cache.symlinks

**Precise** steps to reproduce the behavior
===========================================
[root@dreck mnt]# umount /mnt/pool
[root@dreck mnt]# mount -a
[root@dreck mnt]# xattr -l pool/.mergerfs |head -5
user.mergerfs.async_read: true
user.mergerfs.branches: /mnt/wdblack1=RW:/mnt/wdgreen1=RW:/mnt/wdgreen2=RW:/mnt/samsung1=RW
user.mergerfs.cache.attr: 1
user.mergerfs.cache.entry: 1
user.mergerfs.cache.files: auto-full
[root@dreck mnt]# date
Mon Sep 16 14:06:33 +08 2019

.......

No such xattr: user.mergerfs.func.symlink
No such xattr: user.mergerfs.func.truncate
No such xattr: user.mergerfs.func.unlink
No such xattr: user.mergerfs.func.utimens
[root@dreck mnt]# date
Mon Sep 16 15:35:08 +08 2019

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: 
mergerfs version: 2.28.2
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.2
using FUSE kernel interface version 7.29
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
#
# /etc/fstab
# Created by anaconda on Sat Sep 14 01:00:08 2019
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=49f0e4e8-5374-4b46-a2b3-b630683e9585 /                       ext4    defaults,discard        1 1
UUID=AE5C-92B8          /boot/efi               vfat    umask=0077,shortname=winnt 0 0
UUID=90f2cfe7-61a6-473b-bfd7-a842276c0574 /vz                     ext4    defaults,noatime,lazytime,discard 1 2
UUID=10ea6fe3-6ef7-4b0f-b11b-39e2696b6d84 swap                    swap    defaults,discard        0 0
LABEL=wdblack1                          /mnt/wdblack1             xfs     defaults,noatime        1 3
LABEL=wdgreen1                          /mnt/wdgreen1             xfs     defaults,noatime        1 3
LABEL=wdgreen2                          /mnt/wdgreen2             xfs     defaults,noatime        1 3
LABEL=samsung1                          /mnt/samsung1             xfs     defaults,noatime        1 3

/mnt/wd*:/mnt/samsung1  /mnt/pool  fuse.mergerfs        allow_other,fsname=mergerfs,minfreespace=50G,moveonenospc=true,dropcacheonclose=true,security_capability=false,xattr=nosys,cache.files=auto-full,cache.readdir=true,func.getattr=newest,category.create=mfs,func.mkdir=epall        0 0

* [ ] Linux version: 
Linux dreck 3.10.0-957.12.2.vz7.96.21 #1 SMP Thu Jun 27 15:10:55 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux

* [ ] Versions of any additional software being used
Python 3.6.6

* [ ] List of drives, filesystems, & sizes: 
Filesystem      Size  Used Avail Use% Mounted on
/dev/md126       92G  2.3G   85G   3% /
devtmpfs        7.8G     0  7.8G   0% /dev
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           7.8G  9.3M  7.8G   1% /run
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/md124      477M  9.8M  467M   3% /boot/efi
/dev/md125      125G  206M  118G   1% /vz
/dev/sda1       1.9T  1.7T  125G  94% /mnt/wdblack1
/dev/sdc1       1.9T  991G  872G  54% /mnt/wdgreen2
/dev/sdb1       1.9T  813G  1.1T  44% /mnt/wdgreen1
/dev/sdd1       1.9T  345G  1.5T  19% /mnt/samsung1
tmpfs           1.6G     0  1.6G   0% /run/user/0
/dev/sdh1       1.9T  1.2T  663G  65% /mnt/usb/2
/dev/sdj1       1.9T  1.8T   96G  95% /mnt/usb/4
mergerfs        7.3T  3.8T  3.5T  53% /mnt/pool

* [ ] strace of application having problem: 
strace -o /tmp/xattr.strace xattr -l /mnt/pool/.mergerfs
Output:  http://dpaste.com/2XT36T1

**Comment by trapexit** [comment]
You disabled them.

https://github.com/trapexit/mergerfs#xattr

> nosys will cause mergerfs to return ENOSYS for any xattr call. The difference with noattr is that the kernel will cache this fact and itself short circuit future calls. This will be more efficient than noattr but will cause mergerfs' runtime control via the hidden file to stop working.

**Comment by trapexit** [comment]
I'm working on a new runtime config system that won't use xattr but it's not out yet.

**Comment by azilber** [comment]
Thanks.  I figured it was probably related to that, so I changed it to noattr.
Another issue that this creates when using nosys, is that the mergerfs-tools stop working as well, as they stop being able to read those attributes.

Does Fuse have any data in /proc/?  Maybe you could use that instead?

**Comment by trapexit** [comment]
> mergerfs-tools
Yeah. It disables xattr in general. The tools need the runtime config interface to query the software.

> /proc
This is a completely custom interface. There is no generic API available to do this. There are a few ways to manage the situation... I just need to pick one and do it... but it will require a change to all the tooling.
