### ISSUE TITLE
error: fileid changed#012fsid 0:52: expected fileid 0xfba107efa027, got 0x2db84ad65e

### ISSUE THREAD

**Issue by swimfish09** [trapexit/mergerfs#670]
General description
===================
error: fileid changed#012fsid 0:52: expected fileid 0xfba107efa027, got 0x2db84ad65e

**Precise** steps to reproduce the behavior
===========================================

> now i can not reproduce it.

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
```
mergerfs version: 2.28.1-6-g52e4d60
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.2
using FUSE kernel interface version 7.29
```
* [x] Linux version: `uname -a`
```
Linux nas-001 5.2.8-1.el7.elrepo.x86_64 #1 SMP Fri Aug 9 13:40:33 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
mergerfs /mnt1/test:/mnt2/test /mnt/test -o rw,allow_other,use_ino,noforget,category.action=ff,category.create=ff,category.search=newest,dev,suid
```

**Comment by trapexit** [comment]
I'm sorry but I've no idea what you're reporting. You've provided almost no information.

As the ticket requests... provide as much information as possible. You don't even indicate what the error is from.

**Comment by swimfish09** [comment]
the error is from nfs client /var/log/messages

**Comment by swimfish09** [comment]
like Sep 22 19:03:53 server111 kernel: NFS: server 192.168.245.20 error: fileid changed#012fsid 0:43: expected fileid 0x2dbf21d794, got 0xfbf20269be3d

**Comment by trapexit** [comment]
What does your export file say? What is the fsid values? You need to ensure they are different per mount.

**Comment by swimfish09** [comment]
yes they are all different 
![image](https://user-images.githubusercontent.com/3916975/65470531-3eb8ac80-de9e-11e9-9745-3dcd05c1cb2d.png)

**Comment by swimfish09** [comment]
![image](https://user-images.githubusercontent.com/3916975/65470609-88a19280-de9e-11e9-8daa-613c985146a7.png)

**Comment by swimfish09** [comment]
Errors appear sometimes, not all the time.

**Comment by swimfish09** [comment]
And i will update file on the nfs server

**Comment by trapexit** [comment]
As the docs mention NFS and FUSE don't play all that nice together. It's a kernel level issue. Some people have no problems and others do and I'm not sure what the differences are. 

You could try not using "use_ino" or disable caching "cache.files=off". Otherwise I can't really say.

You should also update to the latest version.

**Comment by swimfish09** [comment]
nfs client kernel `Linux server101 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
server and client with different kernel will cause the problem?

**Comment by swimfish09** [comment]
not using "use_ino" will cause nfs stale error
disable caching "cache.files=off" will affect the performance

**Comment by trapexit** [comment]
As I said... there are issues with FUSE and NFS. There is little I can do. The kernel versions should not make any difference.

Have you benchmarked the performance difference? What is it?

There isn't much I can do but suggest settings that minimize the possibility of things changing from under NFS. This is really not something I have much control over. It's a limitation of the technology.

**Comment by trapexit** [comment]
Are you running multiple instances of a FUSE filesystem?

**Comment by swimfish09** [comment]
yes, with multiple mergerfs process

**Comment by trapexit** [comment]
Have you seen the issue when only one instance is running?

**Comment by trapexit** [comment]
https://sourceforge.net/p/fuse/mailman/message/29480143/

Not generally but for the interaction between FUSE and NFS it might be.

It's a simple fix if it is in fact a problem but this thread was never followed up on AFAICT and I don't know what else the issue may be given others seem to have no problems. 

Could you try a single mount to see if the issue shows up? If not I'll make a change to see if that was the problem.

**Comment by swimfish09** [comment]
ok, but this is my production environment, and i will reproduce it in my test environment.

**Comment by swimfish09** [comment]
i use mergerfs to union a nfs dir and local directory then export it

**Comment by swimfish09** [comment]
i think i kown what the problem
"/mnt1/test"  "/mnt2/test" both contains dir test1 and if i rm the newest dir test1 from the server side
at the same time nfs client cd test1 and ls then the error will display

**Comment by trapexit** [comment]
Sure. As it mentions in the docs you shouldn't be modifying things from underneath the pool. Any cached values used downstream will break.

**Comment by swimfish09** [comment]
now disable caching  "cache.files=off" is the only solution?

**Comment by trapexit** [comment]
I don't believe that will "fix" it. You will still be changing values underneath the system. Have you tested it?

**Comment by swimfish09** [comment]
yes disable caching "cache.files=off" not work

**Comment by trapexit** [comment]
Why are you modifying things out of band?

**Comment by swimfish09** [comment]
i need sync files from /mnt/test1 to /mnt/test2, direct access /mnt/test1 is slow

**Comment by swimfish09** [comment]
keep the same dir innode not change will cause problem?

**Comment by trapexit** [comment]
The inode returned depends on the underlying data as described in the docs. If you change the underlying data not through mergerfs then the inode can suddenly change. But I don't know for sure that's the issue. FUSE doesn't use the inode. There is an internal node id shared with the kernel. That's that issue afaik. Otherwise disabling `use_ino` should work since it just makes up values per node and they shouldn't change due to a change in underlying data.

I don't use NFS. If you can pin point *exactly* what changes lead to these errors I can investigate more but many people use NFS with mergerfs without issue so something is obviously different about your setup.

**Comment by swimfish09** [comment]
Disabling use_ino can work, nfs stale error disappear, but fileid changed still will appear.

**Comment by swimfish09** [comment]
Disabling use_ino not work well, if a change happened in underlying data, nfs client can not see the newest data.

**Comment by trapexit** [comment]
Without additional information I'm not sure I can help. Many export mergerfs with NFS. If you can provide explicit, reproducible settings we can look at this again.
