### ISSUE TITLE
task smbd blocked for more than 120 seconds.

### ISSUE THREAD

**Issue by KrisTheGreat** [trapexit/mergerfs#671]
General description
===================

I use MergerFs on OMV 4.1.24-1. Randomly, usually once a day I got services hung. Sometimes it is smbd and sometimes transmission (depends what I use at the time). When this happens there service is unavailabe, I'm unable to restart or even kill the service's process. The only way get it working again is to restart -f the system. Kern.log attached.

**Precise** steps to reproduce the behavior
===========================================

Do any file operation using smbd. 

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`

mergerfs -V
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.29

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments

UUID=ea6fa12b-6a43-4ad5-9532-41dbb0dcf2f9 /               ext4    errors=remount-ro 0       1
# swap was on /dev/sda5 during installation
UUID=b37248d6-b662-4c3d-bdb3-fb201ff410b3 none            swap    sw              0       0
tmpfs           /tmp            tmpfs   defaults        0       0
# >>> [openmediavault]
/dev/disk/by-label/parity1 /srv/dev-disk-by-label-parity1 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/dev/disk/by-label/data1 /srv/dev-disk-by-label-data1 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/dev/disk/by-label/data2 /srv/dev-disk-by-label-data2 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/srv/dev-disk-by-label-data1:/srv/dev-disk-by-label-data2 /srv/45e0eade-076e-4ce6-8e98-4420663a380a fuse.mergerfs defaults,allow_other,direct_io,use_ino,category.create=lfs,minfreespace=40G 0 0

* [ ] Linux version: `uname -a`

Linux nas 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-5+deb10u2~bpo9+1 (2019-08-16) x86_64 GNU/Linux

* [ ] Versions of any additional software being used

-

* [ ] List of drives, filesystems, & sizes: `df -h`
System plików  rozm. użyte dost. %uż. zamont. na
udev            3,9G     0  3,9G   0% /dev
tmpfs           794M  9,0M  785M   2% /run
/dev/sda1       102G  3,0G   94G   4% /
tmpfs           3,9G     0  3,9G   0% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs           3,9G     0  3,9G   0% /sys/fs/cgroup
tmpfs           3,9G  8,0K  3,9G   1% /tmp
1:2             5,5T  3,2T  2,4T  57% /srv/45e0eade-076e-4ce6-8e98-4420663a380a
/dev/sdb1       2,8T  2,8T   23G 100% /srv/dev-disk-by-label-parity1
/dev/sdd1       2,8T  2,7T   37G  99% /srv/dev-disk-by-label-data2
/dev/sdc1       2,8T  422G  2,4T  16% /srv/dev-disk-by-label-data1

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
-

* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o 
/tmp/mergerfs.strace.txt
[kern.log](https://github.com/trapexit/mergerfs/files/3642832/kern.log)
`

**Comment by trapexit** [comment]
Please use a current release of mergerfs (2.28.2) before I spend time looking into this.

**Comment by KrisTheGreat** [comment]
It seems the problem is gone after upgrading mergerFs to 2.28.2. Thanks.
