### ISSUE TITLE
2.28.2 Alpine Won't run

### ISSUE THREAD

**Issue by alexyao2015** [trapexit/mergerfs#672]
General description
===================
There is some nasty error message that comes when running the latest version on Alpine. Previous version, 2.28.1 did not have this issue.

Expected behavior
=================
Does not crash/die

Actual behavior
===============
Error relocating /usr/bin/mergerfs: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.
Add apk from Alpine repository. Run and watch.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ ] Linux version: `uname -a`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
That's a build / runtime issue. That's not a mergerfs issue. How did you install it? You should rebuild it / talk to the packager.

**Comment by alexyao2015** [comment]
I am still using [this](https://git.alpinelinux.org/aports/commit/?id=1652a7e32d9a7d82f0040e7e67951d5ce83483e0) Alpine package and from previous commits, there seems to have been nothing changed to the way that it was being built. Only thing updated was the version being built. It is installed in a docker container and I have not changed the dockerfile so everything was exactly the same as when it previously worked.
[Here's](https://build.alpinelinux.org/buildlogs/build-edge-x86_64/testing/mergerfs/mergerfs-2.28.2-r0.log) the build log, don't know if there is something important that you can see in there.

**Comment by trapexit** [comment]
The error you show above is a runtime issue with finding ostringstream. That's not anything to do with mergerfs. I really can't comment much more. If I build mergerfs in an alpine:latest container it works just fine as does building from the aport APKBUILD so I'm not sure what's wrong with your setup but I'd suggest rebuilding and ensuring the system is updated.

**Comment by alexyao2015** [comment]
Can confirm that manually building does work fine. Thank you. Sorry about that, though I am still looking forward to an official alpine build.

**Comment by trapexit** [comment]
The aports version is kept up to date so I'm not sure what benefit there is for me doing it. It'd be literally the same thing.

**Comment by alexyao2015** [comment]
I would be interested if there was the APK file released in the releases so there would be an easier way to get older versions instead of manually building.
