### ISSUE TITLE
not case sensitive

### ISSUE THREAD

**Issue by patugo** [trapexit/mergerfs#673]
General description
===================
I have in one drive a Download folder (uppercase D) and in another drive a download folder (lowercase d)

Expected behavior
=================
list those 2 folders as separate

Actual behavior
===============
pick only the 1st one "found"

**Precise** steps to reproduce the behavior
===========================================
-create folder on "drive  1" with name AAA
-create folder  on "drive 2" with name aaa

System information
==================
mounted in fstab with options defaults,allow_other,use_ino,fsname=mergerFS

**Comment by trapexit** [comment]
mergerfs is absolutely case sensitive. Are you using a case insensitive filesystem under it?

**Comment by patugo** [comment]
oops.  Sorry.  Turns out there was a simlink on one of the drives already with that name.
Please delete this ticket.
Again, sorry.
