### ISSUE TITLE
Are there cache.files configurations that conflict with mmap? / Documentation update request

### ISSUE THREAD

**Issue by brettinternet** [trapexit/mergerfs#674]
# General description

> cache.files=libfuse: follow traditional libfuse direct_io, kernel_cache, and auto_cache arguments.

As I understand, this indicates `cache.files=libfuse` will conflict with `mmap`. However, does `cache.files=partial|full|auto-full` conflict with `mmap`? I believe the answer is **no** as long as `dropcacheonclose=true` is added.

The FAQ articulating the incompatibilities with caching and `mmap` usage is very helpful, including a comment @trapexit made on reddit which directed to me to this portion of the documentation ([1](https://www.reddit.com/r/homelab/comments/6icgwg/what_did_i_do_wrong_during_my_plex_setup/djf2rwn), [2](https://www.reddit.com/r/PleX/comments/9jxly2/plex_on_docker_cant_connect_to_webui/e6vkx5e)). [I found other apps conflict](https://serverfault.com/a/985541/408659) with `mmap` and `direct_io` including some mariadb versions and rspamd.

Is there potential to update this section of the FAQ according to the newer page caching configurations implemented in some of your most recent work (since deprecating `direct_io`)?

# System information

I am currently using version `2.24.2` as is available to Debian Stretch, however I'm anticipating how I'll make changes according to my configuration once Stretch catches up. Until Stretch updates mergerfs, I'm stuck unable to cache since a few key software require filesystems that support `mmap`.

---

Thank you for the attention you put in mergerfs. This is an awesome project!

**Comment by brettinternet** [comment]
As I typed this, I just found [FAQ: rtorrent fails with ENODEV (No such device)](https://github.com/trapexit/mergerfs#rtorrent-fails-with-enodev-no-such-device) which answers my question and examples `cache.files` relationship with `direct_io`. I've posted my question anyway in case someone else arrives here with a similar issue.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#caching explains how it all relates.
