### ISSUE TITLE
Direct all reads through particular branches?

### ISSUE THREAD

**Issue by Makeshift** [trapexit/mergerfs#676]
General description
===================
I have a semi-strange use case and was wondering if you had any suggestions to improve my current setup.

In total I have 7 mounts that I'm merging with mergerfs 
* 5 rclone Google Drive mounts that I'm essentially load balancing with mergerfs
* 2 plexdrive mounts (The same Google drive as above, but RO and with considerably better caching)

All of the branches are exactly the same, and are mounted using similar to the following command (Where RO are the plexdrive mounts and RW the rclone ones)

```
/usr/bin/mergerfs -d -o \
allow_other,\
use_ino,\
category.action=rand,\
category.create=rand,\
category.search=ff,\
/shared/mounts/RO_\*=RO:/shared/mounts/RW_\*=RW \
shared/merged
```
I would like to set up a policy or filter to direct all search through the plexdrive RO mounts and all action/create through the rclone mounts.

Expected behavior
=================
I was under the impression that the 'ff' search policy would be perfect for this use-case as it implies that mergerfs will return immediately upon finding a matching path, and will query the disks in order of mount. I can see that my mounts are in the correct order for this to happen, and I can see that the search category is correct:
```
user.mergerfs.branches:/shared/mounts/RO_plexdrive1=RO:/shared/mounts/RO_plexdrive2=RO:shared/mounts/RW_rclone1=RW:shared/mounts/RW_rclone2=RW:shared/mounts/RW_rclone3=RW:shared/mounts/RW_rclone4=RW:shared/mounts/RW_rclone5=RW
user.mergerfs.category.search: ff
```

Actual behavior
===============
Mergerfs seems to query all branches and wait for a response from all of them before returning the response.
With a simple "ls" on a directory containing many directories, the timing difference is quite obvious. For example:
* In the RO Plexdrive mount: 
real    0m0.715s
user    0m0.010s
sys     0m0.011s
* In the RW rclone mount:
real    0m10.321s
user    0m0.009s
sys     0m0.006s
* In the mergerfs mount:
real    0m17.921s (This much longer time is explainable as all 5 rclone mounts are querying at the same time and being throttled)
user    0m0.014s
sys     0m0.000s

I can see in the plexdrive/rclone logs that mergerfs is querying each of the disks and waiting for the response before returning the ls. I would have expected the 'ff' policy to immediately respond as soon as the response from plexdrive comes through (which I can see in the logs is almost immediate).

By removing the RW branches, I can see the RO-only merge works as fast as expected:
```
/usr/bin/mergerfs -d -o \
allow_other,\
use_ino,\
category.action=rand,\
category.create=rand,\
category.search=ff,\
/shared/mounts/RO_\*=RO \
shared/merged
```
real    0m0.137s
user    0m0.032s
sys     0m0.024s

**Precise** steps to reproduce the behavior
===========================================

This is a little difficult to reproduce as it requires a lot of setup to be previously done with rclone. I'm also running this in a complex docker setup that I wouldn't expect anybody to want to replicate. I'm mostly looking for advice on the theory and a confirmation of how the policies work, or if it's possible to implement custom filters for search.

System information
==================
Please provide as much of the following information as possible:

* [X] mergerfs version: `mergerfs -V`: 
mergerfs version: 2.28.2
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.8
using FUSE kernel interface version 7.29
* [X] mergerfs settings: `cat /etc/fstab` or the command line arguments (Above)
* [X] Linux version: `uname -a`
Linux e8302eecd8dc 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 Linux (Alpine Linux - Dockerfiles available on request)
* [X] Versions of any additional software being used:
Plexdrive 5.0.0
Rclone 1.49.5
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
I'm not exactly sure what you're trying to accomplish. An `ls` is a very expensive function in general. It calls `readdir` then `getattr` on every file returned by readdir. Sometimes it'll just do `readdir` if you don't request metadata (like `ls -1`). 

For readdir mergerfs has to query every branch. If that's a concern try using readdir caching. For getattr you can increase attr and entry caches.

`ff` does only scan in order and returns first found but you have to be more specific. Every function behaves slightly differently.

**Comment by Makeshift** [comment]
Essentially what I'm trying to do is have a filter similar to the `:RO` filter on mount, except to forbid any search/reads on those mounts, but permit writes.

This is an odd use case, but essentially I have many mounts containing exactly the same data but are accessed via a different mechanism on a fuse mount. Some of these mounts are optimised for reading but are read only, while others have extremely slow read (so I would like to avoid reading from them at all) but fast write. My workload is as such that the files will not be needed to be read right after writing, so any temporary inconsistencies between the mounts should be negligible.

These fuse mounts in general aren't incredibly stable, hence using mergerfs to essentially 'load balance' them.

My attempted workaround for this was to use `ff`, hoping that `readdir` (and similar) would return as soon as the first branch replied, however as you said above that isn't the case.

I understand if this isn't a use case that you'll support, since it is kind of ridiculous, but I was just wondering if it was possible :)

**Comment by trapexit** [comment]
> Essentially what I'm trying to do is have a filter similar to the :RO filter on mount, except to forbid any search/reads on those mounts, but permit writes.

You simply can't do that. Has nothing to do with mergerfs. A file must exist to write to it. It could have permissions to not allow access or stat'ing it but you can't not have it show up at all. 

> These fuse mounts in general aren't incredibly stable, hence using mergerfs to essentially 'load balance' them.

You mean rclone mounts. FUSE is the general technology that allows it to work in userspace.

> My attempted workaround for this was to use ff, hoping that readdir (and similar) would return as soon as the first branch replied, however as you said above that isn't the case.

You aren't understanding how those functions work. If readdir returned after the first branch there'd be no merging at all. Anything that searched for files (which readdir is used for) would see only the first drive. getattr does return after the first file found but you have to already know the file name. Whether or not that's true is dependent on the software in question. `ls` obviously doesn't unless given the file name. If you just type `ls` it calls readdir to get the list of files then often will stat them to get additional information (size, inode, etc.)

Why don't you just use one mount for reads and another for writes? That seems a whole lot simpler. You have control over the software that is reading or writing. Point writers to the rclone pool and readers at the plexdrive pool.

**Comment by trapexit** [comment]
And does rclone caching not help here? I was under the impression that the caching layer was added specifically for this kind of situation.

**Comment by Makeshift** [comment]
Ah - I understand, thanks for your explanation!

The caching in rclone is a little lacking, and for various reasons I've had much more success with plexdrive's pre-caching. While I do control the software doing the read/writes, they are the same software (eg. sonarr, radarr) and so not easy to point at two separate mounts. I was trying to use mergerfs to take advantage of both systems simultaneously, but as you've explained, that's just not how it works.

As the vast majority of the reading I'll need to do is during the initial scan, I'm opting to just merge the plexdrive's and introduce the rclones into the pool later when I actually start doing the writes. I was just trying to be lazy and have it all set up at once :)

Thanks again - Really appreciate your time.
