### ISSUE TITLE
.fuse_hidden files accumulating

### ISSUE THREAD

**Issue by HikinenM** [trapexit/mergerfs#678]
General description
===================

I installed Home Assistant to my home server and to get logging working properly I had to remove the option direct_io because the sqlite database that Home Assistant uses. Since that change sqlite started successfully access the database and logging etc. works. On the other hand there is now hundreds of .fuse_hiddenXXX files creeping up as time goes by.  Everyday I get around 60-70 more.

I know that I can move the config location to my system disk with plain ext4 filesystem but I just wanted to look for solution first if possible instead of workaround.

Screenshot of the sight from my Windows PC to the folder with the .fuse_hidden files:
https://i.imgur.com/61kwQXR.png

Expected behavior
=================

No .fuse_hidden files accumulating.

Actual behavior
===============

.fuse_hidden files accumulating.

**Precise** steps to reproduce the behavior
===========================================

I installed Home Assistant as a docker and pointed the config to be located on the mergerfs and SMB/CIFS share to enable easy access from my Windows PC.

I then changed mount-options for mergerfs in Openmediavault Union filesystems component to:
defaults,allow_other,use_ino,direct_io
->
defaults,allow_other,dropcacheonclose=true,use_ino,cache.files=auto-full

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.25.1
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
/srv/dev-disk-by-id-ata-WDC_WD40EZRZ-00GXCB0_WD-WCC7K2YPLL3F-part1:/srv/dev-disk-by-id-usb-WD_My_Book_25EE_574343344535434A3333394E-0-0-part1:/srv/dev-disk-by-id-ata-WDC_WD60EZRZ-00GZ5B1_WD-WX11D65CUXA9-part1:/srv/dev-disk-by-id-ata-WDC_WD40EZRZ-00GXCB0_WD-WCC7K7HCKJEF-part1:/srv/dev-disk-by-id-ata-ST2000DL001-9VT156_5YD29P70-part1 /srv/b8beb75a-be9a-499c-82da-a09cd56ddd74 fuse.mergerfs defaults,allow_other,dropcacheonclose=true,use_ino,category.create=mfs,minfreespace=4G 0 0

* [ ] Linux version: `uname -a`
Linux openmediavault 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux

* [ ] Versions of any additional software being used
Openmediavault version Arrakis 4.1.21-1
Home Assistant 0.100.2

**Comment by trapexit** [comment]
1) Please use a current version of the software. 2.25.1 is old and current versions don't even create .fuse_hidden files.
2) Said files shouldn't "accumulate". They are temporary and created due to deleted files still being in use.

**Comment by HikinenM** [comment]
Thanks, I updated to the current version manually and issue is gone.
