### ISSUE TITLE
docker --data-root path changed to mergerfs pool, docker overlay2 refuse to mount on mergerfs pool

### ISSUE THREAD

**Issue by toktay** [trapexit/mergerfs#680]
I am running /root partition on ssd with limited capacity. However I have mounted 4 sata disks drives with snapraid/mergerfs combination at /storage/pool. I changed docker --data-root  directory from /var/lib/docker /storage/pool/docker/data. Suddenly  I have started to receive following errors when running docker container which itself is also using a union filesystem. 

ERROR: for ...  Cannot create container for service .....: b'error creating overlay mount to /storage/pool/docker/data/overlay2/

dmesg shows  
 overlayfs: filesystem on '/storage/pool/docker/data/overlay2/opaque-bug-check105060867/l3' not supported as upperdir 

When I changed the docker --data-root path directly to the mounted disk, it works. 

As far as I understand, overlay conflicts with mergerfs. 

I can live with current situation but  I prefer using mergerfs. I may forgot this detail in the future

**Comment by trapexit** [comment]
There is nothing I can do. overlayfs, like FUSE, has a whitelist of other filesystem types it can interact with. overlayfs doesn't allow a fuse path as the upperdir because it can't guarantee anything about it since it's not a well defined filesystem.
