### ISSUE TITLE
Resilio in Docker on omv

### ISSUE THREAD

**Issue by GeneralMidi** [trapexit/mergerfs#681]
General description
===================
I have resilio sync running in Docker on openmediavault. I pass the user id and group id to the Docker image. I mount the union fs in the image. I don't get any errors, but resilio is not 'seeing' the union fs. The files are not being spread out as I've specified. 

I'm certain it's not a permissions issue. I feel it's a Docker issue, but I'm unsure how to proceed. 

I have defaults, allow_other, direct_io, use_ino

I saw about mmap but it's a touch beyond me. 

Thanks for your time. 

Expected behavior
=================
As resilio syncs files, the files should be spread across the drives as specified in mergerfs. It should also not sync any files already on the drive. I've run this perfectly without the unionfs. 

Actual behavior
===============
As I'm mounting the unionfs in the Docker image, the files are not spread out, plus resilio seems not to see existing files and therefore skip those files. It wants to sync fully every file, as if it can't see the files on the union fs. 

**Precise** steps to reproduce the behavior
===========================================
Pass uid and guid in resilio Docker image. Mount unionfs as a folder in resilio. Sync files. Files are not spread or being seen by resilio. 

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

Running omv 4
Mergerfs version 2.27.1

* [x] mergerfs version: `mergerfs -V`
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ ] Linux version: `uname -a`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
Sorry... what are you asking? Precisely?  You've not filled out almost nothing in the form.

**Comment by GeneralMidi** [comment]
I apologise. I've edited my question.

**Comment by trapexit** [comment]
1) Please use the most recent release.
2) have you "exec"ed into the container and checked that you can in fact see the files? almost always it's a permission issue. Docker is using namespaces. That complicates things.

**Comment by GeneralMidi** [comment]
Thanks for your response. I did see this

https://github.com/trapexit/mergerfs/issues/463

Could this be the same for resilio sync in Docker with direct_io?

**Comment by trapexit** [comment]
direct_io impacts reading and writing. Not listing.

**Comment by trapexit** [comment]
Any updates?

**Comment by GeneralMidi** [comment]
Hi, sorry for not updating. It's working. For anyone in the future having issues, try deleting the docker container and starting over. There was something very strange going on, but I saw that as a solution in the OMV forums, and it also worked here!
