### ISSUE TITLE
Os Reinstall Issue

### ISSUE THREAD

**Issue by DavideCampagna** [trapexit/mergerfs#682]
Hi,
I'm currently using MergerFS on Ubuntu Server 19 with 3 disks.
Unfortunately I need to perform a new clean install of the OS, is there a way for me to do it without losing all my data?
Can I "break" the pool and "reconstruct" it as it was, with out touching any file in those hdds? 

Sorry to bother you and thank you for your wonderful program.

**Comment by Wintersdark** [comment]
No worries.  MergerFS doesn't touch the base filesystems.  You can access the drives directly, and simply mounting them in the same way on another system will work exactly the same as it does now.  The "pool" is just an overlay, it's not like RAID.

That's the real magic of MergerFS vs most other solutions along these lines.

**Comment by DavideCampagna** [comment]
Perfect! Thank you

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#can-mergerfs-be-used-with-drives-which-already-have-data--are-in-use

If you think I can answer that more clearly I'm happy to update it.
