### ISSUE TITLE
if the two path has the same mtime file while file will read

### ISSUE THREAD

**Issue by swimfish09** [trapexit/mergerfs#683]
General description
===================
mergerfs -o allow_other,use_ino,noforget,category.action=ff,category.create=ff,category.search=newest  /mnt/test1:/mnt/test2    /mnt/test

/mnt/test1 and /mnt/test2 contains a same file with same mtime which path will choose to read.

**Comment by trapexit** [comment]
You mean which will it choose to open? Reading is done on the file chosen to open.

Looks like it checks if the mtime is less than the newest found so far it will skip it which means if they are identical it will end up choosing the last one found. I'm also noticing that I don't compare nanoseconds. Generally I prefer the first to win a tie. Perhaps I should change this.

https://github.com/trapexit/mergerfs/blob/master/src/policy_newest.cpp#L132
