### ISSUE TITLE
`mount -a` with nonempty continually mounts itself.

### ISSUE THREAD

**Issue by KyleSanderson** [trapexit/mergerfs#687]
General description
===================
when you use nonempty you can overlay mergerfs onto mergerfs to get process-based sharding.

Expected behavior
=================
`seq 10 | xargs -I -- mount -a && grep mergerfs | wc -l` = 1

Actual behavior
===============
`seq 10 | xargs -I -- mount -a && grep mergerfs | wc -l` = 11...

https://github.com/lizardfs/lizardfs/issues/807

**Comment by trapexit** [comment]
There is nothing that can be done about that without manual attempts by mergerfs to forbid mounting on top of itself (which is a useful feature for live updates). fusermount just works that way and unless I replace fusermount with my own I can't do anything about it.

There isn't a practical way with FUSE to "remount" so mounting on top is kindof the only alternative.

**Comment by KyleSanderson** [comment]
> There isn't a practical way with FUSE to "remount" so mounting on top is kindof the only alternative.

hmmm...  Controllable by a mount flag.
replace_process = Spawn new process, mount over the existing mount, kill the old process (?).
noreplace_process = mergerfs looks to see if it's already a mergerfs mount, if it is - die.

**Comment by trapexit** [comment]
You can't simply kill the old process. That would screw up anything currently using it and monitoring that would be unbounded. It perhaps could try to umount it and continue if in use but in practice that probably be the same as today.

**Comment by KyleSanderson** [comment]
hmm... I was under the impression this was a solved problem since Linux 2.4 with the concept of doing a lazy umount. Instead of killing the old process lets do this instead?

**Comment by trapexit** [comment]
umount2 will require root which is likely to be the case if you're using fstab but fusermount isn't simply umount and is setuid root. I'm also not sure it'd work due to the fact that by the time mergerfs is running I believe the mount has already happened. mergerfs is just being given the /dev/fuse file descriptor. Would not be lazy umounting the underlying mount then. I'll need to investigate more.

**Comment by KyleSanderson** [comment]
> umount2 will require root which is likely to be the case if you're using fstab but fusermount isn't simply umount and is setuid root.
```
/disks/*T* /mnt fuse.mergerfs allow_other,use_ino 0 0
/disks/*T*/Web /mnt/Web fuse.mergerfs allow_other,use_ino,nonempty 0 0
/disks/*T*/Recordings /mnt/Recordings fuse.mergerfs allow_other,use_ino,nonempty 0 0
/disks/*T*/Backup /mnt/Backup fuse.mergerfs allow_other,use_ino,nonempty 0 0
```
Indeed. There's the same concept with fusermount though `-z`(?). Both seem to do the correct thing on my system as root.

> I'm also not sure it'd work due to the fact that by the time mergerfs is running I believe the mount has already happened.

hmmm... I'm not sure. If we take-over the mount and lazy unmount the old filesystem automatically we should be in the clear(?).

> I'll need to investigate more.

No worries - just kind of spit-balling at the moment here.

**Comment by trapexit** [comment]
If the path is already mounted then the new instance would see that. Not the underlying one. I imagine I can fish the underlying one out but off hand not sure.

**Comment by trapexit** [comment]
I know it's been a while but finally added the feature. Will be in the next release. Haven't added it to the docs yet but "lazy-umount-mountpoint=true" will issue a lazy umount call to the underlying filesystem of the mountpoint. I might need to make it more nuanced to only check for mergerfs mounts but right now it just issues the call regardless. If it isn't a mount then it will ignore it.

**Comment by KyleSanderson** [comment]
nice - thank you
