### ISSUE TITLE
mergerfs.consolidate doesn't work

### ISSUE THREAD

**Issue by KrisTheGreat** [trapexit/mergerfs#688]
General description
===================
mergerfs.consolidate doesn't work. When I run it with my "torrent" dir: `mergerfs.consolidate /srv/45e0eade-076e-4ce6-8e98-4420663a380a/torrent` I can hear that disks work for w while, but then there is no output and the program quits.

Expected behavior
=================
mergerfs.consolidate consolidates files to one drive.

Actual behavior
===============
doesn't work as expected

**Precise** steps to reproduce the behavior
===========================================

run `mergerfs.consolidate <dir>`

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`

`mergerfs version: 2.28.2
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.29
`

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda1 during installation
UUID=ea6fa12b-6a43-4ad5-9532-41dbb0dcf2f9 /               ext4    errors=remount-ro 0       1
# swap was on /dev/sda5 during installation
UUID=b37248d6-b662-4c3d-bdb3-fb201ff410b3 none            swap    sw              0       0
tmpfs           /tmp            tmpfs   defaults        0       0
# >>> [openmediavault]
/dev/disk/by-label/parity1 /srv/dev-disk-by-label-parity1 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/dev/disk/by-label/data1 /srv/dev-disk-by-label-data1 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/dev/disk/by-label/data2 /srv/dev-disk-by-label-data2 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/dev/disk/by-label/data3 /srv/dev-disk-by-label-data3 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/dev/disk/by-label/data4 /srv/dev-disk-by-label-data4 xfs defaults,nofail,noexec,usrquota,grpquota,inode64 0 2
/dev/disk/by-id/usb-Seagate_Expansion_NA49J97W-0:0-part1 /srv/dev-disk-by-id-usb-Seagate_Expansion_NA49J97W-0-0-part1 ntfs defaults,nofail 0 2
/srv/dev-disk-by-label-data1:/srv/dev-disk-by-label-data2 /srv/45e0eade-076e-4ce6-8e98-4420663a380a fuse.mergerfs defaults,allow_other,direct_io,use_ino,category.create=mfs,minfreespace=40G 0 0
# <<< [openmediavault]

```

* [ ] Linux version: `uname -a`
`
Linux nas 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-5+deb10u2~bpo9+1 (2019-08-16) x86_64 GNU/Linux
`

**Comment by trapexit** [comment]
Could you please list out *exactly* what you ran? Hard to comment otherwise. 

Having just run the tool it seems to work just fine.

**Comment by trapexit** [comment]
Also... you mention consolidate and balance. Which are you actually talking about?

**Comment by KrisTheGreat** [comment]
Sorry... I meant mergerfs.consolidate. I run mergerfs.consolidate <dir> without options.

**Comment by trapexit** [comment]
Are you positive files are spread across drives per directory? It works just fine for me.

**Comment by KrisTheGreat** [comment]
Yes, files are spread across drives per torrent directory.

**Comment by trapexit** [comment]
I really can't comment without very specific, explicit details. An example i can replicate.

**Comment by KrisTheGreat** [comment]
Ok, I understand. Can I use `rsync --remove-source-files -av /source /dest` for manually consolidate files?

**Comment by trapexit** [comment]
No. That would simply move the files to whatever drives the policy chooses.

To test just create the same relative path on a few drives and then add different files on each. Then run consolidate on the pool relative path.

**Comment by KrisTheGreat** [comment]
Ok, but if I run rsync directly on the drivers? rsync --remove-source-files -av /srv/dev-disk-by-label-data1/torrent/ /srv/dev-disk-by-label-data2/torrent/

**Comment by trapexit** [comment]
Yes. Of course that'd work. But that's not what consolidate does. It only consolidates per directory. Not everything from that directory and below like what you show does.

**Comment by KrisTheGreat** [comment]
Ok, thank you. I think this fixes the problem for me. I just want to have all torrent files on one drive to prevent other disk from spinning :)

**Comment by trapexit** [comment]
That's not necessarily going to happen if you continue to use your torrent app through mergerfs. mergerfs still will have to scan drives when directories are read by anything. Including the torrent app. Also... any new files will be spread out because you're using mfs create policy.

If you want to accomplish that then don't point the torrent app at the pool. Point it to one drive.
