### ISSUE TITLE
mfs not behaving as expected

### ISSUE THREAD

**Issue by GideonWolfe** [trapexit/mergerfs#690]
General description
===================
I am unable to use the `mfs` policy to automatically write to the disk with the most free space

Expected behavior
=================
If I put the following line in my `/etc/fstab`, I get a pooled directory at `/data`

`/home/gideon/Data:/drives/drive2/data /data fuse.mergerfs allow_other,use_ino 0 0`

My docker programs can see this perfectly fine, and they acknowledge the extra 7TB of space. However, downloads are still being saved to the full drive, `/home/gideon/Data` instead of the empty directory at `/disks/disk2/data`.

I attempted to change policies like so

`/home/gideon/Data:/drives/drive2/data /data fuse.mergerfs allow_other,use_ino,category.create=mfs 0 0`

Actual behavior
===============

Now none of my programs recognize the additional 7TB of free space. 

However, it seems that the `mfs` functionality works if I run the command 
`mergerfs -o allow_other,use_ino,category.create=mfs /home/gideon/Data:/drives/drive2/data /data
`
and manually copy a file into the merged folder.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`: 2.24.2
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments: above
* [ ] Linux version: `uname -a`: `Linux nas 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h` 
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

```
Filesystem         Size  Used Avail Use% Mounted on
udev               2.9G     0  2.9G   0% /dev
tmpfs              597M  2.6M  595M   1% /run
/dev/sdb2          7.3T  6.8T   95G  99% /
tmpfs              3.0G     0  3.0G   0% /dev/shm
tmpfs              5.0M  4.0K  5.0M   1% /run/lock
tmpfs              3.0G     0  3.0G   0% /sys/fs/cgroup
/dev/loop0         2.4M  2.4M     0 100% /snap/gotop/3
/dev/loop1         149M  149M     0 100% /snap/chromium/971
/dev/loop2          90M   90M     0 100% /snap/core/8268
/dev/loop3          55M   55M     0 100% /snap/lxd/12317
/dev/loop4          55M   55M     0 100% /snap/core18/1288
/dev/loop5         256K  256K     0 100% /snap/gtk2-common-themes/5
/dev/loop7          43M   43M     0 100% /snap/gtk-common-themes/1313
/home/gideon/Data  7.3T  6.8T   95G  99% /data
/dev/loop8         172M  172M     0 100% /snap/filebot/24
/dev/loop6         149M  149M     0 100% /snap/chromium/986
/dev/sda1          7.3T   93M  6.9T   1% /drives/drive2
/dev/loop9          55M   55M     0 100% /snap/lxd/12631
/dev/loop11         45M   45M     0 100% /snap/gtk-common-themes/1353
/dev/loop10         90M   90M     0 100% /snap/core/8213
/dev/loop12         55M   55M     0 100% /snap/core18/1279
tmpfs              597M  1.2M  596M   1% /run/user/126
tmpfs              597M     0  597M   0% /run/user/1000
```

**Comment by trapexit** [comment]
Please use the current version. Makes debugging far easier. 2.24.2 is pushing 2 years old.

According to that `df` it looks to me you don't actually have /drives/drive2 included in the pool as your "Filesystem" name is "/home/gideon/Data" which is not what it'd be based on your settings. Does /drives/drive2/data exist?

**Comment by GideonWolfe** [comment]
Had some unrelated issues and everything is cleared up now. For what it's worth, I would like to use a later version, but I was just using the default package in the Ubuntu repo.

**Comment by trapexit** [comment]
You can find packages for most recent Ubuntu versions over in the releases section: https://github.com/trapexit/mergerfs/releases
