### ISSUE TITLE
same inodes for different directories

### ISSUE THREAD

**Issue by JsliStorSwift** [trapexit/mergerfs#692]
General description
===================
two different directories should have two different inode numbers. But sometimes they have the same different inode numbers. So several filesystem operations like find will report errors. 

Expected behavior
=================
"find" command should return success. 

Actual behavior
===============
"find" command returned "find: File system loop detected". 

**Precise** steps to reproduce the behavior
===========================================
no exact detailed steps to reproduce. 

System information
==================
mergerfs -v
mergerfs version: 2.28.3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.29

**Comment by trapexit** [comment]
You need to give me actual details. What are your settings. What are the source inodes. What OS.

**Comment by JsliStorSwift** [comment]
this issue related to the algorithm of inode number generation. 
in mycase, the inode and dev of dir1 from branch1 is 180388627456 and 53. 
the inode and dev of dir2 from branch2 is 184683594752 and 53. 

by these values, the end virtual inode numbers are both 270582940672. 
This results in the above filesystem error.

**Comment by JsliStorSwift** [comment]
let me provide a simple fix: virtual_inode = actual_indoe | ((dev << 32) & 0xffffffff00000000).

**Comment by trapexit** [comment]
> virtual_inode = actual_indoe | ((dev << 32) & 0xffffffff00000000).

That is the algo already. The masking is not needed.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/blob/master/src/fs_inode.hpp#L38

**Comment by trapexit** [comment]
What filesystem is this?

**Comment by trapexit** [comment]
Regardless... I think I'll have to introduce a more complicated hashing function and hope for the best. dev_t and ino_t are both 64bit a simple OR will never be 100%. I'm surprised ... you are the first to report this.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/tree/inode

Can you try this out?

**Comment by JsliStorSwift** [comment]
Sorry, I went out for dinner and just returned back. My underlying filesystem is NFS.

**Comment by JsliStorSwift** [comment]
I will try inode branch.

**Comment by trapexit** [comment]
Don't bother with the above. I'm finding dups on my own system. Let me play more.

**Comment by JsliStorSwift** [comment]
the algorithm of fasthash64 in inode branch is stable so far? will it be changed largely in the future?

**Comment by trapexit** [comment]
I confused myself while testing due to a hardlink I had but it seems to be OK. There was a bug in the version prior so please try the latest. If it works for you then I can put out a new release.

**Comment by JsliStorSwift** [comment]
thanks a lot. I will try this branch. if no similar issue happens, I will be back to close this issue.

**Comment by trapexit** [comment]
I've pushed a more thorough patch with doc changes. You don't need to close this as it will close when I commit the change. Anyway... there isn't a guarentee that a collision won't happen but hopefully this will make it much less likely.

**Comment by jsclayton** [comment]
If it helps at all, I was able to work around the issue by taking the `use_ino` option out of the mount arguments. I know that's not an actual fix - I recall reading somewhere that you were thinking of removing that option completely - but it may be a helpful bit of information.

**Comment by trapexit** [comment]
Removing use_ino means it creates a unique value per node. So you won't be able to rely on inodes for hard linking or dedup.

**Comment by k-yeung** [comment]
> What filesystem is this?

My guess is XFS. I believe the inode number is a function of its on-disk location (according to the XFS FAQ, it requires 64-bit inode numbers to allocate inodes above the 1TB mark), so on large disks, bits 32 and above are frequently set, which enroaches on the bits used by the device number.

**Comment by k-yeung** [comment]
How about this instead?

```
-        st_->st_ino |= ((uint32_t)st_->st_dev << 16);
+        st_->st_ino |= bswap_32((uint32_t)st.st_dev);
       else
-        st_->st_ino |= ((uint64_t)st_->st_dev << 32);
+        st_->st_ino |= bswap_64((uint64_t)st.st_dev);
```

I think dev_t was originally 16-bits long, so chances are that the upper 48-bits are zero. If you flip the bits around with bswap, then the chances of the inode number clashing with it are minimal. There is also a dedicated instruction for this on x86/64 (BSWAP), so the performance impact should be minimal.

**Comment by trapexit** [comment]
Yeah, I already considered that. Traditionally dev_t is 16 bits but it is now at least 32 bits.  You don't need to bswap it... just (dev << 48). The performance isn't going to be an issue.

Regardless I suspect a good hashing function might be better. My prototype is using fasthash64. I need to run some tests to see if I get collisions but I need to build a bespoke app since I have hardlinks on my drives.

https://github.com/trapexit/mergerfs/blob/inode/src/fs_inode.hpp

**Comment by trapexit** [comment]
@JsliStorSwift Did the branch work for you? I'm thinking I should probably replace use_ino with a more complex option to allow for selecting from a couple different algos.
