### ISSUE TITLE
How to debug performance issues

### ISSUE THREAD

**Issue by thejinx0r** [trapexit/mergerfs#693]
General description
===================
Reading from mergerfs over zfs with encryption is really slow.

Expected behavior
=================
Reading from mergerfs results in >80% (at least 80MB/s) read speeds compared to reading from the disk directly.

Actual behavior
===============
Reading from mergerfs results in ~20%  (~28MB/s) read speeds compared to reading from the disk directly.

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

I am using debian buster with mergerfs 2.28.3.
I used zfs to create two single disk pools and then enabled compression with gzip-9, which is the highest level of compression:

`zpool create ors_disk_1 /dev/sdc
zpool create ors_disk_2 /dev/sdd
zfs set compression=gzip-9 ors_disk_2 ors_disk_1`

and then I used mergerfs to combine the two.
I used zfs because it seemed like compression on zfs was mature compared to btrfs.

When I read a file on the mergefs pool, vs reading the individual disk, this is the performance difference:
`130 eric@yenflix:/mnt$ dd if=/mnt/ors_storage/data/zBig.ORSSession of=/dev/null
^C6254910+0 records in
6254909+0 records out
3202513408 bytes (3.2 GB, 3.0 GiB) copied, 117.781 s, 27.2 MB/s

130 eric@yenflix:/mnt$ dd if=/mnt/ors_disk_2/data/zBig.ORSSession of=/dev/null                                                                                                                                                                               
43945595+1 records in
43945595+1 records out
22500144898 bytes (23 GB, 21 GiB) copied, 241.634 s, 93.1 MB/s
`

I generally get about 24-28MB/s depending on the parameters I tune for mergerfs, but never more than 28. With compression, the actual compresed size of the file is about 4.7GB.

Is there anything I can do to improve the performance?

System information
==================
Please provide as much of the following information as possible:

[x] mergerfs version: `mergerfs -V`
mergerfs version: 2.28.3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29

[x] mergerfs settings: `cat /etc/fstab` or the command line arguments
/mnt/ors_disk_* /mnt/ors_storage fuse.mergerfs allow_other,cache.open=5,cache.statfs=5,cache.attr=5,cache.entry=5,cache.readdir=true,splice_move,splice_read,splice_write,fuse_msg_size=32,threads=16,cache.files=off,use_ino,category.create=mfs,minfreespace=25G,fsname=ors_data 0 0

[x] Linux version: `uname -a`
Linux yenflix 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

[x ] Versions of any additional software being used
`zfsutils-linux 0.7.12-2+deb10u1 amd64        command-line tools to manage OpenZFS filesystems`

[x] List of drives, filesystems, & sizes: `df -h`
`ors_disk_1        8.8T  744G  8.1T   9% /mnt/ors_disk_1
ors_disk_2        8.8T  744G  8.1T   9% /mnt/ors_disk_2
ors_data           18T  1.5T   17T   9% /mnt/ors_storage`

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
I need more information to help. What version ZFS? Kernel based or FUSE based? Are you saying ZFS without encryption is faster? Why the small fuse_msg_size? You should let the system choose unless you're benchmarking.

Your dd benchmark is not ideal. You should explicitly set read/write sizes and use synchronous transfers. Have you read the docs regarding benchmarking and performance tweaking?

https://github.com/trapexit/mergerfs#nullrw

**Comment by thejinx0r** [comment]
Thanks for the quick reply.
For ZFS, I assume it's kernel based. I don't really know, but I know I don't have zfs-fuse installed.
Just to clarify, I use zfs with compression, not encryption.
I haven't benchmarked zfs without compression as I do need it on. What I am saying is that when I read a file from mergerfs, it is alot slower compared to just  reading the same file directly from disk. 

I have read the performance tweaking. Hence the smaller fuse_msg_size. The default is 256, which is the max. So I've tried many different combinations and nothing really affected the performance. But as you pointed out, I need to change how I benchmark with dd.

I did not try nullrw as I missed that part. I will try it later.

**Comment by trapexit** [comment]
Generally speaking there isn't much I can do regarding performance. It seems to vary quite a bit across systems and I've yet to really nail down why otherwise similar systems seem to vary. That's why I created the "nullrw" mode so that the underlying storage can be removed from the equation. My speculation that it tends to be a latency issue. That the latency overhead of individual blocking requests kills throughput but that depends greatly on the app. Some apps are smart about r/w buffer sizes and others not. Some are very serial and synchronous and others parallel and async. Some of that can be mimicked with the dd ibs and obs to give a sense of how much of an impact it can have.

**Comment by trapexit** [comment]
I rewrote the section on benchmarking and performance. Maybe take a look to see if it helps in narrowing down things.

**Comment by thejinx0r** [comment]
Thanks for the update. 
With the non default options for dd, I was able to get ~50% of the performance of direct access to the disk. I tried different ibs/obs and mount parameters in a python script and I noticed in htop that when I access the disk directly, dd uses 100% of one core. When I was accessing the same file through mergerfs, dd would only be ~4-8% and mergerfs would consistently be at >90% of one core.

nullrw was super fast, so I ended up removing it, but it was consistently giving >1GB/s.

**Comment by trapexit** [comment]
nullrw should be super fast as it literally does nothing with the data. It's solely for finding theoretical top performance.

With what settings for `dd`? I just tested `dd if=/dev/zero of=tmp.file bs=1M count=1024 oflag=nocache conv=fdatasync status=progress` both in the mergerfs pool and out and dd hits only a few % CPU usage. It should be IO bound and use very little CPU. mergerfs tops out around 30% CPU but my system is very busy and don't have the time to setup a second instance. This is on a 3rd gen i7 hitting hard drives. Which btw I get almost identical speeds direct and through mergerfs and that's on a rather busy system IO wise.

I wonder if it's the zfs compression just eating up the CPU and either bad scheduling not putting mergerfs threads and dd on different cores. What CPU are you using? Underlying storage? 

Maybe try setting the number of mergerfs threads to 1 just to see if that impacts anything.

**Comment by thejinx0r** [comment]
Didn't expect that: setting it to 1 thread works.
It doesn't quite reach the same speeds, but definitely much closer. 

Surprisingly, mergerfs still hits >90% on my cpu. It's a an AMD Ryzen 1700x. The drives are over usb right now. ZFS filesystem on each drive.

This was the dd command I used
`dd if={input_file} of=/dev/null ibs={ibs} obs={obs} iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress` with ibs and obs in this range: `["512K", "1M", "2M", "4M"]`

**Comment by trapexit** [comment]
Interesting. Few things... USB generally has higher overhead. Higher and less consistent latency.  Could be part of the story. As well as the ZFS compression. Someone else is reporting slower performance on a Ryzen system. Would seem odd that Ryzen systems would have an issue but I suppose it's plausible.

https://github.com/trapexit/mergerfs/issues/695

**Comment by trapexit** [comment]
BTW... when doing full tests with dd I suggest going down to 512 bytes... not kilobytes. That's the classic blocksize. It and 4k (typical page size) are not uncommon values for reading / writing data. Hopefully most software isn't using such small values but some do.

**Comment by trapexit** [comment]
I doubt it'll make a difference but *just in case*... it was suggested to me for Ryzen systems to ensure the BIOS is up to date.

**Comment by thejinx0r** [comment]
Thanks for all the ideas @trapexit .
In the end, it was an "admin" error. 

In the end, it was a process that was taking a lot of memory.
At first, I didn't have a swap, and then I enabled it, and I still ran out of memory, with the swap hitting capacity.

On stopping that process and running the benchmarks again, with the [512, 4K] for IBS/OBS, I get approximately the same performance when they are both at 4K.  

For the cpu usage, it's higher than ever. The mergerfs process hit 180% cpu usage. But as mentioned before, I have ZFS compression enabled and I'm not sure how top assigns cpu usage if it's kernel based. I will assume that since I'm getting better performance, that the increased cpu usage is due to the increased decompression and not related to mergerfs directly.

Thanks again for the help.

**Comment by trapexit** [comment]
Glad you've mostly figured it out. I'd suggest trying to bench on a plain zfs setup and xfs or ext4 if you can. Would be good to see what exactly is the bottleneck.I'd suspect it's zfs but... 

Regardless, glad to help. Feel free to reach out again if you have any questions or concerns in the future.

**Comment by thejinx0r** [comment]
I think it was really the swapping that was going on that caused the bottle neck.
Right now, I'm getting ~200MB/s reads from it.  I haven't tested writes, but this was mostly for reading anyways, so I'm happy with the performance.
