### ISSUE TITLE
Slow speed on write/read to/from MergerFS

### ISSUE THREAD

**Issue by Prosecutor** [trapexit/mergerfs#695]
General description
===================
Mounted MergerFS but speed is slow (Compared with other server).

Expected behavior
=================
I was expecting some better speeds on this type of server.

Actual behavior
===============
The speed is like strange for me.

**Precise** steps to reproduce the behavior
===========================================
So here is some information. I'm owning 2 servers.
1) Ryzen 5 3600 / 64GB RAM / 4x1 TB NVMe SSD.
2) E-2288G / 32GB RAM / 2x960 GB NVMe SSD.

When I'm launching the tests I'm getting a big difference.

Let's take a look at the first server.

```
(1:169)# dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1042284544 bytes (1.0 GB, 994 MiB) copied, 17 s, 61.3 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.5234 s, 61.3 MB/s
```

```
dd if=/home/user/rclone/gmedia/Media/benchmark of=/dev/null
917504+0 records in
917504+0 records out
469762048 bytes (470 MB, 448 MiB) copied, 4.42408 s, 106 MB/s
```

And now the second one

```
(1:504)# dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1038090240 bytes (1.0 GB, 990 MiB) copied, 2 s, 519 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.08218 s, 516 MB/s
```

```
dd if=/home/user/rclone/gmedia/Media/benchmark of=/dev/null
917504+0 records in
917504+0 records out
469762048 bytes (470 MB, 448 MiB) copied, 2.28686 s, 205 MB/s
```

So as you can see there is a big writing speed difference. I'm not telling that they should be the same, but why this might happen? Is there any way to improve the speed?

System information
==================
Please provide as much of the following information as possible:
For both servers i use same configurations.

```
mergerfs version: 2.28.3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29
```
I'm running it through services as mount. (I'm using MergerFS for Plex and gdrive)
So options witch I'm using is this:
```
dropcacheonclose=true,threads=12,async_read=false,use_ino,cache.files=auto-full,allow_other,func.getattr=newest,category.action=all,category.create=ff
```

Or you need the full command?

```
Linux amd 4.19.96-xanmod46 #1.200114 SMP PREEMPT Tue Jan 14 21:54:52 -03 2020 x86_64 GNU/Linux
```

Raid 0. 70GB on "/" all ther in "/home" location.

**Comment by trapexit** [comment]
What is the underlying mount? rclone? the NVMe?

Have you tried using the nullrw option for benchmarking to get a baseline?

**Comment by Prosecutor** [comment]
@trapexit Yes, it works like Rclone => MergerFS. 

Of course :)

First server:

```
dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.477786 s, 2.2 GB/s
```

Second server:

```
dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.603588 s, 1.8 GB/s
```

**Comment by trapexit** [comment]
Are the kernels / OSes the same?

Can you benchmark just rclone? And then the underlying nvme drive through mergerfs? rclone mounts are FUSE too and you're adding massive overhead to a single request. Clearly there is something different between the two machines if in nullrw mode it's got a ~20 percent difference.

**Comment by Prosecutor** [comment]
@trapexit Yes, the same xanmod. The same OS. There is only 1 difference, amount of drives.

Sure, here is the rclone benchmark. 

Firs server: 

```
dd if=/dev/zero of=/home/marshy/rclone/gdrive/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 35.0605 s, 30.6 MB/s
```

Second one:

```
dd if=/dev/zero of=/home/marshy/rclone/gdrive/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 42.8261 s, 25.1 MB/s
```

With the same configuration on 3rd server( i9-9900K / 64 GB RAM / 2x1TB NVME) I got worse result

```
dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1058013184 bytes (1.1 GB, 1009 MiB) copied, 32 s, 33.0 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 32.5129 s, 33.0 MB/s
```

**Comment by trapexit** [comment]
I'm missing something. What was the setup for the original numbers? Those are higher than the rclone ones.

Can you just list out the average speeds with the mount setup (rclone only, nvme only, mergerfs + nvme, mergerfs + rclone + nvme, mergerfs nullrw, etc.)

**Comment by Prosecutor** [comment]
@trapexit 

First server:

Rclone only:
```
dd if=/dev/zero of=/home/user/rclone/gdrive/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 35.0605 s, 30.6 MB/s
```

NVMe Only:
```
dd if=/dev/zero of=/home/user/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
916455424 bytes (916 MB, 874 MiB) copied, 3 s, 305 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 3.51389 s, 306 MB/s
```

MergerFS+Rclone:
```
# dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1042284544 bytes (1.0 GB, 994 MiB) copied, 17 s, 61.3 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.5234 s, 61.3 MB/s
```

MergerFS Nullrw:
```
dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.477786 s, 2.2 GB/s
```

Second server:
Rclone only:
```
dd if=/dev/zero of=/home/user/rclone/gdrive/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 42.8261 s, 25.1 MB/s
```

NVMe Only:
```
dd if=/dev/zero of=/home/user/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.92746 s, 1.2 GB/s
```

MergerFS+Rclone:
```
dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1038090240 bytes (1.0 GB, 990 MiB) copied, 2 s, 519 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.08218 s, 516 MB/s

```

MergerFS Nullrw:
```
dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.603588 s, 1.8 GB/s
```

Maybe i should execute another dd test?

**Comment by trapexit** [comment]
There is no way you're sending to gdrive at 516MB/s.

**Comment by Prosecutor** [comment]
@trapexit "gmedia" is a MergerFS folder that is launched under rclone.

My mount is like Rclone(gdrive) => Then MergerFS makes mount of it(gmedia) => cache folder, its a clone. So when you add something to gmedia folder it's added in cache folder. And over the night files are transferred to the gdrive.

**Comment by trapexit** [comment]
> "gmedia" is a MergerFS folder that is "launched " under rclone(underlying mount).

You mean over rclone?

I'm still not following. If you're using rclone caching why would rclone alone be so much slower?

**Comment by Prosecutor** [comment]
@trapexit Yeah. 

Because when you are transferring files directly to the gdrive(via rclone)(this was done with dd command), you won't reach more than ~ 35 MB/s per file.

**Comment by trapexit** [comment]
You have "rclone" benchmarks and "mergerfs + rclone" benchmarks. That should mean that the only difference between the two is that mergerfs has been mounted on top of the existing rclone mount. Is that the case or not. I don't see how you can have such drastically different values between rclone and rclone + mergerfs between the two systems if everything is setup the same.

**Comment by Prosecutor** [comment]
@trapexit Me either.

I have one more server with i9-9900K / 64 GB RAM / 2x1 TB NVMe SSD and there values are worse than 1rs server. 

```
dd if=/dev/zero of=/home/user/rclone/gmedia/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1058013184 bytes (1.1 GB, 1009 MiB) copied, 32 s, 33.0 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 32.5129 s, 33.0 MB/s
```

**Comment by trapexit** [comment]
rclone1: 30.6
rclone2: 25.1
mergerfs+rclone1: 61.3 <= why faster than just rclone1?
mergerfs+rclone2: 516 <= ??? Over 10x the speed? That isn't possible.

**Comment by Prosecutor** [comment]
@trapexit Because MergerFS is like a "local mount", it doesn't copy files directly to the GDrive. Rclone mount does.

**Comment by trapexit** [comment]
I don't understand. Is, or is not, mergerfs + rclone just mergerfs on top of the rclone mount?

**Comment by trapexit** [comment]
I don't know what those directories refer to. Please. Can we just do things one step at a time and minimize complexity. 

rclone mount = just rclone mount as you normally use it
mergerfs + rclone = just mergerfs on top of that rclone mount. Not anything else. Just one path.
mergerfs + local disk = just mergerfs on top of local disk. One path. 

What are the benchmarks for those alone.

**Comment by Prosecutor** [comment]
@trapexit 

Rclone mount 1st
```
dd if=/dev/zero of=/home/marshy/rclone/gdrive/benchmark bs=1G count=1 status=progress
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 38.2609 s, 28.1 MB/s
```

Rclone mount 2nd
```
dd if=/dev/zero of=/home/marshy/rclone/gdrive/benchmark bs=1G count=1 status=progress
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 39.1488 s, 27.4 MB/s
```

mergerfs + rclone 1st
```
dd if=/dev/zero of=/home/marshy/rclone/gmedia/benchmark bs=1G count=1 status=progress
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.96781 s, 1.1 GB/s
```


mergerfs + rclone 2nd
```
dd if=/dev/zero of=/home/marshy/rclone/gmedia/benchmark bs=1G count=1 status=progress
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.812204 s, 1.3 GB/s
```


mergerfs + local disk 1st
Mount command: **mergerfs -o dropcacheonclose=true,threads=12,async_read=false,use_ino,cache.files=auto-full,allow_other,func.getattr=newest,category.action=all,category.create=ff /opt/marshy/ /home/marshy/test/**

```
dd if=/dev/zero of=/home/marshy/test/benchmark bs=1G count=1 status=progress
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.980257 s, 1.1 GB/s
```

```
dd if=/dev/zero of=/home/marshy/test/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1041235968 bytes (1.0 GB, 993 MiB) copied, 17 s, 61.2 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.5411 s, 61.2 MB/s

```


mergerfs + local disk 2nd
```
dd if=/dev/zero of=/home/marshy/test/benchmark bs=1G count=1 status=progress
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1 s, 1.1 GB/s
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.02102 s, 1.1 GB/s
```

```
dd if=/dev/zero of=/home/marshy/test/benchmark ibs=1M obs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
945815552 bytes (946 MB, 902 MiB) copied, 2 s, 472 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.28046 s, 471 MB/s
```

**Comment by trapexit** [comment]
You used non sync reads / writes on a number of those tests. Those aren't useful. Writing to caches is naturally going to result in very different values.

Regardless, have you followed the suggestions in the docs regarding performance to compare?

**Comment by Prosecutor** [comment]
@trapexit So witch test comman i should execute then?

Of course. async_read=false only improved the speed.

**Comment by trapexit** [comment]
dd with sync enabled as described in the docs: https://github.com/trapexit/mergerfs#nullrw


Fool with thing that are relevant to the situation. You're writing / reading data. So splice_*, cache.files, maybe security_capability / xattr, posix_acl, async_read.

**Comment by Prosecutor** [comment]
Mount command:  mergerfs -o nullrw=true,dropcacheonclose=true,threads=12,async_read=false,use_ino,cache.files=auto-full,allow_other,func.getattr=newest,category.action=all,category.create=ff /opt/marshy/ /home/marshy/test/

(Added nullrw=true)
```
dd if=/dev/zero of=/home/marshy/rclone/gmedia/benchmark bs=1G count=1 status=progress                                                         1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.970442 s, 1.1 GB/s
```

The  splice_*/no_splice_*, security_capability / xattr, posix_acl doesn't make any changes in performance.  async_read and cache already exists in command by default.

**Comment by trapexit** [comment]
1) As I said... that `dd` usage is not valid. Please use the command described in the docs

`dd if=/file/to/read of=/dev/null bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress`
`dd if=/dev/zero of=/file/to/write bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress`

2) What did cache.files=off or async_read=true do?

**Comment by trapexit** [comment]
Also. These tests must be run on the real devices. nullrw is only for determining maximum values.

**Comment by Prosecutor** [comment]
mergerfs + local disk

Mount: mergerfs -o dropcacheonclose=true,threads=12,async_read=false,use_ino,cache.files=auto-full,allow_other,func.getattr=newest,category.action=all,category.create=ff /opt/marshy/ /home/marshy/test/

```
dd if=/dev/zero of=/home/marshy/test/benchmark bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1044381696 bytes (1.0 GB, 996 MiB) copied, 17 s, 61.4 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.497 s, 61.4 MB/s
```

```
dd if=/home/marshy/test/benchmark of=/dev/null bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
dd: fsync failed for '/dev/null': Invalid argument
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.598039 s, 1.8 GB/s
```

Mount: mergerfs -o threads=12,async_read=false,use_ino,cache.files=off,allow_other,func.getattr=newest,category.action=all,category.create=ff /opt/marshy/ /home/marshy/test/
(cache.files=off)

```
dd if=/dev/zero of=/home/marshy/test/benchmark bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1062207488 bytes (1.1 GB, 1013 MiB) copied, 17 s, 62.5 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.1943 s, 62.4 MB/s
```

```
dd if=/home/marshy/test/benchmark of=/dev/null bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
dd: fsync failed for '/dev/null': Invalid argument
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.400977 s, 2.7 GB/s
```

Mount: mergerfs -o threads=12,async_read=true,use_ino,cache.files=off,allow_other,func.getattr=newest,category.action=all,category.create=ff /opt/marshy/ /home/marshy/test/
(async_read=true and cache.files=off)

```
dd if=/dev/zero of=/home/marshy/test/benchmark bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1069547520 bytes (1.1 GB, 1020 MiB) copied, 17 s, 62.9 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.0673 s, 62.9 MB/s
```

```
dd if=/home/marshy/test/benchmark of=/dev/null bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
dd: fsync failed for '/dev/null': Invalid argument
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.336399 s, 3.2 GB/s
```

Mount:  mergerfs -o dropcacheonclose=true,threads=12,async_read=true,use_ino,cache.files=auto-full,allow_other,func.getattr=newest,category.action=all,category.create=ff /opt/marshy/ /home/marshy/test/

```
dd if=/dev/zero of=/home/marshy/test/benchmark bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
1056964608 bytes (1.1 GB, 1008 MiB) copied, 17 s, 62.1 MB/s
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 17.2875 s, 62.1 MB/s
```

```
dd if=/home/marshy/test/benchmark of=/dev/null bs=1M count=1024 iflag=dsync,nocache oflag=dsync,nocache conv=fdatasync status=progress
dd: fsync failed for '/dev/null': Invalid argument
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.318161 s, 3.4 GB/s
```

**Comment by trapexit** [comment]
It'd be easier to read if you summarized the results.

Either way... the comparison should be done on one style (read or write) with one setup across the machines. We want to find differences. Where things aren't different don't help narrowing it down.

**Comment by Prosecutor** [comment]
Okay.

Mount Command: threads=12,async_read=false,use_ino,cache.files=off,allow_other,func.getattr=newest,category.action=all,category.create=ff

First server:
Read: 2.8 GB/s
Write: 62.6 MB/s

Second server:
Read: 3.2 GB/s
Write: 567 MB/s

**Comment by Prosecutor** [comment]
mergerfs + local disk.

Nope. General difference is amount of drives and that 2x960 GB NVMe SSD's are Datacenter Edition drives.


Let me check on i9-9900K

**Comment by trapexit** [comment]
mergerfs isn't doing anything different between these systems if the OS, filesystems, and settings are the same. It doesn't change settings automatically outside what it says in the docs. So the only things of interest are where they differ. If the drives and controllers are different then we need to remove them from the equation to see if they are the catalyst or cause. Using a RAM disk will let us know if it's the drives or perhaps RAM or CPU somehow.

**Comment by Prosecutor** [comment]
So checked on i9-9900K / 64GB RAM / 2 x 1 TB NVMe SSD.

Mount command: threads=12,async_read=false,use_ino,cache.files=off,allow_other,func.getattr=newest,category.action=all,category.create=ff

mergerfs + local disk.

Read: 2.9 GB/s
Write: 32.6 MB/s

Unfortunately i don't know how to make/mount RAM disk. Maybe you are talking about SWAP?

**Comment by trapexit** [comment]
No. I'm talking about a RAM disk. tmpfs.

https://wiki.archlinux.org/index.php/Tmpfs

`sudo mount -t tmpfs -o size=2G tmpfs /tmp/tmpfs`

**Comment by Prosecutor** [comment]
Just clarify, i sould make this mount then make MergerFS mount over it?

**Comment by trapexit** [comment]
Yes. Just like other tests.

**Comment by Prosecutor** [comment]
Mount command: threads=12,async_read=false,use_ino,cache.files=off,allow_other,func.getattr=newest,category.action=all,category.create=ff

First Server:
Read: 2.6 GB/s
Write: 2.1 GB/s

Second Server:
Read: 2.9 GB/s
Write: 3.2 GB/s

i9-9900K Server:
Read: 2.8 GB/s
Write: 2.8 GB/s

**Comment by trapexit** [comment]
OK... so it appears it has something to do with the drives?

**Comment by Prosecutor** [comment]
Likely they are new, server is just some days old. You mean they are broken?

**Comment by trapexit** [comment]
No. I mean that if your benchmarks show mergerfs working fine with a RAM based disk and performance being odd between systems once you use the drives... then seemingly there is something about that interaction. I have no idea what that is... but that's where it is. mergerfs isn't acting any different between the two.

**Comment by trapexit** [comment]
Without being able to replicate this I really can't help. I can only ask you to continue to poke around and see what's different.

**Comment by Prosecutor** [comment]
CPU and type of SSD. That's all.
Ryzen has default version of SSD
2288G has Datacenter SSD's

**Comment by trapexit** [comment]
It's not that simple. The drivers are obviously different. Are the NVMe devices connected directly to the CPU or a bridge chip? There is a lot different.

**Comment by Prosecutor** [comment]
Understood you now. Unfortunately, I can't tell you how. DC won't tell me that type of info.

**Comment by trapexit** [comment]
DC? You can find that out by looking at the PCI device tree using lspci and similar tooling but honestly it won't mean anything to me. The only way to further test is to use the same drive in different systems.

**Comment by trapexit** [comment]
I doubt it'll make a difference but *just in case*... it was suggested to me for Ryzen systems to ensure the BIOS is up to date.

**Comment by trapexit** [comment]
Any update?
