### ISSUE TITLE
Index at Readme.md

### ISSUE THREAD

**Issue by cpdef** [trapexit/mergerfs#698]
General description
===================
Please add an index to the Readme.md,
then it would be much easier to find the different sections fast.

Expected behavior
=================
To find the relevant section after 20 seconds

Actual behavior
===============
I need to scroll endless down

Sorry for that not program relevant request, i just had problems searching in the Readme

**Comment by trapexit** [comment]
Index in what sense? Ultimately it's just a markdown file (a text file that github interprets in certain ways) and it's not possible to provide a platform independent index section. At most I can link to the public URL but that'd not really work as the man file.

Even then... adding an index for just heading 1 would be a bit long.

- Description
- Features
- How it works
- Options
- Functions / Policies / Categories 
- Building
- Runtime
- Upgrade
- Tooling
- Caching
- Performance
- Benchmarking
- Tips / Notes
- Known Issues / Bugs
- FAQ
- Support
- Links

I'm happy to try to make things easier to manage but github markdown is limited in functionality.

**Comment by cpdef** [comment]
>  At most I can link to the public URL but that'd not really work as the man file.

you could make relative links like `[Features](#FEATURES)`



> Even then... adding an index for just heading 1 would be a bit long.

hmm what i think is, that this is not so long for an index ...

But that should be only a suggestion, if its not possible to solve it, its not a big problem for me. 
Maybe it would be even enough to add such a list, without adding Links, so that one know how far he has to scroll.

**Comment by trapexit** [comment]
> hmm what i think is, that this is not so long for an index

Seems to take a lot of vertical space as it takes up almost half the height on my screen. Those expandable indexes some wikis use would be nice but I don't think that's possible. Breaking up the docs would make it even harder to find stuff IMO. Maybe if I split them horizontally in a table.

I'll play with some ideas.

**Comment by muhlinux** [comment]
> I'll play with some ideas.

html is valid in markdown

<details>
<summary>TOC</summary>
<ul>
<li>Description</li>
<li>Features</li>
<li>How it works</li>
<li>Options</li>
<li>Functions / Policies / Categories</li>
<li>Building</li>
<li>Runtime</li>
<li>Upgrade</li>
<li>Tooling</li>
<li>Caching</li>
<li>Performance</li>
<li>Benchmarking</li>
<li>Tips / Notes</li>
<li>Known Issues / Bugs</li>
<li>FAQ</li>
<li>Support</li>
<li>Links</li>
</ul>

</details>

**Comment by trapexit** [comment]
Yes, but HTML isn't attractive without web rendering and will break the man page.

**Comment by trapexit** [comment]
The current setup is 1 file that serves 3 purposes. 

1) The readme file in the source
2) The github readme / docs
3) the man page

I'm not aware of an easy way to have a decent looking index that will work in all three usecases. It'll probably require creating different files or something.
