### ISSUE TITLE
General question - file larger than single drive

### ISSUE THREAD

**Issue by smathev** [trapexit/mergerfs#702]
Hi.

First off, I'm a new user of mergerfs, and am already really liking it. It's perfect for my use case of many large files, and lot's of randomly sized disks. 

I do however have a question - suppose that I have a two harddrives, and each had 2GB free, and I was trying to copy a 3GB file to the collected mergerFS directory. I believe the directory would have 4GB of free space, but it wouldn't be on one drive.

Would mergerFS then shuffle data around to accomodate the new file, would mergerFS stripe it or simply report that there was no space left on the mergerFS directory?

Forgive my ignorance, and it might be a really stupid question. 

I currently run mfs on my mergerFS directory, and don't know if any other policy would change it's behavior concerning my quesiton.

Lastly - thank you very much for your hard work. Any question I see on reddit or elsewhere there is usually a reply from you, it's really cool to see the level of commitment and care you exhibit over this project!

Thanks in advance.

**Comment by trapexit** [comment]
> Would mergerFS then shuffle data around to accomodate the new file, would mergerFS stripe it or simply report that there was no space left on the mergerFS directory?

https://github.com/trapexit/mergerfs#how-it-works

It will report no space. It does not stripe. It's just a union. Having many small drives isn't the use case it's designed for as that's not a common problem.

**Comment by smathev** [comment]
Hi - thanks for taking your time to reply - it was what I figured, and it makes sense. I notice you've developed a tool to rebalance drives, would a tool that made sure reshuffled to fill every drive, so the "last drive" was mostly free make sense? and is it even possible to create such a tool?
IE. in my quesiton above move 2GB of files from one of the two drives, to make 4GB available on the other drive, and make space for the 3GB file incoming.

Sorry to reopen.

**Comment by trapexit** [comment]
Sure, it's possible. That's really not a thing most people want or need hence there has been no reason to create it. Making the drives less balanced is generally not something you want. The problem is it's a bin packing problem and if you're dealing with a small amount of space you'll need to carefully figure out what to transfer. Unless this is happening often your best bet is to manually move files and consider a different policy.

**Comment by smathev** [comment]
Hi.
Thank you for clarifying and helping me understand :) 

You made me google the bin packing problem to understand the reference, and I see what you mean - it gets quite complex, fairly quickly. It isn't a current problem, I was merely seeking to educate myself. I'm very grateful for mergerFS as is - it solves my needs! I just wanted to know if there was a way to auto-balance towards the "bin packing problem". I'll just manually move files, unless I feel like tackling the problem myself using poorly thought out bash-scripts combined with trial and error :)

Thank you once again for your prompt response, and the awesome software you've developed!
