### ISSUE TITLE
Weird behavior with category.create=eplus

### ISSUE THREAD

**Issue by LT11222** [trapexit/mergerfs#704]
General description
===================

I have a set of 5 drives pooled together, 4x4TB and 1x10TB. I have 3 overlapping pools active, at 
```
/mnt/drive{1..5}/
/mnt/drive{1..5}/backup/ 
/mnt/drive{1..5}/media/ 
```

Here's a snippet of both my fstab and `df -h` output.

```
/mnt/drive1:/mnt/drive2:/mnt/drive3:/mnt/drive4:/mnt/drive5 /mnt/drivePool                                        fuse.mergerfs defaults,allow_other,use_ino,direct_io,hard_remove,func.getattr=newest,category.create=eplus,fsname=drivePool 0 0
/mnt/drive1/media:/mnt/drive2/media:/mnt/drive3/media:/mnt/drive4/media:/mnt/drive5/media /mnt/mediaPool          fuse.mergerfs defaults,allow_other,use_ino,direct_io,hard_remove,func.getattr=newest,category.create=eplus,fsname=mediaPool 0 0
/mnt/drive1/backup:/mnt/drive2/backup:/mnt/drive3/backup:/mnt/drive4/backup:/mnt/drive5/backup /mnt/backupPool    fuse.mergerfs defaults,allow_other,use_ino,direct_io,hard_remove,func.getattr=newest,category.create=eplus,fsname=backupPool 0 0
```

It looks like I might be using some deprecated options, so maybe something there is causing issues?

```
Filesystem                  Size  Used Avail Use% Mounted on
backupPool                   24T  5.3T   17T  24% /mnt/backupPool
/dev/sdb1                   3.6T  1.4T  2.1T  39% /mnt/drive1
/dev/sde1                   3.6T  1.4T  2.1T  41% /mnt/drive2
/dev/sdf1                   3.6T  1.1T  2.4T  30% /mnt/drive3
/dev/sdg1                   3.6T  906G  2.6T  27% /mnt/drive4
/dev/sdc1                   9.1T  703G  7.9T   9% /mnt/drive5
/dev/sdd1                   9.1T  2.7T  6.0T  31% /mnt/drive6
drivePool                    24T  5.3T   17T  24% /mnt/drivePool
mediaPool                    24T  5.3T   17T  24% /mnt/mediaPool
```

I have `category.create=eplus` set for all pools.

When I create a dummy file, I expect the file to be written to the drive with the least used space (`/mnt/drive5`) as given by the `eplus` directive, but what I experience is that the file gets written to the 2nd least filled drive (`/mnt/drive4`).

Expected behavior
=================

When I create a dummy file via `fallocate -l 100G /mnt/drivePool/test.dat` I expect a 100G file to be written to `/mnt/drive5/test.dat` since it has the least used space.

Actual behavior
===============

When I create the dummy file it instead writes to `/mnt/drive4`. If I create two files in a row, 

```
fallocate -l 100G /mnt/drivePool/test.dat
fallocate -l 100G /mnt/drivePool/test2.dat
```

I get `/mnt/drive4/test.dat` and `/mnt/drive5/test2.dat`.
What I would expect is to get `/mnt/drive5/test.dat` and `/mnt/drive5/test2.dat` since `/mnt/drive5` has more than `200G` less space used than `/mnt/drive4`.

I have tested this behavior both at the root of the pool as well as various subdirectories where the relative path exists on all drives. The result is the same each time.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: ```mergerfs version: 2.28.1-8-g4204c80
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.29```
* [ ] mergerfs settings:  see above
* [ ] Linux version: `Linux NAME 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* [ ] strace of mergerfs while app tried to do it's thing: I have the strace but will hold off on posting it to keep the post short, in case my issue is something simple like user error

**Comment by trapexit** [comment]
Have you accounted for path preservation?

**Comment by LT11222** [comment]
Yeah, I've duplicated the folder structure on the drives, but in my example I used the root folder of the drives, so there shouldn't be any issues with path preservation right?

I've tried to create the test files both in the root folder of the drives as well as in mirrored subdirectories and I still seem to be running into the same issue.

**Comment by trapexit** [comment]
Without knowing every single branch/directory's details I really can't comment. The policies work as described in the docs so your best bet is to check those things it checks. Change to `lus` to ensure path preservation isn't part of the issue, etc.

**Comment by LT11222** [comment]
Okay, I'll try changing to `lus` and see if the issue persists. I did check everything using `mergerfs.ctl` and `mergerfs.fsck` and those didn't seem to raise any red flags.

**Comment by LT11222** [comment]
I switched to `lus` via `mergerfs.ctl` and confirmed by reading back with `mergerfs.ctl -m /mnt/drivePool list values` and it still shows the same behavior. 

Tried a reboot as well, no dice.

I'm wondering if there's some discrepancy between how mergerfs is getting the drive space stats and how `df` is?

I threw a bunch of temp files on the drives and it seems like my `/mnt/drive5` is getting files distributed to it correctly, but for some reason it's lagging behind by about 300 gigs. So it doesn't get considered as the least filled drive until the other drives are more than 300 gigabytes more full.

I guess it might be okay to leave things as they are, but I'm worried something is corrupted or set incorrectly which might lead to issues down the line.

**Comment by trapexit** [comment]
Rebooting makes no difference to behavior. The runtime changes are immediate.

What filesystem are you using? The [space used is just calculated](https://github.com/trapexit/mergerfs/blob/master/src/statvfs_util.hpp#L47) by subtracting the number of blocks by the number available for unprivileged users and multiplying by the fragment size. According to[ df](https://github.com/coreutils/coreutils/blob/master/src/df.c#L954) it is based on available to root. Maybe you've reserved different percentages for root?

**Comment by LT11222** [comment]
Okay, looks like it's what you thought, `df` uses the total space available to root. You use `st.f_blocks - st.f_bavail` whereas `df` uses the equivalent of `st.f_blocks - st.f_bfree`.

I threw together a quick python script and the `st.f_bfree` version matched with the numbers from `df -B1`.

Since the used space calculation is just the inverse of the free space, the `df` version ends up thinking there's an extra 500G of headroom on the drive, which offsets the calculated used space by -500G. Since the smaller drives are affected the same way with a -200G offset, I end up with the 300G discrepancy that I see in the `df` stats.

It's probably still gonna bug me that it shows up that way but at least I know why now.

**Comment by trapexit** [comment]
I could create an alternative policy. I can't recall exactly why I chose that but I suspect it's because unprivileged access is generally more accurate to real life. I suppose I could calculate based on incoming requester (bavail for non root and bfree for root) but that might be more confusing. Also... I think that is a ext4 thing. I don't think other filesystems do that.

**Comment by trapexit** [comment]
If you don't care... you can change the reserved space for root.

`sudo tune2fs -m 0 /dev/DEVICE`

**Comment by LT11222** [comment]
I might do that, since they're data drives not system drives, and 5% is a decent amount of space to reclaim. 

Thanks for you help.
