### ISSUE TITLE
Do you have thoughts on implementing a "high water" allocation method?

### ISSUE THREAD

**Issue by thejinx0r** [trapexit/mergerfs#709]
Do you have thoughts on implementing an allocation method similar to what unraid has:
https://wiki.unraid.net/Un-Official_UnRAID_Manual#High_Water

> The high water allocation method attempts to step fill each disk so at the end of each step there is an equal free space left on each disk. The idea is to progressively fill each disk but not constantly go back and forth between disks each time new data is written to the array. Most times, only a single disk will be needed when writing a series of files to the array so the array will only spin-up the needed disk. The high water level is initially set equal to one-half of the size of the largest disk. A new high water level is again set to one-half of the previous high level once all the disks have less free space than the current high water level.

The use case for me is that I have a lot of "small" files that are part of a larger dataset that I want to keep together on the same drive as much as possible, but that it can write to another drive when the fill line is reached. 
So reading through this: #634 

The two main advantages I would get is this:
1) When using mergerfs with multiple disks + snapraid, in case of a drive failure, I've only lost one drive worth of datasets, and not much more because datasets on other drives that did not depend on the missing drive (on average).
2) When accessing a dataset, I would only need to spin up one disk (on average) instead of my pool of drives.

For implementing this over #634 is that completely filling up a filesystem is not generally advised. Also, in a NAS, being accessed by multiple people, it, will spread (in theory) the data access across more drives, improving performances. Without this Feature Request, accessing a bunch of small files by multiple people across multiple drives just looks like a bunch of random IO.

**Comment by trapexit** [comment]
re 1. I'm not sure I follow. The description has nothing to do with "data sets." It is writing to 1 drive at a time until it meets some threshold then moving to the other. When all drives are above the threshold it changes the threshold. This isn't a difference in kind. Just a difference in degree. "sets" will be "split" once it hits the watermark. mfs with a threshold.

re 2. It is simply not accurate in practice. Software rarely requests data directly without also scanning the directory or doing something else which would force mergerfs to query all or at least some drives.

re better performance: it won't spread it across more drives. The strategy is explicitly limiting the spread by making "mfs" sticky to some threshold. All data written upto that threshold is on the same drive. If you want data spread out you would use random. Without knowing the access patterns it's probably the best you can do wrt spreading out data for performance. 

I don't understand your last sentence. It will always be "random io". The argument is where that IO is directed. With this strategy if they are accessing data that was recently written it is more likely they'd be directed to the same drive and performance therefore will suffer.

If you wanted to try to keep data colocated why not use a path preserving create policy? You can pair it with a non-path preserving mkdir to make it spread files around. An alternative could be a hash based algo that picks a drive based on path name or something though it would effectively be the same outcome.

**Comment by trapexit** [comment]
Can you describe your use case rather than a solution? It just complicates the discussion to put the cart before the horse.

**Comment by thejinx0r** [comment]
> If you wanted to try to keep data colocated why not use a path preserving create policy? You can pair it with a non-path preserving mkdir to make it spread files around. 

I think this will work. I'll have to try it.

**Comment by trapexit** [comment]
If you store lots of files in a single directory you may have issues as it would fill one drive unless you create that directory on other drives but if you keep relatively small amount of data per directory it will work fine.

**Comment by thejinx0r** [comment]
It does what I want it to do.
Thanks for the suggestion!

**Comment by trapexit** [comment]
I think a lot of people miss that you can do this kind of thing. It's mentioned in the docs as of a month or two ago but you have to be looking for it of course.

**Comment by thejinx0r** [comment]
I knew that you could modify it on a per function basis. I didn't think of applying it to the mkdir.
I actually used it to fix the mtime folders with getattr for nfs exports.
