### ISSUE TITLE
Above Average CPU Usage by mergerfs

### ISSUE THREAD

**Issue by athenawisdoms** [trapexit/mergerfs#712]
General description
===================

My system is dedicated to running a PostgreSQL 11.2  database server on Ubuntu 18.04.3. `mergerfs` is used to pool 6 differently sized drives (half of a 2TB drive, one 2TB drive and one RAID-10 array) together to be mounted at `/mnt/storage`. PostgreSQL database has been configured to use `/mnt/storage` for its data directory.

Is it normal for `mergerfs` to use so much CPU time? If not, how can we figure out whats wrong?

Thanks!

Expected behavior
=================

`mergerfs` should not be consuming too much CPU time. I expect it to be in the single digits.

Actual behavior
===============

When looking at `htop`, I notice that there is a constant non-trivial amount of CPU usage by `mergerfs`.

![image](https://user-images.githubusercontent.com/6615285/74566423-6b4e8d00-4f41-11ea-8b9e-4f5a79963215.png)

**Precise** steps to reproduce the behavior
===========================================

## Step 1: Set up RAID-10 array consisting of 4 drives

```
sudo mdadm --create --verbose /dev/md0 --level=10 --raid-devices=4 /dev/sd[c-f]
sudo mkfs.ext4 -F /dev/md0
sudo mkdir -p /mnt/md0
sudo mount /dev/md0 /mnt/md0

sudo mdadm --detail --scan | sudo tee -a /etc/mdadm/mdadm.conf
sudo update-initramfs -u
echo '/dev/md0 /mnt/md0 ext4 defaults,nofail,discard 0 0' | sudo tee -a /etc/fstab
```

## Step 2: Set up 2TB drive

```
sudo mkfs.ext4 -F /dev/sdb
sudo mkdir -p /mnt/sdb
sudo mount /dev/sdb /mnt/sdb
```

## Step 3:  Set up `mergerfs`

```
sudo apt install mergerfs fuse -y
sudo mkdir /mnt/storage
sudo mkdir /mnt/sda
sudo mergerfs -o defaults,allow_other,use_ino,fsname=mergerFS /mnt/sda:/mnt/sdb:/mnt/md0 /mnt/storage/
```

## Step 4: Install PostgreSQL

Create `docker-compose.yml` to start a PostgreSQL 11.2 container:

```
version: '3.3'
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg11
        ports:
        - 5432:5432
        volumes:
          - /mnt/storage/timescaledb:/var/lib/postgresql/data
```

then start the Docker container

```
docker-compose up -d    
```

## Step 4: Add some database load

Run a database migration, for example.

## Step 5: View the CPU usage of `mergerfs`

In the bash terminal, run

    htop

System information
==================

## Software

- Ubuntu 18.04.3
- PostgreSQL 11.2
- Docker version 19.03.5, build 633a0ea838

## Hardware

- AMD Opteron(tm) Processor 1385
- 8GB DDR3
- 6 drives
    - 2 TB (OS, 1  of the 2TB is used in `mergerfs`)
    - 2 TB
    - 4 x 1TB (RAID-10 array)

## `mergerfs -V`

```
mergerfs version: 2.21.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

## `cat /etc/fstab`

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda5 during installation
UUID=06587f21-2002-4dc9-a25f-1836d44a9f0e /               ext4    errors=remount-ro 0       1
# /boot was on /dev/sda1 during installation
UUID=0e84510f-5dd9-4281-a997-12494839908d /boot           ext2    defaults        0       2
/swapfile                                 none            swap    sw              0       0
/dev/fd0        /media/floppy0  auto    rw,user,noauto,exec,utf8 0       0
/swapfile none swap sw 0 0
/swapfile none swap sw 0 0
/dev/md0 /mnt/md0 ext4 defaults,nofail,discard 0 0
```

## `name -a`

```
Linux my-db 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## `df-h`

```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           805M  1.1M  804M   1% /run
/dev/sda5       1.8T   57G  1.7T   4% /
tmpfs           4.0G     0  4.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/sda1       961M  159M  753M  18% /boot
tmpfs           805M     0  805M   0% /run/user/1001
/dev/md0        1.8T   77M  1.7T   1% /mnt/md0
/dev/sdb        1.8T  516G  1.2T  30% /mnt/sdb
mergerFS        5.4T  573G  4.6T  11% /mnt/storage
```

## `sudo strace -f -p 751 -o /tmp/mergerfs.strace.txt`

```
strace: Process 751 attached with 12 threads
strace: Process 15494 attached
strace: Process 15495 attached
strace: Process 15498 attached
strace: Process 15499 attached
strace: Process 15502 attached
strace: Process 15503 attached
strace: Process 15504 attached
strace: Process 15505 attached
strace: Process 15508 attached
strace: Process 15511 attached
strace: Process 15516 attached
strace: Process 15517 attached
strace: Process 15518 attached
strace: Process 15519 attached
strace: Process 15520 attached
strace: Process 15521 attached
strace: Process 15522 attached
strace: Process 15523 attached
strace: Process 15526 attached
strace: Process 15527 attached
strace: Process 15528 attached
strace: Process 15531 attached
strace: Process 15534 attached
strace: Process 15535 attached
strace: Process 15536 attached
strace: Process 15537 attached
strace: Process 15538 attached
strace: Process 15539 attached
```

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#what-should-mergerfs-not-be-used-for

You should not be using a database through mergerfs.

Regardless, those are perfectly reasonable numbers for a FUSE filesystem. Other filesystems can use CPU too but if they are in the kernel you don't see their usage as they aren't userland processes.

**Comment by trapexit** [comment]
Also... you're using a version that is nearly 3 years old.

**Comment by wessel145** [comment]
@trapexit the version in the ubuntu repositories is still 2.21. is it possible to push the most recent version to the repo?

**Comment by trapexit** [comment]
No. I don't control Ubuntu's repo. They aren't a rolling release distro. They will never have up to date software.

If you want to use newer versions of anything you have to install it yourself. That's why I provide packages for major distros. Look on the release page.
