### ISSUE TITLE
all files started going onto same disk until filled is their a way to blacklist?

### ISSUE THREAD

**Issue by MasterCATZ** [trapexit/mergerfs#713]
General description
===================
Since this year all data seems to be going onto the same disk 
is it possible to allow RW operation but stop all new files going to a disk ? 
ie) a mergerfs blacklist option ? which will still merge the disk but not use it for new files

 for some reason all files just started piling onto only SRD5NA1B4 until 0 bytes
 ( just had a 260gig file lock up its btrfs ) 
and all other disk 2/3 full 

I am still unsure if this was from snapshots being created of the 260gig file while being downloaded or not , but looking through all the other disks they have not shown any new files being written to them for the last month 

after moving files around deleting snapshots and running 
sudo btrfs fi balance /mnt/SnapRaidArray/SRD5NA1B4
/dev/mapper/SRD5NA1B4-part1    2.8T  2.1T  705G  75% /mnt/SnapRaidArray/SRD5NA1B4

Expected behavior
=================
files go to disk with most free space 

Actual behavior
===============
Files seem to be going onto the last disk that was re-synced using snapraid

**Precise** steps to reproduce the behavior
===========================================
I run btrfs with snapshots and snapraid for parity 
I replaced disk5 beginning of year 
and this now seems to be the only disk mergerfs is writing new files too 
all disks are mounted rw 

swapped out dead disk 
changed multipath  wwid    alias   SRD5NA1B4
snapraid fix -d d5

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
/dev/mapper/SRD4NA1B3-part1 /mnt/SnapRaidArray/SRD4NA1B3 btrfs x-gvfs-hide,rw,users,nosuid,nodev,nofail,noatime 0 0
/dev/mapper/SRD5NA1B4-part1 /mnt/SnapRaidArray/SRD5NA1B4 btrfs x-gvfs-hide,rw,users,nosuid,nodev,nofail,noatime 0 0
/dev/mapper/SRD6NA1B5-part1 /mnt/SnapRaidArray/SRD6NA1B5 btrfs x-gvfs-hide,rw,users,nosuid,nodev,nofail,noatime 0 0

/mnt/SnapRaidArray/* /SnapRaidArray fuse.mergerfs comment=x-gvfs-show,rw,defaults,allow_other,category.create=mfs,moveonenospc=true,minfreespace=50G,fsname=SnapRaidArray 0 0

* [ ] Linux version: `uname -a`
Linux aio 5.4.13-050413-generic #202001171431 SMP Fri Jan 17 19:34:58 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* [ ] Versions of any additional software being used

* [ ] List of drives, filesystems, & sizes: `df -h`
/dev/mapper/SRD19NA1B18-part1  2.8T  1.9T  897G  68% /mnt/SnapRaidArray/SRD19NA1B18
/dev/mapper/SRD4NA1B3-part1    2.8T  1.9T  909G  68% /mnt/SnapRaidArray/SRD4NA1B3
/dev/mapper/SRD3NA1B2-part1    2.8T  1.9T  892G  69% /mnt/SnapRaidArray/SRD3NA1B2
/dev/mapper/SRD2NA1B1-part1    2.8T  1.9T  908G  68% /mnt/SnapRaidArray/SRD2NA1B1
/dev/mapper/SRP1NA1B20-part1   2.7T  2.2T  508G  82% /mnt/SnapRaidArray_P/SRP1NA1B20
/dev/mapper/SRP3NA1B22-part1   2.7T  2.2T  508G  82% /mnt/SnapRaidArray_P/SRP3NA1B22
/dev/mapper/SRP4NA1B23-part1   2.7T  2.2T  508G  82% /mnt/SnapRaidArray_P/SRP4NA1B23
/dev/mapper/SRD5NA1B4-part1    2.8T  2.1T     0 100% /mnt/SnapRaidArray/SRD5NA1B4

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`

* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
I can't comment on why it chose that disk without knowing literally everything about the filesystems before a file was created but you're using mfs so I can only assume it was chosen because it calculated that it was the drive with the most free space.

As for blacklisting drives from creates... yes... https://github.com/trapexit/mergerfs#branches

**Comment by trapexit** [comment]
I don't know how snapshots represent themselves in terms of the storage. mergerfs is just running statvfs like `df` does and sorts by available space.

**Comment by trapexit** [comment]
Are you sure you wrote through mergerfs? That it wasn't a very large file? there is no way that mergerfs would fill 1 drive when using mfs and it wouldn't have skipped the minfreespace check. It's fundamental and used by nearly everyone.

**Comment by MasterCATZ** [comment]
Thanks, =NC (no create). 
so how would I add this to the fstab for a specified disk? 
( I might slip it in next time a have a huge file being downloaded ) 

all I do know is the 260 gig file was being downloaded before the last 5 files that were around 8 gig each, the 260 gig file completed downloading and a few of the last files ran out of space 
how ever it looks like at some stage I turned off "Pre-allocation" 
so that would be the initial root cause,
the files are being written from a Virtualbox with a shared folder path

for now it all seems to be running fine again and files are spreading across the other disks , it might have just been this 1 huge file plus my auto 1 hr snapshots that caused it 

it could also have been a btrfs / statvfs issue as df miss-reports btrfs free space all the time 

I guess this disk would have had the most space after the snapraid fix as the snapshots would not have been recovered  as they are excluded from the syncs

**Comment by trapexit** [comment]
You put it at the end of a branch.

/foo/bar=NC
