### ISSUE TITLE
mergerfs not allowing touch unless all directories are mutable

### ISSUE THREAD

**Issue by abraha2d** [trapexit/mergerfs#715]
General description
===================
I have my /etc/fstab set up like so:
```
UUID=...              /media/disk0-0          ext4            defaults,noauto
UUID=...              /media/disk0-1          ext4            defaults,noauto
...

/media/disk0-*        /mnt/watchtower         fuse.mergerfs   allow_other,moveonenospc=true,noforget,use_ino,fsname=watchtower,category.create=lfs,cache.files=off
```

I have executed `chattr +i` on both the `/media/disk0-*` and the `/mnt/watchtower` mountpoints.

Expected behavior
=================

Running `ls -l /mnt/watchtower` should show nothing.
Running `touch /mnt/watchtower/test` should fail. 
After running `mount /media/disk0-0`, running `ls -l /mnt/watchtower` should show contents of disk.
Also, running `touch /mnt/watchtower/test` should succeed.

Actual behavior
===============

Running `ls -l /mnt/watchtower` shows nothing.
Running `touch /mnt/watchtower/test` fails with `touch: setting times of '/mnt/watchtower/test': No such file or directory`. 
After running `mount /media/disk0-0`, running `ls -l /mnt/watchtower` shows contents of disk.
However, running `touch /mnt/watchtower/test` still fails with the same error as above.

Only once I mount all the `/media/disk0-*` disks am I able to run the `touch` command successfully.

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

See above.

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [x] Linux version: `uname -a`
* [ ] Versions of any additional software being used
* [x] List of drives, filesystems, & sizes: `df -h`
* [x] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [x] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

mergerfs version:
```
mergerfs version: 2.28.3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29
```

mergerfs settings: See above.

Linux version: `Linux pve 5.3.18-1-pve #1 SMP PVE 5.3.18-1 (Wed, 05 Feb 2020 11:49:10 +0100) x86_64 GNU/Linux`

List of drives, filesystems, & sizes:
```
/dev/sdb1             3.6T  114G  3.3T   4% /media/disk0-0
watchtower             15T  114G   14T   1% /mnt/watchtower
/dev/sdc1             3.6T   89M  3.4T   1% /media/disk0-1
/dev/sdd1             3.6T   89M  3.4T   1% /media/disk0-2
/dev/sde1             3.6T   89M  3.4T   1% /media/disk0-3
```

strace of application having problem:
[touch.strace.txt](https://github.com/trapexit/mergerfs/files/4238978/touch.strace.txt)

strace of mergerfs while app tried to do it's thing:
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/4238979/mergerfs.strace.txt)

**Comment by trapexit** [comment]
You've not provided enough info. What are the settings? It isn't forbidding anything. It passes it to the underlying device. Are you sure it selects a device that is mutable? It's not filtering drives based on directory mutablility from file attributes.

**Comment by trapexit** [comment]
`29243 openat(AT_FDCWD, "/mnt/watchtower/test", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = -1 EPERM (Operation not permitted)`

**Comment by trapexit** [comment]
I don't really understand what you expect to be happening. The immutable flag of ext4 has absolutely no impact on mergerfs' behavior.

**Comment by abraha2d** [comment]
Ah, I figured out why it's doing this. As soon as a drive is unmounted, the folder it was mounted in becomes the drive with the least free space, so mergerfs tries to write the new file to it. I guess I had been expecting mergerfs to ignore that drive/folder when considering where to create the new file.

**Comment by trapexit** [comment]
No. It's a live proxy. If you change things, outside of noted caching, that is what is considered the next time something is queried/acted on. If you don't want the branch considered you need to remove it from the runtime. Telling a drive has changed is not so easy.
