### ISSUE TITLE
Update files on readonly branchs

### ISSUE THREAD

**Issue by juanrodgil** [trapexit/mergerfs#717]
More than an issue is a question!

Can the branches be configured so that an update of a file in one of the read-only branches will save the modified file in one of the writing branches?

**Comment by trapexit** [comment]
No. Why would you want that? It would require copying the whole file to then make the change and then you might not even see the file because the policy for open and create and getattr, etc. could be different. 

If you want a copy on write behavior why not use a copy on write filesystem?
