### ISSUE TITLE
Missing raspbian buster armhf package

### ISSUE THREAD

**Issue by adelolmo** [trapexit/mergerfs#719]
The release [2.29.0](https://github.com/trapexit/mergerfs/releases/tag/2.29.0) is missing the package form raspbian buster armhf.
Is this intentional or just a mistake?

**Comment by trapexit** [comment]
Intentional in that the normal Debian Buster armhf package should work: https://github.com/trapexit/mergerfs/releases/download/2.29.0/mergerfs_2.29.0.debian-buster_armhf.deb

Does it not?

**Comment by adelolmo** [comment]
`mergerfs_2.29.0.debian-buster_armhf.deb` seems to work just fine on raspbian.

I was confused because there used to be a package specific for raspbian up until 2.29.0.

Thank you

**Comment by trapexit** [comment]
Even the raspbian build env I had would identify as Debian so it seems not worth to bother going forward with a special package that is otherwise identical.
