### ISSUE TITLE
Cant start docker "trapexit/mergerfs-static-build" on Unraid 6.7.2 & 6.8.2

### ISSUE THREAD

**Issue by vaski666** [trapexit/mergerfs#721]
General description
===================
Running the following command in unraid 6.7.2 and 6.8.2 (after update) results in error.
`docker run -v /mnt/user/appdata/other/mergerfs:/build --rm -it trapexit/mergerfs-static-build`

Expected behavior
=================
docker created succesfully

Actual behavior
===============

collect2: error: ld returned 1 exit status
make: *** [Makefile:111: build/mergerfs] Error 1
strip: 'build/mergerfs': No such file
/tmp/build-mergerfs: line 15: build/mergerfs: not found
cp: can't stat 'build/mergerfs': No such file or directory

**Precise** steps to reproduce the behavior
===========================================
create path `/mnt/user/appdata/other/mergerfs/mergerfs`
run command `docker run -v /mnt/user/appdata/other/mergerfs:/build --rm -it trapexit/mergerfs-static-build`

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
* [x ] mergerfs settings: `cat /etc/fstab` or the command line arguments
/dev/disk/by-label/UNRAID  /boot         vfat      auto,rw,flush,noatime,nodiratime,dmask=77,fmask=177,shortname=mixed  0  1
/boot/bzmodules            /lib/modules  squashfs  ro,defaults  0  2
/boot/bzfirmware           /lib/firmware squashfs  ro,defaults  0  2
tmpfs                      /dev/shm      tmpfs     defaults     0  0
hugetlbfs                  /hugetlbfs    hugetlbfs defaults     0  0

* [ x] Linux version: `uname -a`
Linux Tower 4.19.98-Unraid #1 SMP Sun Jan 26 09:15:03 PST 2020 x86_64 Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz GenuineIntel GNU/Linux
* [ ] Versions of any additional software being used
* [x ] List of drives, filesystems, & sizes: `df -h`
Filesystem      Size  Used Avail Use% Mounted on
rootfs          7.7G  1.1G  6.7G  14% /
tmpfs            32M  596K   32M   2% /run
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.9G     0  7.9G   0% /dev/shm
cgroup_root     8.0M     0  8.0M   0% /sys/fs/cgroup
tmpfs           128M  232K  128M   1% /var/log
/dev/sda1        15G  441M   15G   3% /boot
/dev/loop0      9.2M  9.2M     0 100% /lib/modules
/dev/loop1      7.3M  7.3M     0 100% /lib/firmware
tmpfs           1.0M     0  1.0M   0% /mnt/disks
/dev/md1        7.3T  4.8T  2.5T  66% /mnt/disk1
/dev/nvme0n1p1  477G   49G  427G  11% /mnt/cache
shfs            7.3T  4.8T  2.5T  66% /mnt/user0
shfs            7.8T  4.9T  3.0T  63% /mnt/user
/dev/loop2       20G  8.3G   11G  43% /var/lib/docker
/dev/loop3      1.0G   17M  905M   2% /etc/libvirt
shm              64M     0   64M   0% /var/lib/docker/containers/44c0a00a66d3e6d6496c7a1370c68332ef304f92f3808a22fe1daeecdc935f82/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/05e7fc25381c53bc78624d4f3d94469bcba549a71ebac5f94125b459659a2223/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/e2d8e2a9c6ebad827826aa3ad7646d02672e13f8790db485f1454415fa1b58e0/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/9e7df75ecbc51f7bf3c17b4d5d08b5d1f35b33e507ba9847e2572f9d4cae960f/mounts/shm

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
Has nothing to do with the image. It's just a problem with building on Alpine.

**Comment by vaski666** [comment]
> Has nothing to do with the image. It's just a problem with building on Alpine. I'll take a look.

Great thanks! 
I'm on thin ice with this ticket, but let me know if i can provide any more info or test something.

**Comment by trapexit** [comment]
What are you doing exactly? That docker image is only meant for fooling around. It uses the master branch. It is not intended for production use.

**Comment by vaski666** [comment]
It's a part of a script "To Use Rclone To Mount Cloud Drives And Play Files"
https://forums.unraid.net/topic/75436-guide-how-to-use-rclone-to-mount-cloud-drives-and-play-files/

**Comment by vaski666** [comment]
And my use is mostly "fooling around" :-)

**Comment by trapexit** [comment]
Sure... but what I mean is that it's not building a known stable release. It's building whatever I happen to have checked in. Which obviously is broken for Alpine right now.

**Comment by trapexit** [comment]
try again. make sure to do a docker pull first.

**Comment by vaski666** [comment]
Hi trapexit, 
Its working, thanks a lot for your help and quick replies!
i'll report back to the forum regarding the intended use of the docker.

**Comment by trapexit** [comment]
I changed the way it works. People can use it however they want. It selects the latest tag otherwise they can select it by setting the environment variable TAG.
