### ISSUE TITLE
lus create policy fills disks inconsistently

### ISSUE THREAD

**Issue by hacktek** [trapexit/mergerfs#724]
General description
===================

I have the following disk setup:

df -h | grep -P '/dev/sd(a5|b|c|d|e|f)'
/dev/sda5                            1.8T  4.2G  1.7T   1% /
/dev/sdb                             1.8T  4.6G  1.7T   1% /mnt/disk2
/dev/sdc                             916G   13G  857G   2% /mnt/disk3
/dev/sdd                             916G   13G  857G   2% /mnt/disk4
/dev/sde                             916G   13G  857G   2% /mnt/disk5
/dev/sdf                             916G   13G  857G   2% /mnt/disk6

Basically 2 2TB disks and 4 1TB disks for a total of 8TB. I'm trying to use this as an nginx cache so I'd like least used space to be used to the disks get filled up at a similar rate and each nginx slice chunk goes into different disks for better performance. Everything looks great on the smaller disks and they're filling up at the same rate but the larger disks are not. 

Expected behavior
=================

All drives fill up at the same rate since they all should have similar least used space as cache gets filled.

Actual behavior
===============

mergerfs seems to be filling the 1TB drives at the same rate but discounting the larger 2TB drives.  

**Precise** steps to reproduce the behavior
===========================================

The actual mount union looks like this, in this order:

disk2:disk3:disk4:disk5:disk6:disk1 7684148664 61444372 7231952100   1% /mnt/storage

A couple of things happened when I first created the mount that might be related to I'll mention them:

1/ I used the cloudbox systemd service template as a starting point not noticing that it had an "ff" create policy. This lead to using disk2 first. I noticed when that hit 4.6 gigs and changed the policy to "lus".
2/ I forgot to add the root drive mount path when I first created the mount so I added it after the path. "disk1" is actually "/mnt/disk1" which, as opposed to the rest is actually on the root/OS drive and is not its own drive.

At first I thought that, since I was filling up a single drive first and then changed strategy (and since the OS drive actually has space occupied by...the OS) that it would take the rest of the drives catching up to 4.6GB before stuff actually started getting split and dumped into all drives equally but that does not seem to be happening.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`

```
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments

I've since rearranged disk1 to be first but that has not made any difference.

```
[Unit]
Description=MergerFS Mount
After=network-online.target

[Service]
Type=forking
GuessMainPID=no
ExecStart=/usr/bin/mergerfs \
  -o category.create=lus,async_read=false,cache.files=partial \
  -o dropcacheonclose=true,use_ino \
  -o xattr=nosys,statfs_ignore=ro,allow_other,umask=002,noatime \
  /mnt/disk1=RW:/mnt/disk2=RW:/mnt/disk3=RW:/mnt/disk4=RW:/mnt/disk5=RW:/mnt/disk6=RW /mnt/storage
ExecStop=/bin/fusermount -u /mnt/storage

[Install]
WantedBy=default.target
```

* [ ] Linux version: `uname -a`

```
Linux ftvstor01 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* [ ] List of drives, filesystems, & sizes: `df -h`

```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M  792K  797M   1% /run
/dev/sda5       1.8T  4.2G  1.7T   1% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda1       961M   58M  855M   7% /boot
tmpfs           798M     0  798M   0% /run/user/0
/dev/sdb        1.8T  4.6G  1.7T   1% /mnt/disk2
/dev/sdc        916G   14G  856G   2% /mnt/disk3
/dev/sdd        916G   14G  856G   2% /mnt/disk4
/dev/sde        916G   14G  856G   2% /mnt/disk5
/dev/sdf        916G   14G  856G   2% /mnt/disk6
2:3:4:5:6:1     7.2T   63G  6.8T   1% /mnt/storage
```

**Comment by trapexit** [comment]
Are you positive it is always creating new files? It's not really practical to debug something special like this without more information. As suggested in the docs if you could create a explicit example with generic tools it'd be easier to evaluate.

policies haven't changed in years and are very [straight forward.](https://github.com/trapexit/mergerfs/blob/master/src/policy_lus.cpp#L36) It's more likely nginx is doing something you aren't expecting. Ignoring minfreespace and readonly branches it is just picking the branch with least used space. Space used is calculated by subtracting available blocks (not free blocks, on ext4 that is often different) from total [blocks](https://github.com/trapexit/mergerfs/blob/master/src/statvfs_util.hpp#L45).

**Comment by hacktek** [comment]
Yes, I'm positive it's creating files. This is large content (5+ GB files usually) split into 8MB chunks. Here's a simple looped find showing the total number of lines grows every 5s (i.e. more files are getting created as nginx splits the content to cache it):

```
while [ 1 ]; do find /mnt/storage/ | wc -l; sleep 5; done
3233
3251
3263
3277
3286
3306
3335
3368
^C
```

I nuked all content from all paths (rm -r * on /mnt/storage) and verified that all paths (disk1-6) were empty. Then I re-started nginx so it would create the cache path. I still have the same behavior, the files get created only on the 1TB drives. If I manually check all paths, the cache path only exists in the small drives (3/4/5/6):

```
for i in {1..6}; do echo disk$i:`ls /mnt/disk$i`; done
disk1:
disk2:
disk3:cache
disk4:cache
disk5:cache
disk6:cache
```
I doubt this is nginx related. All nginx is doing is chunking files and dumping them in a path. I did a manual test with dd (created larger files at 50MB just to make sure they would balance properly) and I see the same behavior: the first 2 drives are ignored...

Creating the files:

```
for i in {1..6}; do dd if=/dev/zero of=/mnt/storage/test$i.bin count=1 bs=50M; done
1+0 records in
1+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.187336 s, 280 MB/s
1+0 records in
1+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.228758 s, 229 MB/s
1+0 records in
1+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.211746 s, 248 MB/s
1+0 records in
1+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.206922 s, 253 MB/s
1+0 records in
1+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.453494 s, 116 MB/s
1+0 records in
1+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.19236 s, 273 MB/s
```

Looking for the files:

```
find /mnt/ -name '*.bin' | grep -v storage
/mnt/disk5/test1.bin
/mnt/disk6/test5.bin
/mnt/disk6/test2.bin
/mnt/disk4/test4.bin
/mnt/disk3/test6.bin
/mnt/disk3/test3.bin
```

**Comment by trapexit** [comment]
I don't see how there can be a bug. It is exactly the same calculation for each drive.

df shows you the free blocks. Not available blocks. What filesystem are you using? What are the specific numbers involved. 

Give me the output of `strace -e statfs df 2>&1 | grep f_bavail | grep mnt`

**Comment by hacktek** [comment]
I'm on Ubuntu 18.04. I'll run the command in a bit when I'm in front of a computer. 

Does it not look odd to you that when I used dd to test, files were only created in the small disks and when I used rand all disks were used?

I'll try something else later: I'll partition the 2 TB drive into two 1 TB partitions and we'll see if files continue to not be created there in favor of the 1 TB _capacity_ disks.

**Comment by trapexit** [comment]
What filesystem are you using?

I can't comment on odd or not without knowing *all* the details. Space used is calculated by `f_frsize * (f_block - f_bavail))`. If I don't know what those values (along with everything else that makes up the policy decision) I can't really comment.

**Comment by trapexit** [comment]
If you are using ext{2,3,4}... what is the reserved block count? If you're reserving space with ext{2,3,4} then naturally it will throw off the calculation as mergerfs is respecting the difference between free and available blocks. df shows free. Not available.

**Comment by hacktek** [comment]
OK thanks for the patience.

Result of strace command:

```
strace -e statfs df 2>&1 | grep f_bavail | grep mnt
statfs("/mnt/disk3", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=240095418, f_bfree=237748040, f_bavail=225534412, f_files=61054976, f_ffree=61052638, f_fsid={val=[3514389331, 3787980842]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
statfs("/mnt/disk4", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=240095418, f_bfree=237709749, f_bavail=225496121, f_files=61054976, f_ffree=61052603, f_fsid={val=[4284677642, 998630991]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
statfs("/mnt/disk5", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=240095418, f_bfree=237685529, f_bavail=225471901, f_files=61054976, f_ffree=61052572, f_fsid={val=[1294855876, 4094034700]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
statfs("/mnt/disk6", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=240095418, f_bfree=237720492, f_bavail=225506864, f_files=61054976, f_ffree=61052600, f_fsid={val=[2407292347, 4219641093]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
statfs("/mnt/disk2_1", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=240089350, f_bfree=240041175, f_bavail=227827876, f_files=61046784, f_ffree=61046733, f_fsid={val=[2586583381, 903861009]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
statfs("/mnt/disk2_2", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=240089350, f_bfree=240041931, f_bavail=227828632, f_files=61046784, f_ffree=61046733, f_fsid={val=[228533734, 3544420236]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
statfs("/mnt/storage", {f_type=FUSE_SUPER_MAGIC, f_bsize=4096, f_blocks=1920764980, f_bfree=1908812153, f_bavail=1811120535, f_files=488349696, f_ffree=488247299, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_NOSUID|ST_NODEV|ST_RELATIME}) = 0
```

You'll notice that I partitioned disk2 into two 1 TB partitions. I just ran a test and lus started filling up space on both of those while ignoring the rest which is what I'd expect. It's just interesting that this did not happen when it was a single 2 TB partition.

/mnt/disk_* filling up:

```
while [ 1 ]; do find /mnt/disk2_* | wc -l; sleep 5; done
86
96
108
116
132
145
^C
```

while the rest are not:

```
while [ 1 ]; do find /mnt/ ! \( -path '/mnt/disk2_*' -o -path '/mnt/storage*' \) | wc -l; sleep 5; done
10784
10784
10784
10784
10784
10784
^C
```

All of this is happening on ext4.

Questions:

1. How do I check reserved block count?
2. /mnt/disk1 does not show because that's the root drive and not a separate partition. Does mergerfs need separately mounted partitions in order for the policy to work? I would have expected it to work just the same with several mounted paths regardless of where they are.

**Comment by trapexit** [comment]
> /mnt/disk1 does not show 
Then don't grep by "mnt" or target "/" directly to get those values.

>How do I check reserved block count?

`sudo tune2fs -l /device` and look for "Reserved block count"

If you don't know the value it's probably the default which is 5%. 5% of 2TB is a 2x that of 1TB.

So... space used is blocks minus available.

If you have 5% of 1TB it's ~51GB. Double that is ~102GB. So 51GB+14GB is less than 102GB. So The 1TB drives are going to fill up first till they hit ~102GB if you use `lus` policy.

If you want to change the reserve you can use tune2fs: https://odzangba.wordpress.com/2010/02/20/how-to-free-reserved-space-on-ext4-partitions/

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#policy-descriptions

I added a note to make this information more clear.

**Comment by hacktek** [comment]
That might explain it and thanks for the note, I think that'll help someone!

```
tune2fs -l /dev/sdb1 | grep 'Reserved block count'
Reserved block count:     24418919

tune2fs -l /dev/sdc | grep 'Reserved block count'
Reserved block count:     12209532
```

I just re-did it without partitioning disk2 and I was able to replicate the initial behavior so it's very possible that this is the issue. I'll try reducing the reserved count to 0 on the non-OS drives and 1% on the OS drive and will see what happens.

Cheers!
