### ISSUE TITLE
NFS Stale file handle after disk is missing

### ISSUE THREAD

**Issue by uchagani** [trapexit/mergerfs#725]
General description
===================
I had a mergerfs mount set up but recently and had a disk fail to mount on reboot.  Systemd gave me an error on reboot like this: `Timed out waiting for device /dev/disk/by-id/scsi-SATA_WDC_WD100EZAZ-11_XXXXXXX5-part1.`

When I tried to access the files on the NFS client I got the error `ls: cannot access '/mnt/media/tv': Stale file handle`

I tried to manually remove the disk from mergerfs with `mergerfs.ctl -m /mnt/storage remove path /mnt/disk-XXXXXXX5` but I still have the same issue on the NFS client machine.

I am using the latest version of mergerfs available on the Ubuntu Eoan repo.

Expected behavior
=================
NFS client works as normal but without the files that were located on the missing disk.

Actual behavior
===============
Stale file handle error from NFS client.

**Precise** steps to reproduce the behavior
===========================================
1.  Set up mergerfs with multiple disks.
2.  Set up NFS server and export a directory located on the mergerfs mount.
3.  Set up an NFS client and mount the exported directory.
4.  Ensure NFS client can access the files.
5.  Shut down the server and remove a disk.
6.  Reboot the server.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: 
```
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29
```
* [ ] mergerfs settings: 
```
/dev/disk/by-id/scsi-SATA_WDC_WD100EZAZ-11_XXXXXXX1-part1 /mnt/disk-XXXXXXX1 xfs defaults 0 0
/dev/disk/by-id/scsi-SATA_WDC_WD100EZAZ-11_XXXXXXX2-part1 /mnt/disk-XXXXXXX2 xfs defaults 0 0
/dev/disk/by-id/scsi-SATA_WDC_WD100EZAZ-11_XXXXXXX3-part1 /mnt/disk-XXXXXXX3 xfs defaults 0 0
/dev/disk/by-id/scsi-SATA_WDC_WD100EZAZ-11_XXXXXXX4-part1 /mnt/disk-XXXXXXX4 xfs defaults 0 0
/dev/disk/by-id/scsi-SATA_WDC_WD100EZAZ-11_XXXXXXX5-part1 /mnt/disk-XXXXXXX5 xfs defaults 0 0

/mnt/disk* /mnt/storage fuse.mergerfs defaults,use_ino,noforget,cache.files=off,dropcacheonclose=true,allow_other,category.create=mfs,minfreespace=100G,fsname=mergerfs 0 0

/mnt/storage/media/movies /shared/media/movies none bind 0 0
/mnt/storage/media/tv     /shared/media/tv     none bind 0 0
```
* [ ] Linux version: `Linux server 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* [ ] List of drives, filesystems, & sizes:
```
Filesystem       Size  Used Avail Use% Mounted on
udev              95G     0   95G   0% /dev
tmpfs             19G  2.1M   19G   1% /run
/dev/sda1        275G  6.3G  254G   3% /
tmpfs             95G     0   95G   0% /dev/shm
tmpfs            5.0M     0  5.0M   0% /run/lock
tmpfs             95G     0   95G   0% /sys/fs/cgroup
mergerfs          37T   11T   26T  30% /mnt/storage
/dev/sdp1        9.1T  2.7T  6.5T  30% /mnt/disk-XXXXXXX1
/dev/sdo1        9.1T  2.7T  6.5T  30% /mnt/disk-XXXXXXX2
/dev/sdk1        9.1T  2.7T  6.5T  30% /mnt/disk-XXXXXXX3
/dev/sdm1        9.1T  2.7T  6.5T  30% /mnt/disk-XXXXXXX4
datapool/docker  808G  2.2M  808G   1% /var/lib/docker
tmpfs             19G     0   19G   0% /run/user/1000
```

**Comment by trapexit** [comment]
If the drive disappeared then NFS is rightfully saying that there is a problem. NFS doesn't handle files suddenly disappearing that it expect to be there. That's why you get stale handle. There isn't much I can do. There already known issues with FUSE and NFS as documented in the readme. I don't really have anything more to add or suggest besides ensuring you use the latest release. You shouldn't use the distro version. They are always out of data.

**Comment by uchagani** [comment]
Is there another way you recommend sharing data besides NFS?

**Comment by trapexit** [comment]
Depends on what you are doing. Samba, sshfs, some sort of webdav setup.

**Comment by uchagani** [comment]
Just sharing media files mostly.

**Comment by trapexit** [comment]
NFS Stale files is just a fact of life so unless it happens a lot... that's just normal. And if it was triggered by the removal of files from behind the scenes then it's perfectly expected. If you're just doing read only sharing then Samba tends to work well on most clients.

**Comment by uchagani** [comment]
Great will try that thanks.
