### ISSUE TITLE
Prebuilt package for Ubuntu Eoan (19.10)

### ISSUE THREAD

**Issue by uchagani** [trapexit/mergerfs#728]
General description
===================
With Ubuntu Disco (19.04) no longer supported, can we get prebuilt packages for Ubuntu Eoan (19.10)?

**Comment by trapexit** [comment]
You should be able to use bionic packages but sure... I'll look into it.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/releases/download/2.29.0/mergerfs_2.29.0.ubuntu-eoan_amd64.deb
