### ISSUE TITLE
Rsync Duplicate files

### ISSUE THREAD

**Issue by nayneyT** [trapexit/mergerfs#731]
General description
===================

When rsync'ing from local storage to local storage I get duplicate files in a weird named folder

my /etc/fstab

/mnt/datadisk* /mnt/storage fuse.mergerfs use_ino,dropcacheonclose=true,allow_other,category.create=epmfs,minfreespace=100G,fsname=mergerfs 0 0

rsync command

sudo rsync -arvhp /mnt/ext_usbdrive/volume1/music/ /mnt/storage/music/

End up with

drwxrwxrwx  8 root root 4096 Feb  3 17:43 ''$'\r'
drwxrwxrwx  9 root root 4096 Feb  3 17:43  .
drwxr-xr-x  7 root root 4096 Mar 12 00:06  ..
drwxrwxrwx 28 root root 4096 Jan 27 01:04  Albums
drwxrwxrwx 83 root root 4096 Jan 29 21:12  Compilations
drwxrwxrwx  3 root root 4096 Nov 30 21:06  Singles
drwxrwxrwx 46 root root 4096 Oct 21  2018  Soundtracks
drwxrwxrwx 31 root root 4096 Mar 22  2016  Untagged

The ''$'\r' directory (which shows as _2X680~Y in Samba share) contains the exact data as the files copied. It's like it's copied them twice but placed the 2nd copy inside the random named directory.

Expected behavior
=================

copy recursively from one folder on a mount (ntfs external usb drive) to a merger fs mount.

Actual behavior
===============

Duplicates in a random folder. 

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V` mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
#mergerfs

/dev/disk/by-id/scsi-SATA_ST4000VN000-1H41_Z30147NJ-part1 /mnt/datadisk01 ext4 defaults 0 0
/dev/disk/by-id/scsi-SATA_ST4000VN000-1H41_Z30146RW-part1 /mnt/datadisk02 ext4 defaults 0 0

/mnt/datadisk* /mnt/storage fuse.mergerfs use_ino,dropcacheonclose=true,allow_other,category.create=epmfs,minfreespace=100G,fsname=mergerfs 0 0

* [ ] Linux version: `uname -a` Linux ubuntu 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* [ ] Versions of any additional software being used
rsync --version
rsync  version 3.1.3  protocol version 31

* [ ] List of drives, filesystems, & sizes: `df -h`
/dev/sdb2      fuseblk        7.3T  6.6T  736G  91% /mnt/ext_usbdrive
/dev/sdd1      ext4           3.6T  731G  2.7T  21% /mnt/datadisk01
/dev/sdc1      ext4           3.6T  178M  3.4T   1% /mnt/datadisk02
mergerfs       fuse.mergerfs  7.2T  741G  6.2T  11% /mnt/storage

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`

* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
Please first try the current release. Let me know if it still occurs.

**Comment by nayneyT** [comment]
Hi. I am only just setting this up so I didn't really have much to lose. I started again and reinstalled Ubuntu and MergerFS (from standard Ubuntu repo using apt) and now everything is okay. No idea what was causing it but it's working okay now. So I am closing this.

**Comment by trapexit** [comment]
I don't recommend using standard repo version. They don't get updated and that version has bugs.

https://github.com/trapexit/mergerfs/releases
