### ISSUE TITLE
mergerfs not honoring "MFS" policy? (OMV 5 plugin)

### ISSUE THREAD

**Issue by zeitchef** [trapexit/mergerfs#732]
General description
===================

I'm building a fresh OMV5 server and using the unionfilesystems-plugin (based on mergerfs). I'm very aware this could be an issue with the implementation of that plugin, thus this is a duplicate issue filed on their repo.

I've got 3 disks I'm pooling (4TB, 2TB, 1TB) all freshly-formatted BTRFS. I've set the policy to "Most free space" and left the other defaults when creating the pool in OMV. The data on the disks is music files, all highly structured, and is currently being dumped from a previous disk via rsync.

Expected behavior
=================

The total size of the pool should be 6.7TB and when adding data to the pool, the used data and available data should be equal to the total data. (see screenshot)

Actual behavior
===============

When adding data to the pool, the available data size becomes MUCH smaller than it should, when considering the used and total. Adding 1TB of data has cut the size of available space in the pool in half (see screenshot). I've checked the individual disks and the existing data paths are being honored... should this be the case when using the "MFS" policy? Why am I not able to access the full size of the pool?

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -v`
2.28.3

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda2 during installation
UUID=e2c49a53-f4b9-46e8-aec6-2bd86c1d882b /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda1 during installation
UUID=90C6-424E  /boot/efi       vfat    umask=0077      0       1
# swap was on /dev/sda3 during installation
UUID=6aa83912-b4de-4d4d-af2a-1869d40b612e none            swap    sw              0       0
/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0
# >>> [openmediavault]
/dev/disk/by-label/music1		/srv/dev-disk-by-label-music1	btrfs	defaults,nofail	0 2
/dev/disk/by-label/music2		/srv/dev-disk-by-label-music2	btrfs	defaults,nofail	0 2
/dev/disk/by-label/music3		/srv/dev-disk-by-label-music3	btrfs	defaults,nofail	0 2
/dev/disk/by-label/Archive		/srv/dev-disk-by-label-Archive	hfsplus	defaults,nofail,force	0 2
/srv/dev-disk-by-label-music1:/srv/dev-disk-by-label-music2:/srv/dev-disk-by-label-music3		/srv/cc4f9ccd-8f26-4161-83e9-ef79becb822a	fuse.mergerfs	defaults,allow_other,cache.files=off,use_ino,category.create=mfs,minfreespace=4G,fsname=HDMusic:cc4f9ccd-8f26-4161-83e9-ef79becb822a,x-systemd.requires=/srv/dev-disk-by-label-music1,x-systemd.requires=/srv/dev-disk-by-label-music2,x-systemd.requires=/srv/dev-disk-by-label-music3	0 0
```

* [ ] Linux version: `uname -a`
```
Linux omv.local 5.4.0-0.bpo.3-amd64 #1 SMP Debian 5.4.13-1~bpo10+1 (2020-02-07) x86_64 GNU/Linux
```

* [ ] List of drives, filesystems, & sizes: `df -h`
```
Filesystem                                    Size  Used Avail Use% Mounted on
udev                                          1.8G     0  1.8G   0% /dev
tmpfs                                         369M   22M  348M   6% /run
/dev/sda2                                     225G  1.9G  211G   1% /
tmpfs                                         1.8G  200K  1.8G   1% /dev/shm
tmpfs                                         5.0M     0  5.0M   0% /run/lock
tmpfs                                         1.8G     0  1.8G   0% /sys/fs/cgroup
/dev/sda1                                     511M  140K  511M   1% /boot/efi
tmpfs                                         1.8G  100K  1.8G   1% /tmp
/dev/sdg1                                     3.7T  683G     0 100% /srv/dev-disk-by-label-music1
/dev/sdh1                                     1.9T  577G  1.3T  31% /srv/dev-disk-by-label-music2
/dev/sdi1                                     932G  3.8M  930G   1% /srv/dev-disk-by-label-music3
/dev/sdf2                                     3.7T  3.4T  309G  92% /srv/dev-disk-by-label-Archive
HDMusic:cc4f9ccd-8f26-4161-83e9-ef79becb822a  6.4T  1.3T  2.2T  37% /srv/cc4f9ccd-8f26-4161-83e9-ef79becb822a
```

<img width="1440" alt="76690756-bdb7c200-6643-11ea-85c8-480fd8b9b3f5" src="https://user-images.githubusercontent.com/6670659/76691490-72a1ad00-664b-11ea-8326-b10783b8ef3e.png">

**Comment by trapexit** [comment]
mergerfs just reports back what it's told by the operating system. /dev/sdg1 is clearly reporting weird values. mergerfs has nothing to do with that. 0 bytes free, used 683GB, total 3.7TB? Do you have a lot of linked but open files?

**Comment by zeitchef** [comment]
Thanks for the quick response @trapexit - Sorry, I'm not sure what you mean by "unlinked but open" files? The disk was freshly wiped and formatted, and the only data that's been put onto it is from my archive hard drive via rsync directly into the pool.

I had overlooked the infos from `df -h`, focused solely on the output in OMV (which seems correct).

**Comment by zeitchef** [comment]
I've investigated possible reasons for the error, but most tend to be misunderstandings about the fact that filesystems reserve 5% of space for root - but this is clearly not what's going on here.

The output of `losf +L1`:

```
COMMAND     PID                  USER   FD   TYPE DEVICE SIZE/OFF NLINK    NODE NAME
php-fpm7.   560                  root    3u   REG   0,44        0     0   21690 /tmp/.ZendSem.K2dboT (deleted)
php-fpm7.   594              www-data    3u   REG   0,44        0     0   21690 /tmp/.ZendSem.K2dboT (deleted)
php-fpm7.   595              www-data    3u   REG   0,44        0     0   21690 /tmp/.ZendSem.K2dboT (deleted)
salt-mini   605                  root    8w   REG    8,2      541     0 5639212 /var/log/salt/minion.1 (deleted)
php-fpm7. 26218 openmediavault-webgui    3u   REG   0,44        0     0   21690 /tmp/.ZendSem.K2dboT (deleted)
```

I'm no Linux expert, but this seems pretty inconclusive.

**Comment by zeitchef** [comment]
Here's something - output of `tune2fs -l /dev/sdg1`:

```
tune2fs 1.45.5 (07-Jan-2020)
tune2fs: Bad magic number in super-block while trying to open /dev/sdg1
/dev/sdg1 contains a btrfs file system labelled 'music1'
```

**Comment by trapexit** [comment]
I can't speak to or comment on anything OMV. Just normal tooling. There could be bugs in OMV UI.

But df is unlikely to have one.

btrfs doesn't reserve data like ext4 does AFAIK.

re: unlinked files... if a file is unlinked while open it won't be removed until it's closed by everyone who has it open.

I don't much about btrfs. Not sure what other reasons there could be for it to report like that. Are you using snapshots?

**Comment by zeitchef** [comment]
Just an update: reformatted the disks to ext4 - now have no problems. Closing issue.
