### ISSUE TITLE
wrong disk usage

### ISSUE THREAD

**Issue by momkin** [trapexit/mergerfs#734]
General description
===================
when i check the disk usage with df -BG command i see that More than 838GB of space is gone from the disk usage !

Expected behavior
=================

```
[root@sd-79476 ~]# df -BG
Filesystem     1G-blocks  Used Available Use% Mounted on
devtmpfs             32G    0G       32G   0% /dev
tmpfs                32G    0G       32G   0% /dev/shm
tmpfs                32G    1G       32G   1% /run
tmpfs                32G    0G       32G   0% /sys/fs/cgroup
/dev/sda3          5540G    2G     5258G   1% /
/dev/sdb           5545G   10G     5256G   1% /pool/storage02
/dev/sdc           5545G    2G     5264G   1% /pool/storage03
/dev/sda2             1G    1G        1G  27% /boot
tmpfs                 7G    0G        7G   0% /run/user/0
tmpfs                 7G    0G        7G   0% /run/user/48
1:2:3:4           16628G   13G    16615G   1% /storage
[root@sd-79476 ~]#

```

Actual behavior
===============

```
[root@sd-79476 ~]# df -BG
Filesystem     1G-blocks  Used Available Use% Mounted on
devtmpfs             32G    0G       32G   0% /dev
tmpfs                32G    0G       32G   0% /dev/shm
tmpfs                32G    1G       32G   1% /run
tmpfs                32G    0G       32G   0% /sys/fs/cgroup
/dev/sda3          5540G    2G     5258G   1% /
/dev/sdb           5545G   10G     5256G   1% /pool/storage02
/dev/sdc           5545G    2G     5264G   1% /pool/storage03
/dev/sda2             1G    1G        1G  27% /boot
tmpfs                 7G    0G        7G   0% /run/user/0
tmpfs                 7G    0G        7G   0% /run/user/48
1:2:3:4           16628G   13G    15777G   1% /storage
[root@sd-79476 ~]#
```

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
```
[root@sd-79476 ~]# mergerfs -V
mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
[root@sd-79476 ~]#
```
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
#
# /etc/fstab
# Created by anaconda on Wed Mar 25 21:21:05 2020
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=b58be4ba-4998-44c5-9ae1-33eeace17be5 /                       ext4    defaults,noatime        1 1
UUID=085d7e3b-2a67-484c-8784-01ba35a85807 /boot                   ext4    defaults        1 2
/dev/sdb        /pool/storage02 ext4    defaults,noatime        1 2
/dev/sdc        /pool/storage03  ext4    defaults,noatime        1 2
/pool/storage0*  /storage  fuse.mergerfs  defaults,allow_other,use_ino 0 0

```
* [ ] Linux version: `uname -a`
```
[root@sd-79476 ~]# uname -a
Linux sd-79476 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@sd-79476 ~]#
```
* [ ] Versions of any additional software being used
None
* [ ] List of drives, filesystems, & sizes: `df -h`
```
[root@sd-79476 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /dev/shm
tmpfs            32G  9.2M   32G   1% /run
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/sda3       5.5T  1.9G  5.2T   1% /
/dev/sdb        5.5T  9.6G  5.2T   1% /pool/storage02
/dev/sdc        5.5T  1.4G  5.2T   1% /pool/storage03
/dev/sda2       488M  119M  334M  27% /boot
tmpfs           6.3G     0  6.3G   0% /run/user/0
tmpfs           6.3G     0  6.3G   0% /run/user/48
1:2:3:4          17T   13G   16T   1% /storage
[root@sd-79476 ~]#
```
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
The name of /storage is 1:2:3:4 meaning that you have /pool/storage01 and /pool/storage04 which aren't mounted and therefore on the root device.

```
/dev/sda3          5540G    2G     5258G   1% /
/dev/sdb           5545G   10G     5256G   1% /pool/storage02
/dev/sdc           5545G    2G     5264G   1% /pool/storage03
1:2:3:4           16628G   13G    15777G   1% /storage
```

Size: 5540 + 5545 + 5545 = 16630 which accounting for rounding ... 16628 looks fine.
Same with used and avail.
10+2+2 = ~13
5258 + 5256 + 5264 = ~15777

All those values look fine. Where is this 838G coming from?

**Comment by momkin** [comment]
Total storage of 3  disks is : 16628G 
And the available space is only 15777G

where is the rest of disk space go ?

**Comment by momkin** [comment]
> 
> 
> The name of /storage is 1:2:3:4 meaning that you have /pool/storage01 and /pool/storage04 which aren't mounted and therefore on the root device.
> 
> ```
> /dev/sda3          5540G    2G     5258G   1% /
> /dev/sdb           5545G   10G     5256G   1% /pool/storage02
> /dev/sdc           5545G    2G     5264G   1% /pool/storage03
> 1:2:3:4           16628G   13G    15777G   1% /storage
> ```
> 
> Size: 5540 + 5545 + 5545 = 16630 which accounting for rounding ... 16628 looks fine.
> Same with used and avail.
> 10+2+2 = ~13
> 5258 + 5256 + 5264 = ~15777
> 
> All those values look fine. Where is this 838G coming from?

Total storage of 3 disks is : 16628G
And the available space is only 15777G

where is the rest of disk space go ?

**Comment by trapexit** [comment]
What does this have to do with mergerfs? The numbers all line up as reported by the OS. I can't comment on your underlying filesystems.

**Comment by trapexit** [comment]
You're using ext4. Have you looked at the reserved capacity?

**Comment by momkin** [comment]
Sorry i didn't see the missing space from my system partitions i just saw the mergerfs disk used and i thought its a bug 👍

**Comment by trapexit** [comment]
It's simply ext4 reserved space. It's doing what you've configured it to be.

The default is 5%. 5% of 5540 is 277. 5540 - 277 = 5263. Looks right to me.

If you want to remove the reserve use tune2fs.
