### ISSUE TITLE
CentOS 8 Support

### ISSUE THREAD

**Issue by bfrye26** [trapexit/mergerfs#735]
Trying to see if any of the pre-built images would work on CentOS 8. I am looking to move over to that for my NAS (many reasons, but mainly trying to move away from Debian based distros to get better support for Podman etc). I see support for CentOS 6 and 7, but nothing for 8. Let me know your thoughts.

**Comment by trapexit** [comment]
You can build a package yourself with the instructions in the docs but here you go: https://github.com/trapexit/mergerfs/releases/download/2.29.0/mergerfs-2.29.0-1.el8.x86_64.rpm
