### ISSUE TITLE
mergerfs not mounting pool via /etc/fstab or CLI

### ISSUE THREAD

**Issue by nicklynberg** [trapexit/mergerfs#736]
General description
===================
`df -h` is not showing aggregate storage pool filesystem mounted by mergerfs.  Storage pool doesn't appear to be mounted.

Expected behavior
=================
I see 'mergerfs' Filesystem listed in output of `df -h` in addition to the /mnt/disk* filesystems.

Actual behavior
===============
I do not see 'mergerfs' filesystem/pool listed.

**Precise** steps to reproduce the behavior
===========================================
Add entries to `/etc/fstab` for 4 disks, and 1 for storage pool filesystem which will contain 3 of the disks as shown in below `/etc/fstab`.
Run `sudo mount -a` (no output).
Run `df -h` - observe no 'mergerfs' Filesystem shown.

Alternatively, I have also tried running `sudo mergerfs -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media/` directly.  The command produces no output and `mergerfs` filesystem is still not seen in `df -h`.

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: 
`mergerfs -V
mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31`

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
`# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/mint--vg-root /               ext4    errors=remount-ro 0       1
\# /boot/efi was on /dev/nvme0n1p1 during installation
UUID=3D99-E429  /boot/efi       vfat    umask=0077      0       1
/dev/mapper/mint--vg-swap_1 none            swap    sw              0       0

\#mergerfs config
/dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VDH49X4D-part1 /mnt/disk1 ext4 defaults 0 0
/dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VDH4644D-part1 /mnt/disk2 ext4 defaults 0 0
/dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VAJ0VB9L-part1 /mnt/disk3 ext4 defaults 0 0
/dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VAJ10ZYL-part1 /mnt/parity1 ext4 defaults 0 0

/mnt/disk* /mnt/media fuse.mergerfs defaults,use_ino,allow_other,fsname=mergerfs 0 0
`
AND/OR

`sudo mergerfs -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media/`

* [x] Linux version: `uname -a`
`$ uname -a
Linux nick-server 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
* [ ] Versions of any additional software being used
* [x] List of drives, filesystems, & sizes: `df -h`
>$ df -h
>Filesystem                 Size  Used Avail Use% Mounted on
>udev                       7.8G     0  7.8G   0% /dev
>tmpfs                      1.6G  1.7M  1.6G   1% /run
>/dev/mapper/mint--vg-root  457G  419G   15G  97% /
>tmpfs                      7.8G   12K  7.8G   1% /dev/shm
>tmpfs                      5.0M  4.0K  5.0M   1% /run/lock
>tmpfs                      7.8G     0  7.8G   0% /sys/fs/cgroup
>/dev/nvme0n1p1             511M  6.1M  505M   2% /boot/efi
>tmpfs                      1.6G   56K  1.6G   1% /run/user/1000
>/dev/sda1                  7.3T   93M  6.9T   1% /mnt/disk1
>/dev/sdb1                  7.3T   93M  6.9T   1% /mnt/disk2
>/dev/sdc1                  7.3T   93M  6.9T   1% /mnt/disk3
>/dev/sdd1                  7.3T   93M  6.9T   1% /mnt/parity1`

* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
n/a

* [x] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
Gathered via `sudo strace -f -o /tmp/mergerfs.strace.txt sudo mergerfs -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media/`, but the output is 2000 lines long.  Should I post it here anyways?  Is there a better way to gather this info?

**Comment by trapexit** [comment]
>  Should I post it here anyways?

Post a file.

>  Is there a better way to gather this info?

No.

There really isn't any info for me to go on above. Whats the return code of the cli? What's the trace say?

**Comment by nicklynberg** [comment]
Here is the output generated from when I ran `sudo strace -f -o /tmp/mergerfs.strace.txt sudo mergerfs -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media/`.
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/4432729/mergerfs.strace.txt)

>$ sudo mergerfs -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media/
>$ $?
>0: command not found

**Comment by trapexit** [comment]
`18608 mount("mergerfs", "/mnt/media", "fuse.mergerfs", MS_NOSUID|MS_NODEV, "allow_other,default_permissions,"...) = 0`

Shows mount is successful. Have you checked the process table? `pgrep -alf mergerfs`? Have you tried running it in the foreground `mergerfs -f ...`?

**Comment by nicklynberg** [comment]
`pgrep -alf mergerfs` prints no output.  Likewise `sudo mergerfs -f -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media/` prints no output as well.
>$ sudo mergerfs -f -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media/
>$ $?
>0: command not found
>$ pgrep -alf mergerfs
>$ $?
>1: command not found

**Comment by trapexit** [comment]
It's not supposed to print anything on success nor does running in the foreground. What does `-d` give you (debug mode)?

I don't know... I'm just working with the data I've seen. The mount call succeeded as shown above.

**Comment by nicklynberg** [comment]
Thanks for the quick replies.  Here is `-d` mode output.

```
$ sudo mergerfs -d -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media 
FUSE library version: 2.9.7-mergerfs_2.29.0
nullpath_ok: 1
nopath: 1
utime_omit_ok: 1
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.31
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.31
   flags=0x00448079
   max_readahead=0x00020000
   max_write=0x00100000
   max_background=0
   congestion_threshold=0
   max_pages=256
   unique: 2, success, outsize: 80
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 2719
getattr /
   unique: 4, success, outsize: 120
unique: 6, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 2719
LOOKUP /.Trash
getattr /.Trash
   unique: 6, error: -2 (No such file or directory), outsize: 16
unique: 8, opcode: LOOKUP (1), nodeid: 1, insize: 52, pid: 2719
LOOKUP /.Trash-1000
getattr /.Trash-1000
   unique: 8, error: -2 (No such file or directory), outsize: 16
unique: 10, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 19986
statfs /
   unique: 10, success, outsize: 96
```

**Comment by trapexit** [comment]
OK. Clearly it's working. What happens when you do something (ls, whatever) in /mnt/media?

**Comment by nicklynberg** [comment]
Commands in /mnt/media work as expected.  Is there a simple test I can do to verify the pool is working?  I would expect that if I `touch` a file in `/mnt/media` that I would see the file appear in one of the underlying drives as well (/mnt/disk1, /mnt/disk2, or /mnt/disk3), but this isn't the case.

**Comment by trapexit** [comment]
You are running mergerfs in debug mode... you'll see the commands being called streaming by if mergerfs is processing commands.

There are lots of ways. That's one of them. Clearly something is screwed up on your system. I can run `sudo mergerfs -d -o allow_other /home/<user> /tmp/test` and everything works as expected.

**Comment by nicklynberg** [comment]
The `mergerfs` process doesn't seem to be persisting after running it - sounds like it should be?

```
nick@nick-server:$ sudo mergerfs -d -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
nick@nick-server:/$ rm -rf /mnt/media/*
nick@nick-server:/$ sudo mergerfs -d -o allow_other,use_ino,fsname=mergerfs /mnt/disk\* /mnt/media
FUSE library version: 2.9.7-mergerfs_2.29.0
nullpath_ok: 1
nopath: 1
utime_omit_ok: 1
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.31
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.31
   flags=0x00448079
   max_readahead=0x00020000
   max_write=0x00100000
   max_background=0
   congestion_threshold=0
   max_pages=256
   unique: 2, success, outsize: 80
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 2719
getattr /
   unique: 4, success, outsize: 120
unique: 6, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 2719
LOOKUP /.Trash
getattr /.Trash
   unique: 6, error: -2 (No such file or directory), outsize: 16
unique: 8, opcode: LOOKUP (1), nodeid: 1, insize: 52, pid: 2719
LOOKUP /.Trash-1000
getattr /.Trash-1000
   unique: 8, error: -2 (No such file or directory), outsize: 16
unique: 10, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 19986
statfs /
   unique: 10, success, outsize: 96
nick@nick-server:/$ pgrep -alf mergerfs
nick@nick-server:/$
```

**Comment by nicklynberg** [comment]
Additional info: I tried running your `sudo mergerfs -d -o allow_other /home/<user> /tmp/test` command, and it worked!  Something odd about the directories I'm using - permissions possibly?

**Comment by nicklynberg** [comment]
Something is wrong with the `/mnt/media` folder, I don't know what.  When I try to run the same commands described herein but set the pool to exist at another folder (/mnt/mergerfs) everything works fine.  Thanks for your replies, closing this as the problem is somewhere on my end.
