### ISSUE TITLE
mergerfs meets massive performance downgrade

### ISSUE THREAD

**Issue by fockez** [trapexit/mergerfs#738]
I run mergerfs with latest Debian Testing with kernel 5.4. 
`Linux ches-disk0 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux`
It is on a Dell R730 server with 3 disk arrays. Each array is hard raid6 and have one zfs pool. Mergerfs combine them together. 
`/dpool/ches:/dpoola/ches:/dpoolb/ches   /mnt/data/ches  fuse.mergerfs   defaults,allow_other,use_ino,noforget,cache.files=off,minfreespace=100G,ignorepponrename=true,x-systemd.requires=zfs-mount.service        0       0`
I have 2 nodes with slurm, share the mergerfs disk from nfs
`/mnt/data/ches  *(rw,fsid=1,sync,no_subtree_check)`
`192.168.1.50:/mnt/data/ches     /mnt/share/     nfs`

Now, when meeting massive I/O, the mergerfs process take 200-400% cpu and the I/O jamed there for tens of minutes.

_Originally posted by @fockez in https://github.com/trapexit/mergerfs/issues/727#issuecomment-609465248_

**Comment by trapexit** [comment]
Why have you closed the ticket?

**Comment by fockez** [comment]
I am going to comment it, because I found nfs async helps, but need more test. So the issue description is not accuracy. Then I closed it in case during this time the issue misleading anyone else. Thanks.
