### ISSUE TITLE
Permission issues with Docker

### ISSUE THREAD

**Issue by uchagani** [trapexit/mergerfs#739]
General description
===================
I'm trying to run nextcloud with the data directory stored on a mergerfs pool.  When I start the container I get errors that the directory is not writable. `Can't create or write into the data directory /opt/nextcloud/data `

Additional Info:
- Mergerfs is running as root via `fstab`
- The directory on my mergerfs pool that I am trying to mount is `/mnt/storage/nextcloud`
- Nextcloud recommends not storing data in web root, as such I am switching the data directory to `/opt/nextcloud/data` in the container.
- I have tried the below steps to reproduce with the following scenarios:
  * Letting nextcloud create `/mnt/storage/nextcloud`
  * Creating `/mnt/storage/nextcloud` and running `sudo chown -R www-data:www-data /mnt/storage/nextcloud`
- I've forked the offical docker-compose files from nextcloud so the steps to reproduce are easier.  The only changes I've made are setting the appropriate environment variables and adding a mergerfs volume mount.

When allowing docker to create the directory the permissions are:

```
$ sudo ls -al /mnt/storage/nextcloud/
total 0
drwxr-xr-x 2 root root  6 Apr 18 00:02 .
drwxr-xr-x 3 root root 19 Mar 29 09:54 ..
```

The permissions inside the container for `/opt/nextcloud/data` is:

```
$ sudo docker exec -it nextcloud ls -al /opt/nextcloud/data
total 1
drwxr-xr-x    2 root     root             6 Apr 18 04:02 .
drwxr-xr-x    3 root     root             3 Apr 18 04:02 ..
```

When creating the directory beforehand and changing the owner to `www-data` the permissions are:

```
$ sudo ls -al /mnt/storage/nextcloud/
total 0
drwxr-xr-x 2 www-data www-data  6 Apr 18 00:14 .
drwxr-xr-x 4 root     root     48 Apr 18 00:14 ..
```

The permissions inside the container for /opt/nextcloud/data is:

```
$ sudo docker exec -it nextcloud ls -al /opt/nextcloud/data
total 1
drwxr-xr-x    2 xfs      xfs              6 Apr 18 04:14 .
drwxr-xr-x    3 root     root             3 Apr 18 04:15 ..
```

Expected behavior
=================
Directory is writable.

Actual behavior
===============
Directory is not writable.

**Precise** steps to reproduce the behavior
===========================================
1.  Clone/copy the files from https://github.com/uchagani/docker/tree/master/.examples/docker-compose/insecure/mariadb-cron-redis/fpm
4.  run `sudo docker-compose up --build -d`
5.  navigate to `{ipaddress:10800}`
6.  Enter any username/password for an admin account and click `Finish Setup`

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: 
```
mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```
* [x] mergerfs settings: 
```
/dev/disk/by-id/scsi-some-random-id-1-part1 /mnt/disk-1 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-2-part1 /mnt/disk-2 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-3-part1 /mnt/disk-3 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-4-part1 /mnt/disk-4 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-5-part1 /mnt/disk-5 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-6-part1 /mnt/disk-6 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-7-part1 /mnt/disk-7 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-8-part1 /mnt/disk-8 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-9-part1 /mnt/disk-9 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-10-part1 /mnt/disk-10 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-11-part1 /mnt/disk-11 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-12-part1 /mnt/disk-12 xfs defaults 0 0
/dev/disk/by-id/scsi-some-random-id-13-part1 /mnt/disk-13 xfs defaults 0 0


/mnt/disk* /mnt/storage fuse.mergerfs defaults,use_ino,noforget,cache.files=off,dropcacheonclose=true,allow_other,category.create=mfs,minfreespace=100G,fsname=mergerfs 0 0
```
* [x] Linux version: `Linux server 5.3.0-45-generic #37-Ubuntu SMP Thu Mar 26 20:41:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* [x] Versions of any additional software being used: docker
* [x] List of drives, filesystems, & sizes: 
```
Filesystem            Size  Used Avail Use% Mounted on
udev                   95G     0   95G   0% /dev
tmpfs                  19G  2.4M   19G   1% /run
/dev/sda1             275G  7.5G  253G   3% /
tmpfs                  95G     0   95G   0% /dev/shm
tmpfs                 5.0M     0  5.0M   0% /run/lock
tmpfs                  95G     0   95G   0% /sys/fs/cgroup
mergerfs              124T   16T  109T  13% /mnt/storage
/dev/sdt1              11T  724G   11T   7% /mnt/disk-1
/dev/sdo1             9.1T  9.4G  9.1T   1% /mnt/disk-2
/dev/sdn1             9.1T  9.4G  9.1T   1% /mnt/disk-3
/dev/sdj1              11T  710G   11T   7% /mnt/disk-4
/dev/sdk1             9.1T  3.6T  5.6T  39% /mnt/disk-5
/dev/sdm1             9.1T  3.6T  5.6T  39% /mnt/disk-6
/dev/sdq1             9.1T  2.7T  6.5T  30% /mnt/disk-7
/dev/sdu1              11T  723G   11T   7% /mnt/disk-8
/dev/sdl1             9.1T  9.4G  9.1T   1% /mnt/disk-9
/dev/sdi1             9.1T  9.4G  9.1T   1% /mnt/disk-10
/dev/sds1             9.1T  9.4G  9.1T   1% /mnt/disk-11
/dev/sdr1             9.1T  9.4G  9.1T   1% /mnt/disk-12
/dev/sdp1             9.1T  3.6T  5.6T  39% /mnt/disk-13
datapool/docker       806G  206M  806G   1% /var/lib/docker
datapool              806G  128K  806G   1% /datapool
datapool/docker-data  806G  227M  806G   1% /datapool/docker-data
tmpfs                  19G     0   19G   0% /run/user/1000
```
* [ ] strace of application having problem: I'm not sure how to get this while running docker
* [ ] strace of mergerfs while app tried to do it's thing: I'm not sure how to get this while running docker

**Comment by trapexit** [comment]
You have to ensure the permissions line up across any containers and the host for the filesystem permissions to work. Why do you think this is a mergerfs thing?

**Comment by uchagani** [comment]
when i put the data directory outside of the mergerfs pool I don't have permission issues.  I'm trying to line up the permissions by creating the directory and changing the owner to www-data but it still won't work.

**Comment by trapexit** [comment]
www-data doesn't mean anything. The uid:gid matter. What are the uid and gids involved?

**Comment by uchagani** [comment]
inside the container www-data's id's are 82.  locally the ids are 33.

**Comment by trapexit** [comment]
Right. So they aren't the same user.

**Comment by trapexit** [comment]
Why not just set the directory to be owned by root and sticky like /tmp?

**Comment by uchagani** [comment]
so if i'm understanding this correctly, i need to create `/mnt/storage/nextcloud` on the mergerfs pool, make the directory sticky, and then it should work?

**Comment by trapexit** [comment]
You need permissions to be correct. It's nothing to do with mergerfs. users and groups are just aliases to uid and gid. You have to have the match between the host and the container for things to work. If you make the directory like /tmp then anyone can create stuff like /tmp and whoever creates something owns it. You can do either.

**Comment by uchagani** [comment]
great i'll try this now.  thank you.

**Comment by uchagani** [comment]
so even with the user id and group id matching (but not the names) I still have the same permission issues:

```
$ ls -al /mnt/storage/nextcloud/
total 0
drwxr-xr-x 2 www-data www-data  6 Apr 18 01:03 .
drwxr-xr-x 4 root     root     48 Apr 18 01:03 ..

$ id -u www-data
33
$ id -g www-data
33

$ sudo docker exec -it nextcloud ls -al /opt/nextcloud/data
total 1
drwxr-xr-x    2 xfs      xfs              6 Apr 18 05:03 .
drwxr-xr-x    3 root     root             3 Apr 18 05:07 ..

$ sudo docker exec -it nextcloud id -u xfs
33
$ sudo docker exec -it nextcloud id -g xfs
33
```

**Comment by trapexit** [comment]
I really don't know what to tell you. Clearly there is something off about the setup but I simply don't have enough information to comment.

Have you tried going into the container runtime and poking around as that user?

`docker exec -it -u 33:33 nextcloud /bin/sh`

**Comment by uchagani** [comment]
ok this gives me something to work with i think.  thank you for your help.

**Comment by trapexit** [comment]
You really should setup a explicit uid you want to use for your containers. Not allow them to run as root unless you need to. That would mean explicitly setting the uid:gid. I generally use nobody (65534) or similar.

**Comment by uchagani** [comment]
Yea I need to see how to do that.  I think the nextcloud image requires that data is created via their www-data (82:82).  I'm thinking I create a user with 82:82 then change permissions to that user on my mergerfs pool directory.  Unless there is some other better way.

**Comment by trapexit** [comment]
That's why I was suggesting using sticky root owned directories. You don't have to worry about it.

**Comment by uchagani** [comment]
I didn't like the idea of anyone being able to create data in that directory but I think i'll try it now.

**Comment by trapexit** [comment]
Then you'll just need to set the uid correctly.
