### ISSUE TITLE
Unable to merge RO and RW folders

### ISSUE THREAD

**Issue by drelephant** [trapexit/mergerfs#740]
General description
===================
First, thanks very much for the useful software.

I would like to merge two folders
`/mnt/readonly` and `/mnt/writable` and mount them at `/mnt/pool`.

`/mnt/readonly` contains some folders which are mounted squashfs containers so all folders except the root of `/mnt/readonly` are not writable.

I do not want to edit files on `/mnt/readonly`, but I do want to be able to create matching new files inside the folder. For example, if there is a folder `/mnt/readonly/AAAA/`, then when I try to create the file `/mnt/pool/AAAA/testfile.txt`, I would like it to be written to `/mnt/writable/AAAA/testfile.txt`. Also I would like to later be able to edit `/mnt/pool/AAAA/testfile.txt` if needed.

I do not think I need copy on write because I am not planning to modify any of the files inside `/mnt/readonly`.

Actual behavior
===============
I have tried

> sudo mergerfs -o defaults,allow_other,use_ino,fsname=mergerfs /mnt/writable:/mnt/readonly=RO /mnt/pool/

,

> sudo mergerfs -o defaults,allow_other,use_ino,fsname=mergerfs /mnt/writable:/mnt/readonly=NC /mnt/pool/

, and

> sudo mergerfs -o defaults,allow_other,use_ino,fsname=mergerfs /mnt/readonly=RO:/mnt/writable /mnt/pool/

, but in all those cases, only files from `/mnt/writable` are visible in `/mnt/pool`.

If I do

> sudo mergerfs -o defaults,allow_other,use_ino,fsname=mergerfs /mnt/writable:/mnt/readonly /mnt/pool/

, the folders are merged and files in both folders show up in `/mnt/pool`, as expected. If I try to create a file inside `/mnt/pool/` root, then it is created in `/mnt/writable` as I want. Unfortunately I get a file creation error if I try to write to /mnt/pool/AAAA/testfile.txt.

How can I get it to merge two folders with only one of those folders being writable and the ability to have files and their parent folders created as needed to add files to the virtual folders? It seems to be ignoring any branches with `=RO`.

Thank you.

System information
==================
* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.23.0
FUSE library version: 2.9.7
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

* [ ] Linux version: `uname -a`
Linux 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by trapexit** [comment]
>I do not want to edit files on /mnt/readonly, but I do want to be able to create matching new files inside the folder.

That is explicitly *not* a feature of the product.

https://github.com/trapexit/mergerfs#how-it-works

> mergerfs does not support the copy-on-write (CoW) behavior found in aufs and overlayfs. You can not mount a read-only filesystem and write to it. However, mergerfs will ignore read-only drives when creating new files so you can mix read-write and read-only drives. It also does not split data across drives. It is not RAID0 / striping. It is simply a union.

Use overlayfs for that.

**Comment by trapexit** [comment]
Sorry, just woke up and misread your ticket.

You haven't set a policy. You're using the default which is path preserving. Don't do that.

**Comment by drelephant** [comment]
Thanks for the reply.

Could you please have a go at explaining why the RO drives aren't showing their files?

I've tried `sudo mergerfs -o category.search=epall,allow_other,use_ino,fsname=mergerfs /mnt/readonly=RO:/mnt/writable /mnt/pool/` and many others but I can't get any files inside an `=RO` branch to show.

Sorry, I just can't work it out...

**Comment by trapexit** [comment]
That's different from what you are talking about originally. Have you confirmed your permissions are setup correctly? As the docs say it's almost always that.

**Comment by drelephant** [comment]
I think so, because `sudo mergerfs -o defaults,allow_other,use_ino,fsname=mergerfs /mnt/readonly:/mnt/writable /mnt/pool/` does show files from both branches?

I think I have two problems.

1. branches mounted with `=RO` don't show any files, even though they do when not mounted RO.
2. creating matching files and their parent folders to the writable mount doesn't work (I suspect `category.create=all` might fix that).

Sorry for being dense.

**Comment by trapexit** [comment]
>mergerfs version: 2.23.0

You're using a version that is very old and doesn't support that feature.

**Comment by drelephant** [comment]
Which feature? `=RO`?

**Comment by trapexit** [comment]
Yes. Look at the man page. 2.23.0 came out in 2017. You can't use the docs from 2020 as a reference.

Just upgrade.

**Comment by drelephant** [comment]
Damn.

> sudo apt-get install mergerfs
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> mergerfs is already the newest version (2.23.0~ubuntu-xenial).
> 0 to upgrade, 0 to newly install, 0 to remove and 253 not to upgrade.

I'm not an expert and don't want to update and possibly break my fragile setup, is there an easy way to upgrade when I'm already using the "latest" package for my Ubuntu 16.04 "LTS" setup?

**Comment by drelephant** [comment]
Or alternatively, is there a way to achieve what I want to do using the current version? Like not actually mounting `/mnt/readonly` with `=RO`, but another way to make it only write files to the first listed branch?

**Comment by trapexit** [comment]
Debian is not a rolling release distro. It will never have the most up to date software.

There are packages prebuilt for major distros already: https://github.com/trapexit/mergerfs#build--update

Just use that.

**Comment by drelephant** [comment]
Thanks so much!!

I just installed the prebuilt 2.29 deb and got it all working perfectly with:

>sudo mergerfs -o category.search=all,category.create=all,allow_other,use_ino /mnt/readonly=RO:/mnt/writable /mnt/pool/

Once again, thanks for the great software and all your work.
