### ISSUE TITLE
Load balancing identical paths results in error

### ISSUE THREAD

**Issue by hacktek** [trapexit/mergerfs#742]
General description
===================

I'm trying to merge two identical fuse mounts and load balance between them using search policy rand(or eprand). When doing so and trying to crawl through the entire structure using find, I get an error and the amount of files do not match when comparing against either of the two fuse mounts.

This path does exist in both mounts as like I said, they're identical. I've verified that doing so results in less file output.

Fuse mount 1:

$ find /mnt/remote/Media/ ! -name '*.srt' | wc -l
49439

Fuse mount 2:

$ find /mnt/remote2/Media/ ! -name '*.srt' | wc -l
49439

Merged mount:

$ find /mnt/unionfs/Media/ ! -name '*.srt' | wc -l
find: failed to read file names from file system at or below ‘/mnt/unionfs/Media/’: No such file or directory
39852

Expected behavior
=================

Amount of files in merged mount point is the same as the amount of files in each individual fuse mount.

Actual behavior
===============

Receive the following error:

find: failed to read file names from file system at or below ‘/mnt/unionfs/Media/’: No such file or directory

**Precise** steps to reproduce the behavior
===========================================

1. Mount 2 fuse mounts (I'm using rclone to mount gdrive but I assume they're all the same).
2. find /path/to/mount1 | wc -l
3. find /path/to/mount2 | wc -l
4. find /path/to/merged/mount | wc -l

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`

mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31

* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments

/usr/bin/mergerfs \
  -o category.search=rand \
  -o category.create=ff,async_read=false,cache.files=partial \
  -o dropcacheonclose=true,use_ino,minfreespace=0 \
  -o xattr=nosys,statfs_ignore=ro,allow_other,umask=002,noatime \
  /mnt/local=RW:/mnt/remote=NC:/mnt/remote2=NC /mnt/unionfs

* [x] Linux version: `uname -a`

4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* [x] Versions of any additional software being used

rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

* [x] List of drives, filesystems, & sizes: `df -h`

Filesystem                        Size  Used Avail Use% Mounted on
udev                               32G     0   32G   0% /dev
tmpfs                             6.3G  1.3M  6.3G   1% /run
/dev/nvme0n1p3                    467G  112G  333G  26% /
tmpfs                              32G  8.0K   32G   1% /dev/shm
tmpfs                             5.0M     0  5.0M   0% /run/lock
tmpfs                              32G     0   32G   0% /sys/fs/cgroup
/dev/nvme0n1p2                    488M  140M  324M  31% /boot
local-pcs-remux:remote-pcs-remux  1.0P     0     0    - /mnt/pcs-remux
local-pcs:remote-pcs              1.1P  112G  333G  26% /mnt/pcs
google_pcs_remux:                 1.0P     0  1.0P   0% /mnt/remote-pcs-remux
google_pcs:Media                  1.0P     0  1.0P   0% /mnt/remote-pcs
/dev/nvme1n1p1                    469G   63G  406G  14% /mnt/disk2
/dev/sda1                         469G   64G  406G  14% /mnt/disk3
/dev/sdb1                         469G   64G  406G  14% /mnt/disk4
2:3:4                             1.4T  190G  1.2T  14% /mnt/storage
tmpfs                             6.3G     0  6.3G   0% /run/user/0
google:                           1.0P     0  1.0P   0% /mnt/remote
google2:                          1.0P     0  1.0P   0% /mnt/remote2
local:remote:remote2              2.1P  112G  333G  26% /mnt/unionfs

* [x] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`

https://drive.google.com/open?id=16AieW7MhrcROl3u1_B8PHD-UwUkeu4Ag

* [x] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

https://drive.google.com/open?id=16AieW7MhrcROl3u1_B8PHD-UwUkeu4Ag

**Comment by trapexit** [comment]
You're saying `eprand` does the same thing?

**Comment by hacktek** [comment]
Yeah both behave the same.

**Comment by trapexit** [comment]
If you use the same branch twice does it happen? Have you replicated this with local mounts?

**Comment by hacktek** [comment]
Mounted it like this:

```
/usr/bin/mergerfs -o category.search=eprand -o category.create=ff,async_read=false,cache.files=partial -o dropcacheonclose=true,use_ino,minfreespace=0 -o xattr=nosys,statfs_ignore=ro,allow_other,umask=002,noatime /mnt/local=RW:/mnt/remote=NC:/mnt/remote=NC /mnt/tmp
```

Was able to replicate but it took me two tries:

```
$ find /mnt/tmp/ ! -name '*.srt' | wc -l
49502
$ find /mnt/tmp/ ! -name '*.srt' | wc -l
find: failed to read file names from file system at or below ‘/mnt/tmp/’: No such file or directory
39895
```

I then tried the following with two local paths:

```
/usr/bin/mergerfs -o category.search=eprand -o category.create=ff,async_read=false,cache.files=partial -o dropcacheonclose=true,use_ino,minfreespace=0 -o xattr=nosys,statfs_ignore=ro,allow_other,umask=002,noatime /mnt/local=RW:/mnt/abc=NC:/mnt/def=NC /mnt/tmp
```

Same thing:

```
$ find /mnt/tmp/ | wc -l
find: failed to read file names from file system at or below ‘/mnt/tmp/’: No such file or directory
63345
```

If I remove the RW mount:

```
/usr/bin/mergerfs -o category.search=eprand -o category.create=ff,async_read=false,cache.files=partial -o dropcacheonclose=true,use_ino,minfreespace=0 -o xattr=nosys,statfs_ignore=ro,allow_other,umask=002,noatime /mnt/abc=NC:/mnt/def=NC /mnt/tmp
```

It works:

```
$ find /mnt/tmp/ | wc -l
12
```

So it looks like the local RW path (which does contain the Media folder but might not contain _every_ subfolder) is interfering.

**Comment by trapexit** [comment]
I think find is doing something really atypical. I need to read it's source code because there are no actual errors being generated. It's an app level error. Not filesystem.

**Comment by trapexit** [comment]
Yup. I'm still trying to understand the point of what it does but when changing directory to `..` it is comparing the device id and the inode of the path to see if it changed and returns that error. I'm not sure if that's totally legit... IE... I don't know if the value changing is actually invalid or they're just being careful.

I'll have to research more to comment further.

**Comment by trapexit** [comment]
You should be able to work around this though. Just set `func.open=rand` instead of the full category.

**Comment by hacktek** [comment]
I'll try that, thanks.

**Comment by trapexit** [comment]
BTW... whether or not you'd actually get a performance improvement depends on a few things but why are you using mergerfs for this when something like RAID1 would probably be better? 

Also, if your data is largely static you could use `symlinkify` with `readlink` set to random.

**Comment by hacktek** [comment]
Can't raid1 cloud storage ;)

When you say static data do you mean that any given single file doesn't change? If so it's certainly that way.

**Comment by trapexit** [comment]
Yes, a file that doesn't change.

https://github.com/trapexit/mergerfs#options

It turns files in mergerfs into symlinks to the underlying mount. Removing mergerfs from having to be a middleman for the reads. 

I've not tested it but I think you should be able to turn symlinkify on and then set readlink to rand.

It's probably not that big of a deal but a possible option.

**Comment by hacktek** [comment]
OK thanks, I'm trying func.open=rand and it appears to be working. Gonna test it out a bit more with real world usage. Thanks again.

**Comment by tenknas** [comment]
@hacktek want to know if you were able to use this reliably? Also what if one of the drives failed? ie one of the drives dismounts or reaches google API limits? Is there a way to have mergerfs to just look for another working file on another drive?

**Comment by trapexit** [comment]
> Is there a way to have mergerfs to just look for another working file on another drive?

How would it do that? When the API limit is hit google still shows the files as existing. It only fails on a read and as I understand there isn't a good way to even know it's a quota limit issues.

The only way to manage that would be to in effect ignore read errors and then look for another file to see if there is another with the same relative path. Could I do this? Yes. I'm not keen on doing it given it's a weird situation that's specific to this use case and arguably it would need to be applied to every single function.

**Comment by tenknas** [comment]
> > Is there a way to have mergerfs to just look for another working file on another drive?
> 
> How would it do that? When the API limit is hit google still shows the files as existing. It only fails on a read and as I understand there isn't a good way to even know it's a quota limit issues.
> 
> The only way to manage that would be to in effect ignore read errors and then look for another file to see if there is another with the same relative path. Could I do this? Yes. I'm not keen on doing it given it's a weird situation that's specific to this use case and arguably it would need to be applied to every single function.

I was hoping there was already a function like it. Would love to see it.

Instead of random tho, is there a way to rotate over the mounts one by one?

**Comment by trapexit** [comment]
It doesn't support it because it's a very niche thing. The idea that you would want to ignore errors which on a typical setup means bad drives or corrupted filesystem is just atypical. My fear is needing to add lots of extra code that few people use and increase the complexity. If it's just "On a read if it fails with certain errors it will walk through all drives and try the next branch if a file exists" then that's not bad. If you're asking for me to do that for everything... I'm not sure that's plausible. For writes especially.

**Comment by tenknas** [comment]
Yeah, I am just looking for a way to read and if it fails look for another one. Not much need for write. 

Btw, you reply so quick. Kudos mate. Appreciate the work you do here. Thank you.

**Comment by trapexit** [comment]
I have a patch I made some time ago to test the idea. I'm trying to put together a new release... I'll look to including it. May need some testers though.

**Comment by tenknas** [comment]
I volunteer! Thanks!

**Comment by trapexit** [comment]
You're being way too vague. Only you know what you need functionally.

**Comment by trapexit** [comment]
Addressed by inodecalc feature.
