### ISSUE TITLE
Ramdisk Issue, No Free Space

### ISSUE THREAD

**Issue by Artiume** [trapexit/mergerfs#743]
General description
===================
Trying to create a filesystem where the first few GB's are on a ramdisk then if the ramdisk is overfilled, it will overflow to the /dev/sda disk. 

Created the tmpfs as such.
`ramdisk /ramdisk tmpfs size=2500M,noatime,nodev,nosuid,noexec,nodiratime 0 0`

Nothing unusual with my mount options. my create is currently eplfs, but that was more for trying to force the usage of the ramdisk. I started with `ff` but it didn't seem to respect the ramdisk and after adjusting the options, that's when I discovered the 'No Free Space' issue. It felt similar to  https://github.com/trapexit/mergerfs/issues/443 but I'm using a mix of tmpfs and ext4 and the ext4 volume is behaving as expected. The Readme talks about using tmpfs, so I feel like this could be a Me issue.

```systemd
ExecStart=/usr/bin/mergerfs /ramdisk:/mnt/hdd /ramfs -o \
rw,allow_other,category.create=eplfs,dropcacheonclose=true,fsname=ramfs
```
I tried using various mount options such as use_ino, but no luck. 

Example of the error
```
pi@raspberrypi:/ramfs$ dd bs=1M count=56 if=/dev/zero of=/ramfs/testfile
dd: failed to open '/ramfs/testfile': No space left on device
```

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
```
pi@raspberrypi:/ramfs$ mergerfs -V
mergerfs version: 2.29.0-17-g831dba3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```
* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ ] Linux version: `uname -a` `
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
<details>

pi@raspberrypi:/ramfs$ cat /tmp/app.strace.txt

32442 execve("/bin/dd", ["dd", "bs=1M", "count=56", "if=/dev/zero", "of=/ramfs/testfile"], 0xbea3596c /* 45 vars */) = 0
32442 brk(NULL)                         = 0x9d1000
32442 uname({sysname="Linux", nodename="raspberrypi", ...}) = 0
32442 mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6fcd000
32442 access("/etc/ld.so.preload", R_OK) = 0
32442 openat(AT_FDCWD, "/etc/ld.so.preload", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
32442 fstat64(3, {st_mode=S_IFREG|0644, st_size=54, ...}) = 0
32442 mmap2(NULL, 54, PROT_READ|PROT_WRITE, MAP_PRIVATE, 3, 0) = 0xb6fcc000
32442 close(3)                          = 0
32442 readlink("/proc/self/exe", "/bin/dd", 4096) = 7
32442 openat(AT_FDCWD, "/usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
32442 read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\254\3\0\0004\0\0\0"..., 512) = 512
32442 _llseek(3, 16748, [16748], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
32442 _llseek(3, 16424, [16424], SEEK_SET) = 0
32442 read(3, "A,\0\0\0aeabi\0\1\"\0\0\0\0056\0\6\6\10\1\t\2\n\3\f\1\22\4\24"..., 45) = 45
32442 _llseek(3, 16748, [16748], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
32442 _llseek(3, 16424, [16424], SEEK_SET) = 0
32442 read(3, "A,\0\0\0aeabi\0\1\"\0\0\0\0056\0\6\6\10\1\t\2\n\3\f\1\22\4\24"..., 45) = 45
32442 _llseek(3, 16748, [16748], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
32442 _llseek(3, 16424, [16424], SEEK_SET) = 0
32442 read(3, "A,\0\0\0aeabi\0\1\"\0\0\0\0056\0\6\6\10\1\t\2\n\3\f\1\22\4\24"..., 45) = 45
32442 _llseek(3, 16748, [16748], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
32442 _llseek(3, 16424, [16424], SEEK_SET) = 0
32442 read(3, "A,\0\0\0aeabi\0\1\"\0\0\0\0056\0\6\6\10\1\t\2\n\3\f\1\22\4\24"..., 45) = 45
32442 _llseek(3, 16748, [16748], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
32442 _llseek(3, 16424, [16424], SEEK_SET) = 0
32442 read(3, "A,\0\0\0aeabi\0\1\"\0\0\0\0056\0\6\6\10\1\t\2\n\3\f\1\22\4\24"..., 45) = 45
32442 _llseek(3, 16748, [16748], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
32442 _llseek(3, 16424, [16424], SEEK_SET) = 0
32442 read(3, "A,\0\0\0aeabi\0\1\"\0\0\0\0056\0\6\6\10\1\t\2\n\3\f\1\22\4\24"..., 45) = 45
32442 fstat64(3, {st_mode=S_IFREG|0644, st_size=17708, ...}) = 0
32442 mmap2(NULL, 81964, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6f8a000
32442 mprotect(0xb6f8e000, 61440, PROT_NONE) = 0
32442 mmap2(0xb6f9d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0xb6f9d000
32442 close(3)                          = 0
32442 munmap(0xb6fcc000, 54)            = 0
32442 openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
32442 fstat64(3, {st_mode=S_IFREG|0644, st_size=100586, ...}) = 0
32442 mmap2(NULL, 100586, PROT_READ, MAP_PRIVATE, 3, 0) = 0xb6f71000
32442 close(3)                          = 0
32442 openat(AT_FDCWD, "/lib/arm-linux-gnueabihf/libc.so.6", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
32442 read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\300x\1\0004\0\0\0"..., 512) = 512
32442 _llseek(3, 1293204, [1293204], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2800) = 2800
32442 _llseek(3, 1289788, [1289788], SEEK_SET) = 0
32442 read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\23\1\24"..., 47) = 47
32442 _llseek(3, 1293204, [1293204], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2800) = 2800
32442 _llseek(3, 1289788, [1289788], SEEK_SET) = 0
32442 read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\23\1\24"..., 47) = 47
32442 _llseek(3, 1293204, [1293204], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2800) = 2800
32442 _llseek(3, 1289788, [1289788], SEEK_SET) = 0
32442 read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\23\1\24"..., 47) = 47
32442 _llseek(3, 1293204, [1293204], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2800) = 2800
32442 _llseek(3, 1289788, [1289788], SEEK_SET) = 0
32442 read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\23\1\24"..., 47) = 47
32442 _llseek(3, 1293204, [1293204], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2800) = 2800
32442 _llseek(3, 1289788, [1289788], SEEK_SET) = 0
32442 read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\23\1\24"..., 47) = 47
32442 _llseek(3, 1293204, [1293204], SEEK_SET) = 0
32442 read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2800) = 2800
32442 _llseek(3, 1289788, [1289788], SEEK_SET) = 0
32442 read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\23\1\24"..., 47) = 47
32442 fstat64(3, {st_mode=S_IFREG|0755, st_size=1296004, ...}) = 0
32442 mmap2(NULL, 1364764, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6e23000
32442 mprotect(0xb6f5b000, 65536, PROT_NONE) = 0
32442 mmap2(0xb6f6b000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x138000) = 0xb6f6b000
32442 mmap2(0xb6f6e000, 8988, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6f6e000
32442 close(3)                          = 0
32442 set_tls(0xb6fce170)               = 0
32442 mprotect(0xb6f6b000, 8192, PROT_READ) = 0
32442 mprotect(0xb6f9d000, 4096, PROT_READ) = 0
32442 mprotect(0x2e000, 4096, PROT_READ) = 0
32442 mprotect(0xb6fcf000, 4096, PROT_READ) = 0
32442 munmap(0xb6f71000, 100586)        = 0
32442 rt_sigaction(SIGINT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
32442 rt_sigaction(SIGUSR1, {sa_handler=0x13360, sa_mask=[INT USR1], sa_flags=SA_RESTORER, sa_restorer=0xb6e50120}, NULL, 8) =                                                           0
32442 rt_sigaction(SIGINT, {sa_handler=0x13350, sa_mask=[INT USR1], sa_flags=SA_RESTORER|SA_NODEFER|SA_RESETHAND, sa_restorer=0                                                          xb6e50120}, NULL, 8) = 0
32442 brk(NULL)                         = 0x9d1000
32442 brk(0x9f2000)                     = 0x9f2000
32442 openat(AT_FDCWD, "/usr/lib/locale/locale-archive", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
32442 fstat64(3, {st_mode=S_IFREG|0644, st_size=3031632, ...}) = 0
32442 mmap2(NULL, 2097152, PROT_READ, MAP_PRIVATE, 3, 0) = 0xb6c23000
32442 mmap2(NULL, 2596864, PROT_READ, MAP_PRIVATE, 3, 0x6b000) = 0xb69a9000
32442 close(3)                          = 0
32442 openat(AT_FDCWD, "/dev/zero", O_RDONLY|O_LARGEFILE) = 3
32442 dup2(3, 0)                        = 0
32442 close(3)                          = 0
32442 _llseek(0, 0, [0], SEEK_CUR)      = 0
32442 openat(AT_FDCWD, "/ramfs/testfile", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = -1 ENOSPC (No space left on device)
32442 openat(AT_FDCWD, "/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
32442 fstat64(3, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
32442 read(3, "# Locale name alias data base.\n#"..., 4096) = 2995
32442 read(3, "", 4096)                 = 0
32442 close(3)                          = 0
32442 openat(AT_FDCWD, "/usr/share/locale/en_US.UTF-8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directo                                                          ry)
32442 openat(AT_FDCWD, "/usr/share/locale/en_US.utf8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or director                                                          y)
32442 openat(AT_FDCWD, "/usr/share/locale/en_US/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en.UTF-8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en.utf8/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 write(2, "dd: ", 4)               = 4
32442 write(2, "failed to open '/ramfs/testfile'", 32) = 32
32442 openat(AT_FDCWD, "/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 openat(AT_FDCWD, "/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
32442 write(2, ": No space left on device", 25) = 25
32442 write(2, "\n", 1)                 = 1
32442 close(2)                          = 0
32442 exit_group(1)                     = ?
32442 +++ exited with 1 +++
</details>

**Comment by trapexit** [comment]
ramdisk /ramdisk tmpfs size=**2500M**,noatime,nodev,nosuid,noexec,nodiratime 0 0

https://github.com/trapexit/mergerfs#options

minfreespace=SIZE: The minimum space value used for creation policies. Understands 'K', 'M', and 'G' to represent kilobyte, megabyte, and gigabyte respectively. (default: **4G**)

**Comment by Artiume** [comment]
Makes sense, I forgot about the default min. I'll test it and get back to you

**Comment by Artiume** [comment]
yup, that was the issue. closing ticket
