### ISSUE TITLE
How to get mergerfs to move to next drive despite existing path

### ISSUE THREAD

**Issue by drelephant** [trapexit/mergerfs#745]
General description
===================
I think I'm not really understanding the different mount options....

Expected behavior
=================
When creating a file, I want to get mergerfs to use the existing path if it exists and has enough space, but otherwise move to the next drive that has enough space, create the parent folders and write the file there.

Actual behavior
===============
Mergerfs just returns a "not enough space" error.

**Precise** steps to reproduce the behavior
===========================================

`grep merger /etc/fstab`

> /media/data* /mnt/raid fuse.mergerfs **category.create=eplfs,moveonenospc=true**,defaults,allow_other,minfreespace=300G,func.getattr=newest,fsname=mergerfsPool 0 0

`df -h | grep /media/data`

> /dev/mapper/data1            3.7T  3.4T  256G  94% /media/data1
/dev/mapper/data2            3.7T  3.6T  3.8G 100% /media/data2
/dev/mapper/data3            3.7T  3.3T  300G  92% /media/data3
/dev/mapper/data4            3.7T  3.6T   36G 100% /media/data4
/dev/mapper/data5            3.7T  2.0T  1.7T  54% /media/data5

When I try to duplicate a file that resides on `/media/data3`, it returns a "no space on disk error". What I had hoped it would do is try the existing path (which doesn't have enough free space because it only has 300Gb free), then because of `moveonenospc=true` it would move on to a different drive that does have enough free space, create the parent folders, then put the file there.

How can I achieve what I want to do, ie retaining existing paths if possible but if out of space moving to a different branch?

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`

> mergerfs version: 2.29.0
> FUSE library version: 2.9.7-mergerfs_2.29.0
> fusermount version: 2.9.7-mergerfs_2.29.0
> using FUSE kernel interface version 7.31

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
* [ ] Linux version: `uname -a`
* [ ] Versions of any additional software being used
* [ ] List of drives, filesystems, & sizes: `df -h`
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
That's not how any policies work.

Have you read the docs on policies? And the suggestions and FAQ? I explicitly go over why that pattern isn't ideal.

Why do you want it to write to an existing *set* of paths else create a new one? How is that materially different from just not using path preservation? If it will transparently clone paths to new drives then over time it will end up looking the same as if you didn't use it at all. The reason path preservation is strict is because if you're using it you explicitly don't want files on other drives.

**Comment by trapexit** [comment]
`moveonenospc=true` is for "When enabled if a write fails with ENOSPC or EDQUOT". It has nothing to do with policy.

**Comment by drelephant** [comment]
I've tried to read the docs many times but I'm obviously missing something - there's a **lot** of docs to read there, and with sentences like "If failure with ENOENT run create policy", it's pretty impenetrable for someone without expertise about filesystem intricacies. Honestly, I tried. It was talking about renames when I'm talking about copying/creating.

What will happen if I don't set it to preserve paths? Just write any file to any disk? I suppose it doesn't matter too much in the end (as long as it warns if an existing file is there already if there is a conflict) but I do like the idea of _mostly_ having all files in one folder on the same disk if possible. You are correct though that if I do get what I asked for, I never really thought about that every time I try to add a file to a folder that is full on the destination disk it will just create a new folder on another disk, and eventually it will just be a mess of folders like I was trying to avoid.

Sorry, I don't know what ENOSPC or EDQUOT are or what that really means - I assume ENOSPC means no space left.

**Comment by drelephant** [comment]
I changed to `category.create=mfs`.

Thanks.

**Comment by trapexit** [comment]
>What will happen if I don't set it to preserve paths?

It won't filter drives based on existing paths.

>Just write any file to any disk?

Not *any* disk. It follows whatever the policy dictates.

>(as long as it warns if an existing file is there already if there is a conflict

Not sure what you mean by this. If a file already exists it shows up as such. The policy decides what file is selected.

>Sorry, I don't know what ENOSPC or EDQUOT are or what that really means - I assume ENOSPC means no space left.

They are standard errors in *nix. ENOSPC is about not having space and EDQUOT is a quota error.

**Comment by trapexit** [comment]
I'll try to go through the docs and add the "human readable" versions of some error codes.

**Comment by drelephant** [comment]
> Not sure what you mean by this. If a file already exists it shows up as such. The policy decides what file is selected.

I was just concerned that if you try to write a file with the same path as a file that is on a disk that isn't included in the search policy, it might not realize that it already exists because it's not checking all disks. Is that possible?

> I'll try to go through the docs and add the "human readable" versions of some error codes.

Thanks man. Once again, thanks for all your effort.

**Comment by trapexit** [comment]
Maybe, maybe if you had negative entry caching on and wrote a file out of band to the drives it would not know it's there. But that requires you to almost explicitly go out of your way to try to do that. Otherwise, no.

It always checks all disks when a file is looked for. As the docs say there are no special filters on search functions. You can't skip a search because the drive is full.

**Comment by drelephant** [comment]
Oh, that's great.

I don't know what negative entry caching is, but I never move files around on the drives directly so that won't be a problem.

Thanks again.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#entry--attribute-caching

negative entry caching is caching the fact a file doesn't exist.
