### ISSUE TITLE
Please add an FAQ entry for file clashes

### ISSUE THREAD

**Issue by leggewie** [trapexit/mergerfs#747]
Thank you for developing and maintaining mergerfs.  It certainly looks like a very interesting tool.

While evaluating mergerfs I looked for an answer to what happens on filename clashes and came up empty-handed.  I would think this might come up for others, too.

/mnt/pool1/file1.txt
/mnt/pool2/file1.txt

The two files have the same basename but are not identical.  What happens when /mnt/pool1 and /mnt/pool2 get merged as /mnt/merged?

**Comment by trapexit** [comment]
The policy determines what file is selected.

https://github.com/trapexit/mergerfs#how-it-works

> The file/s or directory/s acted on or presented through mergerfs are based on the policy chosen for that particular action. Read more about policies below.

https://github.com/trapexit/mergerfs#functions--policies--categories

**Comment by leggewie** [comment]
Wow, thank you for the very fast answer.

That's heavy stuff with lots of knobs to tweak.  I'm sure I misunderstood it or am I right to think I've just uncovered a bug?  Assuming default policy (action: epall, create: epmfs, search: ff) and pool1 being mounted "first" to the pool, but being RO, whereas pool2 is RW.  Actually, that's two bugs, one being very serious, including dataloss.  My understanding is that when I open /mnt/pool/file1.txt, I will get back the contents of /mnt/pool**1**/file1.txt.  So far, so good.  I now go ahead and make some changes, save the file and poof, whatever was in /mnt/pool**2**/file1.txt has just been destroyed.  I close the file.  Some time later, I reopen /mnt/pool/file1.txt, only to be served the outdated content at /mnt/pool**1**/file1.txt.

Where do I misunderstand the policy?

**Comment by trapexit** [comment]
It entirely depends on how the software works. You are talking way too high level. 

If software opened `pool1/file1.txt`, wrote the new file to a temp file, removed file1.txt or just renamed over it... then yes. You'd lose data. Because that's what you've set your policy to do. It's not a bug. `actions` are `epall` by default. An `unlink` on `file1.txt` would remove both with that policy.... that's intentional. That's not dataloss.

If the file is updated in place, which is more common, then the `pool2/file1.txt` is completely untouched.

**Comment by leggewie** [comment]
I'm not sure, I'm following you, especially the "If software opened"-bit.  I am here trying to understand how mergerfs would behave.  With the files and pool layout described above and /mnt/pool1/file1.txt containing 1 and /mnt/pool2/file1.txt containing 2, am I correct to assume the following happens:
- "nano /mnt/pool/file.txt" -> file contains 1
- change the file content to 3 and save -> /mnt/file2/file1.txt now contains 3
- redo "nano /mnt/pool/file.txt" -> file contains 1 again

**Comment by trapexit** [comment]
Again, you're talking too high level. "save file" is not a filesystem function. I don't know how nano behaves so I can't speak to it.

I'm not sure how else to explain it. It requires you to understand POSIX filesystem APIs. Each [function](https://github.com/trapexit/mergerfs#function--category-classifications) has a policy. What happens to the files depend on what the software calls. Everything is different.

You don't seem to understand how branch designations work. /mnt/pool1 is not read only. The branch is not considered for creates. That's not the same thing.

https://github.com/trapexit/mergerfs#branches

> RO will exclude those paths from create and action policies (just as a filesystem being mounted ro would).

It doesn't make files read only. It is a modifier for policies.

**Comment by trapexit** [comment]
>am I correct to assume the following happens

No. You're not correct. file1.txt is opened and *depending on how the software saves files* it will either write 3 to /mnt/pool1/file1.txt OR it could delete both files and replace them with a new single file on whatever branch the create policy would choose.
