### ISSUE TITLE
ls -la of nfs mount of exported mergerfs filesystem missing files

### ISSUE THREAD

**Issue by mtraves** [trapexit/mergerfs#752]
General description
===================
Using mergerfs with three physical disks, mounted at /app/data-1, /app-data-2, and /app-data3.
Created /app/mergerfs-1 which includes these three disks.
Created an nfs export of /app/mergerfs-1 to mount on other servers.

An "ls" on the local /app/mergerfs-1/[directory] reports all files in the directory (correct).  An "ls" on the three data drives of the same path (data-1, data-2, data-3) shows that files are split between data-2 and data-3 (correct).  

On a client who has mounted the exported /app/merrgerfs-1, an "ls" of the /app/mergerfs-1[directory] results in a partial listing of files. 

Expected behavior
=================
An "ls" on the NFS client of the servers' exported NFS filesystem should report all files.

Actual behavior
===============
Exporting this mergerfs via NFS to a client.  On the client, an "ls" of the mergerfs directory results in a partial list of files only.

**Precise** steps to reproduce the behavior
===========================================
**On server:**
Using this in /etc/fstab:
```
/app/data-* /app/mergerfs-1 fuse.mergerfs use_ino,cache.files=partial,dropcacheonclose=true,defaults,allow_other,func.getattr=newest,category.create=mfs,moveonenospc=true,minfreespace=50G,fsname=mergerfsPool 0 0
```
Export defined in /etc/exports:
```
/app/mergerfs-1 10.0.10.150(rw,fsid=1,sync,anonuid=1000,anongid=1000,no_subtree_check)
```
```
pi@rocky:~ $ ls /app/mergerfs-1/directory | wc -l
268
pi@rocky:~ $ ls /app/data-1/directory | wc -l
ls: cannot access '/app/data-1/directory': No such file or directory
0
pi@rocky:~ $ ls /app/data-2/directory | wc -l
127
pi@rocky:~ $ ls /app/data-3/directory | wc -l
141
```

**On client:**
Using nfs automount, with the following configuration:
```
/app/rocky-mergerfs-1 -fstype=nfs,rw,nosuid,proto=tcp,resvport 10.0.10.160:/app/mergerfs-1
```

```
mtraves@natasha:~/Projects/htpc$ ls /app/rocky-mergerfs-1/directory | wc -l
98
```

- I have rebooted both the server and client, and tried to adjust fstab options.
- I have downloaded and run the mergerfs.fsck against /app/mergerfs-1 - it exited without any output (no errors)
- I have looked at permissions (per the README as a common issue), however all drives and files have the same user, group, and permissions on the server, and I believe the NFS options address this anyways.

System information
==================
**On server:**
```
pi@rocky:~ $ uname -a
Linux rocky 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
```
```
pi@rocky:~ $ mergerfs -V
mergerfs version: 2.29.0-17-g831dba3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```
```
pi@rocky:~ $ cat /etc/fstab
proc            /proc           proc    defaults          0       0
PARTUUID=738a4d67-01  /boot           vfat    defaults          0       2
PARTUUID=738a4d67-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
# My external drives
UUID=7e8458ed-2e1e-4be0-bef7-c8d5e6e6f351 /app/data-1 ext4 defaults 0 2
UUID=2ab45c57-d8b5-4ca7-b0fc-3002366a0779 /app/data-2 ext4 defaults 0 2
UUID=80db57e5-eb52-4c82-a7fe-232c9c38bd0b /app/data-3 ext4 defaults 0 2
UUID=fc9b3460-f4f9-4d6e-be7c-4270668c1bf4 /app/parity-1 ext4 defaults 0 2
# MergedFS here (I hope)
/app/data-* /app/mergerfs-1 fuse.mergerfs use_ino,cache.files=partial,dropcacheonclose=true,defaults,allow_other,func.getattr=newest,category.create=mfs,moveonenospc=true,minfreespace=50G,fsname=mergerfsPool 0 0
```
```
pi@rocky:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        59G  2.3G   54G   5% /
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G   25M  2.0G   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   54M  199M  22% /boot
/dev/sdc1       7.3T  711G  6.6T  10% /app/parity-1
/dev/sdb1       7.3T  489G  6.8T   7% /app/data-3
/dev/sdd1       7.3T  489G  6.8T   7% /app/data-2
/dev/sda1       7.3T  711G  6.5T  10% /app/data-1
tmpfs           396M     0  396M   0% /run/user/1000
mergerfsPool     22T  1.7T   20T   8% /app/mergerfs-1
```
```
pi@rocky:~ $ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda           8:0    0  7.3T  0 disk
└─sda1        8:1    0  7.3T  0 part /app/data-1
sdb           8:16   0  7.3T  0 disk
└─sdb1        8:17   0  7.3T  0 part /app/data-3
sdc           8:32   0  7.3T  0 disk
└─sdc1        8:33   0  7.3T  0 part /app/parity-1
sdd           8:48   0  7.3T  0 disk
└─sdd1        8:49   0  7.3T  0 part /app/data-2
mmcblk0     179:0    0 59.5G  0 disk
├─mmcblk0p1 179:1    0  256M  0 part /boot
└─mmcblk0p2 179:2    0 59.2G  0 part /
```
```
pi@rocky:~ $ id
uid=1000(pi) gid=1000(pi) groups=1000(pi),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),105(input),109(netdev),995(docker),997(gpio),998(i2c),999(spi)
```

Also using snapraid with the three data-? and parity-1 drives.
```
pi@rocky:~ $ snapraid --version
snapraid v11.3 by Andrea Mazzoleni, http://www.snapraid.it
```

**On "client"**
```
user@natasha:~/Projects/htpc$ cat /etc/auto.media
app/rocky-mergerfs-1 -fstype=nfs,rw,nosuid,proto=tcp,resvport 10.0.10.160:/app/mergerfs-1
```
```
user@natasha:~/Projects/htpc$ uname -a
Linux natasha 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
user@natasha:~/Projects/htpc$ id
uid=1000(user) gid=1000(user) groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),108(lxd),666(media),999(docker)
```
```
root@natasha:~# df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                                16G     0   16G   0% /dev
tmpfs                              3.2G  1.6M  3.2G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   20G  3.2G   16G  17% /
tmpfs                               16G     0   16G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                               16G     0   16G   0% /sys/fs/cgroup
/dev/nvme0n1p2                     976M  145M  764M  16% /boot
/dev/nvme0n1p1                     511M  6.1M  505M   2% /boot/efi
/dev/mapper/ubuntu--vg-var--lv     9.8G  5.9G  3.5G  64% /var
/dev/mapper/ubuntu--vg-home--lv    8.9G  328M  8.1G   4% /home
/dev/mapper/ubuntu--vg-media       393G  116G  260G  31% /app/media
/dev/mapper/ubuntu--vg-datadir     393G   32G  344G   9% /app/datadir
/dev/loop0                          94M   94M     0 100% /snap/core/9066
/dev/loop1                          94M   94M     0 100% /snap/core/8935
tmpfs                              3.2G  4.0K  3.2G   1% /run/user/1000
overlay                            9.8G  5.9G  3.5G  64% /var/lib/docker/overlay2/e9f471a57bc9151775186c100ea4ec2177ca42cbec89aa7eaf92314ea46712d0/merged
shm                                 64M     0   64M   0% /var/lib/docker/containers/cd79924ab602d518fd0f808981324bb9f1a8b3e06db41f4c1d5afd79ecd413a9/mounts/shm
10.0.10.160:/app/mergerfs-1         22T  1.7T   20T   8% /app/rocky-mergerfs-1
```

A number of applications in containers are accessing this (and other) network share.  However, the problem occurs even when these containers are not in use, and just from the bash shell (as user or as root).

**Comment by trapexit** [comment]
>mergerfs version: 2.29.0-17-g831dba3

Have you tried a supported version?

**Comment by mtraves** [comment]
> > mergerfs version: 2.29.0-17-g831dba3
> 
> Have you tried a supported version?

Am I not?  Sorry, I thought I was using the latest version, downloaded from here. You mean rather than cloning and building, I should be using this?

mergerfs_2.29.0.debian-buster_armhf.deb

Assuming I were to do that, do I just reinstall on top of what I have (without breaking/losing anything)?

**Comment by trapexit** [comment]
No. You built from master which is work in progress. The releases page has the actual released versions. They are always tagged. If you want to build a package you should check out the version specifically and then build the package.

>Assuming I were to do that, do I just reinstall on top of what I have (without breaking/losing anything)?

Yes. It's the same as installing anything else. Why would it break or you lose anything? mergerfs doesn't store anything and the only settings are those you've set.

**Comment by mtraves** [comment]
Ah, now I recall.  It's because the specific version isn't available for my platform.  

I'm running raspbian-buster, and the latest version for raspbian listed is:
mergerfs_2.29.0.raspbian-jessie_armhf.deb

There's no listing for mergerfs_2.29.0.raspbian-buster_armhf.deb.

So I built it from Master.  

How would I obtain or build for raspbian-buster-armhf?

Hardware is a Raspberry Pi 4.

**Comment by mtraves** [comment]
Ok, so figured out how to build 2.29.0.  Sorry, new here.  ;-)

```
pi@rocky:~/mergerfs $ git status
On branch master
Your branch is up to date with 'origin/master'.
```

```
pi@rocky:~/mergerfs $ git checkout 10e8bd9fa307bef741182d33f9df004400a82d21
Note: checking out '10e8bd9fa307bef741182d33f9df004400a82d21'.
---
HEAD is now at 10e8bd9 Merge pull request #716 from trapexit/mount
```

```
pi@rocky:~/mergerfs $ sudo make clean
pi@rocky:~/mergerfs $ sudo make deb
```

```
pi@rocky:~ $ sudo dpkg -i mergerfs_2.29.0~raspbian-buster_armhf.deb
dpkg: warning: downgrading mergerfs from 2.29.0-17-g831dba3~raspbian-buster to 2.29.0~raspbian-buster
(Reading database ... 44867 files and directories currently installed.)
Preparing to unpack mergerfs_2.29.0~raspbian-buster_armhf.deb ...
Unpacking mergerfs (2.29.0~raspbian-buster) over (2.29.0-17-g831dba3~raspbian-buster) ...
Setting up mergerfs (2.29.0~raspbian-buster) ...
Processing triggers for man-db (2.8.5-2) ...
```

```
pi@rocky:~ $ mergerfs --version
mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```

**Comment by mtraves** [comment]
Moving back to 2.29.0 appears to have resolved the issue on initial testing. 

Thanks for pointing me in the right direction.  Appreciate the help.

**Comment by trapexit** [comment]
No problem. I put int some changes to the readdir code for linux to improve performance but it wasn't fully tested / worked out.

**Comment by trapexit** [comment]
>There's no listing for mergerfs_2.29.0.raspbian-buster_armhf.deb

Because raspbian is just debian. They don't even change the name in recent versions. The names of these files are automatically derived from the OS at build time.
