### ISSUE TITLE
Using mergerfs on debian (armv5) with samba results in crash

### ISSUE THREAD

**Issue by adriaanb** [trapexit/mergerfs#756]
General description
===================

Accessing a mergerfs filesystem via samba results in crashes after a few read/write accesses.

Expected behavior
=================

Reading and writing files to the mergerfs filesystem via samba should work consistently.

Actual behavior
===============

Reading and writing files to the mergerfs filesystem via samba results in a crash. Read access often works for a bit, write access causes a crash immediately. After a crash, looking up the permissions for the mounted devices results in a series of question marks for the mergerfs drive:

```
d????????? ? ?    ?       ?            ? storage
```
`ls -l`results in
```
ls: cannot access 'storage': Transport endpoint is not connected
```

**Precise** steps to reproduce the behavior
===========================================

- mergerfs is set up on Debian 10 (on an armv5 device).
The output of `uname -a ` is as follows:

```sh
Linux A3NAS 4.19.0-9-marvell #1 Debian 4.19.118-2 (2020-04-29) armv5tel GNU/Linux
```

- mergerfs setup:

```sh
sudo apt install mergerfs fuse
sudo mkdir /mnt/disk{1,2}
sudo mkdir /mnt/storage
```

- fstab content:

```
UUID=1f58878e-d27c-4fe0-a409-ae4473335703       /mnt/disk1      ext4    defaults                0       0
UUID=44711a1d-272e-4935-a96a-151533b16abf       /mnt/disk2      ext4    defaults                0       0

/mnt/disk*     /mnt/storage     fuse.mergerfs direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs 0 0
```
- samba share config:

```
[NetworkStorage]
comment = Personal Storage
path = /mnt/storage
browseable = yes
read only = no
guest ok = no
valid users = myuser
```

followed by

```
sudo systemctl restart smbd
sudo smbpasswd -a myuser
```

If I now access the share either from Finder in Mac OS X Catalina or from Windows 10, I can read files on the share with mixed results. Sometimes the filesystem remains accessible for a few minutes, sometimes it crashes immediately. When trying to write to it it crashes immediately.
If I point the samba share directly to one of the two ext4 drives, the share remains stable and i can read and write successfully.

System information
==================

* [x] mergerfs version: 
```
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.9
using FUSE kernel interface version 7.19
```
* [x] mergerfs settings: 
```
UUID=1f58878e-d27c-4fe0-a409-ae4473335703	/mnt/disk1      ext4    defaults                0       0
UUID=44711a1d-272e-4935-a96a-151533b16abf       /mnt/disk2      ext4    defaults                0       0

/mnt/disk*     /mnt/storage     fuse.mergerfs direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs 0 0
```
* [x] Linux version:
```
Linux A3NAS 4.19.0-9-marvell #1 Debian 4.19.118-2 (2020-04-29) armv5tel GNU/Linux
```
* [x] Versions of any additional software being used
```
Samba version 4.9.5-Debian
```
* [x] List of drives, filesystems, & sizes:
```
Filesystem      Size  Used Avail Use% Mounted on
udev            120M     0  120M   0% /dev
tmpfs            25M  2.3M   23M  10% /run
/dev/sdc2        29G  905M   26G   4% /
tmpfs           125M     0  125M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           125M     0  125M   0% /sys/fs/cgroup
/dev/sdc1       236M  9.8M  214M   5% /boot
tmpfs            25M     0   25M   0% /run/user/1000
/dev/sda1       2.7T  1.2G  2.6T   1% /mnt/disk1
/dev/sdb1       2.7T   89M  2.6T   1% /mnt/disk2
mergerfs        5.4T  1.3G  5.1T   1% /mnt/storage
```
* [x] strace of application having problem: 
[smb.strace.5010.txt](https://www.icloud.com/iclouddrive/04etWoJFhSy0p_n4s_NYD-Ddw#smb.strace)
* [x] strace of mergerfs while app tried to do it's thing: 
[mergerfs.strace.5055.txt](https://www.icloud.com/iclouddrive/0I_LVEralqMniukxGcJnFmUKQ#mergerfs.strace)

**Comment by trapexit** [comment]
> mergerfs version: 2.24.2

That version is from Mar 24, 2018. Please use the current release and confirm there is a problem in it before we investigate further.

**Comment by adriaanb** [comment]
Sorry for missing that the version from the repositories was this old. Indeed, with the latest version I am not experiencing the issue, merely the issue relating to moving files and directories with Samba on Mac OS X 10.9 and up described in the readme. Thank you for the quick response!

**Comment by trapexit** [comment]
> moving files and directories with Samba on Mac OS X 10.9 and up described in the readme

If you stop using a path preserving policy it should work. Sad they still haven't fixed that.

**Comment by adriaanb** [comment]
I managed to get it working, that you very much!
