### ISSUE TITLE
nfs mount point mtime changed nfs client got nfs file stale error 

### ISSUE THREAD

**Issue by swimfish09** [trapexit/mergerfs#759]
General description
===================

```
mergerfs /test1/assets:/test2/assets /test/assets -o rw,umask=0000,allow_other,use_ino,noforget,category.action=eplus,category.create=eplus,category.search=newest,func.utimens=ff,dev,suid
```
when mergerfs start，path /test1/assets mtime is newer than /test2/assets 
if i touch a file through /test/assets，then /test2/assets mtime is newer than /test1/assets

nfs client will got nfs file stale error.

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
```
mergerfs -V
mergerfs version: 2.28.1-6-g52e4d60
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.2
using FUSE kernel interface version 7.29
```
* [x] Linux version: `uname -a`
```
uname -a
Linux store001 5.4.3-1.el7.elrepo.x86_64 #1 SMP Fri Dec 13 07:27:20 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by trapexit** [comment]
This is a consequence of how NFS and FUSE interact and the fact you're changing the file from underneath mergerfs and therefore NFS.

Stop using use_ino and it might work fine but you'll naturally lose the ability to see if files have the same inode. I've toyed with making directories have different calculations for inodes compared to files... perhaps that'd help.

**Comment by swimfish09** [comment]
i tried 2.29.0, the same

**Comment by trapexit** [comment]
Yes. There are no material differences between those versions regarding this. Again, changing files out of band of NFS won't ever go well. It really shouldn't be done.

**Comment by swimfish09** [comment]
maybe mount point should be special treated

**Comment by trapexit** [comment]
What do you mean?

**Comment by swimfish09** [comment]
only choose the first path

**Comment by trapexit** [comment]
I don't understand what you mean. You have set the policy to be newest. You're changing the mtime. It's choosing the file to report you asked it to. The inode changes behind NFS. That is a problem.

**Comment by trapexit** [comment]
Calculation of inodes is tricky. As I said you can stop using use_ino and that may address it but it will impact any software relying on inodes to match linked files. Changing things to treat directories and files differently would be required but you could still have this problem when you do something that impacts the file's identity behind NFS.

**Comment by swimfish09** [comment]
how can i use user.mergerfs.basepath ?  i can not see the attr via attr -l

**Comment by trapexit** [comment]
Just query for it. It's hidden.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#file--directory-xattrs

"While they won't show up when using listxattr mergerfs offers a number of special xattrs to query information about the files served. "

**Comment by swimfish09** [comment]
Whether it can be set and kepp it not to be changed

**Comment by trapexit** [comment]
No. You can't set it. Why would you be able to set readonly values?

**Comment by swimfish09** [comment]
When mergerfs under heavy read and write pressure, Will nfs client get nfs file stale error ?
Now some of my nfs client will, not all of it.

**Comment by trapexit** [comment]
It's not related to the read/write amount. It's related to the fact that underlying information is changed out of band.

**Comment by swimfish09** [comment]
If underlying information is changed out of band, why not all of it got nfs file stale error

**Comment by trapexit** [comment]
Because it depends on the situation. Has it been seen before? Was it cached? For how long? Etc.

**Comment by swimfish09** [comment]
not seen before, just under heavy presure. If cached,after some time all of client will get nfs error.
Actually, others still good.

**Comment by trapexit** [comment]
Define "heavy pressure." In the original post you said the backend was changing. Whether that's because of your policy or out of band changes. 

You have category.search=newest. Have you tried changing that to one that won't be returning a different dir? Or stopped using use_ino to check?

If you must use newest for getattr... I'm looking at a new inode calculation that should help where NFS is used with possibly changing inodes. Particularly on dirs.

**Comment by swimfish09** [comment]
The machine's upstream and downstream bandwidth is almost used up

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/tree/inode-calc#inodecalc

If you're able you can try building this branch and testing the new `inodecalc` option with argument `path-hash`. You'll lose ability to see that files are the same by their inode value but I don't see an alternative.

Also, if you would, let me know if the docs read OK for the option.

**Comment by swimfish09** [comment]
ok, i will try the new code later.

**Comment by swimfish09** [comment]
I have used `inodecalc` option with argument `path-hash`, if i changed a file out of band, from nfs client i cannot see the change.

**Comment by trapexit** [comment]
I'm not sure what you mean. Change in what?

**Comment by trapexit** [comment]
You said you were having stale handle errors. You seem to be talking about something different.

**Comment by swimfish09** [comment]
Yes， i was having  stale handle errors. Change means append string to a file out of band, and then i cannot see the change.

**Comment by swimfish09** [comment]
use `inodecalc` option with argument `path-hash`, stale handle errors disappeared.

**Comment by trapexit** [comment]
I don't know what to tell you about not seeing changes. Works fine for me. What are all your settings?

**Comment by swimfish09** [comment]
mergerfs
``./mergerfs /yuanli-test/t/assets:/cache-test/to/assets /test/t/assets -o inodecalc=path-hash,rw,umask=0000,allow_other,use_ino,noforget,category.action=eplus,category.create=eplus,category.search=newest,func.utimens=ff,dev,suid
``

nfs exports
``/test/t/assets *(rw,sync,insecure,no_root_squash,fsid=d00a76e9-8cd7-42df-8f68-18a898ed7886)
``
nfs client
``mount -t nfs 192.168.199.138://test/t/assets/ /mnt/test/t/assets/
``

**Comment by trapexit** [comment]
Why are you using category.action=eplus? You realize that will result in those actions only working on a single file / directory?

**Comment by trapexit** [comment]
Regardless, everything works as expected with those settings on my setup.

**Comment by swimfish09** [comment]
repeat 
``
echo "1234" > /cache-test/to/assets/test.txt
``
and 
``
cat  /mnt/test/t/assets/test.txt
``

**Comment by trapexit** [comment]
Curiously it works for a time and then stops after a bit of time. mergerfs isn't even requested data when that is happening. It's client side caching. NFS doesn't even ask any information of the server. If I drop caches on the client it gets the data fine.

As the docs mention your mileage will vary if you do things out of band due to caching. There is no good way for mergerfs to know something changed out of band and invalidate the local cache (which may help NFS server force an invalidate to the client, not sure). Why are you changing files from behind mergerfs? And again: why are you using category.action=eplus and func.utimens=ff? That too could lead to confusion.

**Comment by trapexit** [comment]
This is a separate thing regardless. If you agree the stale handles due to inodes is addressed this should be closed.

**Comment by swimfish09** [comment]
fine

**Comment by swimfish09** [comment]
using category.action=eplus and func.utimens=ff? because of nfs file stale error,now i can only use  category.action=eplus

**Comment by trapexit** [comment]
But why eplus? That's really odd. Any actions on overlapping dirs/files will only happen to the file on the lus path. If you rmdir an empty dir in mergerfs and there are more than 1 you'll continue to see that dir.

**Comment by swimfish09** [comment]
just business needs

**Comment by trapexit** [comment]
OK. Just making sure you understood the consequences. 

As for out of band stuff... we can create a new ticket but I'm really not sure there is any good way to solve the issue. The best I can come up with would be to use inotify to watch any directory seen and if a file in it changes invalidate the whole file when the file is closed (on modify would be too much). It'd be somewhat complicated to implement. That's assuming the invalidation works for this. I will need to do more testing to see.

**Comment by swimfish09** [comment]
https://sourceforge.net/p/fuse/mailman/message/29443313/

**Comment by trapexit** [comment]
So it's not addressed?

No. It's not that. unionfs and mergerfs are completely different products.

If you're using the path-hash inode algo then it will always use the same value for inodes.

**Comment by trapexit** [comment]
Have you tried changing the caching values? Either by turning caching off or making them very large?

Without being able to reproduce this I'm shooting in the dark.

**Comment by swimfish09** [comment]
> So it's not addressed?
> 
> No. It's not that. unionfs and mergerfs are completely different products.
> 
> If you're using the path-hash inode algo then it will always use the same value for inodes.
Use master code some file can not display.

**Comment by trapexit** [comment]
I'm sorry but I don't really follow what you're saying. Are files literally not showing up or are you getting stale handle errors? Or both?

**Comment by swimfish09** [comment]
Yes, use master some files  literally not showing up, with no stale handle errors.

**Comment by swimfish09** [comment]
> I'm sorry but I don't really follow what you're saying. Are files literally not showing up or are you getting stale handle errors? Or both?

Using the path-hash inode algo has a problem，if i start up not just one mergerfs process, the root path will has a same ino number because of relative path hashing algorithm.

**Comment by trapexit** [comment]
Problem how? You're far too vague.
