### ISSUE TITLE
"fatal error: 'mntent.h' file not found" building 2.29.0 on FreeBSD

### ISSUE THREAD

**Issue by zofrex** [trapexit/mergerfs#761]
General description
===================

Attempting to compile 2.29.0 on FreeBSD fails with a compile error. Compiling 2.28.3 (and other earlier versions) succeeds.

This seems to be because `mergerfs-mount` is now built by default when you do `gmake build` or `gmake install`, where it wasn't in previous versions. Building it in previous versions exhibits the same error, for example `gmake -C libfuse build/mergerfs-mount` in version 2.28.3 also fails the same way.

If I remove `mergerfs-mount` from the Makefile, I do seem to end up with a working mergerfs install (although I only briefly tested this). What is it, and how essential is it?

Expected behavior
=================

Compilation succeeds and results in a working mergerfs binary.

Actual behavior
===============

```
cc -O2  -Wall -pipe -MMD -Iinclude -Ibuild -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=29 -DPACKAGE_VERSION=\"2.9.7-mergerfs_2.29.0\" -DFUSERMOUNT_DIR=\"/usr/local/bin\" -o build/mount.mergerfs util/mount.mergerfs.c build/libfuse.a -lrt -pthread
cc -O2  -Wall -pipe -MMD -Iinclude -Ibuild -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=29 -DPACKAGE_VERSION=\"2.9.7-mergerfs_2.29.0\" -DFUSERMOUNT_DIR=\"/usr/local/bin\" -Ilib -o build/mergerfs-fusermount util/fusermount.c lib/mount_util.c
util/fusermount.c:24:10: fatal error: 'mntent.h' file not found
#include <mntent.h>
         ^~~~~~~~~~
1 error generated.
lib/mount_util.c:21:10: fatal error: 'mntent.h' file not found
#include <mntent.h>
         ^~~~~~~~~~
1 error generated.
gmake[1]: *** [Makefile:75: build/mergerfs-fusermount] Error 1
gmake[1]: Leaving directory '/usr/home/vagrant/mergerfs-2.29.0/libfuse'
gmake: *** [Makefile:233: libfuse] Error 2
```

**Precise** steps to reproduce the behavior
===========================================

On a fresh install of FreeBSD 12.1 I:

* downloaded and extracted the release tarball, `mergerfs-2.29.0.tar.gz`.
* `sudo ./tools/install-build-pkgs`
* `gmake`

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: 2.29.0
* [x] mergerfs settings: N/A
* [x] Linux version: FreeBSD vagrant 12.1-RELEASE-p5 FreeBSD 12.1-RELEASE-p5 GENERIC  amd64
* [x] Versions of any additional software being used:
 * GNU Make 4.2.1
 * gcc (FreeBSD Ports Collection) 9.3.0
* [x] List of drives, filesystems, & sizes: N/A
* [x] strace of application having problem: N/A
* [x] strace of mergerfs while app tried to do it's thing: N/A

**Comment by trapexit** [comment]
It is rebranded fusermount. Intended eventually to limit the need for host tooling.

It's not essential as the moment and would be optional regardless.

**Comment by zofrex** [comment]
What are your thoughts on a fix here? The options I've thought of so far:

- Make it optional for all OSes (like it was before)
- Make it optional only on FreeBSD
- Change the code so it compiles on FreeBSD as well

I'm happy to take a shot at fixing this, but I don't have any insight into which way is the best way forward.

**Comment by trapexit** [comment]
It might just be build system issue. If I understand correctly libfuse builds on FreeBSD. In which case it might be something simple. If not then can disable it for now.

**Comment by zofrex** [comment]
FYI if compilation is fixed the Makefile will need a little touching up for FreeBSD as well - there's use of `install -D` which won't work, and the chown root:root will fail as there's no group named "root". I can roll a patch for those if that's the path you're going down.

**Comment by trapexit** [comment]
#789
