### ISSUE TITLE
rtorrent halts and becomes unkillable with page caching disabled in FreeBSD 12.1

### ISSUE THREAD

**Issue by zofrex** [trapexit/mergerfs#764]
General description
===================

Depending on mergerfs mount options, rtorrent can get "stuck" (locks up and is unkillable) when writing to a mergerfs mount in FreeBSD 12.1.

It may be notable that the [release notes for FreeBSD 12.1](https://www.freebsd.org/releases/12.1R/relnotes.html) mention:

> The fusefs(5) driver has been overhauled, implementing new features and performance improvements.

I have not seen this issue on FreeBSD 10 or 11 in many years of use, and I have not been able to reproduce it on 12.0 (latest patch version) in my limited testing so far. I can reproduce it on 12.1 release and the latest patch version of 12.1, so I believe it is new to FreeBSD 12.1.

Expected behavior
=================

Writing to a mergerfs mount in rtorrent functions similarly to writing to any other drive. Writing to the rootfs on the same machine is successful, for example.

Alternatively: writing to a mergerfs mount in rtorrent with incompatible options set causes an error or a crash rather than locking up.

Actual behavior
===============

Under FreeBSD 12.1, with the options "direct_io" or "cache.files=off" set, rtorrent will completely lock up writing to the mount. If you run:

    top -p `pgrep rtorrent`

The status will show as "vmopar" and not change (sometimes, rarely, it shows as "fuse" instead). Killing the process will have no effect. `kill -9` has no effect, even from root. The system will also get stuck on shutdown. Other attempts to access the mergerfs mount will also lock up.

I saw in the README that the recommended options for mergerfs + rtorrent these days are:

    use_ino,cache.files=partial,dropcacheonclose=true,allow_other,category.create=mfs

With these options, everything seems to work fine.

Using my original settings but with cache.files=partial instead of direct_io also works fine.

I know it says in the README to not use the options that I was with rtorrent:

> you lose shared mmap support which can affect apps such as rtorrent

but I'm still raising this for a few reasons:

* It didn't use to happen - I've used mergerfs heavily on several versions of FreeBSD 10 and 11 without issue and I'm confident this is new.
* I want to be sure there isn't some other issue here, and that if I change the cache.files option it will be stable. For example perhaps there's a random crash that becomes more likely with this option, but could still exhibit less frequently under other circumstances. Or perhaps it's a sign that there's some other incompatibility between mergerfs and the FreeBSD FUSE system. I mention this because [FreeBSD has significantly reworked FUSE](https://www.freebsd.org/releases/12.1R/relnotes.html), so perhaps they have introduced a new bug, or the new interface isn't 100% compatible with the old one.
* Even if this option is incompatible with rtorrent, I think a more graceful failure mode would be desirable, as this prevents even a clean shutdown of the system. For example an error or even crashing rtorrent would be preferable.
* It isn't clear to me from this sentence in the README what the expected impact to rtorrent is. Will it be slow? Crash? Or is this kind of lock-up expected? If combining this option with rtorrent is expected to have such severe consequences, I think that deserves a mention in the README.

Workarounds & non-impacted behaviour
================================

I have a workaround on my system which is to point rtorrent directly at the underlying drives rather than writing through mergerfs, which is a mild inconvenience but not a showstopper.

It does appear to work ok with cache.files=partial, but given the severity of the issue I want to confirm this is fully avoiding the issue and not merely reducing the probability of it occurring.

Reading from the mergerfs mount has exhibited no problems in over a week of operation, so I do believe only writing is affected.

In my limited testing, writing to the mount through other means than rtorrent also seems to be unaffected.

**Precise** steps to reproduce the behavior
===========================================

* Install FreeBSD 12.1
* Download, compile and install mergerfs
* `kldload fuse`
* Create a mergerfs mount with the direct_io/cache.files=off option (for simplicity I made one from 3 folders on the rootfs, it doesn't need to be on separate drives to exhibit the problem)
* Install rtorrent from pkg
* Start up rtorrent and load a torrent, and set its location to somewhere on the mergerfs mount. For ease of testing I've been using [an Ubuntu torrent](https://releases.ubuntu.com/20.04/ubuntu-20.04-desktop-amd64.iso.torrent)
* rtorrent should lock up or crash within a couple of minutes.

If you use Vagrant I could create a Vagrant box for you that's set up and ready to crash.

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: mergerfs version: 2.29.0-dirty
FUSE library version: 2.9.7-mergerfs_2.29.0
mount_fusefs [fuse4bsd] version: 0.3.9-pre1
using FUSE kernel interface version 7.31

* [x] mergerfs settings: sudo mergerfs -o allow_other,direct_io,use_ino,func.getattr=newest /mnt/\* /data
* [x] FreeBSD version:
 * FreeBSD vagrant 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64
 * FreeBSD vagrant 12.1-RELEASE-p5 FreeBSD 12.1-RELEASE-p5 GENERIC  amd64
* [x] Versions of any additional software being used: rtorrent-0.9.8
* [x] List of drives, filesystems, & sizes:
    Filesystem      Size    Used   Avail Capacity  Mounted on
    /dev/ada0s1a     91G    3.1G     81G     4%    /
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

I haven't managed to get a trace yet of what rtorrent is doing when this happens, I will update later if I manage to do so.

**Comment by trapexit** [comment]
Is mergerfs still working or blocked?

If the kernel changed then it's very likely to be something there or some incompatibility they introduced.

rtorrent uses mmap. Exclusively. No fallback. mmap is an optional feature of a filesystem. Common but optional. On Linux FUSE mmap doesn't work with direct_io=true/cache.files=off. It just returns an error. rtorrent just gets that error and fails to work since it won't fallback to using reads/writes like typical software.

It could be unkillable for a few reasons. If mergerfs is stuck then so too will rtorrent. Regardless of if it's due to a bug in the kernel or mergerfs. Can't know without a lot more information.

>I want to be sure there isn't some other issue here, and that if I change the cache.files option it will be stable.

NO options should impact stability. It's a bug. Mostly likely due to the massive reworking of FUSE on FreeBSD.

>Even if this option is incompatible with rtorrent, I think a more graceful failure mode would be desirable, as this prevents even a clean shutdown of the system. For example an error or even crashing rtorrent would be preferable.

It does fail gracefully. On a non-buggy platform. rtorrent received an error just like any other.

>It isn't clear to me from this sentence in the README what the expected impact to rtorrent is.

As I said above rtorrent requires mmap to work. When it doesn't it just gets an error. How it affects that app is not something I can talk about as many apps use or can use mmap and I can't audit them all.

>If combining this option with rtorrent is expected to have such severe consequences, I think that deserves a mention in the README.

I agree... but that's not the case. Clearly something is broken with the new setup. This isn't normal. Thousands of people use rtorrent on linux with mergerfs.

>It does appear to work ok with cache.files=partial, but given the severity of the issue I want to confirm this is fully avoiding the issue and not merely reducing the probability of it occurring.

It should only work with direct_io=false. It's pretty explicit about that in the docs. Unless FreeBSD was supporting mmap when direct_io=true.

**Comment by zofrex** [comment]
> Is mergerfs still working or blocked?

I'm not 100% certain what you mean by this. The mountpoint seems to still work... to an extent:

```
vagrant@vagrant:~ % ls /data
foo				ubuntu-20.04-desktop-amd64.iso
vagrant@vagrant:~ % cat /data/foo
vagrant@vagrant:~ % ls -l /data
```

At this point (running the `ls -l`) the shell hangs too. After this, I cannot even `ls` the directory from a new shell. I haven't tested a lot of things to see what works/what doesn't as it takes quite a lot of time each time, but if there are specific things I can test that will be helpful to know please let me know!

> Regardless of if it's due to a bug in the kernel or mergerfs. Can't know without a lot more information.

What information do you need?

> Mostly likely due to the massive reworking of FUSE on FreeBSD.

My biggest worry right now is that there might be other, less obvious, issues from FreeBSD's massive & quiet reworking of FUSE.

> Unless FreeBSD was supporting mmap when direct_io=true.

I suppose it must have been? I've been using mergerfs+rtorrent like this for a good half a year+ and I've not had issues like this until I upgraded to FreeBSD 12.1.

I'd like to help any way I can so please let me know if there's any information I can gather or tests I can run.

**Comment by trapexit** [comment]
mergerfs has to take locks on FreeBSD to perform certain actions because it doesn't work like Linux. If you're running mergerfs as root that's especially true. There are a number of reasons that clients could block. Unless you want to learn the ins and outs of FreeBSD FUSE and mergerfs it's not going to be much use you digging into it. Even if you knew it wouldn't necessarily help me as I'd still need to dig into the details.

I'll just have to try setting this all up myself.

**Comment by zofrex** [comment]
OK, well I appreciate you looking into it. Do let me know if you need a hand setting things up, that's one thing I can do at least, as I've set this all up from scratch 7 different ways to test all these scenarios!

**Comment by trapexit** [comment]
1) If mergerfs is killed when things are broken the kernel seems not to return errors to the clients. Seems like a bug. I've never seen this behavior on Linux. I would need to test again but when direct_io=false it seemed fine.
2) I created a simple app to mmap and read or read/write a file. The read works fine. The read/write fails after it tried to flush changes/close the file. Trying to further use the mount worked OK for a command or two and then blocked. I checked the mergerfs stack trace and it was waiting in the kernel to send another message so it doesn't appear to be mergerfs itself blocking.

**Comment by trapexit** [comment]
I've confirmed this happens with sshfs as well. Seems like a kernel bug. I'm submitting a ticket with FreeBSD.

**Comment by trapexit** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247276

**Comment by zofrex** [comment]
Given this was confirmed as a FreeBSD bug in that thread, I think this issue can be closed? I don't think there's any reason to believe there's an issue with mergerfs itself?

Also, thank you so much for creating the reduced test case and reporting it to FreeBSD! Looks like that has resulted in a patch, which is fantastic. Thank you!

**Comment by trapexit** [comment]
np. 

I was leaving it open in case anyone else ran into issues but it looks like the fix is being upstreamed.
