### ISSUE TITLE
Question: Full Drive new File 

### ISSUE THREAD

**Issue by Treverr** [trapexit/mergerfs#769]
What happens when I have the default settings on with a drive that is full? Will Mergerfs make a new folder on the second non-full drive and put the files there? For example, I have drive 1 / tv shows / tv show 1 and then drive 2 / tv shows / * if drive 1 becomes full what happens if I try to add files to tv show 1?

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#filters

No. As it describes in the docs:

>If all branches are filtered an error will be returned. Typically EROFS (read-only filesystem) or ENOSPC (no space left on device) depending on the reasons.

If it created new paths it wouldn't be preserving paths.

**Comment by Treverr** [comment]
Gotcha- I’m using sonar here so the issue I run into is when one drive fills up I can’t import new episodes. I was hoping there was a way that it would create a second path the fed into the same path.

I.e 

I have my first path

_/Volumes/Media/TV Shows/Game of Thrones_

And once Media becomes full, it creates 

_/Volumes/Media 2/TV Shows/Game of Thrones_

And then it feeds them into

_/Volumes/All Media/TV Shows/Game of Thrones_

Is that possible anyway? Or this only will help to create new path on the non-filled drive?

Thanks!

**Comment by trapexit** [comment]
Yes, by using a non-path preserving policy.

**Comment by Treverr** [comment]
So id need to use a policy such as ifs, correct? 

What happens when Sonarr/Radarr tries to upgrade a file that goes over the free space minimum? For example say I have a file that's 1GB and I replace it with a 20GB file with the drive that has 10GB free space? 

Would it fail with not enough free space still? Or would it filter the file because the move is too large for the drive?

**Comment by trapexit** [comment]
>So id need to use a policy such as ifs, correct?

ifs?

>What happens when Sonarr/Radarr tries to upgrade a file that goes over the free space minimum? For example say I have a file that's 1GB and I replace it with a 20GB file with the drive that has 10GB free space?

It depends on how that software works. There are multiple ways to replace a file. I don't know how those apps work in that regard.

>Would it fail with not enough free space still? Or would it filter the file because the move is too large for the drive?

There is no such thing as "move". Files are opened, created, written, read, etc. mergerfs doesn't know how much data is going to be copied. That's not how things work. If Sonarr is doing a copy and writes directly to the destination file that's different from if it wrote to a temp file and renamed, which is different from hardlinking directly, which is different from hardlinking and renaming. Without knowing exactly what the software is doing I can't comment on what would happen. That said: for each of them the info is in the docs.

**Comment by Treverr** [comment]
> ifs?

Sorry, autocorrect got me there. Meant LFS

> It depends on how that software works. There are multiple ways to replace a file. I don't know how those apps work in that regard.

Fair enough, I can search and find out the logic here on my own


> There is no such thing as "move". Files are opened, created, written, read, etc. mergerfs doesn't know how much data is going to be copied. That's not how things work. If Sonarr is doing a copy and writes directly to the destination file that's different from if it wrote to a temp file and renamed, which is different from hardlinking directly, which is different from hardlinking and renaming. Without knowing exactly what the software is doing I can't comment on what would happen. That said: for each of them the info is in the docs.

I'll re-read through and see if I can find the answer I'm looking for.

Thank you!

**Comment by trapexit** [comment]
>Sorry, autocorrect got me there. Meant LFS
Any non-path preserving policy will do.

>I'll re-read through and see if I can find the answer I'm looking for.

The worse case situation would be for it to overwrite the file in place. In which case you just follow the logic.

1. open file for write (so it follows the open policy which doesn't include filtering by space (because it's irrelevant))
2. truncate file
3. start writing file
4. runs out of space and a write returns ENOSPC
5. mergerfs will react depending on the moveonenospc option.
