### ISSUE TITLE
local storage & rclone > mergerfs > nfs - consistent fileid change issues

### ISSUE THREAD

**Issue by delize** [trapexit/mergerfs#770]
General description
===================

I have been having consistent issues with NFS and mergerfs, and I am fairly confident I have followed the outlined guides on NFS, I still have issues. 

Expected behavior
=================

fsid value shouldn't change since manually specified. 

Actual behavior
===============

fsid changes on mergerfs file system, causing outages and errors and syslog reports errors like so:
```
/var/log/syslog.2.gz:Jun 19 06:17:46 apollo kernel: [62739.182378] NFS: server nas.localnet error: fileid changed
/var/log/syslog.2.gz:Jun 19 06:17:46 apollo kernel: [62739.182378] fsid 0:54: expected fileid 0x35000044e4, got 0x3500000081
/var/log/syslog.5.gz:Jun 16 14:24:42 apollo kernel: [152541.777246] fsid 0:52: expected fileid 0x3d00000001, got 0x3c00000001
/var/log/syslog.5.gz:Jun 16 14:24:42 apollo kernel: [152541.778390] NFS: server nas.localnet error: fileid changed
/var/log/syslog.5.gz:Jun 16 14:24:42 apollo kernel: [152541.778390] fsid 0:52: expected fileid 0x3d00000001, got 0x3c00000001
/var/log/syslog.5.gz:Jun 16 14:31:25 apollo kernel: [152945.056839] NFS: server nas.localnet error: fileid changed
/var/log/syslog.5.gz:Jun 16 14:31:25 apollo kernel: [152945.056839] fsid 0:52: expected fileid 0x3d00000001, got 0x8006b
/var/log/syslog.5.gz:Jun 16 14:31:25 apollo kernel: [152945.058544] NFS: server nas.localnet error: fileid changed
/var/log/syslog.5.gz:Jun 16 14:31:25 apollo kernel: [152945.058544] fsid 0:52: expected fileid 0x3d00000001, got 0x8006b
/var/log/syslog.5.gz:Jun 16 14:31:25 apollo kernel: [152945.154746] NFS: server nas.localnet error: fileid changed
...
/var/log/syslog.7.gz:Jun 14 10:27:29 apollo kernel: [ 8299.217240] fsid 0:53: expected fileid 0x35000000a1, got 0x446bae7f5b44da53
/var/log/syslog.7.gz:Jun 14 10:27:29 apollo multipathd[818]: sdc: add missing path
```

**Precise** steps to reproduce the behavior
===========================================

> Explicitly list **all** steps to reproduce. Preferably create a minimal example of the problem using standard command line tools. The more variables (apps, settings, etc.) that are involved the more difficult it is to debug. Also, **please** be sure to have read all of the README. It contains a lot of information regarding known system and user issues.

1. Mount local nas drives, and rclone remote drives into mergerfs
2. Share the mergerfs mount point over NFS
```
$ cat /etc/exports | tail -n 4
/mnt/pool/downloads 192.168.2.0/24(rw,sync,crossmnt,no_subtree_check)
/mnt/pool/media 192.168.2.0/24(rw,sync,crossmnt,no_subtree_check)
/mnt/pool/storage 192.168.2.0/24(rw,sync,crossmnt,no_subtree_check)
/mnt/mergerfs/media 192.168.2.0/24(rw,sync,crossmnt,no_subtree_check,fsid=4)
```
3. On Client, mount nfs point with the following fstab line
`nas.localnet:/mnt/mergerfs/media /mnt/nas/mergerfs-media nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800	0	0`
4. Run plex
5. Wait ~12 to 24 hours
6. NFS shows errors above

System information
==================
Please provide as much of the following information as possible:

* [X] mergerfs version: `mergerfs -V`
```
$ mergerfs -V
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29
```
* [X] mergerfs settings: `cat /etc/fstab` or the command line arguments
I am not using fstab, but I am mounting it dynamically through systemd due to rclone
```
$ cat /etc/systemd/system/mergerfs-gmedia.service
[Unit]
Description=gmedia mergerfs mount
Requires=rclone-gmedia.service
After=rclone-gmedia.service
RequiresMountsFor=/mnt/rclone

[Service]
Type=forking
ExecStart=/usr/bin/mergerfs /mnt/pool/media/:/mnt/rclone/gmusic/:/mnt/rclone/gebooks/:/mnt/rclone/gmedia /mnt/mergerfs/media -o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,noforget,nonempty,dropcacheonclose=true
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
* [X] Linux version: `uname -a`
`Linux nas 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* [X] Versions of any additional software being used
```
$ rclone version
rclone v1.52.1
- os/arch: linux/amd64
- go version: go1.14.4
$ dpkg -l | grep -i nfs
ii  libnfsidmap2:amd64                   0.25-5.1ubuntu1                       amd64        NFS idmapping library
ii  nfs-common                           1:1.3.4-2.5ubuntu3                    amd64        NFS support files common to client and server
ii  nfs-kernel-server                    1:1.3.4-2.5ubuntu3                    amd64        support for NFS kernel server
```

* [X] List of drives, filesystems, & sizes: `df -h`
```
Filesystem                                             Size  Used Avail Use% Mounted on
gdriveebooks-crypt:                                    1.0P     0  1.0P   0% /mnt/rclone/gebooks/eBooks
gdriveelearning:                                       1.0P     0  1.0P   0% /mnt/rclone/gelearning
gdrivemusic-crypt:                                     1.0P     0  1.0P   0% /mnt/rclone/gmusic/Music
gmedia:                                                1.0P     0  1.0P   0% /mnt/rclone/gmedia
pool                                                   6.8T  256K  6.8T   1% /mnt/pool
pool/downloads                                          12T  4.3T  6.8T  39% /mnt/pool/downloads
pool/media                                             7.7T  876G  6.8T  12% /mnt/pool/media
pool/media:rclone/gmusic:rclone/gebooks:rclone/gmedia  1.1P  891G  1.1P   1% /mnt/mergerfs/media
pool/storage                                            17T  9.3T  6.8T  58% /mnt/pool/storage
```
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

I will need to come back to you on the last two

**Comment by trapexit** [comment]
mergerfs has no control over the fsid. The fileid error is something all together different. It implies that a file's identity has changed out of band. Likely the inode changed. Are you moving files from local to remote storage and then removing them locally? You're using "newest" for getattr so if a directory gets updated it will naturally, given the way it currently works, report a different inode. 

This isn't trivial to address. mergerfs could try to use entirely static inode values based on the path but that would break hard links for files. Could only do the static inode for directories rather than files but then there is still a risk of issue when for example you transfer the file to cloud storage and remove the local copy. mergerfs won't know that happened. It could perhaps try to keep records of every single file it ever sees and reuse the inode value but that means a lot more record keeping and therefore more memory usage.

NFS can't work with things changing out of band. mergerfs and rclone and them together are nothing but chances of out of band changes.

**Comment by delize** [comment]
I do have tools changing and moving files around, but, those should be being passed directly through mergerfs to the underlying file system:
```
"Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/pool/storage/docker/config/sonarr",
                "Destination": "/config",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/pool/downloads",
                "Destination": "/downloads",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/mergerfs/media/TV Shows",
                "Destination": "/media",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```
For instance Sonarr. 

Is there a better attribute to use in this case?

**Comment by trapexit** [comment]
>I do have tools changing and moving files around, but, those should be being passed directly through mergerfs to the underlying file system:

But you have rclone in the mix. Are you not doing out of band transfers of data from local to remote? Also you're using newest policy for getattr which is, given the current inode calculation routine, going to make directory inodes change when files get updated.

>Is there a better attribute to use in this case?

Attribute? Options? At the moment using ff would minimize the inode change problem but not stop it necessarily. You'd have to do full scans for Plex or whatnot as a result though. I've never had a problem doing that but some people prefer not to.

> re SMB

Really? I've not heard that from others. Or are you using 10Gbps NICs?

I'm fooling around with different ideas for limiting inode change but it's not there today. There are really only two situations where it's been an issue. NFS in certain setups and workloads and find when using rand for getattr (doesn't like having the directory inode change when the tree is walked).

**Comment by delize** [comment]
> > I do have tools changing and moving files around, but, those should be being passed directly through mergerfs to the underlying file system:
> 
> But you have rclone in the mix. Are you not doing out of band transfers of data from local to remote? Also you're using newest policy for getattr which is, given the current inode calculation routine, going to make directory inodes change when files get updated.

Ah, yes, sorry I didn't think about the backups - was thinking about running services. Yes, I have rclone move files fro the /mnt/pool/media/* to the relevant rclone mount.

> > Is there a better attribute to use in this case?
> 
> Attribute? Options? At the moment using ff would minimize the inode change problem but not stop it necessarily. You'd have to do full scans for Plex or whatnot as a result though. I've never had a problem doing that but some people prefer not to.

Sounds good, I will try and mess around with this and see if any of those work better. I don't mind doing full scans, but my library is quite extensive (30TB). So scans can take a while - I would have to rely on push notifications on new series/movies potentially. That shouldn't be a problem as long as mergerfs still has the file listed I think.

> > re SMB
> 
> Really? I've not heard that from others. Or are you using 10Gbps NICs?

No, using 1Gbps NICs, but experiencing buffering which I didn't experience over NFS. In addition, some shows, seasons or episodes fail to load even though they loaded earlier in the day. It's quite erratic behavior. It used to be instant loads of profiles, but, now it can possibly take several seconds (up to 1 minute at times).
 
> I'm fooling around with different ideas for limiting inode change but it's not there today. There are really only two situations where it's been an issue. NFS in certain setups and workloads and find when using rand for getattr (doesn't like having the directory inode change when the tree is walked). The tricky part is getting unique inodes that don't change unnecessarily _and_ can respect files that share the same dev & inode.

**Comment by trapexit** [comment]
> SMB

Curious. I don't use Samba much but for casual transfers but a lot of users use Samba with mergerfs without any (publicly disclosed) issues. I actually tend to use sshfs when I need some general remote filesystem access and by turning off compression and changing the encryption algo you can get decent enough speeds for my purposes. Sometimes I wonder if spending some time on trying to build a simple remote filesystem that is just "good enough" might be worth the effort.

In any case... I'm fooling around with something at the moment. If you're up to test it I can ping you when I have something.

**Comment by delize** [comment]
Yeah, I would be happy to test something if I have the time and have an existing setup.

It took ~2 minutes to load a Dirk Gently show that is on local disks (not on rclone) being proxyed through mergerfs right now. Then it buffered, two seconds in. 

I am guessing the ultimate problem there is more of just SMB tuning that share specifically or the client itself. Not entirely sure yet (haven't really investigated, as I made the switch yesterday night).

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/tree/inode-calc#inodecalc

If you're able you can try building this branch and testing the new `inodecalc` option with argument `path-hash`. You'll lose ability to see that files are the same by their inode value but I don't see an alternative.

Also, if you would, let me know if the docs read OK for the option.

**Comment by trapexit** [comment]
I've merged it into master. Will be in the next release that I'll probably drop in the next day or two.

**Comment by delize** [comment]
Coming around to this now, but I don't see the tree, unless it was removed after the pull.

Will go and find the docs and read up on it.

**Comment by trapexit** [comment]
Yes, the branch is deleted after I merge it.

**Comment by delize** [comment]
Trying this now, I installed version 2.9.0 of the focal package, and receive the following 

```
$ sudo /usr/bin/mergerfs /mnt/pool/media/:/mnt/rclone/gmusic/:/mnt/rclone/gebooks/:/mnt/rclone/gmedia /mnt/mergerfs/media -o rw,async_read=false,use_ino,allow_other,func.g
etattr=newest,category.action=all,category.create=ff,cache.files=partial,noforget,nonempty,dropcacheonclose=true,inodecalc=path-hash
fuse: unknown option `inodecalc=path-hash'
```

Which according to the doc, is correct, right?

**Comment by trapexit** [comment]
2.9.0? You mean 2.29.0? No, that was the last release. I've yet to release a version with that feature.
