### ISSUE TITLE
Question: Total Free/Used Space Policy vs Percentages

### ISSUE THREAD

**Issue by undaunt** [trapexit/mergerfs#773]
Just a question around the current mfs, lfs, lus policies (and their path preserving counterparts). Do these policies all work off values, or percentages? It appears they work off actual numbers of bytes of free space, whereas mergerfs-balance works off percentages.

Use case: I have 3 12TB drives and 1 8TB drive for holding content. Using the policy of epmfs, in which all four disks have the same top level folder "movies", movies are only being sent to the 3 12TB disks until there is approximately 4TB used and all four disks have 8TB free, then movies begin also appearing in the 8TB disk as part of the epmfs policy.

However, if I were to run a mergerfs-balance on the movies folder, afterwards all disks would be within (by default) 2% usage of each other, instead of let's say 5TB, 5TB, 5TB, and 1TB filled, (which 41% vs 12.5% each filled) they would also be at around 36% each filled, irrespective of total capacity. (Or at least, that's how it appears right now, I've had a multi-TB balance running for the last 12 hours.)

Thanks for any clarification. I'm trying to align my path preserving creation policies with the behavior of balance to be able to quickly rebalance data as I add additional drives, instead of having all net-new data flow to the brand new drive until it hits par. If there is a better way to do that, I'm open to whatever is best.

Thank you.

**Comment by trapexit** [comment]
They are all bytes based. They are listed as "free space" not "percentage free". The tools are entirely separate things. It does percentages because that's what someone asked for and because you need some end state. It reuses the percentage calculation for both the end state and target drive. That's easily changed but no one has cared.

The balance script does *NOT* follow path preservation. If you use it with a system that has path preservation it will screw things up.

May I ask why you want to use path preservation?

**Comment by undaunt** [comment]
Hey, of course. I had previously bugged you on Discord around this (dwtp#6793) but basically I am storing static content (media, in-progress home VHS rips, etc.) on disk1, disk2, disk3, as part of the mergerfs mount. On those disks I've pre-created parent folders such as media, VHS, downloads, etc. for path preservation.

This content is being calculated for parity with snapraid.

I am also mounting a subfolder of a ZFS mirrored pool, /mnt/zfs/fuse, into the mergerfs pool to store docker configs, logs, a Plex database, etc. and other more variable content that is not going into snapraid.

I want to provide a single point to share out via NFS and Samba. I also want my downloads parent folder to report only the proper free space to apps, not including the ZFS disk, to prevent ENOSPC, so I'm including statfs=full. Here is the mount I've settled on:

`/mnt/disk*:/mnt/zfs/fuse /mnt/storage fuse.mergerfs allow_other,minfreespace=50G,use_ino,statfs=full,dropcacheonclose=true,threads=8,fsname=storage,category.action=epall,category.create=epmfs,func.mkdir=epall,func.getattr=newest,cache.files=partial,noforget,x-systemd.requires-mounts-for=/mnt/disk1,x-systemd.requires-mounts-for=/mnt/disk2,x-systemd.requires-mounts-for=/mnt/disk3 0 0`

To deal with the fact that balance doesn't leverage path preservation, I've created a second mount that excludes the zfs disk and am running balance against that.

**Comment by trapexit** [comment]
Ah, right. Remember now. The balance script can be updated to have the ability to do some of those things as I mentioned. Making it work with limited directories would probably require a bigger change since you need a concrete end condition whereas today it just keeps looking for files till the percentage gap closes which requires less code.

**Comment by undaunt** [comment]
I think being able to exclude one of the disks from being a target would be sufficient for not having to create a separate mount just for running balance.

Related, is it possible to make balance also balance against "total amount of free space" and default to say, some amount of gigabytes, and then specify a different amount if desired similar to the percentage functionality? Also, should I move this to the mergerfs-tools issues page?

Thank you.

**Comment by trapexit** [comment]
Yes, please do. But the ending condition needs to be articulated as well unless you're saying that the percentage one is fine.

**Comment by undaunt** [comment]
Moving to the proper repo.
