### ISSUE TITLE
Any way to prioritize between merged drives?

### ISSUE THREAD

**Issue by ambipur76** [trapexit/mergerfs#785]
General description
===================

When merging driveA and driveB, their parameters, like write speed or being able to ask the remaining space on them may be different or differently implemented. Therefore it would be useful to be able to tell mergerfs which of the drives shall be filled up firstly.

Expected behavior
=================

If driveA and driveB are merged e.g. with command mergerfs -o allow_other,use_ino /mnt/driveA*:/mnt/driveB /media/drives it would be useful to be sure that driveA or drive B will be choosen if both of them are empty. An extra switch with priority order or the sequence of the drives in the former could be taken into consideration.

Actual behavior
===============

From user side it is unknown, how mergerfs chooses between drives to be filled (written) firstly if both of them are empty.

System information
==================
Please provide as much of the following information as possible:

* [ ] mergerfs version: `mergerfs -V`
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.9
using FUSE kernel interface version 7.19

* [ ] mergerfs settings: `cat /etc/fstab` or the command line arguments
/usr/bin/mergerfs -o allow_other,use_ino,moveonenospc=true /srv/backup/box.com:/srv/backup/4shared.com /srv/backup/4shared+box.com

* [ ] Linux version: `uname -a`
Linux 4.19.0-9-686-pae #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) i686 GNU/Linux

* [ ] Versions of any additional software being used
rclone v1.52.2 for mounting cloud storages at 4shared.com and box.com

* [ ] List of drives, filesystems, & sizes: `df -h`
Filesystem           Size  Used Avail Use% Mounted on
udev                 959M     0  959M   0% /dev
tmpfs                195M   22M  173M  11% /run
/dev/sda1            9.9G  6.6G  2.8G  71% /
tmpfs                971M     0  971M   0% /dev/shm
tmpfs                5.0M     0  5.0M   0% /run/lock
tmpfs                971M     0  971M   0% /sys/fs/cgroup
tmpfs                971M   40M  932M   5% /tmp
/dev/sda5            864G  801G   54G  94% /srv
Mega:                 50G   24G   27G  47% /srv/backup/mega.nz
T-Online:            1.0P     0  1.0P   0% /srv/backup/t-online.de
4shared:             1.0P     0  1.0P   0% /srv/backup/4shared.com
Box:                  10G     0   10G   0% /srv/backup/box.com
4shared.com:box.com  1.1P     0  1.1P   0% /srv/backup/4shared+box.com

**Comment by trapexit** [comment]
Have you read over the documentation? A large portion of it discusses exactly that.

https://github.com/trapexit/mergerfs#functions--policies--categories

**Comment by ambipur76** [comment]
Thank you for your advice, this was new for me. You are right, I'd better read the documentation first. Bu now, after reading it, I have experimented with epall, epff, eplfs, eplus and epmfs options. After modifying the option, I have restarted my systemd unit which mounts my storage at box.com respectively 4shared.com. In all cases 4shared.com has been choosen by mergerfs, I had no success to force to choose the other storage. Do you have any idea? What can be wrong?

**Comment by trapexit** [comment]
I really can't help without all the information relevant to the decision making process. The policies you listed are path preserving. Only branches with the relative path are considered. If you don't have the path on a branch it will not be considered. Also you're `df` shows 4shared branch having 1PB whereas box.com has 10G. If you're using mfs or lus then of course the former would be selected.

The behavior of the policy works exactly as described. Just run through the logic with the values you have.
