### ISSUE TITLE
Unable to create files via Samba on MergerFS mount

### ISSUE THREAD

**Issue by JeffWDH** [trapexit/mergerfs#801]
**Describe the bug**

I am having an issue creating files via a Samba share on a mergerfs mount. If I try to write to the underlying filesystems via Samba it works as expected. The user I am logged in as has an ACL with "modify" permission on the directory.

Any advice as to how to resolve this would be much appreciated.

**To Reproduce**

Attempt to create a file or folder on Samba share that points to mergerfs and will get "Access denied". Access the underlying volumes via Samba and attempt to create a file or folder and it works fine. 

**System information:**
mergerfs -V
mergerfs version: 2.30.0
FUSE library version: 2.9.7-mergerfs_2.30.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31

Version: 2.29, also on the latest git from last night.

uname -a
Linux Fileserver 3.16.0-10-amd64 #1 SMP Debian 3.16.81-1 (2020-01-17) x86_64 GNU/Linux

smbd --version
Version 4.2.14-Debian

Note: I have simplified my test case by creating directories under /mnt as a test (/mnt/mergerfs mount point, /mnt/mergerfs_test/a, /mnt/mergerfs_test/b for data) for testing purposes. My actual use case has 4 ext4 volumes:

\# Videos drives
/dev/sdb1                                 /mnt/Videos_Drives/sdb1  ext4    errors=remount-ro 0       1
/dev/sdk1                                 /mnt/Videos_Drives/sdk1  ext4    errors=remount-ro 0       1
/dev/sdj1                                 /mnt/Videos_Drives/sdj1  ext4    errors=remount-ro 0       1
/dev/sdi1                                 /mnt/Videos_Drives/sdi1  ext4    errors=remount-ro 0       1

\# MergerFS
/mnt/Videos_Drives/* /mnt/Videos fuse.mergerfs fsname=VideosFS,defaults,allow_other,use_ino,moveonenospc=true,category.create=mfs 0 0

For simplicity of troubleshooting, I'm using the test directories as they exhibit the same behavior.

/etc/fstab:
UUID=ca4c13e9-0eba-4ee9-8858-5d31f99a19e5 /                        ext4    errors=remount-ro 0       1
/mnt/mergerfs_test/* /mnt/mergerfs fuse.mergerfs fsname=MergerFS,defaults,allow_other,use_ino,moveonenospc=true,category.create=mfs 0 0

ls -la /mnt/ | grep mergerfs
drwxrwxr-x+  2 root root 4096 Aug  4 12:18 mergerfs
drwxrwxr-x+  4 root root 4096 Aug  4 12:13 mergerfs_test

ls -la /mnt/mergerfs_test/
total 32
drwxrwxr-x+  4 root root 4096 Aug  4 12:13 .
drwxrwx--x+ 10 root root 4096 Aug  4 12:13 ..
drwxrwxr-x+  4 root root 4096 Aug  4 12:48 a
drwxrwxr-x+  2 root root 4096 Aug  4 12:13 b

Applicable df output:
Filesystem              Size  Used Avail Use% Mounted on
/dev/sda1                15G  4.3G   10G  30% /

getfacl mergerfs
\# file: mergerfs
\# owner: root
\# group: root
user::rwx
user:root:rwx
user:DOMAIN\134domain\040admins:rwx
user:DOMAIN\134jeff:rwx
user:DOMAIN\134sharedmedia:rwx
group::r-x
group:root:r-x
group:DOMAIN\134domain\040admins:rwx
group:fuse:rwx
group:DOMAIN\134sharedmedia:rwx
mask::rwx
other::r-x
default:user::rwx
default:user:root:rwx
default:user:DOMAIN\134domain\040admins:rwx
default:user:DOMAIN\134jeff:rwx
default:user:DOMAIN\134sharedmedia:rwx
default:group::r-x
default:group:root:r-x
default:group:DOMAIN\134domain\040admins:rwx
default:group:fuse:rwx
default:group:DOMAIN\134sharedmedia:rwx
default:mask::rwx
default:other::r-x

getfacl mergerfs_test/
\# file: mergerfs_test/
\# owner: root
\# group: root
user::rwx
user:root:rwx
user:DOMAIN\134domain\040admins:rwx
user:DOMAIN\134jeff:rwx
user:DOMAIN\134sharedmedia:rwx
group::r-x
group:root:r-x
group:DOMAIN\134domain\040admins:rwx
group:fuse:rwx
group:DOMAIN\134sharedmedia:rwx
mask::rwx
other::r-x
default:user::rwx
default:user:root:rwx
default:user:DOMAIN\134domain\040admins:rwx
default:user:DOMAIN\134jeff:rwx
default:user:DOMAIN\134sharedmedia:rwx
default:group::r-x
default:group:root:r-x
default:group:DOMAIN\134domain\040admins:rwx
default:group:fuse:rwx
default:group:DOMAIN\134sharedmedia:rwx
default:mask::rwx
default:other::r-x

getfacl mergerfs_test/a
\# file: mergerfs_test/a
\# owner: root
\# group: root
user::rwx
user:root:rwx
user:DOMAIN\134domain\040admins:rwx
user:DOMAIN\134jeff:rwx
user:DOMAIN\134sharedmedia:rwx
group::r-x
group:root:r-x
group:DOMAIN\134domain\040admins:rwx
group:fuse:rwx
group:DOMAIN\134sharedmedia:rwx
mask::rwx
other::r-x
default:user::rwx
default:user:root:rwx
default:user:DOMAIN\134domain\040admins:rwx
default:user:DOMAIN\134jeff:rwx
default:user:DOMAIN\134sharedmedia:rwx
default:group::r-x
default:group:root:r-x
default:group:DOMAIN\134domain\040admins:rwx
default:group:fuse:rwx
default:group:DOMAIN\134sharedmedia:rwx
default:mask::rwx
default:other::r-x

getfacl mergerfs_test/b
\# file: mergerfs_test/b
\# owner: root
\# group: root
user::rwx
user:root:rwx
user:DOMAIN\134domain\040admins:rwx
user:DOMAIN\134jeff:rwx
user:DOMAIN\134sharedmedia:rwx
group::r-x
group:root:r-x
group:DOMAIN\134domain\040admins:rwx
group:fuse:rwx
group:DOMAIN\134sharedmedia:rwx
mask::rwx
other::r-x
default:user::rwx
default:user:root:rwx
default:user:DOMAIN\134domain\040admins:rwx
default:user:DOMAIN\134jeff:rwx
default:user:DOMAIN\134sharedmedia:rwx
default:group::r-x
default:group:root:r-x
default:group:DOMAIN\134domain\040admins:rwx
default:group:fuse:rwx
default:group:DOMAIN\134sharedmedia:rwx
default:mask::rwx
default:other::r-x

getfattr -d -m "" /mnt/mergerfs_test/*
getfattr: Removing leading '/' from absolute path names
\# file: mnt/mergerfs_test/a
security.NTACL=<snip>
system.posix_acl_access=<snip>
system.posix_acl_default=<snip>
user.SAMBA_PAI=<snip>

\# file: mnt/mergerfs_test/b
security.NTACL=<snip>
system.posix_acl_access=<snip>
system.posix_acl_default=<snip>
user.SAMBA_PAI=<snip>

getfattr -d -m "" /mnt/mergerfs
getfattr: Removing leading '/' from absolute path names
\# file: mnt/mergerfs
security.NTACL=<snip>
system.posix_acl_access=<snip>
system.posix_acl_default=<snip>
user.SAMBA_PAI=<snip>

smb.comf:
[global]
allow insecure wide links = yes
bind interfaces only = yes
interfaces = lo eth0
workgroup = DOMAIN
server role = member server
security = ADS
realm = DOMAIN.xyz.com
winbind refresh tickets = yes
vfs objects = acl_xattr
map acl inherit = yes
store dos attributes = yes
inherit acls = yes
inherit permissions = yes
dedicated keytab file = /etc/krb5.keytab
kerberos method = secrets and keytab
winbind enum users = yes
winbind enum groups = yes
winbind cache time = 60
username map = /etc/samba/user.map

idmap config * : backend = tdb
idmap config * : range = 80000001-100000000
idmap config DOMAIN : backend  = rid
idmap config DOMAIN : range = 1000-999999

load printers = no
printing = bsd
printcap name = /dev/null
disable spoolss = yes

log file = /var/log/samba/log.%m
max log size = 1000
syslog = 0
log level = 10 all:10
panic action = /usr/share/samba/panic-action %d

\#======================= Share Definitions =======================

[Mergerfs]
comment = MergerFS Test
path = /mnt/mergerfs
guest ok = no
read only = no
follow symlinks = yes
wide links = yes

[mnt]
comment = /mnt
path = /mnt
guest ok = no
read only = no
browseable = no

SMB client: Windows 10 domain member computer logged in as DOMAIN\jeff

straces (see attached):
strace -f -p 10446 -o mergerfs.strace.txt
strace -f -p 10604 -o smb.strace.txt

```
strace successful directory creation on /mnt/mergerfs_test/a (\\fileserver\mnt\mergerfs_test\a):
10447 <... read resumed> "8\0\0\0\3\0\0\0\216\1\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 56
10447 lstat("/mnt/mergerfs_test/a/", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
10447 lstat("/mnt/mergerfs_test/a/", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
10447 writev(3, [{"x\0\0\0\0\0\0\0\216\1\0\0\0\0\0\0", 16}, {"\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\225:\276R\2102m^\0\20\0\0\0\0\0\0"..., 104}], 2) = 120
10448 <... read resumed> "?\0\0\0\26\0\0\0\217\1\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 63
10448 lstat("/mnt/mergerfs_test/a/", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
10448 lgetxattr("/mnt/mergerfs_test/a/", "user.DOSATTRIB", 0x7ff87800bfd0, 256) = -1 ENODATA (No data available)
10448 writev(3, [{"\20\0\0\0\303\377\377\377\217\1\0\0\0\0\0\0", 16}], 1) = 16
10448 read(3,  <unfinished ...>
10447 read(3,  <unfinished ...>
10448 <... read resumed> "?\0\0\0\26\0\0\0\220\1\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 63
10448 lstat("/mnt/mergerfs_test/a/", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
10448 lgetxattr("/mnt/mergerfs_test/a/", "user.DOSATTRIB", 0x7ff87800bfd0, 256) = -1 ENODATA (No data available)
10448 writev(3, [{"\20\0\0\0\303\377\377\377\220\1\0\0\0\0\0\0", 16}], 1) = 16
10448 read(3,  <unfinished ...>
10447 <... read resumed> "?\0\0\0\26\0\0\0\221\1\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 63
10447 lstat("/mnt/mergerfs_test/a/", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
10447 lgetxattr("/mnt/mergerfs_test/a/", "user.DOSATTRIB", 0x7ff870000990, 256) = -1 ENODATA (No data available)
10447 writev(3, [{"\20\0\0\0\303\377\377\377\221\1\0\0\0\0\0\0", 16}], 1) = 16
10447 read(3,
```

**Comment by JeffWDH** [comment]
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/5023539/mergerfs.strace.txt)
[smb.strace.txt](https://github.com/trapexit/mergerfs/files/5023540/smb.strace.txt)

**Comment by trapexit** [comment]
You're using posix acls right? You'd need to enable them in mergerfs.

https://github.com/trapexit/mergerfs#options

posix_acl=true

**Comment by JeffWDH** [comment]
During my troubleshooting last night (based on a similar issue I saw on here) I did try adding posix_acl=true to my options and it did not have any effect. I just re-added it to my options now and am seeing the same behavior.

**Comment by trapexit** [comment]
Your smb.trace files is not text.

I see accesses to xatts some succeeded and some not. I'm not all that familiar with what Samba is doing here so without a more precise example and logs it's tough to comment.

**Comment by JeffWDH** [comment]
Sorry, I'm not sure what happened there. Please see the attached new straces:

[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/5023657/mergerfs.strace.txt)
[smb.strace.txt](https://github.com/trapexit/mergerfs/files/5023658/smb.strace.txt)

**Comment by trapexit** [comment]
I see a few failures on "user.DOSATTRIB" getxattrs but everything else is passed through and the calls from samba seem to match up with calls mergerfs makes.

There are no EACCES errors from mergerfs. In smb you see a mkdir fail for "New folder (3)" with EACCES but no such call is made by mergerfs. Meaning I'm missing some other way mergerfs returns EACCES which I don't believe there is any way it will without first making a call to the OS and getting that response or it's the kernel preempting it. Without timestamps in the traces it's hard to really correlate calls.

**Comment by trapexit** [comment]
A shot in the dark but try the defaultperms branch. Removed a kernel feature for managing permissions. Perhaps it doesn't work well with the enabling of posix acls.

**Comment by JeffWDH** [comment]
[smb.strace.txt](https://github.com/trapexit/mergerfs/files/5023756/smb.strace.txt)
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/5023757/mergerfs.strace.txt)

Added -t for timestamps
strace -t -f -p 11054 -o mergerfs.strace.txt &
strace -t -f -p 11088 -o smb.strace.txt &

**Comment by JeffWDH** [comment]
Okay, I'll grab that branch and give it a try.

**Comment by JeffWDH** [comment]
I can confirm that the defaultperms branch works for me.

root@Fileserver:/usr/local/src/mergerfs# git branch
* defaultperms
root@Fileserver:/usr/local/src/mergerfs# mergerfs --version
mergerfs version: 2.30.0-1-g2e5b650
FUSE library version: 2.9.7-mergerfs_2.30.0
fusermount version: 2.9.7-mergerfs_2.29.0

**Comment by trapexit** [comment]
Hmm. OK. I was under the impression it could manage POSIX ACLs with that enabled. Does it work with and/or without posix_acl=true?

**Comment by JeffWDH** [comment]
I just tested both and it works with and without the posix_acl=true option. I'm now running without successfully. 

root@Fileserver:/mnt# grep mergerfs_test /etc/fstab
/mnt/mergerfs_test/* /mnt/mergerfs fuse.mergerfs fsname=MergerFS,defaults,allow_other,use_ino,moveonenospc=true,category.create=mfs 0 0

root@Fileserver:/mnt# ps ax | grep mergerfs_test
13134 ?        S<sl   0:00 mergerfs /mnt/mergerfs_test/* /mnt/mergerfs -o rw,fsname=MergerFS,allow_other,use_ino,moveonenospc=true,category.create=mfs,dev,suid

**Comment by trapexit** [comment]
Must be something else then that I'm not understanding. I had thought that the posix_acl when enabled would work properly with default_permissions which makes the kernel manage that stuff. I noticed your kernel version is older. Any chance you could try it on something newer?

**Comment by JeffWDH** [comment]
I don't really want to mess around with compiling kernels as I do need to rebuild this VM as Debian Jessie is getting old. Give me a few days to build a new Buster VM and move things over to it and I'll do some more testing.

**Comment by trapexit** [comment]
Thanks. A lot of random stuff has changed since that kernel. I'll try to track down if the posix acl stuff was one of them in the meantime. If so then I have to be more careful about a patch. Generally I don't want people disabling default_permissions. 

When you enable posix_acl does it show up as true via the xattr runtime? It should be false if the kernel doesn't support it. Including some more debugging info on the runtime kernel flags has been on my todo list.

**Comment by JeffWDH** [comment]
With the option posix_acl = true:
xattr -l /mnt/mergerfs/.mergerfs | grep posix
user.mergerfs.posix_acl: **false**

**Comment by trapexit** [comment]
Ah. So the kernel doesn't support it. That might be the ultimate issue. Perhaps in 3.x I can make it error in such cases.

**Comment by JeffWDH** [comment]
On Debian 10.5:
root@Fileserver:/mnt# uname -a
Linux Fileserver 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

root@Fileserver:/mnt# grep mergerfs /etc/fstab
/mnt/mergerfs_drives/* /mnt/mergerfs fuse.mergerfs fsname=MergerFS,defaults,allow_other,use_ino,moveonenospc=true,category.create=mfs,posix_acl=true 0 0

root@Fileserver:/mnt# xattr -l /mnt/mergerfs/.mergerfs | grep posix
user.mergerfs.posix_acl: true

Using the up to date master branch code.

Thanks for your help with this today, I spent hours troubleshooting this last night so I could rule out everything I could think of before opening an issue. 

Let me know if you want any testing done on the old VM.

**Comment by trapexit** [comment]
What about on the new vm with 2.29.0 and posix_acl=true?

**Comment by trapexit** [comment]
Oh... by "up to date master" you mean not using the branch I made for you? Then that's all the same. 

I'll put a note in the docs about all this and if people with older kernels need a work around I'll add a flag to disable default_permissions.

**Comment by JeffWDH** [comment]
I'm on the master branch now with it working as expected.  Thanks again!

**Comment by trapexit** [comment]
OK. Then I'll do what I said and just add some documentation for now.
