### ISSUE TITLE
SSHFS branch always eventually stops working

### ISSUE THREAD

**Issue by naktinis** [trapexit/mergerfs#802]
**Describe the bug**
I have the following layout:
/a  - SSHFS mount
/b  - directory inside a Btrfs mount
/ab - MergerFS mount

For some time after a fresh MergerFS mount everything works fine. Then after
some time (typically hours) the SSHFS mount /a starts being ignored. Specifically:
 - on the other side of SSHFS `touch /a/foo` (remote machine)
 - `ls /a/foo` shows `foo` (local machine) - so SSHFS mount itself is working
 - `ls /ab/foo` does not show `foo` - when it should; this is the problem
 - `ls /ab/foo` is also visibly faster (seems like it simply doesn't check /a anymore, and just looks at /b)
 - rerunning mergerfs fixes the issue (for some time)

**To reproduce**
MergerFS command (read-only, file cache off):
```
mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /a:/b /ab
```

Wait for a few hours.

**Expected behavior**
Listing a MergerFS mount should look at both branches.

**System information:**
 - OS, kernel version: `uname -a`
Linux (redacted) 4.20.17-042017-generic #201903190933 SMP Tue Mar 19 13:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - mergerfs version: `mergerfs -V`
```
mergerfs version: unknown
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7
using FUSE kernel interface version 7.31
```

Built from https://github.com/trapexit/mergerfs/archive/2.29.0.tar.gz.

This has also been happening on MegerFS v2.21.0 and is reproducible on many different Linux machines.

 - mergerfs settings
defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /a:/b /ab

 - strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`
```
# strace of mergerfs in a "broken state" running ls above:
18654 read(3,  <unfinished ...>
18653 read(3,  <unfinished ...>
18652 read(3,  <unfinished ...>
18651 read(3,  <unfinished ...>
18650 read(3,  <unfinished ...>
18649 read(3,  <unfinished ...>
18648 read(3,  <unfinished ...>
18647 read(3,  <unfinished ...>
18645 futex(0x7fff6b1f4990, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
18654 <... read resumed> "8\0\0\0\3\0\0\0\226\313\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 56
18654 lstat("/b/", {st_mode=S_IFDIR|0755, st_size=87392, ...}) = 0
18654 lstat("/a/", 0x7f8ee4a391a0) = -1 EACCES (Permission denied)
18654 lstat("/b/", {st_mode=S_IFDIR|0755, st_size=87392, ...}) = 0
18654 writev(3, [{iov_base="x\0\0\0\0\0\0\0\226\313\0\0\0\0\0\0", iov_len=16}, {iov_base="\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2141S\336\375\365\210O`U\1\0\0\0\0\0"..., iov_len=104}], 2) = 120
18654 read(3, ",\0\0\0\1\0\0\0\230\313\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 44
18654 lstat("/b/foo", 0x7f8ee4a39170) = -1 ENOENT (No such file or directory)
18654 lstat("/a/foo", 0x7f8ee4a39170) = -1 EACCES (Permission denied)
18654 writev(3, [{iov_base="\20\0\0\0\376\377\377\377\230\313\0\0\0\0\0\0", iov_len=16}], 1) = 16
18654 read(3, ",\0\0\0\1\0\0\0\232\313\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 44
18654 lstat("/b/foo", 0x7f8ee4a39170) = -1 ENOENT (No such file or directory)
18654 lstat("/a/foo", 0x7f8ee4a39170) = -1 EACCES (Permission denied)
18654 writev(3, [{iov_base="\20\0\0\0\376\377\377\377\232\313\0\0\0\0\0\0", iov_len=16}], 1) = 16
18654 read(3,  <detached ...>
```
```
# strace of a restarted/healthy mergerfs during the same ls scenario:
7627  read(3,  <unfinished ...>
7626  read(3,  <unfinished ...>
7625  read(3,  <unfinished ...>
7624  read(3,  <unfinished ...>
7623  read(3,  <unfinished ...>
7622  read(3,  <unfinished ...>
7621  read(3,  <unfinished ...>
7620  read(3,  <unfinished ...>
7618  futex(0x7ffcb2ef2fb0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
7627  <... read resumed> "8\0\0\0\3\0\0\0d\3\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 56
7627  lstat("/b/", {st_mode=S_IFDIR|0755, st_size=87392, ...}) = 0
7627  lstat("/a/", {st_mode=S_IFDIR|0755, st_size=87386, ...}) = 0
7627  lstat("/a/", {st_mode=S_IFDIR|0755, st_size=87386, ...}) = 0
7627  writev(3, [{iov_base="x\0\0\0\0\0\0\0d\3\0\0\0\0\0\0", iov_len=16}, {iov_base="\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0000\20=\242\325Z\25\317ZU\1\0\0\0\0\0"..., iov_len=104}], 2) = 120
7627  read(3, ",\0\0\0\1\0\0\0f\3\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1052672) = 44
7627  lstat("/b/foo", 0x7f99c23eb170) = -1 ENOENT (No such file or directory)
7627  lstat("/a/foo", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
7627  lstat("/a/foo", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
7627  writev(3, [{iov_base="\220\0\0\0\0\0\0\0f\3\0\0\0\0\0\0", iov_len=16}, {iov_base="!\1\0\0\0\0\0\0\24\244\242^6\330\371d\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0"..., iov_len=128}], 2) = 144
7627  read(3,  <detached ...>
```

**Additional context**
Strace reports an EACCESS issue, but it doesn't seem to be a permission on /a
(as in user/rwx issue). My only guess right now (could be totally wrong) is that
this could be related to sshfs reconnecting and something happening to inodes
(but I don't know it well enough).

Since mergerfs documentation says its supports SSHFS and if this is in fact
related to reconnecting, then this seemed like a pretty critical issue worth
reporting (or maybe at least something worth documenting in case it's an
SSHFS misconfiguration).

**Comment by trapexit** [comment]
`mergerfs version: unknown`

? How did you install it? What version is it?

**Comment by naktinis** [comment]
A colleague of mine wrote a script for it, but I believe it downloads v2.29.0 from `https://github.com/trapexit/mergerfs/archive/2.29.0.tar.gz` and runs `make`. Here's the script: https://gist.github.com/naktinis/746db4c8b1a0d76097cfa6a5b35fb67c

**Comment by trapexit** [comment]
> Strace reports an EACCESS issue, but it doesn't seem to be a permission on /a
(as in user/rwx issue).

mergerfs is just a random userland process from the perspective of that error. It's likely some sshfs issue because mergerfs can only respond to what the kernel tells it.

What OS are you using? Why the weird install? Why not use the properly packaged release tarball?

**Comment by naktinis** [comment]
> What OS are you using? Why the weird install? Why not use the properly packaged release tarball?

Ubuntu 18.04. I'll look into that - I wasn't the original author of the install script. But this was also happening on v2.21.0 (I think this one was from the Ubuntu repo).

> mergerfs is just a random userland process from the perspective of that error.

Would you maybe at least have any insights/suggestions what could be going wrong then? I can even have 2 mergerfs running simultaneously with exact same settings, the same branches, and the same permissions (just different mount points), both of them call the exact same`lstat("/a/foo", ...)`, but one of them fails, while the other one succeeds. Why would `lstat` behave differently for these two indentically launched mergerfs processes?

**Comment by trapexit** [comment]
Have you straced sshfs to see what it does when the request comes in? It or the kernel is the thing denying mergerfs access.

**Comment by trapexit** [comment]
Could you please include **all** your config so I can try to replicate? sshfs version, settings, etc.?

**Comment by naktinis** [comment]
> Could you please include all your config so I can try to replicate? sshfs version, settings, etc.?

Sure, of course.

```
sshfs -o ro,reconnect,cache=no,ServerAliveInterval=5,ServerAliveCountMax=120,ssh_command=ssh -o LogLevel=ERROR -o ConnectTimeout=3 -o ConnectionAttempts=2 [USER]@[REMOTE]:/a /a
```

```
$ sshfs -V
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

strace of sshfs when mergerfs is unsuccessful (running `ls /ab/foo`):
```
12136 read(3,  <unfinished ...>
11897 read(3,  <unfinished ...>
11896 read(3,  <unfinished ...>
11895 read(3,  <unfinished ...>
499   read(3,  <unfinished ...>
26335 read(4,  <unfinished ...>
26334 read(3,  <unfinished ...>
26333 read(3,  <unfinished ...>
26332 futex(0x7ffde377d2f0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <detached ...>
```

strace of sshfs when mergerfs is successful (running `ls /ab/foo`):
```
12136 read(3,  <unfinished ...>
11897 read(3,  <unfinished ...>
11896 read(3,  <unfinished ...>
11895 read(3,  <unfinished ...>
499   read(3,  <unfinished ...>
26335 read(4,  <unfinished ...>
26334 read(3,  <unfinished ...>
26333 read(3,  <unfinished ...>
26332 futex(0x7ffde377d2f0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
12136 <... read resumed> "8\0\0\0\3\0\0\0\314%\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 56
12136 writev(4, [{iov_base="\0\0\0\24\7\0\0\22\337", iov_len=9}, {iov_base="\0\0\0\v/a", iov_len=15}], 2) = 24
12136 futex(0x7f1f20001d18, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
26335 <... read resumed> "\0\0\0%i", 5) = 5
26335 read(4, "\0\0\22\337\0\0\0\17\0\0\0\0\0\1j\354\0\0\0\0\0\0\0\0\0\0A\355_'5\306"..., 36) = 36
26335 futex(0x7f1f20001d18, FUTEX_WAKE_PRIVATE, 1) = 1
12136 <... futex resumed> )             = 0
26335 read(4,  <unfinished ...>
12136 writev(3, [{iov_base="x\0\0\0\0\0\0\0\314%\0\0\0\0\0\0", iov_len=16}, {iov_base="\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\354j\1\0\0\0\0\0"..., iov_len=104}], 2) = 120
12136 read(3,  <unfinished ...>
11897 <... read resumed> ",\0\0\0\1\0\0\0\316%\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 44
11897 writev(4, [{iov_base="\0\0\0\30\7\0\0\22\340", iov_len=9}, {iov_base="\0\0\0\17/a/foo", iov_len=19}], 2) = 28
11897 futex(0x7f1f1c001c48, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
26335 <... read resumed> "\0\0\0%i", 5) = 5
26335 read(4, "\0\0\22\340\0\0\0\17\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\201\244_*\247\352"..., 36) = 36
26335 futex(0x7f1f1c001c48, FUTEX_WAKE_PRIVATE, 1) = 1
11897 <... futex resumed> )             = 0
26335 read(4,  <unfinished ...>
11897 writev(3, [{iov_base="\220\0\0\0\0\0\0\0\316%\0\0\0\0\0\0", iov_len=16}, {iov_base="\240\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0"..., iov_len=128}], 2) = 144
11897 read(3,  <detached ...>
```

**Comment by trapexit** [comment]
With sshfs it's probably better to just run it in debug mode and see what calls come in.

**Comment by trapexit** [comment]
Is the sshfs mount being used during this time or completely idle? I've got a pool of two sshfs mounts with an ls every 10 seconds and it's still fine after a few hours.

**Comment by naktinis** [comment]
It's likely it has some idle periods with occasional writes. These mountpoints can be used by quite a few processes, and I haven't tried to quantify the usage yet.

**Comment by naktinis** [comment]
I've set up the debug logging for sshfs and will wait for this to happen again. I'll let you know once I have any updates. Thank you for your help so far!

**Comment by trapexit** [comment]
No problem. If you can create a script that mimics your workload it'd help because I left my setup running all night and it's still fine.

**Comment by naktinis** [comment]
Reproduced it again just now. sshfs was running with the following options:
```
-o ro,reconnect,cache=no,ServerAliveInterval=5,ServerAliveCountMax=120,ssh_command="ssh -o LogLevel=ERROR -o ConnectTimeout=3 -o ConnectionAttempts=2" -o sshfs_debug -d -o debug
```

After the issue happens, calling `ls /ab/foo` (mergerfs mount) does not produce any sshfs logs.

Calling `ls /a/foo` (directly listing sshfs mount), produces the following sshfs log:
```
unique: 18220, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid: 22969
LOOKUP /foo
getattr /foo
[09090] LSTAT
  [09090]          ATTRS       41bytes (81ms)
   NODEID: 3305
   unique: 18220, success, outsize: 144
```

Regarding the workload I'm trying to think what could be representative of it. We sometimes have bursts of activity: files being written to both local /b branch and to remote /a branch (which syncs back to local /a via sshfs), followed by periods of inactivity. We don't write to the local /a (you probably know that from the `ro` flag), but we may occasionally read from it.

**Comment by trapexit** [comment]
If sshfs isn't receiving any calls then the kernel is returning the EACCES. Not sure what it could be. A caching issue? A bug? Have you tried messing with sshfs' caching options, using default_permissions?

**Comment by naktinis** [comment]
> messing with sshfs' caching options

We use `cache=no` and I don't see other caching options that would be on by default; is there any option you think I should try?

> using default_permissions

Haven't tried yet, but uid (the integer and the username) is the same on both machines for the sshfs directory and all of the files inside. Is there still a chance default_permissions would have an effect in this case?

**Comment by trapexit** [comment]
default_permissions is the kernel managing perms rather than sshfs. If you're getting a perm issue it seems reasonable to try anything related to that.

**Comment by naktinis** [comment]
Here's an interesting observation that may be relevant. When I first run mergerfs, the children threads (LWP) are listed by `ps -eLf` as being owned by `root` UID, however after, I think, nginx tries to access some paths, the same mergerfs threads get listed as now being owned by `www-data`.

I also see what looks like mergerfs issuing `setgroups`, `setreuid`, and later `setregid` right before the first `EACCES` appear:
```
[pid  8303] openat(AT_FDCWD, "/etc/group", O_RDONLY|O_CLOEXEC) = 4
[pid  8303] lseek(4, 0, SEEK_CUR)       = 0
[pid  8303] fstat(4, {st_mode=S_IFREG|0644, st_size=690, ...}) = 0
[pid  8303] mmap(NULL, 690, PROT_READ, MAP_SHARED, 4, 0) = 0x7fea9c176000
[pid  8303] lseek(4, 690, SEEK_SET)     = 690
[pid  8303] fstat(4, {st_mode=S_IFREG|0644, st_size=690, ...}) = 0
[pid  8303] munmap(0x7fea9c176000, 690) = 0
[pid  8303] close(4)                    = 0
[pid  8303] setgroups(1, [33])          = 0
[pid  8303] setreuid(-1, 33)            = 0
[pid  8302] lstat("/b/directory", {st_mode=S_IFDIR|0755, st_size=162, ...}) = 0
[pid  8302] lstat("/a/directory", 0x7fea9a62d170) = -1 EACCES (Permission denied)
[pid  8302] lstat("/b/directory", {st_mode=S_IFDIR|0755, st_size=162, ...}) = 0
```

```
UID        PID  PPID   LWP  C NLWP STIME TTY          TIME CMD
root      8296     1  8296  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8301  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8302  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8303  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8304  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8305  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8308  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8309  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
www-data  8296     1  8311  0    9 18:06 ?        00:00:00 mergerfs -o defaults,ro,allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.search=newest,nosuid,nodev,nonempty /b:/a /ab
```

I can observe these threads first starting as "root" and then (after nginx interacts with them) becoming "www-data". Is this expected behaviour? Did we misconfigure or misunderstood something?

**Comment by trapexit** [comment]
Not sure what you think you see but that behavior is described in the docs. It has to change euid/egid to properly manage POSIX permissions and such. 

As the trace shows it's changing, successfully, to user id 33 and setting group 33 which is the ID the kernel tells mergerfs is making the request.

The uid/gid will change to whatever is making the request and does so only when needed.

https://github.com/trapexit/mergerfs#supplemental-user-groups

https://github.com/trapexit/mergerfs#its-mentioned-that-there-are-some-security-issues-with-mhddfs-what-are-they-how-does-mergerfs-address-them

**Comment by naktinis** [comment]
That makes sense. However, could it be that if it changes to www-data and then back to root (calling `ls` as root) it somehow stays inaccessible from that point onwards?

**Comment by trapexit** [comment]
I'm not sure why or how that would happen. One would expect this to effect any filesystem if it was some generic behavior.

**Comment by trapexit** [comment]
You might be on to something. Might be some caching or shortcut regarding how FUSE (the kernel driver) manages permissions. If you add allow_other or allow_root to sshfs it seems to work fine. Which explains why you might be the only person to notice because pretty much everyone uses allow_other. I've considered making it default in mergerfs because it's really not designed not to run as root or single user. I'd have to ask the kernel driver maintainers about this.

**Comment by trapexit** [comment]
I forgot to ping the mailing list about this but did you try using allow_other?

**Comment by naktinis** [comment]
Yes, seems like it helped. Sorry for the delay, just wanted to make sure the issue went away.

**Comment by trapexit** [comment]
OK. I just sent an email to at least get an understanding on why, specifically, it's happening. I'll add something to the docs about this. It's not unreasonable to want to not enable allow_other but this is out of my hands (practically speaking.)
