### ISSUE TITLE
Cannot change ownership chown of mergerfs pool

### ISSUE THREAD

**Issue by MikeTannenbaum** [trapexit/mergerfs#804]
**Version of mergerfs**
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29

**mergerfs settings:**
/mnt/disk* /mnt/SERENITY fuse.mergerfs use_ino,defaults,allow_other,minfreespace=50G,fsname=mergerfs 0 0

**Version of Linux**
Linux theroyalproxserver 5.4.34-1-pve #1 SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200) x86_64 GNU/Linux

**Versions of any additional software being used**
proxmox  6.2-4 running an ubuntu 20.04 container

**List of drives, their filesystems, and sizes (before and after issue)**
Filesystem            Size  Used Avail Use% Mounted on
udev                  3.8G     0  3.8G   0% /dev
tmpfs                 767M  9.1M  757M   2% /run
/dev/mapper/pve-root   57G  4.9G   50G  10% /
tmpfs                 3.8G   46M  3.7G   2% /dev/shm
tmpfs                 5.0M     0  5.0M   0% /run/lock
tmpfs                 3.8G     0  3.8G   0% /sys/fs/cgroup
mergerfs              6.3T  2.5T  3.5T  42% /mnt/SERENITY
/dev/sdb2             2.7T  2.5T   86G  97% /mnt/disk1
/dev/sdc1             3.6T   89M  3.4T   1% /mnt/disk2
/dev/fuse              30M   20K   30M   1% /etc/pve
tmpfs                 767M     0  767M   0% /run/user/0

**All information about the relevant branches and paths**
drwxrwsr-x  3 nobody nogroup  4096 Nov 27  2019  Incoming

**Precise directions on replicating the issue. Do not leave anything out.**
I'm trying to `chown` the directory above to be owned by my user and a `media` group but continually come up with `chown: changing ownership of 'Incoming/': Operation not permitted`
sdb2 is a drive/partition I've had for a long time which already has files and folders. sdc1 is a new drive/partition I've added which is why I'm using mergerfs. When I look at the Incoming/ folder on sbd2 it has the proper user:group (mikeyt:media) but when I look at the mergerfs mount I get the above nobody:nogroup. I need that Incoming/ folder to be writable but I cannot for the life of me figure out what's going on.

I'm running Proxmox on bare metal with an ubuntu 20.04 container holding docker containers including portainer, plex, radarr, sonarr and more.

would love some help figuring out how to change the ownership of that folder from nobody to mikey (or any user, really). I believe that's not a mergerfs problem based on all the issues and reddit threads I've been through, but I cannot figure out how the heck to get this working so am feeling like mergerfs is where the issue lies for me.

Thanks!

EDIT: I tried using mergerfs.fsck but run in to `user@server:/usr/local/bin$ sudo mergerfs.fsck -h
/usr/local/bin/mergerfs.fsck: 7: Syntax error: newline unexpected`

**Comment by trapexit** [comment]
The permissions are based on the getattr policy. 

You aren't actually showing what you're trying to do. Does `sudo chown mikey:media <dir>` not work? Are you running mergerfs as root?

**Comment by MikeTannenbaum** [comment]
thanks for quick reply.
yes running in etc/fstab

when I run `sudo chown mikey:media <dir>` I get `chown: changing ownership of 'Incoming/': Operation not permitted` as the response

**Comment by MikeTannenbaum** [comment]
ok I'm not sure what to do... I see that `func.FUNC=POLICY` can be set but I don't know how to use it to chown that folder.
Am I thinking about that correctly?

**Comment by trapexit** [comment]
There is nothing to look at. My point was that permissions are taken from the file which mergerfs uses as the return value for getting metadata on a file. Which is getattr. Which you can change the policy of.

Have you tried changing the permissions of each underlying directory? If you're root, unless there is something else funny going on like an immutability flag, it should just work.

**Comment by trapexit** [comment]
I'm not telling you to change the policy. I was just pointing out that's how the permissions are picked up.

**Comment by MikeTannenbaum** [comment]
would changing the policy help? I don't fully understand that but trying to learn my way through.
I'm really struggling to figure out why I can't just `sudo chown` on that directory. when I check the actual drive with those files, the permissions are as I want them to be. When I check the mergerfs mount of SERENITY, they are nobody:nogroup. that's what I'm trying to change. Any idea thoughts on where the blockage is?

**Comment by trapexit** [comment]
No, it wouldn't help.

Please, can you please show me **exactly** what you are doing? Step by step. Not just errors and relative paths? What do you mean "an ubuntu 20.04 container holding docker containers including portainer, plex, radarr, sonarr and more."? You mean a Ubuntu 20.04 VM? You have two mounts. /mnt/disk1 and /mnt/disk2. What are the perms for /mnt/disk1/Incoming and /mnt/disk2/Incoming? Have you tried chown'ing them? Do they error similarly?

**Comment by MikeTannenbaum** [comment]
See below for details. 

This is a machine running proxmox where I've spun up a container. not a vm, a container—from what I understand it's lighter weight than a vm but still works similarly. It's running ubuntu 20.04. On that instance I have docker running with a container for each service (plex, radarr, etc). The IP for this ubuntu instance is 192.168.122.106, and the host machine is 107.

I ssh into 106 with my user `mikeyt`, `cd /SERENITY` and then try `sudo chown mikeyt:media Incoming/` and enter my password, which responds with `chown: changing ownership of 'Incoming/': Operation not permitted`

my goal is to change the user and group for the /Incoming folder listed below to be mikeyt:media.

Here's the output of `mikeyt@ubuntu-server-ct:/SERENITY$ ls -al`

`total 80
drwxrwxr-x 13 nobody nogroup  4096 Jul 31 01:26  .
drwxr-xr-x 25 root   root     4096 Aug  6 17:48  ..
drwxrwxr-x  2 nobody nogroup  4096 Jun 29 17:41  .AppleDB
drwxrwxr-x  2 nobody nogroup  4096 Oct 13  2015  .AppleDesktop
drwxrwxr-x  2 nobody nogroup  4096 Nov 11  2017  .AppleDouble
-rwxrwxr-x  1 nobody nogroup 14340 Feb 24 02:00  .DS_Store
drwxrwxr-x  6 nobody nogroup  4096 Nov 22  2015  .Trash-1001
drwxrwxr-x  4 nobody nogroup  4096 Jun  5  2019 'Cold Storage'
drwxrwsr-x  3 nobody nogroup  4096 Nov 27  2019  Incoming
drwxrwsr-x  8 nobody nogroup  4096 Nov 26  2019 'Media Library'
drwxrwxr-x  3 nobody nogroup  4096 Oct 13  2015 'Network Trash Folder'
drwxrwxr-x  3 nobody nogroup  4096 Oct 13  2015 'Temporary Items'
drwxrwxr-x  2 nobody nogroup 16384 Jul 29  2015  lost+found
drwxrwxr-x  3 nobody mikeyt   4096 Aug  2 19:17  services`

`
root@theroyalproxserver:/mnt# ls -al
total 28
drwxr-xr-x  7 root root 4096 Aug  2 11:08 .
drwxr-xr-x 18 root root 4096 Aug  2 10:31 ..
drwxrwxr-x 13 root root 4096 Jul 30 21:26 disk1
drwxrwxr-x  3 root root 4096 Aug  2 11:24 disk2`

`root@theroyalproxserver:/mnt/disk1# ls -al
total 80
drwxrwxr-x 13 root root    4096 Jul 30 21:26  .
drwxr-xr-x  7 root root    4096 Aug  2 11:08  ..
drwxrwxr-x  2  775 root    4096 Jun 29 13:41  .AppleDB
drwxrwxr-x  2  775 mikeyt  4096 Oct 13  2015  .AppleDesktop
drwxrwxr-x  2  775   1001  4096 Nov 11  2017  .AppleDouble
drwxrwxr-x  4  775   1001  4096 Jun  5  2019 'Cold Storage'
-rwxrwxr-x  1  775   1001 14340 Feb 23 21:00  .DS_Store
drwxrwsr-x  3 root root    4096 Nov 27  2019  Incoming
drwxrwxr-x  2  775 root   16384 Jul 29  2015  lost+found
drwxrwsr-x  8  775   1004  4096 Nov 25  2019 'Media Library'
drwxrwxr-x  3  775 mikeyt  4096 Oct 13  2015 'Network Trash Folder'
drwxrwxr-x  3  775 101000  4096 Aug  2 15:17  services
drwxrwxr-x  3  775 mikeyt  4096 Oct 13  2015 'Temporary Items'
drwxrwxr-x  6  775   1001  4096 Nov 22  2015  .Trash-1001
`

I thought those needed to be root for mergerfs to work — should I straight chown Incoming to be mikeyt:media? I'll try that now to see what happens

**Comment by MikeTannenbaum** [comment]
What i'm running into is that I just pulled all that information from the host machine (running proxmox) as root, but I'm trying to chown for users and groups on the ubuntu instance running within a container, so I can't chown those /mnt/disk1 directly since the users and groups are different given they're different machines.

**Comment by MikeTannenbaum** [comment]
When on the ubuntu machine here's the ownership of the folders:

mikeyt@ubuntu-server-ct:/SERENITY$ ls -al
total 80
drwxrwxr-x 13 nobody nogroup  4096 Jul 31 01:26  .
drwxr-xr-x 25 root   root     4096 Aug  6 17:48  ..
drwxrwxr-x  2 nobody nogroup  4096 Jun 29 17:41  .AppleDB
drwxrwxr-x  2 nobody nogroup  4096 Oct 13  2015  .AppleDesktop
drwxrwxr-x  2 nobody nogroup  4096 Nov 11  2017  .AppleDouble
-rwxrwxr-x  1 nobody nogroup 14340 Feb 24 02:00  .DS_Store
drwxrwxr-x  6 nobody nogroup  4096 Nov 22  2015  .Trash-1001
drwxrwxr-x  4 nobody nogroup  4096 Jun  5  2019 'Cold Storage'
drwxrwsr-x  3 nobody nogroup  4096 Nov 27  2019  Incoming
drwxrwsr-x  8 nobody nogroup  4096 Nov 26  2019 'Media Library'
drwxrwxr-x  3 nobody nogroup  4096 Oct 13  2015 'Network Trash Folder'
drwxrwxr-x  3 nobody nogroup  4096 Oct 13  2015 'Temporary Items'
drwxrwxr-x  2 nobody nogroup 16384 Jul 29  2015  lost+found
drwxrwxr-x  3 nobody mikeyt   4096 Aug  2 19:17  services

**Comment by MikeTannenbaum** [comment]
when ssh'd into the ubuntu container which is being passed the mergerfs mount I am unable to do anything (mkdir, touch) even as sudo. when I'm ssh'd to the host machine I can do everything. I can't figure out where those permission errors are.

**Comment by trapexit** [comment]
I don't know what Proxmox's "container" is. That is an atypical setup and I don't know what it might be doing. Is it using user namespacing? Running the container's software as a specific uid/gid? VMs and containers are completely different things. I don't know what this "ubuntu container" is but clearly it's screwing with things if the filesystem is showing up differently inside than outside. At most you should see uid/gids instead of names because it doesn't have names.

**Comment by trapexit** [comment]
Can you please point me to any documentation on this feature?

**Comment by trapexit** [comment]
https://pve.proxmox.com/wiki/Linux_Container

Nevermind.

It's using LXC and it, if you're setting up an unprivileged container, is not root.

> The root UID 0 inside the container is mapped to an unprivileged user outside the container. 

So... it's doing what you asked of it if that's your setup. You can't chown something you don't own.

**Comment by MikeTannenbaum** [comment]
that makes lots of sense. thanks for helping me understand—I'm learning by doing and this is helpful. will give it another go!

**Comment by MikeTannenbaum** [comment]
For anyone who ends up here in the future...

this was super simple (after hours of trying to figure it out).

Login to your proxmox host instance as root and `chown -R 100000:100000 <dir>` — that will change ownership of the directory to be root:root, based on how LXC maps uids.

**Resources:**
[Unprivileged LXC Containers](https://pve.proxmox.com/wiki/Unprivileged_LXC_containers)
[Linux containers in proxmox](https://pve.proxmox.com/wiki/Linux_Container)
@trapexit's help above. Thank you for spending some time looking at my challenge! You helped me unlock it 🙌
