### ISSUE TITLE
Provide pre-check workaround for rmdir command

### ISSUE THREAD

**Issue by t3nk3y** [trapexit/mergerfs#812]
**Is your feature request related to a problem? Please describe.**
When performing an rmdir on a pool that contains the directory in multiple paths, if one of the directories is empty, and the others are not, the rmdir can result in somewhat unpredictable, and potentially undesirable behavior.

**Describe the solution you'd like**
Implement a check when the rmdir command is requested, that will perform a search on all paths, and if any path has any contents, mergerfs should return an error indicating the directory is not empty(or can not be deleted), and rmdir should abort the action at that point.

As this pre-check would require file system checks on all paths (though only 1 level deep on each), it could create an increased load that may have detrimental effects on some environments, so this should be an optional behavior that is set on the pool.

**Describe alternatives you've considered**
The only alternative that might make sense would be to execute the action on all paths, and if an error occurs on any, to undo that action.  However, this would likely involve far more operations, and be extremely difficult, and potentially dangerous to implement.

**Additional context**
The problem this feature is looking to solve has different manifestations depending on the product in use.  Some specific examples include Webmin, which tries an rmdir before deleting the content of the directory, and since it sees a success, ends up not deleting the directory or its contents from the path that has content, until all empty paths have been deleted.  The bash rmdir command, itself, which reports no errors until it's been executed multiple times, resulting in the only remaining path being the one with content.  And Owncloud, which does it's own pre-check for content beforehand, and will delete the content, then perform the rmdir, which completely works around the problem.

The idea is to get all of the software to perform behavior similar to a "standard" filesystem, by giving the software feedback similar to what it would get without mergerfs.  This also provides a somewhat more cautious and transparent behavior to the user.  If the user attempts to rmdir, they know that if they get an error due to a directory having content, that no action was actually taken, instead of either getting no feedback, or feedback that doesn't fully reflect the actual actions that were carried out.

**Comment by trapexit** [comment]
> The idea is to get all of the software to perform behavior similar to a "standard" filesystem, by giving the software feedback similar to what it would get without mergerfs.

This can be done in a few ways. Is the concern **really** the removal of empty directories while some stay around? Especially given the relevance of the existence of a directory matters  relative to other settings (the create policy)... or is the concern returning ENOTEMPTY if there is a ENOTEMPTY error? Those are different in cost and behavior.

**Comment by t3nk3y** [comment]
This is really looking at the feedback to the application requesting the delete, and to confusion that could be caused for a user.

As an example, from bash, I user might do this:
rmdir /example/issue/path
mv /newpath /example/shared/path

Pretty sure that from the user perspective,they are removing an old dir, and replacing it with a new, but instead, they just moved the newpath IN TO the old path.

You can imagine the chaos that COULD occur if a script tried this, and is expecting to fail if the dir is not deleted.
Other software (such as Webmin) might make programmatic decisions based on the feedback from RMDIR, and this leads to problems if the result of the command is not what is expected.

As opposed to handling what happens to the individual real paths, I think this puts more control in the hand of applications and users to decide how to handle unique situations.  Rather than guessing at what should or should not be done when multiple real paths of varying states exist in the pool, we let the user or application know that as far as the pool is concerned, this action shouldn't be possible, and leave it up to the user/app to decide what to do from there.

It's basically an option to tell mergerfs to be just a little more careful, to workaround assumptions other software might make, or in cases where visibility in to the pool structure can not be a factor in the application.

**Comment by trapexit** [comment]
> You can imagine the chaos that COULD occur if a script tried this, and is expecting to fail if the dir is not deleted.

That can happen anyway. That's why you don't do that without writing code that modern *at() function calls. 

>  this leads to problems if the result of the command is not what is expected.

Yes... but that is always the case with any inconsistent or race conditions. It's not about perfect. It's about good enough that the average software doesn't freak out.

> Rather than guessing at what should or should not be done when multiple real paths of varying states exist in the pool, we let the user or application know that as far as the pool is concerned, this action shouldn't be possible, and leave it up to the user/app to decide what to do from there.

You can't do that. I don't know how else to explain this. You have 10 dirs to rmdir. You get 10 different errors. Or 5 errors and 5 successes. What do you do? What if one app behaves differently from another (which is very common)?

> It's basically an option to tell mergerfs to be just a little more careful, to workaround assumptions other software might make, or in cases where visibility in to the pool structure can not be a factor in the application.

It's just not that simple. You're being simply too vague on how it should respond.

https://man7.org/linux/man-pages/man2/rmdir.2.html

There are listed there at least 13 different error conditions that all software can / do treat differently. How and when should an error be returned by mergerfs? Specifically. There are N rmdirs happening and 1 return value. Each rmdir can return at least success or one of the errors listed in the man page.

**Comment by trapexit** [comment]
The closest thing to what you suggest is to return the first error found which is what the patch I made did. Any other strategy I can think of has problems.

**Comment by t3nk3y** [comment]
I'm not proposing that mergerfs handle all errors for rmdir.  This issue is specific to the case where a directory is not empty. (this is not the other issue I have open).

I'm looking to provide a specific workaround for the case that the directory in the pool view is not empty.  Not trying rmdir on all paths.  Pre-check for contents and fail with not empty if any of the paths have contents.

**Comment by trapexit** [comment]
What is the ultimate concern? The removal of empty directories?

If the error handling is changed to remove errors as found you still get the error. You just don't remove empty directories. But empty directories are relevant only for path preserving and that's managed by mkdir policy.
