### ISSUE TITLE
Unable to modify file permissions

### ISSUE THREAD

**Issue by Skydef** [trapexit/mergerfs#816]
General description
===================
In my previously installed mergerfs version I could change the file/folder permissions with chmod within mergerfs.
Now I receive the error: "chmod: failed to change permissions of '/mnt/virtual/folder/' : Operation not supported"
When mounting with the mergerfs 2.28.x binary chmod still works, when mounting with version 2.30.0 I get this error.

Expected behavior
=================
Use chmod within mergerfs.

Actual behavior
===============
Receiving error using chmod.

**Precise** steps to reproduce the behavior
===========================================

- /usr/local/bin/mergerfs-old -o allow_other,use_ino,category.create=mfs,moveonenospc=true,minfreespace=20G /mnt/data/disk\* /mnt/virtual
- /usr/local/bin/mergerfs-old -V
- [see System information section]
- chmod 2770 /mnt/virtual/folder
- 👍
- umount /mnt/virtual
- mergerfs -o allow_other,use_ino,category.create=mfs,moveonenospc=true,minfreespace=20G /mnt/data/disk\* /mnt/virtual
- mergerfs -V
- [see System information section]
- chmod 2770 /mnt/virtual/folder
- chmod: failed to change permissions of '/mnt/virtual/folder/' : Operation not supported 😟

System information
==================
Please provide as much of the following information as possible:

* [x] mergerfs version: `mergerfs -V`
**Previous:** mergerfs version: 2.28.2-4-gb5f6cd7
&emsp; FUSE library version: 2.9.7-mergerfs_2.28.0
&emsp; fusermount version: 2.9.7
&emsp; using FUSE kernel interface version 7.29
**Current:** mergerfs version: 2.30.0-28-g7ff9956
&emsp; FUSE library version: 2.9.7-mergerfs_2.30.0
&emsp; fusermount version: 2.9.7-mergerfs_2.30.0
&emsp; using FUSE kernel interface version 7.31
* [x] mergerfs settings: `cat /etc/fstab` or the command line arguments
mergerfs -o allow_other,use_ino,category.create=mfs,moveonenospc=true,minfreespace=20G /mnt/data/disk\* /mnt/virtual
* [x] Linux version: `uname -a`
CentOS 8
Linux centos-nas 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* [ ] Versions of any additional software being used
* [x] List of drives, filesystems, & sizes: `df -h`
5 drives, all drives are Ext4 Fs
* [ ] strace of application having problem: `strace -f -o /tmp/app.strace.txt <cmd>` or `strace -f -p <appPID> -o /tmp/app.strace.txt`
* [ ] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Comment by trapexit** [comment]
According to what you posted you are not using 2.30.0. You are using  master. As I say in the docs that is not recommended or supported. Why are you using it?

**Comment by Skydef** [comment]
Sorry, my mistake. I didn't know it was unsupported. I followed the 'Build/Update' section in the readme.md (and didn't use the prebuilt packages). I could not find the paragraph in the readme where you state that master is wip and potentially unsupported/not recommended. Maybe you should put a brief note in the 'Build/Update' section, that you should use the stable prebuilds and not build from source for any productive use.

I've now installed the correct release (mergerfs-2.30.0-1.el8.x86_64.rpm) and everything is working as expected. Thank you!

**Comment by trapexit** [comment]
It's mentioned in the bug report template. I'll add it to the build notes but for most software master is wip.

https://github.com/trapexit/mergerfs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by trapexit** [comment]
#817
