### ISSUE TITLE
Dreaded 'ENOSPC' despite 'mfs' and 'minfreespc' on all drives [NTFS]

### ISSUE THREAD

**Issue by JoeSchr** [trapexit/mergerfs#826]
General description
===================
Hi, there! First of all thanks for this great project, getting it running was a breeze. But now I'm stuck. I read through all the FAQs, Issues and the strace and I believe I tried all the usual problem solvers, but I still can't touch a file on my pool. I can edit and delete files though.

I'm using ntfs btw (and we had a short discussion about migration from drivepool on reddit, but I thought, creating an issue here might help others better)

Ps.: not a native speaker, so please don't hestitate to ask for clarifications

Expected behavior
=================
`/mnt/diskpool $: touch test`
creates file

Actual behavior
===============

`touch: cannot touch 'test': No space left on device`

System information
==================
Please provide as much of the following information as possible:

* [X] mergerfs version: `mergerfs -V`

```
mergerfs version: 2.30.0-38-gb1c6d48
FUSE library version: 2.9.7-mergerfs_2.30.0
fusermount version: 2.9.7-mergerfs_2.30.0
using FUSE kernel interface version 7.31
```

* [X] mergerfs settings: `cat /etc/fstab` or the command line arguments
```
# drive pool disks
PARTUUID="0c5b629e-f07b-49e1-b844-a35ea1915762" /mnt/dp/DT01ACA3/  ntfs-3g   defaults,nls=utf8,umask=000,dmask=027,fmask=137,uid=1000,gid=1000,windows_names 0 0
PARTUUID="7cc61f7b-2288-4045-bb7e-2438d8f27aeb" /mnt/dp/HDWE160/  ntfs-3g   defaults,nls=utf8,umask=000,dmask=027,fmask=137,uid=1000,gid=1000,windows_names 0 0
PARTUUID="cf46f40f-59c1-432d-89f4-be665760836e" /mnt/dp/ST4000DM005-2DP1/  ntfs-3g   defaults,nls=utf8,umask=000,dmask=027,fmask=137,uid=1000,gid=1000,windows_names 0 0
PARTUUID="cc962cbe-01" /mnt/dp/WD15EADS-00S/  ntfs-3g   defaults,nls=utf8,umask=000,dmask=027,fmask=137,uid=1000,gid=1000,windows_names 0 0
PARTUUID="209317a8-507e-41cd-bdc1-cb27df5584be" /mnt/dp/WD15EADS-00P/  ntfs-3g   defaults,nls=utf8,umask=000,dmask=027,fmask=137,uid=1000,gid=1000,windows_names 0 0

# mergerfs disk
/mnt/dp/WD15EADS-00S/PoolPart.2828e811-b105-4382-acaa-4fab3a3dd2ff:/mnt/dp/WD15EADS-00P/PoolPart.9233e6a3-16c8-4cc6-a2a9-1d71e37ac28b:/mnt/dp/ST4000DM005-2DP1/PoolPart.c1a33880-39e3-4ee8-9864-65862f63f85b:/mnt/dp/HDWE160/PoolPart.ee61b84b-a7f1-4fbb-8d02-eb5f66c7f365:/mnt/dp/DT01ACA3/PoolPart.24ee6a2e-2cf1-4df5-8627-488e63e110a7 /mnt/diskpool fuse.mergerfs minfreespace=1M,moveonenospc=true,use_ino,cache.files=partial,dropcacheonclose=true,allow_other,category.create=mfs,defaults,noforget,inodecalc=path-hash,statfs=base,statfs_ignore=ro,fsname=diskpool 0 0


# all disks  
# /dev/sda1: PARTLABEL="Microsoft reserved partition" PARTUUID="e823e01e-9f3c-4322-bc99-0ce5f3862954"
# /dev/sda2: LABEL="3TB-Zac" BLOCK_SIZE="512" UUID="4824DC4D24DC401C" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="0c5b629e-f07b-49e1-b844-a35ea1915762"
# /dev/sdb1: PARTLABEL="Microsoft reserved partition" PARTUUID="0c2072ef-ea49-409c-822f-a47ff38e991e"
# /dev/sdb2: LABEL="6TB-WD-2019" BLOCK_SIZE="512" UUID="E0B69622B695F96C" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="7cc61f7b-2288-4045-bb7e-2438d8f27aeb"
# /dev/sdc1: LABEL="4TB" BLOCK_SIZE="512" UUID="700ECC080ECBC4F6" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="cf46f40f-59c1-432d-89f4-be665760836e"
# /dev/sdd1: BLOCK_SIZE="512" UUID="FAA2F856A2F818B9" TYPE="ntfs" PARTUUID="edbc96fc-01"
# /dev/sdd2: UUID="56479d22-acac-4b91-ae14-34d1bd210290" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="edbc96fc-02"
# /dev/sdd3: PARTUUID="edbc96fc-03"
# /dev/sde1: LABEL="1.6TB-MirrorB" BLOCK_SIZE="512" UUID="8AC849FDC849E7D1" TYPE="ntfs" PARTUUID="cc962cbe-01"
# /dev/sdf1: PARTLABEL="Microsoft reserved partition" PARTUUID="421304b5-d93a-46cc-81e1-8e8db91f07ec"
# /dev/sdf2: LABEL="1.6TB-MirrorA" BLOCK_SIZE="512" UUID="7E3A33673A331C19" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="209317a8-507e-41cd-bdc1-cb27df5584be"
```

* [X] Linux version: `uname -a`
```
Linux RECHENKNElx 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux
```
* [X] List of drives, filesystems, & sizes: `df -h`
```
dev              16G     0   16G   0% /dev
run              16G  996K   16G   1% /run
/dev/sdd2        62G   13G   46G  22% /
tmpfs            16G  123M   16G   1% /dev/shm
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs            16G   55M   16G   1% /tmp
/dev/sdd1        57G   38G   19G  67% /mnt/win
/dev/sde1       1.4T  896G  502G  65% /mnt/dp/WD15EADS-00S
/dev/sdf2       1.4T  142G  1.3T  11% /mnt/dp/WD15EADS-00P
/dev/sda2       2.8T  1.9T  902G  68% /mnt/dp/DT01ACA3
/dev/sdb2       5.5T  4.2T  1.3T  77% /mnt/dp/HDWE160
tmpfs           3.2G   40K  3.2G   1% /run/user/1000
diskpool         11T  7.1T  3.9T  65% /mnt/diskpool
```

* [X] strace of mergerfs while app tried to do it's thing: `strace -f -p <mergerfsPID> -o `

**be aware:** I did `touch test` and there already existed 2 files named `test.sh` and `test-from-ntfs-3g.txt` from when I tested if I could write directly on the mounted drives.

https://gist.github.com/JoeSchr/b0a678333d0a245faed7ac30b276e8bc [strace gist](https://gist.github.com/JoeSchr/b0a678333d0a245faed7ac30b276e8bc) 

Sorry for asking the same questions over and over again, but I'm out of my wits!

**Comment by trapexit** [comment]
Why are you using master? Are you claiming this is a problem with the unreleased master branch vs released versions?

The strace doesn't show any open/create attempts so the policy would have had to returned that error. Meaning they were all filtered.

When testing things you **really** should be simplifying the situation. You have multiple drives and a bunch of random permission tweaks. I just created a single ntfs-3g mount and created a simple mergerfs mount with it and creation of files work fine. With and without all your settings. Can you please create a simpler and more explicit example using a released version?

**Comment by JoeSchr** [comment]
Sure, I will simplify it with 1 drive first and then work my way up.

I already worked out, that the "normal" ntfs-3g package doesn't have fuse
support included, so it couldn't mount without root. But still no luck with
the nospceno.

Regarding master Vs released, I'm not claiming anything, I can't even
remember how I installed it. Probably just `yay -S mergerfs` which then got
it from git master, build it and installed it.

I will check out a released version and then test further.

I'm just glad now I didn't something obvious completely wrong

Thanks for spending your time on this.


__

Typed on a mobile, please excuse any typing mistakes or short-spokeness.

**Comment by JoeSchr** [comment]
So I got it working by installing the release version instead of directly from git
```
$ mergerfs -v
mergerfs version: 2.30.0
FUSE library version: 2.9.7-mergerfs_2.30.0
fusermount version: 2.9.7-mergerfs_2.30.0
using FUSE kernel interface version 7.31
```

now it works flawlessly. 

I also installed `ntfs-3g-fuse` since last posting. but I checked by installing from master again (`mergerfs-git` from AUR, version:  `2.30.0-38-gb1c6d48`) and it stops working, so:


>  Are you claiming this is a problem with the unreleased master branch vs released versions?

sadly yes, I can confirm your initial suspicion


Let me know if I can help you in anyway debugging it.

**Comment by trapexit** [comment]
There is no such revision in my tree as `gb1c6d48`. Not sure what that is.

I'm not sure what's wrong with that build but I just tried master without any issues. Both ntfs mounted with all your options as well as mergerfs.

**Comment by JoeSchr** [comment]
Then everything is fine and let's never talk about it again! ;)

>
>

**Comment by trapexit** [comment]
Hah. Alright. If something comes up feel free to reopen this or create a new ticket.
