### ISSUE TITLE
mergerfs ignore fstab options(?)

### ISSUE THREAD

**Issue by Sdarot** [trapexit/mergerfs#830]
Hello,
I'm facing a problem while setting mount options other than "allow_other".

mergerfs -v

mergerfs version: 2.30.0
FUSE library version: 2.9.7-mergerfs_2.30.0
fusermount version: 2.9.7-mergerfs_2.30.0
using FUSE kernel interface version 7.31

uname -a
`uname -a
Linux Backup 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

my /etc/fstab
``/home/backup/data:/home/backup/nfs /home/backup/merged fuse.mergerfs allow_other,moveonenospc=true,use_ino,inodecalc=path-hash,ignorepponrename=true 0 0``

mount output:
`data:nfs on /home/backup/merged type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)`

as you can see, options like ``use_ino`` ignored.

same `mount` output even if I mount it manually with `mergerfs -o config=mergerfs.conf /home....`

mergerfs.conf (for above command)
```
allow_other
moveonenospc=true
use_ino
inodecalc=path-hash
ignorepponrename=true
```

At first, I thought it count only the first parameter, but that wasn't the case.

What can cause this problem?

**Comment by trapexit** [comment]
Why are you looking at the mount output? That will never show the options. They don't get passed to the kernel. They are mergerfs options. Not FUSE kernel options.
