### ISSUE TITLE
Issues with POSIX ACL and some file operations

### ISSUE THREAD

**Issue by Trezamere** [trapexit/mergerfs#836]
**Describe the bug**
I'm not sure if mergerfs is the root cause or not here, but it appears that some file operations (`truncate`?) are not being handled correctly and I'm getting EPERM errors.

Basically, if I edit a file with mousepad (or gnome text editor), it saves once fine and then trying to save it again I get permission denied (and the file is destroyed / truncated).
If I use e.g. LibreOffice or vim it appears to behave correctly, presumably because they are using temporary files and not truncating.

**To Reproduce**

1. Create user1 and user2 and add them to same group
1. Create a file as user2, give rw to group
1. Set ACL's as specified below (rwx to users and group)
1. Edit and save the file using `xfce mousepad` a couplle times
1. First save works fine?
1. Second save returns permission denied?

**Expected behavior**
File saves without any permission issues.

**System information:**
 - OS, kernel version: `Linux nas-01 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - mergerfs version: 
```
mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```
 - mergerfs settings: `mergerfs /mnt/data/* /mnt/pool -o rw,allow_other,noforget,direct_io,use_ino,category.create=eplus,moveonenospc=true,minfreespace=15G,fsname=mergerfs,posix_acl=true,dev,suid`
 - A strace of the application having a problem:
```
[13:21:35]user1@bosch:~$ strace -p $(pgrep mousepad) -e trace=file -P '/home/user1/Documents/nas/house/todo-new.md'
strace: Requested path "/home/user1/Documents/nas/house/todo-new.md" resolved into "/mnt/documents/house/todo-new.md"
strace: Process 91494 attached
access("/home/user1/Documents/nas/house/todo-new.md", F_OK) = 0
stat("/home/user1/Documents/nas/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=0, ...}) = 0
openat(AT_FDCWD, "/home/user1/Documents/nas/house/todo-new.md", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 13
stat("/home/user1/Documents/nas/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=8, ...}) = 0
openat(AT_FDCWD, "/home/user1/Documents/nas/house/todo-new.md", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EPERM (Operation not permitted)
```
 - strace of mergerfs while app tried to do it's thing:
```
[root@nas-01 ~]# strace -e trace=file -p 931 -f -P '/mnt/data/disk3/documents/house/todo-new.md'
strace: Process 931 attached with 3 threads
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lgetxattr("/mnt/data/disk3/documents/house/todo-new.md", "system.posix_acl_access", "\2\0\0\0\1\0\6\0\377\377\377\377\2\0\7\0\271\v\0\0\2\0\7\0\272\v\0\0\4\0\7", 4096) = 60
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] openat(AT_FDCWD, "/mnt/data/disk3/documents/house/todo-new.md", O_RDONLY|O_LARGEFILE) = 9
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] lgetxattr("/mnt/data/disk3/documents/house/todo-new.md", "system.posix_acl_access", "\2\0\0\0\1\0\6\0\377\377\377\377\2\0\7\0\271\v\0\0\2\0\7\0\272\v\0\0\4\0\7", 4096) = 60
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] lgetxattr("/mnt/data/disk3/documents/house/todo-new.md", "system.posix_acl_access", "\2\0\0\0\1\0\6\0\377\377\377\377\2\0\7\0\271\v\0\0\2\0\7\0\272\v\0\0\4\0\7", 4096) = 60
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] openat(AT_FDCWD, "/mnt/data/disk3/documents/house/todo-new.md", O_WRONLY|O_LARGEFILE) = 9
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   936] lgetxattr("/mnt/data/disk3/documents/house/todo-new.md", "system.posix_acl_access", "\2\0\0\0\1\0\6\0\377\377\377\377\2\0\7\0\271\v\0\0\2\0\7\0\272\v\0\0\4\0\7", 4096) = 60
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=7, ...}) = 0
[pid   937] truncate("/mnt/data/disk3/documents/house/todo-new.md", 0) = 0
[pid   937] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=0, ...}) = 0
[pid   937] utimensat(AT_FDCWD, "/mnt/data/disk3/documents/house/todo-new.md", [UTIME_OMIT, UTIME_NOW], AT_SYMLINK_NOFOLLOW) = -1 EPERM (Operation not permitted)
```

**Additional context**
Perms for file in question:
```
-rw-rw----. 1 user2 documents    0 Oct  2 13:22  todo-new.md

```
user1 is uid: `3001` and in group `documents:6000`
user2 is uid: `3002` and in group `documents:6000`

ACL for file in question:
```
getfacl /mnt/pool/documents/house/todo-new.md 
getfacl: Removing leading '/' from absolute path names
# file: mnt/pool/documents/house/todo-new.md
# owner: user1
# group: documents
user::rw-
user:user1:rwx			#effective:rw-
user:user2:rwx		#effective:rw-
group::rwx			#effective:rw-
group:documents:rwx		#effective:rw-
mask::rw-
other::---
```

NFS4_ACL for file in question:
```
nfs4_getfacl Documents/nas/house/todo-new.md 

# file: Documents/nas/house/todo-new.md
A::OWNER@:rwatTcCy
A::3001:rwatcy
A::3002:rwatcy
A::GROUP@:rwatcy
A:g:6000:rwatcy
A::EVERYONE@:tcy
```

**Comment by trapexit** [comment]
What's the underlying filesystem?

**Comment by Trezamere** [comment]
`/dev/sdd1 /mnt/data/disk3 xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0`

**Comment by trapexit** [comment]
Hmm. As you can see mergerfs is getting the error: `[pid   937] utimensat(AT_FDCWD, "/mnt/data/disk3/documents/house/todo-new.md", [UTIME_OMIT, UTIME_NOW], AT_SYMLINK_NOFOLLOW) = -1 EPERM (Operation not permitted)` It's running as the client's uid and gid. And you can see the getxattr calls. I'm really not sure. The kernel version seems fine. You didn't create user2 after mergerfs started did you? TBH I've never used POSIX ACLs with mergerfs and the docs aren't super clear. Would need to look into it more. 

And not that I expect anything to change in this space but just to be thorough I'd suggest updating to 2.30.0 or 2.31.0. Even if only because the code has been cleaned up and will be easier to compare.

**Comment by Trezamere** [comment]
No, user2 exists before mergerfs starts and no change with 2.31.0.  I'm not sure how you tell it's running as the client's (mergerfs?) uid/gid, unless you just mean mergerfs is trying to set the time and getting permission denied. In that case mergerfs is running as root as a systemd service-mount.

**Comment by trapexit** [comment]
mergerfs always runs relevant commands as the client's uid/gid (assuming it was started as root). It's part of the protocol between the kernel and the server (mergerfs). The client is the app making the request. The kernel asks mergerfs to set the time and as I showed the kernel then returns EPERM when it tries. Probably due to the posix acls but I really don't know why. Does it error when you `touch` a file?

**Comment by Trezamere** [comment]
No, however now I'm not seeing file updates which is weird. Some caching issue and/or behaviour change to v2.31 I didn't read?

```
[12:16:08]user1@bosch:~/Documents/nas/house$ ll
total 8
drwxrws---. 8 user1 documents 4096 Sep 30 11:35  Rentals
-rw-rw----. 1 user2 documents    0 Oct  3 18:43  todo-new.md
[12:16:08]user1@bosch:~/Documents/nas/house$ ll newfile
-rw-rw----. 1 user1 documents 5 Oct  5 11:52 newfile
```
Notice newfile not showing up unless I explicitly ls it.

There are some generic bind mounts that are exported via NFS.

```
[Mount]
Where=/srv/nfs/documents
What=/mnt/pool/documents
Type=none
Options=bind
```

```
# exportfs
/srv/nfs/documents
		192.168.1.0/25
```

**Comment by trapexit** [comment]
You're using NFS? You indicated it was xfs.

**Comment by trapexit** [comment]
No, you're not hitting that issue. That's about NFS splitting apart EXCL|CREAT calls which breaks POSIX expectations. A known issue going back many years that software is supposed to try to work around but often doesn't. This situation as your strace shows indicates the kernel denying mergerfs permission when trying to set the time as mentioned above.

**Comment by trapexit** [comment]
All changes are in the changelog. There were no caching changes but if you're changing things out of band then of course you can have weird issues. Especially with network filesystems. I didn't touch anything with readdir in 2.31.0 from 2.30.0. I did in 2.30.0 though to fix issues with NFS. I've not heard any reports of issues.

**Comment by Trezamere** [comment]
> You're using NFS? You indicated it was xfs.

mergerfs is pooling several disks that are formatted xfs, that pool (via a bind mount) is exported by NFS to clients. In the strace logs above, the '/mnt/data/disk3/' is the xfs formatted disk on the server. The strace of the application is on my desktop.


> No, you're not hitting that issue. That's about NFS splitting apart EXCL|CREAT calls which breaks POSIX expectations. A known issue going back many years that software is supposed to try to work around but often doesn't. This situation as your strace shows indicates the kernel denying mergerfs permission when trying to set the time as mentioned above.

Sorry I'm probably confusing you, the issue I'm seeing in my last post is new and different from the OP. I was associating it with this thread since it seemed related to the 'touch' test you mentioned above. I'll roll back to 2.29 and see if it still happens.

> All changes are in the changelog. There were no caching changes but if you're changing things out of band then of course you can have weird issues. Especially with network filesystems. I didn't touch anything with readdir in 2.31.0 from 2.30.0. I did in 2.30.0 though to fix issues with NFS. I've not heard any reports of issues.

I'm not sure I follow what you mean by 'out of band' but I have rebooted the server after each change (e.g. version upgrade) just to flush any potential state issues out the window. Same with my desktop client.

**Comment by trapexit** [comment]
You **must must must** let me know that you're using NFS. NFS is a unique beast and drastically changes what and how I investigate anything. FUSE and NFS don't play well together.

I'm not really sure what you were talking about in the previous post. It wasn't clear what you were talking about. You touched a file and it didn't show up? This stuff is complicated and I need as much information as possible. We're talking about 3 levels of indirection and every app behaves in it's own ways.

"out of band" meaning not through mergerfs or nfs or what have you. Out of band from the primary path client ->nfsclient -> nfsserver -> mergerfs -> filesystem. If you change the filesystem directly or through NFS and not through mergerfs.

**Comment by Trezamere** [comment]
I've been pretty busy so haven't been able to come back to this until recently; I tried taking the NFS server out of the picture and just editing the file directly on the server owned by the other user, however none of the applications I've tried to use appear to be using the same calls (specifically truncate and utimensat) I've tried vi/vim/nano and truncate (oddly enough doesn't call truncate()).

I was able to see the same error as originally reported through NFS using vim; however vim seemed to handle it gracefully and still save the file properly...

```
truncate("/mnt/data/disk3/documents/house/todo-new.md", 0) = 0
[pid   943] lstat("/mnt/data/disk3/documents/house/todo-new.md", {st_mode=S_IFREG|0660, st_size=0, ...}) = 0
[pid   943] utimensat(AT_FDCWD, "/mnt/data/disk3/documents/house/todo-new.md", [UTIME_OMIT, UTIME_NOW], AT_SYMLINK_NOFOLLOW) = -1 EPERM (Operation not permitted)

```


Perhaps this is a non-issue for mergerfs and there is some issue with NFS or how I have it configured.
