### ISSUE TITLE
fuse: device not found, try 'modprobe fuse' first during init

### ISSUE THREAD

**Issue by Abbotta4** [trapexit/mergerfs#838]
**Describe the bug**
mergerfs fails to mount the pool fs with fstab during init with the error in the title. 

**To Reproduce**
Rebooting the machine causes Linux to fail to boot every time with the error in the title.

**Expected behavior**
I expected mergerfs to mount the filesystem without error.

**System information:**
 - OS, kernel version: Arch Linux, Linux 5.8.12-arch1-1
 - mergerfs version: 2.30.0
 - mergerfs settings: allow_other,minfreespace=20G,moveonenospc=true,use_ino,dropcacheonclose=true,ignorepponrename=true,category.create=lus,cache.files=partial,xattr=nosys,func.getattr=newest,fsname=/mnt/pool
 - List of drives, filesystems, & sizes: two 12TB ext4 drives and a 4TB ext4 drive
 - A strace of the application having a problem: N/A
 - strace of mergerfs while app tried to do it's thing: N/A

**Additional context**
mergerfs successfully mounts the filesystem after Linux has booted. The filesystem only fails to mount during boot.

**Comment by trapexit** [comment]
Please provide all the relevant information. I can't comment on fstab entry if you don't provide it.

If it fails at startup it's almost always a race condition with the source or destination. Do all your source paths exist at the time? Does the mount point?
