### ISSUE TITLE
inotify and mergerfs

### ISSUE THREAD

**Issue by audiomuze** [trapexit/mergerfs#839]
I have two drives mounted in fstab as follows:
`/alib/ext4e:/alib/ext4f   /alib/roonpool   fuse.mergerfs   defaults,allow_other,use_ino,fsname=mergerFS   0   0`

The two drives contain my music library and I'm reliant on the music server detecting changes to files to rescan the underlying content for metadata changes.

```
cat /proc/sys/fs/inotify/max_user_watches returns:
524288
```

Prior to using mergerfs I pointed the music server to the folder containing the mount points of the two drives.  Any changes to a date and/or timestamp would be notified by the OS and the music server would rescan affected content.  Since switching to mergerfs and pointing the music server to /alib/roonpool it no longer detects changes or additions to content on either drive so I'm forced to trigger a rescan of the /roonpool, following which changes/additions are detected and ingested as expected.

So, after that background, my question is does inotify announce changes to mergerfs?

**Comment by audiomuze** [comment]
and resolved , see Kodi et al at https://github.com/trapexit/mergerfs#tips--notes - you will want to set func.getattr=newest

so the fstab entry becomes:
`/alib/ext4e:/alib/ext4f   /alib/roonpool   fuse.mergerfs   defaults,allow_other,use_ino,func.getattr=newest,fsname=mergerFS   0   0`

**Comment by dannymichel** [comment]
> getattr=newest

its not working forr me anymore. it used to
