### ISSUE TITLE
Is it a bad idea to double mount?

### ISSUE THREAD

**Issue by rammellzee** [trapexit/mergerfs#840]
I currently use mergerfs to mount a bunch of drives together. I'm in a situation where I would like to mount rclone along with my current setup. 
    
However, I'd like to use the FF policy for creating files. So I'm wondering whether it would be ok to create a new mergerfs mount that just includes my existing mergers mount path + rclone.  

Thanks.

**Comment by trapexit** [comment]
I don't really understand the question. What do you mean "double mount?" You should generally avoid unnecessary abstraction. Can you describe *exactly* what you're trying to accomplish?

**Comment by rammellzee** [comment]
> I don't really understand the question. What do you mean "double mount?" You should generally avoid unnecessary abstraction. Can you describe _exactly_ what you're trying to accomplish?

Sorry, basically I would like to run a 2nd mergerfs mount which includes a path which is an existing mergerfs mount. Wondering if that is a bad idea.

My current mergerfs mount has: Disk1, Disk2, Disk3

I'd like to add cloud storage via rclone to that mount, but I only want to write to the first 3 local disks. Mounting the rclone remote as read-only isn't an option since it won't work with some apps.

**Comment by trapexit** [comment]
Yes, it's a bad idea. You're adding abstraction to abstraction unnecessarily. What benefit is that to simply having a second pool with the same branches + the rclone mount and tagging the rclone branch RO so it is excluded from create calls?

**Comment by rammellzee** [comment]
Tagging the rclone branch as RO still lead to errors when I tried to create directories. 

What I wanted to accomplish was use the epmfs policy for all my local disks but exclude the rclone mount, thats why I wanted to run mergerFS twice so I could use the "ff" policy on the 2nd mount so that it would accomplish this.

Doesn't seem like this is a good idea so I'll drop it.

**Comment by trapexit** [comment]
What errors? What settings did you use. The create policies completely ignore on NC or RO

**Comment by rammellzee** [comment]
Oh I didn't know you could tag them on mergerfs with NC/RO. I was mounting rclone as read-only which led to errors. Using NC works. This is what I wanted to do, thank you.
