### ISSUE TITLE
MergerFS and hardlinks

### ISSUE THREAD

**Issue by Leseratte10** [trapexit/mergerfs#841]
Hi everyone, 

I currently have a setup with one 12TB harddrive for data, and one 14TB harddrive for backups. 
Backups are using hardlinks with a script like this: 

```bash
#!/bin/sh

src=/media/me/data
dst=/media/me/backup/backups/
today=$(date +%Y-%m-%d)

rsync --progress -avR --delete "${src}"  "${dst}${today}/" --link-dest="${dst}last/"
ln -nsf "${dst}${today}" "${dst}last"
```

This creates, on the backup drive, a folder named 2020-11-09 for today's backup, and a softlink "last" that always points to the most recent backup. In addition to that, files that haven't been modified since the last backup are hardlinked so they don't occupy the space again. 

Both the data drive and the backup drive are beginning to get full, so I'm looking into using MergerFS with some new harddrives in the future. 

Meaning, I'd have one "data" pool that merges the existing 12TB data drive plus a new data drive; and one seperate "backup" pool that merges the existing 14TB backup drive plus a new backup drive. However, reading the documentation, that could cause issues with cross-device hardlinks. 

When there is so much data (or so many different old backups) that the first drive in the backup pool would get full, the rsync would probably either A) fail because it can't create hardlinks, or B) make yet another full backup on the 2nd backup pool drive when it gets the EXDEV error. 

I read all the documentation but I'm unsure on how to best get around this issue. 
Can I just add the "backup/backups" folder on both drives in the backup pool and MergerFS will handle that automatically, meaning, put hardlinks to existing files on the same drive as the existing file, and other new files on the other backup drive?

If not, is there another easy solution to this problem?
Or am I misinterpreting the documentation and this shouldn't be a problem at all?
I'd just like to fully understand that before I switch to MergerFS and then my backup no longer works when the 1st backup drive gets full ...

**Comment by trapexit** [comment]
The behavior of rename and link are based on how you set things up.

https://github.com/trapexit/mergerfs#rename--link

The drive selected for link depends on create policy and ignorepponrename value. If you don't care about strict path preservation then there is nothing for you to concern yourself with so long as there is space for the additional directories and inodes. EXDEV is returned only as described in the docs. That is: only if you have a situation / config where the link dest location is cross device.

**Comment by Leseratte10** [comment]
Thanks for the quick answer. So, for example, if I use `mfs` as policy that would mean that newly created files would go on the new (empty) drive, but new hardlinks to old existing files on the old drive would still go on the old drive just fine?

**Comment by trapexit** [comment]
Yes
