### ISSUE TITLE
LFS + ignore existing path possible? (Tiered Caching)

### ISSUE THREAD

**Issue by zilexa** [trapexit/mergerfs#842]
As described here: 
https://github.com/trapexit/mergerfs#tiered-caching

I have 2 pools, using Ubuntu Budgie 20.04.1, all drives are EXT4. 
The Cache+Data pool consists of a folder on my system SSD (/mnt/data/cache) and 2 HDDs (disk1, disk2). 
 The Data-Only pool has only disk1 and disk2:
```
# CACHE+DATA POOL (MergerFS)
/mnt/data/cache:/mnt/data/disk1:/mnt/data/disk2 /mnt/pool fuse.mergerfs allow_other,cache.files=auto-full,dropcacheonclose=true,use_ino,category.create=lfs,moveonenospc=true,minfreespace=350G,fsname=mergerfsPool 0 0
# DATA-ONLY POOL (MergerFS)
/mnt/data/disk1:/mnt/data/disk2 /mnt/archive fuse.mergerfs allow_other,cache.files=auto-full,dropcacheonclose=true,use_ino,category.create=epmfs,moveonenospc=true,minfreespace=100G,fsname=mergerfsPool 0 0
```
I access all my data via /mnt/pool (= the 1st pool). 
- I have a lot of existing data. This means the commonly used folder paths  already on the DATA-ONLY pool. Because of this, the first pool is barely used. 
- 9/10 times new files/folders are created within an existing folder structure. This constantly wakes up my my harddrives. 
- The SSD (/mnt/data/cache) is barely used. 

This is not what I expected from "LFS" after reading this: https://github.com/trapexit/mergerfs#why-are-all-my-files-ending-up-on-1-drive It is the reason I selected LFS, because for `create` it says `Create: Pick the drive with the least available free space.`
Still, it seems it simply looks at Existing Path. 

I read the whole manual but could not figure out a way to "force" new file/folders to be created on the CACHE+DATA pool, regardless of existing paths on the harddrives. 
Is there a way to achieve this?

I already have `category.create=lfs`, should I add `category.search` and `category.action` set them all to LFS (for the first pool only)?

**Comment by trapexit** [comment]
You're not saying how much space the cache drive has but you set minfreespace=350G which means any drive with less than 350G is skipped. Are you positive your cache has that much space?

There is no forcing or not. The policies work exactly as described. The branch with the least free space that isn't mounted readonly, that isn't tagged RO or NC, or has less than minfreespace. The path's existence is not considered at all (just the general existence of the branch. 

> This constantly wakes up my my harddrives.

Your drives will wake up when accessed. mergerfs won't change that. mergerfs has to know what is where. That requires reading the device. If you want to limit needing to read you should look at the other caching options.

**Comment by zilexa** [comment]
It is a 1TB SSD with currently 630GB free space. I have set that limit of 350 pretty high and planned to lower it to 100GB.

I didn't fully understand the other caching options at first, but it makes a bit more sense now that I read them again. Because I didn't consider this:
> mergerfs has to know what is where. That requires reading the device
That makes total sense!

I will enable `cache.readdir` cache.entry` `cache.attribute` and also `cache.statfs` and `cache.symlink`. 
Before I do that, I will carefully move some folders manually to try to get the full path completely on the SSD of folders that are commonly used for new file/folder creation.

**Comment by trapexit** [comment]
You don't have to create the paths. As I mentioned... the paths play no role in selecting a device. You can easily test by touching a random file in the pool and looking for it on the underlying devices or using the xattr tool to find it as mentioned in the docs.

**Comment by zilexa** [comment]
Thank you for the help, I have changed my mount commands and it works more as expected now.
