### ISSUE TITLE
NFS export on mergerfs only 101 files/dir show up on client

### ISSUE THREAD

**Issue by Dan-RAI** [trapexit/mergerfs#846]
**Describe the bug**
NFS exported mergefs fused drive shows on client side only max 101 files per directory.

**To Reproduce**
NFS export directory with 1000s of files.

**Expected behavior**
All files show up on client

**System information:**
 - OS, kernel version: Linux 5.4.34-1-pve SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200) x86_64 GNU/Linux
 - mergerfs version: 
mergerfs version: 2.29.0-25-gbed493e
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
 - mergerfs settings
mergerfs -o defaults,allow_other,use_ino,category.create=mfs,moveonenospc=true,fsname=vault /mnt/NAS_disk\* /VAULT

**Comment by trapexit** [comment]
Please use a current released version of the software for reports unless it's explicitly related to an unreleased version.

**Comment by Dan-RAI** [comment]
Thanks, upgrading to mergerfs 2.31.0 seems to solve the issue.
