### ISSUE TITLE
mergerfs[11326]: segfault

### ISSUE THREAD

**Issue by YueIan** [trapexit/mergerfs#849]
Hi, mergerfs is very useful for me. 

**Describe the bug**
mergerfs crushed. The error log is:
mergerfs[11326]: segfault at 3200000009 ip 0000560f5f25a204 sp 00007f16b36f3390 error 6 in mergerfs[560f5f212000+6a000]
I set the vdisk generated by mergerfs to samba's share path.

**To Reproduce**
Do not know the steps to reproduce. 

Expected behavior
I expected mergerfs running without error.

**System information:**

OS, kernel version: Linux version 4.15.0-55-generic (buildd@lcy01-amd64-029) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))
mergerfs version: 2.32.0
mergerfs settings: mergerfs -o defaults,allow_other,use_ino,category.create=mfs,moveonenospc=true,minfreespace=1M /mnt/sdb:/mnt/sdc:/mnt/sdd /vdisk
List of drives, filesystems, & sizes: 3 10TB ext4 drives
A strace of the application having a problem: N/A
strace of mergerfs while app tried to do it's thing: N/A

**Additional context**
Before segfault,  there are a lot of IO and mergerfs has been running about 5 day well.

**Comment by trapexit** [comment]
Please provide the information requested in the ticket template.

**Comment by trapexit** [comment]
Please try 2.32.1. I don't know for sure if this is what you hit but I addressed what I found.

**Comment by YueIan** [comment]
Thank you very much. I have pulled the new version.  Because the mergerfs is used online, I will upgrade it later.

**Comment by trapexit** [comment]
Have you been able to test?

**Comment by YueIan** [comment]
It is seems OK. Thank you very much!
I think we can close this issue now.
