### ISSUE TITLE
rtorrent does not start downloading at all on the mergerfs mountpoint

### ISSUE THREAD

**Issue by naseif** [trapexit/mergerfs#853]
Hi, 

I am trying mergerfs for the first time and I am very happy with the result so far. However when I add a torrent file to download on my mountpoint it shows that its downloading but the downlooad does not start all and looks like rtorrent can not write the data on the mountpoint. It does create the files and the folder for the stuff I am trying to download but it does not start and get stuck at 0%. When I login with ssh I can write/delete/move/rename stuff so I am 100% its not a permission issue. I tried everything so far and looked for solutions but could not find any on my own. Here are the options I am using to mount my drives 

 /mnt/disk*   /home/homeserver/media   fuse.mergerfs rw,direct_io,default_permissions,allow_other,minfreespace=50G,fsname=mergerfs  0 0 

OS : Debian 10
mergerfs version : 2.24.2-4

I hope you can help me solve this issue 

Best regards

**Update** : I treid downloading on one of my disks located at /mnt and it started without any issue. Looks like something is wrong with my mount options?

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#you-do-need-mmap-used-by-rtorrent-and-some-other-programs
https://github.com/trapexit/mergerfs#rtorrent-fails-with-enodev-no-such-device

Generally you should try to use the latest release too.
