### ISSUE TITLE
MergerFS Tiered Cache pool with BTRFS snapshots

### ISSUE THREAD

**Issue by zilexa** [trapexit/mergerfs#859]
Tier 0: 1TB SSD, 2x 5TB HDD
Tier 1: 2x 5TB HDD (the same as in T0). 
All are BTRFS formatted and only have their default single subvolume, no RAID, none contain the OS/system. All are dedicated for data. 

This is how I use it now: 
```
# MergerFS ~ T0
/mnt/disks/ssd:/mnt/disks/hdd1:/mnt/disks/hdd2 /mnt/pool fuse.mergerfs allow_other,cache.files=auto-full,dropcacheonclose=true,cache.readdir=true,cache.statfs=true,cache.symlinks=true,cache.entry=3,cache.attr=3,cache.negative_entry=2,use_ino,category.create=lfs,moveonenospc=true,minfreespace=350G,fsname=mergerfsPool 0 0
# MergerFS ~ T1
/mnt/disks/hdd1:/mnt/disks/hdd2 /mnt/pool-archive fuse.mergerfs allow_other,cache.files=auto-full,dropcacheonclose=true,cache.readdir=true,cache.statfs=true,cache.symlinks=true,cache.entry=3,cache.attr=3,cache.negative_entry=2,use_ino,category.create=epmfs,moveonenospc=true,minfreespace=100G,fsname=mergerfsPool 0 0
#
```
(T1, /mnt/pool-archive is only used by the nightly script to write files older than 30 days from T0 to T1.)

Currently, /mnt/pool is the T0 MergerFS mount point and contains all my data, this is the structure: 

> /mnt/pool/Users/user1/.../.../...
> /mnt/pool/Users/user2/.../.../...
> /mnt/pool/Users/user3/.../.../...
> /mnt/pool/Collections/collection1/.../.../...
> /mnt/pool/Collections/collection3/.../.../...
> /mnt/pool/Collections/collection2/.../.../...

Idea: 
Each user and collection folder should have their own snapshots folder containing chronological overview of snapshots, created by https://github.com/3coma3/btrfs-backup

To do this:

1. Replace the folders UserX and CollectionX for nested BtrFS subvolumes and create them with identical path and name on _every_ drive (SSD, HDD1, HDD2).
2. Use [btrfs-backup](https://github.com/3coma3/btrfs-backup) to create daily/weekly/monthly snapshots. 
3. Btrfs-backup will access the drives and subvolumes on those drives directly instead of via MergerFS. But it will only write to the UserX/snapshots and CollectionX/snapshots folders. 

The result: 
When MergerFS writes files to the pool, it does not matter if the data is scattered across the drivepool in the different subvolumes of a single user/collection, since MergerFS shows a merged overview of the drives, which include the subvolumes-as-folders and the snapshot folder of each subvolume, the user will see all snapshots per subvolume in a single snapshot folder. 

Do you see issues with this solution?

**Comment by trapexit** [comment]
Outside possible caching issues given you have a number of them enabled? No.
