### ISSUE TITLE
MergerFS time based script deletes files >30 days

### ISSUE THREAD

**Issue by zilexa** [trapexit/mergerfs#868]
**Describe the bug**
I used this script:: 
https://github.com/trapexit/mergerfs#time-based-expiring
And it actually deletes ALL files that it should move. I lost a lot of files permanently before figuring out this script was the culprit, as it has been running for over a week every night. 

**To Reproduce**
Add an exclude, like I did below, this way, all files in the exclude folder are still present in the Cache and Backing pools. 
Other files outside this dir are deleted if older than 30 days. 
```
#!/bin/bash

# Print expected input if no valid input is given
if [ $# != 3 ]; then
  echo "usage: $0 <cache-drive> <backing-pool> <days-old>"
  exit 1
fi

# Variables
CACHE="${1}"
BACKING="${2}"
N=${3}
# Not required but handy, get path to this script
SCRIPTDIR="$(dirname "$(readlink -f "$BASH_SOURCE")")"

# Find access time of files in cache pool, move with rsync if >N, log to a file next to script.
find "${CACHE}" -type f -atime +${N} -printf '%P\n' | nocache rsync --exclude-from=${CACHE}/Local/Asterix/TV --files-from=- -axHAXWES --progress --preallocate --remove-source-files "${CACHE}/" "${BACKING}/" >> ${SCRIPTDIR}/pool_archiver.log 2>&1

```

**Expected behavior**
instead of moving the files, they get deleted. 

**System information:**
 - OS, kernel version: ubuntu 20.10
mount: 
```
# MergerFS ~ DATA POOL (with SSD as cache)
/mnt/disks/cache:/mnt/disks/disk1:/mnt/disks/disk2:/mnt/disks/disk3 /mnt/pool fuse.mergerfs allow_other,cache.files=auto-full,dropcacheonclose=true,cache.readd>
# MergerFS ~ ARCHIVE POOL (without SSD as cache)
/mnt/disks/disk1:/mnt/disks/disk2:/mnt/disks/disk3 /mnt/pool-archive fuse.mergerfs allow_other,cache.files=auto-full,dropcacheonclose=true,cache.readdir=true,c>
#58 

**Additional context**

**Comment by trapexit** [comment]
How do you call the script?

**Comment by zilexa** [comment]
Verified the behavior via terminal:
```
sudo /home/asterix/docker/SCRIPTS/pool_archiver/pool_archiver.sh /mnt/pool/Users /mnt/pool-archive/Users 21
```
where /mnt/pool and /mnt/pool-archive are the 2 MergerFS mount points.

**Comment by trapexit** [comment]
That's not how it's supposed to be used and would clearly delete files as described https://github.com/trapexit/mergerfs#mv-mntpoolfoo-mntdisk1foo-removes-foo

Notice the argument list. `usage: $0 <cache-drive> <backing-pool> <days-old>`

"cache-drive" not "cache-pool"

**Comment by zilexa** [comment]
Damn now I see my mistake :(
it is basically moving files away from location A, to location A(-1).

**Comment by zilexa** [comment]
Yes I noticed it just as as pasted that command again.. stupid mistake. 

Sorry to bother you, thanks for the quick reply.

**Comment by trapexit** [comment]
I've been meaning to make more elaborate versions of these but haven't gotten to it. I'll add a notice to try to make sure people understand the difference.

**Comment by trapexit** [comment]
No bother. I should be more clear in the docs about the situation.
