### ISSUE TITLE
MergerFS (rclone + zfs) Very Slow - looking to troubleshoot

### ISSUE THREAD

**Issue by kennyparsons** [trapexit/mergerfs#869]
Hey @trapexit ,

First, thank you so much for the amazing work with mergerfs. I've been using it daily for a long time now. 

Now on to the question:

I use mergerfs to fuse a local data directory (a zfs storage pool) with an rclone remote. It's a pretty typical setup:

- new writes go to the local storage (zfs pool)
- local storage gets uploaded to the cloud storage overnight
- local file is deleted after uploading
- rinse and repeat

This setup has been working for a very long time with no issues. But I recently introduced zfs (before was just ext4). Now, when I try to browse files (like a simple `ls` or `cd`) in the merged directory, the machine hangs and takes forever to respond.

Here are the specs:
- mergerfs version: 2.32.2
- rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5
- mergerfs systemd:
```
[Unit]
Description = /gvault MergerFS mount - zfs and cvault
After=cvaultrclonemount.service

[Mount]
What = /datapool/rclone-cache:/mnt/rclone/cvault
Where = /gvault
Type = fuse.mergerfs
Options = async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=auto-full

[Install]
WantedBy=multi-user.target
```

Is there anything obvious for me to test? What would you need from me to dig into the problem. 

Thanks again!

**Comment by trapexit** [comment]
What's the load, memory, and swap look like? zfs as I understand (which I don't have much experience with) uses a decent amount of memory. If it feels laggy and blocking it could be a RAM issue. Data being put in the swap.

You have cache.files=auto-full and don't have dropcacheonclose=true which would generally lead to increased memory usage.

**Comment by kennyparsons** [comment]
I added `dropcacheonclose=true`, as it needs to be in there regardless.

As far as the load, I don't know how I could answer that. What kind of load stats do you need?

Memory=4gb with an 8gb swap.

**Comment by trapexit** [comment]
"load" is a value on any unix system.

cat /proc/loadavg

or look at top or htop or similar tool. 

Use 'free' to find memory usage. Or top/htop/etc.

**Comment by trapexit** [comment]
What is the swap on? HDD? SSD? If you're hitting swap it might be better to just turn it off.

**Comment by kennyparsons** [comment]
Load Average was `0.00 0.02 0.00` when trying to `ls` a directory. 

Swap is a separate vmdk, which is on a 10K SAS drive.

**Comment by kennyparsons** [comment]
I have noticed a slight improvement after a reboot/adding the droponclose value. I may just need to allocate a bit more ram.

**Comment by trapexit** [comment]
dropcacheonclose should only improve things in so much as it'd help clear out cache bloat. You need to look at the RAM and swap usage to understand if that's the issue.

**Comment by kennyparsons** [comment]
Would serving up the merged directory over NFS add to the problem? Right now, the mount is a target for one of my NFS exports.

**Comment by trapexit** [comment]
Lots of things could be issues but without metrics I'm shooting in the dark.

**Comment by kennyparsons** [comment]
RAM appears to have been the culprit. I'll keep monitoring it.

**Comment by trapexit** [comment]
I'll close this for now. If you find anything that is due to mergerfs in this situation feel free to reopen or create a new ticket.

**Comment by ronioncloud** [comment]
I am suffering from 0kbps drops when I try to move the files to the drive, any solution for mergerfs + rclone mount?

**Comment by trapexit** [comment]
Please create a new ticket or join the discord for help. 

https://github.com/trapexit/mergerfs#support

**Comment by kennyparsons** [comment]
@trapexit I'm actually going to re-open this thread. The MergerFS performance has been unusable lately. It is extremely slow and sometimes won't even list directories for me. I updated to the latest. What can we further troubleshoot?

**Comment by trapexit** [comment]
Sounds like something on your system. Have you looked at the load? IO of devices? straced mergerfs to see what is taking time to execute? Minimized the setup to remove complexities? Like rclone which is a remote filesystem and inherently highly latent?

**Comment by trapexit** [comment]
If you look at your settings you're setting yourself up for buffer bloat unless you've got direct-io enable for rclone. You also have async-read=false which will harm read performance. You have no caching of readdir or other things. These all add up. Especially with a slow remote filesystem. There is a section in the docs about performance. Have you evaluated your options there?

**Comment by kennyparsons** [comment]
Load average: 5.72 7.34 7.88
I'm not familiar with strace. Any recommendations for usage to get the data you need to troubleshoot?

**Comment by kennyparsons** [comment]
I ran strace for a few minutes and it generated a massive log file (only about 40 mb, but thousands of lines). Do you want me to upload it or is there something specific you want to see.

**Comment by kennyparsons** [comment]
What's weird now is that the merged directory is working decently fine. Not super fast, but usable. But other things on the machine are just crawling. But not everything. So I think load, ram, and/or io is my next step in troubleshooting, according to that doc and your comments above. 
This is new territory for me, so forgive me if these sound noobish. 

As far as IO, what's the best way to see if IO is causing the queueing.

**Comment by trapexit** [comment]
https://www.2daygeek.com/linux-disk-io-performance-monitoring/

A number of tools in this space. One problem with iostat or any disk based tool is that it won't be able to return metrics about filesystems like mergerfs or rclone since they have no underlying device. Honestly, I've never found a tool that really makes tracking down such issues easy.
