### ISSUE TITLE
Fully static binary

### ISSUE THREAD

**Issue by rominf** [trapexit/mergerfs#872]
**Is your feature request related to a problem? Please describe.**
I want to distribute mergerfs binary along with my software. I'm targeting all x86_64 GNU/Linux distributions. 

**Describe the solution you'd like**
It would be great to have fully static binary uploaded to releases.

**Describe alternatives you've considered**
I could build it by myself, but your GitHub looks more trustworthy :-)

**Additional context**
Here is the output of ldd on my machine (Fedora 33, x86_64):
```
$ ldd mergerfs
	linux-vdso.so.1 (0x00007ffdbf0ea000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1db47a1000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1db4786000)
	libc.musl-x86_64.so.1 => not found
	libm.so.6 => /lib64/libm.so.6 (0x00007f1db4640000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1db4475000)
	/lib/ld-musl-x86_64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f1db4a1a000)
```

So, as you've might guess, it doesn't start. `mergerfs` is extracted from `mergerfs-static-linux_amd64.tar.gz`.

**Comment by rominf** [comment]
I can explain it here; it's not a big secret :-)

I talk with computational linguists occasionally, and they have an issue: often, they have a university machine they can use as they want, but without root access. However, sometimes they need the latest Python version, PostgreSQL, or something else. They need to do some bureaucratic stuff and wait until the system administrator installs what they need. I want to save scientists time and allow them to install what they want.

I found two (technical) solutions to this issue: https://github.com/fsquillace/junest and https://github.com/nix-community/nix-user-chroot. However, I didn't like any of them fully, so I've decided to make my own solution similar to Nix User Chroot, but based on Guix and user namespaces (for root substitution).

The problem is that Guix (contrary to Nix) uses some paths that overlap host filesystem paths that are not writable by normal users, such as: `/gnu`, `/var/guix`, and `/etc/guix`. To solve this problem, I've started to search for a user union filesystem to "merge" the host filesystem with Guix distribution, and I found your project.

I'm writing my project in Nim, and I thought it would be easier to call the `mergerfs` binary. My project's code is not open yet, because I didn't finish it yet, but I'm planning to open it as soon as possible.

Feel free to contact me privately if you want (my contact info is on a website written in GitHub profile).

**Comment by trapexit** [comment]
Maybe I'm missing something but mergerfs doesn't make read-only files/mounts writable.

**Comment by rominf** [comment]
It shouldn't, as long it's possible to choose where to write (and, as I understand, it's possible), it's fine.

Let's take `/etc/guix` for example. The user has a writable dir `~/guix/root/etc` where Guix stores its config files. We need to "merge" hosts `/etc` with `~/guix/root/etc` so that (for example) programs could read `/etc/resolv.conf`, and `guix` could write to `/etc/guix/acl`. I think it's safe to have all writes go to `~/guix/root/etc`.

**Comment by trapexit** [comment]
Are you trying to write to the relative path they share or the files? The former will work. The latter will not.

**Comment by rominf** [comment]
I think only the former.

**Comment by trapexit** [comment]
Have you considered using proper overlaying union filesystems? overlayfs, unionfs, fuse-overlayfs? It would resolve any concern of the writing to read-only files.

Regardless, I'll take a look at the static build later today.

**Comment by trapexit** [comment]
Yeah. I found the issue. My makefile is rebuilding the binary when trying to install which doesn't include the static flags. I'll fix it and reupload the packages.

**Comment by trapexit** [comment]
OK. static targz files are now actually static builds.

**Comment by rominf** [comment]
> Have you considered using proper overlaying union filesystems? overlayfs, unionfs, fuse-overlayfs?

I've considered different union filesystems, but some of them cannot be used by normal (non-root) users, and overlayfs and fuse-overlayfs do not support online file changes to the underlying filesystem, which is a must for me. It looks to me that mergerfs is the best match for my purposes.

**Comment by trapexit** [comment]
What do you mean by "online file changes to the underlying filesystem"?

**Comment by rominf** [comment]
> Offline changes, when the overlay is not mounted, are allowed to either
the upper or the lower trees.

> Changes to the underlying filesystems while part of a mounted overlay
filesystem are not allowed.  If the underlying filesystem is changed,
the behavior of the overlay is undefined, though it will not result in
a crash or deadlock.


https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt

> As the native overlay, you should not modify the underlying directories as the result is undefined.

https://github.com/containers/fuse-overlayfs/issues/190

**Comment by rominf** [comment]
BTW, looks like static binaries work! Thank you very much!

PS: I tested it on Fedora 33 x86_64.

**Comment by trapexit** [comment]
I guess I wasn't clear. I mean to ask *why* you want that. Ultimately similar is true with mergerfs. It is undefined behavior. If you use any caching you can have problems and I can't tell you how.

**Comment by rominf** [comment]
:-( But thanks for the information!

Explanation:
I mount `/etc` from the host (RO) and `~/guix/root/etc` (RW) to /tmp/guix-root/etc, then I do `chroot /tmp/guix-root`. I want, for example, changes to `/etc/resolv.conf` (which were made by some network manager services on the host) to propagate to the user container.

OK, looks like I'll create `/tmp/guix-root/etc`, and `--rbind` mount all `/etc` content there and just assume, that there will be no changes like creation/deletion of top-level files/directories in `/etc`... I think it should be possible to `--rbind` mount top-level `/etc` files/directories on changes using `inotify`, but it sounds even more horrible...

**Comment by trapexit** [comment]
I am confused. If you use a COW overlay filesystem then the whole point is that you can write to the RW path and the underlying isn't touched. What you are suggesting is writing to /etc which shouldn't be possible.

**Comment by trapexit** [comment]
If you want to write to the chrooted /etc/resolve.conf and that file comes *from* non-chrooted /etc you will *not* be able to write to it. That is not how mergerfs works.

**Comment by rominf** [comment]
I don't want to write to chrooted `/etc/resolve.conf`; I want to read it and always get the actual content: chrooted `/etc/resolve.conf` should always be the same as non-chrooted `/etc/resolv.conf` which can be replaced any moment by some network manager service on the host. Is the change to non-chrooted `/etc/resolv.conf` on the host possible? Yes! Do we want undefined behavior? No.

So, if we rbind mount all the files to `/tmp/guix-root/etc/`, we will get chrooted `/etc/resolv.conf` updates. Am I right?

The problem with this rbind mount solution is that we will not see created top-level files/directories. For example, if we installed Apache after creating the Guix user chroot container, we won't see `/etc/apache` in chroot because it wasn't rbind mounted, as this dir was not present at the moment of chroot creation.

PS: Sorry, if my messages are unclear, English is not my native language, but I try my best :-)

**Comment by trapexit** [comment]
If it is read only then there is likely isn't a problem. Especially if you disable page caching. The same is generally true with overlayfs or fuse overlayfs. The reason they say it is undefined is because they aren't trying to manage that situation but if you're only reading something and disable page caching then what the actual risk is changes.

**Comment by trapexit** [comment]
There are risks of such a setup still. For instance the changing of a file out of band can result in a new inode which some software is sensitive to. But the main culprit for that is NFS.

**Comment by rominf** [comment]
Well:
1. OverlayFS does not with user namespaces :-(
2. I can mount fuse-overlayfs, but when I change the lowerdir, changes are not reflected, even though I used `direct_io`.
3. mergerfs works as expected! :tada:

I'll investigate (3) further.

**Comment by trapexit** [comment]
OK. If you end up with any other issues or questions feel free to reach out.
