### ISSUE TITLE
[Documentation] cyclic reference in definition of eppfrd and pfrd policies

### ISSUE THREAD

**Issue by topin89** [trapexit/mergerfs#875]
A minor documentation issue, eppfrd defined as "like pfrd", and vise versa.

Policy | Description
-- | --
eppfrd (existing path, percentage free random distribution) | Like pfrd but limited to existing paths.
pfrd (percentage free random distribution) | Search: Same as eppfrd. Action: Same as eppfrd. Create: Chooses a branch at random with the likelihood of selection based on a branch's available space relative to the total.

**Comment by trapexit** [comment]
It's not really cyclical. Each policy is really 3. Depending on the usage. search, action, or create. The create is the truly relevant definition. I had specific definitions prior and people complained it was too much to read so I made them relative.

If I revert it it'd be:

* pfrd (search): Chooses a branch with existing relative path at random with the likelihood of selection based on a branch's available space relative to the total.
* pfrd (action): Chooses a branch with existing relative path at random with the likelihood of selection based on a branch's available space relative to the total.
* pfrd (create): Chooses a branch at random with the likelihood of selection based on a branch's available space relative to the total.

* eppfrd (search): Chooses a branch with existing relative path at random with the likelihood of selection based on a branch's available space relative to the total.
* eppfrd (action): Chooses a branch with existing relative path at random with the likelihood of selection based on a branch's available space relative to the total.
* eppfrd (create): Chooses a branch with existing relative path at random with the likelihood of selection based on a branch's available space relative to the total.
