### ISSUE TITLE
rewind of opendir() results in double filesystem entries

### ISSUE THREAD

**Issue by slashbeast** [trapexit/mergerfs#877]
**Describe the bug**
New version of midnight commander started to show double entries when browsing mergerfs mountpoints, thanks to @trofi investigation turns out that once rewind happen on opendir(), mergerfs will start returning double entries.

**To Reproduce**
Mount mergerfs with some files and/or directories under 'baz' and run
```
#include <sys/types.h>
#include <dirent.h>
#include <stdio.h>

int main()
{
    DIR * d;
    struct dirent * e;

    printf("first read:\n");
    d = opendir("baz");
    while (e = readdir(d)) { printf("e: %s\n", e->d_name); }

    printf("second read:\n");
    rewinddir(d);
    while (e = readdir(d)) { printf("e: %s\n", e->d_name); }

    closedir(d);
}
```
**Current behavior**
```
first read:
e: .
e: ..
e: aaa
second read:
e: .
e: ..
e: aaa
e: .
e: ..
e: aaa
```

**Expected behavior**
```
first read:
e: .
e: ..
e: aaa
second read:
e: .
e: ..
e: aaa
```
**System information:**
 - OS, kernel version: 5.10.14
 - mergerfs version: mergerfs version: 2.32.2
 - mergerfs settings
 ```
mergerfs $(pwd)/foo:$(pwd)/bar baz
```
Originally reported, with some more context from @trofi under https://bugs.gentoo.org/769356

**Comment by trapexit** [comment]
I'll take a look. Thanks.

**Comment by trapexit** [comment]
#878 addresses it. I clearly had noticed it at some point given I created an API to manage the situation but seems I forgot to use it. I'll release 2.32.3 with this patch ASAP.

**Comment by slashbeast** [comment]
Thanks, once released I will test it and report back, then push it back to Gentoo.

**Comment by slashbeast** [comment]
Everything is all right now, thanks for taking care of this bug so fast!

**Comment by trapexit** [comment]
No problem. Thankfully it was a 1 liner :)
