### ISSUE TITLE
Include a note in the doc for radarr and sonarr - similar to Plex

### ISSUE THREAD

**Issue by alaaalii** [trapexit/mergerfs#887]
**Is your feature request related to a problem? Please describe.**
No. It's just a doc update.

**Describe the solution you'd like**
Add something in the README.md under "KNOWN ISSUES / BUGS" for Radarr and Sonarr because they also use sqlite, similar to Plex. Maybe just expand the "Plex doesn't work with mergerfs" section for Radarr and Sonarr too.

Typically, "end-users" don't really know the technology these applications use, that's why I think it would be nice to actually name Radarr and Sonarr somewhere in the doc rather than rely on the user to know that they use sqlite.

Just for documentation purposes, the error from Radarr at container startup is this:

```
[Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 

[Fatal] ConsoleApp: EPIC FAIL! 

[v3.0.2.4552] NzbDrone.Core.Datastore.CorruptDatabaseException: Radarr failed to start: Database file: code = IoErr (10), message = System.Data.SQLite.SQLiteException (0x800007FF): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
```

It's fixed by using `cache.files=partial` in the mergerfs options, same as Plex.

**Comment by trapexit** [comment]
#1131
