### ISSUE TITLE
Objections against merging BTRFS subvolumes on the same disk?

### ISSUE THREAD

**Issue by zilexa** [trapexit/mergerfs#892]
Currently, I backup my Mergerfs pool via `nocache rsync`, copying the root pool folder to a disk outside the pool. Then I snapshot that folder on that disk. This way, I have a timelined backup.
But this is quite intensive, with rsync. 
BTRFS has send/receive options that are efficient and don't wear the disks that much. The disks in the MergerFS pool each have a single subvol containing the data (those subvols, instead of the disk mount root, are mounted via MergerFS).

I am considering the following alternative: 
Simply use BTRFS send/receive to send a read-only snapshot of each disks subvolume to the backup disk outside the pool. 
I can use the incremental send option for each disk individually.

As a result, I will have subvols for each disk on the backup disk. 
This is not practical: If I need to recover a folder or file, I would have to search through each of the subvols.

Would there be any objections to use MergerFS to create a pool of the backup-subvolumes on the backup disk? Basically, I would mount a bunch of folders on the same disk, that are actually subvolumes. And each subvolume can contain lots of snapshots.

**Comment by trapexit** [comment]
I'm not really sure what you're asking. What are your concerns? mergerfs is just a userspace app like any other from the perspective of the underlying filesystem. I don't see how there would be any issues with readonly snapshots.

**Comment by zilexa** [comment]
I never considered MergerFS to merge folders on the same disk. Just wondering if that would go well. I will give it a go. Thanks for the quick response!

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#branches

> It does not matter if the paths are on the same or different drives nor does it matter the filesystem (within reason). Used and available space will not be duplicated for paths on the same device and any features which aren't supported by the underlying filesystem (such as file attributes or extended attributes) will return the appropriate errors.
