### ISSUE TITLE
Docker Container unable to create files and directories on mergerfs storage

### ISSUE THREAD

**Issue by joshiamey** [trapexit/mergerfs#894]
**Describe the bug**
Mergerfs version: 2.32.4

We have 2 content drives which we combine to create 2 TB storage  (1TB each drive),  on this device the content drives were originally combined using unionfs application, but we ran into an issue where if we have content larger than 1TB to store , it fails to balance and use the drive with free space.

hence I decided to move to mergerfs , this is the options we use 

 mergerfs -o use_ino,nonempty,allow_other,cache.files=off,dropcacheonclose=true,category.create=mfs

We combine these partitions using root user.

Now these directories already have folder present and on these folders the permissions are as below 
drwxr-x---  3 root root 4096 Feb  4 19:02 assets
drwxrwx--- 18 root root 4096 Feb 24 15:31 data
drwxrwx--- 13 root root 4096 Feb  4 19:02 log

Now in data folder we have files mapped to docker container rabbitmq , and rabbitmq on start creates some files in /var/lib which is mapped to this data folder, but it gets the error.

mkdir: can't create directory '/var/lib/rabbitmq/mnesia': No such file or directory
Failed to create directory: /var/lib/rabbitmq/mnesia

both docker daemon and mergerfs are started via root user.

Now when i change the permissions on the data folder to 755 before combining them using mergerfs , rabbitmq starts fine and is able to create those files.

 I don't understand why i would have to change any permissions on these individual folder before combining them as docker is run as root hence the container should be able to create any files that are required. The individual drives before combining are also mounted as RW partitions

Am I missing some option in mergrfs such that data folder permissions change to allow root user to access data folder ?

**System information:**

 - Linux msu 4.14.184 #3 SMP Wed Feb 24 20:53:14 UTC 2021 x86_64 GNU/Linux
 - mergerfs version:2.32.4
 - mergerfs settings: use_ino,nonempty,allow_other,cache.files=off,dropcacheonclose=true,category.create=mfs
 - List of drives, filesystems, & sizes:
   - `df -h`
   - `lsblk`
   - 
NAME           MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda              8:0    0 953.9G  0 disk
sda1           8:1    0     4G  0 part  /system
sda2           8:2    0 949.9G  0 part  /mnt/content_1
sdb              8:16   0 953.9G  0 disk
sdb1           8:17   0 953.9G  0 part  /mnt/content_2

 - strace of mergerfs while app tried to do it's thing:
   - `strace -fvTtt -s 256 -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

[pid 25677] 02:37:44.859456 <... read resumed>"8\0\0\0\3\0\0\0\342D\0\0\0\0\0\0\26\0\0\0\0\0\0\0d\0\0\0e\0\0\0\341#\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 1052672) = 56 <0.010230>
[pid 25677] 02:37:44.859613 lstat("/mnt/content_1/stage/log/rabbitmq", 0x7f2cfa86d1a8) = -1 EACCES (Permission denied) <0.000060>
[pid 25677] 02:37:44.859804 lstat("/mnt/content_2/stage/log/rabbitmq", 0x7f2cfa86d1a8) = -1 EACCES (Permission denied) <0.000053>
[pid 25677] 02:37:44.859948 writev(3, [{iov_base="\20\0\0\0\376\377\377\377\342D\0\0\0\0\0\0", iov_len=16}], 1) = 16 <0.000055>

**Additional context**

**Comment by trapexit** [comment]
You'll need to provide more information. What image? How is it run? Could you provide more than just the error from the strace? I need *everything* relevant.

**Comment by garrettdowd** [comment]
>
>
>both docker daemon and mergerfs are started via root user.

Permissions with docker bind mounts are always a headache. I am not an expert on permissions. especially when it comes to containers, _but you didn't mention which user (rabbitmq) is accessing the bind mounted files from_ **within** _the container._

Furthermore, it depends how the container users are mapped to the host users. Even the [Docker documentation says it can be difficult](https://docs.docker.com/engine/security/userns-remap/)
>
>
>This re-mapping is transparent to the container, but introduces some configuration complexity in situations where the container needs access to resources on the Docker host, such as bind mounts into areas of the filesystem that the system user cannot write to. From a security standpoint, it is best to avoid these situations.

In my experience, your issues probably stem from how the namespace is handled within the container and mapped to the host.

**Comment by joshiamey** [comment]
ok  thank you for you help and input, closing this issue , as updating the host folder permissions from 750 to 755 works for the rabbitmq container to operate successfully
