### ISSUE TITLE
Mounting a mergerfs filesystem on alpine linux

### ISSUE THREAD

**Issue by sprat** [trapexit/mergerfs#895]
I am trying to use the statically-linked binary on a fresh install of Alpine Linux 3.13, and mount a "mergerfs" filesystem via `/etc/fstab`, but I cannot get it to work.

I am starting from this:
```
$ ls -la /mnt/
total 20
drwxr-xr-x    5 root     root          4096 Mar 31 20:10 .
drwxr-xr-x   21 root     root          4096 Mar 23 09:07 ..
drwxrwxrwx    2 root     root          4096 Mar 31 20:56 data1
drwxrwxrwx    2 root     root          4096 Mar 31 20:56 data2
drwxrwxrwx    2 root     root          4096 Mar 31 20:10 storage
```

Here is what I have done:
1. I enabled the `fuse` kernel module via `modprobe` and added it in `/etc/modules`.
2. I installed the `fuse3` package (fuse3-3.10.2-r0) or the `fuse` package (fuse-2.9.9-r1) in another try
3. I have successfully mounted the filesystem with the mergerfs binary: `sudo mergerfs /mnt/data\* /mnt/storage -o allow_other,use_ino`
4. I can list `/mnt/storage`, everything seems ok
5. I looked into `/etc/mtab` and found this: `1:2 /mnt/storage fuse.mergerfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0`
6. I unmounted `/mnt/storage` and added this line into `/etc/fstab`: `/mnt/data* /mnt/storage fuse.mergerfs allow_other,use_ino 0 0`. When I try to `sudo mount /mnt/storage`: `mount: mounting /mnt/data* on /mnt/storage failed: Invalid argument`
7. Another try with the "old" syntax: `mergerfs#/mnt/data* /mnt/storage fuse allow_other,use_ino 0 0`. Now it mounts properly, but when I list `/mnt` or `/mnt/storage`, I get a `ls: /mnt/storage: Permission denied`.

My questions:
- how to debug the problem in step 6? it seems the fuse packages versions are quite up-to-date but the new syntax does not seem to be supported!?
- what am I missing in step 7?
- is there another way to mount the filesystem at boot than `/etc/fstab`?

**Comment by sprat** [comment]
Any ideas?

**Comment by trapexit** [comment]
The mount command used by alpine doesn't do the right thing when using "fuse.mergerfs". Nothing I can do about that. An strace can show you what it's doing, or not doing.

As for "mergerfs#"... it works for me in a container. Are you positive about the entitlements?

**Comment by trapexit** [comment]
>is there another way to mount the filesystem at boot than /etc/fstab?

Use whatever the OS uses for startup scripts. I'm not familiar with Alpine but most systems now use systemd. It might just use some form of sysv.

**Comment by sprat** [comment]
> As for "mergerfs#"... it works for me in a container. Are you positive about the entitlements?

Did you mount the /dev/fuse device from the host into the container? I can make it work in a container, but I mounted the /dev/fuse device from the host, and I am using the root user in the container.

I tried again in my alpine VM: I have a "Permission denied" when listing the /mnt and /mnt/storage directory as a non-root user, but not when using the root user. But I don't understand why since all the directories have rwx permissions for everyone. Maybe I miss a mount option?

**Comment by trapexit** [comment]
>Did you mount the /dev/fuse device from the host into the container?

Yes. That's the only way it can work. 

What exactly does it say the perms are? You must run mergerfs as root, not use uid,gid flags, and use allow_other. That's it.

**Comment by sprat** [comment]
Here is my current session:
```
alpine313:~$ id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant)
alpine313:~$ ls -la /mnt/
total 20
drwxrwxrwx    5 root     root          4096 Apr  8 17:24 .
drwxr-xr-x   21 root     root          4096 Mar 23 09:07 ..
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data1
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data2
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 storage
alpine313:~$ cat /etc/fstab 
UUID=8c3031de-4058-4823-8fda-854f22db39a5	/	ext4	rw,relatime 0 1
UUID=8435aaed-fd4e-4d08-99fb-98f68c4110d6	/boot	ext4	rw,relatime 0 2
/dev/cdrom	/media/cdrom	iso9660	noauto,ro 0 0
/dev/usbdisk	/media/usb	vfat	noauto	0 0
mergerfs#/mnt/data1:/mnt/data2 /mnt/storage fuse allow_other 0 0
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
#VAGRANT-END
alpine313:~$ sudo mount /mnt/storage
alpine313:~$ sudo ls -la /mnt/
total 20
drwxrwxrwx    5 root     root          4096 Apr  8 17:24 .
drwxr-xr-x   21 root     root          4096 Mar 23 09:07 ..
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data1
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data2
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 storage
alpine313:~$ ls -la /mnt/
ls: /mnt/storage: Permission denied
total 16
drwxrwxrwx    5 root     root          4096 Apr  8 17:24 .
drwxr-xr-x   21 root     root          4096 Mar 23 09:07 ..
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data1
drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data2
```

**Comment by sprat** [comment]
Here is a strace log, but I don't know how to interpret it:
```
alpine313:~$ strace ls -la /mnt/
execve("/bin/ls", ["ls", "-la", "/mnt/"], 0x7ffe4ad27040 /* 19 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7fb2d430bb48) = 0
set_tid_address(0x7fb2d430bf90)         = 2467
brk(NULL)                               = 0x55c63ae06000
brk(0x55c63ae08000)                     = 0x55c63ae08000
mmap(0x55c63ae06000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x55c63ae06000
mprotect(0x7fb2d4308000, 4096, PROT_READ) = 0
mprotect(0x55c63ab21000, 16384, PROT_READ) = 0
getuid()                                = 1000
getgid()                                = 1000
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[], NULL, 8) = 0
setgid(1000)                            = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[], NULL, 8) = 0
setuid(1000)                            = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TIOCGWINSZ, {ws_row=52, ws_col=207, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=52, ws_col=207, ws_xpixel=0, ws_ypixel=0}) = 0
lstat("/mnt/", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
open("/mnt/", O_RDONLY|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb2d4273000
getdents64(3, 0x7fb2d4273038 /* 5 entries */, 2048) = 144
lstat("/mnt/.", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
lstat("/mnt/..", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/mnt/data2", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
lstat("/mnt/storage", 0x7ffce95e7da0)   = -1 EACCES (Permission denied)
write(2, "ls: /mnt/storage: Permission den"..., 36ls: /mnt/storage: Permission denied
) = 36
lstat("/mnt/data1", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
getdents64(3, 0x7fb2d4273038 /* 0 entries */, 2048) = 0
close(3)                                = 0
munmap(0x7fb2d4273000, 8192)            = 0
ioctl(1, TIOCGWINSZ, {ws_row=52, ws_col=207, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="total 16", iov_len=8}, {iov_base="\n", iov_len=1}], 2total 16
) = 9
open("/etc/group", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb2d4274000
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
read(3, "root:x:0:root\nbin:x:1:root,bin,d"..., 1024) = 717
lseek(3, -703, SEEK_CUR)                = 14
close(3)                                = 0
munmap(0x7fb2d4274000, 4096)            = 0
open("/etc/passwd", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb2d4274000
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
read(3, "root:x:0:0:root:/root:/bin/bash\n"..., 1024) = 1024
lseek(3, -992, SEEK_CUR)                = 32
close(3)                                = 0
munmap(0x7fb2d4274000, 4096)            = 0
open("/etc/localtime", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=114, ...}) = 0
mmap(NULL, 114, PROT_READ, MAP_SHARED, 3, 0) = 0x7fb2d4274000
close(3)                                = 0
writev(1, [{iov_base="drwxrwxrwx    5 root     root   "..., iov_len=68}, {iov_base="\n", iov_len=1}], 2drwxrwxrwx    5 root     root          4096 Apr  8 17:24 .
) = 69
writev(1, [{iov_base="drwxr-xr-x   21 root     root   "..., iov_len=69}, {iov_base="\n", iov_len=1}], 2drwxr-xr-x   21 root     root          4096 Mar 23 09:07 ..
) = 70
writev(1, [{iov_base="drwxrwxrwx    2 root     root   "..., iov_len=72}, {iov_base="\n", iov_len=1}], 2drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data1
) = 73
writev(1, [{iov_base="drwxrwxrwx    2 root     root   "..., iov_len=72}, {iov_base="\n", iov_len=1}], 2drwxrwxrwx    2 root     root          4096 Apr  8 17:24 data2
) = 73
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by trapexit** [comment]
Works absolutely fine for me.

1. Downloaded alpine VM iso
2. setup-alpine
3. apk add fuse
4. modprobe fuse
4. mkdir /tmp/test
4. fstab line: mergerfs#/var:/root /tmp/test fuse allow_other,use_ino 0 0
5. mount /tmp/test
6. ls -lh /tmp/test works fine and shows /var and /root content

**Comment by sprat** [comment]
As I said, it's ok with the root user. It only fail with a non-root user. I should probably miss a mount option, or maybe allow_user option does not work on alpine.

**Comment by sprat** [comment]
If I run the mergerfs command directly, no permissions problems either

**Comment by trapexit** [comment]
Yeah. Looks like something weird with busybox mount. It doesn't appear to pass in options the way it is setup in fstab but that is a typical setup.

**Comment by trapexit** [comment]
https://wiki.alpinelinux.org/wiki/Alpine_Linux_Init_System

I don't know what's up with busyboxy mount command but it doesn't pass arguments at all so it just uses defaults.

If you copy or link mergerfs binary to "/sbin/mount.mergerfs" and then use the fstype "mergerfs" then it should work from fstab.

I'll look at adding mount.mergerfs to future release to help work around dumb stuff like this.

**Comment by sprat** [comment]
The /sbin/mount.mergerfs symlink trick works perfectly, will use that. Thanks for the help troubleshooting the problem!
