### ISSUE TITLE
Is noforget option necessary to eliminate NFS "stale file handle" error?

### ISSUE THREAD

**Issue by edo1** [trapexit/mergerfs#899]
With `use_ino,inodecalc=path-hash` mount options inode numbers should be persistent.
Does `noforget` change anything in this case (except memory consumption)?

BTW, the effect of this mount option is not described on the man page.

**Comment by trapexit** [comment]
Yes, that's why it's included in the docs. Presenting fixed inodes is separate from the internal representation. NFS can ask for nodes the kernel otherwise told the server it was OK to forget. The option is from libfuse and unnecessary except for NFS / network filesystems. I can add details but it shouldn't be used otherwise and will be removed in the future in favor of something more explicit.

**Comment by trapexit** [comment]
I can add something. The details can be found in the mount.fuse man page: https://www.man7.org/linux/man-pages/man8/fuse.8.html

  noforget
  Normally, libfuse assigns inodes to paths only for as long
  as the kernel is aware of them. With this option inodes
         are instead assigned for at least T seconds (or, in the
         case of noforget, the life-time of the filesystem). This
         will require more memory, but may be necessary when using
         applications that make use of inode numbers.

**Comment by edo1** [comment]
Ok, it will keep the inode numbers in memory forever. Why does it matter if predictable inode numbers are used? The next time the same inode number will be generated.

**Comment by trapexit** [comment]
I'm not sure exactly what you're asking but I think you're conflating two different "inodes". 

There is a difference between what is presented to the user which is what the inodecalc manages and the *internal* node values used between the fuse server and the kernel. "noforgot" manages the latter. Not the former. The kernel typically tells the server to forget nodes after the kernel no longer references it. noforget and remember cause the server to keep references to those around longer than normal *just in case* they are requested again by something like NFS which held on to them while the kernel didn't know.

**Comment by libook** [comment]
Is there any option which incompatible with these 3 options?

I use this configuration:
`defaults,allow_other,cache.files=partial,dropcacheonclose=true,use_ino,nfsopenhack=all`
It seems working well. But few hours later, there would be randomly "stale file handle" error.

I tried to add `inodecalc=path-hash,noforget` options. It broken git with "stale file handle" error.

So I thought if there is something wrong in my configuration.

I use this configuration for the NFS client:
`my_nas_domain:/main /mnt/nas nfs4 defaults,user,exec,nofail,hard,lookupcache=positive,cto,_netdev 0 2`

**Comment by trapexit** [comment]
No, if something was knowingly incompatible the docs would say so.

Are you changing things out of band? Have you tried disabling all caching? What do you mean it "broken git"? I need to know *precisely* what you are doing and what happens.
