### ISSUE TITLE
Building on 32-bit yields duplicate case errors in ioctl.cpp

### ISSUE THREAD

**Issue by meersjo** [trapexit/mergerfs#90]
Not particularly familiar with C++, but I would guess that on a 32-bit platform (Mint 17 here), the FS_IOC_* and FS_IOC32_* constant sets are both defined and identical? Removing the -32 variants from the file allows the build to proceed.

Any chance of a launchpad PPA for this? I believe it's a highly useful thing you are making; shame I only found out about it when I had a look at the mhddfs repo to figure out a problem I'd been having with that :-) This is what should be included in distros, not mhddfs. Thank you for providing it!

**Comment by trapexit** [comment]
Thanks for putting it in the tracker. I'll create a 32bit VM and attempt to fix it. 

As for getting into distro repos.... I've been meaning to look into that. I'll try to make some time to see how to go about that. In the least once I get the 32bit build fixed I can include debs in my releases on github.

**Comment by meersjo** [comment]
Apart from that bit, I can report that it runs perfectly fine on my 32-bit host. Feels a lot faster than my previous setup, too. Thank you for publishing this :-)
