### ISSUE TITLE
Permission Denied on mounted pool drive

### ISSUE THREAD

**Issue by Viking8** [trapexit/mergerfs#906]
First I'd like to thank you for such a fantastic program!

Note: I am using a fresh install of Ubuntu 20.04.2 Desktop.
Linux ubuntuFocal 5.8.0-53-generic

- Output from mergerfs -v.... (installed from ubuntu repo)
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29

- /etc/fstab additions....
/dev/disk/by-id/ata-ST1000DM003-1ER162_Z4Y2XSSH-part1  /mnt/temp  btrfs  defaults  0 0
/dev/disk/by-id/ata-ST2000DL003-9VT166_6YD138Z1-part1  /mnt/disk1    btrfs  defaults  0 0
/dev/disk/by-id/ata-ST2000DM001-1CH164_Z1E3Y2WX-part1  /mnt/disk2    btrfs  defaults  0 0
/dev/disk/by-id/ata-ST3000DM001-1CH166_W1F2A9JM-part1  /mnt/disk3    btrfs  defaults  0 0

/mnt/disk* /mnt/diskpool fuse.mergerfs  direct_io,defaults,use_ino,moveonenospc=true,fsname=mergerfs  0 0

- btrfs-progs is installed

- When mounting using sudo mount -a, the individual disks mount properly. df -h shows those drives mounted to the correct /mnt/disk locations, but doesn't show the mergerfs entry and the diskpool folder is inaccessable. 

I receive....
bash: cd: /mnt/diskpool: Permission denied

- Output of df -h....
Filesystem            Size      Used   Avail    Use%   Mounted on
udev                     7.8G        0       7.8G      0%        /dev
tmpfs                    1.6G     1.8M    1.6G      1%        /run
/dev/sda2             228G      60G   157G     28%      /
tmpfs                    7.9G        0       7.9G       0%       /dev/shm
tmpfs                    5.0M     4.0K     5.0M      1%       /run/lock
tmpfs                    7.9G        0       7.9G      0%        /sys/fs/cgroup
/dev/loop0            56M      56M        0     100%        /snap/core18/1988
/dev/loop1            56M      56M        0     100%        /snap/core18/2066
/dev/loop3            219M    219M      0     100%        /snap/gnome-3-34-1804/66
/dev/loop2            65M      65M        0      100%       /snap/gtk-common-themes/1514
/dev/loop4            52M      52M        0      100%       /snap/snap-store/518
/dev/loop6            66M      66M        0      100%       /snap/gtk-common-themes/1515
/dev/loop7            33M      33M        0       100%      /snap/snapd/11841
/dev/loop5            32M      32M        0        100%     /snap/snapd/11036
/dev/sda1             511M    7.9M     504M       2%     /boot/efi
/dev/sdd1             1.9T      3.8M     1.9T         1%     /mnt/disk1
/dev/sdc1             1.9T      3.8M     1.9T          1%    /mnt/disk2
/dev/sde1             932G    3.8M     930G         1%    /mnt/temp
/dev/sdb1             2.8T      3.8M      2.8T          1%   /mnt/disk3
tmpfs                    1.6G       32K      1.6G         1%   /run/user/1000

- When I go to the folder in the files program, it tells me the same thing. No permissions. I right clicked on what used to be a folder icon (it changed to an icon with a bunch of 1's and 0's after being mounted) and chose properties. Under permissions, it says that they can't be determined. If I unmount the diskpool folder, it returns to normal and can be accessed normally. Your assistance is greatly appreciated

Thanks,

Clayton

**Comment by trapexit** [comment]
1) Please use up to date versions. 2.28.1 came out some time ago and a lot has changed.
2) /mnt/disk* /mnt/diskpool fuse.mergerfs direct_io,defaults,use_ino,moveonenospc=true,fsname=mergerfs 0 0

You don't have "allow_other" and you've run it as root and yet accessing it as non-root.

https://github.com/trapexit/mergerfs#basic-setup

**Comment by Viking8** [comment]
Thx for the response. I uninstalled the repo version and used the instructions you listed. It's now version 2.32.3-26.
I added allow_other to the fstab, but doing mount /mnt/whatever always gets me a message stating that mounting operations are permitted for root only. when I use mount -a Ubuntu tells me only root can use the --all option. Any way around that?
Interesting thing is, I had this working on a different PC with Ubuntu Mate installed, but it's woefully underpowered, so I moved everything to a better computer. I suppose I should have stuck with mate instead of the regular ubuntu desktop.

**Comment by trapexit** [comment]
I don't understand. Yes, you have to be root to use "mount -a". What's the problem? 

Why did you install a non-release? You are using Ubuntu. Just download a package for the relevant version from the release page: https://github.com/trapexit/mergerfs/releases

**Comment by Viking8** [comment]
I guess I thought that doing it the way I did would give me the latest. I will go to releases and choose the latest one from there.
You had said that I ran it as root, but accessing it as non root. what am I running as root? mergerfs? I'm sorry for the confusion. I'm sure you get tired of questions that are simple. I'm not as proficient in the command line, but I'm getting there. Please bare with me.

**Comment by trapexit** [comment]
As the [docs ](https://github.com/trapexit/mergerfs#build--update) say:

> NOTE: Prebuilt packages can be found at and recommended for most users: https://github.com/trapexit/mergerfs/releases 
> NOTE: Only tagged releases are supported. master and other branches should be considered works in progress.

You must run mergerfs as [root](https://github.com/trapexit/mergerfs#tips--notes) and as mentioned by mount to use "-a" you must also be root. You don't mount things as yourself to access them. Generally speaking only root has permissions to mount things. Yes, FUSE filesystems can be run by a random user but mergerfs requires being run as root unless you really know what you're doing.

**Comment by Viking8** [comment]
Thank you. I should have read things over a few more times before asking for help. I do appreciate you being patient with me though. Take care.

**Comment by Viking8** [comment]
Trap, I still need help. I read and read and read some more, but I am missing something and I just can't figure out what it is.

What I've done:
I login as clayton. I update and upgrade the OS install. I go to your github and grab the latest release and install it. 

I go into /mnt and.... 
sudo mkdir temp 
sudo mkdir diskpool
sudo mkdir disk{1,2,3} 

Then I go into fstab and enter the info below and save it.

/dev/disk/by-id/ata-ST1000DM003-1ER162_Z4Y2XSSH-part1     /mnt/temp  btrfs  defaults  0  0
/dev/disk/by-id/ata-ST2000DL003-9VT166_6YD138Z1-part1      /mnt/disk1  btrfs  defaults  0  0
/dev/disk/by-id/ata-ST2000DM001-1CH164_Z1E3Y2WX-part1   /mnt/disk2  btrfs  defaults  0  0
/dev/disk/by-id/ata-ST3000DM001-1CH166_W1F2A9JM-part1  /mnt/disk3  btrfs  defaults  0  0

/mnt/disk*   /mnt/diskpool   fuse.mergerfs   direct_io,defaults,allow_other,use_ino,moveonenospc=true,fsname=mergerfs   0   0

Then I,
sudo mount -a
df -h

But, the pool isn't setup. When I go into the mnt folder, all entries have disappeared and the file manager freezes. When I go into /mnt in the terminal and try to do any command, it freezes that terminal window until I force quit it or reboot.

Above you said I've run it as root and yet accessing it as non-root. I only have one user to access it from, so I'm not sure how else to access it. 

Thanks again for all your help.

**Comment by trapexit** [comment]
Please use the example in the docs if you're unsure. My docs should *always* take priority over some random online guide you've read. direct_io is a deprecated option and defaults has no meaning.

Don't use mount -a. Just mount the path in question.

```
sudo mount /mnt/diskpool
```

You can run mergerfs directly by just doing

```
sudo mergerfs -o allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.create=mfs '/mnt/disk1:/mnt/disk2:/mnt/disk3' /mnt/diskpool
```

The reason you have it lock up is because you created a loop by using globbing carelessly. You include /mnt/diskpool in the pool. 'diskpool' matches 'disk*'.

**Comment by Viking8** [comment]
The globbing as you put it was the issue. I changed the pool directory to /mnt/drivepool and it works great now.
Thanks for the help!
