### ISSUE TITLE
hard_remove documentation?

### ISSUE THREAD

**Issue by joakimlemb** [trapexit/mergerfs#910]
Is there any documentation for the option "hard_remove" mentioned here: https://github.com/trapexit/mergerfs/issues/464 ?

It is not a option mentioned in https://github.com/trapexit/mergerfs/blob/master/README.md

**Comment by trapexit** [comment]
It's not mentioned because it's not an option anymore. The thing it did was work around something that no longer is an issue. Been that way for quite a long time.
