### ISSUE TITLE
Internal move from one branch to another branch deletes all moved directories

### ISSUE THREAD

**Issue by zehnerGIT** [trapexit/mergerfs#915]
**Describe the bug**

I use mergerfs only for a few weeks and have three disks mounted under /srv and merged in /srv/shares (fstab below). The nas and it's disks worked for years without problems. The disk under /srv/data6tb has only a few gb left, so I thought it's a good idea to install mergerfs and move a few directories to /srv/data4tb. Bad idea: all directories are lost after the move.

**To Reproduce**

mv /srv/data6tb/public/video/Serien/dir1 /srv/data4tb/public/video/Serien/
I've done this with 'mc' and 'F6 Move'. MidnightCommander shows even a progressbar and needs a few minutes to complete the move, but after moving no more 'dir1' in source or target.
(dir1 exists on data6tb and contains subfolders with a lot of data, but not on data4tb before the command)

**Expected behavior**

I've tried this before without problems, but only with a few small files. But now with almost 100GB, all my recordings are lost. No exception in syslog or similiar files, no warning message during the move. You should show at least a warning or ask before you delete all files if you don't support this scenario or ignore moves from one internal share to another internal share, all is better than the silent deletion of all files. 

**System information:**

 - OS, kernel version: `uname -a`
Linux nas 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - mergerfs version: `mergerfs -V`
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.9
using FUSE kernel interface version 7.29

 - mergerfs settings: `cat /etc/fstab`
/dev/disk/by-uuid/3e8aff37-1cb4-45f4-abac-0d11266d503d /srv/data6tb/ ext4 defaults 0 0
/dev/disk/by-uuid/da2e638a-9646-46f7-ad28-8f071f6db83e /srv/data12tb/ ext4 defaults 0 0
/dev/disk/by-uuid/c71b5e5b-7776-4c34-a74e-f0095d821e1d /srv/data4tb/ ext4 defaults 0 0

/srv/data*     /srv/shares     fuse.mergerfs defaults,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs 0 0

**Comment by trapexit** [comment]
I'm not understanding you. You say you moved files between filesystems.

>mv /srv/data6tb/public/video/Serien/dir1 /srv/data4tb/public/video/Serien/

That has nothing at all to do with mergerfs. It's literally impossible, if you did what you claim, for mergerfs to have had anything to do with the loss of your files. It doesn't even get any messages from the kernel to do anything unless you are interacting with within the mount point. Which in this case would be /srv/shares/.

Are you positive that's what you did? And you didn't move between the same directory but between mergerfs and an underlying branch?

**Comment by zehnerGIT** [comment]
Thats all I did (but with mc), no moving to the same directory, no moving from branch to pool. 
I moved "dir1" with subdirectories from a branch (/srv/data6tb) to another branch (/srv/data4tb) both branches are in the pool (/srv/shares) and both branches have the path "public/video/Serien/". All directories on both disks should have the right path, because the pool shows directories from both branches at the right place. The directory "dir1" exists before moving (I've done md5sum for all files right before moving, because I still evaluate if mergerfs is the right tool for me), but after moving all files are lost, neither "/srv/data6tb/public/video/Serien/dir1" nor /srv/data4tb/public/video/Serien/dir1" exists (ofc "/srv/shares/public/video/Serien/dir1" doesn't exist, too).
I've done this often before without mergerfs installed, the only difference today was mergerfs. A `find . -name '*dir1*'` no longer show the files, so they aren't moved to a wrong directory, they disappeared.

Is it possible, that the split second where the directory disappeared for the pool (moved from /srv/data6tb) and reappeared (moved to /srv/data4tb) are enough to delete the directory from the pool? With Midnight Commander and "Preserve attributes" it needs a few seconds after moving to reapply all rights, timestamps, ... As said before, the moving of smaller parts (< 1GB) worked without a problem, but this was my first move with a lot of data (> 100GB)

**Comment by trapexit** [comment]
Without knowing exactly what `mc` does I can't comment for sure but yes... in Linux / *nix a file can be deleted at any time. Even if open. Assuming permissions are correct and all that. So sure it's possible something unlinked the files just as you moved them but unless you've got some malicious software or doing something really odd it's not likely to have happened that way. And for sure mergerfs had nothing to do with it as you weren't using it and mergerfs has no interactions with the branches unless the OS is expressly asking it to do so.

You're using ext4. Assuming you've not continued to write to the drives the unlinking you could try to undelete the files. I believe there are a couple tools if you look up the topic on your favorite search engine.

**Comment by zehnerGIT** [comment]
Thanks for your replies. Now that I know, that moving btw. branches should work without issues, I will keep an eye on moving with mc and "Preserve attributes". At least my last move today with more than 100GB worked without issues.

I don't think the drive is dying, but everything is possible. It's only a few months old and still in "check-mode" for me. I check every file copied to the disk (> 2TB till today) by md5sum and until now, not one single bitflip, ... Even the lost files were OK a few minutes before I moved them and SMART tests log no errors, too. Next downtime I will check the filesystem, because even extundelete and debugfs with restore-all options can't find the files
