### ISSUE TITLE
mount bug with /Disk-* Solution in my report.

### ISSUE THREAD

**Issue by Proulx417** [trapexit/mergerfs#920]
Sorry for faults I speak french
**Describe the bug**
When you mount exemple
/mnt/disk-1:/mnt/disk-2:/mnt/disk-3 you can use /mnt/disk-*

I'v write in fstab 
/mnt/disk-* /mnt/disk-pool fuse.mergerfs category.create=mfs,nonempty,defaults,allow_other,minfreespace=1M,fsname=disk-pool 0 00

As you can see I know I make a mistake to add the mergefs mount directory but mergefs have make the system verry laggy. and in htop it goes in Uninterruptible Sleep (D) State

sudo fusermount -uz /mnt/disk-pool to force umount work but mergerfs rest in Uninterruptible Sleep (D) State. Reboot is necessary to clean process in D state.

Can you juste make mergerfs more smart (idiot proof) like a beginner like me? ^^ and ignore the mounting point when using * to prevent bigger problems for other people?

**Expected behavior**

Laggy system, unresponsible in shell and in ftps.

Uninterruptible Sleep (D) State when doing that mistake.

**System information:**
HP Proliant DL380p G8 
6 x 2TB SSD
6 x 8TB HDD

**Comment by trapexit** [comment]
Addressed by #1128. Will be in next release.
