### ISSUE TITLE
Getting "fuse: copy from pipe: Bad file descriptor" when enabling splice_move,splice_read,splice_write

### ISSUE THREAD

**Issue by no1knows** [trapexit/mergerfs#922]
**Describe the bug**

When enabling splice_move,splice_read,splice_write options, and then writing to the pool, mergerfs exits with "fuse: copy from pipe: Bad file descriptor".

**To Reproduce**
Running mergerfs version: 2.32.4
When I run from the following from the commandline (to debug): mergerfs -f -o use_ino,cache.files=off,dropcacheonclose=true,allow_other,category.create=mfs,nonempty,splice_move,splice_read,splice_write,minfreespace=50G,func.getattr=newest /mnt/disk1:/mnt/disk2:/mnt/disk3:/mnt/disk4:/mnt/disk5 /netstorage
The command works fine, until I then write to the pool, e.g. with the following:
tar --exclude-from=/root/backup-excludes.txt -vzcpf /netstorage/Backup-test.tar.gz /opt /etc /var /home /root

If I remove splice_move,splice_read,splice_write options, it works as inteded.

**Expected behavior**

mergerfs doesn't exit. The file is written to the pool.

**System information:**

 - OS, kernel version: Fedora 33, Linux 5.12.11-200.fc33.x86_64 #1 SMP Wed Jun 16 16:10:53 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - mergerfs version: mergerfs version: 2.32.4
 - mergerfs settings: use_ino,cache.files=off,dropcacheonclose=true,allow_other,category.create=mfs,nonempty,splice_move,splice_read,splice_write,minfreespace=50G,func.getattr=newest
 - List of drives, filesystems, & sizes:
/dev/sdf1                                                                 11T   11T   29G 100% /mnt/parity1
/dev/sde1                                                                 11T   11T  132G  99% /mnt/disk3
/dev/sdh1                                                                 11T   11T   29G 100% /mnt/parity2
/dev/sdi1                                                                 11T   11T  110G 100% /mnt/disk5
/dev/sdg1                                                                 11T   11T  107G 100% /mnt/disk1
/dev/sdd1                                                                 11T   11T   92G 100% /mnt/disk2
/dev/sdj1                                                                 11T   11T   94G 100% /mnt/disk4
mergerfs                                                                  55T   54T  533G 100% /netstorage

sdd       8:48   0  10.9T  0 disk
└─sdd1    8:49   0  10.9T  0 part  /mnt/disk2
sde       8:64   0  10.9T  0 disk
└─sde1    8:65   0  10.9T  0 part  /mnt/disk3
sdf       8:80   0  10.9T  0 disk
└─sdf1    8:81   0  10.9T  0 part  /mnt/parity1
sdg       8:96   0  10.9T  0 disk
└─sdg1    8:97   0  10.9T  0 part  /mnt/disk1
sdh       8:112  0  10.9T  0 disk
└─sdh1    8:113  0  10.9T  0 part  /mnt/parity2
sdi       8:128  0  10.9T  0 disk
└─sdi1    8:129  0  10.9T  0 part  /mnt/disk5
sdj       8:144  0  10.9T  0 disk
└─sdj1    8:145  0  10.9T  0 part  /mnt/disk4

 - strace of mergerfs while app tried to do it's thing:
   - `strace -fvTtt -s 256 -p <mergerfsPID> -o [mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/6682084/mergerfs.strace.txt)`

**Additional context**

I had originally enabled these to help with performance, but haven't tested in some time, so not sure if they're still useful/necessary. Is benchmarking the only way to work that out?

Appreciate the help, and am (otherwise) a huge fan of mergerfs :)

**Comment by trapexit** [comment]
Can you reproduce it with something simpler? Simply writing to a file or whatnot. The failure is odd. I've not been able to reproduce on my system. Will need to dig into the code to see where this could be happening.

`40408 11:07:00.843849 splice(6, NULL, 6, NULL, 40, 0) = -1 EBADF (Bad file descriptor) <0.000005>`

splice options *can* but don't always improve performance. In my experience splice_read does the most. All of that code needs to be reworked. It's pretty convoluted and difficult to maintain.

**Comment by no1knows** [comment]
Thanks! Seems to happen even with just splice_read enabled (I thought that might work fine since the writing seems to trigger the issue).

With all splices enabled...
If I do a cp:
# cp Backup-200621.tar.gz Backup-test.tar.gz
cp: overwrite 'Backup-test.tar.gz'? y
cp: error reading 'Backup-200621.tar.gz': Software caused connection abort
cp: failed to close 'Backup-test.tar.gz': Transport endpoint is not connected
cp: failed to close 'Backup-200621.tar.gz': Transport endpoint is not connected
With the attached strace. 
[mergerfs.strace-cp.txt](https://github.com/trapexit/mergerfs/files/6682557/mergerfs.strace-cp.txt)

Touch seemed to work fine. 
[mergerfs.strace-touch.txt](https://github.com/trapexit/mergerfs/files/6682583/mergerfs.strace-touch.txt)

Creating a random 5mb file does not:
# dd if=/dev/urandom of=test.txt bs=5MB count=1
dd: closing output file 'test.txt': Software caused connection abort
[mergerfs.strace-dd.txt](https://github.com/trapexit/mergerfs/files/6682590/mergerfs.strace-dd.txt)

Hope that helps. Shout if you need anything else.

**Comment by trapexit** [comment]
While I wasn't able to reproduce it before suddenly I can so we should be good. Now to figure out why the source and destination are the same.

**Comment by trapexit** [comment]
I think I found it. Looks like it was the result of a not fully initialized variable. Been there for a while so triggering it was probably based on bad luck and the specific build / compiler. I'll put out a patch release this week.

**Comment by no1knows** [comment]
Awesome, thanks so much!

**Comment by trapexit** [comment]
Thanks for the report.
