### ISSUE TITLE
trap divide error

### ISSUE THREAD

**Issue by kotarou3** [trapexit/mergerfs#925]
**Describe the bug**

**Version**: 2.31.0  
**Mount options**: allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=pfrd,minfreespace=102G,moveonenospc=true

When trying to create a new file when all branches are full (have less than `minfreespace` available), mergerfs aborts and leaves the mount point dangling.  
`dmesg` displays the error:
```
traps: mergerfs[1085] trap divide error ip:560e82579ee0 sp:7f70cb2cc118 error:0 in mergerfs[560e8253e000+52000]
```

This feels like a divide-by-zero bug in the `pfrd` implementation, but I haven't confirmed this

**To Reproduce**

1. Create some branches with a small amount of free space (<100G)
2. Mount the branches together with mergerfs with the above mount options
3. Try to create a file in the mergerfs mount point
4. mergerfs crashes with "trap divide error", and returns ECONNABORTED to the caller

**Expected behavior**

mergerfs simply returns ENOSPC to the caller and doesn't crash

**System information:**

 - OS, kernel version: 5.10.0-7-amd64
 - mergerfs version: 2.31.0
 - mergerfs settings: See mount options
 - List of drives, filesystems, & sizes: 3×18TB, 2×16TB, 24×6TB, 12×2TB all using BTRFS

**Comment by trapexit** [comment]
Found the issue. Must had assumed "X mod 0" wouldn't be an exception. Simple change. Will fix and put out a patch release.
