### ISSUE TITLE
Read-only branch writeable to existing files

### ISSUE THREAD

**Issue by eadwu** [trapexit/mergerfs#931]
**Describe the bug**

A directory (or branch is the terminology here I believe) explicitly mounted with (`=RO`) is writeable if the file already exists in that branch.

**To Reproduce**

Steps to reproduce the behavior. List **all** steps to reproduce. **All** settings.

```bash
MERGE_DIR="$(mktemp -d)"

cd "${MERGE_DIR}"
mkdir read-only read-write merged
touch read-only/a
echo a >> read-only/a

sudo mergerfs \
  -o allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs \
  -o posix_acl=true \
  "${MERGE_DIR}/read-only"=RO:"${MERGE_DIR}/read-write"=RW "${MERGE_DIR}/merged"

echo b > "${MERGE_DIR}/merged/a"
cat read-only/a # b

# Expected behavior
touch "${MERGE_DIR}/merged/b"
tree "${MERGE_DIR}" # exists under read-write
```

**Expected behavior**

`read-only/a`'s contents should not be changed.

**System information:**

 - OS, kernel version: Linux terrenus 5.13.2 #1-NixOS SMP PREEMPT Wed Jul 14 15:07:52 UTC 2021 x86_64 GNU/Linux
 - mergerfs version: mergerfs version: 2.32.6
 - mergerfs settings
 - List of drives, filesystems, & sizes:
   - `df -h`
   - `lsblk`
 - A strace of the application having a problem: 
   - `strace -fvTtt -s 256 -o /tmp/app.strace.txt <cmd>`
   - `strace -fvTtt -s 256 -o /tmp/app.strace.txt -p <appPID>`
 - strace of mergerfs while app tried to do it's thing:
   - `strace -fvTtt -s 256 -p <mergerfsPID> -o /tmp/mergerfs.strace.txt`

**Additional context**

I do read the following in the README:
```
mergerfs does NOT support the copy-on-write (CoW) or whiteout behaviors found in aufs and overlayfs. You can not mount a read-only filesystem and write to it. However, mergerfs will ignore read-only drives when creating new files so you can mix read-write and read-only drives. It also does NOT split data across drives. It is not RAID0 / striping. It is simply a union of other filesystems.
```

but I don't really know what the CoW behaviors are in overlayfs and aufs but the second sentence makes me think that this behavior shouldn't be possible.

If additional context is needed regarding the use-case, then mine is something that's probably really niche if not exclusive to myself right now since it has to do with NixOS. In a nutshell, NixOS doesn't follow the FHS setup as expected by the majority of distributions out there, which makes it terrible if I try to use something that isn't supported by NixOS.

As a simple example, an optimized PyTorch build is not available through the cache to download through NixOS, meaning any optimized PyTorch build (or even one with GPU support) needs to built from source.

As a bypass to that, I decided to try something that combines various technologies that I've had in mind for the past few months, virito-fs, chroots, and union filesystems. The idea is install another Linux distribution, in this case I chose `Arch Linux`, into some other subdirectory of the current drive. Then given a union filesystem, I can combine both distributions roots into a merged root directory for easy usage of software unsupported by the ideology of NixOS with none of the unnecessary overhead created by VMs or containers in isolation (without affecting any of the root distribution (in this case NixOS) files). 

While in my relatively simple overlays `overlayfs` would probably work as well, I use ZFS on my laptop (basically only for snapshots), and it appears that it isn't supported as an upper layer for overlayfs. While I think I remember reading virtio-fs is supported as an upper layer for overlayfs, there doesn't seem to be any applications for mounting host <-> host (basically in reverse to why it was actually created).

**Comment by eadwu** [comment]
Oh, this might be expected behavior 

I believe this is the same as https://github.com/trapexit/mergerfs/issues/642

**Comment by eadwu** [comment]
As a followup, is it possible to replicate the read-only behavior, CoW isn't needed, just that any files present on branches marked as RO to be read-only as expected.

This wouldn't be a problem in my approach since FHS systems install on `/usr/bin` and `/usr/local/bin` which basically don't exist on NixOS.

**Comment by trapexit** [comment]
Yes, this is expected behavior. If a file already exists there is no `create`. It's an `open`. Branch config is about the branch's use in policies. Not the files on it.

I'm not sure I understand what you mean. Replicate what behavior? The behavior that depends on a branch being read only is filtering it from create functions.  category.search=erofs of course will make things disappear. It returns the error EROFS. An error that doesn't make sense when doing a readonly behavior. 

You want the files on a branch marked RO for policy to be treated as readonly for writes? Why not mount it as readonly?

**Comment by eadwu** [comment]
Ah sorry, I remember reading that comment yesterday but I interpreted wrongly (late night brain) as making my system root mount as read-only which isn't what I wanted since I needed it to be writeable for normal usage.

`mount -o bind,remount,ro` is probably what was intended, an extra step but it should work fine for my usecase.

**Comment by trapexit** [comment]
Yeah, that's your best bet. I understand that's more work but is less error prone than me trying to catch every condition where writes could happen and having them return EROFS instead. I'd recommend still setting =RO on that branch as it is going to be slightly faster to see that set vs calling the syscall which returns the 'mounted as readonly' info. Not a big deal though.
