### ISSUE TITLE
Docker sees mergerfs mount as read-only

### ISSUE THREAD

**Issue by noisymime** [trapexit/mergerfs#934]
**Describe the bug**

Not sure if this is intended behaviour, but as it seems others using Docker don't have the same issue I thought I'd raise it. 
Whenever I try to create a Docker container (Doesn't appear to matter what container) and bind mount to the hosts mergerfs mounts, Docker reports that the file system is read-only.

Eg (/backup is the mergerfs mount):
`docker: Error response from daemon: error while creating mount source path '/backup/Video': mkdir /backup: read-only file system.`

I have tried every mount option combination I can see in the documentation but the error remains the same. Current fstab line is:
`/mnt/backup-* /backup fuse.mergerfs allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs,fsname=backup,direct_io`

Have tried with and without `direct_io`, all the `cache.files` values, with and without `dropcacheonclose` but the same error is received. 

Mount shows that the mergerfs point is mounted rw:
`backup on /backup type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)`

The user running Docker has permission to write to the folder I'm mounting (Have tried setting it to 777 just in case, no change)

**To Reproduce**

I am seeing this on even the most basic Docker run. Eg:
```
xxxx@shaftoe:~/tmp$ docker run --rm -it -v /backup:/mnt ubuntu:20.04
docker: Error response from daemon: error while creating mount source path '/backup': mkdir /backup: read-only file system.
```
If I mount directly to one of the drives, everything works fine:
```
xxxx@shaftoe:~/Projects/plex$ docker run --rm -it -v /mnt/backup-1:/mnt ubuntu:20.04
root@bc7f6605cb8d:/# 
```

**Expected behavior**

The filesystem is rw, but not seen this way by docker. 

**System information:**

 - OS, kernel version: Linux shaftoe 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - mergerfs version: mergerfs version: 2.31.0

**Comment by trapexit** [comment]
I assure you that it must be something with your setup as many people, including myself, bind mergerfs filesystems from their host into Docker (and other container runtimes) without issue.

I see nothing obviously wrong but you are using an extremely old version of mergerfs and I'd ask you first have an up to date setup before we investigate further.

**Comment by noisymime** [comment]
This is an out of the box Ubuntu 21.04 server setup, basically no changes other than the Docker group setup and mergerfs install. 

2.31.0 is from Oct last year, so I  wouldn't have thought it was extremely old, but I'll try upgrading and see if I get the same.

**Comment by trapexit** [comment]
Enough things change minor release to minor release to warrant the policy. Chasing issues possibly due to outdated software isn't a good use of time.

Regardless, as I said there is nothing odd from what you've shown me.  It works fine on my ubuntu 18.04 system:

```
$ mount  | grep /media
media on /media type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)

$ docker run -it --rm -v /media:/media ubuntu:20.04
root@d4dd89c90cc7:/# mount  | grep /media
/media on /media type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)

root@d4dd89c90cc7:/# touch /media/tmp/foo
root@d4dd89c90cc7:/# stat /media/tmp/foo
  File: /media/tmp/foo
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 30h/48d Inode: 14134499517909866612  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-07-23 01:41:37.290214906 +0000
Modify: 2021-07-23 01:41:37.290214906 +0000
Change: 2021-07-23 01:41:37.290214906 +0000
 Birth: -
root@d4dd89c90cc7:/# unlink /media/tmp/foo
root@d4dd89c90cc7:/#
```

**Comment by trapexit** [comment]
Have you tried expressly declaring the bind mount to be rw?

**Comment by noisymime** [comment]
I can't start the container to check. When this error is given the container creation fails and it drops straight back to the host. 

I'm just setting up a few Ubuntu VMs to try some different combinations now. Vanilla install of server 20.04, 21.04 and 21.04 with mergerfs updated to latest.

**Comment by trapexit** [comment]
Just tried on Ubuntu 20.04 system. Works as expected. What error do you get on start of the container?

**Comment by noisymime** [comment]
Gaah figured it out. The default docker installation on Ubuntu server is via the stupid snap container rather than a direct install. 

Confirmed on both 20.04 and 21.04 that removing the snap container version of docker and installing `docker.io` package directly solves the problem. 

Sorry to waste your time.

**Comment by trapexit** [comment]
no problem.

Does the snap install default mounts to readonly or something?

**Comment by noisymime** [comment]
I don't believe so, forcing the mount to be `rw` or `ro` made no difference. For whatever reason, docker running via snap sees the mergerfs mount as being read only and fails to create the container.

**Comment by noisymime** [comment]
If you want to reproduce:

```
apt-get remove docker.io
snap install docker
docker run --rm -it -v /media:/media:ro ubuntu:20.04
```
