### ISSUE TITLE
How to get mergerfs to use existing system inodes

### ISSUE THREAD

**Issue by shag00** [trapexit/mergerfs#943]
I am using Kubuntu 21.04 and mergerfs 2.31.  There is an issue with using baloo, the Kubuntu metadata file indexer, whereby the inode is changing which is preventing baloo from providing metedata information on files and causing it to re-index the file infinetly (each time an index is requested). It appears this issue is touched on in the readme but is just a little above my ability to comprehend fully.

An example of the same file accessed from 2 directories:
**scott@scottlounge:/mnt/pool/Entertainment/Documentaries/Movies**$ balooshow -x example.ts
3a100000031 49 929 example.ts: No index information found

**scott@scottlounge:/mnt/data/disk09/Entertainment/Documentaries/Movies**$ balooshow -x example.ts          
4ad000e00000891 2193 78446606 example.ts [/mnt/data/disk09/Entertainment/Documentaries/Movies/example.ts]
        Mtime: 1464926155 2016-06-03T11:55:55
        Ctime: 1627905699 2021-08-02T20:01:39
        Cached properties:
                Bitrate: 2937112
                Duration: 3540
                Width: 1280
                Height: 720
                Frame Rate: 25

Internal Info
Terms: Mmp2t Mvideo T3 X1-2937112 X26-1280 X27-720 X29-25 X3-3540
File Name Terms: $$correct$$
XAttr Terms:
bitRate: 2937112
duration: 3540
frameRate: 25
width: 1280
height: 720

This search shows the different inodes and the repeated indexing of the same file:
  baloosearch -i example.ts
    f3f600000031 /mnt/pool/Entertainment/Documentaries/Movies/example.ts
    f8c500000031 /mnt/pool/Entertainment/Documentaries/Movies/example.ts
    Elapsed: 0.997359 msecs

My fstab entry:
`/mnt/data/*	/mnt/pool	fuse.mergerfs	category.create=epmfs,defaults,allow_other,minfreespace=100G,fsname=pool 0 0`

**Comment by trapexit** [comment]
1) As the bug report and documentation recommend please use the latest release of mergerfs when reporting issues.
2) You aren't using `use_ino` option which is in likely every example and suggested in docs. Yes, it should probably be hard coded but that would be an incompatible change and I'll be doing so in the next major release.
3) The documentation discusses this topic in detail. https://github.com/trapexit/mergerfs#inodecalc The default is likely fine.

**Comment by shag00** [comment]
Thank you for your swift response though the results are the reverse of the previous situation. Previously the metadata was available only when seaching from the absolute address:
scott@scottlounge:/mnt/data/disk09/Entertainment/Documentaries/Movies/example.ts
and not when seraching from the pool address:
scott@scottlounge:/mnt/pool/Entertainment/Documentaries/Movies/example.ts

Now the metadata is only visible from the pool address and not the absolute address.

To refine my question, how do I make the metadata information visible from both the absolute and pool addresses concurrently?

**Comment by trapexit** [comment]
I'm not sure I understand why you want to do that. Regardless, without telling me how exactly this software identifies something I really can't provide you with any real advice. Inodes are not unique across the host so it doesn't make sense that it / you would use the inode value alone to identify a file. The filepaths are both absolute. mergerfs is a filesystem. Just because the files exist on a separate filesystem it doesn't mean it isn't an absolute value or that they aren't different files from the normal definition of what a unique file is within a system.

**Comment by trapexit** [comment]
As the docs show you can passthrough the inode if you wish.

**Comment by shag00** [comment]
You have done a great job with this software and I have been using it for years. This whole issue came about because of some issues with baloo. My last question was for completeness rather than of necessity. To an extent it's just a case of the ignorant (me) asking questions to the well versed (you), I did read your documents but to a large extent they could have been written in Chinese for all the help they were though for someone knowledgeable about programming they are no doubt very good.

What you told me in this chat was enough to give me an outcome that works for me, thanks!

**Comment by trapexit** [comment]
I'm not familiar with baloo and the website really doesn't explain how it indexes. I'd have to read the code to understand what it really is using to identify files uniquely. As I said the uniqueness of a file is not defined by the inode alone but assuming it is doing anything sane then in the least so long as the inode stays the same across mounts (which all inodecalc arguments do) you should be fine.
