### ISSUE TITLE
Workers from fstab mounted mergerfs pool running as non-root user

### ISSUE THREAD

**Issue by hwwilliams** [trapexit/mergerfs#949]
I've installed version 2.32.6 of mergerfs on Debian 11 and have configured the pool within fstab using the configuration options below:

```
/mnt/mergerfs/disks/mfs* /mnt/mergerfs/pool fuse.mergerfs defaults,allow_other,cache.files=partial,category.create=mfs,dropcacheonclose=true,func.getattr=newest,ignorepponrename=true,inodecalc=path-hash,minfreespace=200G,moveonenospc=mfs,noforget,threads=-2,use_ino,xattr=noattr 0 0
```

The mergerfs pool mounts fine and I can write to it but I've noticed that some of the worker threads shown in `htop` appear to be running as a system user. I have the Telegraf metric agent installed on the server and it creates a systems user during installation to run the metric agent service.

![image](https://user-images.githubusercontent.com/20447447/129841090-d13c8468-88ad-421c-9ba0-828e9d1e9ad1.png)

Is there somewhere else I should be specifying what user the workers should be running as?

**Comment by trapexit** [comment]
This is normal and expected. Nothing is wrong. It changes credentials as required. 

https://github.com/trapexit/mergerfs#its-mentioned-that-there-are-some-security-issues-with-mhddfs-what-are-they-how-does-mergerfs-address-them
