### ISSUE TITLE
Thank you for this awesome software!

### ISSUE THREAD

**Issue by antonical** [trapexit/mergerfs#960]
Just wanted to give a shout out for this awesome software. Totally transformed the way I deal with our exploding digital storage.

Been through most of the media servers out there. I just love the logical simplicity. Elegant solution to a set of real challenges. Thank you for the detailed documentation and for the mergerfs-tools. 

Been running now for a couple of years without any issues. mergerfs.balance is a great tool also.

Cheers
Tony

**Comment by trapexit** [comment]
Thank you for the support. 

If you want to discuss the software feel free over in the [discussions area](https://github.com/trapexit/mergerfs/discussions) or join us on [Discord](https://discord.gg/MpAr69V).
