### ISSUE TITLE
File system crashes

### ISSUE THREAD

**Issue by SHASHWATAA** [trapexit/mergerfs#965]
Version of mergerfs:mergerfs version: `2.32.3-61-g021ce3d (just installed)`

mergerfs settings / arguments: 

`command line`: `mergerfs -o allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.create=mfs /media/shash/disk1:/media/shash/disk2 /media/shash/Media`

`fstab`: `/media/shash/disk* /media/shash/Media fuse.mergerfs defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=250G,fsname=PlexDisk 0 0`

Version of the OS: `Linux DellTower 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

List of branches, their filesystem types, sizes (before and after issue): 
**before:**

```
/dev/sdb       ext4           3.6T  3.1T  392G  89% /media/shash/disk1
/dev/sdc1      fuseblk        3.7T  1.9T  1.9T  51% /media/shash/disk2
1:2            fuse.mergerfs  7.3T  4.9T  2.2T  69% /media/shash/Media
```

**after:**

```
/dev/sdb       ext4      3.6T  3.1T  392G  89% /media/shash/disk1
/dev/sdc1      fuseblk   3.7T  1.9T  1.9T  51% /media/shash/disk2
df: /media/shash/Media: Transport endpoint is not connected
```

All information about the relevant branches and paths: 
![image](https://user-images.githubusercontent.com/38054130/135199870-4e8cbf5b-b9f6-43f9-bef7-eb5679e619f3.png)

All information about the client app making the requests: sorry what should I provide here?

Runtime environment: nothing is running inside containers

A strace of the app having problems:
[app.strace.txt](https://github.com/trapexit/mergerfs/files/7249028/app.strace.txt)

A strace of mergerfs while the program is trying to do whatever it's failing to do:
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/7249095/mergerfs.strace.txt)

Precise directions on replicating the issue. Do not leave anything out.
App crashes within a few minutes after I run mount the combined drive. I've consistently made it crash by opening nzbget which has paths setup in the combined mergerfs drive. I've attached the strace as suggested in SUPPORT but it's my first time getting strace, let me know if you need anything else.

Try to recreate the problem in the simplest way using standard programs: ln, mv, cp, ls, dd, etc.
I can create small text files on the merged drives and it appears on one of the physical hard drive mount points. mv, cp all work fine as well.

I tried running it in the foreground and it's always crashing with this:
![image](https://user-images.githubusercontent.com/38054130/135207127-69cf6c61-bd93-48e9-aa6a-9a27e61416d8.png)

Then it comes up with Transport endpoint is not connected whenever anything tries to access the combined drives.

Looking up the error brings nothing but a [closed issue on GitHub on the fuse repo](https://github.com/libfuse/libfuse/issues/589).

**Comment by trapexit** [comment]
2.32.3-61-g021ce3d

Are you purposefully testing unreleased code?

**Comment by SHASHWATAA** [comment]
As much as I'd like to say yes I was helping debug the latest build, I didn't realise and was a mistake from my part. 
I was using unreleased code.

Thank you for such a quick responses and the awesome software!
