### ISSUE TITLE
Removing branches does not work

### ISSUE THREAD

**Issue by frederikrogge** [trapexit/mergerfs#980]
## Description

Ultimately, I want to delete pool I created and which consists of two branches. My plan was to first remove the two branches from the pool. I don't know if that is the best way to do it or if there is an easier solution. I tried running

`xattr -w user.mergerfs.branches -</hdd1 /media/drives/.mergerfs`

which should remove the branch /hdd1 from the pool at /media/drives according to the manual. 

## Expected behavior

Branch /hdd1 gets deleted from pool.

## Error

I get the following error message:

```
Fatal Python error: init_sys_streams: <stdin> is a directory, cannot continue
Python runtime state: core initialized

Current thread 0x00007fe2c86e3740 (most recent call first):
<no Python frame>
```

Any ideas? Thank you!

**Comment by trapexit** [comment]
Are you literally using this on the commandline? You have to escape the arguments.

Also... what is `-</hdd1` ? The instruction is just `-<` to remove the first branch. If you want to remove a specific branch then use `-/branch`

https://github.com/trapexit/mergerfs#usermergerfsbranches

**Comment by frederikrogge** [comment]
Thank you!
