### ISSUE TITLE
Failed drives disaster recovery

### ISSUE THREAD

**Issue by vvavepacket** [trapexit/mergerfs#981]
Lets say one of ny drives on mergerfs failed. Does mergerfs crashes or hangs?

What are the fail scenarios or will mergerfs withdtand it and continue working with the rest of remaining drives?

**Comment by trapexit** [comment]
mergerfs is a userspace app like literally any other. If the kernel would block another app it would block the mergerfs thread. If it returns an error then so does mergerfs. It entirely depends on what the kernel does.
