### ISSUE TITLE
Updatedb no longer working

### ISSUE THREAD

**Issue by Davikar** [trapexit/mergerfs#983]
**Describe the bug**

As of version 2.33.0, I can no longer get updatedb to work on a database that I have on the MergerFS volume (mounted at /storage).
Running `updatedb -l 0 -U /storage/davidius/ -o /storage/davidius/Temp/mlocate/mlocate.db`
Returns: updatedb: can not lock `/storage/davidius/Temp/mlocate/mlocate.db': Function not implemented
Going back to 2.32.6 makes it works again.

**System information:**
- Fedora Server 35
- Kernel 5.14.18

-MergerFS settings: defaults,noatime,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,hard_remove,func.getattr=newest,minfreespace=20G,moveonenospc=true,category.create=mspmfs,fsname=Storage,cache.statfs=60,cache.open=30,cache.symlinks=true,cache.readdir=true

Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         12G     0   12G   0% /dev
tmpfs            12G     0   12G   0% /dev/shm
tmpfs           4.7G  1.3M  4.7G   1% /run
/dev/sda3       433G  165G  247G  40% /
tmpfs            12G  8.3M   12G   1% /tmp
/dev/sda2       974M  191M  716M  22% /boot
/dev/sda1       400M  6.2M  394M   2% /boot/efi
/dev/sdg1       1.4T  1.4T   20G  99% /mnt/disk5
/dev/sde1       1.4T  1.4T   20G  99% /mnt/disk4
/dev/sdd1       7.3T  7.2T   20G 100% /mnt/disk2
/dev/sdc1       1.8T  1.8T   20G  99% /mnt/disk3
/dev/sdb1       7.3T  7.3T   19G 100% /mnt/disk1
/dev/sdf1       7.3T  3.9T  3.0T  57% /mnt/disk6
Storage          27T   23T  3.4T  88% /storage
tmpfs           2.4G     0  2.4G   0% /run/user/1001

NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda      8:0    0 465.8G  0 disk
├─sda1   8:1    0   400M  0 part /boot/efi
├─sda2   8:2    0     1G  0 part /boot
└─sda3   8:3    0   440G  0 part /
sdb      8:16   0   7.3T  0 disk
└─sdb1   8:17   0   7.3T  0 part /mnt/disk1
sdc      8:32   0   1.8T  0 disk
└─sdc1   8:33   0   1.8T  0 part /mnt/disk3
sdd      8:48   0   7.3T  0 disk
└─sdd1   8:49   0   7.3T  0 part /mnt/disk2
sde      8:64   1   1.4T  0 disk
└─sde1   8:65   1   1.4T  0 part /mnt/disk4
sdf      8:80   1   7.3T  0 disk
└─sdf1   8:81   1   7.3T  0 part /mnt/disk6
sdg      8:96   1   1.4T  0 disk
└─sdg1   8:97   1   1.4T  0 part /mnt/disk5
sdh      8:112  1     0B  0 disk
zram0  252:0    0     8G  0 disk [SWAP]

 - A strace of the application having a problem:
[app2.strace.txt](https://github.com/trapexit/mergerfs/files/7611160/app2.strace.txt)
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/7611161/mergerfs.strace.txt)
(Removed some sensitive information from the last one)

**Comment by trapexit** [comment]
Thanks for the report. I found the issue. Some refactoring... I missed telling the kernel I don't support locking and so it returns an error. I'll put out a release shortly.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/releases/tag/2.33.1

**Comment by moontide** [comment]
Also, Firefox and Thunderbird keeps saying it's already running and failed to start.

mergerfs 2.33.1 fixed it, firefox & thunderbird back to work.
