### ISSUE TITLE
Free space only from first drive mergerfs - 2.30.0-1

### ISSUE THREAD

**Issue by marc0janssen** [trapexit/mergerfs#987]
-- Mergerfs only shows free space from first drive.

**System information:**

 - OS, kernel version: Linux DS1513 3.10.108 #41890 SMP Fri Jun 25 02:39:14 CST 2021 x86_64 GNU/Linux synology_cedarview_1513+
 -
 - mergerfs version: 

mergerfs version: merge-with-ng-1131-gfe90b72b
FUSE library version: 2.9.7-mergerfs_2.30.0
fusermount version: 2.9.7-mergerfs_2.30.0
using FUSE kernel interface version 7.31

 - mergerfs settings
mergerfs -o nonempty,rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=mfs,dropcacheonclose=true /volume1/video:/volume2/video2 /volume1/mergerfs/video

Filesystem              Size  Used Avail Use% Mounted on
/dev/md0                2.3G  1.4G  845M  62% /
devtmpfs                2.0G     0  2.0G   0% /dev
tmpfs                   2.0G  124K  2.0G   1% /dev/shm
tmpfs                   2.0G   20M  2.0G   2% /run
tmpfs                   2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs                   2.0G  2.2M  2.0G   1% /tmp
/dev/mapper/cachedev_0  5.3T  2.0T  3.3T  38% /volume2
/dev/mapper/cachedev_1  7.9T  5.1T  2.9T  65% /volume1
shm                      64M     0   64M   0% /volume1/@docker/containers/60a88b6ecb9e7306bfe005bfcb042fcd443e146d43aabf87d792d38359a11b13/mounts/shm
1/video:2/video2         14T  7.1T  6.1T  54% /volume1/mergerfs/video

**Comment by trapexit** [comment]
According to what you show here it looks correct to me. 5.3+7.9 ~= 14. 2.0+5.1 ~= 7.1. 3.3+2.9 ~= 6.1.

**Comment by marc0janssen** [comment]
Yes seems so but macros reports 3TB

**Comment by trapexit** [comment]
You are going to have to provide more detail. What is "macros"? As the ticket template asks... you should include *all* relevant information. You provided a `df` output that shows the filesystem reporting the proper values.

**Comment by marc0janssen** [comment]
Found the issue..

I am running this on a Synology... With Entware.

when I create a "shared folder" as mount point  and point MergerFS to that mountpoint voor the combined volumes I get,

1. The correct free diskspace.
2. Errors when trying to view the setting for this "shared folder" if mergerfs is mounted
3. Errors  when using Hyperback
4. Errors when backup config from the configsccreen in Synology

When I create a "shared folder" but now create a folder in there and use that as a mountpoint for the combined volumes I get:

1. Incorrect free disk space (this is the free space voor the shared folder alone, hence the mount is on there)
2. NO Errors when trying to view the setting for this "shared folder" if mergerfs is mounted
3. NO Errors  when using Hyperback
4. NO Errors when backup config from the configsccreen in Synology

I know it walking on a thin line using this on a Synology... But is there a solution?

**Comment by trapexit** [comment]
I've zero experience with Synology. If something in the UI or whatever is reporting the size wrong you probably have things backwards. It's reporting the correct value for the wrong location. Not the wrong value for the correct location. I don't know anything about their software or setup so I really can't say how to resolve it.

**Comment by marc0janssen** [comment]
Ok I am on my own.... might find a solution.... thanks anyway! Have a nice day!

**Comment by trapexit** [comment]
You could try asking around some subreddits or something. homelab or datahoarders. I don't know where Synology folks hang out.

**Comment by marc0janssen** [comment]
Thanks!

**Comment by marc0janssen** [comment]
Hi Trapexit.... As I promised to find a solution.... here is one that works....

1. Configure mergerfs as noted in the wiki....
2. create a share in DSM ( I did "videom")
3. create a mount point in the Synology on /mnt (e.g. mkdir -p /mnt/videom)
4. do a bind mount between the two directories... (mount --bind /mnt/videom /volume1/videom)
5. INIT your desired MERGERFS with the mount on "/mnt/videom".

All problems with MERGERFS are done that way and you can still share it via DSM from Synology..

Here the script...  If you wish I could edit your WIKI-page for you to reflex the full solution.

HAPPY NEW YEAR!!

`
#!/bin/sh

echo "*** Init Mergerfs ***"

# Check and create mountpoint in /mnt 
if [ ! -d "/mnt/videom" ]; then
    mkdir -p /mnt/videom/
fi

# Mount --bind the two directories
mount --bind /mnt/videom/ /volume1/videom/

#start Mergerfs
modprobe fuse
/opt/bin/mergerfs -o nonempty,rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=mfs,dropcacheonclose=true /volume1/video:/volume2/video2 /mnt/videom
`

**Comment by trapexit** [comment]
Feel free.
