### ISSUE TITLE
NPM/Yarn install on some packages produces symlink error

### ISSUE THREAD

**Issue by Vija02** [trapexit/mergerfs#990]
**Describe the bug**

After updating to the new version `2.33.1`, I get an error message while running `yarn` or `npm install` about symlink. Downgrading to `2.32.6` fixes the issue.
Here's an example of the error with command `yarn add @babel/parser`:
```
yarn add v1.22.17
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, symlink '../@babel/parser/bin/babel-parser.js' -> '/home/vija02/debug/merged-test/test-yarn/node_modules/.bin/parser'".
info If you think this is a bug, please open a bug report with the information provided in "/home/vija02/debug/merged-test/test-yarn/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

It seem to occur only on packages that are structured as a workspace/monorepo. Eg: `@babel/parser`, `@chakra-ui/react`, `react`. Simple packages such as `is-odd`, `left-pad`, `axios` installs as expected.

**To Reproduce**
```
mkdir debug
cd debug

mkdir folder1
mkdir folder2
mkdir merged

mergerfs -o use_ino folder1/:folder2/ ./merged

cd merged
yarn add @babel/parser
```

Unfortunately, I'm not sure how to pinpoint the issue on npm/yarn itself.

**Expected behavior**

Install finishes without error

**System information:**

 - OS, kernel version: `uname -a`
 
 `Linux manjaro 5.4.163-1-MANJARO #1 SMP PREEMPT Wed Dec 1 14:47:09 UTC 2021 x86_64 GNU/Linux`

 - mergerfs version: `mergerfs -V`

`mergerfs version: 2.33.1`

~~- mergerfs settings~~
 - List of drives, filesystems, & sizes:
   - `df -h`
```
Filesystem      Size  Used Avail Use% Mounted on
dev              24G     0   24G   0% /dev
run              24G  2.2M   24G   1% /run
/dev/nvme0n1p2  200G  149G   41G  79% /
tmpfs            24G   66M   24G   1% /dev/shm
1:2             1.8T  1.3T  487G  73% /mnt/ssd-pooled
/dev/sdb1       916G  638G  232G  74% /mnt/ssd-mx500-1tb-1
/dev/sda1       343G  105G  222G  32% /mnt/ssd-sandisk-500gb
tmpfs            24G   69M   24G   1% /tmp
/dev/sdc1       916G  615G  256G  71% /mnt/ssd-mx500-1tb-2
/dev/nvme0n1p1  300M  312K  300M   1% /boot/efi
/dev/sdd1       394G  314G   81G  80% /mnt/f
tmpfs           4.7G   84K  4.7G   1% /run/user/1000
1:2             200G  149G   41G  79% /home/vija02/debug/merged
```
   - `lsblk`
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda           8:0    0 447.1G  0 disk 
├─sda1        8:1    0 349.5G  0 part /mnt/ssd-sandisk-500gb
├─sda2        8:2    0   512M  0 part 
├─sda3        8:3    0    16M  0 part 
└─sda4        8:4    0  94.1G  0 part 
sdb           8:16   0 931.5G  0 disk 
└─sdb1        8:17   0 931.5G  0 part /mnt/ssd-mx500-1tb-1
sdc           8:32   0 931.5G  0 disk 
└─sdc1        8:33   0 931.5G  0 part /mnt/ssd-mx500-1tb-2
sdd           8:48   0 698.6G  0 disk 
└─sdd1        8:49   0 393.7G  0 part /mnt/f
sde           8:64   1     0B  0 disk 
nvme0n1     259:0    0 238.5G  0 disk 
├─nvme0n1p1 259:1    0   300M  0 part /boot/efi
├─nvme0n1p2 259:2    0 203.7G  0 part /
└─nvme0n1p3 259:3    0  34.5G  0 part [SWAP]
```
 - A strace of the application having a problem: 
 
[app.strace.txt](https://github.com/trapexit/mergerfs/files/7728451/app.strace.txt)

 - strace of mergerfs while app tried to do it's thing:
 
[mergerfs.strace.txt](https://github.com/trapexit/mergerfs/files/7728425/mergerfstest.strace.txt)

**Additional context**

strace path does not match the reproduction steps exactly

**Comment by trapexit** [comment]
Thanks for the report. Found the issue. Simple fix. Will have a new build out shortly.

**Comment by trapexit** [comment]
Please try 2.33.2

**Comment by Vija02** [comment]
Looks great, thanks for the awesome work!

**Comment by willemw12** [comment]
As a side note:

Maybe add checks for these type of errors to `make test`?

Also, if `make test` would create some mount loop devices (with partitions tables and filesystems) to test with by default, that would make it easier (for others) to run those tests. And easier to run a wider range of tests, for example, "out of disk space" tests.

Just a thought.

**Comment by trapexit** [comment]
Of course it would be good to write tests for everything but

1. This was a very specific bug. I likely wouldn't have caught it anyway
2. Full integration testing requires running as root which isn't ideal.
3. Building out a framework to simplify integration tests would take a bunch of time and I've just not gotten to it.
4. Integration tests aren't ideal but refactoring the code to make filesystem sys calls abstract would be massive.
