### ISSUE TITLE
Missing 2.33.2 for Bullseye amd64?

### ISSUE THREAD

**Issue by tjedmunds** [trapexit/mergerfs#996]
Just wondering if there was an issue with today's new build for Debian Bullseye for the amd64 platform?

It seems to be missing.

Thanks for an awesome utility for my NAS!

**Comment by trapexit** [comment]
Looks like there is some build error on just that platform. I'll look into it.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/releases/tag/2.33.2

OK. Seems like it was intermittent. It built after retrying.

**Comment by tjedmunds** [comment]
Awesome, thanks for looking into it!
